// roster.js — the cast, their passages and their questions
// GENERATED by tools/import-book.mjs from bring-them-home.yml
// Hand edits are lost on the next import. Change the book.

export const ROSTER = [
  {
    "id": "reyes",
    "name": "Dr. Camila Reyes",
    "role": "Guidance Lead",
    "division": "NAV",
    "color": "#315c78",
    "bio": "<p>Sits at the front of the guidance row and owns what the room believes about where the vehicle is. Three tracking stations, a star sight and the crew's own inertial platform, and her job on a quiet shift is deciding which of them to trust when they stop agreeing.</p><p>Her first question about any apparent trajectory change is how many independent sources moved. One source moving is a measurement; every source moving is a spacecraft. She has watched this room spend two hours chasing a burn that turned out to be a station's clock.</p>",
    "quiz": [
      {
        "q": "How does Reyes tell a real trajectory change from a measurement artefact?",
        "a": "By seeing whether independent sources moved, or only one",
        "wrong": [
          "By re-running the same navigation solution with much tighter tolerances",
          "By waiting for the next scheduled navigation update",
          "By comparing the result against the pre-launch plan"
        ]
      }
    ]
  },
  {
    "id": "shah",
    "name": "Priya Shah",
    "role": "Power Systems Lead",
    "division": "ELEC",
    "color": "#9a741d",
    "bio": "<p>Keeps the electrical picture for the whole vehicle, which on this flight is one battery stack, two fuel cells and a long list of things that would like to draw from them.</p><p>She will not look at a voltage on its own. Voltage, current and the heat coming off a component are the same energy accounted for three ways, and a fault that hides in one of them is usually plain in another. A bus holding its voltage while running warm is spending something, and the question is what.</p>",
    "quiz": [
      {
        "q": "Why does Shah read voltage, current and heat as one system?",
        "a": "They are three views of one energy budget",
        "wrong": [
          "Three separate instruments together are more accurate than any one of them",
          "Heat is the only quantity that can be measured directly in flight",
          "The three meters share a single power supply"
        ]
      }
    ]
  },
  {
    "id": "brooks",
    "name": "Dr. Aaron Brooks",
    "role": "Thermal and Life Support Lead",
    "division": "THERM",
    "color": "#4b775f",
    "bio": "<p>Answers for the air the crew breathes and the heat the vehicle has to throw away, both of which are transport problems before they are anything else.</p><p>His standing objection is that a powered box is not a working box. Current reaching a fan says the motor is turning, not that air is moving through the duct behind it. What he asks for is the transport itself — a flow, a temperature difference, a carbon dioxide reading coming down — and he has been shown telemetry proving a scrubber was running while the cabin said it was not.</p>",
    "quiz": [
      {
        "q": "What does Brooks mean by asking whether hardware is transporting what it should?",
        "a": "Power to a fan is not proof that air is moving",
        "wrong": [
          "Hardware telemetry becomes unreliable during a power-down and cannot be trusted",
          "Transport rates can only be measured on the ground",
          "The crew cannot hear whether a fan is running"
        ]
      }
    ]
  },
  {
    "id": "ito",
    "name": "Naomi Ito",
    "role": "Communications Lead",
    "division": "COMMS",
    "color": "#704f88",
    "bio": "<p>Owns the link, which for the next four days means one high-gain antenna, two ground stations and a spacecraft that is slowly rotating.</p><p>Received power is where everybody looks first and the reading she trusts least on its own. A weak signal can be an antenna pointing off, the range opening, or a transmitter failing, and all three arrive at the receiver looking the same. What separates them is whatever else moved at that moment: attitude, range rate, the temperature at the amplifier.</p>",
    "quiz": [
      {
        "q": "Why does Ito treat received power as only part of a link diagnosis?",
        "a": "Pointing, range and a transmitter fault all look the same in it",
        "wrong": [
          "Received power is sampled too slowly to be useful during a fast fade",
          "Power readings are quantised too coarsely at long range",
          "Only frequency measurements are calibrated"
        ]
      }
    ]
  },
  {
    "id": "mensah",
    "name": "Kwame Mensah",
    "role": "Dynamics and Structures Lead",
    "division": "STRUCT",
    "color": "#9a3f36",
    "bio": "<p>Reads the accelerometers, which means he spends a flight arguing that how hard something is shaken matters less than how fast.</p><p>A panel takes up a shake hardest when the rate it is shaken at matches the rate it wants to ring at, and the same force applied away from that rate is felt and forgotten. So the number he wants first is a rate rather than an amplitude: a thruster pulsing at four hertz into a panel that rings at four hertz is a different event from the same thruster at twenty.</p>",
    "quiz": [
      {
        "q": "Why does Mensah care about the frequency something is shaken at, not just how hard?",
        "a": "A structure answers strongly only near its own natural frequency",
        "wrong": [
          "Forcing at high frequency always does more damage than forcing at low frequency",
          "Frequency determines how far the vibration travels through the hull",
          "Accelerometers only respond above a threshold frequency"
        ]
      }
    ]
  },
  {
    "id": "carter",
    "name": "Dr. Evelyn Carter",
    "role": "Mission Integration Lead",
    "division": "INTEG",
    "color": "#3d6f52",
    "bio": "<p>Sits at the back of the room where the recommendations arrive, and is the last person to say yes. Eleven missions, two of which she stopped.</p><p>What she looks for is not agreement but independence. Two instruments sharing a power supply, a calibration or a line of software can be wrong together and confident together, and a room reading them side by side hears that as confirmation. Her question is always which step the two answers have in common.</p>",
    "quiz": [
      {
        "q": "What is Carter guarding against by demanding independent evidence?",
        "a": "Two instruments sharing a step can be wrong together",
        "wrong": [
          "Crew reports become unreliable when the people making them are under stress",
          "A single instrument cannot be calibrated in flight",
          "Independent teams work faster than one large team"
        ]
      }
    ]
  },
  {
    "id": "whitaker",
    "name": "Dale Whitaker",
    "role": "Trajectory Officer",
    "division": "NAV",
    "color": "#315c78",
    "bio": "<p>Fits trajectories to whatever tracking exists, which on a bad shift is three numbers taken hours apart. A fit that matches the data he has is easy; a fit that predicts the next observation is the only kind he will sign.</p><p>He treats residuals as the real output. A pattern in what the model got wrong points at an unmodelled force or a clock error, and both of those have hidden themselves inside a good-looking fit before.</p>",
    "quiz": [
      {
        "q": "Why does Whitaker judge a trajectory fit by its residuals rather than by how closely it matches the tracking?",
        "a": "Structure in the errors shows a force or a clock the fit is hiding",
        "wrong": [
          "Residuals are the only quantity the tracking stations report back to the room",
          "A fit with small residuals always has small uncertainty",
          "Residuals convert range measurements into velocity"
        ]
      }
    ]
  },
  {
    "id": "ferreira",
    "name": "Ana Ferreira",
    "role": "Electrical Load Officer",
    "division": "ELEC",
    "color": "#9a741d",
    "bio": "<p>Keeps the power budget, which during this flight means keeping a list of everything aboard that consumes energy and what happens the hour after it is switched off.</p><p>Her rule is that no load is switched off in isolation. A heater turned off to save amp-hours becomes a thermal problem that costs more amp-hours to reverse, and the ledger has to be kept across systems rather than within one.</p>",
    "quiz": [
      {
        "q": "Why does Ferreira refuse to evaluate a load in isolation?",
        "a": "Switching one off moves the cost somewhere else",
        "wrong": [
          "Every load aboard draws the same current",
          "Loads can only be measured while the fuel cells are running",
          "A load's cost is fixed by its rating rather than by its use"
        ]
      }
    ]
  },
  {
    "id": "novak",
    "name": "Petra Novak",
    "role": "Life Support Engineer",
    "division": "THERM",
    "color": "#4b775f",
    "bio": "<p>Works the three things a sealed cabin runs out of — heat, breathable gas and water — and the ways they interfere with each other. Cooling the cabin condenses water onto the coldest surfaces, and the coldest surfaces are usually the electronics.</p><p>She measures in more than one place on principle. A single cabin sensor reports the air beside itself, and a compartment with poor circulation can be perfectly comfortable at the sensor and dangerous two metres away.</p>",
    "quiz": [
      {
        "q": "Why does Novak insist on carbon dioxide readings from several cabin locations?",
        "a": "With poor circulation the gas is not uniform, so a sensor reads its own corner",
        "wrong": [
          "Sensors drift too quickly to be trusted individually",
          "The crew cannot reach the primary sensor while the module is powered down for the test",
          "Multiple readings are averaged to remove instrument noise"
        ]
      }
    ]
  },
  {
    "id": "haldane",
    "name": "Marcus Haldane",
    "role": "Link Analyst",
    "division": "COMMS",
    "color": "#704f88",
    "bio": "<p>Accounts for every decibel between the spacecraft transmitter and the ground receiver. A fade is never mysterious to him; it is one term in a budget that changed, and the work is finding which.</p><p>Range, antenna pointing, receiver bandwidth and transmitter health all reduce the same received power, and they are told apart by what else changed at the same moment rather than by the signal level itself.</p>",
    "quiz": [
      {
        "q": "How does Haldane separate a pointing problem from a transmitter failure?",
        "a": "By what changed alongside it — attitude, range and schedule leave traces",
        "wrong": [
          "A transmitter failure always removes the carrier completely",
          "Pointing errors change the frequency and failures do not",
          "The received power alone identifies the cause without any other measurement"
        ]
      }
    ]
  },
  {
    "id": "okoye",
    "name": "Chidi Okoye",
    "role": "Structural Dynamics Engineer",
    "division": "STRUCT",
    "color": "#9a3f36",
    "bio": "<p>Studies how a spacecraft responds to being pushed at particular rates. A structure has frequencies at which a small repeated force produces a large motion, and hardware that is perfectly strong at rest can fail there.</p><p>He never accepts a single accelerometer as a description of a mode. One sensor sits at one point, and a point that happens to sit at a node reads almost nothing while the panel beside it moves.</p>",
    "quiz": [
      {
        "q": "Why will Okoye not characterise a vibration mode from one accelerometer?",
        "a": "At a still point of that mode there is nothing to feel",
        "wrong": [
          "Accelerometers cannot measure below one hertz",
          "A single sensor cannot record frequency, only amplitude",
          "One sensor is enough only if the pump speed is constant"
        ]
      }
    ]
  },
  {
    "id": "lindqvist",
    "name": "Erika Lindqvist",
    "role": "Flight Dynamics Integrator",
    "division": "INTEG",
    "color": "#3d6f52",
    "bio": "<p>Sits between the back rooms and the loop, and her job is the one nobody else has: deciding which of six correct answers the flight director hears first.</p><p>She keeps the anomaly log, because in a fast failure the expensive mistake is not a wrong number but two rooms acting on different versions of the same number an hour apart.</p>",
    "quiz": [
      {
        "q": "What does Lindqvist treat as the main risk during a fast-moving failure?",
        "a": "Two teams working from figures that disagree",
        "wrong": [
          "A back room refusing to give an estimate at all",
          "The crew asking questions over the loop",
          "Telemetry arriving faster than it can be plotted"
        ]
      }
    ]
  }
];

export const LEADERS = [
  {
    "id": "reyes",
    "name": "Dr. Camila Reyes",
    "role": "Guidance Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "shah",
    "name": "Priya Shah",
    "role": "Power Systems Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "brooks",
    "name": "Dr. Aaron Brooks",
    "role": "Thermal and Life Support Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "ito",
    "name": "Naomi Ito",
    "role": "Communications Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "mensah",
    "name": "Kwame Mensah",
    "role": "Dynamics and Structures Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "carter",
    "name": "Dr. Evelyn Carter",
    "role": "Mission Integration Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  }
];

export const AVATARS = {};
