// Earth & Sky — 7 Casebook game STRUCTURES (design only: mystery + board + informants + 18-figure roster).
// Same shape as one GAMES element in generate_more.js. Prose (profiles/quizzes) authored elsewhere.
// Spine per game: OVERCLAIM (sensational-wrong) / DISMISSAL (act-of-God) / TRUTH (concealed systemic warning-system failure).
// Rosters: 18 real, accurately-matched figures each; all unique across the 7 games; none in batch/used_figures.txt.

module.exports = [

// 1 ── EARTHQUAKE EARLY-WARNING FAILURE ────────────────────────────────────────
{ id:"e_quake", title:"Nine Seconds to Cordera", discipline:"Seismology & Earthquake Science",
  teaser:"A city shook awake at dawn with no alarm and no seconds to run. A secret underground blast? A quake beyond all odds? Or a warning system quietly switched off?",
  overclaimTag:"a secret blast or weapon", truthTag:"a silenced early-warning network",
  venue:"the Cordera earthquake inquiry", agent:"Investigator Mara Solveig", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Seismology Pioneers", dossierName:"SEISMOLOGY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Cordera earthquake inquiry",
  who:{truth:"director", items:[["director","Roan Vesk — seismic-network director"],["seismologist","The state seismologist"],["engineer","The building-code engineer"]]},
  where:{truth:"office", items:[["fault","The Fault Line & Sensor Sites"],["warncenter","The Alert Operations Centre"],["office","The Network's Budget Office"]]},
  what:{truth:"silenced", overclaim:"blast", dismissal:"freak", items:[["blast","A secret underground blast or weapon"],["freak","A freak quake beyond all odds — an act of God"],["silenced","A defunded sensor network & a buried risk map"]]},
  places:["fault","warncenter","office"],
  chars:[["fieldtech","Field Tech Odile","Seismic field technician","📡","O","the fault sites","Services the sensors; logged the ones that went dark and were never repaired."],
         ["dutyofficer","The Duty Officer","Alert-centre duty officer","🚨","D","the alert centre","Sat the desk that dawn; the alert was written but never sent."],
         ["clerk","The Clerk","Budget-office clerk","🗂","C","the office","Keeps the funding files — and the risk map stamped and shelved."]],
  topics:[["mallet","Robert Mallet (1810-1881)","The founding of seismology"],["milne","John Milne (1850-1913)","The modern seismograph"],
    ["wiechert","Emil Wiechert (1861-1928)","The seismograph & Earth's interior"],["omori","Fusakichi Omori (1868-1923)","Omori's law of aftershocks"],
    ["reid","Harry Fielding Reid (1859-1944)","Elastic rebound & fault rupture"],["moho","Andrija Mohorovičić (1857-1936)","The crust-mantle boundary"],
    ["gutenberg","Beno Gutenberg (1889-1960)","Earth's core & the magnitude scale"],["jeffreys","Harold Jeffreys (1891-1989)","Travel times & the liquid core"],
    ["bullen","Keith Bullen (1906-1976)","The layered model of the Earth"],["wadati","Kiyoo Wadati (1902-1995)","Deep earthquakes & the dipping zone"],
    ["byerly","Perry Byerly (1897-1978)","First motions & fault planes"],["press","Frank Press (1924-2020)","Surface waves & the deep Earth"],
    ["kanamori","Hiroo Kanamori (b. 1936)","The moment magnitude scale"],["aki","Keiiti Aki (1930-2005)","Seismic moment & the earthquake source"],
    ["hanks","Thomas C. Hanks (b. 1944)","Strong ground motion & stress drop"],["housner","George W. Housner (1910-2008)","Earthquake engineering & response spectra"],
    ["cornell","C. Allin Cornell (1938-2007)","Probabilistic seismic hazard"],["mogi","Kiyoo Mogi (1929-2021)","Earthquake prediction & precursors"]],
},

// 2 ── HURRICANE / TORNADO FORECAST-AND-WARNING BREAKDOWN ──────────────────────
{ id:"e_storm", title:"The Halloway Landfall", discipline:"Meteorology & Storm Forecasting",
  teaser:"A killer storm came ashore on a coast that was told to stay. A weapon in the clouds? A freak of nature no one could foresee? Or a warning someone chose to soften?",
  overclaimTag:"weather as a weapon", truthTag:"a downgraded storm warning",
  venue:"the Halloway storm inquiry", agent:"Investigator Cole Renard", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Meteorology Pioneers", dossierName:"METEOROLOGY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halloway storm inquiry",
  who:{truth:"official", items:[["official","Delia Marsh — regional emergency-management chief"],["forecaster","The lead hurricane forecaster"],["mayor","The resort-town mayor"]]},
  where:{truth:"office", items:[["coast","The Coast & Tide Gauges"],["forecastfloor","The Hurricane Forecast Floor"],["office","The Emergency-Management Office"]]},
  what:{truth:"downgraded", overclaim:"weapon", dismissal:"freak", items:[["weapon","Weather turned into a weapon"],["freak","A freak storm no forecast could catch — an act of God"],["downgraded","A warning downgraded to protect the season & the vote"]]},
  places:["coast","forecastfloor","office"],
  chars:[["spotter","Storm Spotter Vane","Volunteer storm spotter","🌀","V","the coast","Called in the wind rising fast; the surge was already over the road."],
         ["radar","The Radar Analyst","Radar analyst","📡","R","the forecast floor","Watched the eye close on the coast; the warning on screen was pulled back."],
         ["clerk","The Clerk","Emergency-office clerk","🗂","C","the office","Keeps the call logs — and the order that softened the evacuation."]],
  topics:[["beaufort","Francis Beaufort (1774-1857)","The wind-force scale"],["coriolis","Gaspard-Gustave de Coriolis (1792-1843)","The Coriolis effect"],
    ["ferrel","William Ferrel (1817-1891)","The circulation of the atmosphere"],["abbe","Cleveland Abbe (1838-1916)","The first weather forecasts"],
    ["shaw","Napier Shaw (1854-1945)","Dynamic meteorology & the upper air"],["vbjerknes","Vilhelm Bjerknes (1862-1951)","The equations of weather prediction"],
    ["bergeron","Tor Bergeron (1891-1977)","The Bergen school & precipitation"],["jbjerknes","Jacob Bjerknes (1897-1975)","Fronts & the life of cyclones"],
    ["rossby","Carl-Gustaf Rossby (1898-1957)","Rossby waves & the jet stream"],["petterssen","Sverre Petterssen (1898-1974)","Weather analysis & forecasting"],
    ["wexler","Harry Wexler (1911-1962)","Hurricanes & weather satellites"],["rsimpson","Robert Simpson (1912-2014)","The Saffir-Simpson hurricane scale"],
    ["saffir","Herbert Saffir (1917-2007)","Hurricane wind & structural damage"],["charney","Jule Charney (1917-1981)","Numerical weather prediction"],
    ["lorenz","Edward Lorenz (1917-2008)","Chaos & the limits of prediction"],["fujita","Tetsuya Ted Fujita (1920-1998)","The tornado intensity scale"],
    ["jsimpson","Joanne Simpson (1923-2010)","Hurricane structure & cloud towers"],["atlas","David Atlas (1924-2015)","Radar meteorology & storm detection"]],
},

// 3 ── FLASH-FLOOD DISASTER (DAM-RELEASE / URBAN) ──────────────────────────────
{ id:"e_flood", title:"The Rossmere Flood", discipline:"Hydrology & Flood Science",
  teaser:"A wall of water took a canyon town in the dark. A dam blown open on purpose? A rain beyond any record? Or gauges gone silent and a flood map locked in a drawer?",
  overclaimTag:"sabotage of the dam", truthTag:"an ignored flood-gauge network",
  venue:"the Rossmere flood inquiry", agent:"Inspector Tomasz Bey", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Hydrology Pioneers", dossierName:"HYDROLOGY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Rossmere flood inquiry",
  who:{truth:"manager", items:[["manager","Elias Thorn — reservoir operations manager"],["hydrologist","The county hydrologist"],["planner","The floodplain planner"]]},
  where:{truth:"office", items:[["gauges","The Creek & Gauge Stations"],["controlroom","The Dam Control Room"],["office","The Water District Office"]]},
  what:{truth:"ignored", overclaim:"sabotage", dismissal:"freak", items:[["sabotage","The dam blown open by sabotage"],["freak","A thousand-year rain no one could plan for — an act of God"],["ignored","A silenced gauge network & a buried floodplain study"]]},
  places:["gauges","controlroom","office"],
  chars:[["gaugekeeper","Gauge Keeper Wynn","Stream-gauge keeper","💧","W","the gauge stations","Reads the creek gauges; the upstream ones stopped reporting weeks back."],
         ["operator","The Gate Operator","Dam gate operator","🎚","G","the control room","Worked the release gates; the order came late and came big."],
         ["clerk","The Clerk","Water-district clerk","🗂","C","the office","Keeps the studies — including the flood map that was never released."]],
  topics:[["dbernoulli","Daniel Bernoulli (1700-1782)","Hydrodynamics & Bernoulli's principle"],["mulvaney","Thomas Mulvaney (1822-1892)","The rational method for peak flow"],
    ["kuichling","Emil Kuichling (1848-1919)","Urban storm drainage & runoff"],["newell","Frederick H. Newell (1862-1932)","Stream gauging & the hydrographic survey"],
    ["sherman","LeRoy K. Sherman (1869-1954)","The unit hydrograph"],["hurst","Harold Edwin Hurst (1880-1978)","Long-term storage & flood records"],
    ["bakhmeteff","Boris Bakhmeteff (1880-1951)","Open-channel hydraulics"],["keulegan","Garbis Keulegan (1890-1989)","Hydraulics & channel flow"],
    ["snyder","Franklin F. Snyder (hydrologist)","The synthetic unit hydrograph"],["langbein","Walter B. Langbein (1907-1982)","Statistical hydrology & runoff"],
    ["white","Gilbert F. White (1911-2006)","Floodplain management & flood risk"],["leopold","Luna Leopold (1915-2006)","River channels & fluvial geomorphology"],
    ["linsley","Ray K. Linsley (1917-1990)","Hydrologic forecasting"],["nash","James E. Nash (1927-1998)","The instantaneous unit hydrograph"],
    ["ippen","Arthur T. Ippen (1907-1974)","Hydraulics & flood routing"],["maddock","Thomas Maddock Jr. (hydrologist)","The hydraulic geometry of rivers"],
    ["haeinstein","Hans Albert Einstein (1904-1973)","Sediment transport in rivers"],["vanoni","Vito Vanoni (1904-1999)","River sedimentation"]],
},

// 4 ── TSUNAMI WARNING FAILURE ─────────────────────────────────────────────────
{ id:"e_tsunami", title:"The Sable Point Wave", discipline:"Tsunami Science & Oceanography",
  teaser:"The sea drew back, then took the shore. A weapon beneath the waves? A freak swell out of nowhere? Or a warning network left to rust and a hazard waved away?",
  overclaimTag:"a blast beneath the sea", truthTag:"a neglected warning-buoy network",
  venue:"the Sable Point tsunami inquiry", agent:"Investigator Ravi Enns", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Tsunami-Science Pioneers", dossierName:"TSUNAMI-SCIENCE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Sable Point tsunami inquiry",
  who:{truth:"chief", items:[["chief","Nadia Voss — tsunami warning-centre chief"],["oceanographer","The duty oceanographer"],["portauthority","The port authority director"]]},
  where:{truth:"office", items:[["shore","The Shore & Tide Stations"],["watchfloor","The Tsunami Warning Centre"],["office","The Warning Programme Office"]]},
  what:{truth:"neglected", overclaim:"blast", dismissal:"freak", items:[["blast","A blast or weapon beneath the sea"],["freak","A freak wave from nowhere — an act of God"],["neglected","A disabled buoy network & a downplayed hazard"]]},
  places:["shore","watchfloor","office"],
  chars:[["buoytech","Buoy Tech Sana","Ocean-buoy technician","🛟","S","the shore stations","Services the sea buoys; half the network had flatlined and stayed down."],
         ["watchstander","The Watchstander","Warning-centre watchstander","🌊","W","the watch floor","Held the desk when the quake hit; the bulletin sat unissued."],
         ["clerk","The Clerk","Programme-office clerk","🗂","C","the office","Keeps the maintenance logs — and the hazard study that was toned down."]],
  topics:[["laplace","Pierre-Simon Laplace (1749-1827)","The dynamical theory of tides"],["airy","George Biddell Airy (1801-1892)","Wave theory & the tides"],
    ["lamb","Horace Lamb (1849-1934)","Hydrodynamics & water waves"],["nansen","Fridtjof Nansen (1861-1930)","Ocean currents & polar seas"],
    ["love","Augustus E. H. Love (1863-1940)","Elastic waves & Earth tides"],["sverdrup","Harald Sverdrup (1888-1957)","Physical oceanography & wave forecasting"],
    ["proudman","Joseph Proudman (1888-1975)","Dynamical oceanography & tides"],["doodson","Arthur Doodson (1890-1968)","Tidal prediction & storm surge"],
    ["shepard","Francis Parker Shepard (1897-1985)","Marine geology & tsunami deposits"],["ewing","Maurice Ewing (1906-1974)","Marine seismology & tsunami sources"],
    ["cox","Doak Cox (1917-2003)","Tsunami research & the Pacific warning system"],["munk","Walter Munk (1917-2019)","Ocean waves & their forecasting"],
    ["vandorn","William Van Dorn (1919-2018)","Tsunami hydrodynamics & wave runup"],["iida","Kumizi Iida (tsunami seismologist)","Tsunami magnitude & catalogs"],
    ["kajiura","Kinjiro Kajiura (tsunami hydrodynamicist)","Tsunami source & propagation"],["wyrtki","Klaus Wyrtki (1925-2013)","Sea level & the Pacific warning centre"],
    ["ebernard","Eddie Bernard (tsunami-warning oceanographer)","The DART deep-ocean buoy network"],["titov","Vasily Titov (tsunami modeler)","Tsunami forecast modeling"]],
},

// 5 ── WILDFIRE CATASTROPHE ────────────────────────────────────────────────────
{ id:"e_wildfire", title:"The Pinehaven Fire", discipline:"Wildfire & Combustion Science",
  teaser:"A firestorm erased a mountain town in an afternoon. Arson on the wind? A blaze beyond anything nature had shown? Or fuel left to pile up and an evacuation held too long?",
  overclaimTag:"coordinated arson", truthTag:"deferred fuel management",
  venue:"the Pinehaven wildfire inquiry", agent:"Investigator June Alaric", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Wildfire-Science Pioneers", dossierName:"WILDFIRE-SCIENCE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Pinehaven wildfire inquiry",
  who:{truth:"chief", items:[["chief","Garrett Pyle — forest district fire chief"],["fbehavior","The fire-behavior analyst"],["sheriff","The county sheriff"]]},
  where:{truth:"office", items:[["ridge","The Ridge & Fuel Breaks"],["firecamp","The Incident Command Post"],["office","The Forest District Office"]]},
  what:{truth:"deferred", overclaim:"arson", dismissal:"freak", items:[["arson","A coordinated arson attack"],["freak","A freak firestorm nothing could stop — an act of God"],["deferred","Deferred fuel clearing & a delayed evacuation order"]]},
  places:["ridge","firecamp","office"],
  chars:[["lookout","Lookout Wren","Fire lookout","🔭","W","the ridge","Spotted the first smoke; watched the brush no one had cleared catch and run."],
         ["dispatcher","The Dispatcher","Incident dispatcher","📻","D","the command post","Ran the radios; the evacuation call was held while the fire jumped the line."],
         ["clerk","The Clerk","District-office clerk","🗂","C","the office","Keeps the burn plans — and the fuel-reduction work that was cut from the budget."]],
  topics:[["zeldovich","Yakov Zeldovich (1914-1987)","Flame propagation & combustion theory"],["blewis","Bernard Lewis (1899-1993)","Flames, combustion & explosions"],
    ["emmons","Howard Emmons (1912-1998)","The physics of fire"],["gisborne","Harry Gisborne (1893-1949)","Fire-danger measurement"],
    ["fons","William Fons (fire scientist)","Modeling the spread of fire"],["byram","George Byram (1909-1996)","Fireline intensity & fire behavior"],
    ["countryman","Clive Countryman (fire scientist)","The fire environment & fire weather"],["mcarthur","Alan McArthur (1923-1978)","The forest fire-danger meter"],
    ["rothermel","Richard Rothermel (1929-2023)","The fire-spread model"],["vanwagner","Charles Van Wagner (1925-2004)","Crown fire & fire intensity"],
    ["biswell","Harold Biswell (1905-1992)","Prescribed burning & fuel management"],["stoddard","Herbert Stoddard (1889-1970)","Fire ecology & controlled burns"],
    ["pyne","Stephen Pyne (b. 1949)","The history of wildfire"],["cohen","Jack Cohen (fire scientist)","The home-ignition zone"],
    ["fwilliams","Forman Williams (b. 1934)","Combustion theory"],["drysdale","Dougal Drysdale (fire scientist)","Fire dynamics"],
    ["quintiere","James Quintiere (fire scientist)","Flame spread & fire growth"],["babrauskas","Vytenis Babrauskas (fire scientist)","Ignition & heat release"]],
},

// 6 ── ASTEROID / NEAR-EARTH-OBJECT IMPACT-HAZARD COVER-UP ─────────────────────
{ id:"e_asteroid", title:"The Hollow Vale Impact", discipline:"Planetary Defense & Impact Science",
  teaser:"A fireball flattened a valley without a moment's warning. A weapon fallen from orbit? A once-in-an-age freak of the heavens? Or a rock that was seen coming and quietly filed away?",
  overclaimTag:"a weapon from orbit", truthTag:"a downplayed impact detection",
  venue:"the Hollow Vale impact inquiry", agent:"Investigator Neve Ostrander", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Planetary-Defense Pioneers", dossierName:"PLANETARY-DEFENSE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Hollow Vale impact inquiry",
  who:{truth:"director", items:[["director","Sabine Verhoeven — sky-survey programme director"],["astronomer","The duty astronomer"],["official","The civil-defence official"]]},
  where:{truth:"office", items:[["crater","The Impact Crater & Fall Field"],["observatory","The Survey Observatory"],["office","The Survey Programme Office"]]},
  what:{truth:"downplayed", overclaim:"weapon", dismissal:"freak", items:[["weapon","A weapon dropped from orbit"],["freak","A freak bolt from the blue — an act of God"],["downplayed","A downplayed detection & a defunded sky survey"]]},
  places:["crater","observatory","office"],
  chars:[["observer","Night Observer Kade","Survey night observer","🔭","K","the observatory","Ran the sky survey; the object was on the plates before it fell."],
         ["orbit","The Orbit Analyst","Orbit-computation analyst","🛰","O","the data room","Ran the numbers; the collision course was flagged and then walked back."],
         ["clerk","The Clerk","Programme-office clerk","🗂","C","the office","Keeps the survey logs — and the funding cut that blinded the sky watch."]],
  topics:[["chladni","Ernst Chladni (1756-1827)","Meteorites & their cosmic origin"],["barringer","Daniel Barringer (1860-1929)","Meteor Crater & impact origin"],
    ["opik","Ernst Öpik (1893-1985)","Near-Earth asteroids & meteors"],["kuiper","Gerard Kuiper (1905-1973)","The small bodies of the solar system"],
    ["whipple","Fred Whipple (1906-2004)","Comets & the dirty snowball"],["lalvarez","Luis Alvarez (1911-1988)","The impact & the mass extinction"],
    ["baldwin","Ralph Baldwin (1912-2010)","Craters as impact scars"],["gehrels","Tom Gehrels (1925-2011)","The Spacewatch survey for asteroids"],
    ["gshoemaker","Eugene Shoemaker (1928-1997)","Impact cratering & astrogeology"],["cshoemaker","Carolyn Shoemaker (1929-2021)","Discovering comets & asteroids"],
    ["helin","Eleanor Helin (1932-2009)","Near-Earth asteroid surveys"],["marsden","Brian Marsden (1937-2010)","Orbits & the Minor Planet Center"],
    ["walvarez","Walter Alvarez (b. 1940)","The iridium layer & the impact hypothesis"],["morrison","David Morrison (b. 1940)","The impact hazard & the Spaceguard survey"],
    ["chapman","Clark Chapman (planetary scientist)","Assessing the asteroid hazard"],["levy","David Levy (b. 1948)","Comet discovery & Shoemaker-Levy 9"],
    ["aharris","Alan Harris (asteroid astronomer)","Asteroid sizes & impact risk"],["hills","Jack Hills (astrophysicist)","Impact tsunami & the asteroid threat"]],
},

// 7 ── AVALANCHE / GLACIER-COLLAPSE DISASTER AT A RESORT ───────────────────────
{ id:"e_avalanche", title:"The Whitewall Slide", discipline:"Snow, Avalanche & Glacier Science",
  teaser:"A wall of snow buried a packed resort run at noon. A charge set off on purpose? A slide no one could have called? Or a snowpack watched, warned about, and skied anyway?",
  overclaimTag:"a deliberate blast", truthTag:"ignored snowpack warnings",
  venue:"the Whitewall avalanche inquiry", agent:"Investigator Lena Harkness", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Snow & Avalanche Pioneers", dossierName:"SNOW & AVALANCHE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Whitewall avalanche inquiry",
  who:{truth:"manager", items:[["manager","Kurt Halden — resort operations manager"],["forecaster","The avalanche forecaster"],["patrol","The ski-patrol director"]]},
  where:{truth:"office", items:[["slope","The Slope & Start Zone"],["patrolhut","The Patrol & Forecast Hut"],["office","The Resort Management Office"]]},
  what:{truth:"kept", overclaim:"blast", dismissal:"freak", items:[["blast","A charge set off deliberately"],["freak","A freak slide beyond any warning — an act of God"],["kept","Ignored snowpack monitoring & a slope kept open"]]},
  places:["slope","patrolhut","office"],
  chars:[["patroller","Patroller Sten","Ski-patrol observer","⛷","S","the start zone","Dug the snow pits; the weak layer was there and shouting for days."],
         ["snowforecaster","The Snow Forecaster","Avalanche forecaster","🏔","F","the forecast hut","Wrote the hazard bulletins; the high rating was overruled to keep the run open."],
         ["clerk","The Clerk","Resort-office clerk","🗂","C","the office","Keeps the closure logs — and the order that reopened the slope early."]],
  topics:[["agassiz","Louis Agassiz (1807-1873)","Glaciers & the ice age"],["jdforbes","James David Forbes (1809-1868)","The viscous flow of glaciers"],
    ["tyndall","John Tyndall (1820-1893)","Glacier motion & regelation"],["church","James E. Church (1869-1959)","Snow surveying & snowpack measurement"],
    ["paulcke","Wilhelm Paulcke (1873-1949)","The science of avalanches"],["seligman","Gerald Seligman (1886-1973)","Snow structure & the ski field"],
    ["voellmy","Adolf Voellmy (1902-1977)","Avalanche dynamics & runout"],["atwater","Montgomery Atwater (1904-1976)","Avalanche forecasting & control"],
    ["roch","André Roch (1906-2002)","Snow, avalanches & the slope"],["bader","Henri Bader (1907-1998)","Snow physics & metamorphism"],
    ["dequervain","Marcel de Quervain (snow scientist)","Snow classification & avalanche release"],["nye","John F. Nye (1923-2019)","The mechanics of glacier flow"],
    ["weertman","Johannes Weertman (1925-2018)","Glacier sliding & ice flow"],["lachapelle","Edward LaChapelle (1926-2007)","Avalanche science & snow crystals"],
    ["perla","Ronald Perla (avalanche scientist)","Snow mechanics & the avalanche handbook"],["schaerer","Peter Schaerer (avalanche scientist)","Avalanche dynamics & defense"],
    ["mcclung","David McClung (avalanche scientist)","Snow-slab stability & forecasting"],["colbeck","Samuel Colbeck (snow scientist)","Snow metamorphism & wet snow"]],
},

];
