// Mind & Culture (humanities / the human record) — 7 Casebook game DESIGNS.
// Same shape as one GAMES element in generate_more.js. Design only:
// mystery + board + informants + an 18-figure roster per game. No prose.
// Spine relabels for non-STEM: OVERCLAIM = a sensational story; DISMISSAL =
// "it's nothing / inevitable / an obvious fake"; TRUTH = a concealed, provable,
// methodical finding whose proof lives in an archive / lab / ledger.
// Cases are FICTIONAL; every figure of the day is a REAL, matched scholar.
module.exports = [

{ id:"c_fall", title:"The Last Council of Vellano", discipline:"History & Historical Method",
  teaser:"A proud republic fell in a single night. A traitor's bargain? A state already doomed? Or one decision buried in the council minutes?",
  overclaimTag:"one great traitor", truthTag:"a documented contingent decision",
  venue:"the Vellano fall inquiry", agent:"Archivist-Investigator Lena Corvo", standingLabel:"Commission credibility",
  readingShort:"Historians", readingLabel:"Historians of Method", dossierName:"HISTORIANS OF METHOD",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Vellano fall inquiry",
  who:{truth:"fa_provv", items:[["fa_provv","Provveditore Bassi — the council's war magistrate"],["fa_general","Ugo Sanvitale — the exiled condottiero"],["fa_doge","Doge Reniero — the last head of state"]]},
  where:{truth:"fa_archive", items:[["fa_walls","The City Walls & the River Gate"],["fa_chamber","The Council Chamber"],["fa_archive","The State Archive & Chancery"]]},
  what:{truth:"fa_decision", overclaim:"fa_betrayal", dismissal:"fa_inevit", items:[["fa_betrayal","A single traitor sold the city from within"],["fa_inevit","A dying republic — its fall was inevitable"],["fa_decision","A documented council vote that stood down the garrison and left the gate unbarred"]]},
  places:["fa_walls","fa_chamber","fa_archive"],
  chars:[["fa_chancellor","Chancery Clerk Orso","Chancery records clerk","🗂","O","the archive","Keeps the council minute-books; can find the vote that stood the mercenaries down."],
         ["fa_warden","Gate Warden Pia","River-gate warden","🗝","P","the walls","Kept the gate watch; knows on whose written order the postern was left unbarred."],
         ["fa_notary","Notary Ferro","City notary & chronicler","🪶","F","the chamber","Recorded the debates verbatim; heard which faction forced the fatal motion through."]],
  topics:[["fa_herodotus","Herodotus (c.484–425 BC)","Inquiry & the first histories"],
    ["fa_thucydides","Thucydides (c.460–400 BC)","Evidence, cause & political history"],
    ["fa_polybius","Polybius (c.200–118 BC)","Why states rise and fall"],
    ["fa_simaqian","Sima Qian (c.145–86 BC)","The grand historian & his sources"],
    ["fa_tacitus","Tacitus (c.56–120 AD)","The corruption of a republic"],
    ["fa_ibnkhaldun","Ibn Khaldun (1332–1406)","The science of the rise & fall of dynasties"],
    ["fa_valla","Lorenzo Valla (1407–1457)","Philology & exposing the Donation of Constantine"],
    ["fa_ranke","Leopold von Ranke (1795–1886)","Archival method & 'how it actually was'"],
    ["fa_michelet","Jules Michelet (1798–1874)","The archive as living narrative"],
    ["fa_fustel","Fustel de Coulanges (1830–1889)","Documents over theory"],
    ["fa_bloch","Marc Bloch (1886–1944)","The historian's craft & source criticism"],
    ["fa_febvre","Lucien Febvre (1878–1956)","The Annales & the history of mentalities"],
    ["fa_braudel","Fernand Braudel (1902–1985)","Structures & the long duration"],
    ["fa_ginzburg","Carlo Ginzburg (b. 1939)","Microhistory & the evidential paradigm"],
    ["fa_davis","Natalie Zemon Davis (1928–2023)","Microhistory & archival reconstruction"],
    ["fa_carr","E. H. Carr (1892–1982)","'What is History?' & the selection of facts"],
    ["fa_collingwood","R. G. Collingwood (1889–1943)","Historical evidence & re-enactment"],
    ["fa_burckhardt","Jacob Burckhardt (1818–1897)","The civilization of the city-state"]],
},

{ id:"c_art", title:"The Halberstadt Panel", discipline:"Art History & Authentication",
  teaser:"A lost masterpiece surfaced from nowhere and sold for a fortune. A priceless discovery? An obvious daub? Or something with a hidden tell?",
  overclaimTag:"a priceless lost masterpiece", truthTag:"a forgery with a hidden tell",
  venue:"the Halberstadt Panel inquiry", agent:"Investigator Rhea Voss", standingLabel:"Commission credibility",
  readingShort:"Connoisseurs", readingLabel:"Connoisseurs & Conservators", dossierName:"CONNOISSEURS & CONSERVATORS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halberstadt Panel inquiry",
  who:{truth:"ar_restorer", items:[["ar_restorer","Anselm Roterman — the panel's restorer"],["ar_dealer","Emile Vasse — the gallery dealer"],["ar_curator","Dr. Halvard — the museum's connoisseur"]]},
  where:{truth:"ar_lab", items:[["ar_gallery","The Auction House & Gallery"],["ar_provenance","The Provenance Archive"],["ar_lab","The Conservation Laboratory"]]},
  what:{truth:"ar_forgery", overclaim:"ar_masterpiece", dismissal:"ar_obvious", items:[["ar_masterpiece","A priceless rediscovered Old Master"],["ar_obvious","An obvious, clumsy fake — beneath notice"],["ar_forgery","A forgery moved on faked provenance, betrayed by an anachronistic pigment"]]},
  places:["ar_gallery","ar_provenance","ar_lab"],
  chars:[["ar_conservator","Conservator Nel","Paintings conservator","🔬","N","the laboratory","Takes the paint cross-sections; found a pigment that did not exist when the panel was supposedly made."],
         ["ar_archivist","Archivist Boll","Provenance archivist","🗂","B","the archive","Traces old sale records; the panel's 'centuries-old' history dead-ends in a forged bill of sale."],
         ["ar_framer","Framer Ruys","Frame-maker & studio hand","🖼","R","the gallery","Built frames for the restorer's studio; saw a 'new' old panel aged in the back room."]],
  topics:[["ar_morelli","Giovanni Morelli (1816–1891)","The Morellian method: the telltale detail"],
    ["ar_berenson","Bernard Berenson (1865–1959)","Connoisseurship & attribution"],
    ["ar_friedlander","Max J. Friedländer (1867–1958)","The trained connoisseur's eye"],
    ["ar_bode","Wilhelm von Bode (1845–1929)","The museum director's eye for Old Masters"],
    ["ar_bredius","Abraham Bredius (1855–1946)","The Vermeer authority who was deceived"],
    ["ar_vanmeegeren","Han van Meegeren (1889–1947)","The forger of false Vermeers"],
    ["ar_coremans","Paul Coremans (1908–1965)","The laboratory that unmasked the forgery"],
    ["ar_kurz","Otto Kurz (1908–1975)","The history of fakes & forgeries"],
    ["ar_zeri","Federico Zeri (1921–1998)","The connoisseur & the fake"],
    ["ar_mccrone","Walter McCrone (1916–2002)","Polarized-light microscopy of pigments"],
    ["ar_gettens","Rutherford J. Gettens (1900–1974)","The technical analysis of pigments"],
    ["ar_stout","George L. Stout (1897–1978)","Conservation science"],
    ["ar_forbes","Edward W. Forbes (1873–1969)","The pigment archive & conservation"],
    ["ar_plesters","Joyce Plesters (1927–1996)","Paint cross-sections & pigment identification"],
    ["ar_vandantzig","Maurits M. van Dantzig (1903–1960)","'Pictology': the science of authenticity"],
    ["ar_hebborn","Eric Hebborn (1934–1996)","The master forger of Old Master drawings"],
    ["ar_keating","Tom Keating (1917–1984)","The forger & the deliberate 'time bomb'"],
    ["ar_clark","Kenneth Clark (1903–1983)","Connoisseurship at the National Gallery"]],
},

{ id:"c_arch", title:"The Cranmoor Skull", discipline:"Archaeology & Scientific Dating",
  teaser:"A gravel pit gave up the missing link. The discovery of the century? A crank's blunder? Or something that was put there?",
  overclaimTag:"the discovery of the century", truthTag:"a planted, doctored artifact",
  venue:"the Cranmoor Skull inquiry", agent:"Inspector Cal Merrin", standingLabel:"Inquiry credibility",
  readingShort:"Archaeologists", readingLabel:"Archaeology & Dating Pioneers", dossierName:"ARCHAEOLOGY & DATING PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Cranmoor Skull inquiry",
  who:{truth:"ah_amateur", items:[["ah_amateur","Silas Fenn — the amateur antiquary who 'found' it"],["ah_keeper","Dr. Marrick — the museum keeper"],["ah_geologist","Prof. Aldous — the site geologist"]]},
  where:{truth:"ah_lab", items:[["ah_pit","The Gravel Pit & Dig"],["ah_gallery","The Museum Gallery"],["ah_lab","The Dating Laboratory"]]},
  what:{truth:"ah_planted", overclaim:"ah_link", dismissal:"ah_mistake", items:[["ah_link","The missing link — the earliest human ancestor"],["ah_mistake","A muddle — an amateur's honest mistake"],["ah_planted","A planted composite: filed, stained, and caught by dating"]]},
  places:["ah_pit","ah_gallery","ah_lab"],
  chars:[["ah_tech","Lab Tech Oona","Dating-lab technician","🧪","O","the laboratory","Runs the fluorine and nitrogen tests; the jaw and the skull are nowhere near the same age."],
         ["ah_foreman","Dig Foreman Cray","Excavation foreman","⛏","C","the gravel pit","Dug the pit for years; the prize pieces only ever turned up when one man was watching."],
         ["ah_registrar","Registrar Pell","Museum registrar","🗂","P","the gallery","Keeps the accession records; the find has no honest chain of discovery."]],
  topics:[["ah_petrie","Flinders Petrie (1853–1942)","Seriation & scientific excavation"],
    ["ah_pittrivers","Augustus Pitt Rivers (1827–1900)","Stratigraphy & typology"],
    ["ah_schliemann","Heinrich Schliemann (1822–1890)","Troy & the perils of the eager digger"],
    ["ah_evans","Arthur Evans (1851–1941)","Knossos & the risk of over-restoration"],
    ["ah_wheeler","Mortimer Wheeler (1890–1976)","The grid method & stratigraphic rigor"],
    ["ah_kenyon","Kathleen Kenyon (1906–1978)","The Wheeler–Kenyon method at Jericho"],
    ["ah_garrod","Dorothy Garrod (1892–1968)","Palaeolithic prehistory & method"],
    ["ah_libby","Willard Libby (1908–1980)","Radiocarbon dating"],
    ["ah_douglass","A. E. Douglass (1867–1962)","Dendrochronology: tree-ring dating"],
    ["ah_oakley","Kenneth Oakley (1911–1981)","The fluorine test that broke Piltdown"],
    ["ah_weiner","Joseph Weiner (1915–1982)","The exposure of the Piltdown hoax"],
    ["ah_legrosclark","Wilfrid Le Gros Clark (1895–1971)","The anatomy that revealed the fake"],
    ["ah_grahameclark","Grahame Clark (1907–1995)","Economic prehistory & method"],
    ["ah_childe","V. Gordon Childe (1892–1957)","Archaeological cultures & synthesis"],
    ["ah_nelson","Nels Nelson (1875–1964)","Stratigraphic excavation"],
    ["ah_kidder","Alfred Kidder (1885–1963)","Stratigraphy & Southwestern archaeology"],
    ["ah_suess","Hans Suess (1909–1993)","Radiocarbon calibration"],
    ["ah_renfrew","Colin Renfrew (1937–2024)","The radiocarbon revolution & rigor"]],
},

{ id:"c_psych", title:"The Mimicry Effect", discipline:"Psychology & Research Method",
  teaser:"A dazzling result took the field by storm — then no one could repeat it. A brilliant discovery? A fluke worth forgetting? Or numbers that never came from real people?",
  overclaimTag:"a landmark discovery", truthTag:"fabricated data",
  venue:"the Mimicry Effect inquiry", agent:"Investigator Dana Pell", standingLabel:"Panel credibility",
  readingShort:"Psychologists", readingLabel:"Psychology & Method", dossierName:"PSYCHOLOGY & METHOD",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Mimicry Effect inquiry",
  who:{truth:"ps_prof", items:[["ps_prof","Prof. Adrian Voss — the celebrated lead author"],["ps_junior","Dr. Kline — a junior co-author"],["ps_editor","The journal editor"]]},
  where:{truth:"ps_dataroom", items:[["ps_lab","The Psychology Laboratory"],["ps_journal","The Journal's Editorial Office"],["ps_dataroom","The Raw-Data Archive"]]},
  what:{truth:"ps_fabricated", overclaim:"ps_landmark", dismissal:"ps_noise", items:[["ps_landmark","A landmark, field-defining effect"],["ps_noise","A fragile fluke — just noise, best forgotten"],["ps_fabricated","Fabricated data behind the famous result"]]},
  places:["ps_lab","ps_journal","ps_dataroom"],
  chars:[["ps_grad","Grad Student Rhee","Doctoral student","🎓","R","the laboratory","Ran the follow-up studies; the 'raw' data are too clean to have come from real subjects."],
         ["ps_auditor","Data Auditor Sol","Statistical auditor","📊","S","the data archive","Re-checks the numbers; the summary statistics are impossible for the sample sizes claimed."],
         ["ps_replicator","Dr. Ives","Replication-team lead","🔁","I","the editorial office","Led the multi-lab replication; the effect vanishes every time it is run honestly."]],
  topics:[["ps_wundt","Wilhelm Wundt (1832–1920)","The first experimental psychology laboratory"],
    ["ps_james","William James (1842–1910)","The principles of psychology"],
    ["ps_galton","Francis Galton (1822–1911)","Correlation & the measurement of mind"],
    ["ps_pearson","Karl Pearson (1857–1936)","Correlation & statistical method"],
    ["ps_fisher","Ronald A. Fisher (1890–1962)","Significance testing & experimental design"],
    ["ps_cohen","Jacob Cohen (1923–1998)","Statistical power & effect size"],
    ["ps_meehl","Paul Meehl (1920–2003)","Clinical versus statistical prediction"],
    ["ps_kahneman","Daniel Kahneman (1934–2024)","Heuristics, biases & a warning on reliability"],
    ["ps_tversky","Amos Tversky (1937–1996)","Judgment under uncertainty"],
    ["ps_rosenthal","Robert Rosenthal (1933–2024)","Experimenter effects & the file-drawer problem"],
    ["ps_ioannidis","John Ioannidis (b. 1965)","Why most published findings may be false"],
    ["ps_nosek","Brian Nosek (b. 1973)","The reproducibility project & open science"],
    ["ps_simonsohn","Uri Simonsohn (behavioral scientist, p-curve method)","Detecting p-hacking in results"],
    ["ps_gigerenzer","Gerd Gigerenzer (b. 1947)","The misuse of null-hypothesis testing"],
    ["ps_greenwald","Anthony Greenwald (b. 1939)","Implicit measures & the replication debate"],
    ["ps_bem","Daryl Bem (b. 1938)","The 'feeling the future' study that sparked the crisis"],
    ["ps_stapel","Diederik Stapel (social psychologist, fabricated-data case)","How fabricated datasets were exposed"],
    ["ps_hauser","Marc Hauser (cognitive scientist, misconduct case)","Data integrity in the lab"]],
},

{ id:"c_script", title:"The Karnos Tablets", discipline:"Linguistics & Decipherment",
  teaser:"A forgotten script gave up its secret: a lost royal epic, one scholar swore. An unbreakable code? A hoax reading? Or a grid that tells a duller truth?",
  overclaimTag:"a lost royal epic", truthTag:"a fabricated decipherment",
  venue:"the Karnos tablets inquiry", agent:"Investigator Yara Sol", standingLabel:"Commission credibility",
  readingShort:"Decipherers", readingLabel:"Decipherers & Linguists", dossierName:"DECIPHERERS & LINGUISTS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Karnos tablets inquiry",
  who:{truth:"sc_claimant", items:[["sc_claimant","Prof. Malden Croft — the sensational decipherer"],["sc_rival","Dr. Sena — a rival philologist"],["sc_curator","The museum curator"]]},
  where:{truth:"sc_study", items:[["sc_gallery","The Tablet Gallery & Find-Site"],["sc_epigraphy","The Epigraphy Lab"],["sc_study","The Decipherment Study"]]},
  what:{truth:"sc_fabreading", overclaim:"sc_epic", dismissal:"sc_undecipherable", items:[["sc_epic","A lost royal epic naming a forgotten king"],["sc_undecipherable","An unreadable script — meaningless marks"],["sc_fabreading","A fabricated decipherment; the grid reads a plain ledger"]]},
  places:["sc_gallery","sc_epigraphy","sc_study"],
  chars:[["sc_epigrapher","Epigrapher Tuma","Field epigrapher","📷","T","the epigraphy lab","Makes the squeezes and photographs; the claimed signs are not on the tablets at all."],
         ["sc_registrar","Registrar Ode","Find-site registrar","🗂","O","the gallery","Logs where each tablet came from; the 'epic' tablets share a suspiciously modern context."],
         ["sc_statistician","Analyst Ven","Computational linguist","🔡","V","the study","Counts the sign frequencies; the grid points to an inventory, not a poem."]],
  topics:[["sc_champollion","Jean-François Champollion (1790–1832)","The decipherment of hieroglyphs"],
    ["sc_young","Thomas Young (1773–1829)","The Rosetta Stone & phonetic values"],
    ["sc_grotefend","Georg F. Grotefend (1775–1853)","The first cuneiform readings"],
    ["sc_rawlinson","Henry Rawlinson (1810–1895)","The Behistun inscription & Old Persian"],
    ["sc_hincks","Edward Hincks (1792–1866)","Akkadian cuneiform"],
    ["sc_hrozny","Bedřich Hrozný (1879–1952)","The decipherment of Hittite"],
    ["sc_ventris","Michael Ventris (1922–1956)","The decipherment of Linear B"],
    ["sc_kober","Alice Kober (1906–1950)","The grids that prepared Linear B"],
    ["sc_chadwick","John Chadwick (1920–1998)","Documents in Mycenaean Greek"],
    ["sc_knorozov","Yuri Knorozov (1922–1999)","The phonetic decipherment of Maya glyphs"],
    ["sc_proskouriakoff","Tatiana Proskouriakoff (1909–1985)","Reading Maya historical inscriptions"],
    ["sc_thompson","J. Eric S. Thompson (1898–1975)","The authority who resisted Maya decipherment"],
    ["sc_saussure","Ferdinand de Saussure (1857–1913)","The linguistic sign & structure"],
    ["sc_jones","William Jones (1746–1794)","Comparative philology & Indo-European"],
    ["sc_rask","Rasmus Rask (1787–1832)","Comparative grammar & sound laws"],
    ["sc_grimm","Jacob Grimm (1785–1863)","Grimm's law of sound shifts"],
    ["sc_gelb","Ignace J. Gelb (1907–1985)","Grammatology & the theory of writing"],
    ["sc_friedman","William F. Friedman (1891–1969)","Cryptanalysis & letter-frequency method"]],
},

{ id:"c_doping", title:"The Verano Ascent", discipline:"Sports Science & Anti-Doping",
  teaser:"A champion rewrote the record books and passed every test. A once-in-a-century talent? A meaningless mark in a dirty sport? Or something built to beat the lab?",
  overclaimTag:"a once-in-a-century clean champion", truthTag:"a systematic doping program",
  venue:"the Verano doping inquiry", agent:"Investigator Marek Dane", standingLabel:"Inquiry credibility",
  readingShort:"Physiologists", readingLabel:"Sport Science & Anti-Doping", dossierName:"SPORT SCIENCE & ANTI-DOPING",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Verano doping inquiry",
  who:{truth:"dp_doctor", items:[["dp_doctor","Dr. Halden Reuss — the team physician"],["dp_athlete","The champion athlete"],["dp_official","The federation official"]]},
  where:{truth:"dp_lab", items:[["dp_camp","The Training Camp & Velodrome"],["dp_federation","The Federation Office"],["dp_lab","The Anti-Doping Laboratory"]]},
  what:{truth:"dp_program", overclaim:"dp_phenom", dismissal:"dp_everyone", items:[["dp_phenom","A clean, once-in-a-century champion"],["dp_everyone","A meaningless record — everyone dopes anyway"],["dp_program","A systematic doping program built to beat the tests"]]},
  places:["dp_camp","dp_federation","dp_lab"],
  chars:[["dp_scientist","Lab Scientist Aro","Anti-doping scientist","🧪","A","the laboratory","Retests the frozen samples; the blood passport shows values no clean rider can hold."],
         ["dp_soigneur","Soigneur Vela","Former team soigneur","🚴","V","the training camp","Worked inside the team; knows the fridge, the schedule, and the microdosing."],
         ["dp_officer","Control Officer Renn","Doping-control officer","📋","R","the federation office","Handles the test chain; can show which controls were dodged, delayed, or warned in advance."]],
  topics:[["dp_hill","A. V. Hill (1886–1977)","VO2 max & muscle physiology"],
    ["dp_krogh","August Krogh (1874–1949)","Capillaries & exercise physiology"],
    ["dp_astrand","Per-Olof Åstrand (1922–2015)","The textbook of work physiology"],
    ["dp_saltin","Bengt Saltin (1935–2014)","Muscle biopsy & endurance physiology"],
    ["dp_donike","Manfred Donike (1933–1995)","GC/MS steroid testing & the T/E ratio"],
    ["dp_beckett","Arnold Beckett (1920–2010)","Early doping analysis & drug control"],
    ["dp_catlin","Don Catlin (b. 1938)","The lab that caught the designer steroid THG"],
    ["dp_ayotte","Christiane Ayotte (anti-doping chemist, Montreal lab)","Detecting masked steroids"],
    ["dp_ekblom","Björn Ekblom (b. 1938)","Blood doping & the physiology of EPO"],
    ["dp_parisotto","Robin Parisotto (sports scientist, EPO & blood passport)","Blood markers of doping"],
    ["dp_lasne","Françoise Lasne (anti-doping scientist)","The urine test for EPO"],
    ["dp_ashenden","Michael Ashenden (sports scientist, biological passport)","The athlete biological passport"],
    ["dp_franke","Werner Franke (1940–2022)","Exposing the East German state doping program"],
    ["dp_berendonk","Brigitte Berendonk (b. 1942)","Documenting state-sponsored doping"],
    ["dp_yesalis","Charles Yesalis (epidemiologist, anabolic steroids)","The spread of steroid use"],
    ["dp_prokop","Ludwig Prokop (1920–2013)","Sports medicine & early doping controls"],
    ["dp_bergstrom","Jonas Bergström (1929–2001)","The muscle-biopsy needle & glycogen"],
    ["dp_rodchenkov","Grigory Rodchenkov (b. 1958)","The lab chief who exposed a national doping program"]],
},

{ id:"c_fraud", title:"The Lindqvist Result", discipline:"Research Integrity & Scientific Method",
  teaser:"One lab announced the breakthrough of the decade — and no one else could reproduce it. A genius ahead of the field? A dead end best forgotten? Or a result that was manufactured?",
  overclaimTag:"the breakthrough of the decade", truthTag:"fabricated results",
  venue:"the Lindqvist Result inquiry", agent:"Investigator Nora Vance", standingLabel:"Panel credibility",
  readingShort:"Skeptics", readingLabel:"Method & Research Integrity", dossierName:"METHOD & RESEARCH INTEGRITY",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Lindqvist Result inquiry",
  who:{truth:"fr_pi", items:[["fr_pi","Prof. Cassian Lund — the principal investigator"],["fr_postdoc","Dr. Ames — a postdoc co-author"],["fr_director","The institute director"]]},
  where:{truth:"fr_forensics", items:[["fr_lab","The Laboratory & Instrument Room"],["fr_press","The Journal & Press Office"],["fr_forensics","The Notebook & Image-Forensics Room"]]},
  what:{truth:"fr_fabrication", overclaim:"fr_breakthrough", dismissal:"fr_deadend", items:[["fr_breakthrough","The breakthrough of the decade"],["fr_deadend","An honest dead end — just science that failed"],["fr_fabrication","Fabricated figures & suppressed failed replications"]]},
  places:["fr_lab","fr_press","fr_forensics"],
  chars:[["fr_whistle","Postdoc Iida","Whistleblower postdoc","🧑‍🔬","I","the laboratory","Tried for months to reproduce the result; the key runs never once worked."],
         ["fr_imaging","Analyst Brede","Image-forensics analyst","🖥","B","the forensics room","Overlays the published figures; the same band appears in three 'different' experiments."],
         ["fr_investigator","Auditor Kase","Integrity investigator","🗂","K","the press office","Holds the notebooks and reviewer files — including the replications quietly buried."]],
  topics:[["fr_bacon","Francis Bacon (1561–1626)","The inductive experimental method"],
    ["fr_boyle","Robert Boyle (1627–1691)","Reproducibility & witnessing experiments"],
    ["fr_whewell","William Whewell (1794–1866)","Induction & the consilience of evidence"],
    ["fr_babbage","Charles Babbage (1791–1871)","'Cooking, trimming & forging' of data"],
    ["fr_popper","Karl Popper (1902–1994)","Falsifiability & conjectures"],
    ["fr_merton","Robert K. Merton (1910–2003)","The norms of science & organized skepticism"],
    ["fr_kuhn","Thomas Kuhn (1922–1996)","Paradigms, anomalies & revolutions"],
    ["fr_fleck","Ludwik Fleck (1896–1961)","How a scientific fact is made"],
    ["fr_lakatos","Imre Lakatos (1922–1974)","Degenerating research programmes"],
    ["fr_medawar","Peter Medawar (1915–1987)","'Is the scientific paper a fraud?'"],
    ["fr_langmuir","Irving Langmuir (1881–1957)","'Pathological science'"],
    ["fr_kohn","Alexander Kohn (1919–1994)","The history of scientific fraud"],
    ["fr_goodstein","David Goodstein (1939–2024)","'On Fact and Fraud'"],
    ["fr_bik","Elisabeth Bik (image-integrity analyst)","Detecting duplicated figures"],
    ["fr_schon","Jan Hendrik Schön (physicist, fabricated-breakthrough case)","How faked results collapse"],
    ["fr_hwang","Hwang Woo-suk (biologist, fabricated stem-cell case)","Suppressed failed replications"],
    ["fr_darsee","John Darsee (researcher, fabricated-data case)","Detecting invented data"],
    ["fr_fanelli","Daniele Fanelli (meta-scientist, research misconduct)","How common is misconduct?"]],
},

];
