// SEVEN Casebook game STRUCTURES for "Law, Money & Power" (institutions & incentives).
// DESIGN ONLY — same field-for-field shape as one GAMES element in generate_more.js.
// NON-STEM relabel of the spine: OVERCLAIM = a sensational villain/conspiracy;
// DISMISSAL = "business/politics as usual"; TRUTH = a concealed, systemic, PROVABLE thing
// whose documentary proof lives at where.truth. Cases are FICTIONAL but plausible;
// every `sci` is a REAL jurist / economist / political scientist (18 unique per game,
// none repeated across the seven, none in batch/used_figures.txt).

module.exports = [

{ id:"j_convict", title:"The Vale Conviction", discipline:"Law: Criminal Evidence & Due Process",
  teaser:"A man is doing life for a killing he swears he never did. A vast plot to frame him? Just a guilty man's excuses? Or something the jury was never allowed to see?",
  overclaimTag:"a vast frame-up conspiracy", truthTag:"a buried exculpatory file",
  venue:"the Vale conviction-review inquiry", agent:"Investigator Ruth Calder", standingLabel:"Review-board credibility",
  readingShort:"Jurists", readingLabel:"Jurists of Evidence & Proof", dossierName:"JURISTS OF EVIDENCE",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Vale conviction-review",
  who:{truth:"prosecutor", items:[["detective","The lead detective"],["prosecutor","District Attorney Miles Crade — the prosecutor"],["judge","The trial judge"]]},
  where:{truth:"dafiles", items:[["precinct","The Police Precinct & Lineup Room"],["courthouse","The Courthouse & Trial Record"],["dafiles","The District Attorney's Case Files"]]},
  what:{truth:"brady", overclaim:"frameup", dismissal:"guilty", items:[["frameup","A vast conspiracy framed an innocent man"],["guilty","Nothing amiss — the right man was convicted"],["brady","A buried exculpatory file & a rigged lineup"]]},
  places:["precinct","courthouse","dafiles"],
  chars:[["paralegal","Paralegal Nora Wyss","Defense paralegal","📎","N","the defense office","Boxed the old case file; found a lab report the defense was never handed."],
         ["clerk","The Court Clerk","Courthouse records clerk","🗂","C","the courthouse","Keeps the transcript and the exhibit log that never quite matched."],
         ["sergeant","Desk Sergeant Boone","Retired desk sergeant","🚔","B","the precinct","Ran the room the night of the lineup; saw the witness steered to a face."]],
  topics:[["dueprocess","Edward Coke (1552-1634)","Due process & the law of the land"],["ratio","William Blackstone (1723-1780)","Blackstone's ratio: ten guilty spared"],
    ["presumption","Cesare Beccaria (1738-1794)","The presumption of innocence"],["judicialevidence","Jeremy Bentham (1748-1832)","The rationale of judicial evidence"],
    ["cautionrule","Matthew Hale (1609-1676)","The caution against easy accusation"],["evidencelaw","Simon Greenleaf (1783-1853)","The treatise on evidence"],
    ["proof","James Fitzjames Stephen (1829-1894)","The criminal law & the burden of proof"],["judicialproof","John Henry Wigmore (1863-1943)","The science of judicial proof"],
    ["testimony","Hugo Münsterberg (1863-1916)","The psychology of the witness stand"],["rightcounsel","Hugo Black (1886-1971)","The right to counsel"],
    ["exclusion","Benjamin Cardozo (1870-1938)","The exclusionary rule & the constable's blunder"],["innocents","Edwin Borchard (1884-1948)","Convicting the Innocent"],
    ["disclosure","William O. Douglas (1898-1980)","Brady v. Maryland & the duty to disclose"],["procedure","Earl Warren (1891-1974)","Criminal procedure & the fair trial"],
    ["memory","Elizabeth Loftus (b. 1944)","The malleability of memory"],["lineups","Gary L. Wells (b. 1950)","Eyewitness ID & the suggestive lineup"],
    ["dnaexon","Barry Scheck (b. 1949)","DNA exoneration & the Innocence Project"],["anatomy","Brandon Garrett (wrongful-conviction scholar)","The anatomy of a wrongful conviction"]],
},

{ id:"j_fraud", title:"The Amberline Collapse", discipline:"Accounting & Corporate Finance",
  teaser:"A high-flying energy trader went from market darling to dust in a month. A raid by short-sellers? Just the market turning? Or billions parked where no auditor would look?",
  overclaimTag:"a short-seller raid", truthTag:"losses hidden off the books",
  venue:"the Amberline bankruptcy examination", agent:"Examiner Dana Roth", standingLabel:"Examiner credibility",
  readingShort:"Reckoners", readingLabel:"Masters of the Ledger", dossierName:"MASTERS OF THE LEDGER",
  enterLabel:"Open the examination", subt:"A deduction game inside the Amberline bankruptcy examination",
  who:{truth:"cfo", items:[["ceo","The chief executive"],["cfo","Julian Frael — the chief financial officer"],["auditor","The outside auditor"]]},
  where:{truth:"spes", items:[["trading","The Trading Floor"],["auditroom","The Auditor's Workroom"],["spes","The Off-Books Partnership Files"]]},
  what:{truth:"offbooks", overclaim:"raid", dismissal:"cycle", items:[["raid","A short-seller raid sank a sound company"],["cycle","Nothing wrong — just the market turning"],["offbooks","Losses hidden in off-books entities"]]},
  places:["trading","auditroom","spes"],
  chars:[["controller","Assistant Controller Pia Voss","Assistant controller","🧮","V","the finance floor","Booked the entries; the same losses kept moving to partnerships she couldn't see."],
         ["junioraudit","The Junior Auditor","Audit-team junior","🗂","A","the auditor's room","Ticked the confirmations; the partnership balances never confirmed back."],
         ["trader","Desk Trader Okonkwo","Energy-desk trader","📈","O","the trading floor","Marked the book to models no one outside could check."]],
  topics:[["doubleentry","Luca Pacioli (c. 1447-1517)","Double-entry bookkeeping"],["agency","Adam Smith (1723-1790)","The joint-stock firm & the agency problem"],
    ["auditduty","Robert H. Montgomery (1872-1953)","The auditor's duty"],["principles","George O. May (1875-1961)","Accounting principles & disclosure"],
    ["goingconcern","William A. Paton (1889-1991)","Accounting theory & the going concern"],["theory","A. C. Littleton (1886-1974)","The structure of accounting theory"],
    ["statements","Benjamin Graham (1894-1976)","Reading the financial statements"],["whitecollar","Edwin Sutherland (1883-1950)","White-collar crime"],
    ["bezzle","John Kenneth Galbraith (1908-2006)","The crash & 'the bezzle'"],["triangle","Donald Cressey (1919-1987)","The fraud triangle & other people's money"],
    ["creative","Abraham Briloff (1917-2013)","Unaccountable, creative accounting"],["incentives","Michael C. Jensen (1939-2024)","Agency theory & managerial incentives"],
    ["asymmetry","George Akerlof (b. 1940)","Asymmetric information & 'lemons'"],["numbersgame","Arthur Levitt (b. 1931)","Earnings management & the numbers game"],
    ["shenanigans","Howard Schilit (forensic-accounting author)","Financial shenanigans"],["enronwarn","Sherron Watkins (b. 1959)","The Enron off-books warning"],
    ["internalaudit","Cynthia Cooper (WorldCom internal auditor)","The internal auditor's discovery"],["forensic","Harry Markopolos (b. 1956)","The forensic whistleblower"]],
},

{ id:"j_capture", title:"The Halcyon Grid", discipline:"Regulation & Public Choice",
  teaser:"A power utility keeps winning every rate case while the lights keep failing. A shadowy cabal? Just how regulation works? Or a board quietly staffed by the firm it is meant to watch?",
  overclaimTag:"a shadowy cabal", truthTag:"a captured oversight board",
  venue:"the Halcyon utility oversight inquiry", agent:"Investigator Owen Marsh", standingLabel:"Commission credibility",
  readingShort:"Theorists", readingLabel:"Theorists of the State & the Firm", dossierName:"THEORISTS OF REGULATION",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halcyon utility oversight inquiry",
  who:{truth:"chair", items:[["ceo","The utility's chief executive"],["chair","Regina Poll — the oversight board chair"],["staff","The commission staff director"]]},
  where:{truth:"boardfiles", items:[["ratehearing","The Rate-Hearing Chamber"],["utilityhq","The Utility's Head Office"],["boardfiles","The Oversight Board's Records"]]},
  what:{truth:"capture", overclaim:"cabal", dismissal:"normal", items:[["cabal","A shadowy cabal secretly runs the grid"],["normal","Nothing amiss — ordinary regulation at work"],["capture","The firm staffed & steered its own regulator"]]},
  places:["ratehearing","utilityhq","boardfiles"],
  chars:[["analyst","Staff Analyst Devi Rao","Commission staff analyst","📊","R","the commission","Runs the rate models; her adverse findings kept getting revised upward."],
         ["clerk","The Records Clerk","Board records clerk","🗂","C","the board office","Keeps the appointment files — and the résumés that all trace to one firm."],
         ["lineworker","Lineworker Hobbs","Utility lineworker","🔌","H","the utility","Patches the failing grid the rate money never seems to reach."]],
  topics:[["bureaucracy","Max Weber (1864-1920)","Bureaucracy & rational-legal authority"],["oligarchy","Robert Michels (1876-1936)","The iron law of oligarchy"],
    ["sunshine","Charles Francis Adams Jr. (1835-1915)","The 'sunshine' railroad commission"],["publicity","Louis Brandeis (1856-1941)","The curse of bigness & publicity"],
    ["adminprocess","James M. Landis (1899-1964)","The administrative process & its capture"],["lifecycle","Marver Bernstein (1919-1990)","The life cycle of a captured commission"],
    ["railhistory","Gabriel Kolko (1932-2014)","The political history of rail regulation"],["regecon","Alfred E. Kahn (1917-2010)","The economics of regulation"],
    ["fcc","Ronald Coase (1910-2013)","The FCC & the case for markets"],["capturetheory","George Stigler (1911-1991)","The theory of regulatory capture"],
    ["collective","Mancur Olson (1932-1998)","The logic of concentrated interests"],["publicchoice","James M. Buchanan (1919-2013)","Public choice & the state"],
    ["rentseeking","Gordon Tullock (1922-2014)","Rent-seeking"],["peltzman","Sam Peltzman (b. 1940)","The economic theory of regulation"],
    ["pricing","Richard Posner (b. 1939)","The pricing of regulation"],["interestgroup","Theodore Lowi (1931-2017)","Interest-group liberalism"],
    ["moderncapture","Jean Tirole (b. 1953)","The modern theory of regulatory capture"],["budgetbureau","William Niskanen (1933-2011)","The budget-maximizing bureau"]],
},

{ id:"j_bank", title:"The Sterling Trust Collapse", discipline:"Banking & Systemic Risk",
  teaser:"A pillar bank that passed every stress test failed in a single weekend. A foreign raid on the currency? A once-a-century storm? Or leverage no model was allowed to see?",
  overclaimTag:"an attack on the currency", truthTag:"hidden leverage & gamed models",
  venue:"the Sterling Trust failure inquiry", agent:"Investigator Cara Finch", standingLabel:"Inquiry credibility",
  readingShort:"Economists", readingLabel:"Students of Panics & Risk", dossierName:"STUDENTS OF PANICS & RISK",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Sterling Trust failure inquiry",
  who:{truth:"cro", items:[["ceo","The bank's chief executive"],["cro","Adrian Sable — the chief risk officer"],["regulator","The bank supervisor"]]},
  where:{truth:"riskfiles", items:[["dealing","The Dealing Room"],["supervisor","The Supervisor's Office"],["riskfiles","The Risk Department's Model Files"]]},
  what:{truth:"leverage", overclaim:"attack", dismissal:"storm", items:[["attack","A foreign raid on the currency broke the bank"],["storm","A once-a-century storm no one could foresee"],["leverage","Hidden leverage & risk models quietly gamed"]]},
  places:["dealing","supervisor","riskfiles"],
  chars:[["quant","Quant Analyst Priya Sen","Risk quant","🧮","P","the risk desk","Built the model; watched its worst-case number get dialed down by hand."],
         ["clerk","The Records Clerk","Risk-department clerk","🗂","C","the risk office","Keeps the model sign-offs and the exposures kept off the main book."],
         ["dealer","Head Dealer Marlow","Head bond dealer","📉","M","the dealing room","Ran the leverage everyone praised until the repo lenders vanished."]],
  topics:[["crowds","Charles Mackay (1814-1889)","Popular delusions & the madness of crowds"],["lastresort","Walter Bagehot (1826-1877)","Lombard Street & the lender of last resort"],
    ["debtdeflation","Irving Fisher (1867-1947)","Debt-deflation"],["uncertainty","Frank Knight (1885-1972)","Risk versus uncertainty"],
    ["liquidity","John Maynard Keynes (1883-1946)","Liquidity & animal spirits"],["manias","Charles P. Kindleberger (1910-2003)","Manias, panics & crashes"],
    ["instability","Hyman Minsky (1919-1996)","The financial-instability hypothesis"],["portfolio","Harry Markowitz (1927-2023)","Portfolio risk & the model"],
    ["fattails","Benoit Mandelbrot (1924-2010)","Fat tails & the misbehavior of markets"],["goodhart","Charles Goodhart (b. 1936)","Goodhart's law & gamed metrics"],
    ["exuberance","Robert Shiller (b. 1946)","Bubbles & irrational exuberance"],["modelsbad","Emanuel Derman (b. 1945)","Models behaving badly"],
    ["thistime","Carmen Reinhart (b. 1955)","'This time is different'"],["bankleverage","Anat Admati (b. 1956)","Bank leverage & the bankers' new clothes"],
    ["warning","Raghuram Rajan (b. 1963)","The 2005 warning on hidden risk"],["repo","Gary Gorton (shadow-banking economist)","The run on repo & shadow banking"],
    ["blackswan","Nassim Nicholas Taleb (b. 1960)","The black swan & tail risk"],["systemic","Andrew W. Lo (b. 1960)","Systemic risk & adaptive markets"]],
},

{ id:"j_vote", title:"The Kessler County Count", discipline:"Elections & Democratic Theory",
  teaser:"A knife-edge election, and half a county's votes seem to vanish into the margins. A foreign hand on the scales? Just politics as usual? Or a map and a purge doing quiet work?",
  overclaimTag:"a foreign plot", truthTag:"a documented gerrymander & purge",
  venue:"the Kessler County election inquiry", agent:"Investigator Lena Ward", standingLabel:"Inquiry credibility",
  readingShort:"Thinkers", readingLabel:"Theorists of the Vote", dossierName:"THEORISTS OF THE VOTE",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Kessler County election inquiry",
  who:{truth:"registrar", items:[["party","The county party boss"],["registrar","Supervisor Hollis Crane — the elections registrar"],["observer","The foreign-affairs observer"]]},
  where:{truth:"electionoffice", items:[["pollingsite","The Polling Precincts"],["partyhq","The County Party Headquarters"],["electionoffice","The County Elections Office"]]},
  what:{truth:"gerrymander", overclaim:"foreign", dismissal:"usual", items:[["foreign","A foreign plot rigged the whole election"],["usual","Nothing unusual — politics as it always is"],["gerrymander","A drawn map & a quiet purge of the rolls"]]},
  places:["pollingsite","partyhq","electionoffice"],
  chars:[["pollworker","Poll Captain Ada Reyes","Precinct poll captain","🗳","R","the precinct","Worked the tables; watched voters turned away as 'inactive' by the hundred."],
         ["clerk","The Records Clerk","Elections records clerk","🗂","C","the elections office","Keeps the purge logs and the district map redrawn behind closed doors."],
         ["canvasser","Canvasser Dumont","Party canvasser","📋","D","the party office","Knocks every door; knew which blocks were carved out of which district."]],
  topics:[["forms","Aristotle (384-322 BC)","The forms of government & citizenship"],["separation","Montesquieu (1689-1755)","The separation of powers"],
    ["paradox","Nicolas de Condorcet (1743-1794)","The voting paradox"],["borda","Jean-Charles de Borda (1733-1799)","Methods of election"],
    ["origins","Elbridge Gerry (1744-1814)","The original gerrymander"],["faction","James Madison (1751-1836)","Faction & Federalist No. 10"],
    ["majority","Alexis de Tocqueville (1805-1859)","The tyranny of the majority"],["represent","John Stuart Mill (1806-1873)","Representative government & the minority"],
    ["heresthetics","William H. Riker (1920-1993)","Social choice & the manipulation of agendas"],["bias","E. E. Schattschneider (1892-1971)","The mobilization of bias"],
    ["southern","V. O. Key Jr. (1908-1963)","Southern politics & disenfranchisement"],["median","Duncan Black (1908-1991)","The median voter"],
    ["polyarchy","Robert A. Dahl (1915-2014)","Polyarchy & who governs"],["duverger","Maurice Duverger (1917-2014)","Electoral laws & party systems"],
    ["impossible","Kenneth Arrow (1921-2017)","The impossibility theorem"],["econdemo","Anthony Downs (1930-2021)","The economic theory of democracy"],
    ["partysystems","Giovanni Sartori (1924-2017)","Parties & the counting of votes"],["measurebias","Bernard Grofman (b. 1944)","The measurement of gerrymandering"]],
},

{ id:"j_trust", title:"The Cygnet Standard", discipline:"Antitrust & Industrial Organization",
  teaser:"A tech giant's rivals keep dying just as they start to win. A ruthless plot to control everything? Just a better competitor winning? Or prices set below cost, and a study buried to hide it?",
  overclaimTag:"an all-controlling conspiracy", truthTag:"concealed predatory pricing",
  venue:"the Cygnet antitrust inquiry", agent:"Investigator Cole Ashby", standingLabel:"Inquiry credibility",
  readingShort:"Economists", readingLabel:"Economists of Monopoly", dossierName:"ECONOMISTS OF MONOPOLY",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Cygnet antitrust inquiry",
  who:{truth:"ceo", items:[["ceo","Roland Vane — the founder & chief executive"],["strategist","The chief strategy officer"],["regulator","The antitrust regulator"]]},
  where:{truth:"strategyfiles", items:[["market","The Marketplace & Rivals"],["boardroom","The Company Boardroom"],["strategyfiles","The Strategy Office's Files"]]},
  what:{truth:"predation", overclaim:"empire", dismissal:"merit", items:[["empire","A sinister plot to control everything"],["merit","Nothing wrong — just a better competitor winning"],["predation","Below-cost pricing & a buried internal study"]]},
  places:["market","boardroom","strategyfiles"],
  chars:[["analyst","Analyst Mira Kade","Strategy analyst","📊","K","the strategy office","Ran the numbers showing the price war lost money on purpose — then watched them vanish."],
         ["clerk","The Records Clerk","Company records clerk","🗂","C","the boardroom","Keeps the board minutes and the study stamped 'do not distribute'."],
         ["rival","Rival Founder Estes","Rival startup founder","💻","E","the marketplace","Watched Cygnet undercut him below cost until his funding dried up."]],
  topics:[["monopolytheory","Antoine Augustin Cournot (1801-1877)","The theory of monopoly"],["pricecomp","Joseph Bertrand (1822-1900)","Price competition"],
    ["shermanact","John Sherman (1823-1900)","The Antitrust Act"],["industry","Alfred Marshall (1842-1924)","The economics of industry"],
    ["trusts","John Bates Clark (1847-1938)","The control of the trusts"],["enterprise","Thorstein Veblen (1857-1929)","The theory of business enterprise"],
    ["creativedest","Joseph A. Schumpeter (1883-1950)","Creative destruction & monopoly"],["monopcomp","Edward Chamberlin (1899-1967)","Monopolistic competition"],
    ["imperfect","Joan Robinson (1903-1983)","Imperfect competition"],["dominant","Heinrich von Stackelberg (1905-1946)","The dominant firm & leadership"],
    ["control","Adolf A. Berle (1895-1971)","The modern corporation & control"],["administered","Gardiner C. Means (1896-1988)","Administered prices"],
    ["scp","Edward S. Mason (1899-1992)","Structure, conduct & performance"],["barriers","Joe S. Bain (1912-1991)","Barriers to entry"],
    ["trustbust","Thurman Arnold (1891-1969)","Trustbusting & enforcement"],["predatorytest","Phillip Areeda (1930-1995)","The test for predatory pricing"],
    ["paradox","Robert H. Bork (1927-2012)","The antitrust paradox"],["foreclosure","Oliver E. Williamson (1932-2020)","Markets, hierarchies & foreclosure"]],
},

{ id:"j_press", title:"The Ashford Dispatch", discipline:"Journalism Ethics & Verification",
  teaser:"A prize-winning series turns out to rest on a source no one can find. A plot to smear the paper? Just an honest mistake? Or a reporter's inventions waved through every check?",
  overclaimTag:"a plot against the paper", truthTag:"fabricated sourcing",
  venue:"the Ashford Dispatch review", agent:"Investigator Nadia Kerr", standingLabel:"Newsroom credibility",
  readingShort:"Editors", readingLabel:"Figures of the Free Press", dossierName:"FIGURES OF THE FREE PRESS",
  enterLabel:"Open the review", subt:"A deduction game inside the Ashford Dispatch review",
  who:{truth:"reporter", items:[["reporter","Corin Faye — the star reporter"],["editor","The managing editor"],["publisher","The publisher"]]},
  where:{truth:"sourcefiles", items:[["newsroom","The Newsroom Floor"],["editdesk","The Editor's Desk"],["sourcefiles","The Source & Fact-Check Files"]]},
  what:{truth:"fabrication", overclaim:"smear", dismissal:"mistake", items:[["smear","An outside plot planted lies to smear the paper"],["mistake","Nothing sinister — an honest reporting error"],["fabrication","Invented sources waved past every check"]]},
  places:["newsroom","editdesk","sourcefiles"],
  chars:[["factchecker","Fact-Checker Jonah Pell","Newsroom fact-checker","✅","P","the newsroom","Flagged the quotes he couldn't verify — and was told to move on."],
         ["clerk","The Records Clerk","Editorial records clerk","🗂","C","the source files","Keeps the assignment logs and the source file that came back empty."],
         ["stringer","Local Stringer Ames","Local stringer","📰","A","the field","Worked the same town; none of the named witnesses ever existed."]],
  topics:[["freepress","John Peter Zenger (1697-1746)","Truth & the free press"],["accuracy","Joseph Pulitzer (1847-1911)","Accuracy & the ethics of the press"],
    ["record","Adolph S. Ochs (1858-1935)","The standard of the record"],["muckrake","Ida Tarbell (1857-1944)","Documentary investigative reporting"],
    ["shame","Lincoln Steffens (1866-1936)","Muckraking & the shame of the cities"],["publicopinion","Walter Lippmann (1889-1974)","Public opinion & the news"],
    ["presscrit","George Seldes (1890-1995)","Press criticism"],["fromrecord","I. F. Stone (1907-1989)","Verify it from the public record"],
    ["broadcast","Edward R. Murrow (1908-1965)","Broadcast integrity"],["thepress","A. J. Liebling (1904-1963)","The press & its critics"],
    ["fourtheories","Fred S. Siebert (1901-1982)","Four theories of the press"],["gatekeeper","David Manning White (1917-1993)","The gatekeeper"],
    ["editor","Ben Bradlee (1921-2014)","The editor & the fabricated story"],["whatsnews","Herbert J. Gans (1927-2024)","Deciding what's news"],
    ["objritual","Gaye Tuchman (b. 1943)","Objectivity as strategic ritual"],["sourcing","Carl Bernstein (b. 1944)","The discipline of sourcing"],
    ["objorigins","Michael Schudson (b. 1946)","The origins of objectivity"],["verification","Bill Kovach (1932-2021)","The elements of verification"]],
},

];
