// 8 Casebook game STRUCTURES for the "Machines & Structures" category.
// Same shape as one element of the GAMES array in generate_more.js.
// DESIGN ONLY: mystery setup + board + informants + 18-figure roster per game.
// No prose. Spine per game: OVERCLAIM (sensational-wrong), DISMISSAL (act-of-God),
// TRUTH (a concealed, systemic, provable cause). what.items order = [overclaim, dismissal, truth].
module.exports = [

// 1) HELICOPTER / ROTORCRAFT CRASH ------------------------------------------
{ id:"m_heli", title:"The Ridgeline Rotor", discipline:"Rotorcraft & Aeromechanics",
  teaser:"A charter helicopter dropped out of a clear sky onto the ridge. A bird strike that shattered the rotor? A freak mountain gust? Or a warning bolted into the logbook?",
  overclaimTag:"a bird strike or sabotage", truthTag:"a deferred gearbox flaw flown anyway",
  venue:"the Ridgeline rotorcraft inquiry", agent:"Investigator Cole Aldith", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Rotorcraft Pioneers", dossierName:"ROTORCRAFT & AEROMECHANICS PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Ridgeline rotorcraft inquiry",
  who:{truth:"hx_operator", items:[["hx_operator","Rourke Vane — charter-fleet operator"],["hx_pilot","The command pilot"],["hx_regulator","The aviation-safety inspector"]]},
  where:{truth:"hx_office", items:[["hx_rotor","The Rotor Head & Gearbox Bay"],["hx_cabin","The Cockpit & Flight Recorders"],["hx_office","The Operator's Maintenance Office"]]},
  what:{truth:"hx_gearbox", overclaim:"hx_strike", dismissal:"hx_gust", items:[["hx_strike","A bird strike or deliberate sabotage"],["hx_gust","A freak mountain gust — an act of God"],["hx_gearbox","A deferred gearbox flaw flown past its warning"]]},
  places:["hx_rotor","hx_cabin","hx_office"],
  chars:[["hx_mechanic","Mechanic Iris Dane","Line mechanic","🔧","M","the rotor bay","Turns the wrenches; logged the metal chips in the gearbox that kept coming back."],
         ["hx_analyst","The Flight-Data Analyst","Flight-recorder analyst","📈","F","the cockpit","Reads the recorders; the vibration trace was screaming before the rotor let go."],
         ["hx_clerk","The Clerk","Maintenance-records clerk","🗂","C","the office","Keeps the tech log — and the deferral that kept a flagged part flying."]],
  topics:[["hx_sikorsky","Igor Sikorsky (1889-1972)","The single main-rotor helicopter"],["hx_autorotation","Juan de la Cierva (1895-1936)","The autogiro, autorotation & the articulated rotor"],
    ["hx_focke","Heinrich Focke (1890-1979)","The first practical helicopter"],["hx_breguet","Louis Breguet (1880-1955)","Early rotary-wing flight"],
    ["hx_flettner","Anton Flettner (1885-1961)","Rotor control & the servo-flap"],["hx_young","Arthur M. Young (1905-1995)","Rotor stabilization & the Bell rotor"],
    ["hx_piasecki","Frank Piasecki (1919-2008)","The tandem-rotor helicopter"],["hx_betz","Albert Betz (1885-1968)","Rotor momentum theory & the Betz limit"],
    ["hx_glauert","Hermann Glauert (1892-1934)","Blade-element & airscrew theory"],["hx_zhukovsky","Nikolai Zhukovsky (1847-1921)","Aerofoil theory & rotor lift"],
    ["hx_gearlewis","Wilfred Lewis (1854-1929)","The gear-tooth strength equation"],["hx_bearing","Arvid Palmgren (1890-1971)","Rolling-bearing fatigue life"],
    ["hx_stribeck","Richard Stribeck (1861-1950)","Bearing friction & lubrication"],["hx_geardyn","Earle Buckingham (1887-1978)","Gear dynamics & wear"],
    ["hx_lcf","Louis F. Coffin (1917-1990)","Low-cycle fatigue"],["hx_manson","S. S. Manson (1919-2013)","Thermal fatigue & fatigue life"],
    ["hx_vibration","J. P. Den Hartog (1901-1989)","Mechanical vibration & resonance"],["hx_snfatigue","O. H. Basquin (S-N fatigue researcher)","The stress-life fatigue law"]],
},

// 2) LONG-SPAN BRIDGE COLLAPSE ----------------------------------------------
{ id:"m_bridge", title:"The Halloway Span", discipline:"Structural & Fracture Mechanics",
  teaser:"A long river bridge dropped a span into the water at rush hour. A barge that struck a pier? A once-in-history flood? Or a crack someone signed off?",
  overclaimTag:"a barge strike or attack", truthTag:"a fatigue crack past a skipped inspection",
  venue:"the Halloway bridge inquiry", agent:"Inspector Nora Selby", standingLabel:"Engineering credibility",
  readingShort:"Pioneers", readingLabel:"Structural & Fracture Pioneers", dossierName:"STRUCTURAL & FRACTURE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halloway bridge inquiry",
  who:{truth:"br_authority", items:[["br_authority","Gideon Marsh — bridge authority director"],["br_engineer","The maintenance engineer"],["br_inspector","The state bridge inspector"]]},
  where:{truth:"br_office", items:[["br_truss","The Truss & the Cracked Gusset"],["br_pier","The Piers & Bearings"],["br_office","The Bridge Authority Office"]]},
  what:{truth:"br_fatigue", overclaim:"br_strike", dismissal:"br_flood", items:[["br_strike","A barge strike or an attack on the span"],["br_flood","A freak flood scouring the pier — an act of God"],["br_fatigue","A fatigue crack ridden past a skipped inspection"]]},
  places:["br_truss","br_pier","br_office"],
  chars:[["br_rigger","Rigger Tom Vasa","Bridge steel rigger","🔧","R","the truss","Climbs the steel; found the gusset crack painted over more than once."],
         ["br_ndt","The NDT Technician","Non-destructive-test technician","🧲","N","the underdeck","Runs the crack detectors; the flaw showed on scans that were never re-run."],
         ["br_clerk","The Clerk","Authority records clerk","🗂","C","the office","Holds the inspection files — and the report that shelved the re-inspection."]],
  topics:[["br_griffith","A. A. Griffith (1893-1963)","The energy theory of fracture"],["br_irwin","George R. Irwin (1907-1998)","The stress-intensity factor"],
    ["br_paris","Paul C. Paris (1930-2017)","The law of fatigue-crack growth"],["br_rice","James R. Rice (b. 1940)","The J-integral & elastic-plastic fracture"],
    ["br_inglis","Charles Inglis (1875-1952)","Stress concentration at a crack"],["br_wells","Alan A. Wells (1924-2005)","Crack-tip opening displacement"],
    ["br_orowan","Egon Orowan (1902-1989)","Plasticity at the crack tip"],["br_miner","Milton A. Miner (cumulative-damage researcher)","The cumulative fatigue-damage rule"],
    ["br_ammann","Othmar Ammann (1879-1965)","Long-span suspension bridges"],["br_strauss","Joseph Strauss (1870-1938)","The Golden Gate Bridge"],
    ["br_ellet","Charles Ellet Jr. (1810-1862)","Early American suspension bridges"],["br_steinman","David B. Steinman (1886-1960)","Suspension-bridge design & aerodynamics"],
    ["br_moisseiff","Leon Moisseiff (1872-1943)","Deflection theory & the Tacoma Narrows lesson"],["br_bouch","Thomas Bouch (1822-1880)","The Tay Bridge disaster & wind load"],
    ["br_baker","Benjamin Baker (1840-1907)","The Forth Bridge & the cantilever"],["br_eiffel","Gustave Eiffel (1832-1923)","Iron structures & wind"],
    ["br_influence","Heinrich Müller-Breslau (1851-1925)","Influence lines & structural analysis"],["br_mohr","Christian Otto Mohr (1835-1918)","Mohr's circle & the analysis of stress"]],
},

// 3) STADIUM / ARENA ROOF COLLAPSE ------------------------------------------
{ id:"m_stadium", title:"The Coronet Arena Roof", discipline:"Structures & Crowd Dynamics",
  teaser:"An arena roof folded onto a packed stand during a sell-out. A bomb in the rafters? A freak snow load from a storm? Or a joint that was quietly cheapened?",
  overclaimTag:"a bomb or explosion", truthTag:"a cheapened connection under an ignored load",
  venue:"the Coronet Arena inquiry", agent:"Investigator Priya Lund", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Structures & Crowd Pioneers", dossierName:"STRUCTURES & CROWD-DYNAMICS PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Coronet Arena inquiry",
  who:{truth:"st_developer", items:[["st_developer","Vaughn Kroll — arena developer"],["st_engineer","The structural engineer of record"],["st_inspector","The building-control inspector"]]},
  where:{truth:"st_office", items:[["st_roof","The Roof Trusses & Node Connections"],["st_stand","The Stand & Concourse"],["st_office","The Developer's Project Office"]]},
  what:{truth:"st_connection", overclaim:"st_bomb", dismissal:"st_snow", items:[["st_bomb","A bomb or explosion in the structure"],["st_snow","A freak snow load from a storm — an act of God"],["st_connection","A value-engineered connection under an ignored crowd-and-snow load"]]},
  places:["st_roof","st_stand","st_office"],
  chars:[["st_erector","Steelworker Bo Renn","Roof steel erector","🔧","B","the roof","Bolted the trusses; watched the engineered node swapped for a cheaper splice."],
         ["st_steward","The Head Steward","Crowd-safety steward","📣","S","the stand","Packs the stands; knows the section was loaded far past its posted count."],
         ["st_clerk","The Clerk","Project records clerk","🗂","C","the office","Keeps the drawings — and the value-engineering change that thinned the joint."]],
  topics:[["st_shukhov","Vladimir Shukhov (1853-1939)","Steel lattice shells & tension roofs"],["st_otto","Frei Otto (1925-2015)","Lightweight tensile & membrane roofs"],
    ["st_fuller","Buckminster Fuller (1895-1983)","The geodesic dome"],["st_nervi","Pier Luigi Nervi (1891-1979)","Reinforced-concrete stadium roofs"],
    ["st_candela","Félix Candela (1910-1997)","Thin-shell concrete roofs"],["st_torroja","Eduardo Torroja (1899-1961)","The cantilevered grandstand shell"],
    ["st_leonhardt","Fritz Leonhardt (1909-1999)","The cable-net stadium roof"],["st_schlaich","Jörg Schlaich (1934-2021)","Lightweight cable & membrane roofs"],
    ["st_geiger","David Geiger (1935-1989)","The cable-dome & air-supported roof"],["st_mengeringhausen","Max Mengeringhausen (1903-1988)","The space-frame node connector"],
    ["st_wachsmann","Konrad Wachsmann (1901-1980)","Space-frame joints & prefabrication"],["st_arup","Ove Arup (1895-1988)","The engineering of great roof shells"],
    ["st_prager","William Prager (1903-1980)","Limit analysis & plastic collapse"],["st_cornell","C. Allin Cornell (1938-2007)","Structural reliability & load factors"],
    ["st_foppl","August Föppl (1854-1924)","Space trusses & framework analysis"],["st_fruin","John J. Fruin (pedestrian-dynamics researcher)","Pedestrian level of service & crowd density"],
    ["st_helbing","Dirk Helbing (b. 1965)","The social-force model of crowd flow"],["st_still","G. Keith Still (crowd-safety researcher)","Crowd dynamics & venue safety"]],
},

// 4) OFFSHORE DRILLING RIG BLOWOUT ------------------------------------------
{ id:"m_rig", title:"The Deepwater Meridian", discipline:"Drilling & Well Control",
  teaser:"An offshore rig blew out and burned at the wellhead. An enemy strike on the platform? A freak pocket of gas no one could predict? Or a safety test that was skipped?",
  overclaimTag:"an attack on the rig", truthTag:"a skipped cement test and a disabled preventer",
  venue:"the Meridian blowout inquiry", agent:"Investigator Ike Marlow", standingLabel:"Commission credibility",
  readingShort:"Pioneers", readingLabel:"Drilling & Well-Control Pioneers", dossierName:"DRILLING & WELL-CONTROL PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Meridian blowout inquiry",
  who:{truth:"rg_operator", items:[["rg_operator","Dalton Voss — well operator's rig manager"],["rg_driller","The rig's driller"],["rg_regulator","The offshore-safety regulator"]]},
  where:{truth:"rg_office", items:[["rg_wellhead","The Wellhead & Blowout Preventer"],["rg_floor","The Drill Floor & Mud Logging"],["rg_office","The Operator's Onshore Office"]]},
  what:{truth:"rg_wellcontrol", overclaim:"rg_attack", dismissal:"rg_pocket", items:[["rg_attack","An attack or sabotage on the platform"],["rg_pocket","A freak gas pocket — an act of God"],["rg_wellcontrol","A skipped cement test and a disabled blowout preventer"]]},
  places:["rg_wellhead","rg_floor","rg_office"],
  chars:[["rg_roughneck","Roughneck Sal Ortiz","Drill-floor roughneck","🔧","R","the drill floor","Works the tongs; saw the well kick back mud while the alarms were bypassed."],
         ["rg_mudlogger","The Mud Logger","Mud-logging technician","📈","M","the logging cabin","Reads the returns; the pressure test failed and got recorded as a pass."],
         ["rg_clerk","The Clerk","Operator records clerk","🗂","C","the office","Holds the well plan — and the order to skip the cement bond log to save a day."]],
  topics:[["rg_bernoulli","Daniel Bernoulli (1700-1782)","Fluid pressure & flow in the well"],["rg_torricelli","Evangelista Torricelli (1608-1647)","Pressure head & efflux"],
    ["rg_boyle","Robert Boyle (1627-1691)","The gas law & expanding gas"],["rg_bingham","Eugene C. Bingham (1878-1945)","Drilling-mud rheology"],
    ["rg_hubbert","M. King Hubbert (1903-1989)","Subsurface pressure & rock fracture"],["rg_muskat","Morris Muskat (1906-1998)","Flow through porous reservoir rock"],
    ["rg_pratt","Wallace Pratt (1885-1981)","Petroleum geology & the reservoir"],["rg_lucas","Anthony F. Lucas (1855-1921)","The gusher & the danger of blowout"],
    ["rg_hughes","Howard Hughes Sr. (1869-1924)","The roller-cone drill bit"],["rg_schlumberger","Conrad Schlumberger (1878-1936)","Electrical well logging"],
    ["rg_halliburton","Erle P. Halliburton (1892-1957)","Oil-well cementing"],["rg_abercrombie","James S. Abercrombie (blowout-preventer co-inventor)","The ram blowout preventer"],
    ["rg_cameron","Harry S. Cameron (well-control equipment pioneer)","Blowout-preventer engineering"],["rg_kinley","Myron Kinley (1898-1978)","Blowout & well-fire control"],
    ["rg_adair","Red Adair (1915-2004)","Offshore blowout firefighting"],["rg_morison","J. R. Morison (offshore wave-load researcher)","Wave forces on offshore structures"],
    ["rg_collipp","Bruce Collipp (semisubmersible-rig pioneer)","The floating offshore rig"],["rg_lees","Frank P. Lees (1931-1999)","Process safety & loss prevention"]],
},

// 5) TUNNEL / METRO-BORE COLLAPSE -------------------------------------------
{ id:"m_tunnel", title:"The Kingsgate Bore", discipline:"Tunnelling & Ground Engineering",
  teaser:"A metro tunnel under the city caved in and swallowed the street above. A gas explosion underground? A freak sinkhole in old ground? Or monitoring that was switched off?",
  overclaimTag:"a gas explosion", truthTag:"cut grouting and ignored settlement gauges",
  venue:"the Kingsgate tunnel inquiry", agent:"Inspector Mabel Crane", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Tunnelling & Ground Pioneers", dossierName:"TUNNELLING & GROUND-ENGINEERING PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Kingsgate tunnel inquiry",
  who:{truth:"tn_contractor", items:[["tn_contractor","Emil Radek — tunnelling contractor"],["tn_engineer","The tunnel design engineer"],["tn_inspector","The transit-authority inspector"]]},
  where:{truth:"tn_office", items:[["tn_face","The Tunnel Face & TBM"],["tn_surface","The Surface & Settlement Markers"],["tn_office","The Contractor's Site Office"]]},
  what:{truth:"tn_settlement", overclaim:"tn_explosion", dismissal:"tn_sinkhole", items:[["tn_explosion","A gas explosion in the bore"],["tn_sinkhole","A freak natural sinkhole — an act of God"],["tn_settlement","Cut grouting and ignored ground-settlement monitoring"]]},
  places:["tn_face","tn_surface","tn_office"],
  chars:[["tn_miner","Miner Jud Kolb","Tunnel-face miner","⛏","J","the tunnel face","Works the shield; watched the grout runs cut short to keep the machine moving."],
         ["tn_surveyor","The Monitoring Surveyor","Ground-settlement surveyor","📐","S","the surface","Reads the surface markers; the settlement gauges were climbing for days."],
         ["tn_clerk","The Clerk","Site records clerk","🗂","C","the office","Keeps the logs — and the memo that halved the grouting to hold the schedule."]],
  topics:[["tn_marcbrunel","Marc Isambard Brunel (1769-1849)","The tunnelling shield"],["tn_barlow","Peter W. Barlow (1809-1885)","The cylindrical tunnelling shield"],
    ["tn_greathead","James Henry Greathead (1844-1896)","The shield & compressed-air tunnelling"],["tn_moir","Ernest William Moir (1862-1933)","Caisson & compressed-air work"],
    ["tn_rabcewicz","Ladislaus von Rabcewicz (1893-1975)","The New Austrian Tunnelling Method"],["tn_muller","Leopold Müller (1908-1988)","Rock mechanics & tunnel support"],
    ["tn_stini","Josef Stini (1880-1958)","Engineering geology for tunnels"],["tn_robbins","James S. Robbins (1913-1958)","The modern tunnel-boring machine"],
    ["tn_muirwood","Alan Muir Wood (1921-2009)","Soft-ground tunnelling"],["tn_mair","Robert Mair (ground-settlement researcher, b. 1950)","Tunnelling-induced ground settlement"],
    ["tn_berigny","Charles Bérigny (grouting pioneer)","Pressure grouting of ground"],["tn_proctor","Ralph R. Proctor (soil-compaction researcher)","Compaction & the Proctor test"],
    ["tn_barton","Nick Barton (rock-mechanics researcher)","The Q-system for rock tunnels"],["tn_bieniawski","Z. T. Bieniawski (rock-mechanics researcher)","The rock-mass rating"],
    ["tn_kerisel","Jean Kérisel (1908-2005)","Earth pressure & deep foundations"],["tn_deere","Don U. Deere (1922-2011)","The rock quality designation (RQD)"],
    ["tn_hoek","Evert Hoek (1933-2024)","Rock-mass strength & the Hoek-Brown criterion"],["tn_westergaard","Harald M. Westergaard (1888-1950)","Stresses in soils & slabs"]],
},

// 6) AUTOMOTIVE ADAS / SELF-DRIVING FATAL CRASH -----------------------------
{ id:"m_adas", title:"The Autopilot on Vane Street", discipline:"Vehicle Automation & Safety",
  teaser:"A self-driving car ran down a pedestrian at night, its autopilot engaged. Was the car hacked and hijacked? A one-in-a-million glitch? Or a safeguard someone switched off?",
  overclaimTag:"a hack or remote hijack", truthTag:"a sensor blind spot and a disabled driver-monitor",
  venue:"the Vane Street autonomy inquiry", agent:"Investigator Dana Okafor", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Vehicle-Automation Pioneers", dossierName:"VEHICLE-AUTOMATION & SAFETY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Vane Street autonomy inquiry",
  who:{truth:"ad_maker", items:[["ad_maker","Sloane Pace — self-driving program lead"],["ad_driver","The backup safety driver"],["ad_regulator","The transport-safety regulator"]]},
  where:{truth:"ad_office", items:[["ad_vehicle","The Vehicle & Its Sensors"],["ad_datacenter","The Telemetry & Perception Logs"],["ad_office","The Program's Development Office"]]},
  what:{truth:"ad_sensorsafeguard", overclaim:"ad_hack", dismissal:"ad_glitch", items:[["ad_hack","A hack or remote hijack of the car"],["ad_glitch","A freak one-off software glitch — bad luck"],["ad_sensorsafeguard","A sensor blind spot met by a disabled driver-monitoring safeguard"]]},
  places:["ad_vehicle","ad_datacenter","ad_office"],
  chars:[["ad_tech","Field Tech Ravi Sen","Vehicle field technician","🔧","R","the vehicle","Services the sensors; saw the car repeatedly miss objects in the dark."],
         ["ad_analyst","The Perception Analyst","Perception-log analyst","📈","P","the data centre","Reads the logs; the car classified the victim three ways and braked too late."],
         ["ad_clerk","The Clerk","Program records clerk","🗂","C","the office","Holds the release notes — and the ticket that disabled the driver-attention alarm."]],
  topics:[["ad_nader","Ralph Nader (b. 1934)","Automobile safety & crashworthiness"],["ad_bohlin","Nils Bohlin (1920-2002)","The three-point seatbelt"],
    ["ad_barenyi","Béla Barényi (1907-1997)","The crumple zone & passive safety"],["ad_haddon","William Haddon Jr. (1926-1985)","The epidemiology of crashes & the Haddon matrix"],
    ["ad_stapp","John Paul Stapp (1910-1999)","Human tolerance to deceleration"],["ad_dehaven","Hugh DeHaven (1895-1980)","Crash survival & occupant packaging"],
    ["ad_hulsmeyer","Christian Hülsmeyer (1881-1957)","Radar & obstacle detection"],["ad_maiman","Theodore Maiman (1927-2007)","The laser behind lidar"],
    ["ad_fossum","Eric Fossum (image-sensor researcher)","The CMOS camera sensor"],["ad_dickmanns","Ernst Dickmanns (b. 1936)","Machine vision & the first self-driving car"],
    ["ad_parkinson","Bradford Parkinson (b. 1935)","The GPS navigation system"],["ad_kalman","Rudolf E. Kálmán (1930-2016)","The Kalman filter & sensor fusion"],
    ["ad_thrun","Sebastian Thrun (b. 1967)","Autonomous driving & the DARPA challenge"],["ad_bainbridge","Lisanne Bainbridge (automation-ironies researcher)","The ironies of automation"],
    ["ad_parasuraman","Raja Parasuraman (1950-2015)","Automation complacency & vigilance"],["ad_sheridan","Thomas B. Sheridan (b. 1929)","Supervisory control of automation"],
    ["ad_endsley","Mica Endsley (b. 1960)","Situation awareness"],["ad_moray","Neville Moray (1935-2017)","Attention & mental workload"]],
},

// 7) MINE TAILINGS-DAM FAILURE ----------------------------------------------
{ id:"m_tailings", title:"The Serra Verde Tailings Dam", discipline:"Slope Stability & Soil Liquefaction",
  teaser:"A mine's tailings dam liquefied in seconds and buried the works below. Was it a blast or an earthquake? A freak downpour beyond any design? Or gauges that were read and ignored?",
  overclaimTag:"a blast or an earthquake", truthTag:"liquefaction the piezometers foretold",
  venue:"the Serra Verde tailings inquiry", agent:"Inspector Rui Alvares", standingLabel:"Engineering credibility",
  readingShort:"Pioneers", readingLabel:"Slope & Soil Pioneers", dossierName:"SLOPE-STABILITY & SOIL PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Serra Verde tailings inquiry",
  who:{truth:"tl_miningco", items:[["tl_miningco","Bruna Teixeira — mine operations director"],["tl_engineer","The dam-of-record engineer"],["tl_auditor","The independent dam auditor"]]},
  where:{truth:"tl_office", items:[["tl_crest","The Raised Dam Crest"],["tl_toe","The Toe & Piezometers"],["tl_office","The Mine's Operations Office"]]},
  what:{truth:"tl_liquefaction", overclaim:"tl_quake", dismissal:"tl_rain", items:[["tl_quake","A blast or an earthquake shaking the dam"],["tl_rain","A freak downpour overtopping the dam — an act of God"],["tl_liquefaction","Static liquefaction of a raised dam its piezometers foretold"]]},
  places:["tl_crest","tl_toe","tl_office"],
  chars:[["tl_walker","Dam-Walker Ana Reis","Tailings-dam walker","💧","A","the toe","Walks the toe daily; saw wet seeps and bulging the reports called normal."],
         ["tl_reader","The Instrument Reader","Geotechnical-instrument reader","📟","I","the crest","Downloads the piezometers; the pore-pressures were red for weeks."],
         ["tl_clerk","The Clerk","Operations records clerk","🗂","C","the office","Keeps the safety file — and the raise approved despite the auditor's warning."]],
  topics:[["tl_fellenius","Wolmar Fellenius (1876-1957)","The slip-circle method"],["tl_bishop","Alec W. Bishop (1920-1988)","The method of slices & slope stability"],
    ["tl_janbu","Nilmar Janbu (1921-2013)","Generalized slope-stability analysis"],["tl_morgenstern","Norbert R. Morgenstern (b. 1935)","Slope stability & tailings-dam safety"],
    ["tl_bjerrum","Laurits Bjerrum (1918-1973)","Soft-clay strength & landslides"],["tl_seed","Harry Bolton Seed (1922-1989)","Cyclic loading & liquefaction"],
    ["tl_ishihara","Kenji Ishihara (b. 1934)","The liquefaction of sands"],["tl_castro","Gonzalo Castro (static-liquefaction researcher)","Steady-state & static liquefaction"],
    ["tl_poulos","Steve J. Poulos (steady-state-strength researcher)","The steady-state strength line"],["tl_biot","Maurice A. Biot (1905-1985)","Poroelasticity & pore pressure"],
    ["tl_roscoe","Kenneth H. Roscoe (1914-1970)","Critical-state soil mechanics"],["tl_schofield","Andrew N. Schofield (b. 1926)","Critical state & centrifuge modelling"],
    ["tl_wroth","Peter Wroth (1929-1991)","Critical-state soil behaviour"],["tl_blight","Geoffrey E. Blight (tailings-dam researcher)","The mechanics of tailings dams"],
    ["tl_wilson","Stanley D. Wilson (geotechnical-instrumentation pioneer)","The piezometer & slope inclinometer"],["tl_whitman","Robert V. Whitman (1928-2012)","Geotechnical risk & reliability"],
    ["tl_sowers","George F. Sowers (1921-1996)","Embankment & foundation failures"],["tl_hoover","Herbert Hoover (1874-1964)","Mining engineering & ore extraction"]],
},

// 8) RAIL LEVEL-CROSSING / SIGNALLING COLLISION -----------------------------
{ id:"m_railx", title:"The Marsh Lane Crossing", discipline:"Railway Signalling & Interlocking",
  teaser:"An express hit a stopped train at a level crossing that should have held it back. A bomb on the line? A driver who ran the signal? Or an interlock someone jumped?",
  overclaimTag:"sabotage on the line", truthTag:"a jumped interlock and deferred maintenance",
  venue:"the Marsh Lane crossing inquiry", agent:"Investigator Glen Ashby", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Railway-Signalling Pioneers", dossierName:"RAILWAY-SIGNALLING PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Marsh Lane crossing inquiry",
  who:{truth:"rx_infra", items:[["rx_infra","Perren Voss — signalling infrastructure manager"],["rx_driver","The express driver"],["rx_regulator","The rail-safety inspector"]]},
  where:{truth:"rx_office", items:[["rx_crossing","The Crossing & Points"],["rx_signalbox","The Signalling Control Centre"],["rx_office","The Infrastructure Head Office"]]},
  what:{truth:"rx_interlock", overclaim:"rx_sabotage", dismissal:"rx_driver", items:[["rx_sabotage","Sabotage — something left on the line"],["rx_driver","Simple driver error — a signal run by"],["rx_interlock","A bypassed interlock and deferred signalling maintenance"]]},
  places:["rx_crossing","rx_signalbox","rx_office"],
  chars:[["rx_technician","S&T Tech Mara Doss","Signal & telegraph technician","🔧","M","the crossing","Maintains the gear; knows which interlock was strapped out to keep trains running."],
         ["rx_signaller","The Signaller","Signalling-centre operator","🚦","S","the control centre","Works the panel; saw the crossing show clear with a train still standing on it."],
         ["rx_clerk","The Clerk","Infrastructure records clerk","🗂","C","the office","Holds the fault log — and the deferral that left the interlock unrepaired."]],
  topics:[["rx_wheatstone","Charles Wheatstone (1802-1875)","The electric telegraph & railway signalling"],["rx_cooke","William Fothergill Cooke (1806-1879)","The block-telegraph system"],
    ["rx_gregory","Charles Hutton Gregory (1817-1898)","The semaphore railway signal"],["rx_sykes","William Robert Sykes (1840-1917)","Lock-and-block interlocking"],
    ["rx_tyer","Edward Tyer (1830-1912)","The single-line token & tablet"],["rx_hall","Thomas S. Hall (1827-1880)","Automatic signalling"],
    ["rx_robinson","William Robinson (1840-1921)","The closed track circuit"],["rx_welch","Ashbel Welch (1809-1882)","The manual block system"],
    ["rx_raven","Vincent Raven (1859-1934)","Early automatic train control"],["rx_gresham","James Gresham (1836-1914)","The automatic vacuum brake"],
    ["rx_raynar","H. Raynar Wilson (railway-signalling historian)","Signalling principles & accident lessons"],["rx_fox","Charles Fox (1810-1874)","The railway switch & points"],
    ["rx_trevithick","Richard Trevithick (1771-1833)","The first steam locomotive"],["rx_locke","Joseph Locke (1805-1860)","Railway civil engineering"],
    ["rx_gooch","Daniel Gooch (1816-1889)","Locomotive engineering & the broad gauge"],["rx_stroudley","William Stroudley (1833-1889)","Locomotive design & braking"],
    ["rx_bradshaw","George Bradshaw (1801-1853)","The railway timetable & scheduling"],["rx_ramsbottom","John Ramsbottom (1814-1897)","The safety valve & water trough"]],
},

];
