// Casebook game STRUCTURES for the "Energy & Matter" category.
// DESIGN ONLY — mystery setup + board + informants + 18-figure roster per game.
// Same field-for-field shape as one element of generate_more.js GAMES array.
// All rosters cross-checked against batch/used_figures.txt — no reuse, no repeats.

module.exports = [

{ id:"t_refinery", title:"The Halden Refinery Fire", discipline:"Process Safety & Combustion Engineering",
  teaser:"A refinery unit erupted in a fireball at dawn. An attack on the plant? A freak spark? Or a safety system quietly switched off?",
  overclaimTag:"sabotage or an attack", truthTag:"a disabled safety system & ignored corrosion",
  venue:"the Halden refinery inquiry", agent:"Investigator Cara Mendel", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Combustion & Corrosion Pioneers", dossierName:"COMBUSTION & CORROSION PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halden refinery inquiry",
  who:{truth:"operator", items:[["operator","Garon Voss — refinery operator"],["superintendent","The unit superintendent"],["inspector","The state safety inspector"]]},
  where:{truth:"office", items:[["units","The Process Units & Flare"],["control","The Control Room"],["office","The Operator's Corporate Office"]]},
  what:{truth:"neglect", overclaim:"attack", dismissal:"freak", items:[["attack","Sabotage or a deliberate blast"],["freak","A freak ignition — an act of God"],["neglect","A disabled relief/flare system & ignored corrosion"]]},
  places:["units","control","office"],
  chars:[["unitop","Operator Delia Fenn","Unit operator","🔥","U","the process units","Ran the tower; logged the relief valve that was carded out of service."],
         ["boardop","The Board Operator","Control-room operator","🎛","B","the control room","Watched the pressure climb with the flare down and no way to vent."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the corrosion reports and the deferral memo that shelved the fix."]],
  topics:[["rf_carnot","Sadi Carnot (1796-1832)","Heat engines & the second law"],["rf_clausius","Rudolf Clausius (1822-1888)","Entropy & the second law"],
    ["rf_joule","James Prescott Joule (1818-1889)","The mechanical equivalent of heat"],["rf_boltzmann","Ludwig Boltzmann (1844-1906)","Statistical thermodynamics & heat"],
    ["rf_clapeyron","Benoit Clapeyron (1799-1864)","Vapor pressure & the Clausius-Clapeyron relation"],["rf_hess","Germain Hess (1802-1850)","Thermochemistry & heats of reaction"],
    ["rf_berthelot","Marcellin Berthelot (1827-1907)","Thermochemistry & explosives"],["rf_bunsen","Robert Bunsen (1811-1899)","The burner & flame chemistry"],
    ["rf_davy","Humphry Davy (1778-1829)","The safety lamp & flame arrest"],["rf_lewis","Bernard Lewis (1899-1993)","Combustion, flames & explosions"],
    ["rf_zeldovich","Yakov Zeldovich (1914-1987)","Detonation & flame theory"],["rf_fk","David Frank-Kamenetskii (1910-1970)","Thermal explosion theory"],
    ["rf_pourbaix","Marcel Pourbaix (1904-1998)","Corrosion & potential-pH diagrams"],["rf_uhlig","Herbert H. Uhlig (1907-1993)","Corrosion engineering"],
    ["rf_shukhov","Vladimir Shukhov (1853-1939)","Oil refining & thermal cracking"],["rf_burton","William M. Burton (1865-1954)","Thermal cracking of petroleum"],
    ["rf_houdry","Eugene Houdry (1892-1962)","Catalytic cracking"],["rf_papin","Denis Papin (1647-1713)","The pressure vessel & the safety valve"]],
},

{ id:"t_dust", title:"The Corriston Mill Blast", discipline:"Combustion & Dust-Explosion Engineering",
  teaser:"A sugar mill blew apart floor by floor one evening. A bomb? A one-in-a-million spark? Or dust someone let pile up?",
  overclaimTag:"sabotage or a bomb", truthTag:"neglected dust with cut cleaning & ventilation",
  venue:"the Corriston mill inquiry", agent:"Inspector Nash Verel", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Combustion Pioneers", dossierName:"COMBUSTION & EXPLOSION PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Corriston mill inquiry",
  who:{truth:"owner", items:[["owner","Corwin Ash — plant owner"],["manager","The production manager"],["inspector","The safety inspector"]]},
  where:{truth:"office", items:[["floor","The Production Floor & Ducts"],["mcc","The Motor Control Room"],["office","The Owner's Plant Office"]]},
  what:{truth:"neglect", overclaim:"attack", dismissal:"freak", items:[["attack","Sabotage or a bomb"],["freak","A freak spark — bad luck"],["neglect","Cut housekeeping & ventilation, with dust left to accumulate"]]},
  places:["floor","mcc","office"],
  chars:[["sweeper","Sweeper Ruiz","Housekeeping hand","🧹","S","the production floor","Sweeps the catwalks; knows the crew was cut and the dust lay inches deep."],
         ["electrician","The Electrician","Plant electrician","⚡","E","the motor room","Wires the motors; saw the ductwork clogged and the fans switched off."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the cleaning logs and the memo that ended the night sweep."]],
  topics:[["du_boyle","Robert Boyle (1627-1691)","Air, pressure & combustion"],["du_priestley","Joseph Priestley (1733-1804)","Oxygen & combustion"],
    ["du_scheele","Carl Wilhelm Scheele (1742-1786)","The discovery of oxygen"],["du_lomonosov","Mikhail Lomonosov (1711-1765)","Combustion & conservation of mass"],
    ["du_gaylussac","Joseph Louis Gay-Lussac (1778-1850)","Gas pressure, temperature & explosion"],["du_avogadro","Amedeo Avogadro (1776-1856)","Gases, the mole & fuel-air ratio"],
    ["du_mallard","Ernest-Francois Mallard (1833-1894)","Flame propagation in gases"],["du_vieille","Paul Vieille (1854-1934)","Detonation & the blast wave"],
    ["du_mach","Ernst Mach (1838-1916)","Shock waves"],["du_hinshelwood","Cyril Norman Hinshelwood (1897-1967)","Chain reactions & combustion kinetics"],
    ["du_bartknecht","Wolfgang Bartknecht (dust-explosion researcher)","Dust-explosion severity & venting"],["du_eckhoff","Rolf K. Eckhoff (dust-explosion researcher)","Dust explosions & prevention"],
    ["du_galloway","William Galloway (coal-dust explosion researcher)","Coal-dust explosions"],["du_haldane","John Scott Haldane (1860-1936)","Mine gases & ventilation"],
    ["du_bagnold","Ralph A. Bagnold (1896-1990)","The physics of blown particles"],["du_gray","Stephen Gray (1666-1736)","Electrostatic charge & conduction"],
    ["du_lichtenberg","Georg Christoph Lichtenberg (1742-1799)","Static discharge"],["du_fourier","Joseph Fourier (1768-1830)","Heat conduction & thermal build-up"]],
},

{ id:"t_battery", title:"The Kelso Grid-Battery Fire", discipline:"Electrochemistry & Battery Safety",
  teaser:"A grid battery bank caught fire and burned for days. Arson? A freak cell? Or a safeguard someone switched off?",
  overclaimTag:"arson or sabotage", truthTag:"a cell defect & a disabled safeguard",
  venue:"the Kelso battery-fire inquiry", agent:"Investigator Pier Solano", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Battery & Electrochemistry Pioneers", dossierName:"BATTERY & ELECTROCHEMISTRY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Kelso battery-fire inquiry",
  who:{truth:"maker", items:[["maker","Elena Corso — battery manufacturer"],["operator","The storage-site operator"],["regulator","The grid safety regulator"]]},
  where:{truth:"office", items:[["yard","The Battery Yard & Racks"],["bms","The Control & BMS Room"],["office","The Manufacturer's Design Office"]]},
  what:{truth:"defect", overclaim:"attack", dismissal:"freak", items:[["attack","Arson or sabotage"],["freak","A freak cell failure — one in a million"],["defect","A cell defect with the battery-management & cooling safeguard disabled"]]},
  places:["yard","bms","office"],
  chars:[["tech","Technician Oyaro","Battery technician","🔋","T","the battery yard","Racks the modules; flagged the cells that ran hot and swollen."],
         ["bmseng","The BMS Engineer","Battery-management engineer","🖥","M","the control room","Reads the cell data; the thermal cutoff was disabled to stop nuisance trips."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the cell-test files and the recall notice that never went out."]],
  topics:[["bt_galvani","Luigi Galvani (1737-1798)","Galvanic action & the cell"],["bt_daniell","John Frederic Daniell (1790-1845)","The Daniell cell"],
    ["bt_grove","William Robert Grove (1811-1896)","The fuel cell"],["bt_plante","Gaston Plante (1834-1889)","The lead-acid battery"],
    ["bt_leclanche","Georges Leclanche (1839-1882)","The dry cell"],["bt_jungner","Waldemar Jungner (1869-1924)","The nickel-cadmium cell"],
    ["bt_edison","Thomas Edison (1847-1931)","The nickel-iron battery"],["bt_nernst","Walther Nernst (1864-1941)","Electrode potentials & the Nernst equation"],
    ["bt_tafel","Julius Tafel (1862-1918)","Electrode kinetics & the Tafel equation"],["bt_frumkin","Alexander Frumkin (1895-1976)","Electrochemical kinetics & the double layer"],
    ["bt_whittingham","M. Stanley Whittingham (b. 1941)","Intercalation & the lithium battery"],["bt_goodenough","John B. Goodenough (1922-2023)","The lithium-ion cathode"],
    ["bt_yoshino","Akira Yoshino (b. 1948)","The lithium-ion battery"],["bt_yazami","Rachid Yazami (b. 1953)","The graphite anode"],
    ["bt_armand","Michel Armand (b. 1946)","Electrolytes & battery materials"],["bt_tarascon","Jean-Marie Tarascon (b. 1953)","Lithium-ion materials & safety"],
    ["bt_newman","John Newman (electrochemical engineer)","Battery modeling & thermal runaway"],["bt_peltier","Jean-Charles Peltier (1785-1845)","Thermoelectric heating & cooling"]],
},

{ id:"t_pipeline", title:"The Brant Hollow Pipeline", discipline:"Pipeline Integrity & Fluid Mechanics",
  teaser:"A gas main ruptured and levelled a street block. A deliberate strike? An act of God? Or corrosion an inspection would have caught?",
  overclaimTag:"sabotage or a strike", truthTag:"corrosion & a skipped inline inspection",
  venue:"the Brant Hollow pipeline inquiry", agent:"Investigator Rhea Colton", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Fluid-Flow & Corrosion Pioneers", dossierName:"FLUID-FLOW & CORROSION PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Brant Hollow pipeline inquiry",
  who:{truth:"operator", items:[["operator","Hollis Trask — pipeline operator"],["controller","The gas control dispatcher"],["regulator","The pipeline safety regulator"]]},
  where:{truth:"office", items:[["rightofway","The Right-of-Way & Rupture Site"],["control","The Gas Control Center"],["office","The Operator's Integrity Office"]]},
  what:{truth:"corrosion", overclaim:"attack", dismissal:"freak", items:[["attack","Sabotage or a third-party strike"],["freak","A freak ground shift — an act of God"],["corrosion","Advanced corrosion with the inline inspection skipped"]]},
  places:["rightofway","control","office"],
  chars:[["patrol","Line-Walker Dumas","Pipeline patroller","🚶","P","the right-of-way","Walks the line; reported the bubbling ground and bare, pitted pipe."],
         ["dispatch","The Dispatcher","Gas-control dispatcher","🖥","D","the control center","Watched the pressure drop; the SCADA alarm was standing when it let go."],
         ["clerk","The Clerk","Integrity-records clerk","🗂","C","the office","Keeps the inspection schedule and the pig run that was cancelled."]],
  topics:[["pp_bernoulli","Daniel Bernoulli (1700-1782)","Flow, pressure & Bernoulli's principle"],["pp_hagen","Gotthilf Hagen (1797-1884)","Laminar flow in pipes"],
    ["pp_poiseuille","Jean Poiseuille (1797-1869)","Viscous flow in pipes"],["pp_weisbach","Julius Weisbach (1806-1871)","Pipe friction & head loss"],
    ["pp_moody","Lewis Ferry Moody (1880-1953)","The Moody friction chart"],["pp_colebrook","Cyril F. Colebrook (pipe-flow engineer)","Pipe roughness & friction"],
    ["pp_joukowsky","Nikolai Joukowsky (1847-1921)","Water hammer & pressure surge"],["pp_vdwaals","Johannes van der Waals (1837-1923)","Real gases at high pressure"],
    ["pp_graham","Thomas Graham (1805-1869)","Gas diffusion & leakage"],["pp_wagner","Carl Wagner (1901-1977)","Oxidation & corrosion theory"],
    ["pp_fontana","Mars G. Fontana (1910-1988)","Corrosion engineering"],["pp_hackerman","Norman Hackerman (1912-2007)","Corrosion inhibition & surfaces"],
    ["pp_kuhn","Robert J. Kuhn (cathodic-protection engineer)","Pipeline cathodic protection"],["pp_inglis","Charles Inglis (1875-1952)","Stress concentration at flaws"],
    ["pp_griffith","A. A. Griffith (1893-1963)","Brittle fracture & crack growth"],["pp_irwin","George R. Irwin (1907-1998)","Fracture mechanics & stress intensity"],
    ["pp_firestone","Floyd Firestone (1898-1986)","Ultrasonic flaw detection"],["pp_venturi","Giovanni Battista Venturi (1746-1822)","The Venturi effect & flow metering"]],
},

{ id:"t_wind", title:"The Fenmark Turbine Collapse", discipline:"Wind Energy & Fatigue Engineering",
  teaser:"A wind turbine threw a blade and toppled its tower. Sabotage? A freak gust? Or fatigue that maintenance would have found?",
  overclaimTag:"sabotage or a strike", truthTag:"blade & bolt fatigue with maintenance skipped",
  venue:"the Fenmark turbine inquiry", agent:"Inspector Yara Doss", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Wind & Fatigue Pioneers", dossierName:"WIND & FATIGUE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Fenmark turbine inquiry",
  who:{truth:"operator", items:[["operator","Sylvie Renn — wind-farm operator"],["technician","The turbine service lead"],["regulator","The turbine safety regulator"]]},
  where:{truth:"office", items:[["nacelle","The Nacelle & Rotor"],["scada","The SCADA Control Hut"],["office","The Operator's Asset Office"]]},
  what:{truth:"fatigue", overclaim:"attack", dismissal:"freak", items:[["attack","Sabotage or a strike on the tower"],["freak","A freak gust — an act of God"],["fatigue","Blade & bolt fatigue with maintenance skipped"]]},
  places:["nacelle","scada","office"],
  chars:[["climber","Blade Tech Aro","Rope-access technician","🧗","A","the nacelle","Climbs the blades; photographed the cracked root and loose hub bolts."],
         ["scadaop","The SCADA Operator","Control-hut operator","🖥","S","the control hut","Reads the vibration alarms that were muted to keep the turbine turning."],
         ["clerk","The Clerk","Asset-records clerk","🗂","C","the office","Keeps the service logs and the maintenance rounds that were skipped."]],
  topics:[["wd_betz","Albert Betz (1885-1968)","The Betz limit & wind-turbine theory"],["wd_lacour","Poul la Cour (1846-1908)","The electricity-generating windmill"],
    ["wd_brush","Charles F. Brush (1849-1929)","The first automatic wind generator"],["wd_juul","Johannes Juul (1887-1969)","AC wind power & the Gedser turbine"],
    ["wd_hutter","Ulrich Hutter (1910-1990)","Modern wind-turbine blade design"],["wd_darrieus","Georges Darrieus (1888-1979)","The vertical-axis wind turbine"],
    ["wd_savonius","Sigurd Savonius (1884-1931)","The Savonius rotor"],["wd_glauert","Hermann Glauert (1892-1934)","Blade-element momentum & rotor aerodynamics"],
    ["wd_kutta","Martin Kutta (1867-1944)","Airfoil lift theory"],["wd_rayleigh","Lord Rayleigh (1842-1919)","Vibration & resonance"],
    ["wd_stodola","Aurel Stodola (1859-1942)","Turbine blades & vibration"],["wd_mohr","Otto Mohr (1835-1918)","Stress analysis & Mohr's circle"],
    ["wd_ewing","James Alfred Ewing (1855-1935)","Hysteresis & metal fatigue"],["wd_gough","Herbert J. Gough (1890-1965)","Metal fatigue research"],
    ["wd_palmgren","Arvid Palmgren (1890-1971)","Bearing life & cumulative fatigue"],["wd_miner","Milton A. Miner (fatigue engineer)","Cumulative fatigue damage"],
    ["wd_paris","Paul C. Paris (1930-2017)","Fatigue crack growth"],["wd_stribeck","Richard Stribeck (1861-1950)","Bearing friction & lubrication"]],
},

{ id:"t_transformer", title:"The Aldergate Substation Fire", discipline:"Power Engineering & Dielectrics",
  teaser:"A substation transformer exploded into flame and blacked out the city. An attack? A lightning strike? Or an overload nobody logged?",
  overclaimTag:"sabotage or an attack", truthTag:"chronic overload & deferred oil testing",
  venue:"the Aldergate substation inquiry", agent:"Investigator Emun Halle", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Power & Dielectric Pioneers", dossierName:"POWER & DIELECTRIC PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Aldergate substation inquiry",
  who:{truth:"operator", items:[["operator","Bram Odell — utility operator"],["engineer","The substation engineer"],["regulator","The grid safety regulator"]]},
  where:{truth:"office", items:[["yard","The Substation Yard & Transformer"],["relay","The Relay & Control House"],["office","The Utility's Asset Office"]]},
  what:{truth:"overload", overclaim:"attack", dismissal:"freak", items:[["attack","Sabotage or an attack on the yard"],["freak","A freak lightning strike — an act of God"],["overload","Chronic overload with insulating-oil testing deferred"]]},
  places:["yard","relay","office"],
  chars:[["subop","Operator Nkemi","Substation operator","⚡","N","the substation yard","Switches the yard; watched the transformer run hot and over its rating."],
         ["oiltech","The Oil Technician","Insulating-oil technician","🧪","O","the control house","Draws the oil samples; the dissolved-gas tests were long overdue."],
         ["clerk","The Clerk","Asset-records clerk","🗂","C","the office","Keeps the load records and the test schedule that was deferred."]],
  topics:[["tx_hopkinson","John Hopkinson (1849-1898)","Magnetic circuits & transformer theory"],["tx_blathy","Otto Blathy (1860-1939)","The ZBD transformer"],
    ["tx_zipernowsky","Karoly Zipernowsky (1853-1942)","AC distribution & the transformer"],["tx_gaulard","Lucien Gaulard (1850-1888)","The early AC transformer"],
    ["tx_deri","Miksa Deri (1854-1938)","The ZBD transformer & AC"],["tx_ferraris","Galileo Ferraris (1847-1897)","AC theory & the rotating field"],
    ["tx_ferranti","Sebastian Ziani de Ferranti (1864-1930)","High-voltage AC & the Ferranti effect"],["tx_weiss","Pierre Weiss (1865-1940)","Ferromagnetism & magnetic domains"],
    ["tx_barkhausen","Heinrich Barkhausen (1881-1956)","Magnetization & core losses"],["tx_debye","Peter Debye (1884-1966)","Dielectrics & polarization"],
    ["tx_mossotti","Ottaviano Mossotti (1791-1863)","Dielectric polarization"],["tx_paschen","Friedrich Paschen (1865-1947)","Gas breakdown & Paschen's law"],
    ["tx_townsend","John Sealy Townsend (1868-1957)","Gas discharge & avalanche breakdown"],["tx_peek","Frank W. Peek (1881-1933)","Corona & dielectric breakdown"],
    ["tx_rogowski","Walther Rogowski (1881-1947)","Dielectric field control"],["tx_stefan","Josef Stefan (1835-1893)","Thermal radiation & heat loss"],
    ["tx_schmidt","Ernst Schmidt (1892-1975)","Heat transfer & thermal analysis"],["tx_seebeck","Thomas Johann Seebeck (1770-1831)","Thermoelectric hot-spot sensing"]],
},

{ id:"t_oncology", title:"The Meredith Clinic Overdose", discipline:"Radiation Physics & Medical Dosimetry",
  teaser:"Cancer patients were burned by their own treatment beam. A software glitch? A rare reaction? Or a calibration check that stopped being done?",
  overclaimTag:"a software or computer glitch", truthTag:"a calibration & QA gap in the beam",
  venue:"the Meredith clinic inquiry", agent:"Inspector Tovah Riis", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Radiation & Dosimetry Pioneers", dossierName:"RADIATION & DOSIMETRY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Meredith clinic inquiry",
  who:{truth:"clinic", items:[["clinic","Dr. Halvard Bre — clinic director"],["physicist","The chief medical physicist"],["regulator","The radiation safety regulator"]]},
  where:{truth:"office", items:[["vault","The Treatment Vault & Machine"],["planning","The Dosimetry & Planning Room"],["office","The Clinic Director's Office"]]},
  what:{truth:"qagap", overclaim:"software", dismissal:"freak", items:[["software","A rogue software or computer glitch"],["freak","A one-off patient reaction — sheer misfortune"],["qagap","A calibration & QA gap in the treatment chain"]]},
  places:["vault","planning","office"],
  chars:[["therapist","Therapist Iyla","Radiation therapist","☢","T","the treatment vault","Runs the beam; saw the patients' skin burn and the machine left unchecked."],
         ["dosimetrist","The Dosimetrist","Clinical dosimetrist","📐","D","the planning room","Builds the plans; the output was never re-calibrated after the source swap."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the QA logs and the memo that cut the physics checks."]],
  topics:[["rx_rontgen","Wilhelm Rontgen (1845-1923)","The discovery of X-rays"],["rx_becquerel","Henri Becquerel (1852-1908)","Natural radioactivity"],
    ["rx_whbragg","William Henry Bragg (1862-1942)","Ionization & the Bragg peak"],["rx_coolidge","William D. Coolidge (1873-1975)","The X-ray tube"],
    ["rx_wideroe","Rolf Wideroe (1902-1996)","The linear accelerator concept"],["rx_kerst","Donald Kerst (1911-1993)","The betatron & medical radiation"],
    ["rx_johns","Harold E. Johns (1915-1998)","Cobalt-60 radiotherapy & medical physics"],["rx_rwilson","Robert R. Wilson (1914-2000)","Proton therapy & the Bragg peak"],
    ["rx_gray","Louis Harold Gray (1905-1965)","The gray & absorbed dose"],["rx_sievert","Rolf Sievert (1896-1966)","Dose equivalent & radiation protection"],
    ["rx_failla","Gioacchino Failla (1891-1961)","Radiation dosimetry"],["rx_quimby","Edith Quimby (1891-1982)","Clinical radiation dosimetry"],
    ["rx_paterson","Ralston Paterson (1897-1981)","The Paterson-Parker dose system"],["rx_parker","Herbert M. Parker (1910-1984)","Dosimetry & dose units"],
    ["rx_fricke","Hugo Fricke (1892-1972)","Chemical (Fricke) dosimetry"],["rx_cameron","John R. Cameron (1922-2005)","Thermoluminescent dosimetry"],
    ["rx_evans","Robley D. Evans (1907-1995)","Radiation measurement & dosimetry"],["rx_cormack","Allan Cormack (1924-1998)","CT imaging & dose computation"]],
},

];
