// Code & Signals (computing & information) — 7 Casebook game STRUCTURES.
// DESIGN ONLY: mystery + board + informants + 18-figure roster per game.
// Shape matches one GAMES element in generate_more.js, field-for-field.
// Spine: overclaim (sensational-wrong) / dismissal (nothing-wrong) / truth (concealed-systemic-provable).
// All 126 figures are real, accurately matched, unique across games, and cross-checked
// against batch/used_figures.txt (no reuse). Every sci carries a parenthesis.

module.exports = [

{ id:"f_breach", title:"The Halcyon Data Breach", discipline:"Computer Security & Information Systems",
  teaser:"Ninety million records walked out the door overnight. A nation-state mastermind? An unstoppable zero-day? Or a patch that was never applied and an alarm that was switched off?",
  overclaimTag:"a nation-state mastermind", truthTag:"a known-unpatched flaw and a silenced alarm",
  venue:"the Halcyon breach inquiry", agent:"Investigator Nora Vance", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Computer-Security Pioneers", dossierName:"COMPUTER-SECURITY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halcyon breach inquiry",
  who:{truth:"cto", items:[["hacker","A foreign intrusion crew"],["cto","Dane Ferro — the firm's security chief"],["vendor","The software vendor"]]},
  where:{truth:"office", items:[["servers","The Customer Database Servers"],["soc","The Security Operations Centre"],["office","The Security Chief's Office"]]},
  what:{truth:"unpatched", overclaim:"mastermind", dismissal:"zeroday", items:[["mastermind","A genius nation-state hacker breached us"],["zeroday","An unavoidable zero-day — no one could have stopped it"],["unpatched","A known-unpatched system and an alert switched off"]]},
  places:["servers","soc","office"],
  chars:[["analyst","The SOC Analyst","Security-operations analyst","🖥","A","the operations centre","Watched the alert fire for weeks; it was acknowledged, then muted."],
         ["admin","Sysadmin Rao","Systems administrator","🔧","S","the server room","Ran the scanners; the critical patch sat in the queue, signed off as 'deferred'."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the risk register — and the memo that accepted the risk and moved on."]],
  topics:[["b_threatmon","James P. Anderson (1930-2007)","Computer-security threat monitoring"],["b_ids","Dorothy Denning (b. 1945)","Intrusion detection"],
    ["b_kernel","Roger Schell (b. 1939)","The security kernel & trusted systems"],["b_access","Butler Lampson (b. 1943)","Access control & protection"],
    ["b_leastpriv","Jerome Saltzer (b. 1939)","Protection & least privilege"],["b_protprin","Michael Schroeder (computer-security pioneer)","The principles of protecting information"],
    ["b_bella","David Elliott Bell (security-model pioneer)","The Bell-LaPadula confidentiality model"],["b_lapadula","Leonard LaPadula (security-model pioneer)","Multilevel security models"],
    ["b_biba","Kenneth Biba (integrity-model pioneer)","The integrity model"],["b_virus","Fred Cohen (b. 1956)","The computer virus, defined"],
    ["b_worm","Eugene Spafford (b. 1956)","Worms, malware & incident analysis"],["b_passwd","Robert Morris Sr. (1932-2011)","Password security & one-way hashing"],
    ["b_trust","Ken Thompson (b. 1943)","Trusting trust & Unix security"],["b_timeshare","Fernando Corbató (1926-2019)","Time-sharing & the computer password"],
    ["b_ware","Willis Ware (1920-2013)","Computer security & privacy safeguards"],["b_risks","Peter G. Neumann (b. 1932)","Computer-related risks to the public"],
    ["b_cuckoo","Cliff Stoll (b. 1950)","Tracking the intruder through the logs"],["b_auth","Roger Needham (1934-2003)","Authentication protocols & stored passwords"]],
},

{ id:"f_ai", title:"The Aegis Model", discipline:"Artificial Intelligence & Machine Learning",
  teaser:"A hiring model quietly rejected thousands who never had a chance. A runaway self-learning intelligence? A handful of rare mistakes? Or a result buried before launch?",
  overclaimTag:"a runaway self-learning intelligence", truthTag:"biased data and a buried warning",
  venue:"the Aegis model inquiry", agent:"Investigator Wen Astor", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Artificial-Intelligence Pioneers", dossierName:"ARTIFICIAL-INTELLIGENCE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Aegis model inquiry",
  who:{truth:"lead", items:[["outsider","An outside data-poisoning crew"],["lead","Dr. Priya Sandoval — the model's lead scientist"],["auditor","The external auditor"]]},
  where:{truth:"evalroom", items:[["datalab","The Training-Data Lab"],["evalroom","The Model Evaluation Room"],["office","The Project Lead's Office"]]},
  what:{truth:"biasdata", overclaim:"sentient", dismissal:"edgecases", items:[["sentient","A runaway, self-teaching intelligence went rogue"],["edgecases","A few rare edge cases — the model works as designed"],["biasdata","Biased training data and a validation result buried before launch"]]},
  places:["datalab","evalroom","office"],
  chars:[["dataeng","The Data Engineer","Training-data engineer","🗄","D","the data lab","Assembled the training set; knows whole groups were barely in it."],
         ["validator","The Validation Scientist","Model-validation scientist","📊","V","the evaluation room","Ran the fairness test; the failing result was pulled before release."],
         ["clerk","The Clerk","Project records clerk","🗂","C","the office","Keeps the sign-off file — and the ship order that overrode the warning."]],
  topics:[["a_named","John McCarthy (1927-2011)","Artificial intelligence, named & founded"],["a_limits","Marvin Minsky (1927-2016)","Neural nets & their early limits"],
    ["a_mlearn","Arthur Samuel (1901-1990)","Machine learning from data"],["a_perceptron","Frank Rosenblatt (1928-1971)","The perceptron"],
    ["a_neuron","Warren McCulloch (1898-1969)","The artificial neuron"],["a_netlogic","Walter Pitts (1923-1969)","The logic of neural nets"],
    ["a_hebb","Donald Hebb (1904-1985)","Hebbian learning"],["a_backprop","Paul Werbos (b. 1947)","Backpropagation"],
    ["a_connect","David Rumelhart (1942-2011)","Backprop & connectionism"],["a_deep","Geoffrey Hinton (b. 1947)","Deep learning"],
    ["a_convnet","Yann LeCun (b. 1960)","Convolutional networks"],["a_repr","Yoshua Bengio (b. 1964)","Deep learning & representation"],
    ["a_causal","Judea Pearl (b. 1936)","Bayesian networks & causal inference"],["a_svm","Vladimir Vapnik (b. 1936)","Statistical learning & the support-vector machine"],
    ["a_forests","Leo Breiman (1928-2005)","Random forests & the two cultures of modelling"],["a_imagenet","Fei-Fei Li (b. 1976)","ImageNet & the data behind vision"],
    ["a_bias","Joy Buolamwini (b. 1989)","Algorithmic bias in face recognition"],["a_datacard","Timnit Gebru (b. 1983)","Bias, data & model documentation"]],
},

{ id:"f_crypto", title:"The Cipher at Meridian Bank", discipline:"Cryptography & Information Security",
  teaser:"Millions drained from accounts thought mathematically safe. An unbreakable-code genius? Sheer computing brute force? Or a cipher they were warned to retire?",
  overclaimTag:"an unbreakable-code genius", truthTag:"a deprecated cipher kept in service",
  venue:"the Meridian Bank cipher inquiry", agent:"Investigator Sol Marchetti", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Cryptography Pioneers", dossierName:"CRYPTOGRAPHY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Meridian Bank cipher inquiry",
  who:{truth:"architect", items:[["codebreaker","A world-class codebreaking crew"],["architect","Lena Marsh — the bank's crypto architect"],["auditor","The security auditor"]]},
  where:{truth:"office", items:[["vault","The Transaction & Key Vault"],["cryptolab","The Cryptography Lab"],["office","The Security Architect's Office"]]},
  what:{truth:"weakcipher", overclaim:"genius", dismissal:"bruteforce", items:[["genius","A genius broke unbreakable encryption"],["bruteforce","Unstoppable brute-force computing — bad luck of the draw"],["weakcipher","A home-rolled, deprecated cipher kept in use against advice"]]},
  places:["vault","cryptolab","office"],
  chars:[["cryptographer","The Cryptographer","Staff cryptographer","🔐","Y","the crypto lab","Flagged the aging cipher years ago; the replace-it memo was shelved."],
         ["keykeeper","The Key Custodian","Key-management officer","🗝","K","the vault","Handles the keys; the same short key had been reused far past its life."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the audit trail — and the risk waiver that kept the old cipher running."]],
  topics:[["c_kerck","Auguste Kerckhoffs (1835-1903)","Kerckhoffs's principle of cipher design"],["c_alberti","Leon Battista Alberti (1404-1472)","The polyalphabetic cipher & cipher disk"],
    ["c_vigenere","Blaise de Vigenère (1523-1596)","The Vigenère cipher"],["c_alkindi","Al-Kindi (c. 801-873)","Frequency analysis & codebreaking"],
    ["c_kasiski","Friedrich Kasiski (1805-1881)","Breaking the polyalphabetic cipher"],["c_otp","Gilbert Vernam (1890-1960)","The one-time pad"],
    ["c_cryptanalysis","William F. Friedman (1891-1969)","Modern cryptanalysis"],["c_codebreaker","Elizebeth Smith Friedman (1892-1980)","Codebreaking & cipher-cracking"],
    ["c_feistel","Horst Feistel (1915-1990)","The Feistel cipher & DES"],["c_publickey","Whitfield Diffie (b. 1944)","Public-key cryptography"],
    ["c_keyexch","Martin Hellman (b. 1945)","The Diffie-Hellman key exchange"],["c_hashtree","Ralph Merkle (b. 1952)","Public keys & cryptographic hashing"],
    ["c_rsa","Ronald Rivest (b. 1947)","The RSA cipher"],["c_sharing","Adi Shamir (b. 1952)","RSA & secret sharing"],
    ["c_rsaalg","Leonard Adleman (b. 1945)","The RSA algorithm"],["c_pgp","Phil Zimmermann (b. 1954)","PGP & encryption for all"],
    ["c_aes","Joan Daemen (b. 1965)","The AES / Rijndael cipher"],["c_applied","Bruce Schneier (b. 1963)","Applied cryptography & security"]],
},

{ id:"f_netout", title:"The Great Grey-Out", discipline:"Computer Networks & the Internet",
  teaser:"Half the web went dark in twenty minutes. A coordinated cyber-attack? An unlucky traffic surge? Or one bad config and a safety net someone removed?",
  overclaimTag:"a coordinated cyber-attack", truthTag:"a misconfiguration and a removed safeguard",
  venue:"the network-outage inquiry", agent:"Investigator Tay Brennan", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Networking Pioneers", dossierName:"NETWORKING & INTERNET PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the network-outage inquiry",
  who:{truth:"netops", items:[["attackers","An outside attack crew"],["netops","Cory Idris — the network operations lead"],["registry","The routing registry"]]},
  where:{truth:"office", items:[["routers","The Core Routers & Peering"],["noc","The Network Operations Centre"],["office","The Operations Manager's Office"]]},
  what:{truth:"misconfig", overclaim:"attack", dismissal:"surge", items:[["attack","A coordinated attack knocked the network down"],["surge","An unlucky traffic surge — the internet is just fragile"],["misconfig","A routing misconfiguration and a removed safeguard cascaded"]]},
  places:["routers","noc","office"],
  chars:[["engineer","The Network Engineer","On-call network engineer","🌐","N","the operations centre","Pushed the change on orders; the route filter had been switched off to save time."],
         ["peering","The Peering Coordinator","Peering & routing coordinator","🔀","P","the router hall","Watches the routes; saw one bad announcement leak everywhere at once."],
         ["clerk","The Clerk","Change-records clerk","🗂","C","the office","Keeps the change tickets — and the sign-off that removed the safety filter."]],
  topics:[["n_vision","J.C.R. Licklider (1915-1990)","The vision of networked computing"],["n_packet","Paul Baran (1926-2011)","Packet switching & survivable networks"],
    ["n_packetname","Donald Davies (1924-2000)","Packet switching, named"],["n_queue","Leonard Kleinrock (b. 1934)","Queueing theory & the ARPANET"],
    ["n_arpanet","Lawrence Roberts (1937-2018)","Building the ARPANET"],["n_tcpip","Vint Cerf (b. 1943)","TCP/IP"],
    ["n_internetwork","Bob Kahn (b. 1938)","TCP/IP & internetworking"],["n_dns","Jon Postel (1943-1998)","The DNS, addresses & IANA"],
    ["n_dnsdesign","Paul Mockapetris (b. 1948)","The Domain Name System"],["n_arch","David D. Clark (b. 1944)","Internet architecture & robustness"],
    ["n_spanning","Radia Perlman (b. 1951)","The spanning-tree protocol"],["n_congestion","Van Jacobson (b. 1950)","TCP congestion control"],
    ["n_aqm","Sally Floyd (1950-2019)","Congestion control & active queue management"],["n_ethernet","Robert Metcalfe (b. 1946)","Ethernet"],
    ["n_datagram","Louis Pouzin (b. 1931)","The datagram"],["n_web","Tim Berners-Lee (b. 1955)","The World Wide Web"],
    ["n_bgp","Yakov Rekhter (Internet-routing pioneer)","The Border Gateway Protocol"],["n_dnssec","Dan Kaminsky (1979-2021)","DNS security & cache poisoning"]],
},

{ id:"f_robot", title:"The Cell-9 Robot", discipline:"Robotics & Autonomous Systems",
  teaser:"A robot arm killed a technician inside its safety cage. A hacked machine? A careless worker? Or a safety lock someone had bypassed?",
  overclaimTag:"a hacked machine", truthTag:"a bypassed safety interlock and a known fault",
  venue:"the Cell-9 robotics inquiry", agent:"Investigator Mara Quint", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Robotics & Autonomy Pioneers", dossierName:"ROBOTICS & AUTONOMY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Cell-9 robotics inquiry",
  who:{truth:"automation", items:[["hacker","An outside attacker who seized the machine"],["automation","Guy Halloran — the plant automation manager"],["worker","The maintenance crew"]]},
  where:{truth:"office", items:[["cell","The Robot Cell & Safety Cage"],["controls","The Robot Control & Interlock Room"],["office","The Automation Manager's Office"]]},
  what:{truth:"interlock", overclaim:"hack", dismissal:"operator", items:[["hack","The robot was hacked and turned deadly"],["operator","Simple operator error — the worker stepped in"],["interlock","A safety interlock bypassed and a known fault left unfixed"]]},
  places:["cell","controls","office"],
  chars:[["technician","The Robot Technician","Robotics maintenance tech","🤖","R","the robot cell","Services the arm; the door interlock had been jumpered out to keep the line moving."],
         ["controls2","The Controls Engineer","Control-systems engineer","🎛","E","the control room","Reads the logs; the arm had lunged unexpectedly before, and it was written up."],
         ["clerk","The Clerk","Safety-records clerk","🗂","C","the office","Keeps the incident file — and the order to bypass the guard 'temporarily'."]],
  topics:[["r_firstrobot","George Devol (1912-2011)","The first industrial robot"],["r_industrial","Joseph Engelberger (1925-2015)","Industrial robotics"],
    ["r_arm","Victor Scheinman (1942-2016)","The programmable robotic arm"],["r_shakey","Charles Rosen (1917-2002)","Shakey & the mobile robot"],
    ["r_planning","Nils Nilsson (1933-2019)","Robot planning & the A* search"],["r_behavior","Rodney Brooks (b. 1954)","Behaviour-based robotics"],
    ["r_legged","Marc Raibert (b. 1949)","Dynamic & legged robots"],["r_navigation","Hans Moravec (b. 1948)","Robot navigation & perception"],
    ["r_activeperc","Ruzena Bajcsy (b. 1933)","Active perception"],["r_vision","Takeo Kanade (b. 1945)","Computer vision for robots"],
    ["r_motion","Oussama Khatib (robot-control pioneer)","Robot motion & obstacle avoidance"],["r_autodrive","Ernst Dickmanns (b. 1936)","Vision-guided autonomous driving"],
    ["r_selfdrive","Sebastian Thrun (b. 1967)","Self-driving & probabilistic robotics"],["r_intelligent","Raj Reddy (b. 1937)","Robotics & intelligent systems"],
    ["r_field","Red Whittaker (b. 1948)","Field & autonomous vehicles"],["r_kalman","Rudolf Kálmán (1930-2016)","The Kalman filter & state estimation"],
    ["r_fuzzy","Lotfi Zadeh (1921-2017)","Fuzzy logic & control"],["r_grasp","Ken Goldberg (b. 1961)","Robot grasping & reliability"]],
},

{ id:"f_privacy", title:"The Beacon Consent Scandal", discipline:"Data Privacy & Information Systems",
  teaser:"A billion intimate records turned up for sale. A criminal data theft? All fair and anonymized? Or consent quietly stripped and the data sold?",
  overclaimTag:"a criminal data theft", truthTag:"anonymization defeated and data monetized",
  venue:"the Beacon data-privacy inquiry", agent:"Investigator Iris Kohl", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Data-Privacy Pioneers", dossierName:"DATA-PRIVACY & DATABASE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Beacon data-privacy inquiry",
  who:{truth:"dataexec", items:[["thieves","An outside data-theft ring"],["dataexec","Reed Calloway — the firm's data-product chief"],["processor","The third-party data processor"]]},
  where:{truth:"office", items:[["warehouse","The Customer Data Warehouse"],["analytics","The Analytics & Re-identification Lab"],["office","The Data Chief's Office"]]},
  what:{truth:"monetized", overclaim:"theft", dismissal:"anon", items:[["theft","Criminals stole the data in a break-in"],["anon","It was all anonymized and consented — nothing wrong"],["monetized","Consent and anonymization quietly defeated, the data sold"]]},
  places:["warehouse","analytics","office"],
  chars:[["dataeng2","The Data Engineer","Data-warehouse engineer","🗄","D","the data warehouse","Built the pipelines; the 'anonymous' IDs could be traced straight back."],
         ["analyst2","The Analytics Lead","Analytics & re-identification lead","📈","A","the analytics lab","Re-linked the records to real names — and was told to keep selling them."],
         ["clerk","The Clerk","Compliance records clerk","🗂","C","the office","Keeps the consent forms — and the deal that sold what they never agreed to."]],
  topics:[["p_infoprivacy","Alan Westin (1929-2013)","Informational privacy & self-determination"],["p_reident","Latanya Sweeney (b. 1968)","Re-identification & k-anonymity"],
    ["p_diffpriv","Cynthia Dwork (b. 1958)","Differential privacy"],["p_context","Helen Nissenbaum (b. 1954)","Privacy as contextual integrity"],
    ["p_deanon","Arvind Narayanan (data-privacy researcher)","De-anonymizing large datasets"],["p_breakanon","Vitaly Shmatikov (data-privacy researcher)","Breaking anonymized data"],
    ["p_anonfail","Paul Ohm (privacy-law scholar)","The failure of anonymization"],["p_mixnet","David Chaum (b. 1955)","Anonymous communication & digital cash"],
    ["p_tor","Roger Dingledine (anonymity-network pioneer)","The Tor anonymity network"],["p_policy","Susan Landau (b. 1954)","Surveillance, privacy & policy"],
    ["p_econ","Ross Anderson (1956-2024)","Security & privacy economics"],["p_sanitize","Simson Garfinkel (privacy & forensics researcher)","Privacy & data sanitization"],
    ["p_relational","Edgar F. Codd (1923-2003)","The relational database"],["p_dbms","Charles Bachman (1924-2017)","The database management system"],
    ["p_ermodel","Peter Chen (b. 1947)","The entity-relationship model"],["p_dbsystems","Michael Stonebraker (b. 1943)","Modern database systems"],
    ["p_transactions","Jim Gray (b. 1944)","Transactions & data at scale"],["p_integration","Hector Garcia-Molina (1954-2019)","Databases & data integration"]],
},

{ id:"f_firmware", title:"The Halden Infusion Pump", discipline:"Embedded & Firmware Engineering",
  teaser:"A drug pump delivered a lethal dose to a sleeping patient. A tampered device? A one-in-a-million glitch? Or a defect hidden and a hardware check taken out?",
  overclaimTag:"a tampered device", truthTag:"a hidden firmware defect and a deleted hardware check",
  venue:"the infusion-pump firmware inquiry", agent:"Investigator Dana Voss", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Firmware & Coding Pioneers", dossierName:"FIRMWARE, CODING & HARDWARE PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the infusion-pump firmware inquiry",
  who:{truth:"firmlead", items:[["tamperer","An outside tamperer"],["firmlead","Cal Devereux — the device firmware lead"],["regulator","The device regulator"]]},
  where:{truth:"office", items:[["bench","The Device & Test Bench"],["firmlab","The Firmware Verification Lab"],["office","The Engineering Lead's Office"]]},
  what:{truth:"defect", overclaim:"tamper", dismissal:"glitch", items:[["tamper","The device was tampered with"],["glitch","A one-in-a-million glitch — nothing preventable"],["defect","A concealed firmware defect and a hardware safety check removed"]]},
  places:["bench","firmlab","office"],
  chars:[["firmeng","The Firmware Engineer","Embedded firmware engineer","💾","F","the firmware lab","Wrote the tests; the failing case was known and quietly closed as 'won't fix'."],
         ["hwtech","The Hardware Test Engineer","Hardware test engineer","🔌","H","the test bench","Checks the boards; the safety watchdog chip was deleted to cut cost."],
         ["clerk","The Clerk","Design records clerk","🗂","C","the office","Keeps the defect log — and the order to ship with the check removed."]],
  topics:[["m_hamming","Richard Hamming (1915-1998)","Error-detecting & correcting codes"],["m_huffman","David A. Huffman (1925-1999)","Data compression & coding"],
    ["m_fano","Robert Fano (1917-2016)","Information & coding theory"],["m_reed","Irving S. Reed (1923-2012)","Reed-Solomon error correction"],
    ["m_solomon","Gustave Solomon (1930-1996)","Reed-Solomon codes"],["m_viterbi","Andrew Viterbi (b. 1935)","The Viterbi decoding algorithm"],
    ["m_ldpc","Robert Gallager (b. 1931)","Low-density parity-check codes"],["m_elias","Peter Elias (1923-2001)","Convolutional codes & error control"],
    ["m_kilby","Jack Kilby (1923-2005)","The integrated circuit"],["m_noyce","Robert Noyce (1927-1990)","The integrated circuit"],
    ["m_micro","Federico Faggin (b. 1941)","The microprocessor"],["m_vlsi","Carver Mead (b. 1934)","VLSI design"],
    ["m_vlsimethod","Lynn Conway (1938-2024)","VLSI design methodology"],["m_microprog","Maurice Wilkes (1913-2010)","Microprogramming & stored control"],
    ["m_faulttol","Algirdas Avizienis (1932-2022)","Fault-tolerant computing"],["m_faulttest","Edward J. McCluskey (1929-2016)","Logic design & fault testing"],
    ["m_dependable","Brian Randell (b. 1936)","Dependable & fault-tolerant systems"],["m_dependability","Jean-Claude Laprie (1944-2010)","The concepts of dependability"]],
},

];
