// DESIGN ONLY — 7 Casebook game STRUCTURES for the "Body & Medicine" category.
// Same shape as one GAMES element in generate_more.js (field-for-field).
// No prose: mystery wiring + board + 3 informants + 18-figure roster per game.
// Spine per game: OVERCLAIM (sensational-wrong / scapegoat clinician) ·
// DISMISSAL (nothing-wrong / act of God) · TRUTH (concealed-systemic-provable).
// Guilty WHO = a system/manager who normalized a defect; the "killer clinician"
// is the OVERCLAIM scapegoat. Truth WHERE = where the proof lives (the records).
// All 126 figures are real, accurately matched, unique across the 7 games, and
// cross-checked against batch/used_figures.txt (none reused).

module.exports = [

{ id:"w_anes", title:"The Silent Theatre", discipline:"Anesthesiology & Patient Safety",
  teaser:"A healthy patient went under for routine surgery and never woke. A reckless anesthetist? A freak drug reaction? Or an alarm someone had already switched off?",
  overclaimTag:"a reckless anesthetist", truthTag:"a normalized monitoring gap",
  venue:"the Halden Surgical Center inquiry", agent:"Investigator Nora Vance", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Anesthesia Pioneers", dossierName:"ANESTHESIA PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Halden Surgical Center inquiry",
  who:{truth:"director", items:[["anesth","Dr. Payne — the anesthetist on the case"],["director","Lorne Halden — the surgical center's director"],["rep","The drug-supply rep"]]},
  where:{truth:"admin", items:[["theatre","The Operating Theatre"],["drugroom","The Drug Room & Vial Store"],["admin","The Center's Administration Office"]]},
  what:{truth:"monitoring", overclaim:"overdose", dismissal:"reaction", items:[["overdose","A reckless anesthetist who overdosed the patient"],["reaction","A rare, fatal drug reaction — an act of God"],["monitoring","A silenced alarm and a look-alike vial, normalized to save time"]]},
  places:["theatre","drugroom","admin"],
  chars:[["nurse","Nurse Beale","Circulating nurse","💉","N","the theatre","Stood at the table all morning; heard the monitor's alarm muted before the first cut."],
         ["biotech","The Biomed Tech","Clinical engineer","🔧","B","the drug room","Services the monitors and stocks the shelves; two drugs sat in near-identical vials side by side."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the service logs — and the standing order telling staff to keep the alarms quiet."]],
  topics:[["ether","Crawford Long (1815-1878)","Ether anesthesia"],["etherday","William T.G. Morton (1819-1868)","The public ether demonstration"],
    ["nitrous","Horace Wells (1815-1848)","Nitrous oxide"],["chloroform","James Young Simpson (1811-1870)","Chloroform anesthesia"],
    ["inhaler","Joseph Clover (1825-1882)","The chloroform inhaler & patient safety"],["spinal","August Bier (1861-1949)","Spinal anesthesia"],
    ["depth","Arthur Guedel (1883-1956)","The stages & depth of anesthesia"],["circuit","Ralph Waters (1883-1979)","Closed-circuit anesthesia & CO2 absorption"],
    ["machine","Elmer McKesson (1881-1935)","The anesthesia machine"],["intubation","Ivan Magill (1888-1986)","Endotracheal intubation"],
    ["laryngoscope","Robert Macintosh (1897-1989)","The laryngoscope"],["relaxant","Harold Griffith (1894-1985)","Curare & muscle relaxants"],
    ["apgar","Virginia Apgar (1909-1974)","Scoring the newborn's vital signs"],["mortality","Henry Beecher (1904-1976)","Anesthesia mortality & research ethics"],
    ["bloodgas","John Severinghaus (1922-2021)","The blood-gas electrode"],["oximetry","Takuo Aoyagi (1936-2020)","Pulse oximetry"],
    ["mishaps","Jeffrey Cooper (anesthesia-safety engineer)","Anesthesia mishaps & human factors"],["apsf","Ellison Pierce (anesthesiologist, 1929-2011)","The anesthesia patient-safety movement"]],
},

{ id:"w_surg", title:"The Wrong Side", discipline:"Surgery & Patient Safety",
  teaser:"An operation went catastrophically wrong on a routine list. A butcher of a surgeon? Sheer bad luck? Or a safety count quietly skipped to save time?",
  overclaimTag:"an incompetent surgeon", truthTag:"a bypassed surgical safeguard",
  venue:"the St. Auben Hospital inquiry", agent:"Investigator Cole Ferris", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Surgery Pioneers", dossierName:"SURGERY & SAFETY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the St. Auben Hospital inquiry",
  who:{truth:"chief", items:[["surgeon","Mr. Rasch — the operating surgeon"],["chief","Dr. Vane — the surgical chief of service"],["vendor","The theatre-supplies vendor"]]},
  where:{truth:"records", items:[["theatre","The Operating Theatre"],["stores","The Sterile Stores & Instrument Count"],["records","The Surgical Office & Records"]]},
  what:{truth:"bypass", overclaim:"incompetence", dismissal:"complication", items:[["incompetence","A careless surgeon operating on the wrong site"],["complication","An unavoidable surgical complication — bad luck"],["bypass","A safety count and checklist quietly bypassed to save time"]]},
  places:["theatre","stores","records"],
  chars:[["scrubnurse","Scrub Nurse Adler","Scrub nurse","🧤","S","the theatre","Passes every instrument; the count came up short and the case pressed on anyway."],
         ["orderly","The Orderly","Theatre orderly","🧺","O","the stores","Wheels the patients and trays; the site-marking and time-out were skipped on a packed list."],
         ["clerk","The Clerk","Surgical records clerk","🗂","C","the office","Files the checklists and count sheets — and the memo that made them optional."]],
  topics:[["ligature","Ambroise Paré (1510-1590)","Battlefield surgery & the ligature"],["ovariotomy","Ephraim McDowell (1771-1830)","Early abdominal surgery"],
    ["fastknife","Robert Liston (1794-1847)","Surgery in the age before anesthesia"],["antiseptic","Joseph Lister (1827-1912)","Antiseptic surgery"],
    ["abdominal","Theodor Billroth (1829-1894)","The birth of abdominal surgery"],["steam","Ernst von Bergmann (1836-1907)","Steam sterilization of instruments"],
    ["thyroid","Theodor Kocher (1841-1917)","Precision thyroid surgery"],["asepsis","William Halsted (1852-1922)","Aseptic technique & surgical gloves"],
    ["operatingroom","Gustav Neuber (1850-1932)","The aseptic operating room"],["neurosurg","Harvey Cushing (1869-1939)","Neurosurgery & the anesthesia record"],
    ["endresult","Ernest Codman (1869-1940)","The 'end result' & surgical accountability"],["vascular","Alexis Carrel (1873-1944)","Vascular suture technique"],
    ["quality","Avedis Donabedian (1919-2000)","Measuring the quality of care"],["error","Lucian Leape (patient-safety researcher, b. 1930)","Medical error & preventable harm"],
    ["icuchecklist","Peter Pronovost (b. 1964)","The checklist in intensive care"],["surgchecklist","Atul Gawande (b. 1965)","The surgical safety checklist"],
    ["neverevents","Martin Makary (surgeon & researcher)","Wrong-site surgery & 'never events'"],["improvement","Donald Berwick (b. 1946)","Quality improvement & reducing harm"]],
},

{ id:"w_compound", title:"The Compounding Room", discipline:"Pharmacy & Sterile Compounding",
  teaser:"Patients who got a routine injection began falling gravely ill across three states. A poisoner? A run of bad luck? Or a sterility control someone quietly switched off?",
  overclaimTag:"a deliberate poisoning", truthTag:"abandoned sterility controls",
  venue:"the Meridian Compounding inquiry", agent:"Investigator Del Marsh", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Pharmacy Pioneers", dossierName:"PHARMACY & STERILITY PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Meridian Compounding inquiry",
  who:{truth:"owner", items:[["pharmacist","The compounding pharmacist"],["owner","Guillory — the pharmacy's owner"],["inspector","The state pharmacy inspector"]]},
  where:{truth:"office", items:[["cleanroom","The Clean Room & Autoclave"],["culture","The Environmental-Monitoring Lab"],["office","The Owner's Business Office"]]},
  what:{truth:"sterility", overclaim:"poison", dismissal:"coincidence", items:[["poison","A deliberate poisoning of the medicine"],["coincidence","A run of coincidental illnesses — bad luck"],["sterility","Sterility controls cut and contamination ignored to raise output"]]},
  places:["cleanroom","culture","office"],
  chars:[["tech","Pharmacy Tech Ruiz","Compounding technician","⚗","T","the clean room","Fills the vials; the autoclave cycles were shortened and the hood left unchecked."],
         ["micro","The Micro Analyst","Environmental-monitoring analyst","🧫","M","the lab","Reads the settle plates; mold grew on the monitors and the results were waved through."],
         ["clerk","The Clerk","Records clerk","🗂","C","the office","Keeps the batch records — and the sterility failures stamped 'release anyway.'"]],
  topics:[["materiamedica","Galen (c.129-216)","Materia medica & compounding"],["canon","Avicenna — Ibn Sina (980-1037)","The pharmacopoeia"],
    ["dose","William Withering (1741-1799)","Dosage & the therapeutic dose"],["morphine","Friedrich Sertürner (1783-1841)","Morphine & alkaloid purity"],
    ["pharmacy","William Procter Jr. (1817-1874)","The founding of pharmacy practice"],["purity","Edward R. Squibb (1819-1900)","Drug-purity standards"],
    ["germtheory","Louis Pasteur (1822-1895)","Germ theory & sterilization"],["tyndall","John Tyndall (1820-1893)","Tyndallization & heat-resistant spores"],
    ["spores","Ferdinand Cohn (1828-1898)","Bacterial spores"],["autoclave","Charles Chamberland (1851-1908)","The autoclave & the sterilizing filter"],
    ["mycology","David Gruby (1810-1898)","The founding of medical mycology"],["fungi","Raymond Sabouraud (1864-1938)","Culturing pathogenic fungi"],
    ["magicbullet","Paul Ehrlich (1854-1915)","Chemotherapy & the 'magic bullet'"],["purefood","Harvey Wiley (1844-1930)","Pure-food & drug law"],
    ["standardization","Torald Sollmann (1874-1965)","Pharmacology & drug standardization"],["medmycology","Rhoda Benham (1894-1957)","Medical mycology"],
    ["mycoses","Chester Emmons (1900-1985)","Fungal taxonomy & the mycoses"],["biologics","Milton J. Rosenau (1869-1946)","Biologics sterility & standards"]],
},

{ id:"w_water", title:"The Tap", discipline:"Water Supply & Environmental Health",
  teaser:"A city switched its water source and children started turning up sick. Old pipes bursting? A scare over nothing? Or a corrosion safeguard skipped and the warnings buried?",
  overclaimTag:"a rogue plant operator", truthTag:"skipped corrosion control",
  venue:"the Rushton water inquiry", agent:"Investigator Faye Orwell", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Water Pioneers", dossierName:"WATER & PUBLIC-HEALTH PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Rushton water inquiry",
  who:{truth:"official", items:[["operator","The water-plant operator"],["official","Merrick — the city's emergency manager"],["regulator","The state environmental regulator"]]},
  where:{truth:"cityhall", items:[["plant","The Treatment Plant & Intake"],["lab","The Water-Testing Lab"],["cityhall","The City Manager's Office"]]},
  what:{truth:"corrosion", overclaim:"tampering", dismissal:"safe", items:[["tampering","A rogue operator poisoning the supply"],["safe","Nothing wrong — the water meets the rules"],["corrosion","Corrosion control skipped and the warnings suppressed"]]},
  places:["plant","lab","cityhall"],
  chars:[["operator2","Operator Nunez","Treatment-plant operator","🚰","O","the plant","Runs the intake; was told to skip the anti-corrosion dosing to cut costs."],
         ["chemist","The Water Chemist","Water-testing chemist","🧪","W","the lab","Runs the samples; the lead numbers climbed and the high readings were dropped from the average."],
         ["clerk","The Clerk","City-hall records clerk","🗂","C","the office","Keeps the correspondence — the resident complaints and the memo that dismissed them."]],
  topics:[["wateranalysis","Edward Frankland (1825-1899)","Water analysis & purity"],["sanitaryscience","William Sedgwick (1855-1921)","Sanitary science & waterborne disease"],
    ["sanitarychem","Ellen Swallow Richards (1842-1911)","Sanitary chemistry & water quality"],["sewers","Joseph Bazalgette (1819-1891)","Sewers & urban sanitation"],
    ["filtration","George Warren Fuller (1868-1934)","Water filtration & treatment"],["chlorination","John L. Leal (1858-1914)","Chlorination of drinking water"],
    ["chlorinecontrol","Abel Wolman (1892-1989)","Controlled water chlorination"],["sanitaryeng","Gordon Maskew Fair (1894-1970)","Sanitary engineering"],
    ["wastewater","Karl Imhoff (1876-1965)","Wastewater treatment"],["corrosionchem","Marcel Pourbaix (1904-1998)","Corrosion chemistry & passivation"],
    ["corrosioncontrol","Herbert Uhlig (1907-1993)","Corrosion control"],["tetraethyl","Thomas Midgley Jr. (1889-1944)","Tetraethyl lead"],
    ["leadthreshold","Robert Kehoe (1893-1992)","The industry threshold for lead"],["industrial","Alice Hamilton (1869-1970)","Industrial lead poisoning"],
    ["envlead","Clair Patterson (1922-1995)","Environmental lead contamination"],["leadkids","Herbert Needleman (1927-2017)","Lead & children's development"],
    ["flintcorrosion","Marc Edwards (environmental engineer, b. 1964)","Corrosion control & the Flint crisis"],["bloodlead","Mona Hanna-Attisha (pediatrician, b. 1976)","Blood-lead in children & the alarm"]],
},

{ id:"w_blood", title:"The Crossmatch", discipline:"Transfusion & Blood Banking",
  teaser:"A transfusion patient died within minutes on a quiet ward. A murderous nurse? A one-in-a-million reaction? Or a matching safeguard that was defeated?",
  overclaimTag:"a murderous nurse", truthTag:"a defeated matching safeguard",
  venue:"the Carraway Hospital blood-bank inquiry", agent:"Investigator June Halloway", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Transfusion Pioneers", dossierName:"TRANSFUSION PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Carraway Hospital blood-bank inquiry",
  who:{truth:"manager", items:[["nurse2","The transfusion nurse"],["manager","Alder — the blood-bank manager"],["assessor","The lab accreditation assessor"]]},
  where:{truth:"records", items:[["ward","The Transfusion Ward"],["bloodbank","The Blood Bank & Crossmatch Lab"],["records","The Blood-Bank Office & Records"]]},
  what:{truth:"mismatch", overclaim:"murder", dismissal:"rareReaction", items:[["murder","A nurse who deliberately killed the patient"],["rareReaction","A rare, unforeseeable transfusion reaction"],["mismatch","A typing and crossmatch safeguard defeated to save time"]]},
  places:["ward","bloodbank","records"],
  chars:[["wardnurse","Nurse Okafor","Ward nurse","🩸","N","the ward","Hung the unit; the wristband and the bag label were never checked against each other."],
         ["labtech","The Lab Tech","Blood-bank technologist","🔬","L","the blood bank","Runs the crossmatch; the compatibility step had been switched to 'electronic release' to clear the backlog."],
         ["clerk","The Clerk","Blood-bank records clerk","🗂","C","the office","Keeps the sample logs — and the mislabeled tube that started it all."]],
  topics:[["circulation","William Harvey (1578-1657)","The circulation of the blood"],["firsttransfusion","Richard Lower (1631-1691)","The first transfusion experiments"],
    ["earlytransfusion","Jean-Baptiste Denys (1643-1704)","Early transfusion & its dangers"],["humantransfusion","James Blundell (1791-1878)","Human blood transfusion"],
    ["crossmatch","Reuben Ottenberg (1882-1959)","Compatibility testing & the crossmatch"],["typingfirst","Ludvig Hektoen (1863-1951)","Typing before transfusion"],
    ["groups","Jan Janský (1873-1921)","The four blood groups"],["classification","William L. Moss (1876-1957)","Blood-group classification"],
    ["citrate","Luis Agote (1868-1954)","Citrate anticoagulation"],["storedblood","Albert Hustin (1882-1967)","Anticoagulated stored blood"],
    ["preservation","Peyton Rous (1879-1970)","Blood preservation for storage"],["depot","Oswald Robertson (1886-1966)","The first blood depot"],
    ["bankterm","Bernard Fantus (1874-1940)","The 'blood bank'"],["plasma","Edwin Cohn (1892-1953)","Plasma fractionation"],
    ["banking","Charles Drew (1904-1950)","Blood plasma & banking"],["rhfactor","Philip Levine (1900-1987)","The Rh factor & hemolytic disease"],
    ["hepb","Baruch Blumberg (1925-2011)","Hepatitis B & blood screening"],["hepc","Harvey Alter (b. 1935)","Hepatitis C & transfusion safety"]],
},

{ id:"w_trial", title:"The Trial Data", discipline:"Clinical Trials & Biostatistics",
  teaser:"A blockbuster drug sailed through its trials, then patients began dying of its side effects. A crank whistleblower? Random noise? Or adverse-event data that was fabricated and buried?",
  overclaimTag:"a rogue trial investigator", truthTag:"suppressed adverse-event data",
  venue:"the Verazol drug-trial inquiry", agent:"Investigator Sam Rourke", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Trial & Statistics Pioneers", dossierName:"CLINICAL-TRIAL PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Verazol drug-trial inquiry",
  who:{truth:"sponsor", items:[["investigator","The lead trial investigator"],["sponsor","Sable — the sponsor's clinical-trials director"],["monitor","The trial-monitoring auditor"]]},
  where:{truth:"headoffice", items:[["site","The Trial Site & Clinic"],["datacenter","The Data-Management Center"],["headoffice","The Sponsor's Head Office"]]},
  what:{truth:"suppression", overclaim:"fraudsite", dismissal:"noise", items:[["fraudsite","A rogue investigator who faked the results"],["noise","The deaths are unrelated — statistical noise"],["suppression","Adverse-event data fabricated and suppressed behind the approval"]]},
  places:["site","datacenter","headoffice"],
  chars:[["trialnurse","Trial Nurse Devi","Research nurse","💊","N","the clinic","Saw the patients; the serious side effects she reported never reached the file."],
         ["stat","The Statistician","Trial biostatistician","📊","S","the data center","Runs the numbers; whole batches of adverse events were recoded as 'unrelated' before analysis."],
         ["clerk","The Clerk","Sponsor records clerk","🗂","C","the office","Keeps the case-report forms — and the safety signal the sponsor sat on."]],
  topics:[["scurvy","James Lind (1716-1794)","The first controlled trial"],["numerical","Pierre-Charles-Alexandre Louis (1787-1872)","The numerical method"],
    ["ttest","William Sealy Gosset — 'Student' (1876-1937)","Small samples & the t-test"],["randomization","Ronald A. Fisher (1890-1962)","Randomization & experimental design"],
    ["confidence","Jerzy Neyman (1894-1981)","Confidence intervals & hypothesis testing"],["hypothesis","Egon Pearson (1895-1980)","Statistical hypothesis testing"],
    ["doe","Frank Yates (1902-1994)","The design of experiments"],["rct","Austin Bradford Hill (1897-1991)","The randomized controlled trial"],
    ["cohort","Richard Doll (1912-2005)","Cohort studies & causation"],["doubleblind","Harry Gold (1899-1972)","The double-blind trial"],
    ["ebm","Archie Cochrane (1909-1988)","Evidence-based medicine"],["metaanalysis","Thomas Chalmers (1917-1995)","Meta-analysis of trials"],
    ["consent","Louis Lasagna (1923-2003)","Trial ethics & informed consent"],["thalidomide","Frances Oldham Kelsey (1914-2015)","Thalidomide & adverse-event review"],
    ["clinepi","Alvan Feinstein (1925-2001)","Clinical epidemiology"],["appraisal","David Sackett (1934-2015)","Critical appraisal of the evidence"],
    ["consort","Doug Altman (1948-2018)","Honest reporting of trials"],["reliability","John Ioannidis (b. 1965)","The reliability of research findings"]],
},

{ id:"w_hai", title:"The Ward Cluster", discipline:"Hospital Epidemiology & Microbiology",
  teaser:"A run of deadly infections tore through one hospital ward. A murderous staffer? A stroke of terrible luck? Or a sterilization protocol defeated and hidden in the records?",
  overclaimTag:"a murderous staffer", truthTag:"a defeated sterilization protocol",
  venue:"the Kettleridge Hospital infection inquiry", agent:"Investigator Ida Brenner", standingLabel:"Inquiry credibility",
  readingShort:"Pioneers", readingLabel:"Microbiology Pioneers", dossierName:"MICROBIOLOGY & INFECTION PIONEERS",
  enterLabel:"Open the inquiry", subt:"A deduction game inside the Kettleridge Hospital infection inquiry",
  who:{truth:"opsmanager", items:[["nurse4","A ward nurse"],["opsmanager","Whitlock — the hospital's operations manager"],["inspector2","The infection-control inspector"]]},
  where:{truth:"records", items:[["ward2","The Affected Ward"],["sterile","The Sterile-Processing Department"],["records","The Infection-Control Office & Records"]]},
  what:{truth:"protocol", overclaim:"killer", dismissal:"chance", items:[["killer","A staff member deliberately harming patients"],["chance","A tragic run of unrelated infections — chance"],["protocol","A sterilization and isolation protocol defeated, traced through the records"]]},
  places:["ward2","sterile","records"],
  chars:[["chargenurse","Charge Nurse Iyer","Charge nurse","🩺","N","the ward","Runs the ward; the isolation precautions were dropped once the beds filled up."],
         ["cssdtech","The Sterile-Processing Tech","Sterile-processing technician","♨","P","the sterile unit","Reprocesses the instruments; the sterilizer failed its spore test and kept running."],
         ["clerk","The Clerk","Infection-control records clerk","🗂","C","the office","Keeps the surveillance logs — where the cluster stands out for anyone who reads them."]],
  topics:[["microscopy","Antonie van Leeuwenhoek (1632-1723)","The first sight of microbes"],["staph","Alexander Ogston (1844-1929)","The discovery of Staphylococcus"],
    ["ecoli","Theodor Escherich (1857-1911)","E. coli & the gut flora"],["bacteriology","Friedrich Loeffler (1852-1915)","Bacteriology & pathogens"],
    ["cultureplate","Julius Petri (1852-1921)","The culture plate"],["agar","Fanny Hesse (1850-1934)","Agar culture medium"],
    ["gramstain","Hans Christian Gram (1853-1938)","The Gram stain"],["strep","Rebecca Lancefield (1895-1981)","Streptococcus grouping"],
    ["anaerobe","Kitasato Shibasaburō (1853-1931)","Anaerobic culture & pathogens"],["sulfa","Gerhard Domagk (1895-1964)","The sulfa drugs"],
    ["penicillin","Alexander Fleming (1881-1955)","Penicillin"],["pendevelopment","Howard Florey (1898-1968)","Turning penicillin into a medicine"],
    ["penisolation","Ernst Chain (1906-1979)","Isolating penicillin"],["streptomycin","Selman Waksman (1888-1973)","Streptomycin & the antibiotic"],
    ["resistance","Mary Barber (1911-1965)","Hospital antibiotic resistance"],["rfactor","Tsutomu Watanabe (1923-1977)","Transferable drug resistance"],
    ["infectioncontrol","E.J.L. Lowbury (1913-2007)","Hospital infection control"],["handhygiene","Didier Pittet (b. 1957)","Hand hygiene & healthcare infection"]],
},

];
