// copy.js — what each place says
// GENERATED by tools/import-book.mjs from qd-cmb.yml
// Hand edits are lost on the next import. Change the book.

export const COPY = {
  "HORN": "<p>The horn itself, at the top of the track: twenty feet of riveted aluminium on a mount, open to the sky, with a ground shield round the mouth and a ladder to the throat.</p>",
  "RECV": "<p>The receiver hut, right underneath it. The cold load in its dewar, the amplifier chain along one bench, and the list of checks pencilled on the wall with dates against each one.</p>",
  "SPECTRUM": "<p>The spectrum building, further along the ridge and much newer. Forty channels of the same sky at once, and a wall of results none of which the horn could have produced.</p>",
  "COSMO": "<p>The theory room at the end of the track. Two blackboards facing each other, the same background pinned between them, and not one instrument in the place.</p>",
  "GATE": "<p>The gate at the bottom of the track, with the site hut beside it and the log everybody signs on the way up.</p>"
};
