// metrics.js — boomtown's four bars, its recovery economy and its fifteen
// post-mission screens.
//
// GENERATED by tools/bible-metrics.mjs from the campaign bible named in
// books/parts/bibles.json. Edit the bible and run the tool again; an edit here
// is lost the next time a bible arrives, and the bible is what the prose is
// held to.
//
// `target` is the mission's target time in seconds, `event` the story event that
// causes the change, and `deltas` the change itself. A bar reaching 100 is not a
// bar that is safe: only `lockFrom` makes it so, and only from that mission on.
export default {
  bars: [
    { key: "plan_evidence", label: "Plan Evidence", start: 80,
      meaning: "Completeness of tested claims in the agreement" },
    { key: "service_continuity", label: "Service Continuity", start: 85,
      meaning: "Readiness of food and housing continuity measures" },
    { key: "field_budget", label: "Field Budget", start: 85,
      meaning: "Staff and survey margin above committed work" },
    { key: "public_accountability", label: "Public Accountability", start: 70,
      meaning: "Open evidence and named responsibility for promises" },
  ],
  rp: { base: 11, min: 4, max: 12 },
  bank: 30,
  missions: [
    { target: 720,
      event: "The diner posts a meal-for-repair agreement and reopens its lunch queue",
      deltas: { plan_evidence: 3, service_continuity: 2, field_budget: -2, public_accountability: 2 } },
    { target: 720,
      event: "The notice board separates the lunch surge from the delivery cost dispute",
      deltas: { plan_evidence: 2, service_continuity: 1, field_budget: -1, public_accountability: 2 } },
    { target: 720,
      event: "The owner restores the lower advertised rate and opens the vacant rooms",
      deltas: { plan_evidence: 1, service_continuity: 3, field_budget: -1, public_accountability: 2 } },
    { target: 720,
      event: "The diner posts one job and keeps the equipment upgrade on its list",
      deltas: { plan_evidence: 2, service_continuity: 2, field_budget: -2, public_accountability: 1 } },
    { target: 960,
      event: "The hearing labels the rent cap as tenant relief rather than a promise of a home for all",
      deltas: { plan_evidence: -2, service_continuity: 2, field_budget: -1, public_accountability: 4 } },
    { target: 960,
      event: "The council reserves the measured fee proceeds for the housing measure",
      deltas: { plan_evidence: 3, service_continuity: 2, field_budget: 2, public_accountability: 2 } },
    { target: 960,
      event: "The supplier keeps its current shift and marks its lease for review",
      deltas: { plan_evidence: 1, service_continuity: 3, field_budget: -1, public_accountability: 1 } },
    { target: 960,
      event: "New vendor permits appear beside the diner’s old menu",
      deltas: { plan_evidence: 2, service_continuity: 1, field_budget: 1, public_accountability: 2 } },
    { target: 960,
      event: "The wage agreement adds a fourth job and posts the offer openly",
      deltas: { plan_evidence: 2, service_continuity: 2, field_budget: -1, public_accountability: 3 } },
    { target: 960,
      event: "The town posts the unused terminal slots beside the proposed second-line offer",
      deltas: { plan_evidence: -3, service_continuity: 0, field_budget: -1, public_accountability: 4 } },
    { target: 1200,
      event: "The hearing removes the unenforced pact from its guaranteed service forecasts",
      deltas: { plan_evidence: 2, service_continuity: 1, field_budget: -1, public_accountability: 2 } },
    { target: 1200,
      event: "The water notice adds the downstream cost to the freight comparison",
      deltas: { plan_evidence: 2, service_continuity: -2, field_budget: -1, public_accountability: 3 } },
    { target: 1200,
      event: "The council retains the cheaper filter quote and publishes who would gain from the tariff",
      deltas: { plan_evidence: 2, service_continuity: 1, field_budget: 2, public_accountability: 2 } },
    { target: 1200,
      event: "The new-line ribbon is taken down and the access retrofit stays on the hearing board",
      deltas: { plan_evidence: -4, service_continuity: -2, field_budget: -2, public_accountability: -2 } },
    { target: 1200,
      event: "The complete agreement is funded and prepared for the final resource check",
      deltas: { plan_evidence: 7, service_continuity: 4, field_budget: 3, public_accountability: 7 } },
  ],
};
