// missions.js — the campaign, and why it takes each warm-up
// GENERATED by tools/import-book.mjs from qd-keynes.yml
// Hand edits are lost on the next import. Change the book.

export const MISSIONS = [
  {
    "title": "A fall that does not stop",
    "objective": "Follow a shock round the board, find out what decides how it comes out, and say what firms cut first.",
    "briefing": "Keynes wants the second round on the board before anybody talks about prices.",
    "stake": "Monday, and investment spending has fallen by a fifth. John Maynard Keynes, the economic adviser here, is at the board with the whole economy drawn on it and wants the fall traced arrow by arrow. Colin Clark, who counts the national income figures, has the returns for the quarter and one number on them that decides everything. Edith Marchant, the statistical clerk, has spent the week refusing to compare figures that are not comparable. Today you work out what the second round of the fall is worth, say what decides whether demand moves output or prices, and settle what a firm facing weaker orders actually cuts.",
    "takeaway": "A fall in spending arrives as somebody else's lost income, and then goes round again.",
    "stops": [
      {
        "group": "FLOW",
        "lesson": 0,
        "task": "Work out the second round"
      },
      {
        "group": "STAT",
        "lesson": 0,
        "task": "Say what decides how demand comes out"
      },
      {
        "group": "FLOW",
        "lesson": 1,
        "task": "Settle what a firm cuts first"
      }
    ]
  },
  {
    "title": "Rounds that add up",
    "objective": "Read what a set of rounds is doing, sum the series, and find how much leaks out of it.",
    "briefing": "Kahn will not publish a figure nobody can check on a sheet of paper.",
    "stake": "Wednesday, and the model room has the rounds on the long table. Richard Kahn, who works the arithmetic in the model room, will not put a number in a note unless the working is on the sheet beside it. Colin Clark has figures for how much of each extra pound goes to tax, to saving and abroad, and none of those comes back as anybody's income here. Edith Marchant has spent two days making the returns comparable. Today you read what the rounds are actually doing, add the whole series up, and find out how much leakage the tidy figure survives.",
    "takeaway": "A change in spending is amplified by a factor that can be computed, and every leak makes it smaller.",
    "stops": [
      {
        "group": "MODEL",
        "lesson": 0,
        "task": "Which rule produces this row, and not only its first two entries?"
      },
      {
        "group": "MODEL",
        "lesson": 1,
        "task": "Add the whole series up"
      },
      {
        "group": "STAT",
        "lesson": 1,
        "task": "Find how much leakage the figure survives"
      }
    ]
  },
  {
    "title": "What to do, and when not to",
    "objective": "Size the response, test it against the state of the economy, and write the conditions in.",
    "briefing": "Robinson will not let a recommendation leave without its conditions attached.",
    "stake": "Friday, and the desk has to produce a recommendation. Joan Robinson, who runs the policy desk, has the output gap and the honest multiplier and will not release a sentence with the conditions stripped off it. Tom Beddowes, her secretary, is holding the summary back until they are written in, because an unnumbered draft once got quoted as final for three years. And on the file are six claims about what this week established, some of them measured and some of them merely typed. Today you size the injection, test it against a state of the economy nobody has measured exactly, and go through the file.",
    "takeaway": "The strongest claim a model of this kind supports is a conditional one, and the conditions are the part that gets dropped.",
    "stops": [
      {
        "group": "DESK",
        "lesson": 0,
        "task": "Size the injection"
      },
      {
        "group": "DESK",
        "lesson": 1,
        "task": "Test it against a state nobody has measured exactly"
      },
      {
        "group": "MODEL",
        "lesson": 2,
        "task": "Go through the file"
      }
    ]
  }
];

export const WARMUPS = {};
