// missions.js — the campaign, and why it takes each warm-up
// GENERATED by tools/import-book.mjs from outbreak-riverton.yml
// Hand edits are lost on the next import. Change the book.

export const MISSIONS = [
  {
    "title": "The First Cluster",
    "objective": "Open an investigation using a defensible provisional case definition and an explicit comparison baseline.",
    "briefing": "Three Riverton hospitals report an unusual combination of fever, dry cough, severe headache, and profound fatigue. The player must decide whether the pattern is a true outbreak signal before scarce emergency resources are committed.",
    "stake": "Day one. Seven patients, three hospitals, four days, and the same four symptoms in every one of them. The epidemiology lead, Sofia Morales, has the surveillance printout and a reporter downstairs already has the number. This stage you decide whether this is an outbreak at all, agree what counts as a case, and spend the first of the response money. Seven sounds like a lot, and Morales will not say whether it is until she knows what a normal week in this city looks like. Call it nothing and you lose the weeks when an outbreak is still small enough to stop.",
    "takeaway": "Use baseline variation, case definition, controls, correlation versus coincidence, measurement bias as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "POP",
        "lesson": 0,
        "task": "Is this a signal, and what on the desk decides it?"
      },
      {
        "group": "POP",
        "lesson": 1,
        "task": "Order the build so each step can be checked before the next one depends on it."
      },
      {
        "group": "POP",
        "lesson": 2,
        "task": "Spend the single response slot on the evidence that makes tomorrow’s citywide case data interpretable."
      }
    ]
  },
  {
    "title": "What Kind of Agent?",
    "objective": "Classify the broad agent category and identify the next discriminating test.",
    "briefing": "Initial samples contain biological material, but the microscope and the routine tests disagree. The team must distinguish a cellular pathogen from a virus or a noninfectious cause without relying on one ambiguous image.",
    "stake": "Day two. Pathology has four results from the same specimens and will not put a name to any of it. The microscope images are the most convincing thing anybody has seen all week, which is exactly why the cell biology lead, Maya Chen, does not trust them yet, and her diagnostics counterpart Ravi Patel wants to commit the diagnostics bench tonight. This stage you decide what broad kind of thing this is and buy the one piece of evidence that would settle it. Everything downstream is chosen off this call: what to grow it in, which drugs are worth considering, what tomorrow's test looks for.",
    "takeaway": "Use cell structure, viruses versus cells, prokaryotes and eukaryotes, staining, independent evidence as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "CLIN",
        "lesson": 0,
        "task": "Which explanation fits every reading, including the quiet negative controls?"
      },
      {
        "group": "POP",
        "lesson": 3,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "MOL",
        "lesson": 0,
        "task": "A reporter enzyme works after 37 °C pre-incubation and loses most activity after 55 °C. What is the strongest interpretation?"
      }
    ]
  },
  {
    "title": "The Point of Entry",
    "objective": "Explain why one cell type is vulnerable and select the experiment that separates receptor binding from downstream replication.",
    "briefing": "The suspected agent reaches respiratory tissue, but only some cell types become affected. The player must determine how membrane structure, receptors, and transport explain this selectivity.",
    "stake": "Day four. The agent reaches the airway in everybody and only some cells are being damaged, and Adeyemi has spent two nights on why. This stage you work out why those cells and not their neighbours, and design the experiment that separates two steps people keep merging. Two of the three benches are already booked and Adeyemi wants the third tonight. Chen has asked for the resistant cells to be kept aside whatever is decided. Your teams start designing a therapy from this picture tonight. If the model is wrong they spend three months blocking a step the agent does not need.",
    "takeaway": "Use phospholipid bilayer, receptors, diffusion, facilitated transport, endocytosis, cell specificity as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "CELL",
        "lesson": 0,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "CELL",
        "lesson": 1,
        "task": "Match each situation to the most scientifically justified interpretation, control, or response. Each choice is used once."
      },
      {
        "group": "CELL",
        "lesson": 2,
        "task": "Change one condition at a time, reverse the strongest effect, and decide whether the surface-receptor step is causally required for entry."
      }
    ]
  },
  {
    "title": "Hijacked Cells",
    "objective": "Build the information-flow model and choose a measurement that distinguishes more RNA from more efficient translation.",
    "briefing": "Molecular data suggest that affected cells are producing unfamiliar RNA and proteins. The player must reconstruct how information flows from nucleic acid to protein and identify where the agent interrupts normal cell function.",
    "stake": "Day six. Infected cells are turning out RNA and proteins the sequencing centre does not recognise, 1 of them at 40 times the level of anything beside it. A genomic epidemiologist, Lena Bergström, has the time- course data and thinks everybody is looking at the wrong molecule; she has had it for two days and nobody has asked for it. This stage you decide where in the cell's own production line the agent is interfering. The loudest molecule in a sample is often a consequence rather than a cause. Aim at the wrong stage and the whole molecular programme goes into a bystander.",
    "takeaway": "Use DNA and RNA, transcription, translation, codons, protein function, gene regulation as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "MOL",
        "lesson": 1,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "MOL",
        "lesson": 2,
        "task": "Match each situation to the most scientifically justified interpretation, control, or response. Each choice is used once."
      },
      {
        "group": "MOL",
        "lesson": 3,
        "task": "Abundance alone fits every mechanism. Which measurement do you make first?"
      }
    ]
  },
  {
    "title": "A Test Before Morning",
    "objective": "Approve a diagnostic workflow only after its analytical and clinical limitations are explicit.",
    "briefing": "Hospitals need a rapid diagnostic by sunrise. The molecular signal is promising, but contamination, false negatives, and prevalence could make a technically impressive test clinically misleading.",
    "stake": "Day nine, and the hospitals need a working test by sunrise. Patel's overnight run has flagged several patients positive — and one of the controls, a tube that had nothing in it and should have come back empty. 3000 people have already been told to isolate on that run and the bulletin goes out at 6. This stage you decide whether the run can be believed and what a positive would mean for a patient. Patel wants to re-run everything from the start. The hospitals want the six o'clock number.",
    "takeaway": "Use PCR logic, controls, sensitivity, specificity, predictive value, prevalence as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "MOL",
        "lesson": 4,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "MOL",
        "lesson": 5,
        "task": "Open the dependency chain behind each result, keep the evidence that still stands, and name the shared source that makes the amplification positives unreliable."
      },
      {
        "group": "POP",
        "lesson": 4,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "CLIN",
        "lesson": 1,
        "task": "Work the arrivals board while the triage rule changes."
      }
    ]
  },
  {
    "title": "Why Are Some Patients Sicker?",
    "objective": "Identify the physiological bottleneck and select measurements that distinguish ventilation, diffusion, circulation, and cellular oxygen use.",
    "briefing": "Patients with similar test results have radically different oxygen levels and recovery times. The team must connect cellular damage to organ-system physiology and homeostatic failure.",
    "stake": "Day 13. Nakamura has two patients who arrived with the same complaint and the same test results. One is walking to the bathroom. The other is failing, and their oxygen saturation reads normal. This stage you find which link in the oxygen chain has broken and buy the measurement that proves it. Nakamura has one arterial line and two patients she would like it in. The second patient's heart rate has not moved all morning, which she finds harder to explain than the saturation. Escalate the wrong link and the treatment is aimed at a part of the chain that is working.",
    "takeaway": "Use homeostasis, gas exchange, circulation, oxygen transport, feedback, organ-system integration as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "CLIN",
        "lesson": 2,
        "task": "Assemble the oxygen path from air to tissue, then name the link that the full panel makes most likely to be limiting."
      },
      {
        "group": "POP",
        "lesson": 5,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "CLIN",
        "lesson": 3,
        "task": "Use the blood-buffer relationship to estimate arterial pH and interpret what the pair of values supports."
      }
    ]
  },
  {
    "title": "The Immune System Turns",
    "objective": "Construct a timeline of immune responses and decide whether deterioration reflects persistent agent burden, delayed adaptive response, or excessive inflammation.",
    "briefing": "Several patients improve and then suddenly deteriorate as inflammation escalates. The player must distinguish protective immune responses from damaging dysregulation.",
    "stake": "Day 18, and this is Ortiz's stage. Several patients improved for a week and are now deteriorating fast, including the paramedic who drove the first case in. The clinical immunologist, Yusuf Haddad, wants drugs that damp the immune system started tonight and Ortiz is not far behind him; Morales wants the timeline built first. Ortiz is right — people are dying on the ward while the argument runs. This stage you build that timeline anyway, because it is what tells you which drug. Haddad has marker levels for all six patients and dates against only half of them. The paramedic's family is in the corridor.",
    "takeaway": "Use innate immunity, adaptive immunity, antibodies, T cells, inflammation, immune regulation as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "IMM",
        "lesson": 0,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "CLIN",
        "lesson": 4,
        "task": "Which mechanism best explains the reversal in the full panel?"
      },
      {
        "group": "CLIN",
        "lesson": 5,
        "task": "Spend the rapid slot on the evidence that best separates ongoing agent-driven injury from a host response that has outlasted it."
      }
    ]
  },
  {
    "title": "The Hidden Transmission Route",
    "objective": "Identify the hidden route and target surveillance where it changes decisions rather than where sampling is easiest.",
    "briefing": "Cases continue despite hospital isolation. Wastewater and neighborhood data suggest transmission is occurring before severe symptoms appear.",
    "stake": "Day 24, and Morales gets her stage. Ward isolation has held for nine days and cases keep appearing in neighbourhoods with nobody in hospital. A field epidemiologist, Grace Oduya, has pulled a sewer sample from the north of the city that was kept by chance and tested this morning — positive four days before the first patient walked in. This stage you decide where transmission is actually happening and where to put surveillance. Oduya has three sampling teams and the city has four watersheds. The nine days of ward isolation have already cost the hospitals their elective work.",
    "takeaway": "Use incidence, prevalence, transmission chains, sampling, R concepts, asymptomatic spread as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "IMM",
        "lesson": 1,
        "task": "Match each situation to the most scientifically justified interpretation, control, or response. Each choice is used once."
      },
      {
        "group": "CELL",
        "lesson": 3,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "CELL",
        "lesson": 4,
        "task": "Every cell has the same genome. Why do only some of them make the receptor?"
      },
      {
        "group": "FIELD",
        "lesson": 0,
        "task": "Sort the specimen tray before the courier goes."
      }
    ]
  },
  {
    "title": "The Animal Connection",
    "objective": "Build a defensible reservoir hypothesis using ecological exposure, prevalence, and genetic relatedness.",
    "briefing": "Genetic similarities and field reports point toward an animal reservoir near the river corridor. The player must investigate without assuming that the most visible species is the source.",
    "stake": "Day 33. Sequences from three patients sit close to a virus found in animals along the river, and the council has signed an order to clear the heron colony on Saturday. The wildlife vet, Mateo Castellanos, has been out there twice and says the herons are the wrong animal; the One Health lead, Arjun Singh, will not say either way until the sampling is designed properly. This stage you decide what role any animal is actually playing and design the campaign that could show it. What is being argued about is who infects whom over time, not which animal is nearby or easiest to blame.",
    "takeaway": "Use reservoirs, vectors, food webs, host range, ecological sampling, One Health as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "FIELD",
        "lesson": 1,
        "task": "Match each situation to the most scientifically justified interpretation, control, or response. Each choice is used once."
      },
      {
        "group": "FIELD",
        "lesson": 2,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "POP",
        "lesson": 6,
        "task": "Allocate the 20 slots so the campaign can distinguish a reservoir pattern from spillback or a one-household sampling artifact."
      }
    ]
  },
  {
    "title": "The Mutation",
    "objective": "Distinguish change in frequency from proof of advantage and identify evidence that tests competing evolutionary explanations.",
    "briefing": "A new genetic variant rises rapidly in one part of the city. The player must decide whether its increase reflects natural selection, random founder effects, or biased sampling.",
    "stake": "Day 45. A variant with 3 changes has gone from 8 to 31% of sequences in 4 weeks, in 1 district, and the briefing is in an hour. Bergström will not call it selection yet. This stage you decide whether that rise means the variant is better at spreading, and get the frequencies onto a footing you can defend. The district that produced the rise also changed who it swabs, which Bergström noticed on Tuesday. The minister's briefing note already calls it a new strain. If you call selection on an artefact, the next real signal will be dismissed too.",
    "takeaway": "Use mutation, selection, genetic drift, founder effects, fitness, allele frequency as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "MOL",
        "lesson": 6,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "POP",
        "lesson": 7,
        "task": "Which explanation best fits the frequency trend and the independent checks?"
      },
      {
        "group": "POP",
        "lesson": 8,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      }
    ]
  },
  {
    "title": "Treatment Failure",
    "objective": "Separate inherited resistance from non-genetic treatment failure and propose a strategy that reduces selective advantage without undertreating patients.",
    "briefing": "A therapy that initially helped is failing in a growing subset of patients. The player must determine whether the cause is biological resistance, poor delivery, incorrect dosing, or patient heterogeneity.",
    "stake": "Day 60. The therapy that bought this city six weeks is failing in one patient in four, and the failures cluster on the wards where it has been used most. Ortiz wants the dose raised today. Bergström has a resistant sequence from a river sample banked a month before the first dose was given anywhere. This stage you work out why it is failing and decide what to do that does not make it worse. Raising the dose is the fastest thing this room can do and might also be the worst. Nobody has yet checked whether the failing patients received every round.",
    "takeaway": "Use resistance, selection pressure, dose-response, targets, pharmacokinetics, heterogeneity as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "POP",
        "lesson": 9,
        "task": "Which explanation fits the complete treatment-response panel?"
      },
      {
        "group": "POP",
        "lesson": 10,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "POP",
        "lesson": 11,
        "task": "One thing before anybody's prescription changes. Which?"
      }
    ]
  },
  {
    "title": "Design the Intervention",
    "objective": "Select a layered intervention portfolio and identify the evidence required before deployment.",
    "briefing": "The city needs an intervention that can be manufactured, tested, and deployed. The player must compare vaccines, targeted therapies, and nonpharmaceutical measures using evidence about mechanism and evidence about populations.",
    "stake": "Day 78. The city wants an intervention and the room is arguing as though it can only have one. The antibody everyone favours binds the exact stretch of protein that mutated in the north, which Bergström has now said three times. This stage you choose what to fund and say what evidence is needed before any of it reaches a person. The options also arrive on different timescales — one is available on Monday, one in a year — which is the whole argument for layering them rather than picking a favourite. Back a single glamorous option and the city has one point of failure against something still changing.",
    "takeaway": "Use antigens, immune memory, drug targets, intervention layers, efficacy versus effectiveness as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "POP",
        "lesson": 12,
        "task": "Match each situation to the most scientifically justified interpretation, control, or response. Each choice is used once."
      },
      {
        "group": "POP",
        "lesson": 13,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "POP",
        "lesson": 14,
        "task": "Allocate three funding slots to a portfolio that acts now, preserves a longer-horizon layer, and avoids depending on one shared mechanism."
      },
      {
        "group": "IMM",
        "lesson": 2,
        "task": "Hold the isolation room while the doors keep opening."
      }
    ]
  },
  {
    "title": "The Trial Signal",
    "objective": "Make a conditional trial decision that weighs benefit, uncertainty, and safety rather than relying on one p-value or headline percentage.",
    "briefing": "Early trial results appear encouraging, but enrollment is small and adverse events are uneven. The player must distinguish a real effect from random variation and decide whether the trial should expand.",
    "stake": "Day 96, and the trial has reported: 10 hospitalisations in the treated group against 20 in the control, out of 400 people. Most of that benefit sits at the one site that enrolled the youngest patients, and the serious adverse events are not spread evenly either. The health minister wants a number before deciding how much to buy, and has been given one percentage she would like confirmed. This stage you read the result properly and decide whether the trial continues, expands or stops. Nobody in the room has yet said how many people 20 is out of.",
    "takeaway": "Use randomization, control groups, effect size, confidence intervals, adverse events, stopping rules as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "CLIN",
        "lesson": 6,
        "task": "One site enrolled younger patients and contributes much of the apparent benefit. What should the trial team do before attributing the difference to treatment?"
      },
      {
        "group": "POP",
        "lesson": 15,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "POP",
        "lesson": 16,
        "task": "The benefit estimate is promising but imprecise, and adverse events are uneven. What is the defensible next decision?"
      }
    ]
  },
  {
    "title": "Containment or Adaptation?",
    "objective": "Use scenarios and trigger-based policies instead of pretending one forecast is certain.",
    "briefing": "The outbreak is geographically uneven. Leaders must choose between aggressive local containment, broader mitigation, and long-term adaptation while the biological parameters remain uncertain.",
    "stake": "Day 121 districts are on visibly different paths and the council wants 1 policy by Friday. 90 of the region's hundred and 20 critical-care beds are full and severe cases are arriving at about 8 a day. Ortiz wants the beds protected; Morales wants the growth stopped where it is still cheap. Ortiz has the bed numbers by hour, Morales has the district growth rates, and the two documents have never been in the same room. This stage you build the arithmetic behind the decision and choose a policy that survives being wrong. The honest answer to an uncertain future is a set of triggers rather than one guess.",
    "takeaway": "Use population growth, feedback, capacity thresholds, model assumptions, scenario analysis, tradeoffs as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "POP",
        "lesson": 17,
        "task": "Arrange the four cards from the earliest prerequisite or cause to the latest result. The interface should lock correctly placed cards after each check."
      },
      {
        "group": "CLIN",
        "lesson": 7,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "POP",
        "lesson": 18,
        "task": "Set the occupancy threshold before releasing the next capacity updates, then see whether the staffing still has the lead time it needs."
      }
    ]
  },
  {
    "title": "The Final Briefing",
    "objective": "Produce a claim-by-claim evidence package with explicit residual uncertainties and durable surveillance responsibilities.",
    "briefing": "The mayor, hospitals, and public must receive one integrated account of what happened, what remains uncertain, and which actions should continue.",
    "stake": "Day 140. The mayor is on air in an hour, and behind that broadcast sit five months of conclusions that are not equally solid. The route of transmission is settled. The animal source is not, and Castellanos has said so in writing. One thing said in public early — that this began with the hospital cluster — did not survive Oduya's sewer sample. This stage you go through the claims one at a time and decide what the city keeps funding after the emergency budget closes. Say too little and the next outbreak arrives with nobody watching for it.",
    "takeaway": "Use evidence synthesis, causal chains, uncertainty, ethics, communication, long-term monitoring as an evidence chain rather than as isolated facts.",
    "stops": [
      {
        "group": "POP",
        "lesson": 19,
        "task": "Spend the two independent checks on the critical claims that still lack adequate backing, then disposition the final report."
      },
      {
        "group": "POP",
        "lesson": 20,
        "task": "Order the briefing by how much weight each claim can carry."
      },
      {
        "group": "POP",
        "lesson": 21,
        "task": "The emergency budget closes this month. Which durable capability should receive the protected outbreak-surveillance funding?"
      }
    ]
  }
];

export const WARMUPS = {
  "trial-near": {
    "title": "Walk the campus before you are needed on it",
    "why": "Week three, and the hospital has been rebuilt around the outbreak: triage marquees in the courtyards, a decon tunnel across the main route, container labs where the car park was. Ortiz, the clinical physiology lead, walks every arrival round once, because a route you have not walked is a route you will take through a clean corridor in dirty gloves."
  },
  "greet": {
    "title": "Six leads, three shifts, and a fence between them",
    "why": "The clinical side and the laboratory side have barely met, and by the end of the week a decision will rest on one trusting the other's number. Get round the campus and put a name to every lead before the next shift change, because at three in the morning a phone call from somebody you have met is a different conversation."
  },
  "trial-far": {
    "title": "The containment ward opens today, and the transport with it",
    "why": "Everything past the fence has been off the call list all week. From today the containment ward and the mortuary annexe are on it, and they are far enough out that transport is signed out to reach them. Drive the route once before somebody is waiting at the other end of it."
  },
  "follow": {
    "title": "Chen walks the specimen path once, end to end",
    "why": "A swab taken in a marquee reaches the container lab through four pairs of hands, and every handover is a place contamination can enter. Chen, the cell biology lead, walks the whole path this morning at the pace it actually happens. Stay with her — the handovers are where the walk is learned and where somebody following too closely gets in the way."
  },
  "hunt": {
    "title": "Six ventilators, and the board accounts for four",
    "item": {
      "name": "ventilator",
      "plural": "ventilators"
    },
    "why": "Before tonight's admissions the ward has to know what it actually has. Four ventilators are where the board says. Two were moved during the weekend surge and nobody updated anything. Find them, because a machine nobody can locate is a machine that does not exist at two in the morning."
  },
  "canvass": {
    "title": "Who in Ferry Ward is actually staying home",
    "why": "The transmission estimate assumes the advice was followed, and the difference between a ward that isolated and a ward that could not decides whether the curve is bending. Ask along the streets until enough answers have come back to tell those two apart."
  },
  "evade": {
    "title": "The journalist at the gate who wants a number",
    "why": "A reporter has been at the main gate since six wanting today's case count before it is confirmed, and Morales, the epidemiology lead, has been clear that nothing goes out before the reconcile. Keep clear and finish your round. A number given at a gate is a number the hospital will spend a week correcting."
  },
  "tag": {
    "title": "Catch Patel before he goes into the container lab",
    "why": "Patel, the molecular diagnostics lead, has the run sheet for last night's plates, which is the only record of which samples were re-tested and which were not. Once he is gowned and inside he is unreachable for three hours, and this morning's positives cannot be interpreted without knowing which of them are repeats."
  }
};
