// cards.js — planetary_defense_v2's opening card and its ending card.
//
// GENERATED by tools/bible-copy.mjs from the campaign bible named in
// books/parts/bibles.json, VERBATIM. This is the bible's own "Opening sequence"
// paragraph and not a retelling of it: edit the bible and run the tool again.
//
// It is above the grade-6.5 card bar, and deliberately. The card that used to be
// here was written down to that bar in this repo, which put the game and the
// bible in disagreement about what the player is told on the first screen.
export const OPENING = [
  "You are the asteroid response lead, which means you turn sky measurements into a warning "
    +   "people can use. At Cerro Alto, you will use astronomy to make the call. Eleven days "
    +   "remain for fifteen work shifts. A new object may hit Earth; the broad path covers nine "
    +   "million people, but it is too wide for a local order. Director Mira Chen closes the "
    +   "launch binder and says, “If we tell a town to leave, I need to be able to tell them "
    +   "why.”",
];

export const ENDING = [
  "The network wall fills with acknowledgements. Below the ridge, the first marked buses "
    +   "leave for the narrow warning zone. Most town lights stay steady. The main-body "
    +   "stand-down remains green, and the dish keeps tracking the smaller fragment.",
];
