export const HISTORIC_CHARACTERS=[
  {id:"patel",name:"Dr. Maya Patel",role:"ED Director",bio:"<p>Leads Emergency Department triage. Teaches breathing clues first.</p>",color:"#c0392b",hat:"none" },
  {id:"reyes",name:"Dr. Luis Reyes",role:"Respiratory Lead",bio:"<p>Pediatric lung specialist.</p>",color:"#2980b9",hat:"none" },
  {id:"chen",name:"Dr. Mei Chen",role:"Pediatrics",bio:"<p>Nutrition and digestion.</p>",color:"#27ae60",hat:"none" },
  {id:"garcia",name:"Dr. Elena Garcia",role:"Orthopedics",bio:"<p>Bones and rehab.</p>",color:"#d35400",hat:"none" },
  {id:"kim",name:"Dr. Sam Kim",role:"Neurology",bio:"<p>Brain and senses.</p>",color:"#16a085",hat:"none" },
  {id:"okafor",name:"Dr. Amaka Okafor",role:"Infection",bio:"<p>Germs and immunity.</p>",color:"#2c3e50",hat:"none" },
  {id:"nurse_lee",name:"Nurse Alex Lee",role:"Charge Nurse",bio:"<p>Keeps shifts on time.</p>",color:"#8e44ad",hat:"cap" },
  {id:"amara",name:"Amara",role:"Patient",bio:"<p>Patient Amara.</p>",color:"#7f8c8d",hat:"none" },
  {id:"ana",name:"Ana",role:"Patient",bio:"<p>Patient Ana.</p>",color:"#7f8c8d",hat:"none" },
  {id:"arjun",name:"Arjun",role:"Patient",bio:"<p>Patient Arjun.</p>",color:"#7f8c8d",hat:"none" },
  {id:"ava",name:"Ava",role:"Patient",bio:"<p>Patient Ava.</p>",color:"#7f8c8d",hat:"none" },
  {id:"ben",name:"Ben",role:"Patient",bio:"<p>Patient Ben.</p>",color:"#7f8c8d",hat:"none" },
  {id:"caleb",name:"Caleb",role:"Patient",bio:"<p>Patient Caleb.</p>",color:"#7f8c8d",hat:"none" },
  {id:"chloe",name:"Chloe",role:"Patient",bio:"<p>Patient Chloe.</p>",color:"#7f8c8d",hat:"none" },
  {id:"dante",name:"Dante",role:"Patient",bio:"<p>Patient Dante.</p>",color:"#7f8c8d",hat:"none" },
  {id:"deshawn",name:"DeShawn",role:"Patient",bio:"<p>Patient DeShawn.</p>",color:"#7f8c8d",hat:"none" },
  {id:"eli",name:"Eli",role:"Patient",bio:"<p>Patient Eli.</p>",color:"#7f8c8d",hat:"none" },
  {id:"ella",name:"Ella",role:"Patient",bio:"<p>Patient Ella.</p>",color:"#7f8c8d",hat:"none" },
  {id:"fatima",name:"Fatima",role:"Patient",bio:"<p>Patient Fatima.</p>",color:"#7f8c8d",hat:"none" },
  {id:"harper",name:"Harper",role:"Patient",bio:"<p>Patient Harper.</p>",color:"#7f8c8d",hat:"none" },
  {id:"ivy",name:"Ivy",role:"Patient",bio:"<p>Patient Ivy.</p>",color:"#7f8c8d",hat:"none" },
  {id:"jamal",name:"Jamal",role:"Patient",bio:"<p>Patient Jamal.</p>",color:"#7f8c8d",hat:"none" },
  {id:"jordan",name:"Jordan",role:"Patient",bio:"<p>Patient Jordan.</p>",color:"#7f8c8d",hat:"none" },
  {id:"jules",name:"Jules",role:"Patient",bio:"<p>Patient Jules.</p>",color:"#7f8c8d",hat:"none" },
  {id:"june",name:"June",role:"Patient",bio:"<p>Patient June.</p>",color:"#7f8c8d",hat:"none" },
  {id:"lena",name:"Lena",role:"Patient",bio:"<p>Patient Lena.</p>",color:"#7f8c8d",hat:"none" },
  {id:"lily",name:"Lily",role:"Patient",bio:"<p>Patient Lily.</p>",color:"#7f8c8d",hat:"none" },
  {id:"luis",name:"Luis",role:"Patient",bio:"<p>Patient Luis.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mae",name:"Mae",role:"Patient",bio:"<p>Patient Mae.</p>",color:"#7f8c8d",hat:"none" },
  {id:"malik",name:"Malik",role:"Patient",bio:"<p>Patient Malik.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mateo",name:"Mateo",role:"Patient",bio:"<p>Patient Mateo.</p>",color:"#7f8c8d",hat:"none" },
  {id:"maya",name:"Maya",role:"Patient",bio:"<p>Patient Maya.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mei",name:"Mei",role:"Patient",bio:"<p>Patient Mei.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mina",name:"Mina",role:"Patient",bio:"<p>Patient Mina.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mr_alvarez",name:"Mr. Alvarez",role:"Patient",bio:"<p>Patient Mr. Alvarez.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mr_bell",name:"Mr. Bell",role:"Patient",bio:"<p>Patient Mr. Bell.</p>",color:"#7f8c8d",hat:"none" },
  {id:"mr_cho",name:"Mr. Cho",role:"Patient",bio:"<p>Patient Mr. Cho.</p>",color:"#7f8c8d",hat:"none" },
];