// groups.js — the areas of study
// GENERATED by tools/import-book.mjs from overwind_v2.yml
// Hand edits are lost on the next import. Change the book.

export const GROUPS = [
  {
    "id": "BANK",
    "code": "BANK",
    "name": "The Bank",
    "color": "#2f6f9f",
    "difficulty": 2,
    "type": "protocol",
    "desc": "Source position (-9, -4); canonical named owner Ruth Bell, cage operator.",
    "defaultLeader": "bell",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "WIND",
    "code": "WIND",
    "name": "Winder House",
    "color": "#7a5aa8",
    "difficulty": 3,
    "type": "protocol",
    "desc": "Source position (-30, 6); canonical named owner Ewan Price, winding engineer.",
    "defaultLeader": "price",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "ROPE",
    "code": "ROPE",
    "name": "Rope Shop",
    "color": "#c2704a",
    "difficulty": 4,
    "type": "protocol",
    "desc": "Source position (-34, 34); canonical named owner Mara Shaw, rope technician.",
    "defaultLeader": "shaw",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "CAGE",
    "code": "CAGE",
    "name": "Shaft and Brake House",
    "color": "#3f8d6e",
    "difficulty": 2,
    "type": "protocol",
    "desc": "Source position (20, -4); canonical named owner Ada Kerr, mine safety engineer.",
    "defaultLeader": "kerr",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "TIP",
    "code": "TIP",
    "name": "Tip and Conveyor",
    "color": "#8a7a3f",
    "difficulty": 3,
    "type": "protocol",
    "desc": "Source position (34, -30); canonical named owner Ivo Reed, conveyor foreman.",
    "defaultLeader": "reed",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "GRAV",
    "code": "GRAV",
    "name": "Gravity Station",
    "color": "#4f6f8f",
    "difficulty": 4,
    "type": "protocol",
    "desc": "Source position (-70, -290); canonical named owner Nia Cole, survey engineer.",
    "defaultLeader": "cole",
    "budget": 70,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  }
];
