// fixtures.js — the objects the questions are about, for Red Sand: Full Tank.
//
// GENERATED from the campaign bible by tools/build-fixtures.mjs. Every id, place,
// kind and caption is the bible's; `wall` and `along` are this file's, because
// they are about the room rather than the object. Look at them with
// `npm run shots` before believing the arrangement — see gamekit/INTERIORS.md.
//
//   build:  'vessel' | 'rack' | 'bench' | 'board'
//   wall:   'left' | 'right' | 'back'
//   along:  -1 … 1 along that wall. 0 is the middle.
export const FIXTURES = {
  GIBBS: [
    { id: 'chronology-wall', name: 'chronology wall', build: 'board', wall: 'back', along: 0,
      caption: "A five-event chronology rail for locking the physical order of the reactor incident." },
    { id: 'conversion-board', name: 'Tank mass on the left', build: 'board', wall: 'left', along: 0,
      caption: "Tank mass on the left, particle count on the right, and a blank unit path between them." },
    { id: 'evidence-board', name: 'Raw carbon', build: 'board', wall: 'right', along: 0,
      caption: "Raw carbon, gas, water, pressure, and calibration evidence arranged without dashboard summaries." },
    { id: 'final-recovery-board', name: 'The final recovery plans with time', build: 'board', wall: 'back', along: -0.45,
      caption: "The final recovery plans with time, power, amount, thermal, and composition consequences." },
    { id: 'ledger', name: 'Carbon entering', build: 'bench', wall: 'left', along: -0.45,
      caption: "Carbon entering, carbon accounted for, and a magnet marked DO NOT EXPLAIN YET." },
    { id: 'loadboard', name: 'loadboard', build: 'board', wall: 'right', along: -0.45,
      caption: "The four campaign loads and their current margins, shown together for allocation decisions." },
    { id: 'operating-point-board', name: 'operating point board', build: 'board', wall: 'back', along: 0.45,
      caption: "Temperature and pressure controls overlaid with rate, equilibrium-yield, and thermal constraints." },
    { id: 'rate-board', name: 'rate board', build: 'board', wall: 'left', along: 0.45,
      caption: "Initial-rate trials and a blank rate-law line for comparing concentration changes." },
    { id: 'sample-tray', name: 'sample tray', build: 'bench', wall: 'right', along: 0.45,
      caption: "Four sealed sample cards waiting to be classified before the ledger can be trusted." },
    { id: 'verification-panel', name: 'Independent access', build: 'board', wall: 'back', along: -0.2,
      caption: "Independent access, controller, and temperature records shown side by side for action verification." },
  ],
  INTAKE: [
    { id: 'compressor-log-desk', name: 'compressor log desk', build: 'bench', wall: 'back', along: 0,
      caption: "The hand-checked compressor log with captured carbon dioxide and the current methane target." },
    { id: 'compressors', name: 'compressors', build: 'vessel', wall: 'left', along: 0,
      caption: "The intake compressor platform with the live capture log and overdrive control." },
    { id: 'intake-bypass-manifold', name: 'intake bypass manifold', build: 'vessel', wall: 'right', along: 0,
      caption: "The hydrogen-release manifold dividing a finite supply among production, diagnosis, and restart reserve." },
    { id: 'intake-calculation-board', name: 'intake calculation board', build: 'board', wall: 'back', along: -0.45,
      caption: "A mass-to-methane conversion path beside the full-shift carbon-dioxide capture record." },
  ],
  HSTORE: [
    { id: 'gas-sampling-ports', name: 'gas sampling ports', build: 'rack', wall: 'back', along: 0,
      caption: "Four sampling ports from tank to reactor branch, each with room for an observed and expected composition." },
    { id: 'hydrogen-calculation-desk', name: 'Pressure', build: 'bench', wall: 'left', along: 0,
      caption: "Pressure, volume, temperature, and gas-constant values laid out for the total-mole calculation." },
    { id: 'jacket-heater-logger', name: 'A sealed branch with a jacket heater', build: 'vessel', wall: 'right', along: 0,
      caption: "A sealed branch with a jacket heater, temperature control, pressure logger, and composition tap." },
    { id: 'store-scales', name: 'store scales', build: 'bench', wall: 'back', along: -0.45,
      caption: "Storage mass and pressure readings beside the line that feeds the reactor." },
  ],
  KINET: [
    { id: 'bed', name: 'The catalyst bed housing', build: 'vessel', wall: 'back', along: 0,
      caption: "The catalyst bed housing, with inlet and outlet access and a visible flow direction." },
    { id: 'bed-log', name: 'bed log', build: 'board', wall: 'left', along: 0,
      caption: "The catalyst-bed mechanism rail and operating log, including free sites and surface intermediates." },
    { id: 'bed-ports', name: 'bed ports', build: 'rack', wall: 'right', along: 0,
      caption: "Four axial catalyst-bed ports from inlet to outlet for temperature, conversion, halide, and activity readings." },
    { id: 'charge-bench', name: 'charge bench', build: 'bench', wall: 'back', along: -0.45,
      caption: "Molecular and catalyst charge models arranged for structure and catalyst questions." },
    { id: 'model-rail-desk', name: 'Property cards for matching molecular shape', build: 'bench', wall: 'left', along: -0.45,
      caption: "Property cards for matching molecular shape, polarity, and dominant intermolecular force." },
    { id: 'molecular-model-rail', name: 'molecular model rail', build: 'rack', wall: 'right', along: -0.45,
      caption: "Three-dimensional molecular models that can be ordered from Lewis structure through polarity." },
    { id: 'separation-cartridge', name: 'separation cartridge', build: 'vessel', wall: 'back', along: 0.45,
      caption: "A temperature-controlled cartridge that shows which substances pass, remain, or condense." },
  ],
  SOIL: [
    { id: 'brinetank', name: 'The recycle-water tank with measured acid', build: 'vessel', wall: 'back', along: 0,
      caption: "The recycle-water tank with measured acid, base-addition control, and pH probe." },
    { id: 'columns', name: 'The treatment columns for particles', build: 'vessel', wall: 'left', along: 0,
      caption: "The treatment columns for particles, dissolved ions, and other water-cleanup steps." },
    { id: 'hopper', name: 'hopper', build: 'vessel', wall: 'right', along: 0,
      caption: "The raw-water hopper receiving ice and brine before treatment." },
    { id: 'spectrophotometer', name: 'spectrophotometer', build: 'vessel', wall: 'back', along: -0.45,
      caption: "A wavelength-controlled spectrophotometer with a sealed standard and an unknown-sample slot." },
    { id: 'water-assay-desk', name: 'Mass', build: 'bench', wall: 'left', along: -0.45,
      caption: "Mass, molar mass, and sample volume values for putting the recycle sample on a molar scale." },
    { id: 'water-report', name: 'water report', build: 'board', wall: 'right', along: -0.45,
      caption: "The recycle-water report separating concentration from total amount." },
  ],
  CUT: [
    { id: 'excavation-face', name: 'excavation face', build: 'vessel', wall: 'back', along: 0,
      caption: "The exposed ice-and-regolith face where the plant's raw water source is collected." },
    { id: 'process-map', name: 'A site-wide material map linking ice', build: 'board', wall: 'left', along: 0,
      caption: "A site-wide material map linking ice, water treatment, electrolysis, the reactor, and water return." },
    { id: 'rover-sampler', name: 'rover sampler', build: 'rack', wall: 'right', along: 0,
      caption: "The rover field sampler holding an independent source vial, blank, and calibration standard." },
  ],
  EQUIL: [
    { id: 'analyser', name: 'The reactor analyser used to freeze models', build: 'board', wall: 'back', along: 0,
      caption: "The reactor analyser used to freeze models, reveal holdout runs, and compare predicted behavior." },
    { id: 'bed-head', name: 'bed head', build: 'vessel', wall: 'left', along: 0,
      caption: "The reactor-bed head where inlet conditions and thermal gradients are first visible." },
    { id: 'equil-stub', name: 'The equilibrium board with Q on one side', build: 'board', wall: 'right', along: 0,
      caption: "The equilibrium board with Q on one side, K on the other, and the gap between them." },
    { id: 'heat-model-board', name: 'heat model board', build: 'board', wall: 'back', along: -0.45,
      caption: "A heating-and-phase-change rail used to reconstruct when thermal signals should arrive." },
    { id: 'ice-board', name: 'ice board', build: 'board', wall: 'left', along: -0.45,
      caption: "An ICE table for the Sabatier gases with linked stoichiometric changes and an equilibrium row." },
    { id: 'reactor-calculation-bench', name: 'Coolant mass', build: 'bench', wall: 'right', along: -0.45,
      caption: "Coolant mass, heat capacity, and temperature-rise data laid out for the heat-removal calculation." },
    { id: 'reactor-console', name: 'The reactor console with the operating point', build: 'board', wall: 'back', along: 0.45,
      caption: "The reactor console with the operating point, sensor-bias control, and thermal safety limit." },
    { id: 'residual-field', name: 'residual field', build: 'board', wall: 'left', along: 0.45,
      caption: "A residual field comparing observed and predicted inlet temperatures across normal and low-radiator runs." },
    { id: 'skid', name: 'The Sabatier reactor skid with temperature', build: 'vessel', wall: 'right', along: 0.45,
      caption: "The Sabatier reactor skid with temperature, pressure, feed, and coolant controls." },
  ],
  PHASE: [
    { id: 'coldline', name: 'coldline', build: 'vessel', wall: 'back', along: 0,
      caption: "The cold product line where water removal and phase behavior affect methane recovery." },
    { id: 'coldline-tap', name: 'coldline tap', build: 'vessel', wall: 'left', along: 0,
      caption: "A controlled cold-line tap for removing product water and restoring the original condition." },
    { id: 'fridge', name: 'fridge', build: 'vessel', wall: 'right', along: 0,
      caption: "The refrigeration stage that keeps separated product inside the required temperature range." },
    { id: 'phase-radiator', name: 'phase radiator', build: 'vessel', wall: 'back', along: -0.45,
      caption: "The radiator-side heat ledger showing coolant removal, storage, carried heat, and accumulation." },
  ],
  ELEC: [
    { id: 'cell-diagram', name: 'A cell diagram showing the cathode', build: 'board', wall: 'back', along: 0,
      caption: "A cell diagram showing the cathode, anode, electron path, ion path, and gas outlets." },
    { id: 'stack', name: 'stack', build: 'vessel', wall: 'left', along: 0,
      caption: "The electrolyzer stack that splits treated water into hydrogen and oxygen." },
    { id: 'stack-accounting-panel', name: 'stack accounting panel', build: 'board', wall: 'right', along: 0,
      caption: "The whole-plant hydrogen ledger beside the electrolyzer stack and recycle-water input." },
    { id: 'stack-power-controller', name: 'stack power controller', build: 'board', wall: 'back', along: -0.45,
      caption: "The dust-limited recovery power controller with protected loads and the electrolysis allocation." },
    { id: 'stack-sheet', name: 'The timed current', build: 'board', wall: 'left', along: -0.45,
      caption: "The timed current, efficiency, Faraday constant, and hydrogen-yield calculation sheet." },
    { id: 'volt-sheet', name: 'volt sheet', build: 'board', wall: 'right', along: -0.45,
      caption: "The stack voltage and current sheet used to connect electrical input with chemical output." },
  ],
  ASSAY: [
    { id: 'assay-review-board', name: 'The Batch C review board combining amount', build: 'board', wall: 'back', along: 0,
      caption: "The Batch C review board combining amount, pressure, contaminant, dryer, and calibration evidence." },
    { id: 'spec-bench', name: 'spec bench', build: 'bench', wall: 'left', along: 0,
      caption: "The independent specification bench with sealed standards and composition assays." },
  ],
  ARRAY: [
    { id: 'array-controller', name: 'array controller', build: 'board', wall: 'back', along: 0,
      caption: "The live solar-array controller showing dust-limited generation and available electrical power." },
  ],
  BATT: [
    { id: 'cell-stacks', name: 'cell stacks', build: 'rack', wall: 'back', along: 0,
      caption: "The battery cell stacks with the protected reserve floor and a diagram of the external circuit." },
  ],
  TANKS: [
    { id: 'casebook-board', name: 'casebook board', build: 'board', wall: 'back', along: 0,
      caption: "A casebook board for matching earlier clues to the meanings supported by later evidence." },
    { id: 'farm-gauges', name: 'Tank pressure', build: 'board', wall: 'left', along: 0,
      caption: "Tank pressure, mass, composition, and loading status shown at the farm gauges." },
    { id: 'tank-calculation-station', name: 'tank calculation station', build: 'bench', wall: 'right', along: 0,
      caption: "The final plan-comparison station for certified methane, processing loss, pressure, and thermal limits." },
    { id: 'umbilical', name: 'umbilical', build: 'vessel', wall: 'back', along: -0.45,
      caption: "The loading umbilical carrying conditioned propellant toward the ascent vehicle." },
  ],
  PAD: [
    { id: 'certification-console', name: 'certification console', build: 'board', wall: 'back', along: 0,
      caption: "The launch certification console with fixed acceptance rules and the final GO / NO-GO panel." },
    { id: 'recovery-allocation-board', name: 'recovery allocation board', build: 'board', wall: 'left', along: 0,
      caption: "A 100-point recovery allocation board beside Commander Abiola's final decision position." },
  ],
};
