// fixtures.js — the objects the questions are about, for Safety Factor.
//
// GENERATED from the campaign bible by tools/build-fixtures.mjs. Every id, place,
// kind and caption is the bible's; `wall` and `along` are this file's, because
// they are about the room rather than the object. Look at them with
// `npm run shots` before believing the arrangement — see gamekit/INTERIORS.md.
//
//   build:  'vessel' | 'rack' | 'bench' | 'board'
//   wall:   'left' | 'right' | 'back'
//   along:  -1 … 1 along that wall. 0 is the middle.
export const FIXTURES = {
  WHEEL: [
    { id: 'hub-schedule', name: 'hub schedule', build: 'board', wall: 'back', along: 0,
      caption: "The old stopping trace and the wheel loading schedule share this marked board." },
    { id: 'gondola-shell', name: 'gondola shell', build: 'vessel', wall: 'left', along: 0,
      caption: "A grounded gondola shell shows the carried mass and attachment points." },
    { id: 'brake-drum', name: 'The guarded drum shows its prediction mark', build: 'vessel', wall: 'right', along: 0,
      caption: "The guarded drum shows its prediction mark, stop mark, and operating-rule card." },
    { id: 'arm-nine-file', name: 'arm nine file', build: 'rack', wall: 'back', along: -0.45,
      caption: "The arm-nine inspection record waits in a yellow evidence sleeve." },
    { id: 'machine-room-board', name: 'machine room board', build: 'board', wall: 'left', along: -0.45,
      caption: "This board carries rotational and stopping calculations beside the wheel." },
    { id: 'hub-board', name: 'hub board', build: 'board', wall: 'right', along: -0.45,
      caption: "This board turns the hub trace into a signed kinematics prediction." },
    { id: 'wheel-case-stand', name: 'wheel case stand', build: 'bench', wall: 'back', along: 0.45,
      caption: "The wheel case stand holds the shared-capacity cards and inspection condition." },
  ],
  SHIP: [
    { id: 'arm-trestles', name: 'arm trestles', build: 'bench', wall: 'back', along: 0,
      caption: "The trestles support the force diagram and static-load model." },
    { id: 'drive-console', name: 'The drive console plots interval', build: 'board', wall: 'left', along: 0,
      caption: "The drive console plots interval, amplitude growth, and the reversal test." },
    { id: 'seat-frame', name: 'seat frame', build: 'bench', wall: 'right', along: 0,
      caption: "The seat frame shows the system boundary around ship and riders." },
    { id: 'timing-trace', name: 'timing trace', build: 'board', wall: 'back', along: -0.45,
      caption: "The timing trace places the free period beside the October drive interval." },
    { id: 'ship-console-board', name: 'ship console board', build: 'board', wall: 'left', along: -0.45,
      caption: "The console board carries support-load and pendulum-period calculations." },
    { id: 'ship-diagnostic-panel', name: 'The panel combines vertical', build: 'board', wall: 'right', along: -0.45,
      caption: "The panel combines vertical, lateral, offset, and October-event readings." },
    { id: 'ship-rule-console', name: 'ship rule console', build: 'board', wall: 'back', along: 0.45,
      caption: "The joint-rule console records the forbidden timing band and shared shutdown rules." },
  ],
  CAROUSEL: [
    { id: 'chain-rig', name: 'The chair-chain rig shows radius', build: 'rack', wall: 'back', along: 0,
      caption: "The chair-chain rig shows radius, angle, weight, and inward force." },
    { id: 'pole-jig', name: 'pole jig', build: 'rack', wall: 'left', along: 0,
      caption: "The pole jig fixes the chair radius used by the operating model." },
    { id: 'drive-panel', name: 'drive panel', build: 'board', wall: 'right', along: 0,
      caption: "The drive panel sets chair speed and prints the inclusive shutdown threshold." },
    { id: 'platform-jacks', name: 'platform jacks', build: 'vessel', wall: 'back', along: -0.45,
      caption: "The jacks level the platform and restore its original shim state for the control." },
    { id: 'controller-crate', name: 'controller crate', build: 'rack', wall: 'left', along: -0.45,
      caption: "The sealed replacement controller can connect only to the isolated simulator." },
    { id: 'controller-record', name: 'The record board shows serial', build: 'board', wall: 'right', along: -0.45,
      caption: "The record board shows serial, delivery, power, and installation evidence." },
    { id: 'joint-setting-board', name: 'joint setting board', build: 'board', wall: 'back', along: 0.45,
      caption: "The joint setting board overlays the angle locus, measured radius, and power limit." },
  ],
  BUMPER: [
    { id: 'car-on-stands', name: 'The raised car exposes mass', build: 'vessel', wall: 'back', along: 0,
      caption: "The raised car exposes mass, wheels, floor contact, and momentum data." },
    { id: 'dummy-rig', name: 'The padded dummy rig records stopping time', build: 'vessel', wall: 'left', along: 0,
      caption: "The padded dummy rig records stopping time, momentum change, and force." },
    { id: 'floor-console', name: 'floor console', build: 'board', wall: 'right', along: 0,
      caption: "The floor console locks the prediction before the dry stopping test." },
    { id: 'console-card', name: 'console card', build: 'rack', wall: 'back', along: -0.45,
      caption: "The October operator card slot shows when the record is present or missing." },
    { id: 'pavilion-board', name: 'pavilion board', build: 'board', wall: 'left', along: -0.45,
      caption: "The pavilion board carries the energy ledger and collision calculation." },
    { id: 'sensor-booking-board', name: 'sensor booking board', build: 'board', wall: 'right', along: -0.45,
      caption: "The booking board prices each proposed source of new evidence." },
    { id: 'collision-evidence-panel', name: 'The panel compares timing', build: 'board', wall: 'back', along: 0.45,
      caption: "The panel compares timing, amplitude, force, and the manual stop." },
  ],
  COASTER: [
    { id: 'profile-drawing', name: 'profile drawing', build: 'board', wall: 'back', along: 0,
      caption: "The old profile drawing carries the provisional loop geometry and frozen verdict." },
    { id: 'station-wheel', name: 'station wheel', build: 'vessel', wall: 'left', along: 0,
      caption: "The axle encoder stand compares independent and portable-wheel residuals." },
    { id: 'lift-panel', name: 'The lift panel shows train mass', build: 'board', wall: 'right', along: 0,
      caption: "The lift panel shows train mass, rise, time, efficiency, and motor demand." },
    { id: 'crown-tape', name: 'crown tape', build: 'rack', wall: 'back', along: -0.45,
      caption: "The crown tape reveals the physical loop radius only after prediction freeze." },
    { id: 'station-board', name: 'station board', build: 'board', wall: 'left', along: -0.45,
      caption: "The station board carries contact and required-margin derivations." },
  ],
  TOWER: [
    { id: 'fin-stack', name: 'fin stack', build: 'rack', wall: 'back', along: 0,
      caption: "The fin stack shows the brake hardware used by the tested configuration." },
    { id: 'drop-log', name: 'The drop log shows release height', build: 'board', wall: 'left', along: 0,
      caption: "The drop log shows release height, direction, and predicted entry speed." },
    { id: 'brake-desk', name: 'brake desk', build: 'bench', wall: 'right', along: 0,
      caption: "The brake desk carries the response sweep and rider-load transfer chain." },
    { id: 'witness-sheet', name: 'The witness sheet records uncertainty', build: 'board', wall: 'back', along: -0.45,
      caption: "The witness sheet records uncertainty, geometry checks, and procedure identity." },
    { id: 'tower-release-desk', name: 'tower release desk', build: 'bench', wall: 'left', along: -0.45,
      caption: "The release desk holds the claims Hart must verify before arming." },
  ],
  FLUME: [
    { id: 'header-gauge', name: 'header gauge', build: 'vessel', wall: 'back', along: 0,
      caption: "The probe panel reveals expected and observed values one station at a time." },
    { id: 'gate-ram', name: 'The gate ram shows its piston areas', build: 'vessel', wall: 'left', along: 0,
      caption: "The gate ram shows its piston areas, pressure transfer, and commanded opening." },
    { id: 'hull-scales', name: 'hull scales', build: 'bench', wall: 'right', along: 0,
      caption: "The hull scales compare log weight with displaced-water buoyancy." },
    { id: 'pump-curve', name: 'The pump curve marks flow', build: 'board', wall: 'back', along: -0.45,
      caption: "The pump curve marks flow, head, efficiency, and required input power." },
    { id: 'pumphouse-board', name: 'pumphouse board', build: 'board', wall: 'left', along: -0.45,
      caption: "The pump-power board carries continuity and power derivations." },
    { id: 'flume-case-stand', name: 'flume case stand', build: 'bench', wall: 'right', along: -0.45,
      caption: "The case stand compares flume evidence with the coaster certificate claim." },
  ],
  WORKSHOP: [
    { id: 'bench-notebooks', name: 'The notebook bench holds procedures', build: 'bench', wall: 'back', along: 0,
      caption: "The notebook bench holds procedures, calibration records, wind cases, and shared dependencies." },
    { id: 'workshop-diagnosis-board', name: 'The diagnosis board joins controller', build: 'board', wall: 'left', along: 0,
      caption: "The diagnosis board joins controller, brake, sensor, and shared-kit evidence." },
    { id: 'casebook-table', name: 'casebook table', build: 'bench', wall: 'right', along: 0,
      caption: "The Casebook table pairs Hart's card with only the claims it supports." },
    { id: 'configuration-desk', name: 'configuration desk', build: 'bench', wall: 'back', along: -0.45,
      caption: "The desk holds the exact bumper and tower configurations for attestation." },
    { id: 'uncertainty-board', name: 'uncertainty board', build: 'board', wall: 'left', along: -0.45,
      caption: "The uncertainty board stresses all seven ride decisions across supported ranges." },
    { id: 'work-allocation-board', name: 'The final allocation board shows useful work', build: 'board', wall: 'right', along: -0.45,
      caption: "The final allocation board shows useful work, protected reserve, and dead ends." },
  ],
  PLANT: [
    { id: 'motor-plate', name: 'motor plate', build: 'board', wall: 'back', along: 0,
      caption: "The shared plate shows the 55 kW limit and every competing load." },
  ],
  ARCADE: [
    { id: 'stall-cannon', name: 'stall cannon', build: 'vessel', wall: 'back', along: 0,
      caption: "The stall cannon turns water-exit speed into an independent projectile range." },
  ],
  REOPENIN: [
    { id: 'certificate-board', name: 'certificate board', build: 'board', wall: 'back', along: 0,
      caption: "Seven rows show which ride decisions have enough proof to sign." },
    { id: 'reopening-board', name: 'reopening board', build: 'board', wall: 'left', along: 0,
      caption: "The Reopening Board displays the full Casebook beside seven blank verdicts." },
  ],
  GATE: [
    { id: 'certificate-table', name: 'certificate table', build: 'bench', wall: 'back', along: 0,
      caption: "The certificate table holds the final seven claims and both signatures." },
  ],
};
