// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"rail", title:"The 8:14 to Ardenmoor", discipline:"Railway Safety Engineering",
  teaser:"A commuter train left the rails on a straight. A bomb on the line? A careless driver? Or maintenance quietly deferred?", overclaimTag:"sabotage on the line", truthTag:"concealed deferred maintenance",
  venue:"the Ardenmoor rail inquiry", agent:{name:"Investigator Wren Halcott", role:"Investigator's Notepad"},
  standingLabel:"Inquiry credibility", readingShort:"Pioneers", readingLabel:"Railway Pioneers",
  dossierName:"RAILWAY PIONEERS", enterLabel:"Open the inquiry", subt:"A deduction game inside the Ardenmoor rail inquiry", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the answer the front pages want: the evidence points not to a device on the line, but to something quieter, and far harder to bury.",
  CATS:{
    who:{ title:"Who is behind it", truth:"infra", items:[
      {id:"infra", label:"Doran Kell — infrastructure operator"},
      {id:"driver", label:"The train driver"},
      {id:"regulator", label:"The rail safety inspector"} ]},
    where:{ title:"Where it culminates", truth:"office", items:[
      {id:"track", label:"The Track & Points"},
      {id:"signalbox", label:"The Signal Centre"},
      {id:"office", label:"The Operator's Head Office"} ]},
    what:{ title:"What is happening", truth:"neglect", items:[
      {id:"sabotage", label:"Sabotage — something left on the line"},
      {id:"driver", label:"Simple driver error — a signal passed"},
      {id:"neglect", label:"Concealed deferred maintenance & a bypassed safeguard"} ]}
  },
  PLACES:{
    track:{name:"The Track & Points", xy:[140,90]},
    signalbox:{name:"The Signal Centre", xy:[330,240]},
    office:{name:"The Operator's Head Office", xy:[520,90]}
  },
  EDGES:[["track","signalbox"],["signalbox","office"]],
  CHARACTERS:{
    ganger:{ name:"Ganger Roe", role:"Permanent-way ganger", face:"🔧", badge:"R", legend:"the track", hint:"Walks the rails; flagged the cracked joint that was never renewed." },
    signaller:{ name:"The Signaller", role:"Signal-centre operator", face:"🚦", badge:"S", legend:"the box", hint:"Worked the panel; knows which safeguard was switched out to keep trains running." },
    clerk:{ name:"The Clerk", role:"Records clerk", face:"🗂", badge:"C", legend:"the office", hint:"Holds the maintenance backlog and the budget memo that froze it." }
  },
  TOPICMAP:{
    track:{ ganger:["railpioneer","gauge"], signaller:["locomotive","airbrake"], clerk:["railprofile","interlocking"] },
    signalbox:{ ganger:["steelrail","fatigue"], signaller:["axlefail","electrictraction"], clerk:["mucontrol","stresses"] },
    office:{ ganger:["vibration","mechanics"], signaller:["brittle","wheelrail"], clerk:["speed","safetyvalve"] }
  },
  TOPICS:{
    // cell: Ganger Roe @ The Track & Points
    railpioneer:{ sci:"George Stephenson (1781-1848)", topic:"The Rocket & the birth of railways", lede:"The illiterate colliery boy who taught himself engines and gave the world its iron roads, its Rocket, and the gauge nearly every railway still runs on.", no:1,
      profile:"George Stephenson rose from an illiterate colliery worker to 'the Father of Railways,' teaching himself to read at eighteen while tending pumping engines in the Northumberland coalfields. He built his reputation first on safety: in 1815 he devised a miner's safety lamp, the 'Geordie,' independently of Humphry Davy. But his lasting work was the railway. At Killingworth colliery he built a series of steam locomotives, and in 1825 he engineered the Stockton and Darlington Railway, the first public line to use steam traction.\n\nHis masterpiece was the Liverpool and Manchester Railway, opened in 1830, the first inter-city line worked wholly by locomotives. To choose them a competition was held at Rainhill in 1829, and the Rocket, built by George with his son Robert, won decisively: it combined a multi-tube boiler, a blast pipe, and directly driven cylinders into the template every steam locomotive would follow. Stephenson also fixed the gauge of 4 feet 8 and a half inches, which spread across the world as 'standard gauge.'\n\nStephenson understood a railway as a whole system: not just an engine, but a graded, drained, maintained 'permanent way' of rails, sleepers, and ballast that had to be built well and kept up. He fought for gentle gradients and solid foundations because he knew the road, not only the engine, carried the train.\n\nFor this inquiry, that is the point. Stephenson's railway was never a finished monument; it was a machine that wears, and a train leaving the rails on a straight speaks first to the state of that machine. Before anyone imagines a device left on the line, his legacy asks the plainer question: was the permanent way maintained as he insisted it must be?",
      frame:"Roe knocks ballast from his boot. \"Everyone starts with Stephenson, because he started all of it. Show me you know where railways came from, and I'll show you where this one went wrong.\"",
      q:[
        { q:"What made Stephenson's Rocket the winning design at Rainhill?", o:[
          { t:"A multi-tube boiler with a blast pipe, raising steam fast for sustained speed.", v:"expert", fb:"The fire-tube boiler and blast pipe let Rocket make steam continuously." },
          { t:"A single wide flue through the boiler, hoarding heat for the long steep banks.", v:"wrong", fb:"One big flue could not raise steam fast enough; many small tubes won." },
          { t:"Its tall driving wheels alone, geared so high that no rival could keep its pace.", v:"partial", fb:"Big wheels helped, but the boiler and draught were the real advance." },
          { t:"A gear train set between the pistons and the axle, dropped by every later engine.", v:"wrong", fb:"Rocket drove its wheels directly; the gearing idea belonged to older engines." } ] },
        { q:"What system did Stephenson insist a railway needed beyond the engine?", o:[
          { t:"A graded, drained permanent way of rails, sleepers and ballast, kept in repair.", v:"expert", fb:"Stephenson built the whole road, not just the engine, and kept it maintained." },
          { t:"A telegraph along every mile, without which no locomotive could be run safely.", v:"wrong", fb:"Telegraph came later; his insistence was on the permanent way itself." },
          { t:"Only heavier rails, since track upkeep was a matter engines made unnecessary.", v:"partial", fb:"Heavier rail helps, but the point was continuous upkeep of the road." },
          { t:"Nothing but a firm level bed, which once laid would never need touching again.", v:"danger", fb:"A railway bed wears under traffic and must be renewed, not laid and forgotten." } ] },
        { q:"Why does Stephenson's view of the railway matter to this inquiry?", o:[
          { t:"A railway is a machine that wears and needs upkeep, not a finished monument.", v:"expert", fb:"Treating the railway as a wearing machine points first at its maintenance." },
          { t:"It shows only an object left on the line could throw a train off good track.", v:"danger", fb:"Sound track does not need sabotage to fail; worn track fails on its own." },
          { t:"It proves a track built to gauge is safe for good and never wants renewing.", v:"wrong", fb:"Rails and joints wear and crack; gauge alone is no guarantee of safety." },
          { t:"It means the locomotive, not the road beneath it, decides every derailment.", v:"partial", fb:"The road beneath the train derails trains as surely as any engine fault." } ] }
      ] },
    // cell: Ganger Roe @ The Track & Points
    gauge:{ sci:"Isambard Kingdom Brunel (1806-1859)", topic:"Gauge, track & the Great Western", lede:"The cigar-smoking genius who laid a seven-foot 'billiard table' across England and lost the gauge war but proved that stability lives in the track.", no:2,
      profile:"Isambard Kingdom Brunel was the most flamboyant engineer of the railway age, and the Great Western Railway from London to Bristol was his canvas. Where George Stephenson had fixed a gauge of 4 feet 8 and a half inches, Brunel chose a broad gauge of 7 feet a quarter inch, arguing that a wider track gave a lower centre of gravity, steadier running, and room for larger, faster engines. To match it he built with extraordinary care: gentle gradients his rivals mocked as 'Brunel's billiard table,' the great Box Tunnel, the flat brick arches of the Maidenhead Bridge, and Paddington station.\n\nHis broad gauge did run beautifully, but it could not share track with the growing standard-gauge network. A Royal Commission examined the 'gauge war,' and the Gauge Act of 1846 settled the country on Stephenson's dimension; the last broad-gauge lines were converted in 1892, after Brunel's death. He poured the same daring into ships, the Great Western, the Great Britain, and the vast Great Eastern, and, with his father Marc, the Thames Tunnel.\n\nBrunel's obsession was track geometry: gauge, alignment, gradient, and a solid, well-drained bed, because he understood that how steadily a train runs depends on the precision of the road under it. A wheel stays on the rail only while gauge and alignment hold within fine tolerances.\n\nFor this inquiry, that is Brunel's gift. Track geometry is measurable; gauge, cant, twist, and alignment are recorded and can be checked against the point where the train left the rails. A derailment on a straight sends an investigator to the state of the track, not to a phantom on the line, because geometry that has drifted or a joint that has failed leaves a record a saboteur does not.",
      frame:"Roe crouches and sights along the rail with one eye. \"Brunel knew a train only stays on steel that's laid true. Tell me what gauge really is, and I'll tell you what mine measured that morning.\"",
      q:[
        { q:"What was Brunel's broad gauge meant to give the Great Western?", o:[
          { t:"Steadier, faster running from a lower centre of gravity on a wider track.", v:"expert", fb:"A wide gauge lowered the centre of gravity and steadied fast running." },
          { t:"A cheaper line, since a wider track needed far less earthwork and ballast.", v:"wrong", fb:"Broad gauge cost more, not less, in land and works; steadiness was the aim." },
          { t:"More seats per carriage, which he counted the whole reason to widen the track.", v:"partial", fb:"Wider coaches helped, but Brunel's argument was stability at speed." },
          { t:"Immunity from derailment, so that no broad-gauge train could ever leave the rails.", v:"danger", fb:"No gauge makes a train derailment-proof; track condition still governs." } ] },
        { q:"How was the 'gauge war' between broad and standard gauge settled?", o:[
          { t:"A Royal Commission and the 1846 Gauge Act fixed the standard dimension.", v:"expert", fb:"Parliament settled on Stephenson's gauge; the GWR converted its last in 1892." },
          { t:"Brunel's broad gauge won outright and spread across the whole country.", v:"wrong", fb:"Broad gauge lost; standard gauge became the national dimension." },
          { t:"The two gauges were simply blended into a new width halfway between them.", v:"partial", fb:"No compromise width was adopted; the standard gauge simply prevailed." },
          { t:"It was never resolved, and Britain still runs two incompatible gauges today.", v:"danger", fb:"The question was decided long ago; Britain runs one standard gauge." } ] },
        { q:"Why does track geometry help this inquiry resist a lurid answer?", o:[
          { t:"Gauge, cant and alignment are measured, so a bad straight leaves a record.", v:"expert", fb:"Measured geometry sends the board to the track's condition, not a saboteur." },
          { t:"Because only tampering could spread the rails and drop a wheel on a straight.", v:"danger", fb:"Gauge widens from wear and failed fastenings, no tampering required." },
          { t:"Because geometry cannot be measured, so any cause guessed is as good as another.", v:"wrong", fb:"Track geometry is precisely measured; that is what makes it evidence." },
          { t:"Because the engine alone sets whether a train holds the rails through a straight.", v:"partial", fb:"The road's geometry, not the engine, holds a wheel on a straight." } ] }
      ] },
    // cell: The Signaller @ The Track & Points
    locomotive:{ sci:"Robert Stephenson (1803-1859)", topic:"Locomotives & rail bridges", lede:"George's only son, who drew the Rocket's boiler, spanned the Menai Strait with iron tubes, and learned from a bridge that fell what repeated loads can do.", no:3,
      profile:"Robert Stephenson, the only son of George, was in his own right one of the greatest engineers of the nineteenth century. He ran the locomotive works at Newcastle that built the Rocket in 1829, much of its detailed design his own, and went on to engineer the London and Birmingham Railway, then the trunk lines that stitched Britain together. But it is his bridges that teach this inquiry the most.\n\nHe built the High Level Bridge at Newcastle and the Royal Border Bridge at Berwick, and, most daringly, the Britannia Bridge across the Menai Strait, where trains ran inside great wrought-iron tubes, a form he developed with the ironmaster William Fairbairn and the mathematician Eaton Hodgkinson after exhaustive model testing. It was pioneering structural engineering: they calculated and tested rather than guessed.\n\nThe hardest lesson came from failure. In 1847 his cast-iron girder bridge over the River Dee collapsed under a passing train, killing five. The inquiry that followed exposed the treachery of cast iron in bending and the way repeated traffic could work a flaw until it broke. It helped turn engineers away from brittle cast iron toward wrought iron and, later, steel, and toward the idea that structures must be understood under the loads they carry again and again.\n\nFor this inquiry, Robert Stephenson is the reminder that a structure under traffic can fail progressively and quietly. The Dee Bridge did not fall to a saboteur; it fell because a flawed member was loaded past what it could endure, over and over. A rail or a joint carrying train after train can do the same, a slow physical decline with a signature an investigator can read, entirely unlike an object left on the line.",
      frame:"The Signaller lays a diagram flat. \"Robert Stephenson built the strongest bridges of his age and watched one fall anyway. Show me you understand what traffic does to iron, and I'll tell you about the box.\"",
      q:[
        { q:"What did Robert Stephenson's Britannia Bridge pioneer?", o:[
          { t:"Wrought-iron tubes carrying trains inside them, proven first by model testing.", v:"expert", fb:"Trains ran inside tubular wrought-iron beams, tested on models beforehand." },
          { t:"A cast-iron arch, the strongest form then known for spanning wide water.", v:"wrong", fb:"It was tubular wrought iron, chosen over the cast iron he came to distrust." },
          { t:"Steel plate girders, the material that would define bridges for the century.", v:"partial", fb:"Steel came later; Britannia was wrought iron, tested and calculated." },
          { t:"A suspension deck so light that any heavy train would set it swaying wildly.", v:"danger", fb:"The tubes were rigid beams, not a swaying suspension span." } ] },
        { q:"What did the 1847 Dee Bridge collapse teach engineers?", o:[
          { t:"Cast iron is treacherous in bending and can fail under repeated traffic.", v:"expert", fb:"The collapse exposed cast iron's weakness and the toll of repeated loads." },
          { t:"That only sabotage could drop a bridge that had carried trains for years.", v:"danger", fb:"No saboteur was involved; a flawed cast-iron girder failed under load." },
          { t:"That wrought iron was unsafe, sending designers back to cast-iron beams.", v:"wrong", fb:"It pushed engineers toward wrought iron, away from brittle cast iron." },
          { t:"That trains had simply grown too heavy for any bridge to be built at all.", v:"partial", fb:"Bridges could be built for the traffic, but not from brittle cast iron." } ] },
        { q:"How does the Dee Bridge failure guide this inquiry?", o:[
          { t:"A structure under repeated traffic can fail slowly, with a readable signature.", v:"expert", fb:"Progressive failure under traffic leaves evidence a board can trace." },
          { t:"It shows a sound structure only fails when someone plants a charge on it.", v:"danger", fb:"Structures fail from overload and flaws, not only from sabotage." },
          { t:"It proves iron never fails gradually, so any break must be instant and total.", v:"wrong", fb:"Fatigue and cracking are gradual; that slow decline is the whole point." },
          { t:"It means only bridges, not rails, decline under the passing of trains.", v:"partial", fb:"Rails and joints wear under traffic exactly as loaded members do." } ] }
      ] },
    // cell: The Signaller @ The Track & Points
    airbrake:{ sci:"George Westinghouse (1846-1914)", topic:"The fail-safe air brake", lede:"The inventor who made a runaway train stop itself, turning the loss of pressure from a disaster into the very thing that sets the brakes.", no:4,
      profile:"George Westinghouse was an American inventor and industrialist who, at twenty-two, patented a railway air brake that would save countless lives. Early trains were braked by hand, with brakemen scrambling from car to car twisting wheels on the driver's whistle signal, hopelessly slow for a long, fast train. Westinghouse's first brake, patented in 1869, used compressed air piped from the locomotive to push brake shoes against the wheels of every car at once.\n\nBut his masterstroke came in 1872 with the automatic air brake. Instead of air being sent to apply the brakes, compressed air was held in a reservoir on each car and used to keep the brakes released; a continuous 'brake pipe' running the length of the train maintained the pressure. If that pressure dropped, whether the driver applied the brake, a hose burst, or the train broke in two, the brakes applied themselves, automatically and everywhere. This is the essence of a fail-safe: the system's default, when something goes wrong, is the safe state. Westinghouse went on to found Westinghouse Electric and to champion alternating-current power with Nikola Tesla.\n\nThe automatic air brake let trains grow longer, heavier, and faster while stopping reliably from a single handle, and versions of it brake trains to this day.\n\nFor this inquiry, Westinghouse embodies the principle at the heart of the case. Railways are built layer on layer with fail-safe devices, so that one fault, one leak, one human slip does not end in catastrophe. That is exactly why 'the driver simply passed a signal' is too small an answer on its own: the fail-safes exist so a single mistake is caught. Unless one of them was switched out, weakened, or bypassed to keep the trains running to time, in which case the slip that should have been survivable becomes fatal.",
      frame:"The Signaller taps the pressure gauge on the wall. \"Westinghouse built a brake that stops the train when everything fails, not when it works. Tell me how it does that, and I'll tell you what a fail-safe is worth once someone switches it off.\"",
      q:[
        { q:"How does Westinghouse's automatic air brake fail safe?", o:[
          { t:"Air pressure holds the brakes off, so any loss of pressure applies them.", v:"expert", fb:"Losing brake-pipe pressure, from any cause, sets the brakes automatically." },
          { t:"A charge in the brake line is the only thing that can stop the whole train.", v:"danger", fb:"No explosive is involved; a simple pressure drop applies every brake." },
          { t:"The driver must pump air to each car to set the brakes, one car at a time.", v:"wrong", fb:"Air holds the brakes off; it is released, not pumped, to stop the train." },
          { t:"A reservoir sets the brakes only when the driver signals down the brake pipe.", v:"partial", fb:"The brakes apply on any pressure loss, not only on a deliberate command." } ] },
        { q:"Why did the automatic air brake transform railway safety?", o:[
          { t:"One handle stopped a long, fast train reliably, even if it broke apart.", v:"expert", fb:"Continuous, automatic braking let trains grow longer, heavier and faster." },
          { t:"It let brakemen ride in warmth instead of turning wheels out in the open.", v:"wrong", fb:"It removed the brakemen's task entirely; comfort was not the point." },
          { t:"It slightly shortened stops, a modest gain over the old hand brakes.", v:"partial", fb:"The gain was enormous and, crucially, automatic on any parting of the train." },
          { t:"It made trains unstoppable, so speed no longer had any safe limit at all.", v:"danger", fb:"It made trains stop better, not run without limit; brakes have limits too." } ] },
        { q:"What does the fail-safe principle mean for reading this derailment?", o:[
          { t:"One slip should be survivable, unless a safeguard was bypassed to save time.", v:"expert", fb:"Fail-safes exist so one mistake is caught; a bypassed one lets it kill." },
          { t:"A fail-safe cannot fail, so only sabotage could ever defeat the system.", v:"danger", fb:"Fail-safes can be disabled or deferred; that is a failure, not sabotage." },
          { t:"Fail-safes make drivers irrelevant, so no human action matters any more.", v:"wrong", fb:"Fail-safes support the driver; they do not remove the human entirely." },
          { t:"It shows a single driver error is always enough to explain a crash outright.", v:"partial", fb:"The whole point is that one slip alone should not be fatal." } ] }
      ] },
    // cell: The Clerk @ The Track & Points
    railprofile:{ sci:"Charles Vignoles (1793-1875)", topic:"The flat-bottom rail", lede:"The surveyor whose T-shaped rail, spiked straight to the sleeper, became the shape under nearly every train that runs, and the shape that cracks at its joints.", no:5,
      profile:"Charles Blacker Vignoles was an Irish-born engineer and surveyor who gave his name to the flat-bottomed rail used on most of the world's railways. Early lines used various rail sections, many needing cast-iron 'chairs' to hold them upright. The flat-bottom, or Vignoles, rail has a wide foot that can be spiked or fastened directly to the sleeper, a broad web rising to a rounded head on which the wheel runs. Its cross-section, foot, web, and head, distributes the wheel's load down into the sleeper and ballast. An American engineer, Robert L. Stevens, devised a similar section around the same time; Vignoles popularised it in Britain and Europe.\n\nVignoles led a wandering, ambitious career: he surveyed railways across Britain, worked on the Liverpool and Manchester line, and late in life engineered the great Kyiv Chain Bridge across the Dnieper. But it is the rail profile that endures under every journey.\n\nThe shape matters because it governs where stress concentrates. A rail is a beam supported on sleepers; it bends slightly under each wheel and is worked hardest at the running surface and at its ends, where one length of rail meets the next. Traditionally those ends were bolted together with 'fishplates,' and the bolt holes and rail ends became notorious starting points for cracks.\n\nFor this inquiry, Vignoles's rail focuses attention on the joint. The junction between two rails, and the holes drilled through them, is a classic weak point where fatigue cracks begin and grow under traffic. A cracked joint left un-renewed does not announce itself with a bang; it spreads slowly through the steel until a wheel finds it. Knowing the rail's shape and its weak points tells an investigator where to look, and what a genuine, developing failure looks like.",
      frame:"The Clerk slides a cross-section drawing across the desk. \"Every rail on this railway is the same shape, and it fails in the same places. Tell me where a rail is weakest, and I'll find you the record of the one that was.\"",
      q:[
        { q:"What defines the flat-bottomed (Vignoles) rail?", o:[
          { t:"A wide foot fastened straight to the sleeper, a web, and a running head.", v:"expert", fb:"Foot, web and head: the foot spikes down directly, no chair needed." },
          { t:"A rounded bar held upright in a cast-iron chair bolted to each sleeper.", v:"wrong", fb:"That is the older chaired 'bullhead' style; Vignoles rail needs no chair." },
          { t:"A deep I-beam of equal top and bottom, run either way up when it wears.", v:"partial", fb:"Its head and foot differ; a flat-bottom rail is not symmetric top to bottom." },
          { t:"A hollow rail whose inner channel carries the signalling current along it.", v:"danger", fb:"The rail is solid steel; it is not a hollow conductor by design." } ] },
        { q:"Where on a jointed rail do cracks most often begin?", o:[
          { t:"At the rail ends and the fishplate bolt holes, where stress concentrates.", v:"expert", fb:"Joints and bolt holes are classic crack starters under repeated load." },
          { t:"Only where a saboteur has cut it, since sound rail never cracks on its own.", v:"danger", fb:"Rails crack from fatigue at stress raisers with no cutting involved." },
          { t:"At the very centre of each rail, the point furthest from any support.", v:"wrong", fb:"The ends and bolt holes, not the mid-span, are the usual origins." },
          { t:"Evenly along the whole rail, so no one spot is worth inspecting first.", v:"partial", fb:"Cracks cluster at joints and holes; inspection targets those first." } ] },
        { q:"How does knowing the rail's weak points help this inquiry?", o:[
          { t:"It tells the board where a real, slow-growing crack would start and hide.", v:"expert", fb:"The joint is where a developing failure hides; that is where to look." },
          { t:"It proves a clean break on a straight can only be the work of a device.", v:"danger", fb:"A fatigue crack at a joint is metallurgy, not a planted device." },
          { t:"It shows rails never crack, so a broken rail must have been placed there.", v:"wrong", fb:"Rails do crack, at known spots, if worn rail is left un-renewed." },
          { t:"It means only the locomotive's wheels, never the rail, cause a derailment.", v:"partial", fb:"A failing rail derails trains as readily as any fault in the wheels." } ] }
      ] },
    // cell: The Clerk @ The Track & Points
    interlocking:{ sci:"John Saxby (1821-1913)", topic:"Signal interlocking", lede:"The signal-fitter who locked points and signals together so that no signalman, however tired, could ever set two trains on a collision course.", no:6,
      profile:"John Saxby was an English railway signalling engineer who, in 1856, patented the interlocking of points and signals, one of the most important safety inventions in railway history. In the early years a signalman worked the levers for points and signals independently, and nothing physical stopped him from clearing a signal for a train while the points ahead were set the wrong way, or from admitting two trains to the same stretch of line. Human vigilance was the only safeguard, and it failed with fatal regularity.\n\nSaxby's interlocking used a mechanical frame of locking bars beneath the levers so that the levers could only be pulled in safe sequences. A signal could not be cleared unless the points on that route were correctly set and locked, and conflicting routes could not be set at once. The machine enforced the logic of safety, converting a rule that a man might forget into a constraint he could not physically break. Saxby founded the firm Saxby and Farmer, and interlocking spread across the world's railways; every modern signalling system, mechanical or computerised, still rests on the same principle.\n\nInterlocking is a designed safeguard against human error: it assumes the operator will one day make a mistake and arranges that the mistake cannot become a disaster.\n\nFor this inquiry, Saxby is central. Interlocking exists precisely so that one wrong lever, one lapse in the signal box, cannot line up a catastrophe on its own. So when a train comes to grief, the crucial question is not only whether someone erred, but whether the safeguards that should have caught the error were intact. An interlocking or a train-detection safeguard quietly switched out, bypassed to keep trains flowing to time, turns a routine slip into a disaster the machine was built to prevent.",
      frame:"The Clerk sets down a signalling ledger. \"Saxby made it so a tired man's mistake couldn't kill anyone. That only holds while the locking's all there. Show me you understand it, and I'll show you what was taken out.\"",
      q:[
        { q:"What did Saxby's interlocking physically prevent?", o:[
          { t:"Clearing a signal unless the points on that route were set and locked.", v:"expert", fb:"Signals and points were locked together so only safe routes could be set." },
          { t:"Any train from moving until the signalman telegraphed the next box ahead.", v:"wrong", fb:"Interlocking governs points and signals, not telegraph block working." },
          { t:"Levers from being pulled too fast, by slowing the signalman's own hands.", v:"partial", fb:"It enforced safe combinations, not merely the speed of working levers." },
          { t:"Every accident, making the human signalman entirely unnecessary thereafter.", v:"danger", fb:"It caught many errors but never made the signalman redundant." } ] },
        { q:"What was interlocking's underlying safety philosophy?", o:[
          { t:"Assume the operator will err, and make the dangerous move impossible.", v:"expert", fb:"It builds in the certainty of human error and blocks the fatal outcome." },
          { t:"Trust the operator fully, since a trained signalman never makes mistakes.", v:"danger", fb:"The whole point was that vigilance fails; the machine backs it up." },
          { t:"Replace judgement with speed, letting more trains share one length of line.", v:"wrong", fb:"Interlocking constrains unsafe moves; it does not chase raw throughput." },
          { t:"Punish errors after the fact, once a signalman has already made them.", v:"partial", fb:"It prevents the error in the moment, rather than punishing it later." } ] },
        { q:"Why is interlocking so important to how we read this crash?", o:[
          { t:"A safeguard bypassed to save time turns a survivable slip into a disaster.", v:"expert", fb:"The key question is whether the safeguards were intact or switched out." },
          { t:"Interlocking cannot be defeated, so only sabotage could cause a crash.", v:"danger", fb:"Interlocks can be disabled or bypassed; that is a failure, not sabotage." },
          { t:"It proves the signalman alone is to blame whenever a train comes to grief.", v:"wrong", fb:"A working interlock shifts blame away from a lone signalman, not onto him." },
          { t:"It means human error can be ruled out entirely in any modern accident.", v:"partial", fb:"Error is not ruled out; it is caught only while the safeguard is in place." } ] }
      ] },
    // cell: Ganger Roe @ The Signal Centre
    steelrail:{ sci:"Henry Bessemer (1813-1898)", topic:"Steel & the durable rail", lede:"The metal-maker whose roaring converter turned iron into cheap steel by the ton, and gave the railways a rail that lasted, but never a rail that lasts forever.", no:7,
      profile:"Henry Bessemer was an English inventor and engineer whose converter, announced in 1856, made steel a cheap, mass-produced material for the first time. His process blew air up through a vessel of molten pig iron; the oxygen burned out the excess carbon and impurities in a spectacular shower of sparks, and in minutes turned brittle iron into tough, workable steel. Before Bessemer, steel was costly and made in small batches; after him it could be poured by the ton.\n\nFor the railways this was transformative. Early rails were wrought iron, and under the pounding of traffic they wore, laminated, and had to be replaced often, sometimes within a few years on busy lines. Bessemer steel rails were far harder and tougher; they carried heavier axle loads and lasted many times longer, making the dense, fast railway network of the later nineteenth century possible. Bessemer grew wealthy and was knighted, though he battled patent disputes and quality problems as ironmasters learned to control his volatile process.\n\nSteel made the durable rail. It did not make an immortal one.\n\nFor this inquiry, that distinction is the trap and the truth. A steel rail is tough and long-lived, which tempts an operator to treat it as permanent and to defer its renewal. But steel still wears at the running surface, still accumulates rolling-contact fatigue, and still cracks once it is worked beyond its life. A rail kept in service past the point where it should have been renewed is not sabotaged and is not simply unlucky; it has reached the end of a knowable service life that someone chose to ignore. Knowing what steel can and cannot endure separates a rail failed by neglect from a fantasy of tampering.",
      frame:"Roe turns a scarred lump of rail steel in his hand. \"Bessemer's steel outlasts anything the old ironmasters rolled. That's exactly why folk forget it wears out at all. Tell me what steel can take, and I'll tell you what this rail had already taken.\"",
      q:[
        { q:"What did Bessemer's converter do to molten iron?", o:[
          { t:"Blew air through it to burn out carbon, making cheap steel in minutes.", v:"expert", fb:"Air blown through the melt oxidised the carbon, mass-producing steel." },
          { t:"Slowly baked it in a furnace for days to draw the impurities to the top.", v:"wrong", fb:"It was fast, minutes not days, and driven by an air blast, not slow baking." },
          { t:"Added carbon to soft iron to harden it, a small step done batch by batch.", v:"partial", fb:"The process removed carbon and impurities; it did not add carbon in." },
          { t:"Purified it so completely that the resulting rail could never wear or crack.", v:"danger", fb:"Bessemer steel is durable, not eternal; rails still wear and fatigue." } ] },
        { q:"Why did steel rails replace wrought-iron ones?", o:[
          { t:"They were far harder and tougher, carrying heavier loads far longer.", v:"expert", fb:"Steel's hardness let rails last many times longer under heavy traffic." },
          { t:"They were lighter, so trains needed much less power to haul the same load.", v:"wrong", fb:"Steel rails are heavier, not lighter; durability was their advantage." },
          { t:"They were merely cheaper to buy, though they wore out just as fast.", v:"partial", fb:"They lasted far longer, not merely cost less; the gain was in wear life." },
          { t:"They never wore at all, so a steel line could be laid and left for good.", v:"danger", fb:"Steel rails wear and fatigue; they still need inspection and renewal." } ] },
        { q:"What does steel's durability tempt an operator to forget?", o:[
          { t:"That a rail has a service life which, once past, ends in cracks.", v:"expert", fb:"Durability invites deferral, but steel still reaches the end of its life." },
          { t:"That only a saboteur, never fair wear, could ever break a steel rail.", v:"danger", fb:"Worn steel breaks on its own; no tampering is needed to crack it." },
          { t:"That steel rails must be replaced every year like the old iron ones.", v:"wrong", fb:"Steel rails last for years, not months; the risk is over-deferring them." },
          { t:"That rails wear only at the joints and nowhere along their length.", v:"partial", fb:"Rails fatigue at the surface and joints alike; the whole rail ages." } ] }
      ] },
    // cell: Ganger Roe @ The Signal Centre
    fatigue:{ sci:"August Wohler (1819-1914)", topic:"Metal fatigue & the railway axle", lede:"The railway engineer who broke thousands of axles on purpose and discovered the quiet law by which metal, stressed again and again, finally gives way.", no:8,
      profile:"August Wohler was a German railway engineer whose systematic experiments in the 1850s and 1860s founded the study of metal fatigue. Railway axles were failing in service, sometimes catastrophically, even though the loads they carried were well below the strength the metal showed in a single pull. Wohler, working for the Prussian state railways, set out to understand why by testing: he built machines to load axles and specimens through millions of repeated cycles and recorded exactly how many cycles they survived at each level of stress.\n\nHis results revealed a law hidden in the metal. A component stressed repeatedly can fail at a load it would easily bear once; the higher the stress, the fewer cycles it survives. Wohler plotted stress against the number of cycles to failure, giving the 'S-N curve' (the Wohler curve) still used today, and he identified that below a certain stress, for some steels, a part might endure essentially forever, the 'fatigue limit.' He showed that fatigue cracks start small, often at a surface flaw or stress concentration, and grow a little with each cycle until the remaining metal can no longer hold.\n\nFor this inquiry, Wohler is decisive. Fatigue is the signature failure of anything that carries traffic, and it is slow, cumulative, and legible. A fatigue crack advances cycle by cycle and leaves tell-tale beach marks on the fracture face that record its patient growth. That is nothing like the sudden, chaotic damage of an explosive charge, and nothing like a one-off blunder. When a rail or an axle fails by fatigue, the metal itself testifies that the failure was building for a long time, in plain view of anyone who inspected it, and that renewing the cracked part in time would have prevented it.",
      frame:"Roe holds a broken axle stub to the light and points at the rings on its face. \"Wohler could read a break like this the way you'd read tree rings. It didn't happen that morning. Show me you understand fatigue, and I'll tell you how long this was coming.\"",
      q:[
        { q:"What did Wohler's axle experiments establish about metal?", o:[
          { t:"It can fail under repeated loads well below its single-pull strength.", v:"expert", fb:"Repeated stress below the static strength is exactly what fatigue exploits." },
          { t:"It grows stronger the more times it is loaded, until it never fails.", v:"wrong", fb:"Cyclic loading weakens metal toward failure; it does not strengthen it." },
          { t:"It fails only when a single load exceeds its rated strength outright.", v:"partial", fb:"That is single-overload failure; fatigue needs many repeated cycles." },
          { t:"It fails at random, so no test can ever predict when a part will break.", v:"danger", fb:"Wohler made fatigue predictable, plotting cycles against stress." } ] },
        { q:"What does the Wohler (S-N) curve show?", o:[
          { t:"Higher stress means fewer cycles survived before the part fatigues.", v:"expert", fb:"The S-N curve trades stress against cycles to failure for a material." },
          { t:"That any sudden break must come from a blast, since metal never tires.", v:"danger", fb:"Fatigue breaks metal with no blast; the curve quantifies exactly that." },
          { t:"That a part's life depends only on its age in years, not on its use.", v:"wrong", fb:"Fatigue tracks load cycles under traffic, not calendar age alone." },
          { t:"That every steel lasts forever below any load, with no limit at all.", v:"partial", fb:"Only some steels show a true fatigue limit; many keep degrading." } ] },
        { q:"How does fatigue help this inquiry reject a sensational cause?", o:[
          { t:"A fatigue crack grows slowly and leaves beach marks recording its age.", v:"expert", fb:"Beach marks date a fatigue failure as long-building, not sudden sabotage." },
          { t:"It shows a clean rail break can only be a device planted on the line.", v:"danger", fb:"Fatigue leaves a slow signature; a blast leaves a violent, different one." },
          { t:"It proves metal breaks instantly and cleanly, with no prior warning at all.", v:"wrong", fb:"Fatigue is gradual and marked; its slow growth is visible on the break." },
          { t:"It means only axles, never rails, can fail by this slow cracking process.", v:"partial", fb:"Rails fatigue exactly as axles do, at their surfaces and joints." } ] }
      ] },
    // cell: The Signaller @ The Signal Centre
    axlefail:{ sci:"William J. M. Rankine (1820-1872)", topic:"Fatigue & the failure of axles", lede:"The Scottish polymath who, decades before anyone listened, showed that railway axles snap not from 'crystallizing' iron but from cracks creeping in from the surface.", no:9,
      profile:"William John Macquorn Rankine was a Scottish civil engineer and physicist, one of the founders of modern thermodynamics and a prolific writer of engineering textbooks. Among his many contributions, one speaks directly to this inquiry: in 1843, as a young engineer, he published a study of the fractures of railway axles. Axles were breaking in service and killing people, and the popular explanation was that the constant vibration of running had somehow 'crystallized' the wrought iron, turning it brittle over time.\n\nRankine examined broken axles and rejected that theory. He saw that the fractures began at the surface, usually at a shoulder or a sharp change of section near the wheel seat, and grew gradually inward, a process we now recognise as fatigue-crack growth from a stress concentration. He argued for rounding those abrupt changes of section to relieve the stress, advice that anticipated fatigue engineering by decades. His broader career was vast: the Rankine cycle underlies steam-engine thermodynamics, he worked on soil mechanics and earth pressures, and his manuals trained generations of engineers.\n\nThe 'crystallization' myth mattered because it framed axle failure as a mysterious, unavoidable decay. Rankine replaced the myth with a mechanism: a crack, starting at a knowable place, driven by repeated stress, that could be designed against and inspected for.\n\nFor this inquiry, Rankine guards against both traps at once. Against the sensational, he shows that a broken axle or rail has an ordinary, traceable cause you can find in the metal, not a saboteur's hand. Against the dismissive, he shows it is not blameless bad luck or a mystery of vibration either; it is a crack that started at a predictable spot and grew in plain sight, which attention and renewal would have caught. The failure has an address, and someone was responsible for watching it.",
      frame:"The Signaller pushes a yellowed report toward you. \"For years men blamed 'crystallized' iron and shrugged. Rankine wouldn't. Show me you know why an axle really breaks, and I'll tell you which alarms went quiet.\"",
      q:[
        { q:"What did Rankine reject about railway axle failures?", o:[
          { t:"The idea that vibration 'crystallized' iron and made it brittle over time.", v:"expert", fb:"He replaced the crystallization myth with cracks growing from the surface." },
          { t:"The idea that axles fail from a single overload on their first heavy run.", v:"wrong", fb:"He identified gradual cracking, not a first-run overload, as the cause." },
          { t:"The idea that surface flaws matter, insisting the core fails first instead.", v:"partial", fb:"Rankine stressed the surface origin, not a hidden failure of the core." },
          { t:"The idea that axles fail at all, holding that sound iron never breaks.", v:"danger", fb:"Axles plainly did fail; Rankine explained how, he did not deny it." } ] },
        { q:"Where did Rankine find axle cracks actually started?", o:[
          { t:"At the surface, at shoulders and sharp changes of section near the wheel.", v:"expert", fb:"Stress concentrated at abrupt shoulders, and cracks grew inward from there." },
          { t:"Only at points a saboteur had filed, since clean shafts never crack.", v:"danger", fb:"Cracks began at stress raisers from ordinary running, not from filing." },
          { t:"Deep in the very centre of the axle, far from any surface feature at all.", v:"wrong", fb:"The origin was the surface shoulder, not the axle's deep interior." },
          { t:"Uniformly all over the axle, so no one region was worth rounding off.", v:"partial", fb:"The shoulders were the hot spots; rounding them relieved the stress." } ] },
        { q:"How does Rankine's finding cut against both easy answers?", o:[
          { t:"The break has a traceable cause, neither a device nor blameless bad luck.", v:"expert", fb:"A crack with a known origin can be inspected for; someone owned that watch." },
          { t:"It shows a snapped axle is proof that someone tampered with the train.", v:"danger", fb:"The cause is metallurgical and ordinary, not the mark of a saboteur." },
          { t:"It proves such failures are pure chance that no inspection could foresee.", v:"wrong", fb:"The crack grows visibly from a known spot; inspection can catch it." },
          { t:"It means only the driver's handling could ever crack a running axle.", v:"partial", fb:"Handling matters little; the crack is set by cyclic stress and geometry." } ] }
      ] },
    // cell: The Signaller @ The Signal Centre
    electrictraction:{ sci:"Werner von Siemens (1816-1892)", topic:"Electric traction", lede:"The German industrialist who ran the world's first electric train around a Berlin exhibition, and turned the two rails into wires that both carry the train and can betray a break in it.", no:10,
      profile:"Werner von Siemens was a German industrialist and inventor, founder of the firm that still bears his name, and a pioneer of electrical engineering. In 1866 he described the dynamo-electric principle, showing that a generator could excite its own magnetism and so produce large currents efficiently, a foundation of practical electric power. He then applied that power to transport. At the 1879 Berlin Trade Exhibition he demonstrated the first electric railway, a small locomotive drawing current from a live rail and hauling passengers around a track, and in 1881 he opened the first electric tramway at Lichterfelde near Berlin.\n\nElectric traction promised clean, powerful, controllable movement without the smoke and bulk of a steam locomotive, and it reshaped urban and suburban railways. Siemens built an industrial empire around telegraphy, cables, dynamos, and electrical machinery, and his work seeded much of the modern electrified railway.\n\nElectric railways also changed the role of the rails themselves. Beyond carrying the wheels, the running rails came to carry electrical current, for traction return and, crucially in signalling, for the track circuits that detect whether a section of line is occupied or a rail is broken.\n\nFor this inquiry, Siemens points to the double duty of the rail. A sound, continuous rail conducts; a broken rail interrupts the circuit and can raise the alarm. Modern signalling can, in principle, detect a fractured rail electrically and hold the trains, provided the detection is working and has not been switched out. So the question is not whether the technology to catch a broken rail existed, but whether it was in service that morning, or bypassed to keep the timetable moving. The safeguard that should have spoken may have been silenced.",
      frame:"The Signaller runs a finger along a wiring schematic. \"Siemens made the rails carry current, not just carriages. A broken rail can trip a circuit and stop everything, when the circuit's live. Show me you understand traction, and I'll tell you what wasn't live.\"",
      q:[
        { q:"What did Werner von Siemens demonstrate in 1879?", o:[
          { t:"The first electric railway, a locomotive drawing current from a live rail.", v:"expert", fb:"His Berlin exhibition locomotive took current from a conductor rail." },
          { t:"The first steam tramway, running a small boilered engine through the streets.", v:"wrong", fb:"It was electric, not steam; that was the whole novelty of the demonstration." },
          { t:"A battery-powered cart, carrying its own cells rather than drawing power.", v:"partial", fb:"It drew power from a live rail, not from onboard batteries." },
          { t:"A wireless train, powered through the air with no rail or wire at all.", v:"danger", fb:"Power came through a rail conductor; there was no wireless transmission." } ] },
        { q:"Beyond carrying wheels, what job did the rails take on?", o:[
          { t:"Carrying current, for traction return and for track-circuit detection.", v:"expert", fb:"Running rails conduct return current and form signalling track circuits." },
          { t:"Storing an explosive charge, hidden inside the hollow of the rail head.", v:"danger", fb:"The rail is solid, a conductor and a beam, not a container for a device." },
          { t:"Nothing electrical, since signals always ran on separate buried cables.", v:"wrong", fb:"The rails themselves carry the track-circuit current in modern signalling." },
          { t:"Only lighting the stations, a minor use unrelated to running trains.", v:"partial", fb:"Their electrical role is central to detection, not a sideline for lighting." } ] },
        { q:"Why does the rail's electrical role matter to this inquiry?", o:[
          { t:"A broken rail can trip a circuit and stop trains, if detection is live.", v:"expert", fb:"The real question is whether that safeguard was in service or switched out." },
          { t:"It proves a rail can only break when a device shorts the circuit out.", v:"danger", fb:"Rails break from fatigue; the circuit detects the break, it doesn't cause it." },
          { t:"It shows a broken rail can never be detected, so no alarm was possible.", v:"wrong", fb:"Track circuits can detect a broken rail; the issue is whether one worked." },
          { t:"It means signalling faults, not track faults, cause every derailment.", v:"partial", fb:"A broken rail is a track fault the signalling is meant to catch." } ] }
      ] },
    // cell: The Clerk @ The Signal Centre
    mucontrol:{ sci:"Frank J. Sprague (1857-1934)", topic:"Electric railways & multiple-unit control", lede:"The 'Father of Electric Traction,' who wired a whole city's streetcars, then let one driver command a train of powered cars, and built the tight-timetabled railway we still ride.", no:11,
      profile:"Frank Julian Sprague was an American electrical engineer, a former US Navy officer who briefly worked for Thomas Edison before setting out on his own. In 1888 he equipped the Richmond Union Passenger Railway in Virginia, the first large-scale, commercially successful electric streetcar system, solving the practical problems of motors, overhead wires, and current collection that had defeated others. It made electric street railways viable across the world almost overnight.\n\nHis second great invention, in 1897, was multiple-unit (MU) control. Instead of one locomotive hauling dead carriages, Sprague put traction motors under many cars and let a single driver in the leading cab control them all through electrical control lines running the length of the train. This is the basis of the electric multiple unit and of every subway and metro train: rapid acceleration, distributed power, and the ability to run frequent, punctual services. Sprague also developed electric elevators, which made the skyscraper practical.\n\nMultiple-unit control let railways run intense, closely spaced timetables, exactly the kind of busy commuter service where trains must keep to the minute.\n\nFor this inquiry, Sprague names the pressure, not the villain. His technology delivers frequency and punctuality; a railway built on it lives and dies by keeping trains moving to time. That is a virtue until punctuality becomes the master value, and the slower, invisible work of maintaining the track falls behind the timetable. A modern commuter railway that runs beautifully to schedule can be quietly deferring the renewals that keep it safe. The failure, when it comes, is not in Sprague's elegant control system but in the plain rail beneath it, sacrificed to the clock his invention made king.",
      frame:"The Clerk gestures at the running-time board on the wall. \"Sprague gave us trains every few minutes, and a timetable nobody dares miss. Show me you understand how that railway runs, and I'll show you what the running keeps burying.\"",
      q:[
        { q:"What did Sprague's multiple-unit control allow?", o:[
          { t:"One driver to control powered motors spread along many cars of a train.", v:"expert", fb:"MU control drives motors under many cars from a single leading cab." },
          { t:"One locomotive to haul far more dead carriages than before behind it.", v:"wrong", fb:"The point was distributed power, not a stronger single locomotive." },
          { t:"Two drivers to share a cab, easing the workload on long fast runs.", v:"partial", fb:"It needed no second driver; one cab commanded the whole train." },
          { t:"A train to run with no driver aboard, controlled wholly from a tower.", v:"danger", fb:"A human driver still commanded the train from the leading cab." } ] },
        { q:"What kind of service did MU control make possible?", o:[
          { t:"Frequent, punctual trains with rapid acceleration, as on a metro line.", v:"expert", fb:"Distributed power gives the quick, close-headway service metros rely on." },
          { t:"Trains so automatic that timetables and maintenance no longer mattered.", v:"danger", fb:"Frequency raises the stakes on maintenance; it does not retire it." },
          { t:"Slow, infrequent trains that needed far fewer staff to run each day.", v:"wrong", fb:"It enabled frequent, fast service, the opposite of infrequent running." },
          { t:"Long-distance expresses only, of little use for busy commuter lines.", v:"partial", fb:"It suits dense commuter and metro work above all, not just expresses." } ] },
        { q:"What pressure does a punctual, frequent railway create?", o:[
          { t:"To keep trains moving to time, even as track upkeep falls behind.", v:"expert", fb:"When the clock rules, the slow work of renewal is what quietly slips." },
          { t:"To search every train for sabotage before it is allowed to depart.", v:"danger", fb:"The pressure is the timetable, not a hunt for imagined saboteurs." },
          { t:"To slow every service down, since speed alone endangers a busy line.", v:"wrong", fb:"The pressure is to keep to time, which can crowd out safe maintenance." },
          { t:"To hire more drivers, the single fix a crowded timetable ever needs.", v:"partial", fb:"More crew won't fix deferred track; the hazard is under the trains." } ] }
      ] },
    // cell: The Clerk @ The Signal Centre
    stresses:{ sci:"Karl Culmann (1821-1881)", topic:"Graphic statics & stress", lede:"The Swiss professor who taught engineers to draw the invisible forces inside a structure, and saw the lines of stress in a loaded beam echoed in the grain of a bone.", no:12,
      profile:"Karl Culmann was a German-born engineer who became a professor at the new Federal Polytechnic in Zurich, the ETH, and founded the discipline of graphic statics. His 1866 book, 'Die graphische Statik,' showed how to calculate the forces in trusses, arches, and beams not by long algebra but by drawing them: forces became lines whose lengths and directions could be laid out with ruler and compass, so an engineer could see where a structure was pushed, pulled, and stressed. It was a powerful tool in an age before computers, and it trained a generation to reason about load paths visually.\n\nCulmann studied railways closely, touring British and American lines and bridges, and his methods were used to design the iron structures the railways demanded. He is also remembered for a famous moment of insight: shown the sectioned head of a human femur, he recognised that the fine internal struts of the bone followed the same curves as the principal-stress trajectories he drew for a loaded crane, a striking hint that nature places material along the lines of force.\n\nThat idea, that stress runs in traceable paths and concentrates at particular places, is Culmann's gift to this inquiry.\n\nIn a rail, stress is not uniform. It crowds at the running surface under the wheel, at changes of section, and above all at the bolt holes and squared ends of a jointed rail. Those are exactly the spots where cracks nucleate and grow. Culmann's discipline lets an investigator predict where a rail is working hardest and therefore where a fatigue failure would begin, long before it breaks. A crack that starts at a fishbolt hole is not a mystery or a saboteur's choice; it is the structure failing exactly where the lines of force said it would.",
      frame:"The Clerk unrolls a stress diagram, all fans of fine lines. \"Culmann could draw where a beam hurts most. So can I, on a rail. Show me you can see where the force gathers, and I'll show you where this one gave.\"",
      q:[
        { q:"What did Culmann's graphic statics let engineers do?", o:[
          { t:"Find the forces in a structure by drawing them, not by long algebra.", v:"expert", fb:"Graphic statics solved load paths with ruler-and-compass diagrams." },
          { t:"Measure real bridges in service with gauges bonded to the ironwork.", v:"wrong", fb:"It was a drawing-board method of analysis, not field strain measurement." },
          { t:"Guess a structure's strength by eye, without any construction at all.", v:"partial", fb:"It was rigorous drawn calculation, not eyeballing; it gave real numbers." },
          { t:"Prove any well-drawn structure could never fail under load at all.", v:"danger", fb:"It reveals where forces concentrate; it cannot make a structure fail-proof." } ] },
        { q:"What did Culmann notice about stress in a loaded structure?", o:[
          { t:"It runs in traceable paths and crowds at certain concentrated spots.", v:"expert", fb:"Stress trajectories concentrate at section changes, holes, and surfaces." },
          { t:"It spreads so evenly that no single point is ever more loaded than another.", v:"danger", fb:"Stress concentrates sharply; that unevenness is where failures start." },
          { t:"It vanishes entirely once a structure is finished and standing still.", v:"wrong", fb:"A standing structure still carries stress; loads never make it vanish." },
          { t:"It matters only in bridges, never in a plain length of running rail.", v:"partial", fb:"Rails carry concentrated stress too, at their joints and running surface." } ] },
        { q:"How does Culmann's thinking guide this inquiry?", o:[
          { t:"It predicts where a rail works hardest, and so where a crack begins.", v:"expert", fb:"A crack at a fishbolt hole is the structure failing exactly as predicted." },
          { t:"It shows a crack at a bolt hole must have been cut there deliberately.", v:"danger", fb:"The bolt hole is a natural stress raiser; the crack is fatigue, not filing." },
          { t:"It proves stress is unknowable, so a break site tells the board nothing.", v:"wrong", fb:"Stress paths are calculable; the crack site is evidence, not noise." },
          { t:"It means only whole bridges, not rails, can be analysed for stress.", v:"partial", fb:"The same analysis applies to a rail as to any loaded beam." } ] }
      ] },
    // cell: Ganger Roe @ The Operator's Head Office
    vibration:{ sci:"Stephen Timoshenko (1878-1972)", topic:"Strength of materials & vibration", lede:"The engineer who wrote the textbooks the world learned from, and treated the rail as a beam floating on ballast, trembling a little under every wheel that passed.", no:13,
      profile:"Stephen Timoshenko was a Russian-born engineer, often called the father of modern engineering mechanics, whose textbooks on strength of materials, theory of elasticity, and vibration taught much of the twentieth-century engineering world. After leaving revolutionary Russia he settled in the United States, teaching at Michigan and Stanford and writing works still consulted today. He refined beam theory, and the 'Timoshenko beam' that bears his name accounts for shear deformation and rotary inertia that the older, simpler theory ignored, matters that grow important when a beam vibrates or is loaded quickly.\n\nCrucially for the railways, Timoshenko analysed the stresses in the track itself. He modelled the rail as a beam resting on an elastic foundation, the springy support of sleepers and ballast, and calculated how it bends and how the stresses distribute as a wheel rolls over it. He extended this to the dynamic case: a wheel is not a static weight but a moving, sometimes hammering load, and imperfections like a rail joint, a worn low spot, or a flat on a wheel throw sudden impacts into the rail that amplify the stress well above the static value.\n\nThat dynamic amplification is Timoshenko's warning to this inquiry.\n\nA rail joint that has loosened or dipped, a corrugated or worn railhead, makes every passing wheel strike harder, and each blow works any existing crack a little further. The vibration is measurable and its effect calculable: a defect that raises impact loads accelerates its own destruction. So a rail that failed was not struck once by something on the line; it was hammered thousands of times by ordinary traffic across a defect that maintenance should have smoothed or renewed. The rail's trembling under each wheel is the slow arithmetic of neglect, not the signature of a bomb.",
      frame:"Roe presses his palm flat on the desk to still an imagined shudder. \"Timoshenko showed the rail rides on ballast like a plank on springs, and a bad joint makes every wheel hit it harder. Show me you understand that, and I'll tell you how that joint had been drumming for months.\"",
      q:[
        { q:"How did Timoshenko model the rail under a wheel?", o:[
          { t:"As a beam on an elastic foundation of springy sleepers and ballast.", v:"expert", fb:"The rail bends on the elastic support of ballast as a wheel rolls over it." },
          { t:"As a rigid bar clamped solidly at both ends and unable to deflect at all.", v:"wrong", fb:"The rail is supported continuously and does deflect, not clamped rigid." },
          { t:"As a free weight resting on the bare ground, with no support beneath it.", v:"partial", fb:"It rests on an elastic foundation of sleepers, not on bare ground." },
          { t:"As an unbreakable member that no passing wheel could ever overstress.", v:"danger", fb:"The rail is stressed by every wheel and can indeed be overworked." } ] },
        { q:"Why does a bad rail joint raise the stress on the rail?", o:[
          { t:"A dip or gap makes each wheel strike harder, amplifying the load.", v:"expert", fb:"Impacts at a defect push dynamic stress well above the static value." },
          { t:"It doesn't; only a charge on the line can ever raise a rail's stress.", v:"danger", fb:"Ordinary wheels at a bad joint raise the stress; no device is needed." },
          { t:"It lowers the stress, since a loose joint lets the rail flex it away.", v:"wrong", fb:"A loose or dipped joint concentrates impact, it does not relieve it." },
          { t:"It matters only at high speed, and never on a slow commuter run.", v:"partial", fb:"Even at modest speed a defect hammers the rail every time a wheel passes." } ] },
        { q:"What does dynamic amplification tell this inquiry?", o:[
          { t:"A defect hammered by ordinary traffic drives its own slow failure.", v:"expert", fb:"Thousands of ordinary impacts across a defect, not one strike, break the rail." },
          { t:"A rail can fail only from a single violent blow struck from outside.", v:"danger", fb:"The rail was hammered many times by traffic, not struck once by a device." },
          { t:"Vibration is harmless, so a rail's condition cannot matter to a break.", v:"wrong", fb:"Dynamic loads are real and measurable; a defect worsens them each pass." },
          { t:"Only wheels, never the rail's own defects, decide when a rail fails.", v:"partial", fb:"The rail's worn joint is what turns each wheel into a hammer blow." } ] }
      ] },
    // cell: Ganger Roe @ The Operator's Head Office
    mechanics:{ sci:"Jean-Victor Poncelet (1788-1867)", topic:"Work, energy & applied mechanics", lede:"The soldier-mathematician who survived a march into Russia, invented a new geometry in a prison cell, and gave engineers the very idea of mechanical 'work.'", no:14,
      profile:"Jean-Victor Poncelet was a French army engineer and mathematician whose life bridged the battlefield and the lecture hall. As a young officer he took part in Napoleon's disastrous 1812 invasion of Russia, was left for dead at the Battle of Krasnoi, and spent nearly two years as a prisoner of war. In captivity, with no books, he reconstructed mathematics from memory and developed projective geometry, which he published after his return, founding a whole branch of the subject.\n\nBut Poncelet was equally an engineer of machines. He improved the water wheel; his 'Poncelet wheel' used curved blades to capture more of a stream's energy, and he helped establish the science of applied mechanics for industry. He was among those who put the concept of mechanical 'work,' force acting through a distance, at the centre of engineering, giving practical meaning to work, energy, and the power of machines. His analyses helped engineers reason quantitatively about how much a machine could do and what forces it must withstand.\n\nEnergy is Poncelet's lens on this inquiry.\n\nA moving train carries kinetic energy that grows with the square of its speed; a commuter train at line speed holds an enormous store of it. That energy has to go somewhere, dissipated gently by the brakes in a normal stop, or released violently in a derailment. Poncelet's mechanics let an investigator account for that energy and read its release. The devastation of a derailment is the ordinary kinetic energy of a heavy, fast train suddenly unleashed as it ploughs off the rails, and it has a mechanical signature quite different from the sharp, chemical blast of an explosive. Knowing the difference keeps the board from mistaking the fury of a high-speed derailment for the mark of a bomb.",
      frame:"Roe spreads his hands wide, then claps them. \"Poncelet reckoned the energy in a moving thing. A train at line speed carries a terrible lot of it. Show me you know where that energy goes in a wreck, and I'll tell you it wasn't any bomb.\"",
      q:[
        { q:"What concept did Poncelet help place at the heart of mechanics?", o:[
          { t:"Mechanical work, a force acting through a distance, and its energy.", v:"expert", fb:"Poncelet advanced work and energy as practical engineering quantities." },
          { t:"Electric charge, the flow of current through a conducting machine.", v:"wrong", fb:"His domain was mechanical work and machines, not electrical charge." },
          { t:"Raw speed alone, treated apart from any force or distance moved.", v:"partial", fb:"Work joins force and distance; speed alone is not the concept." },
          { t:"Perpetual motion, a machine yielding more energy than it is given.", v:"danger", fb:"Poncelet's mechanics obey energy conservation, not perpetual motion." } ] },
        { q:"How does a moving train's kinetic energy behave with speed?", o:[
          { t:"It grows with the square of speed, so a fast train holds a great store.", v:"expert", fb:"Energy scales with speed squared; doubling speed quadruples it." },
          { t:"It stays fixed, so a crash releases no more energy at speed than at rest.", v:"danger", fb:"A faster train carries far more energy to release in a wreck." },
          { t:"It falls as the train speeds up, since motion carries the load along.", v:"wrong", fb:"Kinetic energy rises, not falls, as a train goes faster." },
          { t:"It rises straight in step with speed, doubling as the speed doubles.", v:"partial", fb:"It rises with the square of speed, faster than a simple doubling." } ] },
        { q:"How does energy help tell a derailment from a bomb?", o:[
          { t:"A wreck's fury is released kinetic energy, unlike a sharp chemical blast.", v:"expert", fb:"A high-speed derailment unleashes ordinary kinetic energy, not a blast." },
          { t:"It shows only an explosive could ever cause such violent destruction.", v:"danger", fb:"The devastation is the train's own energy, not a bomb's; signatures differ." },
          { t:"It proves derailments release no energy, so damage implies an attack.", v:"wrong", fb:"A derailing train releases its huge kinetic energy as it leaves the rails." },
          { t:"It means only very slow trains derail, so speed rules a wreck out.", v:"partial", fb:"Fast trains derail with great energy; speed makes wrecks worse, not rarer." } ] }
      ] },
    // cell: The Signaller @ The Operator's Head Office
    brittle:{ sci:"Constance Tipper (1894-1995)", topic:"Brittle fracture & cold rails", lede:"The Cambridge metallurgist who explained why whole ships cracked in half in cold seas, and gave the world the test for the temperature at which tough steel turns treacherous.", no:15,
      profile:"Constance Tipper was a British metallurgist and crystallographer at Cambridge, one of the few women in engineering science of her era, whose work explained one of the great material mysteries of the Second World War. Welded 'Liberty ships,' mass-produced to carry cargo across the Atlantic, were suffering sudden, catastrophic fractures; some split entirely in two, often in cold northern waters and sometimes while lying still in harbour. The failures were baffling, and sabotage was among the suspicions.\n\nTipper showed that the cause lay in the steel itself. Ordinary structural steel undergoes a 'ductile-to-brittle transition' as it cools: above a certain temperature it is tough and bends before it breaks, but below that transition temperature it can fracture suddenly and brittlely, a crack racing across it with little warning and little energy. The cold seas had pushed the ships' steel below its transition, and welded hulls, being continuous, let a crack run unchecked once started. She developed a means, the 'Tipper test,' of measuring a steel's transition temperature, so that steels could be chosen to stay tough in service.\n\nBrittle fracture, cold, and a pre-existing flaw are the elements her work joins together, and they belong at the centre of this inquiry.\n\nA rail already carrying a fatigue crack is far more dangerous on a cold night, when the steel is below its transition and a crack that might have held can suddenly run through the rail. That is not sabotage; it is metallurgy, foreseeable and preventable by renewing cracked rail before winter finds it. But it is not blameless bad luck either. Tipper's lesson cuts both ways: a rail that snaps in the cold was neither a bomb nor an act of God, but a known flaw meeting a known condition, which vigilance should have removed.",
      frame:"The Signaller glances at the frost still on the window. \"Tipper worked out why good steel shatters in the cold. That morning was a cold one. Show me you understand brittle fracture, and I'll tell you what the rail had waiting in it.\"",
      q:[
        { q:"What is the ductile-to-brittle transition Tipper studied?", o:[
          { t:"Below a certain temperature, tough steel can fracture suddenly and brittlely.", v:"expert", fb:"Below its transition temperature, ductile steel turns brittle and snaps." },
          { t:"Above a certain temperature, steel melts and flows before it can crack.", v:"wrong", fb:"The transition is brittleness, not melting; it is far below any melting." },
          { t:"Steel slowly rusts thinner in the cold until it can no longer bear a load.", v:"partial", fb:"That is corrosion; the transition is a sudden change in fracture behaviour." },
          { t:"Cold steel grows tougher, so a rail is safest on the coldest of nights.", v:"danger", fb:"Cold makes steel more brittle, not tougher; that is the danger." } ] },
        { q:"Why did the welded Liberty ships fracture so catastrophically?", o:[
          { t:"Cold pushed the steel brittle, and welded hulls let a crack run unchecked.", v:"expert", fb:"Below-transition steel plus continuous welds let cracks race the hull." },
          { t:"Enemy saboteurs had planted charges, splitting the hulls from within.", v:"danger", fb:"The cause was brittle fracture in cold steel, found by science, not sabotage." },
          { t:"Their engines overheated the hull steel until it softened and tore apart.", v:"wrong", fb:"The steel was too cold and brittle, not overheated and soft." },
          { t:"They were simply overloaded with cargo far beyond any safe limit.", v:"partial", fb:"Some failed at rest or lightly loaded; brittleness, not overload, was key." } ] },
        { q:"How does brittle fracture cut against both easy answers here?", o:[
          { t:"A cold-night break is a known flaw meeting cold, not a bomb or bad luck.", v:"expert", fb:"Foreseeable and preventable: renew cracked rail before winter finds it." },
          { t:"It shows a rail can shatter only when an explosive shocks the cold steel.", v:"danger", fb:"Brittle fracture needs no explosive; a fatigue crack and cold suffice." },
          { t:"It proves cold rails are perfectly safe, so weather can be set aside.", v:"wrong", fb:"Cold makes a cracked rail more dangerous, not safe; weather matters." },
          { t:"It means only ships, never rails, are at risk from brittle fracture.", v:"partial", fb:"Rails suffer brittle fracture too; the Liberty ships are the warning." } ] }
      ] },
    // cell: The Signaller @ The Operator's Head Office
    wheelrail:{ sci:"Heinrich Hertz (1857-1894)", topic:"Contact stress: wheel on rail", lede:"The physicist who proved radio waves exist, and in his twenties also worked out the enormous stress crammed into the coin-sized patch where a steel wheel meets a steel rail.", no:16,
      profile:"Heinrich Hertz is most famous for proving the existence of electromagnetic waves, confirming Maxwell's theory and laying the ground for radio; the unit of frequency bears his name. But as a young man in 1882 he also solved a very different problem that matters intimately to railways: what happens where two curved elastic bodies press together. His theory of contact mechanics, 'Hertzian contact,' calculates the tiny area over which they actually touch and the intense stresses concentrated there.\n\nA railway wheel and a rail are both hard steel, and they meet over an astonishingly small patch, roughly the size of a small coin. The full weight carried by that wheel is funnelled through that patch, so the contact stresses are enormous, among the highest routinely borne by any engineering component. Hertz's mathematics gives the size of the contact patch and the stresses just beneath the surface, where they peak.\n\nThose repeated, concentrated stresses are why the railhead fatigues, and that is Hertz's contribution to this inquiry.\n\nRolling millions of wheels over that little patch drives 'rolling contact fatigue': fine cracks at the surface and gauge corner, head checks, and 'squats,' which if left unmanaged grow downward and can turn into a transverse crack that breaks the rail. It is a slow, well-understood degradation with a clear visual and metallurgical signature, and it is controlled by grinding the railhead and, in the end, renewing the rail. A railhead cracked by contact fatigue and left un-renewed did not come to grief through sabotage; it wore out under ordinary wheels exactly as Hertz's stresses predict, on a schedule maintenance was meant to keep.",
      frame:"The Signaller balances a coin on the desk and taps it. \"Hertz showed the whole weight of the wheel goes through a patch no bigger than that. Show me you understand contact stress, and I'll tell you what the railhead looked like before it let go.\"",
      q:[
        { q:"What did Hertz's contact theory calculate?", o:[
          { t:"The small area two curved bodies touch and the stresses concentrated there.", v:"expert", fb:"Hertzian contact gives the patch size and the intense stress beneath it." },
          { t:"The friction that heats a wheel's brake shoes as a train slows to a stop.", v:"wrong", fb:"That is braking friction; Hertz treated elastic contact between bodies." },
          { t:"The overall weight a bridge could carry spread across all of its supports.", v:"wrong", fb:"His theory is about the contact patch, not a whole structure's load." },
          { t:"The exact wavelength of the radio waves he is otherwise best known for.", v:"partial", fb:"That is his other, separate work; contact mechanics is the relevant one." } ] },
        { q:"Why are wheel-rail contact stresses so high?", o:[
          { t:"The wheel's full load passes through a patch only a coin's size across.", v:"expert", fb:"A tiny contact patch concentrates the whole wheel load into huge stress." },
          { t:"The rails are electrified, so current adds to the mechanical stress there.", v:"wrong", fb:"The stress is purely mechanical; traction current does not add to it." },
          { t:"The steel is soft, so the wheel sinks deep into the rail as it rolls.", v:"danger", fb:"Rail steel is hard; the stress is high because the contact patch is tiny." },
          { t:"The wheel spins fast, and speed alone is what raises the contact stress.", v:"partial", fb:"Contact stress comes from load over a small area, not chiefly from speed." } ] },
        { q:"How does rolling contact fatigue bear on this inquiry?", o:[
          { t:"A cracked, un-renewed railhead wore out under wheels, as Hertz predicts.", v:"expert", fb:"Contact fatigue is a slow, signed degradation, not the mark of sabotage." },
          { t:"It shows a surface crack proves someone scored the rail deliberately.", v:"danger", fb:"Head checks and squats come from ordinary rolling, not from scoring." },
          { t:"It proves the railhead can never crack, so a break must be an attack.", v:"wrong", fb:"Railheads crack from contact fatigue routinely if left unground." },
          { t:"It means only wheels, not the rail, ever wear on a busy railway.", v:"partial", fb:"Both wear; the railhead fatigues under the same contact stress." } ] }
      ] },
    // cell: The Clerk @ The Operator's Head Office
    speed:{ sci:"Sir Nigel Gresley (1876-1941)", topic:"Speed, streamlining & the locomotive", lede:"The locomotive engineer who clothed his engines in blue streamlining and sent Mallard down a bank at 126 miles an hour, still the fastest steam has ever run.", no:17,
      profile:"Sir Nigel Gresley was the chief mechanical engineer of Britain's London and North Eastern Railway, and the finest steam-locomotive designer of his generation. He built the great Pacific locomotives that hauled expresses up the East Coast Main Line, among them the celebrated Flying Scotsman, and in 1938 his streamlined A4 Pacific 'Mallard' reached 126 miles per hour on a descent near Grantham, a world speed record for steam that has never been broken.\n\nGresley's engineering was about extracting speed reliably. He refined boiler and cylinder design and adopted his conjugated valve gear to drive three cylinders efficiently. He understood streamlining, wind-tunnel-testing shapes to cut air resistance at speed, and he understood that running fast demanded everything else be right: powerful, controllable braking, and, above all, a track maintained to a standard that matched the pace. Mallard's record run, in fact, pushed the machine to its limits, a middle big-end bearing overheated near the peak, a reminder that at the edge of performance the margins are thin.\n\nThat relationship between speed and the state of the track is Gresley's lesson for this inquiry.\n\nThe faster a train runs, the less forgiving a track defect becomes: a dipped joint or a cracked rail that a slow train might survive can derail a fast one, and the energy of the wreck is far greater. Running to fast, tight timetables therefore raises the stakes on maintenance, precisely when the pressure to keep to time can tempt an operator to defer it. A derailment on a straight at line speed is not, on its own, evidence of a saboteur or a single careless driver; it can be the predictable meeting of high speed with a track allowed to fall behind the standard that speed requires. Gresley ran fast because the whole railway was kept fit to. When it is not, speed finds the flaw.",
      frame:"The Clerk taps a timetable column. \"Gresley ran the fastest steam in the world, but only because the whole railway was kept fit for it. Show me you understand speed, and I'll show you what this railway demanded of a track it wasn't keeping up.\"",
      q:[
        { q:"What was Gresley's Mallard famous for?", o:[
          { t:"Reaching 126 mph on a descent, the world steam speed record.", v:"expert", fb:"Mallard's 126 mph in 1938 remains the record for steam traction." },
          { t:"Hauling the heaviest coal trains ever run over a British main line.", v:"wrong", fb:"Mallard was a fast express engine, not a heavy freight hauler." },
          { t:"Being the first locomotive ever fitted with a streamlined shape.", v:"partial", fb:"Others were streamlined before; Mallard's fame is its record speed." },
          { t:"Running so fast that no track defect could ever affect it at all.", v:"danger", fb:"High speed makes defects more dangerous, not less; margins shrink." } ] },
        { q:"What did running fast demand of the rest of the railway?", o:[
          { t:"Strong braking and a track maintained to the standard the speed needed.", v:"expert", fb:"Speed requires everything else, brakes and track, to be kept up to it." },
          { t:"Nothing extra, since a fast enough engine floats clear of the rails.", v:"danger", fb:"A train never leaves the rails by design; it depends utterly on the track." },
          { t:"Only a bigger boiler, with track and brakes left exactly as before.", v:"wrong", fb:"Power alone is not enough; brakes and track must match the speed." },
          { t:"Merely a smoother shape, the sole thing that ever limits a train's speed.", v:"partial", fb:"Streamlining helps, but track and braking limit safe speed far more." } ] },
        { q:"How does speed relate to deferred track maintenance here?", o:[
          { t:"The faster the train, the less a track defect can be survived.", v:"expert", fb:"High speed meeting a neglected track is a predictable, provable cause." },
          { t:"Fast trains prove any derailment must be the work of a saboteur.", v:"danger", fb:"Speed finds a real flaw; it does not imply a planted device." },
          { t:"Speed and track upkeep are unrelated, so pace tells the board nothing.", v:"wrong", fb:"Speed sets how forgiving the track must be; the two are tightly linked." },
          { t:"Only the driver's speed choice, never the track, decides a derailment.", v:"partial", fb:"A defect at line speed derails a train whatever the driver intends." } ] }
      ] },
    // cell: The Clerk @ The Operator's Head Office
    safetyvalve:{ sci:"Timothy Hackworth (1786-1850)", topic:"Early locomotives & the safety valve", lede:"The devout, dogged engineer who made the early locomotive reliable, and whose spring-loaded safety valve is the ancestor of every device that vents danger so no one has to remember to.", no:18,
      profile:"Timothy Hackworth was an English engineer, a blacksmith's son and a deeply religious man, who did as much as anyone to turn the early steam locomotive from a fragile novelty into a dependable machine. He worked alongside George Stephenson and became the locomotive superintendent of the Stockton and Darlington Railway, keeping its temperamental engines running. He built 'Sans Pareil' to compete at the Rainhill Trials of 1829, and his 'Royal George' and later designs improved the power and reliability of locomotives at a critical moment.\n\nAmong the problems Hackworth wrestled with was the deadliest: the boiler. Early boilers, holding steam at pressure, could explode with lethal force if that pressure ran away. The safeguard was the safety valve, a valve held shut by a spring or weight that lifts automatically to vent steam once pressure exceeds a safe limit, needing no human to watch or act. Hackworth improved the reliability of the spring-loaded safety valve on his locomotives, part of a broader effort to make the machine safe to work.\n\nThe safety valve is the purest fail-safe, and it is Hackworth's warning to this inquiry.\n\nIt protects automatically, without vigilance, so long as it is left alone. But the whole grim history of boiler explosions is also a history of the valve defeated: drivers and firemen tying it down, weighting it, or screwing it shut to raise pressure for more power and speed, and blowing themselves up. The lesson generalises to every railway safeguard. Disasters recur not when the safety devices are absent but when someone bypasses them to keep performance up, to make the time, to hit the target. A safeguard deliberately overridden turns a routine limit into a catastrophe, and that is a decision, made by someone, not an accident and not an attack.",
      frame:"The Clerk sets a small brass valve on the ledger like an exhibit. \"Hackworth's valve keeps you safe without anyone minding it, until somebody ties it down to make the numbers. Show me you understand a fail-safe, and I'll show you the order that tied one down.\"",
      q:[
        { q:"What does a boiler safety valve do?", o:[
          { t:"Lifts on its own to vent steam once pressure passes a safe limit.", v:"expert", fb:"A spring holds it shut until unsafe pressure lifts it automatically." },
          { t:"Seals the boiler tighter as pressure climbs, to hold the steam in.", v:"wrong", fb:"It opens to release pressure; it does not seal the boiler tighter." },
          { t:"Warns the driver with a whistle so he can release the pressure himself.", v:"partial", fb:"It acts automatically, not merely warning; no human need respond." },
          { t:"Raises the pressure on demand to give the engine extra power and speed.", v:"danger", fb:"Its job is to limit pressure safely, not to boost it for performance." } ] },
        { q:"Why is the safety valve considered a true fail-safe?", o:[
          { t:"It protects automatically, needing no one to watch or act.", v:"expert", fb:"The valve vents danger by itself, without vigilance, if left alone." },
          { t:"It cannot be defeated, so a boiler with one can never explode at all.", v:"danger", fb:"Valves were often tied down and boilers still burst; it can be defeated." },
          { t:"It works only while the driver holds it open by hand throughout.", v:"wrong", fb:"It acts by itself; no one need hold it open for it to work." },
          { t:"It merely records the pressure for the crew to check later on.", v:"partial", fb:"It acts on the pressure directly; it does not just log a reading." } ] },
        { q:"What is the safety valve's warning for this whole inquiry?", o:[
          { t:"Disasters recur when someone bypasses a safeguard to hit a target.", v:"expert", fb:"An overridden safeguard is a decision by someone, not accident or attack." },
          { t:"A safeguard once fitted removes all risk, so any crash means sabotage.", v:"danger", fb:"Fitting a safeguard does not remove risk if it is later bypassed." },
          { t:"Safeguards are pointless, since crews ignore them in every single case.", v:"wrong", fb:"Safeguards work well until deliberately defeated; they are not pointless." },
          { t:"Only boilers, never track or signals, can have a safeguard defeated.", v:"partial", fb:"Any safeguard can be bypassed, on the track and in the box alike." } ] }
      ] }
  },
  STORIES:{
    ganger:{
      track:"Roe walks the four-foot with you, boots crunching ballast, and stops dead at a joint. \"I flagged this one months back. Cracked, I wrote. Renew it, I wrote. Look what got done about it.\"",
      signalbox:"Roe stands stiff among the panels, cap in his hands. \"I don't belong in here with the lights and levers. But I'll tell you this: the steel my rails are made of doesn't lie, whatever the timetable says.\"",
      office:"Roe eyes the carpet like it might bite. \"They keep us out in the cold and the paperwork in here in the warm. Somewhere in these cabinets is the note I wrote about that joint.\""
    },
    signaller:{
      track:"The Signaller has come trackside, uneasy in the open air. \"Up in the box I see it all as lights on a diagram. Out here it's real steel, and real steel that no light was watching.\"",
      signalbox:"The Signaller stands at the panel and lowers their voice. \"There's a function on this frame that used to hold the trains for a fault like this. Ask me what became of it, once you've earned it.\"",
      office:"The Signaller keeps their coat on in the office. \"They set the rules I work to from in here. When a safeguard gets switched out to keep trains moving, this is the room that signs for it.\""
    },
    clerk:{
      track:"The Clerk has been sent trackside and hates it, ledger clutched to their chest. \"I know this rail by its record, not its rust. And its record, I promise you, is not a clean one.\"",
      signalbox:"The Clerk hovers by the log books in the box. \"Every fault raised, every job put off, it all comes back to my files in the end. The signallers report it; someone decides to file it away.\"",
      office:"The Clerk is finally on home ground, surrounded by cabinets. \"The backlog lives here. So does the memo that froze it. Show me you understand this railway, and I'll show you which drawer.\""
    }
  },
  story:[
    "The <b>8:14 to Ardenmoor</b> was a full commuter train on an ordinary weekday morning when it left the rails on a dead-straight stretch of line and tore into the embankment. No curve, no collision, no obvious reason, only the wreckage and the questions. You are <b>Investigator Wren Halcott</b>, and the Ardenmoor rail inquiry has handed you the case the whole country is waiting on.",
    "<b>Three people will help you</b>, each holding a piece and none the whole. <b>Ganger Roe</b>, the permanent-way man who walks these rails and swears he flagged trouble here long ago. <b>The Signaller</b>, who works the panel at the Signal Centre and knows what the lights were and were not doing. And <b>the Clerk</b>, keeper of the records, who can tell you which jobs were ordered, which were done, and which were quietly set aside. Earn their trust and they will talk.",
    "<b>Someone here is behind it.</b> Three names sit in your notepad: <b>Doran Kell</b>, the infrastructure operator who runs the track and the budgets; the <b>train driver</b>, who was at the controls; and the <b>rail safety inspector</b>, whose job was to catch exactly this. Every column of the case, <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> truly happened, hides a tempting wrong answer. The headlines want <b>sabotage, something left on the line</b>. The quick verdict wants <b>simple driver error, a signal passed at danger and nothing more</b>. The truth is narrower than the first and graver than the second, and quieter than either.",
    "You have <b>8 days</b> and a single accusation to make. Name it well and a paper trail becomes proof; name it wrong and a real, provable failure vanishes behind a headline or a scapegoat, free to happen again."
  ],
  endings:{ overclaimWhat:"sabotage", dismissalWhat:"driver",
    win:{
      expertTitle:"What the Records Prove, and No More",
      expert:["Halcott names it exactly: Doran Kell, the infrastructure operator, who ran the track and the budgets and let the backlog freeze; the truth culminating in the Operator's Head Office, where the deferred-maintenance list and the budget memo live; and concealed deferred maintenance, a cracked rail left un-renewed, with the safeguard that should have caught it quietly bypassed to keep the trains to time. Not a saboteur. Not a careless driver alone.",
        "Every card accounted for. Halcott walked the track, the Signal Centre, and the Head Office, turned a wary ganger, signaller, and clerk into witnesses, and claimed precisely what the records and the memo could defend. The inquiry issues findings that renew the rail, restore the safeguard, and unfreeze the backlog, which is the entire point of doing it right."],
      soundTitle:"Right, but Lightly Proven",
      sound:["Halcott names the right three, Doran Kell, the Head Office, and a concealed deferred-maintenance failure with a safeguard bypassed to keep time. The shape of the case is correct, and the refusal to cry sabotage or pin it all on the driver is exactly right.",
        "But too many threads were left loose, and the operator's lawyers will pull at them. A few more days tracing the cracked joint and the frozen backlog would have made the finding unassailable. Close and honest, if not yet airtight."],
      namedTitle:"The Right Answer, Unearned",
      named:["Halcott names the truth, Doran Kell, the Head Office, the deferred maintenance and the bypassed safeguard, but gathered too little to back it. It reads like a hunch that happened to land.",
        "The inquiry cannot rest its findings on an accusation this thin, however correct. Being right is not the same as being able to prove it to the people who will fight the finding."]
    },
    overclaim:{ title:"The Inquiry That Cried Sabotage",
      body:["Halcott reports sabotage, something left on the line, the answer the front pages were already running. It is vivid, and it is not what the evidence shows.",
        "The rail bore a fatigue crack with a long, slow signature, its beach marks recording months of growth, and the detection that should have caught it had been switched out to keep the trains moving. There was no device and no intruder. When the sensational charge collapses, it takes the inquiry's credibility with it, and the real, provable failure in the Operator's Head Office is dismissed as just another conspiracy theory."] },
    dismissal:{ title:"Case Closed on the Driver",
      body:["Halcott files it as simple driver error, a signal passed at danger, nothing systemic, close the file. It is half a truth and misses the graver half.",
        "The whole point of a railway's fail-safes is that one slip should not be fatal, and here one had been quietly bypassed to keep to time, over a rail the operator had left cracked and un-renewed. Blaming the driver leaves that neglected track and that frozen backlog exactly as they were, waiting for the next train. The inquiry saw the last hand on the controls and never the decision, taken in an office, to let the line decay."] },
    wrongNames:{ title:"So Close",
      body:["Halcott has the nature of it cold, concealed deferred maintenance and a safeguard bypassed to keep the timetable, neither sabotage nor a lone driver's blunder. But the finger lands on the wrong name or the wrong room, and the real culprit and the office where it was decided go unnamed."] } },
}};