// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"marine", title:"The Kestrel's Roll", discipline:"Marine & Naval Architecture",
  teaser:"A packed ferry rolled over in calm water minutes from port. An attack? A freak wave? Or a number in the loading book?", overclaimTag:"a torpedo or attack", truthTag:"a concealed loss of stability",
  venue:"the Kestrel ferry inquiry", agent:{name:"Investigator Mara Ostend", role:"Investigator's Notepad"},
  standingLabel:"Board credibility", readingShort:"Pioneers", readingLabel:"Naval-Architecture Pioneers",
  dossierName:"NAVAL-ARCHITECTURE PIONEERS", enterLabel:"Open the inquiry", subt:"A deduction game inside the Kestrel ferry inquiry", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the answer the front pages crave: the evidence points not to a torpedo but to something quieter — and far harder to bury.",
  CATS:{
    who:{ title:"Who is behind it", truth:"operator", items:[
      {id:"operator", label:"Harmon Vell — ferry line owner"},
      {id:"captain", label:"Captain Iris Sund — ship's master"},
      {id:"surveyor", label:"The maritime surveyor"} ]},
    where:{ title:"Where it culminates", truth:"office", items:[
      {id:"cardeck", label:"The Vehicle Deck & Bow Door"},
      {id:"bridge", label:"The Bridge & Ballast Controls"},
      {id:"office", label:"The Ferry Line's Office"} ]},
    what:{ title:"What is happening", truth:"stability", items:[
      {id:"attack", label:"A torpedo, mine, or deliberate attack"},
      {id:"rogue", label:"A freak rogue wave — an act of God"},
      {id:"stability", label:"A concealed loss of stability from overloading"} ]}
  },
  PLACES:{
    cardeck:{name:"The Vehicle Deck & Bow Door", xy:[140,90]},
    bridge:{name:"The Bridge & Ballast Controls", xy:[330,240]},
    office:{name:"The Ferry Line's Office", xy:[520,90]}
  },
  EDGES:[["cardeck","bridge"],["bridge","office"]],
  CHARACTERS:{
    bosun:{ name:"Bosun Adisa", role:"Deck bosun & loading hand", face:"⚓", badge:"B", legend:"the car deck", hint:"Waved the cars aboard; knows they were never tallied or lashed." },
    purser:{ name:"The Purser", role:"Ship's purser & records", face:"🗂", badge:"P", legend:"the office", hint:"Holds the manifests and the head-count the sailing was booked past." },
    pilot:{ name:"Harbor Pilot Enns", role:"Harbor pilot", face:"🧭", badge:"H", legend:"the quay", hint:"Boards every ship; saw the Kestrel riding low, her marks underwater." }
  },
  TOPICMAP:{
    cardeck:{ bosun:["buoyancy","metacentre"], purser:["floatstab","loadline"], pilot:["hullform","modeltest"] },
    bridge:{ bosun:["modelbasin","shiptheory"], purser:["waves","wake"], pilot:["viscousdrag","freesurface"] },
    office:{ bosun:["scaling","currents"], purser:["charts","forecast"], pilot:["gyro","hydrostatics"] }
  },
  TOPICS:{
    // cell: Bosun Adisa @ The Vehicle Deck & Bow Door
    buoyancy:{ sci:"Archimedes (c.287-212 BC)", topic:"Buoyancy & displacement", lede:"The Syracusan who leapt from his bath shouting 'Eureka' because he had just grasped exactly how much sea a hull shoves aside.", no:1,
      profile:"Archimedes of Syracuse was the greatest mathematician and engineer of antiquity, and in his treatise 'On Floating Bodies' he set down the law that still governs every ship afloat. His principle is simple to state and impossible to escape: a body immersed in a fluid is pushed up by a force equal to the weight of the fluid it displaces. A hull sinks into the water until the weight of the water it shoves aside exactly equals the weight of the ship. That balance, and nothing else, holds thousands of tons of steel on the surface.\n\nThe famous story has him puzzling over whether a king's crown was pure gold or secretly cut with silver. Stepping into a full bath and watching it overflow, he saw that a submerged object displaces its own volume of water, giving him a way to compare densities without melting the crown down. He is said to have run through the streets crying 'Eureka' — 'I have found it.' Whatever the truth of the tale, the displacement result is exact, and Archimedes proved it with rigor centuries before calculus existed.\n\nFor a ferry, displacement is a running account. Every car, every truck, every passenger adds weight, and the hull answers by settling deeper until it displaces that much more water. The gap left between the waterline and the deck edge — the freeboard — is the reserve of buoyancy that keeps a wave from stepping aboard. Load past a point and that reserve is spent. For this inquiry, Archimedes is the first witness: a ship does not float or founder by luck or by an enemy's hand. It floats by an equation, and if the Kestrel sat too low, the reason was written in her load, not in the weather and not in a torpedo.",
      frame:"Adisa jerks a thumb at the waterline scar on the hull. \"Every ton I waved aboard pushed her down by a fixed amount — that's not opinion, that's law. Tell me what holds a hull up, and I'll tell you how much we piled on.\"",
      q:[
        { q:"What does Archimedes' principle state?", o:[
          { t:"The upward force on a hull equals the weight of the water it pushes aside.", v:"expert", fb:"Buoyancy equals the weight of displaced water — Archimedes' exact result." },
          { t:"The upward force on a hull equals the weight of the air trapped beneath it.", v:"wrong", fb:"There is no trapped-air cushion; buoyancy comes from displaced water." },
          { t:"The upward force on a hull grows with the speed at which the ship travels.", v:"wrong", fb:"Buoyancy has nothing to do with speed; a moored ship floats the same." },
          { t:"The upward force on a hull depends only on how deep its keel is set.", v:"partial", fb:"Draft reflects the load, but the force equals the displaced water's weight." } ] },
        { q:"How does loading a ferry change how she sits?", o:[
          { t:"Each added ton settles her deeper until she displaces that much more water.", v:"expert", fb:"Displacement is a running account; more load means less freeboard." },
          { t:"Added weight is carried by the engines' thrust and barely changes her draft.", v:"wrong", fb:"Thrust drives her forward; it does nothing to hold weight against gravity." },
          { t:"Added weight lowers her a little, but her reserve buoyancy is effectively endless.", v:"partial", fb:"Reserve buoyancy is finite; the freeboard is all of it, and it runs out." },
          { t:"Added weight tells only in a storm; in calm water a hull floats regardless.", v:"danger", fb:"Calm water floats an overloaded hull barely, until the first heel wins." } ] },
        { q:"Why does Archimedes' principle help this board?", o:[
          { t:"Floating and sinking follow an exact law, so a low ferry points to her load.", v:"expert", fb:"The waterline is evidence; it is set by weight, not weather or attack." },
          { t:"A hull this low can only have been forced under by a blast tearing her open.", v:"danger", fb:"No blast is needed to press a hull down; extra tonnage does it quietly." },
          { t:"Displacement cannot be measured, so how deep she sat tells the board nothing.", v:"wrong", fb:"Displacement is precisely measurable; her marks recorded the load." },
          { t:"It fixes how she floats but says nothing about how much cargo she carried.", v:"partial", fb:"Read backward, her draft reveals the very tonnage that was aboard." } ] }
      ] },
    // cell: Bosun Adisa @ The Vehicle Deck & Bow Door
    metacentre:{ sci:"Pierre Bouguer (1698-1758)", topic:"Metacentric height & stability", lede:"The French geodesist who gave stability a precise address — the metacentre, the point a ship must never let her weight climb above.", no:2,
      profile:"Pierre Bouguer was a French mathematician, astronomer, and hydrographer, a prodigy who succeeded his father as a professor of hydrography at fifteen. He is remembered for the Peru expedition that helped measure the shape of the Earth, for pioneering work in photometry, and above all, among mariners, for his 'Traite du navire' of 1746 — a founding text of scientific naval architecture. In it he defined the concept that still decides whether a ship is safe: the metacentre.\n\nPicture a ship heeled slightly to one side. Buoyancy still pushes up through the center of the displaced water, but that center has shifted toward the low side. The vertical line of that push crosses the ship's centerline at a point Bouguer named the metacentre, M. Whether the ship rights herself depends on where M sits relative to her center of gravity, G. If M is above G, the buoyant push swings her back upright — she is stable. If the center of gravity climbs above the metacentre, the same push rolls her further over, and she capsizes. The distance between the two, the metacentric height or GM, is the single number that measures a ship's stiffness against rolling.\n\nBouguer's insight is that stability is not a feeling but a calculation. Load a ferry's vehicle deck with heavy cars and trucks and you raise G. Pile the load high, or leave it free to shift, and G climbs toward M, shrinking the righting arm until it vanishes. For this inquiry the metacentre is the crux. A capsize in calm water is not proof of a wave or a weapon; it is proof that somebody let the center of gravity rise past the point Bouguer taught us to compute two centuries ago. The margin was a number, and the number was spent.",
      frame:"Adisa taps his own chest, then lifts his hand higher. \"Stack the weight up here and she stops wanting to come back level. There's a point you can't let her weight climb past. Name it, and I'll tell you how high we stacked them.\"",
      q:[
        { q:"What is the metacentre?", o:[
          { t:"The point the buoyant-force line crosses the centerline when a ship heels over.", v:"expert", fb:"M is where the shifted buoyancy line meets the centerline — Bouguer's point." },
          { t:"The fixed point high on the mast from which the whole ship is said to balance.", v:"wrong", fb:"The metacentre sits near the waterline, not up the mast." },
          { t:"The exact center of the hull where all of the ship's weight is taken to act.", v:"wrong", fb:"That is the center of gravity, G, not the metacentre, M." },
          { t:"The lowest point of the keel, about which a heeling ship is said to turn.", v:"partial", fb:"A ship does not pivot about the keel; M sits well above it." } ] },
        { q:"When is a ship stable, in Bouguer's terms?", o:[
          { t:"When the metacentre stays above the center of gravity, so she rights herself.", v:"expert", fb:"Positive GM — M above G — supplies the righting push; that is stability." },
          { t:"When she is heavy enough that no wave could ever push her off level at all.", v:"danger", fb:"Sheer weight is no guarantee; the G-to-M relation is what decides." },
          { t:"When her center of gravity sits above the metacentre by a comfortable margin.", v:"wrong", fb:"That is precisely the capsizing condition — G must stay below M." },
          { t:"When she is loaded as full as she can be, since weight always steadies a hull.", v:"partial", fb:"Low weight helps, but overloading raises G and can erase the margin." } ] },
        { q:"What does the metacentre tell this board?", o:[
          { t:"That a calm-water capsize means the righting margin was raised away and lost.", v:"expert", fb:"GM is computable; a lost margin points to loading, not weather or arms." },
          { t:"That only a torpedo could roll a certified ferry over in a flat, quiet sea.", v:"danger", fb:"No blast is needed; a raised center of gravity capsizes a ship quietly." },
          { t:"That stability cannot be figured in advance, so the capsize is quite unexplainable.", v:"wrong", fb:"Stability is calculated before every voyage; it is far from a mystery." },
          { t:"That the ship was simply too small, and nothing about her loading matters.", v:"partial", fb:"Size is not the issue; her loading raised G and spent the margin." } ] }
      ] },
    // cell: The Purser @ The Vehicle Deck & Bow Door
    floatstab:{ sci:"Christiaan Huygens (1629-1695)", topic:"The stability of floating bodies", lede:"The Dutch master of clocks and light who also asked, with a mathematician's stubbornness, which way a floating block will choose to sit.", no:3,
      profile:"Christiaan Huygens was the leading scientist of the seventeenth century between Galileo and Newton — a Dutch mathematician, physicist, and astronomer. He invented the pendulum clock, discovered Saturn's largest moon Titan and the true shape of its rings, and proposed the wave theory of light. Less famous, but central to this case, is his early work on the equilibrium of floating bodies, written around 1650 in a manuscript he left unpublished in his lifetime.\n\nBuilding on Archimedes, Huygens went further: not merely does a floating body displace its own weight in water, but among all the ways it could float, only certain orientations are stable. He worked out, for floating shapes such as blocks and segments, which resting positions a body will hold and which it will abandon, rolling to a more comfortable attitude at the smallest nudge. A tall, narrow block set upright is in equilibrium — but tip it slightly and it flops onto its side, because the upright pose sits on the wrong side of stability. Huygens turned this into geometry, finding the conditions that separate a pose a body keeps from one it flees.\n\nThat distinction is the whole of a ferry's safety. A ship, too, has poses she will keep and poses she will abandon. Loaded correctly, upright is the attitude she returns to; loaded wrongly — too much weight carried high — upright becomes the pose she flees, and the first small heel sends her rolling to lie on her side. For this inquiry, Huygens is a warning that floating is not the same as being stable. A hull can sit level at the quay and still be one nudge from a capsize she was always going to seek. The question is never whether she floated, but whether upright was a pose she would keep.",
      frame:"The Purser sets down a ledger. \"People think a ship that floats is a ship that's safe. They are not the same thing, and the difference lives in numbers I keep. Show me you know it, and I'll open the book.\"",
      q:[
        { q:"What did Huygens add to Archimedes on floating bodies?", o:[
          { t:"That only certain floating orientations are stable; others a body abandons.", v:"expert", fb:"Huygens sorted the poses a body keeps from the ones it flees." },
          { t:"That a body floats only if it is lighter than water at every point within it.", v:"wrong", fb:"Even a dense hull floats if shaped to displace enough; not his point." },
          { t:"That a floating body displaces its own weight, and nothing more need be said.", v:"partial", fb:"That is Archimedes; Huygens asked which floating poses actually hold." },
          { t:"That any floating body is safe in every pose, since floating proves it stable.", v:"danger", fb:"Exactly the error he refuted — floating and stable are not the same." } ] },
        { q:"Why might a tall, narrow block flop onto its side?", o:[
          { t:"Upright is an equilibrium it cannot hold, so a small tilt rolls it flat.", v:"expert", fb:"Some equilibria are unstable; the block flees upright at the first nudge." },
          { t:"It soaks up water at the top, growing heavy up high until it simply tips over.", v:"wrong", fb:"No water need enter; the geometry alone makes upright unstable." },
          { t:"It is top-heavy, though any floating shape settles into the same flat pose.", v:"partial", fb:"Broad, low shapes hold upright happily; only the tall block flops." },
          { t:"Only an outside push can move it; left alone it stays upright indefinitely.", v:"danger", fb:"Unstable equilibrium falls to the tiniest disturbance, not a hard shove." } ] },
        { q:"What does Huygens warn this board?", o:[
          { t:"That a hull can float level and still be one heel from a capsize she seeks.", v:"expert", fb:"Floating is not safety; the loaded pose may be one she was always fleeing." },
          { t:"That a ship seen floating at the quay could only be sunk by a deliberate act.", v:"danger", fb:"An unstable hull needs no attacker; she rolls at the first small heel." },
          { t:"That floating proves stability, so a capsize must come from outside the ship.", v:"wrong", fb:"Floating does not prove stability; the capsize can be built into her load." },
          { t:"That stability depends on the hull's shape alone, never on how she is loaded.", v:"partial", fb:"Loading raises the center of gravity and changes her stability directly." } ] }
      ] },
    // cell: The Purser @ The Vehicle Deck & Bow Door
    loadline:{ sci:"Samuel Plimsoll (1824-1898)", topic:"The load line & overloading", lede:"The MP they called the sailor's friend, who fought to paint a single line on every hull so no owner could load a ship to her grave.", no:4,
      profile:"Samuel Plimsoll was a British coal merchant turned Member of Parliament who waged a decade-long campaign against what he called 'coffin ships' — vessels so overloaded and so heavily over-insured that unscrupulous owners stood to profit more if they sank than if they arrived. Crews, with little real choice, were sent to sea in hulls loaded past any margin of safety, and drownings were common. His 1873 book 'Our Seamen' turned public fury into a movement, and he pressed the cause in Parliament with such passion that he was once censured for his outbursts on the floor of the House.\n\nHis remedy was elegant and enforceable: a mark painted on the side of every ship showing the maximum depth to which she could legally be loaded. Load her past that line and she rode too low, with too little freeboard and too little reserve buoyancy to survive rough water. The Merchant Shipping Act of 1876 made the load line law, and the 'Plimsoll line' — later refined into a set of marks for different seasons and waters — became one of the most successful safety measures in maritime history, adopted around the world.\n\nThe load line is the plain, painted embodiment of everything else in this inquiry. It converts the calculus of buoyancy and stability into a mark a harbor pilot can read from a passing launch. If a ship sits with her marks at or below the waterline, she is carrying more than she may lawfully or safely bear, and the reserve that keeps the sea out is gone. For this board, Plimsoll's line is nearly the whole story: a ferry needs no rogue wave and no torpedo to explain a capsize if she went to sea loaded past the very mark he fought to have painted on her.",
      frame:"The Purser slides a photograph across the desk — the Kestrel's marks well below the water. \"There's a line on every hull that says 'no lower.' You should know what it means before I tell you where hers sat.\"",
      q:[
        { q:"What does the load line (Plimsoll mark) show?", o:[
          { t:"The maximum depth to which a ship may legally and safely be loaded down.", v:"expert", fb:"The mark caps loading; below it, freeboard and reserve buoyancy are gone." },
          { t:"The depth the keel reaches below the surface when the ship is riding empty.", v:"wrong", fb:"That is draft, and empty draft at that; the line is a loaded limit." },
          { t:"A rough guide to trim that a careful master may cross in fine, calm weather.", v:"partial", fb:"The line is a legal maximum, not a fair-weather suggestion to ignore." },
          { t:"A decorative marking with no real bearing on how much a ship can carry.", v:"danger", fb:"The line is a hard safety limit, the very heart of Plimsoll's reform." } ] },
        { q:"What evil did Plimsoll's campaign target?", o:[
          { t:"Overloaded, over-insured 'coffin ships' that owners profited from when lost.", v:"expert", fb:"Coffin ships — overloaded and over-insured — were his central target." },
          { t:"Warships sailing under false colors to slip past an enemy blockade at sea.", v:"wrong", fb:"That is a naval ruse; Plimsoll fought commercial overloading." },
          { t:"Poor food and pay for crews, which he thought drove men to abandon ship.", v:"partial", fb:"Conditions were bad, but his fight was against overloading itself." },
          { t:"Sabotage by rival owners who scuttled ships to ruin a competitor's trade.", v:"danger", fb:"The danger came from owners overloading their own hulls, not rivals." } ] },
        { q:"How does the load line bear on the Kestrel?", o:[
          { t:"If she sailed with her marks under water, she was loaded past her limit.", v:"expert", fb:"Submerged marks are the plain signature of an overloaded, low-riding hull." },
          { t:"Marks under water prove a hull holed by a mine and already taking on the sea.", v:"danger", fb:"A submerged mark shows load, not a breach; no flooding is implied by it." },
          { t:"The load line applies only to cargo ships, so a ferry's marks mean nothing.", v:"wrong", fb:"Load lines apply to ferries too; the limit is the same for all hulls." },
          { t:"Low marks show a heavy trip, but say nothing about her actual stability.", v:"partial", fb:"Riding past the line spends freeboard and the stability margin together." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Vehicle Deck & Bow Door
    hullform:{ sci:"Frederik H. af Chapman (1721-1808)", topic:"Naval architecture & hull form", lede:"The Swedish shipwright who first treated a hull as mathematics on paper, drawing whole navies before a single plank was cut.", no:5,
      profile:"Frederik Henric af Chapman was a Swedish shipbuilder widely regarded as the first true naval architect — the first to design ships by scientific calculation rather than by inherited rule of thumb. Born in Gothenburg to an English-born shipwright, he studied yards across Europe, learned mathematics and mechanics, and rose to become the chief designer of the Swedish navy. His great work, 'Architectura Navalis Mercatoria' (1768), was an atlas of merchant and naval vessels drawn to consistent scale — a reference so thorough that it standardized how ships were conceived and compared.\n\nChapman brought method to a craft ruled by tradition. He applied the geometry of curves to the shaping of a hull's lines, developed a systematic way to lay out a hull's form so its displacement and balance could be computed in advance, and studied how a hull's shape governs its resistance, its capacity, and its steadiness. He designed and built large fleets efficiently, introducing near-industrial organization to the shipyard, and his frigates and archipelago craft served Sweden well. He proved that a ship's behavior could be predicted from her drawn form before she ever touched the water.\n\nFor this inquiry, Chapman stands for predictability. A ferry is not an improvisation; her hull form, her intended draft, and the loading she was designed to carry are all known quantities, set down long before she sails. Deviations from that design — a deck packed beyond what the lines were drawn to bear — are therefore visible against a fixed standard. When a hull misbehaves, the naval architect asks first how she differed from the vessel on the drawings. A capsize is measured against a design, and if the Kestrel was loaded far past what Chapman's kind of calculation allowed for her, the fault lies in that departure, not in an act of God or an enemy.",
      frame:"Enns squints out at the harbor. \"I've watched a thousand hulls come past my launch, and a good one behaves the way her lines promise. Show me you know how a hull is meant to sit, and I'll tell you how this one didn't.\"",
      q:[
        { q:"What made af Chapman the first true naval architect?", o:[
          { t:"He designed ships by calculation and drawn lines, not by old rule of thumb.", v:"expert", fb:"Chapman replaced craft habit with mathematics on paper — the field's start." },
          { t:"He built the largest wooden warship ever to be launched from any European yard.", v:"wrong", fb:"Size was not his mark; method and calculation were his real innovation." },
          { t:"He organized the shipyard efficiently, though he left the design to tradition.", v:"partial", fb:"He reformed the yard and the design; he did not leave design to habit." },
          { t:"He proved a hull's behavior at sea can never be foreseen from its drawings.", v:"danger", fb:"He proved the opposite — a hull's behavior follows from its drawn form." } ] },
        { q:"What could Chapman compute from a hull's drawn lines?", o:[
          { t:"Its displacement and balance, so her floating trim was known in advance.", v:"expert", fb:"From the lines came displacement and trim — the ship known before launch." },
          { t:"The precise wages a crew would earn on a voyage of any given length at sea.", v:"wrong", fb:"That is a purser's arithmetic, not naval architecture from the lines." },
          { t:"Its rough size, though nothing about how deep she would actually come to float.", v:"partial", fb:"The lines yield displacement and trim exactly, not just a rough size." },
          { t:"Nothing useful, since a hull's real behavior is settled only once it is at sea.", v:"danger", fb:"The whole point was that behavior follows from the drawn form." } ] },
        { q:"Why does Chapman's method help this board?", o:[
          { t:"A hull has a designed load, so packing her past it shows a clear departure.", v:"expert", fb:"Loading is measured against the design; the Kestrel's excess is visible." },
          { t:"It proves a well-drawn ferry can capsize only if a weapon strikes her hull.", v:"danger", fb:"A hull loaded past her design capsizes with no weapon at all." },
          { t:"It shows hull behavior is unknowable, so the capsize cannot be accounted for.", v:"wrong", fb:"Chapman made hull behavior knowable; the departure can be measured." },
          { t:"It fixes her shape but reveals nothing about the weight she was made to bear.", v:"partial", fb:"The design fixes her intended loading as surely as her shape." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Vehicle Deck & Bow Door
    modeltest:{ sci:"William Froude (1810-1879)", topic:"Model testing & the Froude number", lede:"The Devon engineer who towed little waxed models down a tank and cracked the riddle of how a big ship's motion scales from a small one.", no:6,
      profile:"William Froude was a British engineer who, late in a career that included work for Brunel's railways and ships, founded the science of ship-model testing. He built the first purpose-made towing tank at Torquay in the early 1870s, running waxed models along a measured length of water to record their resistance. His central discovery, the 'law of comparison,' showed how the results from a small model translate to a full-size ship — provided one particular condition is met.\n\nThat condition is captured by what we now call the Froude number, a ratio comparing a vessel's speed to the size of the waves its own length can make. Model and ship behave alike when their Froude numbers match, so wave-making resistance measured on a model can be scaled up reliably. This let designers predict a ship's power and speed from cheap tank tests rather than costly trial and error. But Froude studied more than drag: he made a careful theoretical and experimental study of the rolling of ships among waves, showing that a hull has a natural rolling period and can be driven into dangerous, resonant rolls when waves arrive in time with it.\n\nFor this inquiry, Froude matters twice over. First, he stands for the principle that a ship's motions are testable and predictable, not mysterious. Second, his work on rolling shows that a hull's response to the sea is a known quantity, tied to her stability. A ferry with ample metacentric height rolls smartly and returns firmly; one loaded until her margin is thin rolls sluggishly, hangs at the far end, and may not come back. Froude's tank is a rebuke to the idea that the sea sprang a surprise no one could have foreseen; the Kestrel's stability, and how she would roll, were calculable long before she ever sailed.",
      frame:"Enns rolls his hand side to side. \"A hull has a rhythm to her roll, and a pilot feels the instant it's gone wrong. It's no mystery — men measured it in tanks a century ago. Prove you understand it.\"",
      q:[
        { q:"What does the Froude number let engineers do?", o:[
          { t:"Scale a small model's wave-making resistance up to a full-size ship reliably.", v:"expert", fb:"Matching Froude numbers makes model and ship behave alike — his law." },
          { t:"Convert a ship's fuel use into the range she can steam before she must refuel.", v:"wrong", fb:"That is a range calculation, not the speed-to-wave ratio Froude found." },
          { t:"Compare two hulls' shapes, though the results cannot be scaled between sizes.", v:"partial", fb:"The whole value is that matched Froude numbers do let you scale up." },
          { t:"Predict exactly when a rogue wave will rise, so no ship need be caught out.", v:"danger", fb:"The number scales resistance and motion; it forecasts no freak waves." } ] },
        { q:"What did Froude find about how ships roll?", o:[
          { t:"A hull has a natural roll period and can be driven into dangerous rolls.", v:"expert", fb:"Froude tied rolling to a natural period and to the ship's stability." },
          { t:"A hull rolls at random, so its motion in waves can never really be predicted.", v:"wrong", fb:"He showed rolling is orderly and predictable, set by a natural period." },
          { t:"Rolling depends only on the wave height, not on the ship's own stability at all.", v:"partial", fb:"Roll depends heavily on the hull's stability, not on the waves alone." },
          { t:"Rolling is harmless in calm water; only a storm sea can make a hull roll far.", v:"danger", fb:"A ferry with a thin margin can roll far in calm water and not return." } ] },
        { q:"How does Froude's work guide this inquiry?", o:[
          { t:"A ship's roll and stability are calculable, so the capsize was foreseeable.", v:"expert", fb:"Roll and stability are testable; the Kestrel's danger was predictable." },
          { t:"It shows only a torpedo's shock could roll a sound hull past her return point.", v:"danger", fb:"A thin stability margin lets a hull roll over with no shock at all." },
          { t:"It shows a ship's motions are untestable, so the sea's behavior stays a mystery.", v:"wrong", fb:"Froude made motions testable; his tank exists to remove the mystery." },
          { t:"It fixes her top speed but tells the board nothing about why she rolled over.", v:"partial", fb:"His rolling work bears directly on why and how far a hull rolls." } ] }
      ] },
    // cell: Bosun Adisa @ The Bridge & Ballast Controls
    modelbasin:{ sci:"David W. Taylor (1864-1940)", topic:"The ship model basin", lede:"The U.S. naval constructor who built America its first great testing tank and filled it with the data every warship hull would be measured against.", no:7,
      profile:"David Watson Taylor was a United States naval constructor and rear admiral who brought rigorous science to American warship design. A brilliant student who graduated at the top of his class, he studied naval architecture in Britain and returned determined to give the U.S. Navy its own experimental capability. In 1898 he oversaw the building of the Experimental Model Basin at the Washington Navy Yard — a long tank in which scale models were towed to measure their resistance and behavior, echoing Froude's work but on a national scale.\n\nTaylor used the basin to conduct systematic experiments, varying hull dimensions methodically and recording the results. This produced the 'Taylor Standard Series,' a body of resistance data from which designers could estimate the power a proposed hull would need without building it first. He summarized the field in his influential book 'The Speed and Power of Ships.' He is also associated with early study of the bulbous bow, the underwater bulb at a ship's forefoot that can reduce wave-making resistance. His method throughout was to replace guesswork with a library of measured cases.\n\nFor this inquiry, Taylor represents the institutional memory of naval architecture. The behavior of hulls is not rediscovered for each new ship; it rests on decades of tank data and standard series that tell an engineer, in advance, how a given hull will float, resist, and respond. A ferry's safe loading and stability sit squarely within that known body of knowledge. When a ship capsizes, the question is not whether her behavior could have been predicted — Taylor's basin proves it could — but whether anyone consulted what was already known, or loaded her in defiance of it. The data existed; the only question is whether it was honored or ignored.",
      frame:"Adisa nods at the ballast panel. \"Up here they've got dials and tables for everything a hull will do. None of it's guesswork. Show me you know where that knowledge comes from, and I'll tell you what nobody bothered to check.\"",
      q:[
        { q:"What was Taylor's Experimental Model Basin for?", o:[
          { t:"Towing scale models to measure hull resistance and predict a ship's power.", v:"expert", fb:"The basin measured models to forecast full-size resistance and power." },
          { t:"Training naval cadets to pilot small boats through a narrow indoor channel.", v:"wrong", fb:"It was a measuring tank, not a training channel for boat handling." },
          { t:"Storing spare test models, though the ships' behavior was still judged by eye.", v:"partial", fb:"Models were towed and measured, not merely stored for later study." },
          { t:"Proving that a hull's resistance can never be known until the ship is built.", v:"danger", fb:"The basin's whole purpose was to know resistance before building." } ] },
        { q:"What was the Taylor Standard Series?", o:[
          { t:"A body of measured resistance data for estimating a new hull's power needs.", v:"expert", fb:"The series let designers estimate power from methodically varied cases." },
          { t:"A ranking of the world's fastest warships by their recorded top speeds at sea.", v:"wrong", fb:"It was resistance data, not a league table of ship speeds." },
          { t:"A single model's results, useful only for the one hull that had been tested.", v:"partial", fb:"It spanned many systematically varied hulls, not just one." },
          { t:"A claim that all hulls behave identically, so no testing is ever really needed.", v:"danger", fb:"Hulls differ; the series exists precisely to chart those differences." } ] },
        { q:"What does Taylor's basin tell this board?", o:[
          { t:"A hull's limits were already known, so a capsize means the data was ignored.", v:"expert", fb:"The knowledge existed; the failure was to honor it, not to lack it." },
          { t:"It proves a capsize this sudden could only be the work of a hidden mine.", v:"danger", fb:"No mine is needed; ignoring known stability limits is enough to capsize." },
          { t:"It shows hull behavior is guesswork, so the loss could not be foreseen at all.", v:"wrong", fb:"Taylor's basin made hull behavior data, not guesswork." },
          { t:"It fixed her power but left her stability and loading wholly unstudied.", v:"partial", fb:"Standard series and stability sit in the same known body of knowledge." } ] }
      ] },
    // cell: Bosun Adisa @ The Bridge & Ballast Controls
    shiptheory:{ sci:"William J. M. Rankine (1820-1872)", topic:"Shipbuilding theory & stability", lede:"The Glasgow polymath who wrote the era's engineering textbooks and gathered the scattered science of the shipyard into one coherent theory.", no:8,
      profile:"William John Macquorn Rankine was a Scottish engineer and physicist of extraordinary range, a professor at the University of Glasgow and one of the founders of thermodynamics — the Rankine cycle and the absolute Rankine temperature scale bear his name. He also made foundational contributions to soil mechanics, structural analysis, and the theory of waves. A tireless systematizer, he wrote a series of engineering manuals that trained a generation of Victorian engineers, insisting always that practical craft be underpinned by sound theory.\n\nAmong these was his work on shipbuilding, gathered in the collaborative volume 'Shipbuilding: Theoretical and Practical.' Rankine helped bring the mathematics of buoyancy, stability, and resistance to a trade that had long relied on experience alone. He treated a ship as a mechanical system whose behavior could be analyzed: the forces of buoyancy and weight, the couple that rights or capsizes a heeled hull, the resistance of the water to her passage. He was among the early members of the Institution of Naval Architects, part of a movement to make shipbuilding a calculated engineering discipline rather than a hereditary craft.\n\nFor this inquiry, Rankine embodies the idea that a ship's stability is a matter of mechanics, open to analysis and prediction. The righting couple that returns a heeled ferry to upright is a force that can be computed from her form and her loading; when it is too small, or reversed, the outcome follows by mechanics, not by chance. Rankine would have no patience for calling a capsize an act of God when the governing forces were calculable all along. His legacy is that the collapse of a ship's stability is an engineering event with an engineering cause — and, in this case, an engineering decision behind it.",
      frame:"Adisa taps a worn manual on the chart table. \"There's a whole science to whether she comes back level or she doesn't. It's in books like this. Convince me you understand the forces, and I'll tell you what tipped the balance.\"",
      q:[
        { q:"What did Rankine help bring to shipbuilding?", o:[
          { t:"The mathematics of buoyancy, stability, and resistance to a craft of habit.", v:"expert", fb:"Rankine gave the shipyard a theoretical basis in buoyancy and stability." },
          { t:"The steam turbine, which first drove ships faster than any sail could manage.", v:"wrong", fb:"That was Parsons; Rankine's gift was theory, not a new engine." },
          { t:"Better timber-joining methods, though the theory of stability he left aside.", v:"partial", fb:"His contribution was stability theory, not joinery technique." },
          { t:"Proof that a ship's stability defies analysis and can only be learned at sea.", v:"danger", fb:"He showed stability yields to analysis; it does not defy it." } ] },
        { q:"How did Rankine treat a ship?", o:[
          { t:"As a mechanical system whose righting and resistance forces can be computed.", v:"expert", fb:"He analyzed the ship as forces and couples open to calculation." },
          { t:"As a work of craft best left entirely to a master shipwright's own instinct.", v:"wrong", fb:"Rankine's whole point was to replace instinct with analysis." },
          { t:"As a hull to be tested afloat, since theory could tell little in advance.", v:"partial", fb:"He showed much could be computed before the ship ever floated." },
          { t:"As too complex for analysis, so its behavior remained a matter of pure luck.", v:"danger", fb:"He made stability a calculation, removing it from the realm of luck." } ] },
        { q:"How does Rankine's view frame this capsize?", o:[
          { t:"The righting couple is computable, so its collapse had a cause, not luck.", v:"expert", fb:"A vanished righting couple is an event with an engineering cause." },
          { t:"It shows a righting couple can only be defeated by the shock of an explosion.", v:"danger", fb:"A small or reversed righting couple capsizes a hull with no blast." },
          { t:"It shows stability is unknowable, so calling it an act of God is fair enough.", v:"wrong", fb:"Rankine made stability calculable; 'act of God' does not survive it." },
          { t:"It explains her water resistance but says nothing about why she rolled over.", v:"partial", fb:"His stability work bears squarely on why she failed to right herself." } ] }
      ] },
    // cell: The Purser @ The Bridge & Ballast Controls
    waves:{ sci:"John Scott Russell (1808-1882)", topic:"Waves & the wave-line hull", lede:"The Scottish engineer who galloped along a canal chasing a single heaped-up wave that would not break, and named a new thing in physics.", no:9,
      profile:"John Scott Russell was a Scottish civil engineer and naval architect whose most celebrated moment came in 1834 on the Union Canal near Edinburgh. Watching a boat stop suddenly, he saw the mass of water it had been pushing roll on ahead as a single smooth heap that neither broke nor spread — a solitary wave holding its shape. He chased it on horseback for a mile or two before losing it, and spent years afterward studying what he called the 'wave of translation,' known today as a soliton, a landmark in the physics of waves.\n\nFrom this fascination Russell developed his 'wave-line' theory of ship design, arguing that a hull's forward lines should be shaped to match the form of a wave so as to part the water with least disturbance. Whatever the theory's limits, it pushed designers to think hard about the waves a ship itself makes and moves through. Russell was a formidable builder too: with Isambard Kingdom Brunel he constructed the 'Great Eastern,' by far the largest ship of its age, and he was a founder of the Institution of Naval Architects.\n\nFor this inquiry, Russell is the authority on waves themselves. He knew, better than almost anyone of his century, what waves are and how they behave — their shapes, their speeds, the energy they carry. That expertise cuts against the lure of the 'rogue wave' explanation. A wave large enough to capsize a ferry leaves evidence: it is a storm-sea or shoal phenomenon, felt by other vessels and recorded by the weather. It does not rise from a flat, calm harbor approach to single out one overloaded ship. Russell's science lets the board weigh whether a wave was even possible — or whether the water that came aboard was already on her own deck.",
      frame:"The Purser taps the weather log. \"They'll want you to blame a wave — one freak sea, nobody's fault. But waves leave a record, and I keep records. Show me you understand them before you reach for that story.\"",
      q:[
        { q:"What was Russell's 'wave of translation'?", o:[
          { t:"A single heaped wave that held its shape and neither broke nor spread out.", v:"expert", fb:"The solitary wave kept its form for miles — Russell's famous sighting." },
          { t:"A towering breaker that curls over and collapses onto a beach in the surf.", v:"wrong", fb:"His wave did not break; that is exactly what made it remarkable." },
          { t:"An ordinary ripple, of interest only for how quickly it faded to nothing.", v:"partial", fb:"It was a lasting, coherent wave, not a fading ripple of no interest." },
          { t:"A freak wave that rises without warning out of any calm, flat water at will.", v:"danger", fb:"It arose from a boat's own push in a canal, not from calm water at will." } ] },
        { q:"What was Russell's 'wave-line' theory about?", o:[
          { t:"Shaping a hull's forward lines to part the water with the least disturbance.", v:"expert", fb:"Wave-line design matched the bow to a wave to disturb the water least." },
          { t:"Timing a ship's engines to ride the crest of following seas for free speed.", v:"wrong", fb:"The theory concerned hull shape, not engine timing on the seas." },
          { t:"Decorating a hull's bow, a matter of style with no effect on her motion.", v:"partial", fb:"It was about hydrodynamic form, not decoration of the bow." },
          { t:"Proving a hull can outrun any wave, so no sea can ever overtake a ship.", v:"danger", fb:"No hull outruns every wave; the theory was about shaping, not escape." } ] },
        { q:"How does Russell's expertise bear on the 'rogue wave' claim?", o:[
          { t:"A wave able to capsize a ferry leaves a record and is felt by other ships.", v:"expert", fb:"Big waves are storm or shoal events, recorded and widely felt, not silent." },
          { t:"It confirms a freak wave can strike one hull alone from a calm, flat sea.", v:"danger", fb:"Russell's science argues against a lone freak wave in a calm approach." },
          { t:"It shows waves are unknowable, so the rogue-wave story cannot be tested.", v:"wrong", fb:"He made waves highly knowable; the rogue claim can indeed be tested." },
          { t:"It fixes a wave's speed but not whether one was present that day at all.", v:"partial", fb:"The weather record can settle whether such a wave was even possible." } ] }
      ] },
    // cell: The Purser @ The Bridge & Ballast Controls
    wake:{ sci:"Lord Kelvin — William Thomson (1824-1907)", topic:"The ship wake & the tides", lede:"The Belfast-born titan of Victorian physics who fixed the angle of every ship's wake and built a brass machine that could predict the tides.", no:10,
      profile:"William Thomson, ennobled as Lord Kelvin, was one of the dominant physicists of the nineteenth century — a professor at Glasgow for over half a century, a founder of thermodynamics, and the engineer whose instruments made the first successful transatlantic telegraph cable possible. His name marks the absolute temperature scale. Among his many contributions, two speak directly to the sea: the pattern of a ship's wake, and the prediction of the tides.\n\nKelvin showed that the wake trailing behind any ship moving through deep water spreads within a wedge of a fixed half-angle — close to nineteen and a half degrees — regardless of the ship's speed. This 'Kelvin wake' is a signature of surface-wave physics, the same for a duck or a battleship, and it demonstrates how orderly and predictable the water's response to a moving hull really is. Separately, Kelvin analyzed the tides as the sum of regular harmonic components and built a mechanical tide-predicting machine, a system of pulleys and dials that could compute the rise and fall of the sea at a port far into the future.\n\nFor this inquiry, Kelvin stands for the deep predictability of the sea's motions. Wakes follow a law; tides are computed years ahead and printed in tables any master consults before sailing. The state of the water on the Kestrel's approach — the tide, the current, the wash of passing traffic — was knowable and, for the most part, known. This forecloses the idea that the sea did something inexplicable. If the water misbehaved, it did so within limits Kelvin's science had already mapped, and the search must turn to what aboard the ship, not out in the harbor, had changed.",
      frame:"The Purser opens the tide tables. \"The sea keeps to a schedule, and I can show you exactly what it was doing that hour. Prove you understand how orderly the water is, and I'll tell you what wasn't in the tables.\"",
      q:[
        { q:"What did Kelvin show about a ship's wake?", o:[
          { t:"It spreads within a wedge of fixed half-angle, whatever the ship's speed.", v:"expert", fb:"The Kelvin wake holds a constant half-angle near nineteen degrees." },
          { t:"It widens steadily with speed, opening flat behind only the fastest ships.", v:"wrong", fb:"The half-angle stays fixed; it does not open up with more speed." },
          { t:"It trails straight behind the hull, forming no discernible angle at all.", v:"partial", fb:"The wake forms a clear, fixed wedge, not a single straight line." },
          { t:"It varies so wildly that no two wakes ever share the same shape or spread.", v:"danger", fb:"Wakes are strikingly regular, sharing one characteristic angle." } ] },
        { q:"What did Kelvin's tide-predicting machine do?", o:[
          { t:"Compute a port's future rise and fall as a sum of harmonic components.", v:"expert", fb:"It summed harmonic tidal components to predict the sea years ahead." },
          { t:"Measure the depth of water beneath a ship's keel as she steamed into port.", v:"wrong", fb:"That is a sounding; Kelvin's machine forecast the tide instead." },
          { t:"Record past tides for the log, though it could not predict future ones.", v:"partial", fb:"Its purpose was prediction of future tides, not mere record-keeping." },
          { t:"Prove the tides are random, so no port's water level can be foreseen.", v:"danger", fb:"The machine proved tides are regular and highly predictable." } ] },
        { q:"What does Kelvin's science say about the Kestrel's approach?", o:[
          { t:"The state of the water was knowable, so no inexplicable sea can be blamed.", v:"expert", fb:"Tides and wakes were mapped; the search turns to the ship, not the sea." },
          { t:"It shows the harbor sea can turn freakish, striking one hull without warning.", v:"danger", fb:"Kelvin's science leaves little room for a freak harbor sea." },
          { t:"It shows the sea is unpredictable, so the water's behavior explains the loss.", v:"wrong", fb:"He made the sea's motions predictable, not a mystery." },
          { t:"It fixes the tide's height but leaves the current wholly unaccounted for.", v:"partial", fb:"Currents, like tides, sit within the mapped, knowable state of the water." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Bridge & Ballast Controls
    viscousdrag:{ sci:"George Gabriel Stokes (1819-1903)", topic:"Viscosity & water resistance", lede:"The Cambridge mathematician who wrote the equations of every flowing fluid and reckoned the drag on a sphere sinking through it.", no:11,
      profile:"Sir George Gabriel Stokes was an Anglo-Irish mathematician and physicist, Lucasian Professor at Cambridge, whose work underlies the whole science of fluid motion. Building on Claude-Louis Navier before him, he framed the Navier-Stokes equations, the fundamental laws describing how a viscous fluid flows under pressure, gravity, and internal friction. These equations remain the bedrock of hydrodynamics; the difficulty of solving them in general is one of the famous open problems of mathematics.\n\nStokes gave viscosity — a fluid's internal stickiness, its resistance to being sheared — a rigorous place in physics. He derived 'Stokes's law' for the slow fall of a small sphere through a viscous fluid, showing how the drag depends on the sphere's size, its speed, and the fluid's viscosity. The result let scientists measure viscosity and understand sedimentation, and it captures the essential truth that a body moving through water is resisted by forces that can be written down and calculated. He also contributed to optics, coining the term 'fluorescence,' but his fluid mechanics is his monument.\n\nFor this inquiry, Stokes represents the calculability of the water's resistance to a hull. The forces the sea exerts on a moving ferry — the drag on her hull, the damping of her roll, the slow ooze of water finding its way across a deck — are governed by viscosity and by equations, not by whim. This matters in two ways. It confirms that a ship's motion through calm water holds no surprises for the analyst. And it reminds the board that water is a real, heavy, mobile substance: once it is free to move across a broad deck, its behavior, however destabilizing, is ordinary physics, not an act of God. The sea obeys equations; so does the water that should never have been loose aboard her.",
      frame:"Enns dips his hand as if into the tide. \"Water pushes back on a hull in ways you can put numbers to — and it's heavy stuff once it's loose. Show me you grasp how water behaves, and I'll tell you where I saw it go.\"",
      q:[
        { q:"What are the Navier-Stokes equations?", o:[
          { t:"The core laws of how a viscous fluid flows under pressure and friction.", v:"expert", fb:"They govern viscous flow — the bedrock equations of hydrodynamics." },
          { t:"A rule for the buoyant force on any object fully submerged in still water.", v:"wrong", fb:"That is Archimedes' principle; Navier-Stokes describes flow, not float." },
          { t:"A formula for a ship's top speed, useful for nothing else about the flow.", v:"partial", fb:"They describe the whole flow field, not merely a single speed." },
          { t:"A proof that fluid motion is lawless and can never really be described at all.", v:"danger", fb:"They are the very laws of fluid motion, not a proof of its lawlessness." } ] },
        { q:"What does Stokes's law describe?", o:[
          { t:"The drag on a small sphere sinking slowly through a viscous fluid.", v:"expert", fb:"Stokes's law ties a sphere's drag to size, speed, and viscosity." },
          { t:"The lift on a wing as it slices through fast-moving air at an angle.", v:"wrong", fb:"That is aerodynamic lift; Stokes's law is about viscous drag." },
          { t:"The speed of sound as it passes through water of a given temperature.", v:"partial", fb:"Sound speed is a separate matter; his law concerns viscous drag." },
          { t:"The force of a wave breaking, which no equation can ever hope to pin down.", v:"danger", fb:"Even breaking waves obey fluid dynamics; his law is viscous drag." } ] },
        { q:"How does Stokes's science bear on this case?", o:[
          { t:"Water's forces obey equations, so loose water on deck is ordinary physics.", v:"expert", fb:"Free water is heavy and mobile, and its effect is calculable, not divine." },
          { t:"It proves water can move a hull only when a blast blows a hole in her side.", v:"danger", fb:"Water need not be let in by a blast; it can already be loose on the deck." },
          { t:"It shows fluid forces are unknowable, so the water's role can't be judged.", v:"wrong", fb:"Stokes made fluid forces calculable; the water's role can be judged." },
          { t:"It explains her hull drag but nothing about water moving across the deck.", v:"partial", fb:"The same viscous physics governs water sloshing across a car deck." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Bridge & Ballast Controls
    freesurface:{ sci:"Sir William H. White (1845-1913)", topic:"Roll & the free-surface effect", lede:"The Royal Navy's chief constructor, who wrote the manual a generation learned from — and warned exactly what loose water does to a ship's stability.", no:12,
      profile:"Sir William Henry White was one of the most influential naval architects of his age, Director of Naval Construction for the British Royal Navy, responsible for the design of a great many warships during a period of rapid change. Before that, he wrote 'A Manual of Naval Architecture' (1877), a comprehensive textbook that became the standard reference for naval architects across the world, teaching buoyancy, stability, strength, and the motion of ships in a single authoritative volume.\n\nWhite's manual laid out with unusual clarity the principles that decide a ship's safety, including the treatment of stability and the danger of liquids free to move inside a hull. This is the free-surface effect: when a tank or a deck holds liquid that can slosh from side to side, the liquid's own shifting weight moves toward the low side as the ship heels, dragging the center of gravity that way and reducing the ship's effective metacentric height. A partly filled space is far more dangerous than a full one or an empty one, because the free surface lets the load chase the roll. Enough free water, spread across a wide deck, can wipe out a ship's stability entirely.\n\nFor this inquiry, White's free-surface effect is close to the beating heart of the case. A vehicle deck is a single vast open space; let water onto it — through a door, a scupper, a wave that came aboard because the freeboard was already gone — and that water is free to surge across the full width as she rolls. Each roll throws it further, and it drags her stability down with it until she cannot return. This is how an overloaded, low-riding ferry can capsize in calm water without any wave or weapon: the danger was not from the sea outside but from water loose on the deck within, exactly as White warned.",
      frame:"Enns lowers his voice. \"The worst thing at sea isn't the water outside the hull — it's water loose inside her, running with the roll. If you understand that, you understand what took her. Show me.\"",
      q:[
        { q:"What is the free-surface effect?", o:[
          { t:"Liquid free to slosh inside a hull shifts with the roll and cuts stability.", v:"expert", fb:"Free liquid chases the low side, dropping the effective metacentric height." },
          { t:"The drag of the open sea against a hull's outer surface as she moves ahead.", v:"wrong", fb:"That is skin friction outside; free surface is loose liquid within." },
          { t:"The tendency of a full tank to make a ship slightly heavier up toward the bow.", v:"partial", fb:"A full tank has no free surface; the danger is a partly filled space." },
          { t:"A harmless swaying of cargo that no loaded ship has ever really needed to fear.", v:"danger", fb:"Free surface is a classic capsizing hazard, not a harmless sway." } ] },
        { q:"Why is a partly filled space more dangerous than a full one?", o:[
          { t:"Its free surface lets the liquid chase the roll and drag stability down.", v:"expert", fb:"A free surface lets the load run to the low side and worsen every roll." },
          { t:"It weighs far more than a full space, pressing the hull dangerously deep.", v:"wrong", fb:"A partly filled space weighs less, not more; the hazard is the motion." },
          { t:"It sits higher in the hull, though the liquid inside cannot actually move.", v:"partial", fb:"The whole danger is that the liquid does move across the space." },
          { t:"It is not more dangerous at all; only the total weight aboard can matter.", v:"danger", fb:"Distribution and free surface matter as much as the total weight." } ] },
        { q:"How does the free-surface effect explain the Kestrel?", o:[
          { t:"Water loose on her wide car deck ran with the roll until she couldn't return.", v:"expert", fb:"Free water on an open car deck is the classic route to a calm-water capsize." },
          { t:"Only a torpedo could let in enough water to unbalance a deck this large.", v:"danger", fb:"Water can board through a door or lost freeboard, needing no torpedo." },
          { t:"A vehicle deck holds no water, so the free-surface effect cannot apply here.", v:"wrong", fb:"An open car deck is exactly where free water pools and surges." },
          { t:"It might add a little roll, but her stability was never really threatened.", v:"partial", fb:"Enough free surface can erase stability outright, not merely nudge it." } ] }
      ] },
    // cell: Bosun Adisa @ The Ferry Line's Office
    scaling:{ sci:"Osborne Reynolds (1842-1912)", topic:"Turbulence & scale models", lede:"The Manchester professor who dyed a thread of water and caught the exact instant a smooth flow shatters into turbulence.", no:13,
      profile:"Osborne Reynolds was a British engineer and physicist, the first professor of engineering at Owens College in Manchester, whose 1883 experiment is one of the most elegant in the history of fluid mechanics. Injecting a fine thread of dye into water flowing through a glass tube, he watched the thread run straight and smooth at low speeds — laminar flow — and then, as the speed rose past a threshold, break up and mix into chaotic swirls: turbulence. He showed that the transition is governed by a single dimensionless ratio, now called the Reynolds number, comparing the fluid's inertia to its viscosity.\n\nThe deeper power of this number is dynamic similarity: two flows with the same Reynolds number behave alike, whatever their actual size or speed. This is what makes a scale-model test in a tank meaningful, and it is also what complicates it, because a small model and a full-size ship cannot in general match both the Reynolds number and Froude's wave-scaling number at once. Naval architects learned to separate the frictional resistance, which scales by Reynolds's rule, from the wave-making resistance, which scales by Froude's — combining the two to predict the full ship.\n\nFor this inquiry, Reynolds stands for the rigor and the honesty of scale testing. The behavior of a ferry — her resistance, her wake, the flow of water across her decks — can be studied on models and in calculation, provided the analyst respects the scaling laws and does not fool himself. Reynolds's discipline is that the water does not lie; it obeys ratios that can be written down. A capsize is not beyond such analysis. The only way the truth escapes is if no one runs the numbers, or if someone runs them and looks away from what the model, honestly scaled, already shows.",
      frame:"Adisa gestures at the filing cabinets. \"All the tests, all the numbers, they end up in a room like this. The water doesn't lie — but paper can be filed away. Show me you know how the numbers are made, and I'll tell you which drawer to open.\"",
      q:[
        { q:"What did Reynolds's dye experiment reveal?", o:[
          { t:"How a smooth, laminar flow breaks into turbulence past a threshold speed.", v:"expert", fb:"He caught the laminar-to-turbulent transition at a critical value." },
          { t:"How the buoyant force on a submerged body grows with its total volume.", v:"wrong", fb:"That is buoyancy; his experiment was about the flow's transition." },
          { t:"How dye spreads in still water, of interest only to the study of mixing.", v:"partial", fb:"It revealed the transition to turbulence, a far more general result." },
          { t:"That water flow is wholly random and can never be predicted in advance.", v:"danger", fb:"He showed the transition is orderly, set by the Reynolds number." } ] },
        { q:"What does the Reynolds number compare?", o:[
          { t:"A fluid's inertia to its viscosity, setting whether flow is smooth or rough.", v:"expert", fb:"Inertia over viscosity — the ratio that predicts the flow transition." },
          { t:"A ship's weight to its buoyancy, deciding how deep the hull will float.", v:"wrong", fb:"That is a flotation balance, not the inertia-to-viscosity ratio." },
          { t:"A model's size to the real ship's, which is all that scaling ever requires.", v:"partial", fb:"Scale alone is not enough; the Reynolds number must be matched." },
          { t:"A wave's height to its length, which alone fixes when a hull will capsize.", v:"danger", fb:"That describes wave steepness, not the Reynolds number." } ] },
        { q:"What does Reynolds's discipline imply for this board?", o:[
          { t:"A ferry's behavior is analyzable, so the truth escapes only if no one looks.", v:"expert", fb:"The numbers exist to be run; looking away is the only way truth hides." },
          { t:"It proves a capsize can be understood only after a weapon strike is found.", v:"danger", fb:"No weapon is needed; honest scaling already explains the capsize." },
          { t:"It shows scale tests are meaningless, so nothing here could be foreseen.", v:"wrong", fb:"Scale tests are valid when the scaling laws are respected." },
          { t:"It fixes her friction drag but leaves her stability entirely untested.", v:"partial", fb:"The same rigor applies to stability as to drag; both can be studied." } ] }
      ] },
    // cell: Bosun Adisa @ The Ferry Line's Office
    currents:{ sci:"Vagn Walfrid Ekman (1874-1954)", topic:"Wind-driven currents & drift", lede:"The Swedish oceanographer who explained why polar ice, and every wind-blown current, drifts stubbornly to the side of the wind that pushes it.", no:14,
      profile:"Vagn Walfrid Ekman was a Swedish oceanographer who, as a young man, solved a puzzle that had baffled the explorer Fridtjof Nansen. Nansen had noticed that the Arctic ice did not drift in the direction of the wind but consistently forty to fifty degrees to its right. Working under the physicist Vilhelm Bjerknes, Ekman showed in 1905 that this deflection follows from the Earth's rotation — the Coriolis effect — acting on wind-driven water. His analysis produced the 'Ekman spiral': surface water pushed by the wind drags the layer beneath it, and each successive layer is deflected further, so the net transport of water runs at right angles to the wind.\n\nEkman's work founded the physical study of ocean currents and remains fundamental to oceanography. It explains coastal upwelling, the movement of surface waters, and the drift of anything floating on the sea. He also designed instruments — the Ekman current meter and water bottle — to measure these flows directly, marrying theory to careful observation in the field.\n\nFor this inquiry, Ekman supplies the science of drift and current: how the water around the Kestrel was moving, and how a disabled or floating object would be carried. This matters for reconstructing the casualty — where she began to roll, how she and any debris drifted afterward, and whether the current could have contributed to her heading or her heel. But it matters most as another entry in the ledger of the knowable. Wind, current, and drift are computed, not conjured. Every environmental force acting on the ferry that day can be accounted for, which steadily narrows the unexplained down to what was done aboard her — and to who did it.",
      frame:"Adisa spreads a current chart on the desk. \"The water was moving that day, and men can tell you exactly how and which way. Prove you understand drift, and I'll help you rule out what the current could and couldn't do.\"",
      q:[
        { q:"What puzzle did Ekman explain?", o:[
          { t:"Why wind-driven ice drifts at an angle to the wind, not straight with it.", v:"expert", fb:"Nansen's puzzle: Earth's rotation deflects wind-driven drift sideways." },
          { t:"Why the tides rise and fall twice a day at most ports around the world.", v:"wrong", fb:"Tides are gravitational; Ekman explained wind-driven drift instead." },
          { t:"Why warm water floats above cold, layering the ocean into distinct bands.", v:"partial", fb:"That is stratification; his puzzle was the sideways drift of currents." },
          { t:"Why ocean currents are random, so no drift can ever really be predicted.", v:"danger", fb:"He showed drift is orderly and predictable, set by the Earth's spin." } ] },
        { q:"What is the Ekman spiral?", o:[
          { t:"Each deeper layer deflects further, so net transport runs across the wind.", v:"expert", fb:"Layer by layer the deflection grows, turning transport across the wind." },
          { t:"A whirlpool that forms wherever two ocean currents happen to meet head-on.", v:"wrong", fb:"The spiral is a depth profile of drift, not a surface whirlpool." },
          { t:"The curved path one water parcel traces as the tide turns through a full day.", v:"partial", fb:"It describes wind-driven layers, not a tidal parcel's daily path." },
          { t:"A proof that deep water never moves, however hard the wind blows on top.", v:"danger", fb:"Deep layers do move; the spiral describes exactly how they do." } ] },
        { q:"How does Ekman's science serve this board?", o:[
          { t:"Wind and current are computable, narrowing the loss to what was done aboard.", v:"expert", fb:"Every environmental force is accountable; the unexplained shrinks to the ship." },
          { t:"It shows the current alone can roll a sound ferry over without any warning.", v:"danger", fb:"A calm current does not capsize a stable hull; the fault was aboard." },
          { t:"It shows drift is unknowable, so the water's role simply cannot be ruled out.", v:"wrong", fb:"Ekman made drift computable; the current's role can be ruled in or out." },
          { t:"It tracks debris afterward but says nothing about why she rolled at all.", v:"partial", fb:"Drift analysis helps reconstruct the casualty, part of a full accounting." } ] }
      ] },
    // cell: The Purser @ The Ferry Line's Office
    charts:{ sci:"Matthew Fontaine Maury (1806-1873)", topic:"Wind & current charts", lede:"The American naval officer, grounded by a lame leg, who mined a mountain of dusty ships' logs into the first great charts of the sea's own habits.", no:15,
      profile:"Matthew Fontaine Maury was a United States Navy officer whose seagoing career was cut short by a stagecoach accident that left him lame. Assigned instead to the Navy's Depot of Charts and Instruments, he turned a desk job into a revolution. He gathered the old logbooks of countless voyages and systematically extracted from them the winds and currents each ship had met, sorting the data by place and season. From this he produced his 'Wind and Current Charts,' which let captains choose faster, safer routes and cut weeks from long passages.\n\nIn exchange for blank logbooks to fill in on a standard form, thousands of mariners fed Maury fresh observations, an early triumph of crowd-sourced science. He organized an international conference in 1853 to standardize marine data-gathering, and in 1855 he published 'The Physical Geography of the Sea,' widely regarded as the first textbook of modern oceanography. He earned the title 'Pathfinder of the Seas' for turning scattered experience into systematic, published knowledge of the ocean.\n\nFor this inquiry, Maury embodies the principle that the sea's conditions are recorded, not secret. The winds, currents, and hazards of the Kestrel's route were charted long before she sailed; a master could know, in advance, what water and weather to expect on that passage. This starves the 'freak of nature' explanation of its oxygen. If the charts show a benign, well-traveled approach — no notorious currents, no lurking shoal, ordinary conditions on an ordinary day — then the sea did not ambush her. Maury's charts turn the environment from a suspect into a witness, and a witness that points the board's attention firmly back toward the ship and her loading.",
      frame:"The Purser lays out a route chart. \"Everything the sea does on that crossing is written down somewhere — the winds, the sets, the shoals. Show me you understand how the sea is charted, and I'll show you how ordinary that day really was.\"",
      q:[
        { q:"How did Maury make his wind and current charts?", o:[
          { t:"By mining old ships' logs for the winds and currents each voyage had met.", v:"expert", fb:"He extracted systematic data from countless logbooks — his great method." },
          { t:"By sailing every route himself and recording the weather as he went along.", v:"wrong", fb:"A lame leg kept him ashore; he mined others' logs, not his own voyages." },
          { t:"By copying older charts, adding little beyond a neater and cleaner layout.", v:"partial", fb:"He built new charts from raw log data, not by recopying old ones." },
          { t:"By guesswork, since the open ocean's conditions can never truly be recorded.", v:"danger", fb:"His whole point was that ocean conditions can be recorded and charted." } ] },
        { q:"What was 'The Physical Geography of the Sea'?", o:[
          { t:"An early textbook of oceanography, systematizing the sea's winds and currents.", v:"expert", fb:"It is widely called the first modern oceanography text — Maury's landmark." },
          { t:"A logbook of a single famous voyage around the stormy tip of South America.", v:"wrong", fb:"It was a systematic science of the sea, not one voyage's log." },
          { t:"A collection of sailors' tales, entertaining but of no scientific value at all.", v:"partial", fb:"It was rigorous, data-driven oceanography, not mere sailors' stories." },
          { t:"A claim that the sea is beyond all study, so no chart of it can be trusted.", v:"danger", fb:"Maury proved the sea can be studied and charted in fine detail." } ] },
        { q:"How do Maury's charts bear on this inquiry?", o:[
          { t:"The route's conditions were known, so a 'freak of nature' barely stands.", v:"expert", fb:"A charted, benign approach starves the act-of-God story of its oxygen." },
          { t:"They prove the approach hid a freak current able to roll almost any ship over.", v:"danger", fb:"Charts of a benign route argue against any lurking freak current." },
          { t:"They show sea conditions are unknowable, so the day's weather is a mystery.", v:"wrong", fb:"Maury made sea conditions knowable; the day can be reconstructed." },
          { t:"They fix the winds but say nothing about the currents on her approach.", v:"partial", fb:"His charts cover currents as fully as winds along a route." } ] }
      ] },
    // cell: The Purser @ The Ferry Line's Office
    forecast:{ sci:"Robert FitzRoy (1805-1865)", topic:"Weather forecasting & storm warnings", lede:"The Beagle's captain, who carried Darwin around the world and later gave the very word 'forecast' to the English language.", no:16,
      profile:"Vice-Admiral Robert FitzRoy was a British naval officer, scientist, and pioneer of meteorology, remembered first as the captain of HMS Beagle on the voyage that carried the young Charles Darwin around the world. A skilled surveyor and a devoted student of the weather, FitzRoy later founded what became the UK Meteorological Office and gave himself over to a then-radical idea: that the weather could be predicted, and lives saved by the warning.\n\nFitzRoy coined the term 'forecast,' insisting the word carried the reasoning of science, not the pretensions of prophecy. He organized a network of coastal stations that telegraphed barometer and weather readings to a central office, from which he issued the first storm warnings — hoisting cones at ports to alert ships of coming gales. He designed sturdy, accessible barometers, with printed guidance, for fishing communities. His forecasts were mocked when they failed and his work was often controversial, but he established the practice of systematic, science-based weather prediction that the modern world now takes entirely for granted.\n\nFor this inquiry, FitzRoy is the authority on what the weather was doing and whether it was foreseeable. A storm severe enough to endanger a ferry does not arrive unannounced in a well-served harbor; the barometer falls, warnings go up, other vessels take note. If the record shows calm, settled weather on the day the Kestrel rolled — no gale, no warning cone, no falling glass — then the 'freak storm' or 'sudden squall' story cannot be sustained. FitzRoy's legacy tells the board that dangerous weather leaves fingerprints in advance. Their absence is itself evidence: whatever capsized the ferry, it was not a sky that turned on her without warning.",
      frame:"The Purser turns to the barometer readings. \"If the weather meant to kill her, the glass would have said so hours before. Show me you understand forecasting, and I'll show you a barometer that never budged.\"",
      q:[
        { q:"What did FitzRoy pioneer?", o:[
          { t:"Science-based weather forecasting and the first public storm warnings.", v:"expert", fb:"He coined 'forecast' and issued the first storm warnings by telegraph." },
          { t:"The marine chronometer, which let a ship fix its longitude far from land.", v:"wrong", fb:"That was Harrison; FitzRoy's field was weather prediction." },
          { t:"A better barometer, though he doubted the weather could ever be predicted.", v:"partial", fb:"He championed prediction; the barometer was a tool toward it." },
          { t:"Weather prophecy by omen, a method no better than reading the clouds.", v:"danger", fb:"His forecasts were reasoned from data, the opposite of prophecy." } ] },
        { q:"How did FitzRoy warn ships of coming gales?", o:[
          { t:"By telegraphing readings to a center and hoisting storm cones at ports.", v:"expert", fb:"Central analysis plus port storm cones was FitzRoy's warning system." },
          { t:"By firing signal guns the moment a gale was already breaking overhead at sea.", v:"wrong", fb:"His warnings came ahead of the gale, not once it had already struck." },
          { t:"By publishing an annual almanac of the weather many months in advance.", v:"partial", fb:"He issued short-range forecasts from live data, not a yearly almanac." },
          { t:"He never warned ships; he held that gales cannot be seen coming at all.", v:"danger", fb:"Warning ships of coming gales was the whole point of his work." } ] },
        { q:"What does FitzRoy's science say about the Kestrel's weather?", o:[
          { t:"A dangerous storm leaves warning signs, so calm records exclude a freak gale.", v:"expert", fb:"No falling glass and no warning cone means no storm to blame." },
          { t:"It shows a sudden squall can rise unseen and roll a ship in a quiet harbor.", v:"danger", fb:"A dangerous squall would show on the barometer and the record first." },
          { t:"It shows weather is unforeseeable, so a freak storm cannot really be excluded.", v:"wrong", fb:"FitzRoy made weather foreseeable; its calm can be documented." },
          { t:"It fixes the wind but tells the board nothing about the state of the sea.", v:"partial", fb:"Settled weather implies a settled sea; the two go together here." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Ferry Line's Office
    gyro:{ sci:"Elmer Sperry (1860-1930)", topic:"The gyrocompass & ship stabilizer", lede:"The American inventor who tamed the spinning gyroscope into a compass that ignores the sea and a fin that fights a ship's roll.", no:17,
      profile:"Elmer Ambrose Sperry was one of America's most prolific inventors, holding hundreds of patents across electric machinery, navigation, and control. His genius was for feedback: building machines that sense their own error and correct it automatically. His fortunes and his fame came from harnessing the gyroscope — a rapidly spinning wheel that resists being tilted and points stubbornly in a fixed direction — to the practical problems of the sea and the air.\n\nSperry perfected the gyrocompass, which finds true north from the Earth's rotation rather than a magnetic field, freeing navigation from the errors that a ship's own iron introduces into a magnetic compass. He built gyroscopic autopilots and, of particular relevance here, the active gyro ship stabilizer and gyro-controlled fin systems designed to sense a ship's roll and counter it, steadying the vessel against the sea. His instruments measured and acted on a ship's motion continuously, turning the vague art of 'feeling' a ship into quantities read from dials.\n\nFor this inquiry, Sperry represents the instrumented ship: a vessel whose heading, rate of turn, and angle of roll can be sensed, recorded, and even controlled. A modern ferry's motion is not a matter of impression; it is data. That has two consequences for the board. It means the ship's behavior in her final minutes may be recoverable from her instruments, showing exactly how she heeled and when. And it underlines that roll is a measurable, manageable thing — a ship stabilized against it is a ship whose designers took her stability seriously. A vessel that rolled past recovery in calm water was not the victim of an immeasurable force, but of a stability that instruments like Sperry's could have quantified, had anyone been watching the numbers.",
      frame:"Enns thumbs the edge of a logbook. \"A ship's roll isn't a feeling — it's a number, and there are instruments that read it and even fight it. Show me you understand that, and I'll tell you what her own dials would have shown.\"",
      q:[
        { q:"What does a gyrocompass do?", o:[
          { t:"Finds true north from the Earth's spin, free of a ship's magnetic errors.", v:"expert", fb:"The gyrocompass seeks true north mechanically, immune to a ship's iron." },
          { t:"Points to magnetic north more sharply than any needle compass can manage.", v:"wrong", fb:"It ignores magnetism entirely, finding true north from rotation." },
          { t:"Keeps a steady heading only while a ship steams in a dead-straight line.", v:"partial", fb:"It holds true north through turns, not only on a straight course." },
          { t:"Predicts a coming storm by sensing the faint tremor of a distant gale.", v:"danger", fb:"A gyrocompass is a direction finder, not a weather instrument." } ] },
        { q:"What did Sperry's gyro stabilizer do?", o:[
          { t:"Sense a ship's roll and act to counter it, steadying her against the sea.", v:"expert", fb:"The active stabilizer sensed roll and fought it — Sperry's feedback genius." },
          { t:"Lock the rudder amidships so the ship could never wander off her heading.", v:"wrong", fb:"That is a steering lock; the stabilizer worked on roll, not heading." },
          { t:"Add ballast low down, a fixed weight that did nothing about the roll itself.", v:"partial", fb:"It actively countered roll rather than adding a fixed dead weight." },
          { t:"Prove a ship's roll is beyond control, so no vessel can be steadied at all.", v:"danger", fb:"Sperry's device proved roll can be measured and actively fought." } ] },
        { q:"What does Sperry's instrumented ship mean for this board?", o:[
          { t:"Roll is a number, so her stability could have been quantified, not just felt.", v:"expert", fb:"Instruments could have quantified the stability she was allowed to lose." },
          { t:"It proves only a torpedo's shock could make a roll her instruments would read.", v:"danger", fb:"Instruments read the roll of an overloaded hull with no torpedo at all." },
          { t:"It shows a ship's roll can't be measured, so her final minutes are lost to us.", v:"wrong", fb:"Sperry's whole legacy is that roll is measurable, even recordable." },
          { t:"It records her heading but reveals nothing about how far she heeled over.", v:"partial", fb:"The same instruments that hold heading also measure the angle of heel." } ] }
      ] },
    // cell: Harbor Pilot Enns @ The Ferry Line's Office
    hydrostatics:{ sci:"Blaise Pascal (1623-1662)", topic:"Hydrostatic pressure", lede:"The French prodigy who saw that a confined fluid passes on a push undiminished, and that water presses harder the deeper you go.", no:18,
      profile:"Blaise Pascal was a French mathematician, physicist, and philosopher, a prodigy who invented a mechanical calculator as a teenager and helped found probability theory before turning to religious philosophy. In physics, he made lasting contributions to the study of fluids at rest — hydrostatics — and to the understanding of atmospheric pressure, famously arranging an experiment carrying a barometer up a mountain to show that air pressure falls with height.\n\nPascal's principle states that a pressure applied to a confined, incompressible fluid is transmitted undiminished to every part of the fluid and to the walls of its container. This is the basis of the hydraulic press and every hydraulic machine: a small force on a small piston can raise a large load on a large one. He also clarified that within a fluid at rest, pressure increases with depth in proportion to the height of fluid standing above — the deeper you go, the greater the pressure — and that this pressure acts equally in all directions. The unit of pressure, the pascal, bears his name.\n\nFor this inquiry, Pascal's hydrostatics underlies the plain mechanics of a floating, and a flooding, ship. Pressure rising with depth is why a hull that sits deeper feels the sea pressing higher up her sides, and why, once her freeboard is spent, water finds and forces its way through any low opening. It is why a submerged load line means the sea now stands against openings meant to be above it. Pascal reminds the board that flooding and pressure are ordinary, lawful physics. Water rising over a deck edge and pressing in needs no explosion to admit it — only a hull loaded so deep that the sea was already standing where it should never have reached.",
      frame:"Enns taps the desk twice. \"Water presses harder the deeper down you go — load a hull too deep and the sea's standing against doors that were meant to be dry. Show me you grasp pressure, and I'll tell you where the sea got in.\"",
      q:[
        { q:"What does Pascal's principle state?", o:[
          { t:"Pressure on a confined fluid passes undiminished to every part of it.", v:"expert", fb:"A confined fluid transmits an applied pressure equally throughout — his law." },
          { t:"Pressure in a fluid acts only downward, in the direction of gravity's pull.", v:"wrong", fb:"Fluid pressure acts equally in all directions, not only downward." },
          { t:"Pressure on a fluid fades with distance from where the force was applied.", v:"partial", fb:"The pressure is transmitted undiminished, not weakened with distance." },
          { t:"Pressure in water is too erratic to follow any law that can be written down.", v:"danger", fb:"Hydrostatic pressure follows precise, simple laws Pascal set out." } ] },
        { q:"How does pressure vary within still water?", o:[
          { t:"It rises with depth, growing with the height of the water standing above.", v:"expert", fb:"Deeper means greater pressure, set by the column of water above." },
          { t:"It stays the same at every depth, since water cannot be compressed at all.", v:"wrong", fb:"Incompressibility does not make pressure uniform; depth still raises it." },
          { t:"It rises only near the surface, then holds perfectly constant far below it.", v:"partial", fb:"Pressure keeps rising steadily with depth, not just near the top." },
          { t:"It falls with depth, so the deepest water presses the least of any of it.", v:"danger", fb:"Pressure grows with depth; the deepest water presses hardest, not least." } ] },
        { q:"How does Pascal's hydrostatics bear on the Kestrel?", o:[
          { t:"A hull loaded too deep lets the sea stand against openings meant to be dry.", v:"expert", fb:"Lost freeboard puts the sea against low openings, no explosion required." },
          { t:"It proves the sea could reach her deck only through a hole torn by a blast.", v:"danger", fb:"A deep-loaded hull lets the sea reach openings with no blast at all." },
          { t:"It shows flooding is lawless, so how the water entered can't be reasoned out.", v:"wrong", fb:"Flooding follows Pascal's laws; the water's path can be reasoned out." },
          { t:"It explains her buoyancy but nothing about water pressing in through a door.", v:"partial", fb:"Rising pressure with depth is what forces water through a low door." } ] }
      ] }
  },
  STORIES:{
    bosun:{
      cardeck:"Bosun Adisa stands on the sloping vehicle deck, boots braced against the list. \"I waved every one of them aboard with my own arm, and not a soul counted or lashed a single vehicle. Show me you know what holds a hull up, and I'll tell you how many I lost track of.\"",
      bridge:"Adisa lingers by the ballast panel, uneasy among the dials. \"Down on the deck it's all muscle and rope; up here it's numbers nobody read. Prove you understand the forces, and I'll tell you which gauges were shouting.\"",
      office:"Adisa turns his cap in his hands in the paneled office. \"This is where the sailing got booked, long before I ever swung an arm. The truth's in a drawer here, not on my deck. Know your science, and I'll point you at it.\""
    },
    purser:{
      cardeck:"The Purser meets you at the foot of the ramp, clutching a folder. \"I keep the head-count and the manifest, and I can tell you both were wrong before we cast off. Show me you understand loading, and I'll show you the figure we sailed past.\"",
      bridge:"The Purser stands at the chart table, tapping the weather log. \"They'll offer you a rogue wave and a clean conscience. My records say the sea was quiet. Prove you know how orderly the water is, and I'll walk you through the log.\"",
      office:"In the office the Purser lays a hand flat on the load book. \"Everything anyone tells you at sea, I can check against paper right here. The manifests don't lie, even when people do. Earn it, and I'll open the book.\""
    },
    pilot:{
      cardeck:"Harbor Pilot Enns runs a palm along the cold hull plating. \"I boarded her at the sea buoy and felt her wrong under my feet — she rode low, marks under water. Show me you know how a hull should sit, and I'll tell you how this one didn't.\"",
      bridge:"Enns stands at the wheel he last held that night. \"She answered slow and hung on every roll, like a hull with nothing left to right her. Convince me you understand that, and I'll tell you what I felt through the deck.\"",
      office:"Enns is out of place among the ledgers, hat in hand. \"I only ever saw the last few minutes, but the reason for them was decided in a room like this. Show me you follow the physics, and I'll tell you what I reported.\""
    }
  },
  story:[
    "The <b>Kestrel</b> was a workhorse ferry on a short, familiar crossing, packed hull to rail with cars and trucks and holidaymakers on a bright, still evening. Minutes from her berth, in calm water and clear weather, she leaned, hung, and rolled all the way over, and the harbor filled with the worst kind of questions. You are <b>Investigator Mara Ostend</b>, and the Kestrel inquiry has landed on your desk with the whole port watching.",
    "<b>Three people inside will help you</b>, each holding a fragment and none the whole. <b>Bosun Adisa</b>, the deck hand who waved every vehicle aboard and knows they were never counted or lashed. <b>The Purser</b>, keeper of the manifests and the head-count, who can tell you what the sailing was booked against. And <b>Harbor Pilot Enns</b>, who boarded her at the sea buoy and felt her riding low, her marks already under water. Win their trust and they will talk.",
    "<b>Someone here is behind it.</b> Three names wait in your notepad: <b>Harmon Vell</b>, the ferry line's owner; <b>Captain Iris Sund</b>, the ship's master; and <b>the maritime surveyor</b> who signed her fit. Every column of the case — <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> truly happened — hides a tempting wrong answer. The cameras want <b>a torpedo, a mine, a deliberate attack</b>. The easy verdict wants <b>a freak rogue wave, an act of God that no one could prevent</b>. The truth is narrower than the first and graver than the second — quieter than a blast, and no accident of the sea.",
    "You have <b>8 days</b> and a single accusation to make. Name it well and a number in a loading book becomes proof; name it wrong and a real, provable failure is lost to a headline or an act of God."
  ],
  endings:{ overclaimWhat:"attack", dismissalWhat:"rogue",
    win:{
      expertTitle:"What the Load Book Proves, and No More",
      expert:["Ostend names it exactly: Harmon Vell, the ferry line's owner, who booked a sailing loaded far past what the ship could safely carry; the truth culminating in the Ferry Line's Office, where the manifests and the load book record what was put aboard and what margin was left; and a concealed loss of stability from overloading — too many vehicles, none tallied or lashed, the Kestrel sailing with her marks under water and her righting margin spent, water free to surge across the vehicle deck. Not a torpedo. Not a freak wave.",
        "Every card accounted for. Ostend worked the vehicle deck, the bridge, and the office, turned a deck hand and a purser into witnesses, and claimed precisely what the load book and the marks could defend. The board issues findings that fix how ferries are loaded and tallied — which is the entire point of doing it right."],
      soundTitle:"Right — but Lightly Proven",
      sound:["Ostend names the right three — Vell, the Ferry Line's Office, and a concealed loss of stability from overloading. The shape of the case is correct, and the refusal to cry sabotage or shrug at an act of God is exactly right.",
        "But too many threads were left loose, and Vell's lawyers will pull at them. A few more days pinning the manifest to the marks and the missing tally would have made the finding unassailable. Close and honest, if not yet airtight."],
      namedTitle:"The Right Answer, Unearned",
      named:["Ostend names the truth — Vell, the office, the stability lost to overloading — but gathered too little to back it. It reads like a hunch that happened to land.",
        "The board cannot rewrite how a fleet is loaded on an accusation this thin, however correct. Being right is not the same as being able to prove it to the people who will fight the finding."]
    },
    overclaim:{ title:"The Board That Cried Torpedo",
      body:["Ostend reports a torpedo, a mine, a deliberate attack — the answer the cameras were already broadcasting. It is vivid, and it is not what the evidence shows.",
        "There was no blast, no breach, no scorch or shattered plating — only a hull that rode too low, a righting margin already spent, and water running free across an open vehicle deck until she rolled. When the attack story collapses, it takes credibility with it, and the real, provable failure is dismissed as just another conspiracy theory. The only weapon aboard was a loading book no one was willing to read."] },
    dismissal:{ title:"Case Closed on the Sea",
      body:["Ostend files it as a freak rogue wave, an act of God, nothing anyone could have prevented, and closes the file. It is comforting and it is wrong.",
        "The weather was calm, the barometer never moved, the tides and currents were charted and ordinary, and no other vessel felt a thing — while the Kestrel sailed with her marks under water and her stability given away in the loading. Blaming the sea leaves the real fault in place: a ferry line free to overload the next sailing exactly as it overloaded this one. The board saw a wave that was never there and never the number in the book."] },
    wrongNames:{ title:"So Close",
      body:["Ostend has the nature of it cold — a concealed loss of stability from overloading, too many vehicles and too little margin, neither a torpedo nor a freak wave. But the finger lands on the wrong name or the wrong room."] } },
}};