// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"volcano", title:"The Halcyon Caldera", discipline:"Volcanology & Seismology",
  teaser:"The mountain above the town is stirring. Do you evacuate — and risk crying wolf — or trust the official 'all clear'?", overclaimTag:"an imminent apocalypse", truthTag:"a real, uncertain hazard being downplayed",
  venue:"the Halcyon Volcano Observatory", agent:{name:"Dr. Nils Aakre", role:"Investigator's Notepad"},
  standingLabel:"Scientific standing", readingShort:"Pioneers", readingLabel:"Earth-Science Pioneers",
  dossierName:"EARTH-SCIENCE PIONEERS", enterLabel:"Enter the observatory", subt:"A deduction game inside the Halcyon eruption crisis", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the headline that ends the world: the evidence points not to a supereruption, but to whatever the mountain is actually saying. Proving that — in time — is the job.",
  CATS:{
    who:{ title:"Who is behind it", truth:"mayor", items:[
      {id:"director", label:"The observatory director"},
      {id:"geologist", label:"Dr. Sasi — field geologist"},
      {id:"mayor", label:"Mayor Holt — civil-protection chief"} ]},
    where:{ title:"Where it culminates", truth:"town", items:[
      {id:"summit", label:"The Summit & Crater"},
      {id:"station", label:"The Monitoring Station"},
      {id:"town", label:"The Town & Evacuation Zone"} ]},
    what:{ title:"What is happening", truth:"hazard", items:[
      {id:"apocalypse", label:"A civilization-ending supereruption"},
      {id:"allclear", label:"Nothing — harmless steam, all clear"},
      {id:"hazard", label:"A real, imminent, survivable-if-you-act hazard, downplayed"} ]}
  },
  PLACES:{
    summit:{name:"The Summit & Crater", xy:[140,90]},
    station:{name:"The Monitoring Station", xy:[330,240]},
    town:{name:"The Town & Evacuation Zone", xy:[520,90]}
  },
  EDGES:[["summit","station"],["station","town"]],
  CHARACTERS:{
    guide:{ name:"Guide Rún", role:"Mountain guide", face:"⛰", badge:"G", legend:"the summit", hint:"Knows the mountain's moods; smells the sulfur changing." },
    seismo:{ name:"The Seismologist", role:"Duty seismologist", face:"📈", badge:"S", legend:"the station", hint:"Watches the drums; the tremor pattern has changed and no one's listening." },
    warden:{ name:"Warden Cole", role:"Evacuation warden", face:"🚨", badge:"E", legend:"the town", hint:"Runs the drills; caught between the science and the mayor's office." }
  },
  TOPICMAP:{
    summit:{ guide:["platetectonics","seismicwaves"], seismo:["magnitude","intensity"], warden:["innercore","seafloor"] },
    station:{ guide:["magma","vei"], seismo:["pyroclastic","lahar"], warden:["gas","tremor"] },
    town:{ guide:["forecasting","hotspot"], seismo:["calderas","tsunami"], warden:["paleomag","monitoring"] }
  },
  TOPICS:{
    // cell: Guide Rún @ The Summit & Crater
    platetectonics:{ sci:"Alfred Wegener (1880-1930)", topic:"Plate tectonics & continental drift", lede:"The meteorologist who saw the continents adrift and was mocked for a lifetime before the deep sea proved him right.", no:1,
      profile:"Alfred Wegener was a German meteorologist and polar explorer who, in 1912, dared to propose that the continents were not fixed but had drifted apart from a single ancestral landmass he later called Pangaea. He built his case in 'The Origin of Continents and Oceans' (1915): the jigsaw fit of Africa and South America, matching fossils and rock strata split across whole oceans, and glacial scars stranded in now-tropical lands.\n\nHis critics savaged him. Wegener could name no force strong enough to shove a continent through solid seafloor, and geologists resented a weatherman trespassing in their field. He died in 1930 on the Greenland ice sheet, still unvindicated, his idea in exile.\n\nVindication came decades later. Seafloor spreading and paleomagnetism supplied the missing engine: continents do not plow through the ocean floor — they ride atop plates of lithosphere made at ridges and destroyed at trenches, dragged by the slow churn of the mantle. Modern plate tectonics folded drift into one coherent theory, and the mockery turned to belated honor.\n\nNearly every volcano and earthquake on Earth clusters along plate boundaries — the Pacific 'Ring of Fire' burns because plates dive beneath one another there and melt into magma. For this inquiry, Wegener's story carries two warnings. First, a mountain in a tectonically active setting is doing exactly what such mountains do; unrest is not proof of an apocalypse. Second, a correct reading of the evidence can be buried for a lifetime by people invested in the settled story. Learning why a volcano sits where it does is the first step to telling ordinary restlessness from a genuine, gathering threat — and to refusing both the panic and the shrug.",
      frame:"Rún raps the rock face with a gloved knuckle. \"Flatlanders think this mountain is furniture. It isn't. It's here for a reason, and it moves. Before I trust you above the treeline, show me you know the ground you stand on:\"",
      q:[
        { q:"What was Wegener's central claim about the continents?", o:[
          { t:"That the continents drifted apart from one ancient supercontinent.", v:"expert", fb:"Exactly — a single Pangaea that fragmented and dispersed over geologic time." },
          { t:"That the continents had always sat fixed exactly where we find them.", v:"wrong", fb:"That was the orthodoxy Wegener attacked; the continents have plainly moved." },
          { t:"That the continents were slowly sinking beneath a rising world ocean.", v:"wrong", fb:"Drift is lateral motion of plates, not a global drowning of the land." },
          { t:"That the whole Earth was steadily expanding and cracking the crust.", v:"danger", fb:"Earth-expansion was a rival fringe idea; plate tectonics, not growth, moves continents." } ] },
        { q:"Why did geologists reject continental drift for so long?", o:[
          { t:"Because the matching coastlines and fossils were later shown to be forgeries.", v:"wrong", fb:"The evidence was real and never faked; the objection was mechanical, not factual." },
          { t:"Because Wegener could not name a force able to move a whole continent.", v:"expert", fb:"Right — the missing engine, mantle-driven plates, arrived only decades later." },
          { t:"Because no earthquakes or volcanoes had yet been found anywhere on Earth.", v:"wrong", fb:"Quakes and volcanoes were well known; their pattern later confirmed the boundaries." },
          { t:"Because the continents were proven to be far too light to ever move.", v:"wrong", fb:"Weight was never the sticking point; the absent driving mechanism was." } ] },
        { q:"Why do most volcanoes cluster where they do?", o:[
          { t:"They are spread at random, so any peak is as dangerous as any other.", v:"danger", fb:"Volcanism is not random; it concentrates along plate boundaries and hotspots." },
          { t:"They form only where ancient meteor craters happened to punch the crust.", v:"wrong", fb:"Impact craters are not the source; subduction and rifting feed most volcanoes." },
          { t:"They sit along plate boundaries where crust is made, split, or subducted.", v:"expert", fb:"Yes — the Ring of Fire traces subduction zones around the Pacific plate." },
          { t:"They appear wherever the ocean is deepest and the water pressure greatest.", v:"wrong", fb:"Depth alone does not make magma; plate geometry and melting do." } ] }
      ] },
    // cell: Guide Rún @ The Summit & Crater
    seismicwaves:{ sci:"Richard Dixon Oldham (1858-1936)", topic:"P & S waves", lede:"The surveyor of Indian earthquakes who first read the three separate pulses in a quake — and used them to find the Earth's core.", no:2,
      profile:"Richard Dixon Oldham was a British geologist who spent his career with the Geological Survey of India, where the great 1897 Assam earthquake gave him a natural laboratory. Sifting the seismograms, he showed in 1900 that a distant quake arrives not as one jolt but as an ordered sequence of distinct wave types — a breakthrough that turned the seismograph from a curiosity into an instrument for X-raying the planet.\n\nThe first arrivals are P waves, or primary waves: fast, compressional pushes that squeeze and stretch the rock along their path, like sound moving through the ground. They travel through solids and liquids alike. Behind them come the slower S waves, or secondary waves, which shake the rock sideways; crucially, shear waves cannot pass through a liquid at all. Last and most destructive are the surface waves that roll along the ground and do most of the damage to buildings.\n\nOldham's masterstroke came in 1906, when he noticed that S waves failed to emerge on the far side of the planet, leaving a 'shadow zone.' The only explanation was a large liquid region at the center — the first seismic evidence for Earth's core. He had learned to see the planet's hidden interior by the way its waves arrived and, tellingly, by the ones that never did.\n\nFor volcano monitoring, the P–S interval is the everyday ruler. The gap between the fast P and the slower S arrival grows with distance, so it tells an analyst how far off a quake was, and clusters of small quakes creeping upward beneath a volcano can trace magma on the move. Reading the waves lets you distinguish a deep tectonic rumble from shallow, rising unrest — the difference between a mountain merely grumbling and one actively loading for an eruption.",
      frame:"Rún watches a distant rockfall smoke off a ridge. \"The mountain talks in tremors, and most people only hear noise. If you can tell one kind of shaking from another, maybe you'll hear what I hear:\"",
      q:[
        { q:"How do P waves differ from S waves?", o:[
          { t:"P waves are compressional and faster; S waves shear and arrive later.", v:"expert", fb:"Right — P is the push-pull first arrival, S the slower sideways shear." },
          { t:"P waves only travel on the surface; S waves only travel deep inside.", v:"wrong", fb:"Both are body waves; surface waves are a separate, later-arriving type." },
          { t:"P waves are always harmless while S waves alone can level a whole city.", v:"danger", fb:"Surface waves usually do the worst damage; both body waves are diagnostic, not doom." },
          { t:"P waves carry heat through the rock while S waves carry only the sound.", v:"wrong", fb:"Neither transports heat; both are elastic waves differing in motion and speed." } ] },
        { q:"What did the S-wave shadow zone reveal about the Earth?", o:[
          { t:"That the planet is completely solid and uniform all the way down.", v:"wrong", fb:"The opposite — a blocked wave revealed a large region that is not solid." },
          { t:"That a large liquid core lies at the center, blocking the shear waves.", v:"expert", fb:"Yes — S waves cannot cross liquid, so their absence mapped the outer core." },
          { t:"That the Earth is hollow, letting the waves pass clean through the middle.", v:"danger", fb:"A hollow Earth is a myth; the shadow marks a dense liquid core, not a void." },
          { t:"That earthquakes only ever happen on one single side of the planet.", v:"wrong", fb:"Quakes occur worldwide; the shadow is about wave paths, not quake location." } ] },
        { q:"Why is the gap between P and S arrivals useful at a volcano?", o:[
          { t:"The interval widens with distance, so it tells you how far the quake was.", v:"expert", fb:"Correct — timing the P–S gap locates quakes and tracks rising magma swarms." },
          { t:"The gap reveals the silica content and chemical makeup of the erupting lava.", v:"wrong", fb:"Composition comes from samples and gases, not from the P–S timing." },
          { t:"A wide gap always proves a world-ending supereruption is hours away.", v:"danger", fb:"The gap measures distance, not doom; it never forecasts an apocalypse." },
          { t:"The interval sets the precise calendar date the volcano will erupt.", v:"wrong", fb:"No single interval fixes a date; forecasting needs many converging signals." } ] }
      ] },
    // cell: The Seismologist @ The Summit & Crater
    magnitude:{ sci:"Charles Richter (1900-1985)", topic:"Earthquake magnitude", lede:"The Caltech physicist whose name became shorthand for a whole planet's shaking — a scale he built to compare quakes fairly.", no:3,
      profile:"Charles Richter was an American seismologist at Caltech who, in 1935 with his colleague Beno Gutenberg, devised the first quantitative measure of an earthquake's size. Before it, quakes were ranked only by the damage they caused, which depended as much on where people lived as on the event itself. Richter wanted a number that belonged to the quake, not the town.\n\nBorrowing the idea of a logarithmic 'stellar magnitude' scale from astronomy, he defined local magnitude from the largest wave amplitude on a standard seismograph, corrected for distance. Because it is logarithmic, each whole step is a tenfold jump in amplitude and roughly a 32-fold jump in released energy: a magnitude 6 is not slightly larger than a 5 but dramatically so. The scale has no ceiling and no floor, though the Earth's rocks set practical limits on the largest possible quakes.\n\nModern seismology has largely replaced the original 'Richter scale' with the moment magnitude scale, which is tied to the physical area of fault rupture and slip and does not saturate for the very largest events. But Richter's core insight endures: one instrument-based number lets you compare a tremor beneath a volcano with a great subduction quake on the far side of the world.\n\nFor this investigation, magnitude is a tool for proportion, and proportion is everything. Beneath a restless volcano the telling signal is usually not one enormous quake but a rising swarm of small ones as magma forces rock apart. A cluster of magnitude-2 and magnitude-3 events is easy to wave away as trivial — yet their number, depth, and upward march can matter far more than their modest size. Knowing what magnitude does and does not mean guards against both crying catastrophe and dismissing a real climb.",
      frame:"The seismologist jabs a pen at the paper drum. \"Everyone throws the word 'magnitude' around and nobody knows what it means. It's the first thing I need you to get right, so tell me:\"",
      q:[
        { q:"What does an earthquake's magnitude measure?", o:[
          { t:"The size of the quake at its source, on a single instrument-based scale.", v:"expert", fb:"Right — magnitude belongs to the quake itself, independent of where you feel it." },
          { t:"How badly a particular town's buildings were damaged by the ground shaking.", v:"danger", fb:"That is intensity, not magnitude; damage depends on distance and buildings." },
          { t:"The number of separate aftershocks that will follow the main event.", v:"wrong", fb:"Aftershock counts are a different statistic; magnitude sizes a single quake." },
          { t:"The precise depth in kilometers at which the rupture first began.", v:"wrong", fb:"Depth is located separately; magnitude quantifies the energy released." } ] },
        { q:"The scale is logarithmic. What does one whole step mean?", o:[
          { t:"Each step adds a fixed, small amount of shaking, the same at every level.", v:"wrong", fb:"No — logarithmic steps multiply, so higher magnitudes leap in size." },
          { t:"Each step is a tenfold jump in amplitude and far more released energy.", v:"expert", fb:"Yes — one unit is ten times the amplitude and roughly 32 times the energy." },
          { t:"Each step doubles the distance the waves can travel across the globe.", v:"wrong", fb:"Steps scale wave size, not travel distance; range depends on paths, not magnitude." },
          { t:"Each step guarantees the next quake will end all life on the planet.", v:"danger", fb:"Magnitude has practical limits; no ordinary step means an extinction event." } ] },
        { q:"Beneath a restless volcano, which signal matters most?", o:[
          { t:"A single giant quake, since only one huge shock can ever precede lava.", v:"danger", fb:"Eruptions are usually heralded by swarms of small quakes, not one giant." },
          { t:"A rising swarm of small quakes climbing upward as magma forces rock apart.", v:"expert", fb:"Correct — number, depth, and upward march can outweigh any single magnitude." },
          { t:"Total silence on the drums, which always proves the danger has passed.", v:"danger", fb:"Silence can mask a sealed conduit; quiet is not the same as safe." },
          { t:"One distant tectonic quake striking hundreds of kilometers from the volcano.", v:"wrong", fb:"A far tectonic event says little about the magma directly beneath the vent." } ] }
      ] },
    // cell: The Seismologist @ The Summit & Crater
    intensity:{ sci:"Giuseppe Mercalli (1850-1914)", topic:"Intensity vs magnitude", lede:"The Italian priest-volcanologist who ranked earthquakes by what they actually did to people, streets, and walls.", no:4,
      profile:"Giuseppe Mercalli was an Italian priest, volcanologist, and seismologist who taught in Naples in the shadow of Vesuvius. In the early 1900s he refined the scale that still bears his name — a way of ranking an earthquake not by its energy at the source but by its observed effects at a given place: what people felt, how furniture moved, whether plaster cracked, chimneys fell, or buildings collapsed.\n\nThis is intensity, and it differs fundamentally from magnitude. A single earthquake has one magnitude but many intensities — high near the epicenter and fading with distance. Intensity depends on the local geology, the depth of the quake, and above all on how well the buildings are built. A modest quake beneath a town of unreinforced masonry can be devastating, while a far larger quake in open country may barely rate. The modern Modified Mercalli scale runs in Roman numerals from I (barely detectable) to XII (total destruction).\n\nMercalli was above all a student of volcanoes, cataloguing eruptions of Vesuvius, Etna, and Stromboli, and he died in 1914 in a fire in his home. His scale endures because it captures the thing that actually matters to the people on the ground: not an abstract number, but harm.\n\nFor this inquiry, the magnitude–intensity distinction is a shield against two errors. Officials eager to reassure will cite a small magnitude to prove there is 'nothing to worry about' — while ignoring that a shallow quake under a vulnerable town can still bring down walls and block escape roads. Officials or headlines eager to panic may inflate local shaking into proof of catastrophe. Intensity keeps the focus where it belongs: on exposure and vulnerability, on who and what lies in harm's way, which is exactly the question an evacuation must answer.",
      frame:"\"Magnitude is the physicist's number,\" the seismologist says, \"but Mercalli asked the human question — what did it do to the houses? Answer me in his terms:\"",
      q:[
        { q:"How does intensity differ from magnitude?", o:[
          { t:"Intensity rates a quake's local effects; magnitude sizes the source once.", v:"expert", fb:"Right — one magnitude, but many intensities that fade with distance." },
          { t:"Intensity and magnitude are simply two names for the very same single number.", v:"wrong", fb:"They are distinct: one measures effects felt, the other energy released." },
          { t:"Intensity is always larger than magnitude for every earthquake on record.", v:"wrong", fb:"They are different scales entirely and are not simply larger or smaller." },
          { t:"Intensity measures the source energy while magnitude counts the damage.", v:"wrong", fb:"That reverses them: magnitude is the source, intensity the observed effect." } ] },
        { q:"Why can a small-magnitude quake still be dangerous to a town?", o:[
          { t:"It cannot; below a set magnitude every quake is completely harmless.", v:"danger", fb:"A shallow small quake under weak buildings can still cause real harm." },
          { t:"A shallow quake under weak buildings brings high intensity where people live.", v:"expert", fb:"Yes — depth, geology, and building quality drive the harm, not magnitude alone." },
          { t:"Because small quakes secretly carry more total energy than large ones.", v:"wrong", fb:"They carry less energy; the harm comes from proximity and vulnerability." },
          { t:"Because even small quakes always trigger a world-ending eruption within hours.", v:"danger", fb:"A small quake does not doom the world; its local intensity is the real concern." } ] },
        { q:"Why does the intensity concept matter to an evacuation call?", o:[
          { t:"It keeps the focus on exposure — who and what lies in the hazard's path.", v:"expert", fb:"Correct — evacuation is about harm to people, exactly what intensity captures." },
          { t:"It proves evacuations are never justified for any earthquake at all.", v:"danger", fb:"Intensity can justify evacuation precisely because it measures real local harm." },
          { t:"It lets officials replace field surveys with a single laboratory reading.", v:"wrong", fb:"Intensity is built from ground observations, not a lone lab measurement." },
          { t:"It fixes the precise minute the shaking will reach the town square.", v:"wrong", fb:"Intensity describes effects, not arrival times; it forecasts no exact minute." } ] }
      ] },
    // cell: Warden Cole @ The Summit & Crater
    innercore:{ sci:"Inge Lehmann (1888-1993)", topic:"Earth's interior", lede:"The Danish seismologist who found a solid heart inside the molten core — and worked on to the age of 104.", no:5,
      profile:"Inge Lehmann was a Danish seismologist and one of the great interpreters of the planet's hidden interior. In a famously terse 1936 paper titled simply 'P'', she resolved a puzzle in earthquake records: certain P waves were arriving inside the supposed core shadow, where the liquid outer core should have bent them away. Her explanation was elegant and correct — a distinct, solid inner core at the very center, reflecting and refracting waves in a way a wholly liquid core could not.\n\nThe boundary she identified is now called the Lehmann discontinuity, and it completed the layered picture of the Earth: a thin rocky crust, a thick solid-but-slowly-flowing mantle, a liquid iron outer core whose churning generates the magnetic field, and a solid iron inner core kept solid by immense pressure despite temperatures rivaling the Sun's surface. Lehmann built all of this from the arrival times of waves on paper seismograms, sorted by hand into cardboard boxes.\n\nShe had a long career against considerable headwinds for a woman in her era, remained scientifically active for decades, and lived to 104. A colleague marveled that she deduced the inner core 'with a black box whose contents were earthquakes' — and nothing more.\n\nHer work matters to this inquiry as a model of inference. Lehmann never saw the inner core; she read it from the pattern of signals that reached her instruments. A volcano investigator works the same way, reconstructing an unseen magma system from quakes, gas, and ground swelling. Her example warns against two failures: dismissing an anomaly because it is inconvenient, and over-reading it into fantasy. The right response to a strange signal is to ask, patiently, what hidden structure would produce exactly this — no more, and no less.",
      frame:"Warden Cole unrolls a cross-section of the mountain. \"I run drills for a thing nobody can see. Lehmann never saw the core either — she reasoned it out. Show me you can reason about what's under our feet:\"",
      q:[
        { q:"What did Inge Lehmann discover in 1936?", o:[
          { t:"That a solid inner core sits within the liquid outer core, bending P waves.", v:"expert", fb:"Right — the P' arrivals in the shadow zone revealed a solid center." },
          { t:"That the Earth's center is a vast, echoing empty cavern with no core at all.", v:"danger", fb:"A hollow center is a myth; she showed a solid inner core, not a void." },
          { t:"That the entire core, inner and outer alike, is completely molten.", v:"wrong", fb:"She proved the inner part is solid, distinct from the liquid outer core." },
          { t:"That the mantle, not the core, is the source of all earthquakes.", v:"wrong", fb:"Her work located the inner core; it was not about the origin of quakes." } ] },
        { q:"Which layers make up the Earth from surface to center?", o:[
          { t:"Crust, then a single uniform layer of molten rock down to the middle.", v:"wrong", fb:"There are several distinct layers, not one molten mass beneath the crust." },
          { t:"Crust, mantle, liquid outer core, and solid inner core, in order.", v:"expert", fb:"Correct — a rocky mantle over a liquid then solid iron core." },
          { t:"A thin crust wrapped directly around a giant hollow ball of gas.", v:"danger", fb:"There is no hollow gas ball; dense iron, liquid then solid, fills the center." },
          { t:"Crust, then water all the way down to a small pebble at the core.", v:"wrong", fb:"The interior is rock and iron under pressure, not a deep global ocean." } ] },
        { q:"What is the lesson of Lehmann's method for a volcano inquiry?", o:[
          { t:"Reconstruct the unseen system patiently from the signals it actually sends.", v:"expert", fb:"Yes — infer the hidden magma system from quakes, gas, and swelling, no more." },
          { t:"Ignore any strange signal, since anomalies are always instrument errors.", v:"danger", fb:"Dismissing inconvenient anomalies is exactly the failure her work warns against." },
          { t:"Treat one odd reading as instant proof the whole world will soon end.", v:"danger", fb:"Over-reading a single anomaly into apocalypse is the opposite of her patience." },
          { t:"Wait until the eruption happens before drawing any conclusion at all.", v:"wrong", fb:"The point is to infer structure in advance from signals, not to wait for disaster." } ] }
      ] },
    // cell: Warden Cole @ The Summit & Crater
    seafloor:{ sci:"Harry Hess (1906-1969)", topic:"Seafloor spreading", lede:"The Navy captain who used his warship's sonar to find the engine that finally proved the continents move.", no:6,
      profile:"Harry Hess was an American geologist and a U.S. Navy officer whose wartime command let him run his ship's echo-sounder continuously across the Pacific. The profiles he gathered revealed a seafloor far stranger than expected: great mid-ocean mountain ranges, deep trenches, and curious flat-topped drowned volcanoes he named guyots. After the war, as a Princeton professor, he assembled these clues into a mechanism that had eluded Wegener.\n\nIn his 1962 paper 'History of Ocean Basins,' Hess proposed seafloor spreading. Hot mantle rises beneath the mid-ocean ridges, erupts as new basaltic crust, and spreads outward like a slow conveyor belt; far away, old ocean floor bends down into the trenches and is consumed back into the mantle. The continents do not plow through the seafloor, as critics had demanded — they ride passively on top of it. Hess candidly called his paper 'an essay in geopoetry,' aware he was ahead of the proof.\n\nThe proof came within a few years, when magnetic stripes on the seafloor were found to be symmetric mirror images on either side of the ridges, recording reversals of Earth's magnetic field as the new crust cooled. That symmetry was spreading made visible, and it turned drift into the settled science of plate tectonics.\n\nFor this investigation, Hess embodies how a hidden process becomes undeniable once the right measurement is made. The magma feeding a volcano is part of the same planetary engine: melt rising, cooling, and building landforms. His story also cautions the reassurers — 'nothing is happening' is a claim about a system you cannot see directly, and the seafloor looked quiet for centuries while it was, in fact, endlessly moving. Absence of an obvious sign is not evidence of calm.",
      frame:"Cole taps a bathymetric chart pinned to the wall. \"People think what they can't see isn't moving. Hess proved the whole ocean floor was on the move the entire time. Convince me you grasp how:\"",
      q:[
        { q:"What is seafloor spreading?", o:[
          { t:"New crust forms at mid-ocean ridges and spreads outward like a conveyor.", v:"expert", fb:"Right — melt rises at ridges, cools into crust, and is consumed at trenches." },
          { t:"The seafloor is rigid, fixed and unmoving, exactly as the old textbooks taught.", v:"wrong", fb:"Hess showed the opposite: the floor is created and destroyed continuously." },
          { t:"The oceans are steadily draining down into a single crack in the crust.", v:"wrong", fb:"Spreading is about crust, not water; the oceans are not draining away." },
          { t:"The entire seafloor is about to flip over and drown every coastline.", v:"danger", fb:"No flip is coming; spreading is a slow, steady conveyor of new crust." } ] },
        { q:"What finally confirmed seafloor spreading?", o:[
          { t:"Symmetric magnetic stripes mirrored on both sides of the ocean ridges.", v:"expert", fb:"Yes — matched magnetic reversals recorded spreading as it happened." },
          { t:"A single deep-ocean borehole that reached and photographed the Earth's core.", v:"wrong", fb:"No drill has reached the core; the proof was magnetic seafloor stripes." },
          { t:"Eyewitness sailors who watched new continents surface overnight.", v:"danger", fb:"Continents do not surface overnight; the confirmation was magnetic symmetry." },
          { t:"The discovery that the seafloor is uniformly the same age everywhere.", v:"wrong", fb:"Seafloor age varies — young at ridges, old at trenches — which supports spreading." } ] },
        { q:"What does Hess's story warn a reassuring official against?", o:[
          { t:"Assuming a system is calm just because no obvious sign is showing.", v:"expert", fb:"Correct — the seafloor looked still for centuries while endlessly moving." },
          { t:"Ever trusting any instrument reading taken out on the open ocean.", v:"wrong", fb:"His whole case was built on trusting careful sonar measurements." },
          { t:"Believing that any hidden geologic process can ever be proven at all.", v:"wrong", fb:"He showed hidden processes can be proven once the right data are gathered." },
          { t:"Warning the public before a guaranteed planetary catastrophe strikes.", v:"danger", fb:"The lesson is about unseen motion, not a looming planetary catastrophe." } ] }
      ] },
    // cell: Guide Rún @ The Monitoring Station
    magma:{ sci:"Norman L. Bowen (1887-1956)", topic:"Magma, silica & viscosity", lede:"The Canadian who melted rocks in the lab to learn the order in which a cooling magma crystallizes.", no:7,
      profile:"Norman L. Bowen was a Canadian petrologist who, at the Geophysical Laboratory in Washington, turned igneous geology into an experimental science. By melting rock and letting it crystallize under controlled conditions, he worked out the sequence in which minerals form as a magma cools — the celebrated 'Bowen's reaction series,' published in his 1928 book 'The Evolution of the Igneous Rocks.' It explained how a single parent magma can differentiate into a whole family of rock types.\n\nThe practical heart of his work, for a volcanologist, is what controls a magma's viscosity — its resistance to flow. The master variable is silica content. Silica-poor magmas, like the basalt of Hawaii, are hot and runny; their gas escapes easily and they tend to erupt effusively as flowing lava. Silica-rich magmas, like andesite and rhyolite, are stiff and sticky; dissolved gas cannot escape and pressure builds until the magma shatters itself in a violent explosion. Temperature and dissolved water also matter, but silica sets the basic style.\n\nThis single principle largely determines whether a volcano oozes or blasts. A stiff, gas-charged, silica-rich system is the recipe for explosive eruptions, pyroclastic flows, and towering ash columns; a fluid basaltic system usually produces spectacular but far less lethal lava fountains and flows.\n\nFor this inquiry, magma chemistry is the key to proportion. Knowing the composition of a volcano's magma tells you what kind of eruption is physically plausible. It lets you reject the fantasy that any restless peak might unleash a civilization-ending blast, while also refusing the comfortable lie that stiff, gassy magma is 'just steam.' The rock itself, read through Bowen's chemistry, sets the realistic envelope of danger — usually neither apocalypse nor nothing, but a hazard with a specific, knowable character.",
      frame:"Rún pockets a chunk of pale, glassy rock and turns it over. \"This one's sticky stuff, not the runny black kind. The mountain's mood is written in its chemistry. Read it for me:\"",
      q:[
        { q:"What most controls a magma's viscosity?", o:[
          { t:"Its silica content — more silica makes a stiffer, more explosive magma.", v:"expert", fb:"Right — silica-rich magma is sticky and traps gas; silica-poor is runny." },
          { t:"Its color alone, since only dark magmas are ever able to flow at all.", v:"wrong", fb:"Color hints at composition but silica content is what governs viscosity." },
          { t:"The phase of the moon and its tides at the exact moment the eruption begins.", v:"danger", fb:"Tides are negligible here; silica and temperature set how magma flows." },
          { t:"The total age of the volcano, measured from its very first eruption.", v:"wrong", fb:"A volcano's age does not fix viscosity; magma chemistry does." } ] },
        { q:"Why do silica-rich magmas erupt more explosively?", o:[
          { t:"Because they are stiff, so trapped gas builds pressure until it shatters them.", v:"expert", fb:"Yes — gas cannot escape sticky magma, so it fragments violently." },
          { t:"Because they are so runny that gas escapes gently and quietly every time.", v:"wrong", fb:"That describes low-silica basalt; silica-rich magma traps its gas instead." },
          { t:"Because they contain no dissolved gas whatsoever to drive an eruption.", v:"wrong", fb:"They hold plenty of gas; the problem is the gas cannot get out." },
          { t:"Because any silica-rich magma is guaranteed to destroy the whole planet.", v:"danger", fb:"Explosive is not planet-ending; eruption size still depends on volume and setting." } ] },
        { q:"How does knowing the magma type sharpen a hazard call?", o:[
          { t:"It sets the realistic envelope of what kind of eruption is possible.", v:"expert", fb:"Correct — chemistry bounds the plausible, rejecting both apocalypse and 'just steam'." },
          { t:"It proves any restless volcano can unleash a civilization-ending blast.", v:"danger", fb:"Chemistry usually rules that fantasy out; most systems have a knowable ceiling." },
          { t:"It shows that stiff, gas-charged magma is really just harmless steam.", v:"danger", fb:"Stiff gassy magma is the explosive kind; calling it steam is the dismissal trap." },
          { t:"It reveals the precise hour the next eruption is certain to begin.", v:"wrong", fb:"Chemistry sets the style, not the timing; forecasts need monitoring too." } ] }
      ] },
    // cell: Guide Rún @ The Monitoring Station
    vei:{ sci:"Christopher Newhall (volcanologist)", topic:"Eruption size & the VEI", lede:"The USGS scientist who gave eruptions a common yardstick, so a hiccup and a catastrophe stop being confused.", no:8,
      profile:"Christopher Newhall is an American volcanologist, long with the U.S. Geological Survey, who in 1982 with Stephen Self created the Volcanic Explosivity Index, or VEI. Just as earthquakes needed a magnitude scale, eruptions needed one number to compare a small Hawaiian lava fountain with a continent-shaking blast. The VEI supplied it, drawing mainly on the volume of erupted material and the height of the eruption column, with the plume reaching into the stratosphere at the higher levels.\n\nThe scale runs from 0 to 8. It is logarithmic above the lowest steps, so each unit roughly represents a tenfold increase in erupted volume. A VEI 0–1 is a gentle effusive eruption; a VEI 3 is a substantial explosive event; the 1980 Mount St. Helens blast was a VEI 5; the 1991 Pinatubo eruption a VEI 6; and only a handful of prehistoric 'supereruptions,' such as Yellowstone and Toba, reach VEI 8. Crucially, the very large events are extraordinarily rare, separated by tens of thousands of years.\n\nNewhall spent much of his career on eruption forecasting and on communicating risk to the public and to officials, including work around Pinatubo, whose successful evacuation saved many thousands of lives.\n\nFor this inquiry, the VEI is the antidote to the false choice between apocalypse and nothing. It shows that eruptions occupy a broad spectrum, and that the overwhelmingly most likely events at a given volcano are modest ones — dangerous locally, but far from civilization-ending. Invoking a VEI 8 supereruption to frighten a resort town is almost always statistically absurd; but so is treating a plausible VEI 3 or 4, which can devastate a valley, as if it were nothing. The scale keeps the conversation honest and proportionate.",
      frame:"Rún flips through a chart of past blasts. \"There's a whole ladder between a burp and the end of the world, and most people only know the top rung. Show me you can place an eruption on it:\"",
      q:[
        { q:"What does the Volcanic Explosivity Index mainly measure?", o:[
          { t:"The size of an eruption, from erupted volume and column height.", v:"expert", fb:"Right — the VEI compares eruptions by volume and plume height." },
          { t:"The exact chemical formula of the lava produced by the eruption.", v:"wrong", fb:"Composition is a separate matter; the VEI captures explosive size." },
          { t:"The precise number of people that a given eruption is sure to kill.", v:"wrong", fb:"Casualties depend on exposure and warning, not directly on the VEI." },
          { t:"The exact number of years until the volcano's very next eruption.", v:"wrong", fb:"The VEI sizes an eruption; it does not forecast timing." } ] },
        { q:"How common are the largest VEI 7–8 supereruptions?", o:[
          { t:"Extremely rare, separated by many tens of thousands of years apart.", v:"expert", fb:"Yes — VEI 8 events are vanishingly rare on any human timescale." },
          { t:"Routine — most volcanoes produce a VEI 8 blast every few decades.", v:"danger", fb:"Far from routine; supereruptions are among Earth's rarest events." },
          { t:"They are physically impossible and have never once happened at all.", v:"wrong", fb:"They have happened — Toba, Yellowstone — but exceedingly seldom." },
          { t:"They occur on a strict schedule that lets us predict the exact year.", v:"wrong", fb:"There is no fixed schedule; large eruptions are rare and irregular." } ] },
        { q:"How does the VEI guard against both traps in a crisis?", o:[
          { t:"It shows the likely eruption is modest — dangerous locally, not world-ending.", v:"expert", fb:"Correct — the spectrum rejects apocalypse while still taking real hazard seriously." },
          { t:"It proves every restless volcano is on the verge of a VEI 8 event.", v:"danger", fb:"The scale shows the opposite; huge events are the rarest by far." },
          { t:"It proves a VEI 3 or 4 in a valley is nothing worth worrying about.", v:"danger", fb:"A VEI 3–4 can devastate a valley; that is the dismissal trap." },
          { t:"It replaces the need for any live monitoring by fixing the outcome in advance.", v:"wrong", fb:"The VEI describes past size; forecasting still requires live monitoring." } ] }
      ] },
    // cell: The Seismologist @ The Monitoring Station
    pyroclastic:{ sci:"Alfred Lacroix (1863-1948)", topic:"Pyroclastic flows & Mont Pelée", lede:"The Frenchman who watched a glowing avalanche erase a city in minutes and gave the killer a name.", no:9,
      profile:"Alfred Lacroix was a French mineralogist and geologist who became the chief scientific witness to one of history's deadliest eruptions. On May 8, 1902, Mont Pelée on Martinique unleashed a searing cloud of gas, ash, and rock fragments that swept down on the port of Saint-Pierre and killed roughly 28,000 people in a matter of minutes. Lacroix arrived to study the disaster and, in his monumental report, named the phenomenon the nuée ardente — the 'glowing cloud.'\n\nWhat he described is now called a pyroclastic density current, or pyroclastic flow: a ground-hugging avalanche of hot gas and volcanic debris that races downhill at speeds up to hundreds of kilometers per hour and temperatures of hundreds of degrees. Unlike a lava flow, which is slow enough to outwalk, a pyroclastic flow arrives faster than anyone can run and kills by heat and asphyxiation. It is the single deadliest volcanic hazard, and Saint-Pierre became its grim archetype.\n\nThe tragedy of 1902 was compounded by human failure. An election was approaching, officials had assured residents the mountain was safe, and evacuation was discouraged; a commission even reported that Saint-Pierre was in no immediate danger. The people stayed, and the cloud came.\n\nLacroix's work matters to this inquiry on two levels. Scientifically, pyroclastic flows define the most acute survivable-only-if-you-leave hazard: you cannot outrun one, so the only defense is to be gone before it forms. Politically, Saint-Pierre is the cautionary tale that haunts every honest volcanologist — a case where authorities, anxious about an election and the local economy, downplayed a real threat and told people to stay put. The parallel to any tourist town under a stirring volcano is exact and unforgiving.",
      frame:"The seismologist lowers her voice. \"There's one hazard you cannot outrun, and a town that was told to stay calm right before it died. Learn the lesson of Saint-Pierre, and tell me you understand it:\"",
      q:[
        { q:"What is a pyroclastic flow?", o:[
          { t:"A fast, ground-hugging avalanche of hot gas, ash, and rock fragments.", v:"expert", fb:"Right — a searing density current racing downhill far faster than a person." },
          { t:"A slow river of molten lava that people can easily walk away from.", v:"danger", fb:"That is a lava flow; pyroclastic flows are far faster and cannot be outrun." },
          { t:"A harmless plume of cool white steam drifting up from the summit.", v:"danger", fb:"Steam plumes are benign; pyroclastic flows are the deadliest hazard of all." },
          { t:"A gentle rain of fine gray ash that settles quietly over the whole region.", v:"wrong", fb:"Ashfall is a different, slower hazard; a flow is a fast, hot avalanche." } ] },
        { q:"Why are pyroclastic flows so lethal?", o:[
          { t:"They arrive faster than anyone can run and kill by heat and asphyxiation.", v:"expert", fb:"Yes — the only defense is to be gone before the flow ever forms." },
          { t:"They move slowly enough that residents can always outwalk them safely.", v:"wrong", fb:"They travel at highway speeds; walking away is not possible." },
          { t:"They are dangerous only to aircraft high above and never to people below.", v:"wrong", fb:"They are ground-hugging and deadly to anyone in the valley below." },
          { t:"They wipe out all human life on Earth in a single instant everywhere.", v:"danger", fb:"They are locally catastrophic, not globally instant; the peril is the valley path." } ] },
        { q:"What human lesson does Saint-Pierre teach for this crisis?", o:[
          { t:"Officials downplayed a real threat and told people to stay — and they died.", v:"expert", fb:"Correct — election and economy fears buried the warning; the parallel is exact." },
          { t:"The eruption proved that no evacuation is ever worth the disruption.", v:"danger", fb:"The lesson is the reverse: a timely evacuation would have saved thousands." },
          { t:"It showed that scientists always exaggerate volcanic danger for attention.", v:"wrong", fb:"There the danger was downplayed, not exaggerated; the science was ignored." },
          { t:"It proved pyroclastic flows can be reliably outrun with early warning.", v:"wrong", fb:"You cannot outrun a flow; warning works only by getting people out first." } ] }
      ] },
    // cell: The Seismologist @ The Monitoring Station
    lahar:{ sci:"Barry Voight (1937-2024)", topic:"Lahars & flank collapse", lede:"The engineer-geologist who predicted a mountain's collapse in writing weeks before Mount St. Helens fell.", no:10,
      profile:"Barry Voight was an American geologist and engineer who applied the mechanics of landslides to volcanoes with rare foresight. In early 1980, watching a huge bulge swell on the north flank of Mount St. Helens, Voight warned in writing that the slope was unstable and could fail catastrophically. On May 18 it did: the largest landslide in recorded history peeled away the flank, uncorked the pressurized magma beneath, and triggered the lateral blast that killed 57 people. His analysis of flank instability had been vindicated in the most dramatic way.\n\nVoight is also closely associated with two linked hazards. The first is flank collapse or debris avalanche — the sudden failure of an oversteepened, weakened volcanic slope. The second is the lahar: a fast-moving slurry of volcanic ash, rock, and water, with the consistency of wet concrete, that pours down river valleys. Lahars can form when an eruption melts summit snow and ice, when a crater lake breaks out, or when heavy rain mobilizes loose ash, and they can travel tens of kilometers, burying everything in the valleys far from the vent.\n\nIt was a lahar, not a blast, that destroyed the Colombian town of Armero in 1985, killing some 23,000 people, when a modest eruption of Nevado del Ruiz melted its ice cap. The warnings had been issued but not acted upon in time.\n\nFor this inquiry, Voight's hazards are decisive. A town in a valley below a snow-capped volcano can be devastated by a lahar even from a small eruption, and the danger zone follows the river channels, not a circle around the summit. This is the archetype of a real, survivable-if-you-act hazard: leave the valley floor, and you live.",
      frame:"\"Forget the summit for a second,\" the seismologist says, tracing a river valley on the map. \"The thing that reaches the town comes down the rivers. Voight knew it. Prove you do too:\"",
      q:[
        { q:"What is a lahar?", o:[
          { t:"A fast slurry of ash, rock, and water pouring down the river valleys.", v:"expert", fb:"Right — a volcanic mudflow with the feel of wet concrete, following channels." },
          { t:"A slow stream of glowing molten lava creeping down the summit cone.", v:"wrong", fb:"That is a lava flow; a lahar is a water-and-debris mudflow, and far faster." },
          { t:"A cloud of fine volcanic ash drifting harmlessly on the high winds.", v:"wrong", fb:"Ashfall is airborne; a lahar rushes along the ground down valley floors." },
          { t:"A gentle warm spring that bubbles up harmlessly at the mountain's base.", v:"danger", fb:"A lahar is a destructive flood of debris, not a benign warm spring." } ] },
        { q:"What did Voight foresee at Mount St. Helens in 1980?", o:[
          { t:"That the bulging north flank was unstable and could fail catastrophically.", v:"expert", fb:"Yes — the slope collapsed on May 18, uncorking the lateral blast." },
          { t:"That the volcano was completely dormant and posed no serious risk whatsoever.", v:"danger", fb:"He warned of instability; the 'all clear' view was the one proved wrong." },
          { t:"That a supereruption would wipe out the entire western United States.", v:"danger", fb:"He predicted a flank failure and blast, not a continent-ending event." },
          { t:"That the summit crater lake would freeze solid and seal the vent.", v:"wrong", fb:"His warning was about slope collapse, not a freezing crater lake." } ] },
        { q:"Why does a lahar threat shape where a town must evacuate?", o:[
          { t:"The danger follows the river channels, not a simple circle around the summit.", v:"expert", fb:"Correct — leave the valley floor and you survive; the path is the hazard." },
          { t:"Only people standing on the very summit are ever at risk from a lahar.", v:"wrong", fb:"Lahars travel tens of kilometers down-valley, far from the summit." },
          { t:"A lahar can only form during a rare, world-ending VEI 8 supereruption.", v:"danger", fb:"Even a small eruption melting ice can spawn a deadly lahar, as at Armero." },
          { t:"Lahars are far too slow to reach any inhabited valley in time to harm it.", v:"danger", fb:"They move fast and have buried whole towns; Armero lost some 23,000." } ] }
      ] },
    // cell: Warden Cole @ The Monitoring Station
    gas:{ sci:"Haroun Tazieff (1914-1998)", topic:"Volcanic gases as precursors", lede:"The daredevil volcanologist who climbed into active craters to sample the breath of the Earth itself.", no:11,
      profile:"Haroun Tazieff was a French volcanologist, filmmaker, and adventurer, born in Warsaw, who did more than almost anyone to bring the study of active volcanoes to a wide public. Famous for descending into erupting craters in a silvered heat suit, he pioneered the direct sampling and filming of volcanic gases, arguing that the gases a volcano exhales are among the most revealing signals of what its magma is doing underground.\n\nMagma carries dissolved gases — mostly water vapor, carbon dioxide, and sulfur dioxide, along with hydrogen sulfide, hydrogen chloride, and others. As magma rises and the pressure drops, these gases come out of solution, much as bubbles form when a bottle is opened. Because different gases exsolve at different depths, a shift in the mix and the rate of emission can betray magma ascent before anything is visible at the surface. A surge in sulfur dioxide, in particular, often signals fresh magma nearing the vent.\n\nVolcanic gas can also kill directly. Carbon dioxide is denser than air and can pool invisibly in hollows; at Lake Nyos in Cameroon in 1986 a sudden release of volcanic CO2 suffocated more than 1,700 people. Gas monitoring is thus both a forecasting tool and a hazard in its own right.\n\nFor this inquiry, gas geochemistry is a precursor that is hard to fake and hard to hide. Rising sulfur dioxide flux and changing gas ratios are objective evidence that magma is moving, cutting through arguments about whether the unrest is 'real.' They also refute the comfortable dismissal that a plume is 'just harmless steam' — the composition of that plume is measurable, and a sulfur-rich, escalating signal is precisely the fingerprint of an advancing eruption, not of an idle mountain.",
      frame:"Cole holds up a battered gas-sampling flask. \"The mayor's office keeps calling it 'just steam.' Tazieff would've laughed. Steam has a smell and a chemistry. Tell me what the mountain's breath can reveal:\"",
      q:[
        { q:"Why do volcanic gases reveal what magma is doing?", o:[
          { t:"Rising magma releases gas as pressure drops, betraying its ascent early.", v:"expert", fb:"Right — different gases exsolve at different depths, flagging magma on the move." },
          { t:"Because gases are emitted only after the eruption has fully finished.", v:"wrong", fb:"Gas changes precede eruptions; they are precursors, not just aftermaths." },
          { t:"Because the gas is a pure, inert cloud that never changes composition.", v:"wrong", fb:"The mix shifts with depth and supply, which is exactly why it is useful." },
          { t:"Because a single whiff of any gas guarantees the planet will end within a day.", v:"danger", fb:"Gas signals magma movement, not an apocalypse; it is data, not doom." } ] },
        { q:"Which gas surge often signals fresh magma nearing the surface?", o:[
          { t:"A sharp rise in sulfur dioxide flux from the vent and fumaroles.", v:"expert", fb:"Yes — climbing SO2 is a classic fingerprint of shallow, fresh magma." },
          { t:"A rise in ordinary breathable oxygen escaping from deep in the crust.", v:"wrong", fb:"Oxygen is not a magmatic gas; sulfur dioxide is the telltale signal." },
          { t:"A total absence of any gas at all, proving the danger has fully passed.", v:"danger", fb:"A sealed, gas-starved vent can be more dangerous, not safe; silence can mislead." },
          { t:"A surge of pure helium that lifts the ash cloud harmlessly away.", v:"wrong", fb:"Helium is a trace tracer, not a lift gas; SO2 flux is the key precursor." } ] },
        { q:"Why does gas data undercut the 'just harmless steam' claim?", o:[
          { t:"A plume's composition is measurable, and rising sulfur betrays real magma.", v:"expert", fb:"Correct — you can analyze the breath; an escalating sulfur signal is no idle steam." },
          { t:"Because all volcanic plumes are in fact pure water vapor and nothing else.", v:"danger", fb:"That is the dismissal itself; real plumes carry sulfur and CO2 you can measure." },
          { t:"Because gas readings can never be trusted and are always instrument noise.", v:"wrong", fb:"Gas flux is a robust, repeatable measurement, not mere noise." },
          { t:"Because steam by itself has already killed millions of people worldwide.", v:"danger", fb:"The point is the plume is not just steam; overstating it is the opposite error." } ] }
      ] },
    // cell: Warden Cole @ The Monitoring Station
    tremor:{ sci:"Bernard Chouet (b. 1949)", topic:"Harmonic tremor & precursors", lede:"The seismologist who heard the drumbeat of moving fluids and turned it into an eruption alarm.", no:12,
      profile:"Bernard Chouet is a Swiss-American volcano seismologist who spent his career at the U.S. Geological Survey decoding the peculiar rumblings that precede eruptions. Ordinary tectonic earthquakes come from rock snapping along faults and produce sharp, high-frequency jolts. Chouet studied a very different signal: long-period (LP) events and harmonic tremor — smooth, rhythmic, low-frequency vibrations that he showed are produced by pressurized fluids, magma and gas, surging through cracks and conduits within the volcano.\n\nHis key insight was that these long-period signals are a direct fingerprint of fluid movement, not rock fracture, and that a swarm of them often marks magma and gas pressurizing the plumbing shortly before an eruption. Where a rising count of small volcano-tectonic quakes says rock is breaking as magma pushes upward, a burst of long-period events and sustained harmonic tremor can say the magma itself is on the move and pressure is building toward failure.\n\nChouet's work became famous for its practical payoff: at Mount Redoubt in Alaska and elsewhere, patterns of long-period seismicity helped forecast explosive eruptions with enough lead time to warn aircraft and communities. It turned a subtle seismic hum into an operational alarm.\n\nFor this inquiry, harmonic tremor is one of the most telling precursors an observatory can watch, and one of the easiest to underplay because it does not feel like a 'real' earthquake to residents. A shift from scattered tectonic pops to sustained rhythmic tremor is exactly the kind of change that a duty seismologist would flag and an official eager to reassure might bury. Recognizing it separates a volcano merely settling from one actively pressurizing — the crux of deciding whether the warning to leave is justified.",
      frame:"Cole leans in. \"The seismologist keeps saying the shaking 'changed its tune' and getting waved off. Chouet's whole life was that tune. Show me you'd know what it means:\"",
      q:[
        { q:"What produces harmonic tremor and long-period events?", o:[
          { t:"Pressurized fluids — magma and gas — surging through cracks and conduits.", v:"expert", fb:"Right — Chouet tied the rhythmic low-frequency hum to moving fluids, not fracture." },
          { t:"Rock snapping along a fault, exactly like an ordinary tectonic quake.", v:"wrong", fb:"That makes sharp high-frequency jolts; tremor is the smooth fluid signal." },
          { t:"Wind gusts and distant ocean waves buffeting the seismometers from far away.", v:"wrong", fb:"Those are noise sources; harmonic tremor comes from fluids inside the volcano." },
          { t:"Nothing physical at all — the tremor is purely an instrument malfunction.", v:"danger", fb:"It is a real signal of fluid movement, not a glitch to dismiss." } ] },
        { q:"Why is a shift to sustained tremor an important precursor?", o:[
          { t:"It suggests magma itself is on the move and pressure is building to failure.", v:"expert", fb:"Yes — a burst of long-period events can precede explosive eruptions." },
          { t:"It proves conclusively that the volcano has gone permanently dormant.", v:"danger", fb:"Sustained tremor points to pressurization, not dormancy; it is a warning sign." },
          { t:"It means a distant tectonic fault, not the volcano, is doing the shaking.", v:"wrong", fb:"Harmonic tremor originates in the volcano's own fluid-filled plumbing." },
          { t:"It guarantees an instant, unstoppable, world-ending eruption within minutes.", v:"danger", fb:"It is a precursor that buys warning time, not a countdown to the apocalypse." } ] },
        { q:"Why might an official be tempted to underplay tremor?", o:[
          { t:"It does not feel like a 'real' quake to residents, so it is easy to bury.", v:"expert", fb:"Correct — the subtle hum is easy to wave off, which is exactly the risk." },
          { t:"Because tremor is universally known to mean a volcano is perfectly safe.", v:"danger", fb:"It often means the opposite; underplaying it is the dangerous move." },
          { t:"Because harmonic tremor is far too loud for any instrument to record.", v:"wrong", fb:"It is a low-amplitude signal instruments capture well; loudness is not the issue." },
          { t:"Because tremor can only ever be detected after an eruption has ended.", v:"wrong", fb:"Its value is precisely that it appears before eruptions, as a precursor." } ] }
      ] },
    // cell: Guide Rún @ The Town & Evacuation Zone
    forecasting:{ sci:"Katia & Maurice Krafft (d. 1991)", topic:"Forecasting, evacuation & the warning", lede:"The volcano-chasing couple whose films of disaster convinced officials to evacuate — and saved tens of thousands.", no:13,
      profile:"Katia and Maurice Krafft were a French husband-and-wife team of volcanologists who became the most famous volcano chroniclers of their age, filming eruptions at close range from the 1960s until their deaths. On June 3, 1991, both were killed by a pyroclastic flow at Mount Unzen in Japan, alongside the journalist Harry Glicken and dozens of others. They had spent their lives documenting exactly the hazard that took them.\n\nTheir most consequential legacy is not the footage of fire fountains but their work on volcanic risk to people. The Kraffts assembled harrowing film of lahars, pyroclastic flows, and their aftermath into a video, made with volcanologists and civil-defense agencies, intended to show officials and residents in vulnerable towns what these hazards really do. That video was shown to authorities in the Philippines shortly before the June 1991 eruption of Mount Pinatubo and helped persuade them to order the evacuations that saved an estimated tens of thousands of lives — one of the great success stories of applied volcanology.\n\nForecasting a volcano is not about naming a date. It is about combining many precursors — seismicity, gas, ground deformation, past behavior — into a probabilistic judgment, and then, crucially, communicating it in time for people to act. The hardest part is often not the science but the decision to call an evacuation under uncertainty, knowing you may be wrong and mocked either way.\n\nFor this inquiry, the Kraffts embody the whole point. The correct response to a credible, uncertain volcanic threat is not to panic about the end of the world, nor to wait for certainty that never comes, but to warn clearly and move people out of the hazard's path. An evacuation that proves 'unnecessary' is a success, not a failure.",
      frame:"Rún grows quiet. \"The Kraffts died doing this, but their films got a whole city moved out in time before Pinatubo. That's the whole game — the warning. Tell me you understand what it's for:\"",
      q:[
        { q:"What is volcanic forecasting really about?", o:[
          { t:"Combining many precursors into a judgment, then warning people in time.", v:"expert", fb:"Right — probability from seismicity, gas, and deformation, communicated to act on." },
          { t:"Naming the exact calendar date and precise hour the eruption will begin.", v:"wrong", fb:"Forecasting gives probabilities and lead time, not a precise date." },
          { t:"Waiting for total certainty before ever alarming the public at all.", v:"danger", fb:"Certainty never comes; waiting for it is how towns get caught unwarned." },
          { t:"Predicting the precise number of people a future eruption will kill.", v:"wrong", fb:"The aim is to reduce that number by warning, not to forecast a body count." } ] },
        { q:"How did the Kraffts' work help save lives at Pinatubo in 1991?", o:[
          { t:"Their hazard films helped persuade officials to order timely evacuations.", v:"expert", fb:"Yes — showing what lahars and flows do convinced authorities to move people out." },
          { t:"They personally halted the eruption before it could reach the towns.", v:"danger", fb:"No one stops an eruption; their contribution was persuading people to leave." },
          { t:"They proved the volcano was harmless, so no one needed to leave at all.", v:"danger", fb:"The opposite — they documented the danger to justify evacuation." },
          { t:"They calculated the exact minute the first ash cloud would appear.", v:"wrong", fb:"Their role was risk communication, not pinpoint timing of the blast." } ] },
        { q:"How should officials treat an evacuation that proves 'unnecessary'?", o:[
          { t:"As a success — people were moved from a credible threat and survived.", v:"expert", fb:"Correct — a precautionary evacuation under uncertainty is a win, not a failure." },
          { t:"As proof that scientists lie and should be ignored the next time.", v:"danger", fb:"That reasoning gets people killed when the real event finally comes." },
          { t:"As grounds to ban all future evacuations to protect the local economy.", v:"danger", fb:"Protecting tourism over safety is exactly the failure this case warns against." },
          { t:"As evidence the monitoring instruments must all be broken and replaced.", v:"wrong", fb:"A non-eruption after warning is a normal, acceptable outcome, not a fault." } ] }
      ] },
    // cell: Guide Rún @ The Town & Evacuation Zone
    hotspot:{ sci:"J. Tuzo Wilson (1908-1993)", topic:"Hotspots & transform faults", lede:"The Canadian who explained a chain of islands as a plate sliding over one fixed plume of heat.", no:14,
      profile:"J. Tuzo Wilson was a Canadian geophysicist who supplied two of the keystones of plate tectonics in the 1960s. In 1963 he explained the Hawaiian island chain with the hotspot idea: a stationary plume of hot material deep in the mantle melts through the overriding plate, building a volcano; as the plate slides steadily onward, that volcano is carried off the plume and dies, while a new one grows behind it. The result is a conveyor-belt trail of progressively older, extinct islands — a natural record of the plate's motion and speed.\n\nIn 1965 Wilson identified a third kind of plate boundary, the transform fault, where two plates slide past each other horizontally, as along California's San Andreas. Together with the spreading ridges and subduction trenches, transform faults completed the geometry of how plates interact, and Wilson showed how the three boundary types link into continuous networks — the 'Wilson cycle' of ocean basins opening and closing.\n\nHotspots explain volcanoes far from any plate edge, from Hawaii to Yellowstone, and their fixed plumes give geologists a reference frame for tracking plate movement over tens of millions of years.\n\nFor this inquiry, Wilson's ideas set context and proportion. Knowing whether a volcano sits above a subduction zone, a rift, or a hotspot tells you what kind of magma and eruptions to expect and how the system is fed. It also tempers the apocalyptic reflex: a hotspot or arc volcano behaving restlessly is following a well-understood script, not signaling the end of the world. Understanding the tectonic setting is how an investigator frames the realistic range of outcomes rather than leaping to the most terrifying one — or dismissing the threat because the volcano is 'just doing its thing.'",
      frame:"Rún points across the valley to a line of older, worn-down cones. \"Same plume, older peaks — the ground slid over it. Wilson figured that out. Show me you can read a volcano's setting:\"",
      q:[
        { q:"What is a volcanic hotspot?", o:[
          { t:"A fixed mantle plume the moving plate slides over, building a chain.", v:"expert", fb:"Right — Hawaii's trail of aging islands records the plate's steady motion." },
          { t:"A place where two plates grind sideways past one another horizontally.", v:"wrong", fb:"That is a transform fault; a hotspot is a fixed plume beneath a moving plate." },
          { t:"A spot where the ground is warmest simply because the sun beats down.", v:"wrong", fb:"Hotspots are fed by mantle heat from below, not by sunlight above." },
          { t:"A single volcano guaranteed to detonate and end all life very soon.", v:"danger", fb:"A hotspot is a setting, not a doomsday device; it follows a known script." } ] },
        { q:"What did Wilson identify as a transform fault?", o:[
          { t:"A boundary where two plates slide horizontally past one another.", v:"expert", fb:"Yes — the San Andreas is the classic transform boundary he described." },
          { t:"A boundary where new seafloor is created and spreads outward.", v:"wrong", fb:"That is a spreading ridge; transforms slide, they do not create crust." },
          { t:"A boundary where one plate dives beneath another into the mantle.", v:"wrong", fb:"That is a subduction trench; a transform is horizontal sliding." },
          { t:"A crack that is slowly splitting the whole planet clean in half.", v:"danger", fb:"Transforms are ordinary sliding boundaries, not a planet-splitting rupture." } ] },
        { q:"Why does knowing a volcano's tectonic setting matter here?", o:[
          { t:"It frames the realistic range of eruptions instead of the scariest one.", v:"expert", fb:"Correct — setting tells you the plausible outcomes, tempering apocalyptic leaps." },
          { t:"It proves any restless volcano is about to end the entire world.", v:"danger", fb:"Setting does the opposite — it bounds expectations to a known script." },
          { t:"It shows the volcano is 'just doing its thing' and can be ignored fully.", v:"danger", fb:"Context frames the hazard; it never licenses ignoring a real threat." },
          { t:"It reveals the exact chemical recipe of every future ash particle.", v:"wrong", fb:"Setting hints at magma type broadly; exact chemistry needs direct sampling." } ] }
      ] },
    // cell: The Seismologist @ The Town & Evacuation Zone
    calderas:{ sci:"Robert Christiansen (1933-2022)", topic:"Calderas & supervolcanoes", lede:"The USGS geologist who mapped Yellowstone's three giant caldera cycles — and put the 'supervolcano' fear in proportion.", no:15,
      profile:"Robert Christiansen was a U.S. Geological Survey geologist who devoted decades to unraveling the volcanic history of Yellowstone. Through painstaking field mapping and dating, he showed that the region had produced three enormous caldera-forming eruptions over the past 2.1 million years, the calderas being the vast craters left when a magma chamber empties and its roof collapses. His work defined Yellowstone as one of Earth's great volcanic systems and established the framework still used to study it.\n\nA caldera forms differently from an ordinary cone-building eruption. When a huge volume of silica-rich magma erupts explosively, the ground above the emptied chamber founders, dropping to form a basin tens of kilometers across. The largest such events, the 'supereruptions' of VEI 8, eject thousands of cubic kilometers of material and are among the rarest phenomena in geology, separated by hundreds of thousands of years.\n\nChristiansen was also a voice of proportion. As 'supervolcano' fears spread through the media, he and his USGS colleagues repeatedly stressed that Yellowstone shows no sign of an imminent giant eruption, that the overwhelmingly likely activity is far smaller hydrothermal or lava events, and that sensational doomsday scenarios badly misrepresent the actual hazard and its probabilities.\n\nFor this inquiry, Christiansen is the direct rebuttal to the overclaim. Calderas and supereruptions are real, but they are spectacularly rare, and no responsible reading of a stirring resort volcano jumps to a civilization-ending blast. His career models the discipline of holding two truths at once: the biggest eruptions deserve serious study, and invoking them to describe an ordinary volcanic crisis is scientifically indefensible fear-mongering that distracts from the genuine, nearer hazard actually facing the town.",
      frame:"The seismologist taps a caldera map. \"Someone in this town is whispering 'supervolcano' to scare everyone. Christiansen spent his life putting that word in its place. Help me put it in its place:\"",
      q:[
        { q:"How does a caldera form?", o:[
          { t:"The ground founders into a huge crater as its magma chamber empties.", v:"expert", fb:"Right — the roof collapses after a large volume of magma erupts out." },
          { t:"A single new cone grows upward from repeated small lava flows.", v:"wrong", fb:"That builds a stratovolcano; a caldera is a collapse basin, not a cone." },
          { t:"A giant meteor impact punches a round crater into the volcanic plateau.", v:"wrong", fb:"Calderas are volcanic collapse features, not impact craters." },
          { t:"The whole planet cracks open along one enormous continental rift.", v:"danger", fb:"A caldera is a local collapse basin, not a planet-wide rupture." } ] },
        { q:"How often do VEI 8 supereruptions actually occur?", o:[
          { t:"Spectacularly rarely — hundreds of thousands of years typically apart.", v:"expert", fb:"Yes — they are among the rarest geologic events, not a near-term worry." },
          { t:"Every few years at any large caldera system somewhere on Earth.", v:"danger", fb:"Far from it; supereruptions are vanishingly rare on human timescales." },
          { t:"On a fixed clockwork schedule that makes them easy to predict exactly.", v:"wrong", fb:"There is no dependable clock; they are rare and irregular." },
          { t:"Never, since caldera-forming supereruptions have never truly happened.", v:"wrong", fb:"They have happened — Yellowstone, Toba — but exceedingly seldom." } ] },
        { q:"How should a serious scientist treat 'supervolcano' talk in this crisis?", o:[
          { t:"As indefensible fear-mongering that distracts from the real, nearer hazard.", v:"expert", fb:"Correct — invoking a rare giant to describe ordinary unrest misleads and harms." },
          { t:"As the single most likely outcome that everyone should prepare for now.", v:"danger", fb:"A supereruption is the least likely outcome; that framing is the overclaim trap." },
          { t:"As proof that the volcano is harmless and no one needs to worry at all.", v:"danger", fb:"Rejecting the apocalypse does not mean rejecting the genuine local hazard." },
          { t:"As a reason to shut the observatory and stop all monitoring entirely.", v:"wrong", fb:"Debunking hype is a reason to monitor carefully, not to stop watching." } ] }
      ] },
    // cell: The Seismologist @ The Town & Evacuation Zone
    tsunami:{ sci:"Rogier Verbeek (1845-1926)", topic:"Volcanic tsunami & Krakatoa", lede:"The Dutch geologist whose exhaustive report on Krakatoa revealed how a volcano can drown coasts miles away.", no:16,
      profile:"Rogier Verbeek was a Dutch geologist in the colonial East Indies who produced the definitive scientific account of the catastrophic 1883 eruption of Krakatoa. His monumental report reconstructed the sequence of events in extraordinary detail and became a foundation of modern volcanology, showing what careful, systematic documentation of a disaster could achieve.\n\nKrakatoa's climax on August 27, 1883 was one of the loudest events in recorded history, heard thousands of kilometers away, and it collapsed much of the island into the emptied magma chamber. But most of the roughly 36,000 deaths were not caused by the blast, the ash, or the pyroclastic flows directly. They were caused by tsunamis — great sea waves, some tens of meters high, generated as the eruption and collapse violently displaced the ocean. These waves swept away coastal towns around the Sunda Strait, far from the volcano itself.\n\nVerbeek's work established that a volcano can be lethal at great distance through the sea, a hazard easy to overlook when attention fixes on the summit. Volcanic tsunamis can be triggered by caldera collapse, by pyroclastic flows entering the water, or by flank collapse sliding into the sea — as a smaller but deadly 2018 event at Anak Krakatau tragically confirmed.\n\nFor this inquiry, Verbeek widens the map of who is in danger. If the stirring volcano stands near water, or if a collapsing flank could reach a lake or the sea, the hazard zone extends well beyond the obvious slopes to distant shorelines. It is another example of a real, geographically specific threat that a summit-focused 'all clear' can miss entirely — and another reason the honest question is not whether the mountain will 'blow up' but exactly where its effects will reach.",
      frame:"\"Everyone stares at the summit,\" the seismologist says, \"but Krakatoa killed most people at the shoreline, with waves. Verbeek proved it. Tell me you'd look past the crater:\"",
      q:[
        { q:"What killed most of Krakatoa's victims in 1883?", o:[
          { t:"Tsunamis — huge sea waves that swept the coasts around the strait.", v:"expert", fb:"Right — Verbeek showed the waves, not the blast, caused most deaths." },
          { t:"The deafening sound of the explosion rupturing eardrums for miles.", v:"wrong", fb:"The blast was heard far off, but tsunamis caused most of the deaths." },
          { t:"A slow lava flow that engulfed the surrounding villages one by one.", v:"wrong", fb:"Krakatoa was explosive; lava flows were not the main killer here." },
          { t:"A single supereruption that instantly wiped out the whole planet.", v:"danger", fb:"It was regionally devastating via tsunamis, not a global extinction." } ] },
        { q:"How can a volcano trigger a tsunami?", o:[
          { t:"By caldera collapse, pyroclastic flows, or a flank sliding into water.", v:"expert", fb:"Yes — any violent displacement of the sea can raise deadly waves." },
          { t:"Only by a direct meteor strike landing in the open ocean nearby.", v:"wrong", fb:"Volcanic tsunamis come from the eruption itself displacing water." },
          { t:"By heating the sea until it boils away and then rushes back in.", v:"wrong", fb:"Boiling is not the mechanism; sudden displacement of water is." },
          { t:"It cannot — no volcano has ever once generated a tsunami in all of history.", v:"danger", fb:"Volcanic tsunamis are well documented; Krakatoa is the classic case." } ] },
        { q:"What does the tsunami hazard add to defining the danger zone?", o:[
          { t:"The threat can extend to distant shorelines, well beyond the slopes.", v:"expert", fb:"Correct — a summit-focused 'all clear' can miss the coastal reach entirely." },
          { t:"It confirms that only people on the summit itself are ever in danger.", v:"danger", fb:"The opposite — the sea can carry the hazard far from the volcano." },
          { t:"It proves the eruption will certainly end civilization across the globe.", v:"danger", fb:"It widens the local map; it does not imply a worldwide catastrophe." },
          { t:"It shows monitoring the ocean is pointless since waves cannot be tracked.", v:"wrong", fb:"Coastal and sea monitoring is exactly how such tsunamis are watched for." } ] }
      ] },
    // cell: Warden Cole @ The Town & Evacuation Zone
    paleomag:{ sci:"Motonori Matuyama (1884-1958)", topic:"Geomagnetic reversals", lede:"The Japanese geophysicist who found that the Earth's magnetic field had flipped, north for south, in the deep past.", no:17,
      profile:"Motonori Matuyama was a Japanese geophysicist who made one of the most startling discoveries of twentieth-century Earth science. Studying the magnetism frozen into layers of volcanic basalt, he noticed in the 1920s that some ancient rocks were magnetized in the opposite direction to the present field. In a 1929 paper he argued the only sensible explanation: the Earth's magnetic field itself had reversed polarity in the geologic past, north and south swapping places.\n\nThe idea was radical and slow to be accepted, but it proved profoundly correct. Lava records the direction of the ambient magnetic field as it cools and locks in magnetic minerals, so a stack of dated flows preserves a chronology of reversals. The most recent long period of reversed polarity is now named the Matuyama chron in his honor. Decades later, this record of reversals became the decisive evidence for seafloor spreading, when the same reversal pattern was found mirrored symmetrically across the mid-ocean ridges.\n\nMatuyama's reversals are gradual events on geologic timescales, unfolding over thousands of years, and — importantly — they are not linked to volcanic eruptions, mass extinctions, or civilizational collapse, despite recurring doomsday myths that claim otherwise.\n\nFor this inquiry, Matuyama serves two purposes. First, his method shows how volcanic rock is a recording instrument, letting geologists read a volcano's eruptive history flow by flow — history that constrains what it may do next. Second, he is a caution against the apocalyptic reflex: a magnetic reversal is a real, well-documented planetary phenomenon that panicked pseudoscience routinely inflates into an extinction event. The discipline of separating a genuine, slow, harmless process from a manufactured catastrophe is exactly what this crisis demands of its investigator.",
      frame:"Cole spreads out a stack of dated lava layers. \"Some pamphlet's got the town scared the poles are about to flip and end us all. Matuyama's the man who actually found reversals. Set the record straight for me:\"",
      q:[
        { q:"What did Matuyama discover about the Earth's magnetic field?", o:[
          { t:"That it had reversed polarity in the past, swapping north and south.", v:"expert", fb:"Right — ancient basalts recorded a field pointing the opposite way." },
          { t:"That the magnetic field has been perfectly constant for all of time.", v:"wrong", fb:"He showed the opposite: the field has flipped repeatedly over eons." },
          { t:"That the magnetic field is generated entirely by the Sun, not the core.", v:"wrong", fb:"The field comes from the core; his finding was about its reversals." },
          { t:"That the next flip will instantly wipe out all life on the planet.", v:"danger", fb:"Reversals are slow and harmless; the extinction claim is a doomsday myth." } ] },
        { q:"How does volcanic rock record magnetic reversals?", o:[
          { t:"Cooling lava locks in the field's direction, flow by dated flow.", v:"expert", fb:"Yes — a stack of dated flows preserves a chronology of reversals." },
          { t:"The rock loudly repels compasses only during an active eruption.", v:"wrong", fb:"It quietly freezes the field direction as it cools, not just while erupting." },
          { t:"The rock's color changes from red to blue each time the poles flip.", v:"wrong", fb:"Color is not the record; the frozen magnetic orientation is." },
          { t:"It cannot record anything, since rock holds no magnetism at all.", v:"wrong", fb:"Iron-bearing lava is precisely what preserves the ancient field direction." } ] },
        { q:"Why is the reversal story a caution for this crisis?", o:[
          { t:"It is a real, slow, harmless process routinely inflated into catastrophe.", v:"expert", fb:"Correct — separating genuine science from manufactured doom is the whole task." },
          { t:"It proves a magnetic flip will trigger the volcano's eruption any day.", v:"danger", fb:"Reversals are unrelated to eruptions; that link is pure pseudoscience." },
          { t:"It shows that volcanic rock can tell us nothing about the past at all.", v:"wrong", fb:"Rock is a superb recorder; reversals are read straight from the lava." },
          { t:"It means the town should evacuate immediately because the poles are moving.", v:"danger", fb:"A slow reversal is no evacuation trigger; the real hazard is the volcano itself." } ] }
      ] },
    // cell: Warden Cole @ The Town & Evacuation Zone
    monitoring:{ sci:"Thomas Jaggar (1871-1953)", topic:"Continuous monitoring", lede:"The American who built the first permanent volcano observatory so a mountain would never again be watched too late.", no:18,
      profile:"Thomas Jaggar was an American geologist who, after touring the aftermath of the 1902 Mont Pelée and Soufrière disasters in the Caribbean, resolved that volcanoes should be watched continuously rather than studied only after they had killed. In 1912 he founded the Hawaiian Volcano Observatory on the rim of Kilauea, the first permanent volcano observatory in the United States and a model for the world. He ran it for decades, often in spartan conditions, building the practice of long-term, instrument-based observation.\n\nJaggar's conviction was that eruptions are preceded by measurable changes, and that only a continuous, calibrated record can catch them. He championed networks of seismometers to track earthquakes, tiltmeters and later other instruments to detect the swelling and subsidence of the ground as magma moves, and systematic measurement of temperatures, gases, and lava behavior. The point was to know a volcano's normal baseline so intimately that a departure from it would stand out and could be acted upon.\n\nThis is the foundation of modern volcano monitoring: seismicity, ground deformation, gas emissions, and thermal and visual observation, integrated over time so that unrest can be recognized early and forecasts issued. An observatory's authority rests on this unbroken record.\n\nFor this inquiry, Jaggar's legacy frames the central conflict. A properly monitored volcano leaves an evidentiary trail — quakes, tremor, tilt, gas — that neither an apocalyptic rumor nor an official 'all clear' can honestly override. When the instruments say the baseline has shifted, that record is the check on both panic and suppression. The gravest failure is not a wrong forecast but a decision to ignore or bury the monitoring data for reasons that have nothing to do with the science — the very failure this investigation exists to expose.",
      frame:"Cole gestures at the racks of humming instruments. \"Jaggar built the first observatory so no mountain would be watched too late. We've got the data. Someone just won't act on it. Show me you know what watching means:\"",
      q:[
        { q:"What did Thomas Jaggar establish in 1912?", o:[
          { t:"The first permanent U.S. volcano observatory, at Kilauea in Hawaii.", v:"expert", fb:"Right — a base for continuous, instrument-based watching of a live volcano." },
          { t:"A one-time expedition that studied a volcano only after it erupted.", v:"wrong", fb:"His whole point was continuous watching, not after-the-fact study." },
          { t:"A law banning anyone from ever living near an active volcano again.", v:"wrong", fb:"He founded an observatory to monitor volcanoes, not to legislate them." },
          { t:"A machine that could reliably stop eruptions before they ever began.", v:"danger", fb:"No device stops eruptions; his aim was to observe and forecast them." } ] },
        { q:"What does modern volcano monitoring integrate?", o:[
          { t:"Seismicity, ground deformation, gas, and thermal observation over time.", v:"expert", fb:"Yes — combining these against a known baseline reveals real unrest." },
          { t:"A single seismometer reading taken just once, right after an eruption.", v:"wrong", fb:"One late reading is useless; monitoring is many signals watched continuously." },
          { t:"Only eyewitness reports from tourists visiting the summit each season.", v:"wrong", fb:"Instruments, not casual sightings, form the backbone of monitoring." },
          { t:"Astrological charts that predict eruptions from the planets' alignment.", v:"danger", fb:"Monitoring is instrumental science; astrology has no place in it." } ] },
        { q:"Why does the monitoring record matter to this case?", o:[
          { t:"It is the check that neither a rumor nor an 'all clear' can honestly override.", v:"expert", fb:"Correct — a shifted baseline is objective evidence against panic and suppression alike." },
          { t:"It lets officials safely ignore the data whenever it is inconvenient.", v:"danger", fb:"Burying inconvenient data is precisely the failure this inquiry exposes." },
          { t:"It proves the volcano will produce a world-ending blast within the coming week.", v:"danger", fb:"The record bounds the hazard realistically; it does not forecast apocalypse." },
          { t:"It shows monitoring is a waste once a baseline has finally been set.", v:"wrong", fb:"The baseline is what makes ongoing monitoring valuable, not obsolete." } ] }
      ] }
  },
  STORIES:{
    guide:{
      summit:"Rún meets you at the crater rim, scarf pulled over her nose against the fumes. \"Smell that? Sharper than last month, and the snow's melting in patches it never used to. The mountain's telling us something — question is who's listening.\"",
      station:"Rún leans in the doorway of the station, mud to the knee. \"I've walked every gully off this peak for thirty years. If you want to know which way trouble runs downhill, ask me — not the brochure the mayor's office prints.\"",
      town:"Rún finds you on the town's main street, uneasy among the cafés. \"Feels wrong to be down here sipping coffee while the top of the mountain sweats sulfur. I brought the tourists up for years. I'd not bring them up now.\""
    },
    seismo:{
      summit:"The seismologist has hiked up with a portable sensor. \"I wanted to feel it myself. The drums back down show the tremor's gone rhythmic — a hum, not just pops. That's a different animal, and it started three weeks ago.\"",
      station:"Bent over the drum recorder, the seismologist barely looks up. \"Look at this trace. Swarms climbing shallower every day. I've flagged it twice. Twice it came back marked 'no public concern.' You tell me who writes that.\"",
      town:"The seismologist paces the evacuation-zone office, papers in hand. \"My readings say the conduit's pressurizing. Someone upstairs keeps softening my words before they reach this town. I need someone who'll read the raw data.\""
    },
    warden:{
      summit:"Warden Cole is up marking sensor stakes, radio crackling. \"I run the drills, so I climb up to see for myself. What I see doesn't match the 'all clear' I'm ordered to broadcast. That gap is going to get people killed.\"",
      station:"Cole spreads hazard maps across the station bench. \"Lahar channels, pyroclastic run-outs — I know exactly where they'd go. What I don't know is why my evacuation route keeps getting shortened on the mayor's orders.\"",
      town:"Cole stands in the empty muster square, whistle around his neck. \"This is where the buses would load. I've got the plan, the drills, the sirens. What I haven't got is permission to sound them. Ask me why.\""
    }
  },
  story:[
    "The town of <b>Halcyon</b> sits in a green valley beneath a snow-capped volcano, and its whole living is the summer trade — the cable car, the hot springs, the postcards. But the mountain has begun to stir. Sulfur sharpens the air, the drums at the observatory scrawl a new rhythm, and a coded plea has reached the Bureau. You are <b>Dr. Nils Aakre</b>, sent quietly to the <b>Halcyon Volcano Observatory</b> to find out what is really happening before the season — or the mountain — breaks.",
    "<b>Three people will help you</b>, each for their own reasons and only if you earn it. <b>Guide Rún</b>, who has read the mountain's moods for thirty years and smells the sulfur changing. <b>The Seismologist</b> on duty, who watches the drums and swears the tremor has turned and no one will listen. And <b>Warden Cole</b>, who runs the evacuation drills and is caught between the science and the mayor's office. None of them is to blame; each holds only fragments.",
    "<b>Someone here is steering the story.</b> Three names sit in your notepad: the <b>observatory director</b>, the field geologist <b>Dr. Sasi</b>, and <b>Mayor Holt</b>, the civil-protection chief. Each column of the case — <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> is truly happening — hides a tempting wrong answer. One camp cries that a <b>civilization-ending supereruption</b> is upon us. The official line insists it is <b>nothing — harmless steam, all clear.</b> The truth lies between — and the mountain will not wait for you to find it.",
    "You have <b>8 days</b> and a single accusation. Call it right and a warning goes out in time; call it wrong and you either empty a town for nothing — or leave it in the path of the flow."
  ],
  endings:{ overclaimWhat:"apocalypse", dismissalWhat:"allclear",
    win:{
      expertTitle:"The Warning, Made Undeniable",
      expert:["Aakre names it precisely: Mayor Holt, as civil-protection chief, suppressing the evacuation call; the danger culminating in the Town & Evacuation Zone squarely in the hazard's path; and the true event a real, imminent, survivable-if-you-act eruption — flank instability feeding lahars and pyroclastic flows down the valley — not a supereruption, and not harmless steam.",
        "Every card is accounted for. He read the raw seismicity, the climbing gas flux, and the hazard maps, and he refused both the doomsday word and the 'all clear.' The evidence he assembled cannot be softened by a press office. The sirens sound, the buses load, and the valley empties in time — which was the whole point."],
      soundTitle:"Right, and Enough to Act",
      sound:["Aakre names the right three — Holt, the Town, and a genuine downplayed hazard rather than apocalypse or nothing. The shape of it is correct and the restraint is exactly right.",
        "But he left evidence on the table, and the mayor's allies will contest the thin spots. Close and honest; another day of gathering tremor and gas records would have made the warning unassailable."],
      namedTitle:"The Right Answer, Barely Held",
      named:["Aakre points to the truth — Holt, the Town, the concealed but survivable hazard — yet gathered too few clues to anchor it. It reads more like instinct than proof.",
        "An evacuation order this thinly supported can be overruled by the officials it accuses. Being right is not the same as being able to make them act."]
    },
    overclaim:{ title:"The Investigator Who Cried Doomsday",
      body:["Aakre reports an imminent civilization-ending supereruption — terrifying, and flatly unsupported by the data. The seismicity, the gas flux, and the magma chemistry all point to a hazardous but ordinary flank eruption, orders of magnitude smaller than the VEI 8 catastrophe he invokes.",
        "The overclaim does more than embarrass. The moment the mayor's office can wave away one wild, disprovable claim, the real and provable finding — a downplayed, survivable hazard bearing down on the town — is discredited along with it. The valley loses the credible warning it actually needed, buried under a doomsday headline no scientist could defend."] },
    dismissal:{ title:"The 'All Clear' Signed",
      body:["Aakre accepts the official line — harmless steam, nothing to see — and closes the file. He has taken the comfortable half of the story and left the dangerous half untouched.",
        "The climbing quake swarms, the rhythmic harmonic tremor, the rising sulfur, the lahar channels drawn straight through town: all of it pointed past the reassurance to a real, gathering threat. He mistook a mountain being downplayed for a mountain at rest, exactly as Saint-Pierre was told it was safe — and the flow does not wait for the season to end."] },
    wrongNames:{ title:"So Close",
      body:["Aakre reads the event itself correctly — a real, imminent, survivable-if-you-act hazard being downplayed to protect the town's tourist season, neither the supereruption of the panic nor the harmless steam of the official line. The science, he has cold; it is the culprit and the ground zero he has misplaced."] }
  },
}};
