// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"reactor", title:"The Thornbury Reactor", discipline:"Nuclear Reactor Safety",
  teaser:"A reactor ran wild during a night-shift test. An attack? A one-in-a-billion fluke? Or a design flaw someone buried?", overclaimTag:"sabotage or an attack", truthTag:"a concealed reactor design flaw",
  venue:"the Thornbury reactor inquiry", agent:{name:"Inspector Ada Vrain", role:"Investigator's Notepad"},
  standingLabel:"Inquiry credibility", readingShort:"Pioneers", readingLabel:"Nuclear Pioneers",
  dossierName:"NUCLEAR PIONEERS", enterLabel:"Open the inquiry", subt:"A deduction game inside the Thornbury reactor inquiry", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the answer the cameras want: the traces point not to an intruder in the night, but to something quieter — and far harder to bury.",
  CATS:{
    who:{ title:"Who is behind it", truth:"designer", items:[
      {id:"operator", label:"Operations chief Marsh"},
      {id:"designer", label:"Aldous Reeve — chief reactor designer"},
      {id:"regulator", label:"The nuclear inspector"} ]},
    where:{ title:"Where it culminates", truth:"designoffice", items:[
      {id:"control", label:"The Reactor Control Room"},
      {id:"hall", label:"The Reactor Hall & Core"},
      {id:"designoffice", label:"The Design Authority's Office"} ]},
    what:{ title:"What is happening", truth:"designflaw", items:[
      {id:"attack", label:"Sabotage or an attack on the plant"},
      {id:"freak", label:"A freak accident — vanishingly unlikely"},
      {id:"designflaw", label:"A concealed reactor design flaw, run past its margin"} ]}
  },
  PLACES:{
    control:{name:"The Reactor Control Room", xy:[140,90]},
    hall:{name:"The Reactor Hall & Core", xy:[330,240]},
    designoffice:{name:"The Design Authority's Office", xy:[520,90]}
  },
  EDGES:[["control","hall"],["hall","designoffice"]],
  CHARACTERS:{
    operator2:{ name:"Operator Nadia Sorel", role:"Reactor operator", face:"🎛", badge:"O", legend:"the control room", hint:"Ran the test to the book she was handed; the book was wrong." },
    healthphys:{ name:"The Health Physicist", role:"Health physicist", face:"☢", badge:"H", legend:"the reactor hall", hint:"Reads the dose and the core; knows how fast the power really ran away." },
    clerk:{ name:"The Clerk", role:"Design-office clerk", face:"🗂", badge:"C", legend:"the office", hint:"Keeps the design files — and the flaw report stamped and shelved." }
  },
  TOPICMAP:{
    control:{ operator2:["radioactivity","nucleus"], healthphys:["neutron","fission"], clerk:["fissionchem","chainreaction"] },
    hall:{ operator2:["firstpile","dropmodel"], healthphys:["reactorphysics","reactoreng"], clerk:["betadecay","navalreactor"] },
    designoffice:{ operator2:["inherentsafety","delayedneutrons"], healthphys:["healthphysics","halflife"], clerk:["riskassessment","riskcell"] }
  },
  TOPICS:{
    // cell: Operator Nadia Sorel @ The Reactor Control Room
    radioactivity:{ sci:"Marie Curie (1867-1934)", topic:"Radioactivity", lede:"The Paris physicist who gave the phenomenon at the heart of this inquiry its name — and paid for it with her life.", no:1,
      profile:"Marie Curie was a Polish-born physicist and chemist working in Paris who gave the phenomenon at the center of this inquiry its name: radioactivity. Studying the mysterious rays from uranium that Henri Becquerel had noticed, she made a decisive measurement — the intensity of the radiation depended only on how much uranium was present, not on its chemical form, temperature, or combination. From this she argued that radioactivity is a property of the atom itself, an internal event, not a chemical reaction between atoms.\n\nWorking with her husband Pierre, she pursued the tiny extra activity in uranium ore and, in 1898, announced two new elements: polonium, named for her homeland, and radium. Isolating a measurable amount of pure radium from tons of pitchblende took years of punishing chemical labor. Her tool throughout was quantitative: an ionization chamber paired with Pierre's piezoelectric quartz, which let her measure the faint electric current the rays drove through air. She won two Nobel Prizes — Physics in 1903, shared with Pierre and Becquerel, and Chemistry in 1911 — the only person honored in two different sciences. She died in 1934 of a blood disease almost certainly caused by decades of exposure.\n\nFor this board, Curie's legacy is that radioactivity is measurable and lawful. The rays a reactor produces are not mysterious or capricious; their intensity tracks exactly what the atoms are doing. Every detector in that control room descends from her ionization chamber. So when a reactor's power runs away, it leaves a quantitative record — a trace that can distinguish a physical excursion from an intruder's hand. Before anyone calls the accident a fluke or a plot, Curie would say: read the numbers, because the atoms were counting.",
      frame:"Nadia slides her logbook across. \"They're already whispering I broke it, or that someone else did. I read every dial that night. Before you trust my numbers, show me you know what those dials even measure.\"",
      q:[
        { q:"What did Curie establish about radioactivity?", o:[
          { t:"That it is a property of the atom itself, independent of the element's chemical form.", v:"expert", fb:"Radioactivity is intrinsic to the atom, not a property of the compound." },
          { t:"That it is a delicate reaction between atoms that the smallest disturbance can set off.", v:"danger", fb:"It is not a fragile chemical reaction; nothing external sets off a single atom." },
          { t:"That it depends on the uranium's temperature and on how the sample has been prepared.", v:"wrong", fb:"Curie showed activity ignores temperature and chemical preparation entirely." },
          { t:"That only uranium is radioactive, so the effect is rare and easily contained.", v:"partial", fb:"She found activity in thorium and new elements too; uranium is not unique." } ] },
        { q:"How did the Curies measure radioactivity?", o:[
          { t:"By the electric current the rays drove through air, read on a sensitive electrometer.", v:"expert", fb:"Ionized air conducts a tiny current; measuring it quantified the radiation." },
          { t:"By the heat the rays gave off, gauged with a finely calibrated laboratory thermometer.", v:"wrong", fb:"Radium does warm slightly, but the Curies measured ionization, not heat." },
          { t:"By how quickly the samples visibly glowed, which only the purest radium could do.", v:"danger", fb:"Glow is not the measurement; the electrometer read invisible ionization." },
          { t:"By weighing the ore before and after, since activity slowly consumes the mineral.", v:"partial", fb:"The ore is not consumed measurably; activity was read electrically." } ] },
        { q:"Why does measurable radioactivity matter to this inquiry?", o:[
          { t:"A reactor's power leaves a quantitative trace, so its behavior can be read, not guessed.", v:"expert", fb:"Instruments record the excursion; a runaway and a break-in read differently." },
          { t:"Any radiation reading at all is proof that someone breached and tampered with the core.", v:"danger", fb:"Elevated radiation follows any power surge; it does not by itself mean sabotage." },
          { t:"Radiation cannot be measured in real time, so the night's events are lost for good.", v:"wrong", fb:"Curie's ionization chambers measure in real time; the traces survive." },
          { t:"The dose to the crew is all that counts; the power history tells the board nothing.", v:"partial", fb:"Dose matters, but the power and flux record is what reveals the cause." } ] }
      ] },
    // cell: Operator Nadia Sorel @ The Reactor Control Room
    nucleus:{ sci:"Ernest Rutherford (1871-1937)", topic:"The nuclear atom", lede:"The New Zealand farm boy who fired particles at gold foil and found the dense heart of the atom staring back.", no:2,
      profile:"Ernest Rutherford, born on a New Zealand farm, became the father of nuclear physics. At Manchester he set his assistants Hans Geiger and Ernest Marsden to fire alpha particles at a thin gold foil. Almost all passed straight through, but a tiny fraction bounced sharply back — as if, he said, a fifteen-inch shell had been fired at tissue paper and rebounded to hit you. No diffuse cloud of charge could do that.\n\nFrom this, in 1911, Rutherford drew the nuclear atom: nearly all the mass and all the positive charge packed into a minuscule central nucleus, with electrons in the vast empty space around it. He had already, with Frederick Soddy, explained radioactivity as the spontaneous transmutation of one element into another, and had named the alpha and beta rays and shown alphas to be helium nuclei. In 1919 he went further, using alpha particles to knock protons out of nitrogen and turn it into oxygen — the first deliberate transmutation of one element into another, and the discovery of the proton.\n\nRutherford worked by inference: he never saw a nucleus, but the scattering pattern forced its existence. He was also famously wrong once, dismissing practical atomic energy as 'moonshine' the year before the chain reaction was conceived — a reminder that even great authorities can wave away what is coming.\n\nFor this board, Rutherford supplies two lessons. First, the nucleus holds energy millions of times greater than any chemical bond, which is why a reactor can surge with terrifying speed. Second, structure is read from evidence: the night's events, however violent, left a scattering of traces an investigator can reason back from, rather than a mystery to be filled with a lurid guess.",
      frame:"Nadia jabs at the power trace on the wall. \"The needle didn't lie — it just moved faster than anyone believed it could. To read what the core did, you'd better know what a nucleus even is.\"",
      q:[
        { q:"What did the gold-foil experiment show?", o:[
          { t:"That an atom's mass and positive charge sit in a tiny, dense central nucleus.", v:"expert", fb:"A few alphas rebounding meant a concentrated core: the nucleus." },
          { t:"That the atom is a uniform sphere of charge with electrons stuck evenly throughout it.", v:"wrong", fb:"That plum-pudding picture is exactly what the rebound disproved." },
          { t:"That atoms are mostly solid, so a stray particle could never pass through metal foil.", v:"danger", fb:"Most alphas passed straight through — atoms are mostly empty space." },
          { t:"That electrons orbit at fixed distances, which was the experiment's main discovery.", v:"partial", fb:"Fixed orbits came later from Bohr; Rutherford's result was the nucleus." } ] },
        { q:"What was Rutherford's 1919 achievement?", o:[
          { t:"The first deliberate transmutation — turning nitrogen into oxygen and freeing a proton.", v:"expert", fb:"He changed nitrogen to oxygen with alphas, discovering the proton." },
          { t:"The first splitting of a uranium nucleus, releasing the energy that would power reactors.", v:"danger", fb:"That was fission, decades later; Rutherford transmuted light nuclei." },
          { t:"The invention of the cyclotron to accelerate particles to enormous energies.", v:"wrong", fb:"Lawrence built the cyclotron; Rutherford used natural alpha sources." },
          { t:"Proof that alpha rays are simply fast electrons streaming from a decaying atom.", v:"partial", fb:"Alphas are helium nuclei; beta rays are the electrons." } ] },
        { q:"Why does the nuclear atom matter to this inquiry?", o:[
          { t:"The nucleus stores immense energy, so a reactor can surge fast yet still obey physics.", v:"expert", fb:"Nuclear energy dwarfs chemical energy, which is why excursions are so fast." },
          { t:"Such energy is so vast that only a planted charge could ever release it so suddenly.", v:"danger", fb:"A chain reaction releases that energy; no bomb is needed for a power surge." },
          { t:"Nuclear energy is no larger than chemical energy, so a runaway is physically impossible.", v:"wrong", fb:"Nuclear energy is millions of times chemical; a runaway is very possible." },
          { t:"The energy is real but far too slow to matter on the timescale of a single night.", v:"partial", fb:"A prompt excursion unfolds in a fraction of a second, not slowly." } ] }
      ] },
    // cell: The Health Physicist @ The Reactor Control Room
    neutron:{ sci:"James Chadwick (1891-1974)", topic:"The neutron", lede:"The quiet Cavendish physicist who caught the uncharged particle that makes every reactor — and every runaway — possible.", no:3,
      profile:"James Chadwick discovered the particle that makes a reactor possible. Working under Rutherford at Cambridge's Cavendish Laboratory, he chased a puzzle: when beryllium was bombarded with alpha particles, it gave off a strange, highly penetrating radiation that carried no charge. Others guessed it was high-energy gamma rays, but the energetics did not add up. In 1932 Chadwick ran careful experiments showing the radiation could knock protons out of paraffin with an efficiency only a massive particle could explain. He concluded it was a new, electrically neutral particle with almost the same mass as the proton — the neutron. It won him the Nobel Prize in 1935.\n\nRutherford had predicted such a particle years earlier, but Chadwick proved it. The consequence was immediate and enormous. Because the neutron has no electric charge, it feels no repulsion from the positively charged nucleus; even a slow neutron can drift straight in and be captured. That is exactly what makes nuclear fission and a self-sustaining chain reaction possible: neutrons split heavy nuclei, which release more neutrons, which split more nuclei. Chadwick understood the stakes and became the scientific head of the British mission to the Manhattan Project.\n\nFor this board, the neutron is the currency of the whole event. A reactor's power is really a neutron population, multiplying or dying away from instant to instant. Control rods work by swallowing neutrons; the moderator works by slowing them so they split fuel more readily. When power runs away, it is the neutron count that explodes, and neutron detectors record that rise in fine detail. That trace is a physical fingerprint of an excursion — utterly unlike the mark an intruder would leave, and entirely foreseeable to anyone who understood Chadwick's particle.",
      frame:"The Health Physicist sets a foil detector on the table. \"Everything that happened in that core, the neutrons wrote down for me. Show me you know what a neutron is before I share the count.\"",
      q:[
        { q:"What did Chadwick discover in 1932?", o:[
          { t:"A neutral particle of nearly proton mass behind beryllium's penetrating radiation.", v:"expert", fb:"The neutron: uncharged, roughly a proton's mass, and deeply penetrating." },
          { t:"A new form of gamma ray far more energetic than any seen before from beryllium.", v:"wrong", fb:"The gamma explanation failed the energy bookkeeping; it was a particle." },
          { t:"A ray so penetrating that no shielding can stop it or contain a reactor's core.", v:"danger", fb:"Neutrons are shielded routinely by water and concrete; not unstoppable." },
          { t:"A second kind of electron, negatively charged but far heavier than the ordinary one.", v:"partial", fb:"It carries no charge at all and is not any kind of electron." } ] },
        { q:"Why does the neutron's lack of charge matter?", o:[
          { t:"Feeling no repulsion, it enters nuclei easily, driving fission and the chain reaction.", v:"expert", fb:"No charge means no electrical barrier, so neutrons readily split fuel." },
          { t:"Being electrically neutral, it passes through everything and can never be controlled.", v:"danger", fb:"Neutrons are absorbed by rods and moderators; they are controllable." },
          { t:"Its neutrality lets it orbit the nucleus closely, holding the whole atom tightly together.", v:"wrong", fb:"Neutrons live in the nucleus, not in orbit; charge is a separate matter." },
          { t:"It makes the neutron heavy, which is why it can knock protons loose on contact.", v:"partial", fb:"Mass and charge are distinct; its neutrality is what eases nuclear capture." } ] },
        { q:"Why is the neutron central to this inquiry?", o:[
          { t:"Reactor power is a neutron population, and detectors record its explosive rise.", v:"expert", fb:"The flux trace is a physical fingerprint of the excursion, second by second." },
          { t:"A neutron surge can only come from an intruder deliberately pulling the core apart.", v:"danger", fb:"A power excursion is neutron multiplication, not the mark of a saboteur." },
          { t:"Neutrons cannot be counted quickly, so the runaway left no usable record behind.", v:"wrong", fb:"Neutron detectors respond in milliseconds; the rise was recorded in detail." },
          { t:"Only the final dose matters; the neutron history adds nothing to the board's picture.", v:"partial", fb:"The flux record is precisely what tells a physical runaway from tampering." } ] }
      ] },
    // cell: The Health Physicist @ The Reactor Control Room
    fission:{ sci:"Lise Meitner (1878-1968)", topic:"Nuclear fission", lede:"The exile who worked out, walking in the Swedish snow, that a uranium nucleus had split in two.", no:4,
      profile:"Lise Meitner spent three decades as Otto Hahn's physics partner in Berlin before the phenomenon at the heart of this case bore her interpretation. An Austrian physicist of Jewish heritage, she was forced to flee Germany in 1938 as the Nazis closed in, escaping to Sweden with almost nothing. From exile she kept up a correspondence with Hahn, who had found something he could not explain: bombarding uranium with neutrons produced barium, an element little more than half uranium's size. Chemistry said it was there; physics said it was impossible.\n\nOver Christmas 1938, walking in the snow with her nephew Otto Frisch, Meitner did the calculation. Picturing the nucleus as a wobbling liquid drop, she saw that an unstable uranium nucleus could pinch in the middle and split in two. The fragments would fly apart with enormous energy, and — using Einstein's mass-energy relation — she found that the tiny mass lost in the split accounted for about 200 million electron-volts of energy per event. Frisch named it 'fission,' borrowing the biologists' word for a dividing cell. The 1944 Nobel Prize in Chemistry went to Hahn alone; Meitner's exclusion is remembered as one of the field's great injustices. She also refused, on principle, to work on the atomic bomb.\n\nFor this board, Meitner explains the reactor's fuel and its danger in one stroke. Every watt the Thornbury core produced came from uranium nuclei splitting, each release freeing more neutrons to split more nuclei. A runaway is simply that process multiplying faster than it is removed — lawful physics, not a random fluke and not an outsider's doing. Meitner reconstructed an invisible event from evidence and calculation, which is exactly what a sound inquiry must do rather than reach for a sensational story.",
      frame:"The Health Physicist lays out two graphs. \"The power and the fission-product counts have to agree, and they do. Convince me you know what fission is, and I'll walk you through them.\"",
      q:[
        { q:"What did Meitner and Frisch conclude about uranium?", o:[
          { t:"That the nucleus splits into lighter nuclei, releasing energy and more neutrons.", v:"expert", fb:"The nucleus divides — fission — freeing energy and neutrons for a chain." },
          { t:"That uranium is so unstable it could detonate at the slightest touch or vibration.", v:"danger", fb:"Fission needs a neutron to start; uranium does not go off from a touch." },
          { t:"That uranium slowly decays into barium by emitting a long chain of alpha particles.", v:"wrong", fb:"Barium comes from splitting, not a slow alpha-decay chain." },
          { t:"That neutrons chip small fragments off the nucleus without truly dividing it in two.", v:"partial", fb:"The nucleus genuinely splits roughly in half; it is not merely chipped." } ] },
        { q:"Where does fission's energy come from?", o:[
          { t:"The fragments weigh slightly less than the original, and that lost mass becomes energy.", v:"expert", fb:"Mass lost in the split converts to energy by E=mc2, about 200 MeV each." },
          { t:"The neutrons carry chemical energy stored in the bonds holding the nucleus together.", v:"wrong", fb:"Nuclei are bound by nuclear forces, not chemical bonds; mass is the source." },
          { t:"A hidden store of energy that only a deliberately built trigger can release from uranium.", v:"danger", fb:"The energy releases whenever a neutron splits a nucleus; no saboteur needed." },
          { t:"The heat of the neutrons striking the nucleus, added up over many collisions.", v:"partial", fb:"Collision heat is negligible; the energy is the mass difference converted." } ] },
        { q:"Why does fission matter to this inquiry?", o:[
          { t:"The reactor's power is fission, so a runaway is that same process multiplying too fast.", v:"expert", fb:"A runaway is fission outrunning its controls — lawful physics, not a fluke." },
          { t:"A fission burst on this scale can only be the work of someone arming the core.", v:"danger", fb:"An excursion is the chain reaction itself, not an intruder arming anything." },
          { t:"Fission is far too gentle to run away, so the surge must have some outside cause.", v:"wrong", fb:"Fission can absolutely run away if reactivity climbs; that is the whole risk." },
          { t:"Fission explains the heat but says nothing about how fast the power can climb.", v:"partial", fb:"Fission physics sets the timescale of the surge precisely, via the neutrons." } ] }
      ] },
    // cell: The Clerk @ The Reactor Control Room
    fissionchem:{ sci:"Otto Hahn (1879-1968)", topic:"The chemistry of fission", lede:"The meticulous radiochemist who found barium where uranium should have been — and could not believe his own flawless result.", no:5,
      profile:"Otto Hahn is often called the father of nuclear chemistry, and it was his chemistry that caught nuclear fission in the act. A meticulous German radiochemist, he had worked with Lise Meitner in Berlin for thirty years, discovering the element protactinium and the phenomenon of nuclear isomerism along the way. In December 1938, with his assistant Fritz Strassmann, he bombarded uranium with neutrons and set out to identify what was produced.\n\nThe result baffled him. Among the products was barium — an element barely more than half the mass of uranium. Hahn's radiochemistry was too careful to be wrong: he could separate and identify the barium beyond doubt. But as a chemist he could not say how a uranium nucleus could shed so much of itself, and he wrote to Meitner in exile for help. Her physics supplied the answer — the nucleus had split — while his chemistry supplied the proof. He received the 1944 Nobel Prize in Chemistry for the discovery, an award that painfully omitted Meitner. After the war he spoke out against nuclear weapons and led German science as head of the Max Planck Society.\n\nFor this board, Hahn embodies evidence over assertion. Fission does not merely release energy; it leaves ash — a specific inventory of lighter elements, the fission products, each a chemical fingerprint of a nucleus that split. The mix and the amounts record how much fission occurred and under what conditions. From the debris in a wrecked core, a radiochemist can reconstruct the event as surely as Hahn read barium out of his uranium. That is the opposite of guessing at sabotage: the chemistry testifies to a power excursion, a physical process with a traceable, quantitative signature that no intruder's story can imitate.",
      frame:"The Clerk squares a folder on the desk. \"Every claim in this inquiry needs a paper behind it. The fission products are the paper the core kept on itself. Show me you can read that chemistry.\"",
      q:[
        { q:"What did Hahn and Strassmann prove?", o:[
          { t:"That barium, far lighter than uranium, was among the products — proof the nucleus split.", v:"expert", fb:"Barium's presence was the chemical proof that uranium nuclei had divided." },
          { t:"That the uranium sample had been chemically poisoned by someone deliberately tampering with it.", v:"danger", fb:"The barium came from fission, not contamination; the chemistry was clean." },
          { t:"That uranium turns to lead through the ordinary chain of natural radioactive decay.", v:"wrong", fb:"Natural decay ends at lead slowly; this was prompt splitting into barium." },
          { t:"That a new element heavier than uranium had been created by the added neutrons.", v:"partial", fb:"Transuranics were the expectation; the shock was a much lighter product." } ] },
        { q:"Why was identifying the products so difficult?", o:[
          { t:"The fission products were tiny traces mixed together, needing painstaking separation.", v:"expert", fb:"Minute quantities amid many others demanded exacting radiochemistry." },
          { t:"The products were radioactive gases that escaped before they could be weighed.", v:"wrong", fb:"Most fission products are solids; careful chemistry pinned them down." },
          { t:"The samples were so dangerous that no chemist could safely approach them at all.", v:"danger", fb:"The quantities were minute and workable; skill, not danger, was the barrier." },
          { t:"The products decayed within seconds, leaving nothing behind to analyze at leisure.", v:"partial", fb:"Many products persist long enough to identify; separation was the real task." } ] },
        { q:"Why does fission chemistry matter to this inquiry?", o:[
          { t:"Fission products fingerprint how much fission occurred, letting the board reconstruct it.", v:"expert", fb:"The product inventory records the excursion's size and course quantitatively." },
          { t:"Any fission products found in the room prove a device was smuggled in and detonated.", v:"danger", fb:"Fission products come from the fuel splitting in the core, not from any bomb." },
          { t:"The debris tells the board nothing, since fission products look identical for every fault.", v:"wrong", fb:"Product ratios vary with the event and reveal its specific history." },
          { t:"The chemistry gives the fuel's age but reveals nothing about the night in question.", v:"partial", fb:"The inventory dates the fuel and quantifies the surge that occurred." } ] }
      ] },
    // cell: The Clerk @ The Reactor Control Room
    chainreaction:{ sci:"Leo Szilard (1898-1964)", topic:"The chain reaction", lede:"The restless Hungarian who imagined the self-feeding atomic fire at a London traffic light, years before anyone split an atom.", no:6,
      profile:"Leo Szilard imagined the chain reaction before anyone had split an atom on purpose. A restless Hungarian physicist, he was waiting at a London traffic light in September 1933, brooding on Rutherford's dismissal of atomic power as 'moonshine,' when the idea struck him: if some element could be found that emitted two neutrons for every one it absorbed while splitting, then a mass of it could sustain a reaction that fed on itself, multiplying and releasing vast energy. He patented the concept of the neutron chain reaction in 1934, and — grasping its military potential — quietly assigned the patent to the British Admiralty to keep it secret.\n\nWhen fission was discovered in 1938, Szilard immediately saw that uranium might be the element he had imagined. He confirmed that fission released extra neutrons, drafted the 1939 letter that Einstein signed to warn President Roosevelt, and worked with Enrico Fermi to design and build the first reactor. Yet he was also the conscience of the project: he later circulated a petition urging that the bomb not be used on cities, and spent his last years campaigning for arms control.\n\nFor this board, Szilard defines the danger precisely. A reactor is a chain reaction held exactly at balance — each fission provoking, on average, just one more. Push it so that each fission causes slightly more than one, and the population climbs; let the fast 'prompt' neutrons alone carry it past balance, and it explodes in a fraction of a second. Szilard understood this from the start, which is why a runaway is not an act of God: it is the known failure mode of the very thing being operated. And because multiplication is a physical quantity, the surge it produced is written in the record, not in an intruder's footprints.",
      frame:"The Clerk taps a filed patent. \"Men have known this machine could bite since before it existed. If you think what happened here was a bolt from the blue, you don't yet understand the chain reaction.\"",
      q:[
        { q:"What did Szilard conceive in 1933?", o:[
          { t:"A self-sustaining chain reaction, each fission releasing neutrons that split more nuclei.", v:"expert", fb:"One fission feeding the next is the self-sustaining chain reaction." },
          { t:"A bomb that any small nation could cheaply assemble from a handful of ordinary uranium ore.", v:"danger", fb:"He conceived the chain reaction itself; weaponizing it came much later." },
          { t:"A way to draw energy from the atom slowly and gently, with no risk of any surge.", v:"wrong", fb:"He saw at once that the chain could also run away, not only run gently." },
          { t:"A single fission releasing enough energy at once to level a city on its own.", v:"partial", fb:"A single fission is minute; the power comes from multiplication over many." } ] },
        { q:"What decides whether a chain reaction grows?", o:[
          { t:"The multiplication factor: whether each fission causes on average more than one more.", v:"expert", fb:"If it exceeds one the population climbs; at one it holds; below one it dies." },
          { t:"The purity of the uranium alone, so any impurity makes an explosion certain.", v:"danger", fb:"Purity affects reactivity, but the deciding quantity is multiplication." },
          { t:"The outside temperature, since a chain reaction can only start when the fuel is hot.", v:"wrong", fb:"Chain reactions run cold or hot; temperature is not the trigger." },
          { t:"The total amount of fuel present, regardless of how the neutrons are behaving.", v:"partial", fb:"Geometry and absorbers matter as much as mass; k captures them all." } ] },
        { q:"Why does the chain reaction matter to this inquiry?", o:[
          { t:"A reactor is a chain held at balance, so a runaway is a known, foreseeable failure.", v:"expert", fb:"Tipping past balance is the reactor's built-in danger, not an act of God." },
          { t:"Only sabotage could tip a balanced chain reaction, since it cannot slip on its own.", v:"danger", fb:"Reactivity can rise from voids, heat, or rod motion — no saboteur required." },
          { t:"A chain reaction cannot exceed balance, so the reported surge simply did not happen.", v:"wrong", fb:"A chain can and does exceed balance; that is precisely an excursion." },
          { t:"The chain explains the steady power but not how the excursion could accelerate.", v:"partial", fb:"Reactivity feedbacks set the acceleration; the chain governs both." } ] }
      ] },
    // cell: Operator Nadia Sorel @ The Reactor Hall & Core
    firstpile:{ sci:"Enrico Fermi (1901-1954)", topic:"The first controlled pile", lede:"The Italian navigator who lit the first nuclear fire beneath a football stadium — and proved a chain reaction could be tamed.", no:7,
      profile:"Enrico Fermi built the first nuclear reactor and proved that a chain reaction could be tamed. An Italian physicist of extraordinary range — equally gifted in theory and experiment — he had already won the 1938 Nobel Prize for creating radioactive isotopes by neutron bombardment and for discovering that slow neutrons are far more effective at splitting nuclei. He used the prize trip to Stockholm to escape Fascist Italy with his Jewish wife and emigrate to the United States.\n\nAt the University of Chicago, beneath the stands of an unused football field, Fermi and his team assembled Chicago Pile-1: a lattice of graphite blocks and lumps of uranium, studded with cadmium-coated control rods. The graphite slowed the neutrons so they would split more uranium; the rods, which soak up neutrons, held the reaction in check. On December 2, 1942, Fermi ordered the rods withdrawn a measured step at a time, watching the neutron count climb and level off exactly as his slide-rule predicted, until the pile sustained its own chain reaction for the first time in history. He kept it critical for less than half an hour, then ordered the rods back in.\n\nFor this board, Fermi's pile is the founding proof that a chain reaction is not a wild force but a controllable one. Control came from the rods and from a sliver of timing grace built into fission itself, and Fermi advanced only as fast as his measurements let him. A reactor that runs away has lost that control — and control is lost for physical, understandable reasons rooted in the design, not by fate and not by a phantom. Fermi's discipline was to move one careful step at a time and never past what the numbers allowed; a night-shift test that pushed a core past its margins is the exact opposite of how he worked.",
      frame:"Nadia stands at the rail above the core. \"Fermi ran the first one of these by hand and never let it get ahead of him. That's how I was trained. Show me you know how the first pile was held in check.\"",
      q:[
        { q:"What did Fermi achieve on December 2, 1942?", o:[
          { t:"The first controlled, self-sustaining chain reaction, in a graphite-and-uranium pile.", v:"expert", fb:"A controlled, self-sustaining pile — the first working reactor." },
          { t:"The first nuclear explosion, a small test blast beneath a Chicago football stadium.", v:"danger", fb:"It was controlled and released little energy; there was no explosion." },
          { t:"The first electricity generated from atomic fission, lighting a single small bulb.", v:"wrong", fb:"CP-1 produced no electricity; it proved a controlled chain reaction." },
          { t:"The first proof that uranium fissions, by detecting barium among the products.", v:"partial", fb:"Fission was already known; Fermi proved it could be self-sustaining." } ] },
        { q:"How did Fermi control the pile?", o:[
          { t:"With neutron-absorbing rods, withdrawn or inserted to hold multiplication at one.", v:"expert", fb:"Cadmium rods soaked up neutrons; their position set the reactivity." },
          { t:"By flooding it with water the instant the neutron count began to rise at all.", v:"danger", fb:"CP-1 had no such flood system; control was by the movable rods." },
          { t:"By limiting the uranium so tightly that the reaction could never quite sustain.", v:"wrong", fb:"The pile was built to just reach critical; rods controlled it." },
          { t:"By adjusting the graphite blocks between runs to tune how fast neutrons moved.", v:"partial", fb:"Graphite was fixed once built; the rods did the moment-to-moment control." } ] },
        { q:"Why does the first pile matter to this inquiry?", o:[
          { t:"It proved a chain reaction is controllable, so lost control points to the machine.", v:"expert", fb:"Control is real physics; losing it has design causes, not fated ones." },
          { t:"It proved reactors are so stable that only sabotage could ever make one run away.", v:"danger", fb:"Reactors can be tipped by their own feedbacks; sabotage is not required." },
          { t:"It proved reactors are inherently wild, so any accident is simply bad luck.", v:"wrong", fb:"The pile showed control is achievable; a runaway means control was lost." },
          { t:"It showed reactors make heat, which tells the board little about the accident.", v:"partial", fb:"The pile's lesson is controllability, which bears directly on this case." } ] }
      ] },
    // cell: Operator Nadia Sorel @ The Reactor Hall & Core
    dropmodel:{ sci:"Niels Bohr (1885-1962)", topic:"The liquid-drop nucleus & fission", lede:"The Copenhagen master who pictured the nucleus as a trembling droplet — and saw at a glance why uranium splits.", no:8,
      profile:"Niels Bohr gave physics the picture that explains why a nucleus splits. The towering Danish theorist had already won the 1921 Nobel Prize for his quantum model of the atom, in which electrons occupy fixed energy levels, and his Copenhagen institute was the gravitational center of the new physics. In the 1930s he championed the liquid-drop model of the nucleus: the idea that a nucleus behaves like a droplet of charged fluid, held together by a surface-tension-like force that fights the mutual electrical repulsion of its protons.\n\nWhen fission was announced in early 1939, Bohr saw at once how the drop model explained it. Absorbing a neutron sets the drop wobbling; if it stretches into a dumbbell shape far enough, electrical repulsion wins over surface tension and the drop snaps in two. Working with the young John Wheeler at Princeton, Bohr produced a landmark paper that same year showing that it is the rare isotope uranium-235 that fissions readily when it captures a slow neutron, while the common uranium-238 largely does not. That distinction — which isotope, which neutron energy — underlies every reactor's fuel and moderator design.\n\nFor this board, Bohr's drop model turns fission from a marvel into a calculation. It says which nuclei will split, and under what conditions, and how much energy each split will yield. A reactor is an engineered application of exactly that theory: arrange the fuel, slow the neutrons to the energies that split uranium-235, and the machine's behavior follows predictably from the physics. When such a machine surges, the surge obeys the same understood rules. Bohr's lesson for an inquiry is that the nucleus is not capricious; its behavior can be reasoned out in advance, which is why a runaway is a foreseeable consequence rather than an inexplicable stroke of misfortune.",
      frame:"Nadia points at the fuel channels. \"People treat the core like a magic box. It isn't — Bohr worked out on paper which atoms split and when. Prove you understand that before we talk about what my core did.\"",
      q:[
        { q:"What does the liquid-drop model picture a nucleus as?", o:[
          { t:"A charged drop, held by surface tension against the repulsion of its own protons.", v:"expert", fb:"Surface tension versus proton repulsion is the drop model in a phrase." },
          { t:"A tightly wound spring that releases all its energy the instant it is disturbed.", v:"danger", fb:"It is not a coiled spring; a neutron must be captured to trigger fission." },
          { t:"A miniature solar system of protons orbiting a heavy central neutron core.", v:"wrong", fb:"Nucleons are packed, not orbiting; the drop is a fluid, not a solar system." },
          { t:"A rigid crystal of particles that shatters cleanly whenever it is struck hard.", v:"partial", fb:"The nucleus flows and deforms like a liquid; it is not a brittle crystal." } ] },
        { q:"What did Bohr and Wheeler establish about uranium?", o:[
          { t:"That the rare isotope uranium-235 fissions with slow neutrons; uranium-238 mostly does not.", v:"expert", fb:"U-235 is the fissile isotope split by slow neutrons; U-238 largely resists." },
          { t:"That any uranium at all will detonate if enough neutrons strike it fast enough.", v:"danger", fb:"Only U-235 fissions readily; bulk natural uranium will not detonate." },
          { t:"That uranium-238 is the fissile isotope, which is exactly why natural uranium is so common.", v:"wrong", fb:"U-235, not U-238, is the fissile one; that is the point of the paper." },
          { t:"That fission needs extremely fast neutrons, which only a reactor can produce.", v:"partial", fb:"Slow neutrons split U-235 best, which is why reactors moderate them." } ] },
        { q:"Why does the drop model matter to this inquiry?", o:[
          { t:"It makes fission predictable, so a reactor's behavior is theory, not a mystery.", v:"expert", fb:"Predictable fission means a surge is foreseeable, not inexplicable luck." },
          { t:"It proves fission is so unpredictable that any accident defies all explanation.", v:"danger", fb:"The drop model makes fission calculable, the opposite of unpredictable." },
          { t:"It applies only to bombs, so it tells the board nothing about a power reactor.", v:"wrong", fb:"The same physics governs reactors; it is not confined to weapons." },
          { t:"It explains the energy released but not which conditions bring on a surge.", v:"partial", fb:"The model also sets the conditions for fission, bearing on the surge." } ] }
      ] },
    // cell: The Health Physicist @ The Reactor Hall & Core
    reactorphysics:{ sci:"Eugene Wigner (1902-1995)", topic:"Reactor physics & the Wigner effect", lede:"The theorist who became a reactor engineer and catalogued the core's hidden traps — stored energy and the poison that chokes a chain.", no:9,
      profile:"Eugene Wigner was the rare theorist who also became a reactor engineer, and the phenomena that bear his mark sit close to this case. A Hungarian-American physicist who would win the 1963 Nobel Prize for his work on symmetry in physics, Wigner turned during the war to designing the giant Hanford reactors that produced plutonium — arguably the first person to treat reactor design as a full engineering discipline rather than a physics experiment.\n\nTwo of his contributions matter here. The first is the Wigner effect: intense neutron bombardment knocks carbon atoms out of their normal positions in a graphite moderator, storing potential energy in the disordered lattice. If enough accumulates, it can be released suddenly as heat — a hazard behind the 1957 Windscale reactor fire. The second is his insight into fission-product poisoning. When the first Hanford reactor started up and then mysteriously died back hours later, Wigner and Fermi recognized the culprit: xenon-135, a fission product that is one of the most voracious neutron absorbers known. It builds up when power falls and smothers the chain reaction, then slowly burns off. Wigner had prudently designed in spare fuel channels, which saved the project.\n\nFor this board, Wigner's work is a catalogue of the reactor's hidden traps — effects that are subtle but entirely known and predictable to those who study them. A reactor sitting in a deeply xenon-poisoned, low-power state is in a treacherous condition: the poison must be overridden to restore power, and doing so carelessly can leave the core primed to surge once the xenon burns away. None of this is mysterious. It is textbook reactor physics. That is why an excursion reached during an ill-advised test is a foreseeable outcome rather than a freak of nature — the warnings were written into the science decades before.",
      frame:"The Health Physicist unrolls a chart of xenon curves. \"The core was in a state a first-year student is taught to respect. If you think this was simply bad luck, you haven't met the physics yet. Let me test you.\"",
      q:[
        { q:"What is the Wigner effect?", o:[
          { t:"Neutron bombardment displaces graphite atoms, storing energy later freed as heat.", v:"expert", fb:"Displaced atoms store 'Wigner energy' that can later be freed as heat." },
          { t:"Radiation makes the graphite so unstable it can explode without any warning at all.", v:"danger", fb:"The stored energy releases as heat, not as a spontaneous explosion." },
          { t:"Neutrons make the graphite intensely radioactive, which is its only real hazard.", v:"wrong", fb:"Induced activity is separate; the Wigner effect is stored lattice energy." },
          { t:"Irradiation gradually crumbles the graphite moderator to dust, weakening the core.", v:"partial", fb:"The lattice disorders and stores energy; it does not simply crumble." } ] },
        { q:"What is xenon poisoning?", o:[
          { t:"Xenon-135, a fission product and strong neutron absorber, builds up and chokes the chain.", v:"expert", fb:"Xenon-135 absorbs neutrons voraciously, suppressing power after a drop." },
          { t:"A leak of xenon gas into the reactor hall that would swiftly poison anyone working nearby.", v:"danger", fb:"Xenon poisoning is neutronic, not a toxic gas hazard to workers." },
          { t:"A slow chemical corrosion of the fuel rods by xenon gas released during operation.", v:"wrong", fb:"It is neutron absorption, not chemical corrosion of the rods." },
          { t:"A buildup of ash in the fuel that gradually lowers how much heat the core can make.", v:"partial", fb:"It is specifically neutron absorption by xenon-135, not generic ash." } ] },
        { q:"Why does reactor physics matter to this inquiry?", o:[
          { t:"These effects are known, so a poisoned or over-stressed core is a foreseeable hazard.", v:"expert", fb:"Xenon and stored energy are textbook; the hazard was predictable, not fated." },
          { t:"These effects are so obscure that no working operator could have seen the danger coming.", v:"danger", fb:"These effects are standard curriculum; the danger was well understood." },
          { t:"These effects vanish entirely at full power, so they had no bearing on the night's events.", v:"wrong", fb:"Xenon poisoning is worst at low power, exactly the test condition here." },
          { t:"These effects change the dose but not the odds of the reactor running away.", v:"partial", fb:"These effects directly shape reactivity and the chance of an excursion." } ] }
      ] },
    // cell: The Health Physicist @ The Reactor Hall & Core
    reactoreng:{ sci:"Walter Zinn (1906-2000)", topic:"Reactor engineering & control", lede:"The man who pulled the last rod on the world's first reactor, then spent his life turning the pile into an engineered machine.", no:10,
      profile:"Walter Zinn turned the reactor from a physicist's pile into an engineered machine. A Canadian-American physicist, he stood beside Fermi at Chicago Pile-1 in 1942 — it was Zinn who pulled out the last control rod to bring the world's first reactor to life. He went on to become the founding director of Argonne National Laboratory and the leading figure in early reactor engineering, designing a whole series of experimental reactors and thinking hard about how to make them useful and safe.\n\nHis masterpiece was Experimental Breeder Reactor I, which in 1951 became the first reactor to generate usable electricity, lighting a string of bulbs, and the first to 'breed' more fuel than it consumed. Zinn also built the prototype that led to the naval reactor. But he learned the hazards firsthand: in 1955 EBR-I suffered a partial fuel meltdown during a deliberate test, when the metal fuel bowed under heat and briefly increased reactivity — a self-reinforcing feedback that ran faster than the operators expected. Zinn's teams studied that failure and folded its lessons into safer designs.\n\nFor this board, Zinn is the engineer's conscience. A reactor stays controllable only because its control system is deliberately engineered to make it so: neutron-absorbing rods that can be driven in, a fast automatic shutdown, and feedbacks arranged so that a rise in power tends to damp itself rather than amplify. Get those wrong — build in a feedback that reinforces instead of resists, or a rod that misbehaves at the worst moment — and the same machine becomes a trap. EBR-I showed that even a careful test can find such a flaw. That is why a reactor running away during a night-shift test is not a supernatural event: it is engineering, and engineering can be examined, blamed, and fixed.",
      frame:"The Health Physicist watches the coolant gauges. \"A reactor is only as safe as the control system someone drew. If a rod can do the wrong thing at the wrong instant, that's not fate — that's engineering. Let's see what you know.\"",
      q:[
        { q:"What was Zinn's EBR-I?", o:[
          { t:"The first reactor to make usable electricity, and the first to breed its own fuel.", v:"expert", fb:"EBR-I lit bulbs in 1951 and bred more fuel than it burned." },
          { t:"The first reactor to explode in a test, proving the technology far too dangerous.", v:"danger", fb:"EBR-I's 1955 partial melt was a studied test result, not a proof of doom." },
          { t:"The first reactor cooled entirely by air, needing no water or metal coolant at all.", v:"wrong", fb:"EBR-I was liquid-metal cooled; its firsts were electricity and breeding." },
          { t:"The first reactor built purely to test materials, never meant to produce any power.", v:"partial", fb:"EBR-I generated real electricity; it was more than a materials rig." } ] },
        { q:"How does a control system hold a reactor steady?", o:[
          { t:"With absorber rods, a fast automatic shutdown, and feedbacks that damp rising power.", v:"expert", fb:"Rods, scram, and self-damping feedback together keep reactivity in check." },
          { t:"By sealing the core so tightly that no change in conditions can reach the fuel.", v:"danger", fb:"Feedbacks and rods manage a reactor; sealing it off is not control." },
          { t:"By keeping the fuel cold, since a chain reaction cannot proceed below a set heat.", v:"wrong", fb:"Chain reactions run cold or hot; control is by absorbers and feedback." },
          { t:"By adjusting the coolant flow, which alone sets how fast the reactor can run.", v:"partial", fb:"Coolant flow matters, but rods and reactivity feedback do the controlling." } ] },
        { q:"Why does reactor engineering matter to this inquiry?", o:[
          { t:"Control depends on the design, so a flawed rod or feedback can make control dangerous.", v:"expert", fb:"A misdesigned feedback or rod can turn a safe action into an excursion." },
          { t:"Control systems never fail by themselves, so a reactor lost like this means an outside hand.", v:"danger", fb:"Control can fail through design flaws in the feedbacks or rods, not sabotage." },
          { t:"Control is purely the operator's skill, so any runaway is simply human error.", v:"wrong", fb:"Even a skilled operator cannot beat a control system engineered to misbehave." },
          { t:"Control depends only on the coolant, which had nothing to do with the surge.", v:"partial", fb:"Reactivity feedbacks and rods, not coolant alone, govern control here." } ] }
      ] },
    // cell: The Clerk @ The Reactor Hall & Core
    betadecay:{ sci:"Chien-Shiung Wu (1912-1997)", topic:"Beta decay & precision measurement", lede:"The 'First Lady of Physics' who overturned a law of nature by refusing to trust anything she had not measured to the last decimal.", no:11,
      profile:"Chien-Shiung Wu was the most exacting experimental physicist of her generation, and her craft is the standard an inquiry should hold itself to. Born near Shanghai and educated at Berkeley, she became known as the 'First Lady of Physics.' During the war she joined the Manhattan Project, where her doctoral expertise proved unexpectedly vital: when the first Hanford production reactor started up and then died back, it was Wu's earlier measurements of xenon-135 as a fission product — and of how ferociously it absorbs neutrons — that helped explain the poisoning that was choking the chain reaction.\n\nHer most celebrated work came in 1956. Two theorists, Lee and Yang, proposed that the weak interaction governing beta decay might violate 'parity' — that nature might, at the deepest level, tell left from right. Most physicists thought it absurd. Wu designed and executed a beautifully controlled experiment, cooling cobalt-60 nuclei to near absolute zero and aligning their spins, and showed that the electrons from beta decay flew off preferentially in one direction. Parity was violated. Lee and Yang won the Nobel Prize; Wu, whose experiment proved them right, was passed over — a famous oversight.\n\nFor this board, Wu offers method as much as physics. Beta decay is the process by which a neutron in a nucleus turns into a proton, spitting out an electron and a neutrino; it is also how fission products transform, giving rise both to the delayed neutrons that make a reactor controllable and to poisons like xenon. But Wu's deeper lesson is discipline: she trusted no result until every variable was pinned down. A board tempted by a quick, dramatic answer — sabotage — or a quick, comforting one — a fluke — should remember that Wu overturned a law of physics only because she refused to accept anything she had not measured to the last decimal.",
      frame:"The Clerk lines up three signed statements. \"Two of these can't both be true. Wu would have measured her way to the answer and trusted nothing else. Show me you can be that careful about beta decay.\"",
      q:[
        { q:"What did Wu's 1956 experiment demonstrate?", o:[
          { t:"That beta decay violates parity — nature can tell left from right at the deepest level.", v:"expert", fb:"Aligned cobalt-60 sent electrons one way — parity is not conserved." },
          { t:"That radioactive atoms can be made to decay on command by cooling them near zero.", v:"danger", fb:"Cooling aligned the spins; it did not trigger decay on command." },
          { t:"That beta particles travel faster than light when a nucleus is chilled enough.", v:"wrong", fb:"Nothing exceeds light speed; she measured a directional asymmetry." },
          { t:"That cobalt-60 emits electrons equally in every direction, as symmetry demands.", v:"partial", fb:"The whole point was that emission was not symmetric; parity failed." } ] },
        { q:"What is beta decay?", o:[
          { t:"A nucleus turns a neutron into a proton, emitting an electron and a neutrino.", v:"expert", fb:"Neutron-to-proton conversion emits a beta electron and a neutrino." },
          { t:"A nucleus violently bursts apart, scattering protons and neutrons in all directions.", v:"danger", fb:"That is fission or fragmentation; beta decay changes just one nucleon." },
          { t:"A nucleus absorbs an electron from its innermost orbit and grows one unit heavier.", v:"wrong", fb:"That is electron capture; ordinary beta-minus emits an electron instead." },
          { t:"A nucleus sheds a helium nucleus, dropping two protons and two neutrons at once.", v:"partial", fb:"That is alpha decay; beta decay involves no helium nucleus." } ] },
        { q:"Why does Wu's precision matter to this inquiry?", o:[
          { t:"She trusted only measured facts, the standard for rejecting a convenient story here.", v:"expert", fb:"Measure everything, assume nothing — that discipline rejects both traps." },
          { t:"Her work proves reactors are unpredictable, so no accident can truly be explained.", v:"danger", fb:"Wu made physics more predictable, not less; her rigor cuts against 'fluke.'" },
          { t:"Her parity result already settles the cause of the accident, with no further inquiry needed.", v:"wrong", fb:"Parity has no bearing on the cause; her method, not her result, applies." },
          { t:"Her rigor matters only in a laboratory, not in a working reactor investigation.", v:"partial", fb:"Her method applies exactly here: reconstruct the event from hard evidence." } ] }
      ] },
    // cell: The Clerk @ The Reactor Hall & Core
    navalreactor:{ sci:"Hyman Rickover (1900-1986)", topic:"The naval reactor & safety culture", lede:"The abrasive admiral who built the nuclear navy and a safety culture so relentless it ran for decades without a single reactor accident.", no:12,
      profile:"Hyman Rickover built the nuclear navy and, with it, the most demanding safety culture the reactor world has known. A hard-driving, famously abrasive U.S. Navy engineer, he grasped in the late 1940s that a compact reactor could give a submarine unlimited underwater endurance. Against fierce institutional resistance he forced through the development of the pressurized-water reactor, and in 1955 the USS Nautilus signaled 'underway on nuclear power.' He effectively seeded the civilian pressurized-water industry as well, since the first commercial plant at Shippingport grew from his program.\n\nBut Rickover's deepest legacy was not a machine; it was a way of working. He personally interviewed thousands of officer candidates, demanded that every person understand their system to the bolt, insisted on conservative design with wide margins, and cultivated a relentless 'questioning attitude' in which anyone could halt an operation over a doubt. He punished complacency and rewarded the engineer who admitted a problem. Under his standards the naval reactor program ran for decades without a reactor accident — an almost unbelievable record in a dangerous technology.\n\nFor this board, Rickover is the measuring stick for everything that failed at Thornbury. His entire philosophy was that reactor accidents are not bad luck but the predictable fruit of shortcuts: undocumented tests, thin margins, unreported flaws, a culture that lets people run a machine they do not fully understand or that pressures them to keep quiet. A night-shift test pushed past the reactor's limits, on a machine whose designers had not disclosed everything they knew, is the precise opposite of the Rickover standard. Where his program treated every doubt as a stop signal, Thornbury treated a known hazard as a secret. That contrast tells the board this was no freak of nature and needed no saboteur — it was a safety culture that had already been hollowed out.",
      frame:"The Clerk sets down a thin test log. \"Rickover would have stopped this test cold — no proper paperwork, no margin, questions unanswered. That it went ahead tells you something. Show me you understand what he built.\"",
      q:[
        { q:"What did Rickover create?", o:[
          { t:"The nuclear navy — the first practical naval reactor and an exacting safety culture.", v:"expert", fb:"Nautilus and a rigorous safety culture were Rickover's twin legacies." },
          { t:"The atomic bomb used at sea, giving submarines a devastating first-strike weapon.", v:"danger", fb:"He built propulsion reactors, not weapons; the reactor drove the ship." },
          { t:"The first civilian power reactor, built with no involvement from the armed forces.", v:"wrong", fb:"Civilian Shippingport grew directly from Rickover's naval program." },
          { t:"The pressurized-water reactor design, though he left safety practice to others.", v:"partial", fb:"He drove the PWR and the safety culture; the two were inseparable to him." } ] },
        { q:"What defined Rickover's safety culture?", o:[
          { t:"Conservative design, deep competence, constant questioning, and firm accountability.", v:"expert", fb:"Margins, mastery, a questioning attitude, and accountability defined it." },
          { t:"Absolute secrecy, so that no flaw or incident was ever written down or shared.", v:"danger", fb:"He demanded openness about problems; secrecy is the opposite of his way." },
          { t:"Sheer speed and low cost above all, trusting operators to catch any problem in the moment.", v:"wrong", fb:"He prized margins over speed and cost, and never trusted luck." },
          { t:"Heavy automation, so that trained crews were no longer needed to run the plant.", v:"partial", fb:"He insisted crews master their systems; automation did not replace them." } ] },
        { q:"Why does naval safety culture matter here?", o:[
          { t:"A disciplined culture prevents such accidents, so a runaway means the culture failed.", v:"expert", fb:"The spotless naval record shows accidents track culture, not fate." },
          { t:"The naval record proves reactors never fail, so this one must have been attacked.", v:"danger", fb:"Culture prevents accidents; its absence, not an attacker, explains this one." },
          { t:"Safety culture applies only to ships at sea, so it has no bearing on a land reactor here.", v:"wrong", fb:"The same principles govern any reactor, at sea or on land." },
          { t:"Good culture reduces paperwork errors but cannot affect the core physics itself.", v:"partial", fb:"Culture shapes design margins and test discipline — the physics of safety." } ] }
      ] },
    // cell: Operator Nadia Sorel @ The Design Authority's Office
    inherentsafety:{ sci:"Alvin Weinberg (1915-2006)", topic:"Reactor design & inherent safety", lede:"The Oak Ridge director who coined 'inherent safety' and warned that nuclear power is a Faustian bargain paid in permanent honesty.", no:13,
      profile:"Alvin Weinberg spent his life on the question this inquiry turns on: what makes a reactor safe by its very nature. An American physicist who directed Oak Ridge National Laboratory for eighteen years, he co-invented the pressurized-water reactor with Eugene Wigner and then became the technology's most thoughtful critic. He coined the phrase 'inherent safety' and argued that the ideal reactor is one whose own physics protects it — so that if power starts to rise, the reactor's response is to push reactivity down and quiet itself, with no operator and no active system required.\n\nWeinberg contrasted this with reactors that lean on engineered safeguards and human vigilance to stay out of trouble. He championed the molten-salt reactor precisely because he believed it failed safe. And he famously called nuclear energy a 'Faustian bargain': society gains an almost limitless energy source, but only if it commits to the long-term discipline, care, and honesty the technology demands, forever. Break that bargain — cut corners, hide problems — and the gift turns dangerous.\n\nFor this board, Weinberg names the fault line at the center of the case. A well-designed reactor has negative feedback: heat up, and reactivity drops. A dangerous reactor can have the reverse under some conditions — a positive feedback in which a rise in power or a change in coolant increases reactivity, driving power higher still. That is the opposite of inherent safety, and it is a property of the design, chosen or tolerated by whoever drew it. Weinberg would tell the board that if the Thornbury core could reinforce its own power under the conditions of that test, then no operator error and no outside enemy is needed to explain a runaway — the machine was built to be able to run away, and someone decided that was acceptable.",
      frame:"Nadia looks around the design office. \"Out here they decide whether the machine forgives a mistake or punishes it. I want to know which one they built. Tell me what inherent safety means.\"",
      q:[
        { q:"What is inherent (passive) safety?", o:[
          { t:"Physics that lowers reactivity as power rises, so the reactor quiets itself unaided.", v:"expert", fb:"Negative feedback means a power rise damps itself, with no action needed." },
          { t:"A reactor so heavily guarded that no accident of any kind is physically possible.", v:"danger", fb:"No reactor is accident-proof; inherent safety is self-damping physics." },
          { t:"A bank of backup pumps and diesels that switch on the instant anything goes wrong.", v:"wrong", fb:"Those are active safeguards; inherent safety needs no equipment to act." },
          { t:"A trained operator watching the gauges closely enough to catch every small rise in power.", v:"partial", fb:"Inherent safety works without an operator; it is built into the physics." } ] },
        { q:"What did Weinberg mean by a 'Faustian bargain'?", o:[
          { t:"Nuclear power gives great benefit but demands permanent discipline and honesty in return.", v:"expert", fb:"Great energy in exchange for lasting vigilance — that is the bargain." },
          { t:"Nuclear power is a pact with the devil that is certain to destroy whoever ever dares use it.", v:"danger", fb:"He meant sober commitment, not literal doom; discipline is the price." },
          { t:"Nuclear power is entirely free of cost once the first reactor has been fully built.", v:"wrong", fb:"The bargain is ongoing care, not a one-time cost; vigilance never ends." },
          { t:"Nuclear power is risky only for the first generation, then becomes wholly safe.", v:"partial", fb:"The vigilance he demanded is permanent, not a passing phase." } ] },
        { q:"Why does inherent safety matter to this inquiry?", o:[
          { t:"A positive feedback under some conditions means a surge can grow instead of self-correcting.", v:"expert", fb:"If feedback goes positive, power reinforces itself — no enemy needed." },
          { t:"A missing safeguard would prove an intruder disabled it, since the physics itself never fails.", v:"danger", fb:"Positive feedback is a design property, not evidence of tampering." },
          { t:"Inherent safety is automatic, so any well-built reactor simply cannot ever surge at all.", v:"wrong", fb:"Not all reactors are inherently safe; some can amplify a surge by design." },
          { t:"Inherent safety concerns only brand-new designs, not a reactor already in service today.", v:"partial", fb:"Inherent safety is a property of this operating reactor's design too." } ] }
      ] },
    // cell: Operator Nadia Sorel @ The Design Authority's Office
    delayedneutrons:{ sci:"John Wheeler (1911-2008)", topic:"Fission theory & delayed neutrons", lede:"The theorist who co-wrote the theory of fission and later named the black hole — and whose one small number defines the line a reactor must never cross.", no:14,
      profile:"John Wheeler helped write the theory of fission and then helped build the reactors that used it, and one subtle number from that work sits at the heart of this case. A brilliant American theoretical physicist — later famous for coining the term 'black hole' — Wheeler collaborated with Niels Bohr in 1939 on the definitive early theory of nuclear fission, then joined the Manhattan Project and worked on the great plutonium-producing reactors at Hanford.\n\nThe number that matters is the delayed-neutron fraction. When a uranium nucleus fissions, most of the neutrons fly out instantly, within a tiny fraction of a second. But a small share — under one percent for uranium-235 — are not released until seconds or even minutes later, emitted by certain fission-product nuclei as they beta-decay. These 'delayed' neutrons are almost negligible in number, yet they are the reason a reactor can be run at all. Because a self-sustaining chain relies on that late trickle to stay critical, the reactor's power responds slowly, over seconds, giving control rods and human hands time to act.\n\nFor this board, the delayed-neutron fraction defines the safety margin — and the phrase 'run past its margin' has an exact physical meaning. So long as a reactor needs the delayed neutrons to sustain itself, it is controllable. But if reactivity is pushed high enough that the prompt neutrons alone can sustain the chain, the reactor becomes 'prompt critical,' and its power no longer waits for the slow neutrons: it doubles again and again in thousandths of a second, far faster than any rod can move. That is a runaway. It is not a mystery and not an act of sabotage; it is a known threshold, quantified decades ago, that a reckless test can drive a flawed reactor across. Cross it, and the physics does the rest.",
      frame:"Nadia's finger hovers over a reactivity chart. \"There's a line you do not cross, and it's measured in fractions of a percent. I need to know you understand what lives on the far side of it. Delayed neutrons — go.\"",
      q:[
        { q:"What are delayed neutrons?", o:[
          { t:"A small fraction of fission neutrons emitted seconds later by decaying products.", v:"expert", fb:"Under 1% arrive seconds late from beta-decaying fission products." },
          { t:"Neutrons that lie dormant in the fuel until a shock suddenly releases them all.", v:"danger", fb:"They are not stored; they are emitted late by decaying fission products." },
          { t:"Neutrons slowed by the moderator so much that they arrive late at the next nucleus.", v:"wrong", fb:"Delay comes from radioactive decay timing, not from moderation slowing them." },
          { t:"The neutrons a reactor holds in reserve, kept back until extra power is needed.", v:"partial", fb:"They are not a controllable reserve; their timing is set by decay." } ] },
        { q:"Why do delayed neutrons make a reactor controllable?", o:[
          { t:"They slow the reactor's response over seconds, giving rods and operators time to act.", v:"expert", fb:"Relying on the late trickle stretches the response to a human timescale." },
          { t:"They absorb excess neutrons, capping the power so a runaway can never occur.", v:"danger", fb:"They do not absorb neutrons; they extend the response time for control." },
          { t:"They quietly cool the core between pulses, keeping the fuel from ever overheating at all.", v:"wrong", fb:"They govern timing, not cooling; the coolant removes heat separately." },
          { t:"They boost the total neutron count, making the reaction easier to keep going.", v:"partial", fb:"Their value is timing, not count; they are too few to matter for power." } ] },
        { q:"What happens past the delayed-neutron margin?", o:[
          { t:"The chain sustains on prompt neutrons alone and power surges within milliseconds.", v:"expert", fb:"Prompt criticality makes power double in thousandths of a second — a runaway." },
          { t:"The reactor simply shuts itself off, since crossing the margin trips every safeguard.", v:"danger", fb:"Crossing it causes a runaway, not an automatic safe shutdown." },
          { t:"Nothing changes, because the margin is only a paperwork limit with no physical effect.", v:"wrong", fb:"The margin is physical: past it, prompt neutrons alone drive the surge." },
          { t:"Power rises steadily over many minutes, slow enough for the crew to correct it.", v:"partial", fb:"Past the margin the rise is near-instant, far too fast to hand-correct." } ] }
      ] },
    // cell: The Health Physicist @ The Design Authority's Office
    healthphysics:{ sci:"Karl Z. Morgan (1907-1999)", topic:"Health physics & radiation dose", lede:"The father of health physics, who built the science of measuring dose — and later turned to warn the industry he had helped create.", no:15,
      profile:"Karl Z. Morgan is called the father of health physics — the science of protecting people from radiation — and both his measurements and his conscience speak to this case. Recruited to the Manhattan Project, he was tasked with keeping the workers who handled unprecedented quantities of radioactive material from being harmed. From that wartime urgency he built an entire discipline: how to measure radiation dose, how to set exposure limits, and how to track radioactive material once it enters the body. He led health physics at Oak Ridge for decades and became the first president of the Health Physics Society.\n\nMorgan championed the principle now known as ALARA — keep every dose 'as low as reasonably achievable' — grounded in the sober assumption that there may be no perfectly safe threshold, so even small exposures carry some risk. He pressed for careful monitoring, shielding, and honest accounting of doses. And in his later years he did something rarer: he turned critic, testifying that the industry he had helped build was underplaying the hazards of low-level radiation. He spoke uncomfortable truths against powerful pressure to stay quiet.\n\nFor this board, Morgan supplies both a tool and a warning. The tool is dose: radiation released in an accident is measurable, and the pattern and quantity of that release record how much fuel fissioned, how fast, and where it went. A power excursion leaves a distinctive radiological signature — a burst of specific fission products in specific places — quite unlike anything an intruder could stage. The warning is his life's second act: that those closest to a nuclear program may know its dangers and be pressed to keep silent. A board should weigh both the numbers on the dosimeters and the possibility that someone with knowledge was told to look away.",
      frame:"The Health Physicist spreads the dose maps across the design table. \"These numbers don't argue and they don't forget. Morgan built the whole science of reading them. Show me you can, and I'll tell you what they say happened.\"",
      q:[
        { q:"What is health physics?", o:[
          { t:"The science of measuring radiation and protecting people from its harm.", v:"expert", fb:"Morgan's field measures dose and shields people from radiation harm." },
          { t:"The study of using radiation to cure disease at the highest possible dose.", v:"danger", fb:"That is radiation therapy; health physics limits and protects against dose." },
          { t:"The branch of physics that designs the reactors themselves for maximum output.", v:"wrong", fb:"Reactor design is separate; health physics protects people from radiation." },
          { t:"The practice of cleaning up radioactive spills after an accident has occurred.", v:"partial", fb:"Cleanup is one part; the field is measurement and protection broadly." } ] },
        { q:"What does the ALARA principle require?", o:[
          { t:"Keep doses as low as reasonably achievable, since no dose is surely without risk.", v:"expert", fb:"ALARA drives dose down because there may be no safe threshold at all." },
          { t:"Permit any dose below a high threshold, since low-level radiation is entirely harmless.", v:"danger", fb:"ALARA assumes there may be no safe threshold; it does not permit exposure freely." },
          { t:"Match each worker's dose to a fixed annual quota and stop measuring once it is met.", v:"wrong", fb:"ALARA minimizes dose continuously; it is not a quota to spend down." },
          { t:"Shield only the workers nearest the core, since distant staff face no real hazard.", v:"partial", fb:"ALARA protects everyone exposed, not only the closest workers." } ] },
        { q:"Why does dose measurement matter to this inquiry?", o:[
          { t:"The release records how much fuel fissioned and how fast, revealing the excursion.", v:"expert", fb:"The radiological signature reconstructs the excursion's scale and course." },
          { t:"Any radiation found is certain proof that a device was smuggled in and detonated inside.", v:"danger", fb:"A power surge releases radiation too; it is no proof of a bomb." },
          { t:"Dose reveals only who was harmed, never anything about how the accident unfolded.", v:"wrong", fb:"The release pattern encodes the event's size, speed, and location." },
          { t:"The dose maps show where people stood but cannot indicate the size of the event.", v:"partial", fb:"The quantity and mix of products directly scale the excursion." } ] }
      ] },
    // cell: The Health Physicist @ The Design Authority's Office
    halflife:{ sci:"Frederick Soddy (1877-1956)", topic:"Isotopes & half-life", lede:"The radiochemist who named the isotope and gave radioactivity its unerring clock — each nucleus ticking down at its own fixed rate.", no:16,
      profile:"Frederick Soddy gave radioactivity its clock and its bookkeeping. An English radiochemist, he worked with Ernest Rutherford in Montreal at the turn of the century, and together they reached a startling conclusion: radioactivity is the spontaneous transmutation of one element into another, atom by atom, as unstable nuclei disintegrate. This was alchemy made real, and it overturned the assumption that elements were immutable.\n\nSoddy went on to make sense of a growing confusion. Chemists kept finding 'new' radioactive substances that were chemically identical to known elements but had different atomic weights and decay behavior. In 1913 Soddy coined the word 'isotope' — from the Greek for 'same place' — to describe these variants that occupy the same spot on the periodic table but differ in mass. He also formulated the displacement law describing how alpha and beta decay shift an element across the table. He won the 1921 Nobel Prize in Chemistry for this work; in later life he turned, more controversially, to economics.\n\nCentral to all of it is the half-life: the fixed time in which half the atoms in a radioactive sample decay. Every isotope has its own, from fractions of a second to billions of years, and it never varies. For this board, half-lives are a forensic clock. The debris of the Thornbury accident is a mix of fission-product isotopes, each ticking down at its own known rate. By measuring which isotopes are present and in what ratios, an analyst can date the release, gauge how much fission occurred, and reconstruct the sequence — much as a coroner reads a time of death. That precision is the enemy of both easy answers: it can confirm exactly when and how fiercely the core surged, leaving no room to hide the event behind a vague 'fluke' or to invent a saboteur the isotopes do not support.",
      frame:"The Health Physicist holds up a spectrum printout. \"Every one of these lines is a clock Soddy taught us to read. They date the accident to the hour. Convince me you understand isotopes and half-life, and I'll read them with you.\"",
      q:[
        { q:"What did Soddy establish about the elements?", o:[
          { t:"That radioactivity transmutes one element into another, and elements have isotopes.", v:"expert", fb:"Decay transmutes elements; isotopes share chemistry but differ in mass." },
          { t:"That elements can be freely turned to gold, fulfilling the old dream of the alchemists.", v:"danger", fb:"Decay follows fixed paths, not a chemist's wish; gold-making is a myth here." },
          { t:"That every element has exactly one stable form, fixed forever and never changing.", v:"wrong", fb:"Elements can have several isotopes and can transmute by decay." },
          { t:"That radioactive atoms merely rearrange their electrons without changing element.", v:"partial", fb:"Decay changes the nucleus and the element, not just the electrons." } ] },
        { q:"What is a half-life?", o:[
          { t:"The fixed time for half a radioactive sample to decay, unique to each isotope.", v:"expert", fb:"Half decays each half-life; the rate is fixed and never varies." },
          { t:"The moment a radioactive sample becomes completely safe and stops emitting entirely.", v:"danger", fb:"After one half-life half remains; it is never suddenly 'safe.'" },
          { t:"The time an isotope takes to decay away fully, leaving nothing radioactive behind.", v:"wrong", fb:"One half-life removes half, not all; decay is exponential, never complete." },
          { t:"The average lifetime of a single atom before it finally releases its radiation.", v:"partial", fb:"Half-life is a population measure; mean atomic life is a related but distinct figure." } ] },
        { q:"Why do half-lives matter to this inquiry?", o:[
          { t:"Fission products decay on known clocks, so their ratios date and reconstruct the event.", v:"expert", fb:"Known decay rates turn the debris into a datable, quantitative timeline." },
          { t:"Isotopes decay so wildly and unpredictably that no timeline of the accident can be trusted.", v:"danger", fb:"Decay rates are fixed and precise, making a reliable timeline possible." },
          { t:"Half-lives are all so long that the debris reveals nothing about a single night.", v:"wrong", fb:"Many fission products have short half-lives, ideal for dating one night." },
          { t:"The isotopes name the fuel type but cannot fix when the release took place.", v:"partial", fb:"Isotope ratios pin the timing tightly, not just the fuel type." } ] }
      ] },
    // cell: The Clerk @ The Design Authority's Office
    riskassessment:{ sci:"Norman Rasmussen (1927-2003)", topic:"Reactor risk assessment", lede:"The MIT engineer who first put hard numbers on reactor catastrophe — and gave the board the arithmetic to test a 'one-in-a-billion' fluke.", no:17,
      profile:"Norman Rasmussen taught the nuclear field how to put numbers on catastrophe, and his methods are the direct answer to anyone calling the Thornbury accident a one-in-a-billion fluke. A physicist and nuclear engineer at MIT, he was chosen in the early 1970s to lead a landmark study of how likely a serious reactor accident really was. The result, published in 1975 as WASH-1400, the Reactor Safety Study, was the first large-scale application of probabilistic risk assessment to nuclear power.\n\nRasmussen's team did not guess. They broke potential accidents into sequences — an initiating event, followed by the success or failure of each safety system in turn — and built 'event trees' and 'fault trees' to trace every path to core damage and estimate the probability of each. The study was influential and also controversial; a later review panel criticized its handling of uncertainty. But it established the framework the whole industry now uses to find weak points and rank hazards, and it made explicit that reactor accidents are not single random strokes but chains of failures whose odds can be estimated.\n\nFor this board, Rasmussen is the antidote to the dismissal trap. 'A vanishingly unlikely accident, no one's fault' is a claim about probability, and probability can be checked. Risk assessment asks: what was the true chain here — a design feature that could turn feedback the wrong way, a safety margin knowingly violated, a test run in a forbidden regime, a warning left unshared? Each link raises the odds, and together they can turn a supposed one-in-a-billion event into something that was, in truth, waiting to happen. Rasmussen's trees expose the difference between an accident that was genuinely improbable and one that only looks that way because someone hid a branch of the tree from view.",
      frame:"The Clerk lays out a fan of fault-tree diagrams. \"People love the phrase 'one in a billion.' Rasmussen taught us to actually do the arithmetic. Show me you can, and I'll tell you which branch of this tree went missing.\"",
      q:[
        { q:"What is probabilistic risk assessment?", o:[
          { t:"A method estimating accident odds by mapping chains of failures through logic trees.", v:"expert", fb:"Event and fault trees estimate the odds of each accident sequence." },
          { t:"A promise that reactors are perfectly safe, since every accident is ruled impossible.", v:"danger", fb:"PRA quantifies risk; it never claims accidents are impossible." },
          { t:"A single overall safety rating stamped on a reactor once at the time it is licensed.", v:"wrong", fb:"PRA is an analysis of failure paths, not a one-time stamp." },
          { t:"A tally of past accidents used to guess how often the next one will occur.", v:"partial", fb:"PRA models sequences from first principles, not just past counts." } ] },
        { q:"What did Rasmussen's WASH-1400 do?", o:[
          { t:"It gave the first systematic estimate of reactor accident probabilities and effects.", v:"expert", fb:"It pioneered probabilistic risk assessment for reactor accidents." },
          { t:"It proved a serious reactor accident could never physically happen in any design.", v:"danger", fb:"It estimated real, nonzero accident odds; it did not rule accidents out." },
          { t:"It set out the legal radiation dose limits that every nuclear plant must operate within.", v:"wrong", fb:"Dose limits are Morgan's domain; WASH-1400 estimated accident risk." },
          { t:"It ranked reactors by cost, choosing the cheapest safe design for the utilities.", v:"partial", fb:"It assessed safety risk, not construction cost." } ] },
        { q:"Why does risk assessment matter to this inquiry?", o:[
          { t:"It tests the 'fluke' claim, since a hidden flaw makes the accident far more likely.", v:"expert", fb:"Each concealed flaw and violated margin raises the odds far above 'freak.'" },
          { t:"It shows the odds are so tiny that this accident truly must have been an act of God alone.", v:"danger", fb:"A concealed flaw removes the low odds; the event was not improbable." },
          { t:"It proves nothing, since accident odds can never be calculated for a real reactor.", v:"wrong", fb:"Rasmussen showed odds can be estimated sequence by sequence." },
          { t:"It scores the reactor overall but says nothing about this particular sequence.", v:"partial", fb:"PRA works precisely at the level of the specific accident sequence." } ] }
      ] },
    // cell: The Clerk @ The Design Authority's Office
    riskcell:{ sci:"Chauncey Starr (1912-2007)", topic:"Risk, safety & how safe is safe enough", lede:"The engineer who first asked 'how safe is safe enough' as a science — and showed a risk imposed on the public demands a far higher bar.", no:18,
      profile:"Chauncey Starr founded the modern study of how societies weigh technological risk, and his framework explains why concealment at a reactor is not a minor sin but a betrayal. An American engineer who helped lead early nuclear projects and later founded the Electric Power Research Institute, Starr published a paper in 1969, 'Social Benefit versus Technological Risk,' that essentially created the field of quantitative risk analysis for technology.\n\nStarr's central move was to compare, in hard numbers, the risks people actually accept against the benefits they receive. Studying real data, he drew out a striking pattern: people will tolerate risks roughly a thousand times greater when those risks are voluntary — like driving or skiing — than when the same level of risk is imposed on them involuntarily. Nuclear power sits squarely in the involuntary category: a community living near a plant did not individually choose its hazards. Starr argued that such imposed risks are, rightly, held to a far higher standard of safety and public acceptance than risks people take on themselves.\n\nFor this board, Starr frames the moral weight of the case. The question 'how safe is safe enough' is not rhetorical; it has a quantitative answer that depends on who bears the risk and who reaps the benefit. Because a reactor imposes its dangers on a public that must simply trust the operators and designers, that trust is the whole foundation of its acceptability. A concealed design flaw and a shelved safety report do not merely raise the technical odds of an accident; they shatter the compact Starr described, in which the people who impose an involuntary risk owe the public honesty about it. Neither a sensational cry of sabotage nor a shrug of 'freak accident' respects that compact — only naming the concealment does.",
      frame:"The Clerk closes the last folder. \"The public near this plant never chose its risks — they trusted us to be honest about them. Starr made that a science. Show me you understand it, and I'll tell you what that trust was worth here.\"",
      q:[
        { q:"What did Starr's 1969 work establish?", o:[
          { t:"A way to weigh technological risks against their benefits, using real acceptance data.", v:"expert", fb:"He quantified acceptable risk versus benefit, founding the field." },
          { t:"That nuclear power carries no real risk, so public fear of it is wholly irrational.", v:"danger", fb:"He measured real risks as nonzero; he did not dismiss them as unreal." },
          { t:"That every technology must reach zero risk before the public will ever accept it.", v:"wrong", fb:"He found people accept nonzero risk, not that zero risk is required." },
          { t:"That risk depends only on how many people a technology could possibly harm.", v:"partial", fb:"Benefit and voluntariness matter too, not just the number exposed." } ] },
        { q:"What is Starr's voluntary/involuntary distinction?", o:[
          { t:"People tolerate far more risk they choose than equal risk imposed upon them.", v:"expert", fb:"Voluntary risk is tolerated roughly a thousandfold more than imposed risk." },
          { t:"People will accept any imposed risk at all, provided the technology is useful enough.", v:"danger", fb:"Imposed risk is held to a much higher standard, not accepted freely." },
          { t:"People judge all risks identically, whether they are chosen or forced on them.", v:"wrong", fb:"Starr found chosen and imposed risks are judged very differently." },
          { t:"People accept only risks they can personally see, ignoring any hidden hazards.", v:"partial", fb:"Visibility differs from voluntariness; the key split is chosen versus imposed." } ] },
        { q:"Why does 'how safe is safe enough' matter here?", o:[
          { t:"Reactor risk is imposed on the public, so it demands a higher standard and honesty.", v:"expert", fb:"Imposed risk rests on trust; concealment breaks the compact Starr described." },
          { t:"The risk is so slight that any accident must be an outsider's deliberate attack.", v:"danger", fb:"A higher standard for imposed risk does not imply an attacker caused this." },
          { t:"The public simply accepts all reactor risk, so disclosing flaws is never truly needed.", v:"wrong", fb:"Imposed risk demands disclosure precisely because the public cannot consent." },
          { t:"The standard is purely technical, so public trust has no place in this inquiry.", v:"partial", fb:"Public trust is central to imposed risk, not outside the inquiry." } ] }
      ] }
  },
  STORIES:{
    operator2:{
      control:"Nadia sits at her own console, the test log open. \"I turned every knob exactly as written. If the procedure was a trap, I walked into it blind. Show me you understand this room and I'll tell you what the book told me to do.\"",
      hall:"Nadia leads you onto the gantry above the core. \"This is where my numbers turned to noise. I know what I did; I want to know what the machine did back. Prove you can follow it.\"",
      designoffice:"Nadia stands stiffly among the drafting tables. \"They wrote the book I followed. Somewhere out here is the reason it was wrong. Help me understand the physics and I'll show you the line I was told never to question.\""
    },
    healthphys:{
      control:"The Health Physicist scrolls the flux recording. \"The detectors caught the whole rise, millisecond by millisecond. Convince me you can read what they saw, and I'll tell you how fast it truly ran.\"",
      hall:"The Health Physicist checks a survey meter against the core. \"The dose here tells me how much fuel let go, and when. Show me you know the physics, and I'll tell you what the readings rule out.\"",
      designoffice:"The Health Physicist spreads dose maps over a designer's desk. \"These numbers match a power excursion and nothing else — not a bomb, not a fluke. Earn it, and I'll walk you through why.\""
    },
    clerk:{
      control:"The Clerk arrives with a trolley of logbooks. \"Every switch throw in here is written down somewhere. The trouble is what isn't. Show me you understand this place and I'll tell you which records to trust.\"",
      hall:"The Clerk eyes the core uneasily, clipboard clutched tight. \"I file what the physicists hand me; I don't come down here often. Prove you grasp the machine, and I'll tell you what crossed my desk about it.\"",
      designoffice:"The Clerk stands beside a locked cabinet. \"This is where the design files live — every one stamped, dated, and shelved. Some were shelved a little too quickly. Show me you understand the physics, and I'll tell you which drawer to open.\""
    }
  },
  story:[
    "The <b>Thornbury reactor</b> was the pride of the grid — a powerful, modern core that had run clean for years. Then, in the small hours of a routine night-shift test, its power ran wild, and by dawn the reactor hall was sealed and the questions had begun. You are <b>Inspector Ada Vrain</b>, and the inquiry has handed you the file the whole industry is waiting on.",
    "<b>Three people inside will help you</b>, each holding a piece and none the whole. <b>Operator Nadia Sorel</b>, who ran the test exactly as the procedure told her — a procedure that may have been wrong. <b>The Health Physicist</b>, who read the dose and the neutron flux and knows, to the millisecond, how fast the power ran away. And <b>the Clerk</b>, who keeps the design files and knows which reports were stamped, shelved, and forgotten. Win their trust and they will talk.",
    "<b>Someone here is behind it.</b> Three names sit in your notepad: <b>Operations chief Marsh</b>, who ordered the test; <b>Aldous Reeve</b>, the chief reactor designer who drew the core; and <b>the nuclear inspector</b>, who signed the plant as safe. Each column — <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> truly happened — hides a tempting wrong answer. The headlines want <b>sabotage, an attack on the plant</b>. The quiet file wants <b>a freak accident, vanishingly unlikely, no one's fault</b>. The truth is narrower than the first and graver than the second — and it is written on a page someone made sure was not read.",
    "You have <b>8 days</b> and a single accusation to make. Name it well and a shelved report becomes proof that saves the next reactor; name it wrong and a real, provable failure is lost to a headline or a shrug."
  ],
  endings:{ overclaimWhat:"attack", dismissalWhat:"freak",
    win:{
      expertTitle:"What the Traces Prove, and No More",
      expert:["Vrain names it exactly: Aldous Reeve, the chief reactor designer, whose office holds the safety report he shelved rather than share; the truth culminating in the Design Authority's Office, where the concealed flaw and the buried memo live; and a hidden design flaw — a positive feedback that let the core reinforce its own power, driven past its margin during the night-shift test. Not an attack. Not a freak of nature.",
        "Every card accounted for. Vrain worked the control room, the reactor hall, and the design office, turned a wary clerk into a witness, and claimed precisely what the flux traces and the shelved report could defend. The inquiry issues findings that shut down the flawed cores and force the fault into the open — which is the entire point of doing it right."],
      soundTitle:"Right — but Lightly Proven",
      sound:["Vrain names the right three — Reeve, the Design Office, and the concealed design flaw run past its margin. The shape of the case is correct, and the refusal to cry sabotage or shrug off a fluke is exactly right.",
        "But too many threads were left loose, and the design authority's lawyers will pull at them. A few more days tracing the shelved report and the flux record would have made the finding unassailable. Close and honest, if not yet airtight."],
      namedTitle:"The Right Answer, Unearned",
      named:["Vrain names the truth — Reeve, the Design Office, the concealed flaw driven past its margin — but gathered too little to back it. It reads like a hunch that happened to land.",
        "The inquiry cannot shut down a fleet on an accusation this thin, however correct. Being right is not the same as being able to prove it to the people who will fight the finding."]
    },
    overclaim:{ title:"The Inquiry That Cried Sabotage",
      body:["Vrain reports sabotage — an attack on the plant — the answer the cameras were already broadcasting. It is vivid, and it is not what the evidence shows.",
        "The flux traces show a physical power excursion, the fission-product signature matches the core's own fuel, and no intruder left a mark — only a reactor reinforcing its own power until it ran away. When the overclaim collapses, it takes the inquiry's credibility with it, and the real, provable flaw is dismissed as one more conspiracy theory. The only saboteur was a feedback built into the design and a report someone chose not to read."] },
    dismissal:{ title:"Case Closed as an Act of God",
      body:["Vrain files it as a freak accident — vanishingly unlikely, no one's fault, close the file. It is comforting, and it misses the graver truth.",
        "The runaway followed known physics across a known threshold, in a core whose designers understood its flaw and did not disclose it. Calling it fate leaves that flaw in every sister reactor still running, waiting for the next night-shift test to find it again. The inquiry saw an unlucky night and never the hazard that had been designed in and hidden."] },
    wrongNames:{ title:"So Close",
      body:["Vrain has the nature of it cold — a concealed design flaw, a core driven past its margin into a runaway, neither an attack nor a freak of nature. But the finger lands on the wrong name or the wrong room."] } },
}};