// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"software", title:"Fatal Exception", discipline:"Software & Systems Safety",
  teaser:"A radiation machine gave patients a hundredfold overdose. A hacker? Careless nurses? Or a bug built in — and hidden?", overclaimTag:"a malicious hack", truthTag:"a fatal software defect, concealed",
  venue:"the Calder radiotherapy inquiry", agent:{name:"Auditor Lena Foss", role:"Investigator's Notepad"},
  standingLabel:"Engineering credibility", readingShort:"Pioneers", readingLabel:"Computing Pioneers",
  dossierName:"COMPUTING PIONEERS", enterLabel:"Open the inquiry", subt:"A deduction game inside the Calder radiotherapy inquiry", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the answer the headlines want: the evidence points not to an outside attacker, but to something quieter that was built into the machine and left there.",
  CATS:{
    who:{ title:"Who is behind it", truth:"maker", items:[
      {id:"operator", label:"The radiotherapy technicians"},
      {id:"maker", label:"Renwick — the manufacturer's software lead"},
      {id:"hospital", label:"The hospital physicist"} ]},
    where:{ title:"Where it culminates", truth:"vendor", items:[
      {id:"treatment", label:"The Treatment Room & Console"},
      {id:"biomed", label:"The Hospital Biomedical Lab"},
      {id:"vendor", label:"The Manufacturer's Software Office"} ]},
    what:{ title:"What is happening", truth:"defect", items:[
      {id:"hack", label:"A malicious hack or cyberattack"},
      {id:"usererror", label:"Simple operator error — nothing systemic"},
      {id:"defect", label:"A concealed software defect & a removed interlock"} ]}
  },
  PLACES:{
    treatment:{name:"The Treatment Room & Console", xy:[140,90]},
    biomed:{name:"The Hospital Biomedical Lab", xy:[330,240]},
    vendor:{name:"The Manufacturer's Software Office", xy:[520,90]}
  },
  EDGES:[["treatment","biomed"],["biomed","vendor"]],
  CHARACTERS:{
    tech:{ name:"Technician Ama", role:"Radiotherapy technician", face:"☢", badge:"T", legend:"the console", hint:"Typed the fast edit that triggered the fault; blamed, but she saw 'MALFUNCTION 54.'" },
    phys:{ name:"The Medical Physicist", role:"Hospital medical physicist", face:"📟", badge:"P", legend:"the biomed lab", hint:"Reconstructed the doses; proved the machine, not the patient, was wrong." },
    qa:{ name:"The QA Engineer", role:"Manufacturer QA engineer", face:"🐞", badge:"Q", legend:"the vendor office", hint:"Knows the race condition was known, and the hardware interlock was removed to cut cost." }
  },
  TOPICMAP:{
    treatment:{ tech:["algorithm","turing"], phys:["boolean","architecture"], qa:["compiler","abstraction"] },
    biomed:{ tech:["concurrency","synchronization"], phys:["overflow","nullref"], qa:["testing","formalmethods"] },
    vendor:{ tech:["softwaresafety","criticalsoftware"], phys:["robusterror","hci"], qa:["complexity","mythicalmonth"] }
  },
  TOPICS:{
    // cell: Technician Ama @ The Treatment Room & Console
    algorithm:{ sci:"Ada Lovelace (1815-1852)", topic:"The first algorithm", lede:"The Countess who looked at a machine of brass and gears and saw that it would only ever do what someone told it to.", no:1,
      profile:"Augusta Ada King, Countess of Lovelace, was an English mathematician and the daughter of the poet Lord Byron. In the 1840s she worked alongside Charles Babbage, designer of the Analytical Engine — a mechanical, general-purpose computer that was never fully built. In 1843 she translated an Italian account of the engine by Luigi Menabrea and appended her own Notes, together far longer than the paper itself.\n\nHer Note G set out, in careful detail, a step-by-step procedure for the engine to compute the Bernoulli numbers — a sequence of operations with loops and reused intermediate results that is widely regarded as the first published computer algorithm. More strikingly, Lovelace grasped what Babbage barely stated: that the engine manipulated symbols, not merely numbers, and might handle anything reducible to rules. She mused that it could one day compose elaborate music. This is the seed of general-purpose computing.\n\nYet she was equally clear about the machine's limits. In her famous remark, the engine 'has no pretensions whatever to originate anything'; it can only do 'whatever we know how to order it to perform.' The machine holds no will of its own; its behavior is simply the behavior of its program.\n\nFor this inquiry, Lovelace draws the first hard line. A radiotherapy machine that delivers a lethal dose did not decide to; it executed instructions. That cuts against the sensational story of a machine 'hacked' into malice, and against the lazy story of a careless hand at the keys. If the output was wrong, the ordered steps — the software — are where an investigator must look. What the engine did, someone told it to do.",
      frame:"Ama folds her arms. \"They're pinning this on my keystrokes. A machine only runs what someone wrote into it — prove you know that much before I tell you what I typed.\"",
      q:[
        { q:"What did Lovelace's famous Note G contain?", o:[
          { t:"A step-by-step method for the engine to compute the Bernoulli numbers.", v:"expert", fb:"That sequence of operations is widely called the first published algorithm." },
          { t:"A secret command set letting the machine rewrite its own instructions at will.", v:"danger", fb:"Lovelace held the opposite: the engine originates nothing on its own." },
          { t:"A proof that Babbage's engine could never be built from brass and gears.", v:"wrong", fb:"She detailed how it would compute, not any impossibility of building it." },
          { t:"A table of logarithms the engine would print faster than a human clerk.", v:"partial", fb:"Note G was a genuine programmed procedure, not merely a printed table." } ] },
        { q:"What did Lovelace foresee about the engine's reach?", o:[
          { t:"That it could manipulate symbols of any kind, not only numbers.", v:"expert", fb:"She foresaw general symbol manipulation — even, she wrote, composing music." },
          { t:"That it would think for itself once its gear-train grew large enough.", v:"wrong", fb:"She explicitly denied the machine could originate its own ideas." },
          { t:"That it would speed arithmetic but do nothing a human clerk could not.", v:"partial", fb:"She went further: it could handle symbols well beyond mere arithmetic." },
          { t:"That it might one day seize control of every task its owners assigned it.", v:"danger", fb:"That is the runaway-machine myth; Lovelace argued the exact reverse." } ] },
        { q:"What did she mean that the engine cannot 'originate anything'?", o:[
          { t:"It only does what it is programmed to; its output traces to its code.", v:"expert", fb:"A lethal result comes from the instructions it was given, not a will of its own." },
          { t:"It could act on its own, so a rogue machine can decide to harm a patient.", v:"danger", fb:"Lovelace denied this; the engine cannot do what it was never told to do." },
          { t:"It was too slow to matter, so its results should never be trusted at all.", v:"wrong", fb:"She praised its power; her point was about origination, not speed." },
          { t:"It needed a human at each step and so could never run a task unattended.", v:"partial", fb:"It could run unattended; the point is it follows its program, not free will." } ] }
      ] },
    // cell: Technician Ama @ The Treatment Room & Console
    turing:{ sci:"Alan Turing (1912-1954)", topic:"Computability & the Turing machine", lede:"The mathematician who invented an imaginary machine to fix, once and for all, what a machine can and cannot do.", no:2,
      profile:"Alan Turing was an English mathematician and one of the founders of computer science. In his 1936 paper 'On Computable Numbers,' he introduced an abstract device now called the Turing machine: an idealized reader that moves along an infinite tape, reading and writing symbols according to a fixed table of rules. Simple as it is, this machine captures precisely what it means for something to be 'computable' by any step-by-step procedure.\n\nTuring then proved something profound and unsettling. He showed there is no general algorithm that can decide, for every possible program and input, whether that program will eventually halt or run forever — the halting problem is undecidable. Some questions about programs cannot be answered by any program at all. He also described the universal machine: a single Turing machine that, given a description of any other, can imitate it — the theoretical ancestor of every stored-program computer. During the Second World War he was central to breaking German ciphers at Bletchley Park.\n\nTuring's work marks the exact boundary between what computation can and cannot guarantee. A Turing machine is deterministic: the same rules on the same tape always produce the same behavior. But the halting result warns that you cannot, in general, prove a program has no bad state simply by inspecting it.\n\nFor this inquiry, that is a double lesson. A malfunctioning machine is not mystical — its fault is the deterministic result of its program and inputs, and it should reproduce under the same conditions rather than strike at random like an intruder. Yet Turing also warns that some defects hide beyond any casual inspection, which is exactly how a lethal flaw can pass every routine check unseen.",
      frame:"Ama leans in. \"The console did the same thing twice on the same steps — that's not random, and it's not some ghost in the wires. Show me you understand what a machine can and can't do.\"",
      q:[
        { q:"What is a Turing machine?", o:[
          { t:"An abstract device that reads and writes symbols on a tape by fixed rules.", v:"expert", fb:"That idealized machine defines exactly what any step-by-step procedure can compute." },
          { t:"An early electronic computer Turing built to break German wartime ciphers.", v:"wrong", fb:"It is a mathematical abstraction, not a physical machine he constructed." },
          { t:"A test to judge whether a computer can convincingly imitate a human being.", v:"wrong", fb:"That is the later Turing test; the Turing machine is a model of computation." },
          { t:"A fast calculator that handles arithmetic but no other kind of symbol task.", v:"partial", fb:"It manipulates symbols in general, which is far more than arithmetic alone." } ] },
        { q:"What did Turing prove with the halting problem?", o:[
          { t:"No general algorithm can decide whether any given program will ever halt.", v:"expert", fb:"Some questions about programs are undecidable by any program at all." },
          { t:"That any bug can be found in advance if you simply inspect the code closely.", v:"danger", fb:"The halting result shows exactly why inspection cannot catch every fault." },
          { t:"That every program eventually stops if given enough memory to run in.", v:"wrong", fb:"Many programs run forever; whether one halts is not generally decidable." },
          { t:"That programs with loops are always slower than programs written without them.", v:"partial", fb:"Halting is about decidability, not the speed of loops." } ] },
        { q:"Why does determinism matter to reading this malfunction?", o:[
          { t:"The same program on the same inputs repeats its fault, pointing to the code.", v:"expert", fb:"A reproducible fault traces to the software, not to a random or outside cause." },
          { t:"A repeatable, timed fault is the fingerprint of an attacker striking on schedule.", v:"danger", fb:"Determinism points inward to the program, not outward to an intruder." },
          { t:"Machines behave unpredictably, so no fault can ever really be reproduced.", v:"wrong", fb:"A deterministic machine reproduces its behavior under the same conditions." },
          { t:"It proves the operator caused it, since the machine itself never varies.", v:"partial", fb:"Reproducibility implicates the inputs and code, not automatically the operator." } ] }
      ] },
    // cell: The Medical Physicist @ The Treatment Room & Console
    boolean:{ sci:"George Boole (1815-1864)", topic:"Boolean logic", lede:"A self-taught schoolmaster who turned reasoning itself into algebra, and unknowingly wrote the grammar of every digital circuit.", no:3,
      profile:"George Boole was an English mathematician and logician, largely self-taught, who rose from running a small school to a professorship at Queen's College, Cork. In 'The Mathematical Analysis of Logic' (1847) and his masterwork 'An Investigation of the Laws of Thought' (1854), he did something audacious: he treated logic as a branch of algebra. Where ordinary algebra manipulates numbers, Boole's algebra manipulates truth — variables that take only the values true or false, combined by the operations we now call AND, OR, and NOT.\n\nIn Boole's system, statements become equations. 'The beam is armed AND the shield is in place' is true only when both parts are true; an OR is true when either holds; a NOT flips a value. From a handful of such rules, whole chains of reasoning can be computed rather than argued. Boole died young, and his work was admired but little used until, in 1937, a young engineer named Claude Shannon showed that Boolean algebra describes exactly the behavior of electrical switching circuits. That insight is the foundation of all digital logic — every logic gate in every computer is Boole made physical.\n\nFor this inquiry, Boolean logic is the language of safety. A protective interlock is a logical condition: the beam may fire only if a set of guard conditions are all true — an AND of many terms. Remove one term, or let a stale value read true when it should be false, and the guard silently stops guarding. That is neither an attacker's cunning nor an operator's slip; it is a logic gate that was supposed to block a hazard and, by design or by defect, did not. Boole teaches the physicist to ask which condition was quietly dropped.",
      frame:"The physicist sets down a dosimetry chart. \"Every safety of that machine reduces to a logical condition — all true, or the beam should not fire. Before I show you my reconstruction, prove you can read that logic.\"",
      q:[
        { q:"What is Boolean algebra?", o:[
          { t:"A logic of true and false values combined with the operations AND, OR, and NOT.", v:"expert", fb:"Boole made reasoning computable by treating truth as algebra." },
          { t:"A method of rounding real numbers to whole values before performing any calculation.", v:"wrong", fb:"Boole's variables are truth values, not rounded numbers." },
          { t:"A geometry of curves that Boole used to model the reasoning of the mind.", v:"wrong", fb:"His system is an algebra of logic, not a geometry of curves." },
          { t:"A way of ranking arguments as strong or weak by counting their premises.", v:"partial", fb:"It evaluates statements as true or false, not by tallying premises." } ] },
        { q:"How did Boole's logic reach modern computers?", o:[
          { t:"Shannon showed it describes switching circuits, the basis of digital design.", v:"expert", fb:"Boolean logic became the behavior of every logic gate in a computer." },
          { t:"Boole himself wired the first electric adding machine from his own equations.", v:"wrong", fb:"Boole built no computer; Shannon linked his algebra to circuits decades later." },
          { t:"Babbage engraved Boole's laws onto the gears of the Analytical Engine.", v:"wrong", fb:"Babbage's engine predates and did not use Boole's algebra of logic." },
          { t:"It survives only in philosophy and never truly entered engineering practice.", v:"partial", fb:"On the contrary, it underpins all digital hardware design." } ] },
        { q:"How does Boolean logic frame a safety interlock?", o:[
          { t:"As an AND of guard conditions that must all hold or the beam must not fire.", v:"expert", fb:"Drop or falsify one term and the guard silently stops protecting." },
          { t:"As proof that any failed guard means an intruder flipped a value on purpose.", v:"danger", fb:"A dropped or stale term needs no attacker; a defect alone can do it." },
          { t:"As a single yes-or-no switch that the operator throws by hand each time.", v:"wrong", fb:"An interlock is a combination of conditions, not one manual switch." },
          { t:"As a suggestion the machine may weigh but is free to override on its own.", v:"partial", fb:"A true interlock is binding logic, not advice the machine may ignore." } ] }
      ] },
    // cell: The Medical Physicist @ The Treatment Room & Console
    architecture:{ sci:"John von Neumann (1903-1957)", topic:"The stored-program computer", lede:"The polymath whose one short report fixed the shape of nearly every computer built since.", no:4,
      profile:"John von Neumann was a Hungarian-American mathematician of staggering range — foundational work in quantum mechanics, game theory, and the Manhattan Project among it. In 1945 he wrote the 'First Draft of a Report on the EDVAC,' which crystallized an idea that had been taking shape among the ENIAC engineers into a clear, general design. It described a computer with a single memory that holds both the program's instructions and the data they act on, a central processing unit to fetch and execute those instructions in sequence, and a control unit to direct the flow.\n\nThis 'stored-program' concept is the reason we call most computers von Neumann machines. Because instructions live in the same memory as data, a computer can be reprogrammed by changing what is stored, not by rewiring it — the machine is universal in the practical sense Turing had described in theory. The design also has a famous limit, the 'von Neumann bottleneck': instructions and data must pass through the same channel between memory and processor.\n\nThe deep implication is that a computer's behavior at any instant depends on the state stored in its memory — the values of its variables, its flags, its position in the program. Change that state and you change what the machine does next.\n\nFor this inquiry, that reframes the machine on the console. Its lethal act was not a physical break you could photograph; it was the machine executing its stored instructions on a particular state of memory. If a flag held the wrong value at the wrong moment, the processor faithfully did the wrong thing. The physicist's task is to reconstruct not a broken part but the state the software was in — where the truth of a defect hides, invisible to any wrench.",
      frame:"The physicist gestures at a memory dump. \"There's no cracked part to hold up to the light. The machine did what its stored state told it to. Show me you understand how that machine is built.\"",
      q:[
        { q:"What defines the von Neumann architecture?", o:[
          { t:"One memory holding both instructions and data, run in sequence by a processor.", v:"expert", fb:"Sharing memory for code and data is the heart of the stored-program design." },
          { t:"Separate machines for each task, wired by hand before every new calculation.", v:"wrong", fb:"That is the older plug-and-rewire approach the stored program replaced." },
          { t:"A network of many small processors that vote on every result they compute.", v:"wrong", fb:"That describes redundant or parallel designs, not von Neumann's model." },
          { t:"A processor that keeps its whole program in gears while data lives on paper tape.", v:"partial", fb:"The key idea is program and data together in one electronic memory." } ] },
        { q:"Why does the stored-program idea matter?", o:[
          { t:"The machine can be reprogrammed by changing memory, not by rewiring it.", v:"expert", fb:"Behavior is set by stored instructions, making the computer truly general." },
          { t:"It lets the computer invent new instructions no programmer ever wrote.", v:"danger", fb:"It runs only stored instructions; it does not originate its own." },
          { t:"It makes programs run faster than any wired machine ever possibly could.", v:"partial", fb:"Its gift is flexibility; the shared channel can even be a speed bottleneck." },
          { t:"It removes the need for memory, since the program lives inside the processor.", v:"wrong", fb:"The program lives in memory; that is precisely the point." } ] },
        { q:"How does this shape the malfunction inquiry?", o:[
          { t:"Behavior hinges on stored state, so a wrong flag makes the machine act wrongly.", v:"expert", fb:"The fault is in the software's state, not a part you can photograph." },
          { t:"A wrong result must mean the hardware physically shattered somewhere deep inside.", v:"wrong", fb:"A stored-program fault leaves the hardware intact and the logic to blame." },
          { t:"An altered memory can only be the mark of someone breaking in to change it.", v:"danger", fb:"A defect can corrupt state on its own; no intruder is required." },
          { t:"Since the program is fixed in memory, its behavior can never vary at all.", v:"partial", fb:"The program is fixed, but the data and flags it acts on change constantly." } ] }
      ] },
    // cell: The QA Engineer @ The Treatment Room & Console
    compiler:{ sci:"Grace Hopper (1906-1992)", topic:"Compilers & the first 'bug'", lede:"The Navy mathematician who taught computers to read something closer to English — and who taped a real moth into the logbook.", no:5,
      profile:"Grace Hopper was an American mathematician and United States Navy officer who rose to rear admiral and became one of the most influential figures in early programming. During the Second World War she programmed the Harvard Mark I, one of the first large-scale computers. Afterward she pursued a radical idea: that people should not have to write in raw numeric machine code. Around 1952 she developed the A-0 system, generally credited as the first compiler — a program that translates more human-readable instructions into the machine's own code.\n\nHopper argued for years that programming could use words, not just numbers, against colleagues who thought it impossible. Her work led to FLOW-MATIC and fed directly into COBOL, a business language that ran the world's payrolls and ledgers for decades. She was famous for plain-spoken wisdom, for handing out 'nanoseconds' (lengths of wire), and for insisting it is easier to ask forgiveness than permission.\n\nShe is also tied to the word 'bug.' In 1947, operators of the Harvard Mark II found a moth caught in a relay; they taped it into the logbook as the 'first actual case of bug being found.' The term for a fault predated the moth, but Hopper's team popularized 'debugging' as the daily work of hunting such faults down.\n\nFor this inquiry, Hopper is the QA engineer's patron. A compiler is a layer of translation where meaning can be lost and errors introduced, and high-level languages make coding easier without making defects vanish. Her lesson is unglamorous and vital: a bug is a concrete, locatable thing in the code. It is not an intruder's magic and not an operator's imagination — it is found by someone willing to look.",
      frame:"The QA engineer taps a logbook. \"A bug isn't a ghost and it isn't a headline. It's a real thing sitting in the code, waiting for someone to find it. Convince me you know how to look.\"",
      q:[
        { q:"What was Grace Hopper's landmark software contribution?", o:[
          { t:"The first compiler, translating readable instructions into machine code.", v:"expert", fb:"Her A-0 system let people program without writing raw numeric code." },
          { t:"The first electronic computer, which she designed and built for the Navy.", v:"wrong", fb:"She programmed early machines; her breakthrough was the compiler." },
          { t:"The first operating system that let many users share one computer at once.", v:"wrong", fb:"That came later from others; Hopper's advance was compilation." },
          { t:"A faster wiring scheme that made the Harvard Mark I run several times quicker.", v:"partial", fb:"Her legacy is software translation, not a hardware speedup." } ] },
        { q:"What was the famous Mark II 'bug'?", o:[
          { t:"A moth caught in a relay, taped into the logbook as an actual 'bug' found.", v:"expert", fb:"The team popularized 'debugging' as the routine work of hunting faults." },
          { t:"A saboteur's device planted in the machine to corrupt all of the Navy's results.", v:"danger", fb:"It was an ordinary insect, not sabotage — and 'bug' meant a fault already." },
          { t:"A programming error Hopper made that wiped out a week of computed tables.", v:"wrong", fb:"The story is a literal moth in a relay, not one of her coding mistakes." },
          { t:"A design flaw in the relays that Hopper proved could never be repaired.", v:"partial", fb:"The moth was removed and logged; it was a stuck insect, not an unfixable flaw." } ] },
        { q:"What does Hopper's view of bugs mean for this case?", o:[
          { t:"A defect is a concrete, locatable thing that someone can find by looking.", v:"expert", fb:"Neither an intruder's magic nor an operator's imagination — findable code." },
          { t:"High-level languages remove bugs, so modern code needs no real testing.", v:"danger", fb:"Compilers ease coding but never make defects vanish; testing still matters." },
          { t:"Bugs are unknowable events, so chasing one is a waste of an inquiry's time.", v:"wrong", fb:"Hopper's whole point was that bugs are concrete and can be hunted down." },
          { t:"A fault only exists if the operator admits to having caused it directly.", v:"partial", fb:"A defect exists in the code regardless of who touched the console." } ] }
      ] },
    // cell: The QA Engineer @ The Treatment Room & Console
    abstraction:{ sci:"Barbara Liskov (b. 1939)", topic:"Data abstraction", lede:"The computer scientist who taught programs to hide their guts behind a clean promise — and warned what happens when the promise lies.", no:6,
      profile:"Barbara Liskov is an American computer scientist at MIT and a winner of the Turing Award in 2008. Her central contribution is data abstraction: the discipline of separating what a piece of software does — its interface, the promises it makes to the rest of the program — from how it does it, the hidden implementation inside. In the 1970s she designed the programming language CLU, which introduced 'clusters' for abstract data types, along with early forms of iterators and exception handling that shaped languages for decades after.\n\nThe power of abstraction is that a programmer using a component need only trust its interface, not read its internals. This is how large systems become buildable: each module is a sealed box that keeps its promise. Liskov also gave her name to the Liskov Substitution Principle, a rule for well-behaved type hierarchies — an object of a subtype must be usable anywhere the parent type is expected, without surprising the code that relies on it. She later did fundamental work on distributed systems and fault tolerance.\n\nAbstraction's strength is also its danger. When you trust a sealed box, you cannot see whether the guarantee it advertises is truly kept inside. If the box says 'this operation is safe' but its hidden implementation no longer makes it so, everything built on top inherits a lie it cannot detect.\n\nFor this inquiry, that is pointed. When a software module quietly takes over a safety job that hardware used to guarantee, the rest of the system still trusts the old promise on the label. The interface says the machine is protected; the implementation may no longer protect it. Liskov teaches the QA engineer to open the box and check whether the promise on the outside still matches the code within.",
      frame:"The QA engineer slides a module spec across the desk. \"Everyone trusts the label on the box. My job is to open it and see if the promise inside still holds. Show me you know what abstraction really hides.\"",
      q:[
        { q:"What is data abstraction?", o:[
          { t:"Separating what a component promises from how it is implemented inside.", v:"expert", fb:"Users trust the interface; the messy internals stay hidden behind it." },
          { t:"Removing all detail from a program until only comments remain in the file.", v:"wrong", fb:"Abstraction hides implementation behind an interface, not the code itself." },
          { t:"Storing data in the cloud so the program need not keep any of it locally.", v:"wrong", fb:"That is remote storage; abstraction is about interface versus implementation." },
          { t:"Writing every module as one long routine so nothing is hidden from view.", v:"partial", fb:"Abstraction does the opposite: it deliberately hides internals behind a boundary." } ] },
        { q:"What does the Liskov Substitution Principle require?", o:[
          { t:"A subtype must be usable wherever its parent type is expected, unsurprised.", v:"expert", fb:"Substituting a subtype must not break code that relied on the parent." },
          { t:"Every program must be rewritten entirely from scratch whenever a new type is added.", v:"wrong", fb:"The principle governs safe substitution, not wholesale rewriting." },
          { t:"Two programs may be swapped only if they were written in the same language.", v:"wrong", fb:"It is about type behavior within a program, not language compatibility." },
          { t:"A subtype may replace its parent as long as it runs at least as quickly.", v:"partial", fb:"Speed is not the test; behavioral compatibility is." } ] },
        { q:"How does abstraction bear on this malfunction?", o:[
          { t:"A trusted box can hide that its safety guarantee is no longer kept inside.", v:"expert", fb:"The interface may still promise protection the implementation dropped." },
          { t:"A broken promise inside a module can only mean an outsider tampered with it.", v:"danger", fb:"A defect inside the box can break the promise with no intruder at all." },
          { t:"Abstraction guarantees safety, so any well-labeled module can be trusted fully.", v:"danger", fb:"The label can lie; the promise must be checked against the real code." },
          { t:"Since internals are hidden, no one can ever verify what a module truly does.", v:"partial", fb:"They are hidden by default, but QA can and must open the box to verify." } ] }
      ] },
    // cell: Technician Ama @ The Hospital Biomedical Lab
    concurrency:{ sci:"Leslie Lamport (b. 1941)", topic:"Concurrency & race conditions", lede:"The theorist who spent a career on the hardest question in computing: what does it mean for two things to happen at once?", no:7,
      profile:"Leslie Lamport is an American computer scientist and a winner of the Turing Award in 2013, honored for foundational work on distributed and concurrent systems. When many processes run at the same time — separate threads in a program, or separate machines across a network — reasoning about them is treacherous, because they interleave in orders no single mind planned. Lamport built much of the theory that tames this.\n\nIn 1974 his Bakery algorithm solved mutual exclusion — letting concurrent processes take turns at a shared resource without ever colliding — using no special hardware. In his celebrated 1978 paper 'Time, Clocks, and the Ordering of Events in a Distributed System,' he introduced logical clocks and the 'happened-before' relation, a rigorous way to say which events could possibly have influenced which when there is no shared clock. He later framed the Byzantine Generals Problem for fault tolerance, and created both LaTeX and the TLA+ specification language for describing concurrent systems precisely.\n\nAt the center of his world is the race condition: a flaw where a program's correctness depends on the timing or ordering of events. Most of the time the pieces happen to line up and all is well; under a rare, unlucky interleaving, one process reads a value another has not yet finished setting, and the system enters a state no designer intended.\n\nFor this inquiry, this is the crux. If a fast, specific sequence at the console interleaves with the machine's own setup in just the wrong order, a stale value can slip through and the machine can do something lethal — but only under that rare timing. Such a fault is deterministic yet elusive, reproducible only when the race is re-run. It is not an intruder's cunning and not a careless slip; it is the machine losing a race no one knew it was running.",
      frame:"Ama's jaw tightens. \"They say my fast edit did it. It only did it because two things inside that machine were racing each other. Show me you understand what a race condition is.\"",
      q:[
        { q:"What is a race condition?", o:[
          { t:"A flaw where correctness depends on the timing or order of concurrent events.", v:"expert", fb:"An unlucky interleaving lets one process read what another hasn't finished setting." },
          { t:"A contest in which the faster of two computers wins and only its result is kept.", v:"wrong", fb:"It is not a speed contest; it is an ordering flaw between concurrent steps." },
          { t:"An attacker racing the system to break in before defenses come online.", v:"danger", fb:"A race condition is an internal timing bug, not an intruder's move." },
          { t:"A program running slowly because too many users share it at one time.", v:"partial", fb:"That is contention for resources, not the ordering flaw of a race." } ] },
        { q:"What did Lamport's 'happened-before' relation give us?", o:[
          { t:"A way to order events across processes that share no common clock.", v:"expert", fb:"Logical clocks say which events could possibly have influenced which." },
          { t:"A single master clock that forces every machine onto the same exact time.", v:"wrong", fb:"His insight was ordering events without any shared physical clock." },
          { t:"A proof that concurrent programs can never be reasoned about at all.", v:"wrong", fb:"He made concurrency reasoned about rigorously, not declared hopeless." },
          { t:"A method to make slow networks deliver every message instantly.", v:"partial", fb:"It orders events logically; it does not speed message delivery." } ] },
        { q:"Why does a race condition fit this malfunction?", o:[
          { t:"A rare interleaving of console and setup can slip a stale value through.", v:"expert", fb:"Deterministic yet elusive, it strikes only when the same race re-runs." },
          { t:"A timing-dependent fault is the clear signature of a hacker's precise strike.", v:"danger", fb:"A race is an internal ordering bug, not evidence of an intruder." },
          { t:"Because a fast operator is always the true root cause of any timing fault.", v:"partial", fb:"Fast input can trigger a race, but the flaw is the racing code, not the typist." },
          { t:"Because the machine simply behaves at random and no cause can be traced.", v:"wrong", fb:"A race is deterministic under its timing, not truly random." } ] }
      ] },
    // cell: Technician Ama @ The Hospital Biomedical Lab
    synchronization:{ sci:"Edsger Dijkstra (1930-2002)", topic:"Synchronization & deadlock", lede:"The exacting Dutchman who gave concurrent programs their traffic laws — and warned that testing can never prove a program safe.", no:8,
      profile:"Edsger W. Dijkstra was a Dutch computer scientist and a winner of the Turing Award in 1972, famous both for deep results and for sharp, uncompromising opinions. Early on he devised the shortest-path algorithm that still bears his name. But his greatest gift to safety may be his work on coordinating concurrent processes — the very problem at the heart of this case.\n\nDijkstra invented the semaphore, a simple synchronization primitive that lets concurrent processes take turns at a shared resource so they never collide or corrupt each other's work. To dramatize the pitfalls he posed the Dining Philosophers problem, in which philosophers sharing forks can all end up waiting on one another forever — the state called deadlock, where each process holds something the next one needs and none can proceed. His contributions to mutual exclusion and the THE operating system made concurrency something engineers could reason about rather than merely fear.\n\nHe also fought for rigor in ordinary programming. His 1968 letter 'Go To Statement Considered Harmful' helped launch structured programming, and he insisted that 'testing shows the presence, not the absence, of bugs' — a warning that passing tests can never prove a program correct.\n\nFor this inquiry, Dijkstra supplies the missing safeguard. Synchronization exists precisely to prevent one process from reading a value another has not finished writing — to stop the race. Where such coordination is absent or wrong, a concurrent program can slip into a state its designers never intended, entirely on its own. That is a defect in the software's design, not a mistake by whoever happened to be at the console. And because testing cannot prove its absence, such a flaw can survive every trial the makers ran.",
      frame:"Ama pulls up a timing diagram. \"There are rules for letting two processes share the same machine safely. If those rules weren't there, that's not on me. Show me you know how synchronization works.\"",
      q:[
        { q:"Why did Dijkstra invent the semaphore?", o:[
          { t:"To let concurrent processes share a resource in turn without colliding.", v:"expert", fb:"Semaphores coordinate access so one process cannot corrupt another's work." },
          { t:"To make a single program run on many computers at the very same time.", v:"wrong", fb:"A semaphore coordinates concurrent access, not distribution across machines." },
          { t:"To signal an operator by lamp whenever the machine finished a task.", v:"wrong", fb:"It is an internal coordination primitive, not an operator's warning light." },
          { t:"To speed up a program by letting every process run without any waiting.", v:"partial", fb:"It sometimes makes processes wait on purpose, precisely to stay safe." } ] },
        { q:"What is deadlock, as in the Dining Philosophers?", o:[
          { t:"A state where each process waits forever for what another one holds.", v:"expert", fb:"None can proceed, because each holds a resource the next one needs." },
          { t:"A crash that erases memory the moment two processes start at once.", v:"wrong", fb:"Deadlock is endless waiting, not an erasure of memory." },
          { t:"A break-in where an attacker locks the operators out of the machine.", v:"danger", fb:"Deadlock is a concurrency hazard within the program, not an intrusion." },
          { t:"A slowdown that clears itself once the busiest process finally finishes.", v:"partial", fb:"True deadlock never clears on its own; the processes wait indefinitely." } ] },
        { q:"How does synchronization bear on this fault?", o:[
          { t:"Missing or wrong coordination lets a race reach a state no one intended.", v:"expert", fb:"That is a design defect, not a mistake by whoever was at the console." },
          { t:"If the machine passed its tests, synchronization bugs are ruled out for good.", v:"danger", fb:"Dijkstra warned tests show a bug's presence, never its absence." },
          { t:"Any coordination failure must be the work of someone attacking the system.", v:"danger", fb:"Faulty synchronization fails on its own; no attacker is needed." },
          { t:"Since operators run the machine, a timing fault is always operator error.", v:"partial", fb:"Fast input may trigger it, but the flaw is the absent coordination in the code." } ] }
      ] },
    // cell: The Medical Physicist @ The Hospital Biomedical Lab
    overflow:{ sci:"Jacques-Louis Lions (1928-2001)", topic:"Integer overflow & the Ariane 5 inquiry", lede:"The mathematician handed the smoking wreck of Europe's new rocket, who traced a fireball back to a single line of reused code.", no:9,
      profile:"Jacques-Louis Lions was an eminent French mathematician, renowned for work on partial differential equations, numerical analysis, and control theory, and a president of the French Academy of Sciences. In 1996 he was asked to chair the inquiry board into one of the most instructive software failures ever recorded: the maiden flight of the Ariane 5 rocket, Flight 501, which veered off course and self-destructed about 37 seconds after launch on 4 June 1996.\n\nLions's board did not speculate. Methodically, it traced the disaster to the inertial reference system's software. A piece of code carried over from the older, slower Ariane 4 converted a 64-bit floating-point number representing horizontal velocity into a 16-bit signed integer. Ariane 5 flew faster; the value was too large for the small integer to hold. The conversion overflowed and raised an unhandled exception; the reference system shut down, its identical backup failed the same way an instant later, and the guidance fed the rocket nonsense until it tore itself apart. The offending calculation was not even needed after liftoff.\n\nThe report became a landmark. It showed how reusing trusted code in a new context, without re-validating its assumptions, can plant a fatal defect that no one intended and no test on Ariane 5 had exercised.\n\nFor this inquiry, the parallel is exact. An integer overflow is a value too big for the container built to hold it — a small, quiet defect with a catastrophic result. Lions found it not by crying sabotage and not by blaming the launch crew, but by patient analysis of the software and its assumptions. His board is the model: the truth was a concealed defect, and only disciplined reconstruction, not a lurid guess, brought it into the light.",
      frame:"The physicist spreads out a fault trace. \"Ariane 5 was one number too big for its box, and it cost a rocket. Small defects end lives. Show me you understand overflow before I share my reconstruction.\"",
      q:[
        { q:"What is integer overflow?", o:[
          { t:"A value too large for the fixed-size container meant to hold it.", v:"expert", fb:"When it will not fit, the number wraps or raises an error — often disastrously." },
          { t:"A memory chip physically filling until no more data can be written.", v:"wrong", fb:"Overflow is one value exceeding its type's range, not a full memory chip." },
          { t:"A flood of network traffic sent to overwhelm a machine from outside.", v:"danger", fb:"That is a denial-of-service attack; overflow here is an internal arithmetic fault." },
          { t:"A program using more processor time than its schedule allotted to it.", v:"partial", fb:"That is a timing budget issue, not a value exceeding its container." } ] },
        { q:"What did Lions's board find destroyed Ariane 5?", o:[
          { t:"Reused code converted a large velocity into a too-small integer and overflowed.", v:"expert", fb:"The unhandled overflow shut down guidance and the rocket self-destructed." },
          { t:"A guidance beacon jammed by a rival to sabotage Europe's launch.", v:"danger", fb:"There was no sabotage; the board traced it to an internal software defect." },
          { t:"An engine that exploded on the pad from a flaw in its fuel pump.", v:"wrong", fb:"The engines were sound; the failure was in the inertial reference software." },
          { t:"A launch operator who entered the wrong coordinates before liftoff.", v:"partial", fb:"No operator error; the defect was reused code with an unchecked conversion." } ] },
        { q:"What does the Ariane 5 report teach this board?", o:[
          { t:"Reused code in a new context can hide a fatal, unintended defect.", v:"expert", fb:"Patient analysis, not a lurid guess, is what brings such a flaw to light." },
          { t:"A new machine that fails so fast has almost certainly been attacked.", v:"danger", fb:"Ariane 5 showed the opposite; the killer was an ordinary software defect." },
          { t:"Blame the operators first, since crews cause most technical failures.", v:"danger", fb:"Lions blamed neither crew nor saboteur; he found the defect by analysis." },
          { t:"Trust the maker's testing, since a passing test proves the code is safe.", v:"partial", fb:"No Ariane 5 test exercised the flaw; passing tests did not prove it safe." } ] }
      ] },
    // cell: The Medical Physicist @ The Hospital Biomedical Lab
    nullref:{ sci:"Tony Hoare (b. 1934)", topic:"The 'billion-dollar mistake'", lede:"The inventor of Quicksort who, half a century on, apologized to the world for one small feature he had added because it was easy.", no:10,
      profile:"Sir Charles Antony Richard Hoare — 'Tony' Hoare — is a British computer scientist and a winner of the Turing Award in 1980. As a young researcher he devised Quicksort, still among the most widely used sorting algorithms. He went on to found much of the theory of program correctness: Hoare logic, a formal system that reasons about a program using preconditions (what must hold before a step) and postconditions (what must hold after), letting one prove mathematically what code does. He also created CSP, Communicating Sequential Processes, a foundational model of concurrency.\n\nBut Hoare is just as famous for a confession. While designing the language ALGOL W in 1965, he introduced the null reference — a way for a pointer to mean 'nothing.' It was simple to implement and hard to resist. In a 2009 talk he called it his 'billion-dollar mistake,' estimating the untold cost of the crashes, wrong results, and security holes that unchecked null values have caused in the decades since. A single convenient shortcut, multiplied across the industry, became an endless source of failure.\n\nFor this inquiry, Hoare embodies two truths. First, a defect need not be exotic: an unchecked special value — a null, an error code, an exception left unhandled — can let a program march on in an invalid state and do real harm, exactly as Ariane 5's overflow did. Second, such flaws are often born of convenience, chosen because they are easy and cheap, not because anyone meant harm. That is the shape of the truth here: not an attacker's design and not an operator's blunder, but an ordinary, avoidable shortcut in the code that no one caught. Hoare's logic is also the cure — proving, not hoping, that each state is safe.",
      frame:"The physicist frowns at an error log. \"One unhandled value and the machine keeps going as if all is well. Hoare spent his life on that. Show me you understand it before I trust you with the doses.\"",
      q:[
        { q:"What was Hoare's 'billion-dollar mistake'?", o:[
          { t:"Inventing the null reference, whose unchecked use caused decades of failures.", v:"expert", fb:"He called this easy 1965 shortcut a mistake that cost the industry dearly." },
          { t:"Publishing Quicksort before he had fully proven that it always terminates.", v:"wrong", fb:"Quicksort was a triumph; his regret was the null reference." },
          { t:"Selling a badly flawed compiler that shipped with bugs to thousands of buyers.", v:"wrong", fb:"The mistake was a language feature, the null reference, not a sold product." },
          { t:"Designing a sorting method that ran too slowly on very large data sets.", v:"partial", fb:"Quicksort is fast; his self-criticism was aimed at the null reference." } ] },
        { q:"What is Hoare logic?", o:[
          { t:"A formal system proving what code does via preconditions and postconditions.", v:"expert", fb:"It lets one prove, not merely hope, that each program step is correct." },
          { t:"A rule that programs must be tested on every possible input before release.", v:"wrong", fb:"It reasons about code mathematically rather than by exhaustive testing." },
          { t:"A style guide requiring short functions and clear names throughout code.", v:"wrong", fb:"It is a proof system about behavior, not a formatting convention." },
          { t:"A checklist of common bugs to scan for during a manual code review.", v:"partial", fb:"It is a rigorous logic of correctness, not an informal review checklist." } ] },
        { q:"How does Hoare's story bear on this malfunction?", o:[
          { t:"An unchecked special value can let a program run on in an invalid state.", v:"expert", fb:"Such easy, cheap shortcuts, not malice, are the usual shape of a defect." },
          { t:"An unhandled error is the unmistakable calling card of a system intrusion.", v:"danger", fb:"An unhandled value fails on its own; it is a defect, not proof of a break-in." },
          { t:"A convenient shortcut in code is harmless, since compilers catch them all.", v:"danger", fb:"Compilers miss many; unchecked nulls have caused untold real failures." },
          { t:"A crash only ever happens when an operator feeds the machine bad input.", v:"partial", fb:"Internal unchecked values crash programs with no bad operator input at all." } ] }
      ] },
    // cell: The QA Engineer @ The Hospital Biomedical Lab
    testing:{ sci:"Glenford Myers (software-testing pioneer)", topic:"Testing & its limits", lede:"The engineer who insisted a good test is one that fails — because a test meant to confirm success will quietly let bugs live.", no:11,
      profile:"Glenford Myers is an American computer scientist and author whose 1979 book 'The Art of Software Testing' became a foundational text of the discipline. He also wrote influential work on structured design, including the ideas of coupling and cohesion for judging how well a program is broken into modules, and worked in industry on major hardware and software systems.\n\nMyers's central and counterintuitive point concerns the psychology of testing. Most people, he observed, unconsciously test to show a program works — and so they run the gentle cases that pass, and feel reassured. That, he argued, is exactly backwards. Testing should be defined as the process of executing a program with the intent of finding errors, and a successful test case is one that exposes a previously undetected fault. A test run that finds nothing has, in this view, largely wasted its effort. He drove home how easily a single small program can hide errors, and how our desire to see success blinds us to failure.\n\nHe also stressed a hard limit: exhaustive testing — trying every possible input and path — is practically impossible for any real program. You can never test a program into being correct; you can only sample. Testing, at best, reveals some bugs; it can never prove there are none.\n\nFor this inquiry, Myers dismantles a comforting alibi. When a maker says the machine 'passed all its tests,' that clears nothing. A rare defect — a race that fires only under an unusual timing, a value checked in every case but the fatal one — can survive every trial the makers ever ran. 'It was tested' is not 'it was safe.' Myers arms the QA engineer to reject both the shrug of operator error and the certainty that a tested machine cannot be flawed.",
      frame:"The QA engineer doesn't look up. \"They'll wave the test reports at you like a clean bill of health. A test that passes tells you almost nothing. Show me you know what testing can and can't prove.\"",
      q:[
        { q:"What did Myers say the goal of testing should be?", o:[
          { t:"To find errors — a good test is one that exposes a previously hidden bug.", v:"expert", fb:"Testing to confirm success quietly lets faults survive undetected." },
          { t:"To confirm the program works, running the cases most likely to pass.", v:"danger", fb:"Myers called that mindset backwards; it hides bugs rather than finding them." },
          { t:"To measure how fast the program runs under a heavy user workload.", v:"wrong", fb:"That is performance testing; Myers meant the hunt for correctness errors." },
          { t:"To document the features so future programmers know how to use them.", v:"partial", fb:"Tests can inform, but their purpose per Myers is to reveal defects." } ] },
        { q:"What is testing's fundamental limit?", o:[
          { t:"Exhaustive testing is impossible, so tests never prove a program correct.", v:"expert", fb:"Tests can reveal some bugs; they can never show that none remain." },
          { t:"Testing catches every bug if you simply write enough test cases.", v:"danger", fb:"No finite set of tests is exhaustive; some defects always slip through." },
          { t:"Testing works only on hardware, never on the software running on it.", v:"wrong", fb:"Myers's whole subject is testing software; the limit is exhaustiveness." },
          { t:"Testing must be done by the programmer who wrote the code being tested.", v:"partial", fb:"Independence helps, but the deeper limit is that testing cannot be exhaustive." } ] },
        { q:"What does 'it passed all its tests' prove here?", o:[
          { t:"Very little — a rare defect can survive every trial the makers ran.", v:"expert", fb:"Passing tests is not safety; a timing bug can hide in the untested case." },
          { t:"That the machine is fully safe, so the fault must lie with the operator instead.", v:"danger", fb:"Passing tests cannot clear a defect; it shifts nothing onto the operator." },
          { t:"That any remaining fault was planted deliberately after testing ended.", v:"danger", fb:"Untested paths can hide honest defects; no saboteur is implied." },
          { t:"That the program is correct on every input it was actually given.", v:"partial", fb:"Only on the inputs tried; the fatal case may never have been run." } ] }
      ] },
    // cell: The QA Engineer @ The Hospital Biomedical Lab
    formalmethods:{ sci:"Robert W. Floyd (1936-2001)", topic:"Proving programs correct", lede:"A college dropout turned Stanford professor who showed you could prove a program right the way a mathematician proves a theorem.", no:12,
      profile:"Robert W. Floyd was an American computer scientist and a winner of the Turing Award in 1978. Remarkably, he had no doctorate; largely self-taught after an early degree, he became a full professor at Stanford on the strength of his ideas. His landmark 1967 paper 'Assigning Meanings to Programs' launched the field of formal verification. Floyd proposed attaching logical assertions to points within a program's flowchart — statements that must be true whenever control reaches that point — and showed how, by reasoning from one assertion to the next, you could prove that the whole program meets its specification.\n\nThis method of inductive assertions directly inspired Tony Hoare's logic and the broader discipline of formal methods. Floyd also gave computing the Floyd-Warshall shortest-path algorithm, a cycle-detection technique, and foundational work in parsing. His conviction was that programming should aspire to the rigor of mathematics rather than the trial and error of tinkering.\n\nThe appeal of proof is precisely what testing lacks. A test checks a program on the cases you happen to run; a proof establishes correctness for all inputs at once, closing the gap where a rare defect hides. For software that can kill, that difference is everything.\n\nFor this inquiry, Floyd points to what was missing. A correctness proof is only as good as the specification it covers. If the software's concurrent behavior — its timing, its shared state — was never formally specified and proven, or if a proof was inherited from an older, slower context and never redone, then the fatal race was simply never ruled out. That omission is a defect in engineering discipline, not a mistake by the person at the console. Floyd's standard exposes the difference between a machine that was proven safe and one that was merely assumed to be.",
      frame:"The QA engineer sets down a spec. \"You can prove a program correct, not just poke at it and hope. If nobody proved the timing was safe, that's the whole story. Show me you understand what a proof buys you.\"",
      q:[
        { q:"What did Floyd's inductive assertions do?", o:[
          { t:"Attach logical assertions to points in a program to prove it meets its spec.", v:"expert", fb:"Reasoning from assertion to assertion proves the program correct." },
          { t:"Insert print statements so a programmer can watch the values go by.", v:"wrong", fb:"Assertions are proof conditions, not debugging printouts." },
          { t:"Run the program on random inputs to estimate how often it fails.", v:"wrong", fb:"That is statistical testing; Floyd's method is mathematical proof." },
          { t:"Comment each line of code so future readers understand the intent.", v:"partial", fb:"Assertions are formal claims to be proven, not explanatory comments." } ] },
        { q:"Why prove a program rather than only test it?", o:[
          { t:"A proof covers all inputs at once, where testing samples only some.", v:"expert", fb:"Proof closes the gap where a rare, untested defect can hide." },
          { t:"A proof runs the program faster than testing it repeatedly does.", v:"wrong", fb:"Proof concerns correctness, not runtime speed." },
          { t:"Proof lets you skip writing a specification for what the code should do.", v:"danger", fb:"Proof needs a specification; it verifies against it, not instead of it." },
          { t:"Testing is useless, so proof is the only way to gain any confidence.", v:"partial", fb:"Testing has value; proof simply covers what sampling cannot." } ] },
        { q:"How does Floyd's standard bear on this fault?", o:[
          { t:"If the concurrent timing was never proven safe, the race was never ruled out.", v:"expert", fb:"That omission is a defect in engineering discipline, not operator error." },
          { t:"An unproven program can only ever fail if someone attacks it from the outside.", v:"danger", fb:"An unproven race fails on its own; no intruder is required." },
          { t:"Once code runs at all, it is proven correct and needs no further check.", v:"danger", fb:"Running is not proof; correctness must be established, not assumed." },
          { t:"A proof from the old, slower system fully covers the new machine too.", v:"partial", fb:"A proof inherited from a different context may not cover the new timing at all." } ] }
      ] },
    // cell: Technician Ama @ The Manufacturer's Software Office
    softwaresafety:{ sci:"Nancy Leveson (b. 1948)", topic:"Software safety engineering", lede:"The engineer who dissected the era's most notorious medical software deaths and built a whole discipline so they need not repeat.", no:13,
      profile:"Nancy Leveson is an American professor at MIT and the founder of modern software system safety. Her book 'Safeware' (1995) and later 'Engineering a Safer World' (2011) reshaped how engineers think about safety in computer-controlled systems. She is also known for the definitive technical analysis, with Clark Turner, of the Therac-25 — a radiation-therapy machine whose software gave several patients massive overdoses in the 1980s, killing some of them.\n\nLeveson's investigation of that machine is a founding case study of the field, and its findings are directly relevant here. The Therac-25 overdoses were not caused by a saboteur or by careless operators. They arose from software defects — race conditions that struck only when an experienced operator edited settings quickly — combined with a fateful design decision: earlier models had hardware interlocks that physically prevented an unsafe beam, but the Therac-25 removed them and trusted software alone. When the software failed, nothing else stood in the way.\n\nFrom such cases Leveson drew principles that overturn intuition. Software does not wear out or fail randomly like a gear; it fails from design and requirements errors built in from the start. Safety, she argues, is a property of the whole system, not something you get by making each component individually reliable — a perfectly reliable component doing the wrong thing is still deadly. Accidents in complex systems come from flawed interactions and missing constraints, not just isolated bugs.\n\nFor this inquiry, Leveson is the clearest lens on the truth. She teaches that a lethal radiation fault most often comes from a concealed software defect and a stripped-away safeguard — not from a hacker's cunning, not from a nurse's slip. Her work is the map for finding exactly that.",
      frame:"Ama lowers her voice in the vendor's own office. \"There's a woman who took apart machines exactly like this one and found what really killed people. Show me you understand software safety before I tell you what I saw here.\"",
      q:[
        { q:"How does software fail, in Leveson's account?", o:[
          { t:"From design and requirements errors built in, not from wear or random faults.", v:"expert", fb:"Software has no gears to wear out; its faults are baked in from the start." },
          { t:"By slowly degrading with use until, like a worn bearing, it breaks down.", v:"wrong", fb:"Software does not wear; that is a hardware failure model, not a software one." },
          { t:"Only when an outside attacker corrupts it, since clean code cannot fail.", v:"danger", fb:"Software fails on its own from design errors, with no attacker involved." },
          { t:"At random intervals that engineers can predict well with a failure-rate curve.", v:"partial", fb:"Random-failure curves fit hardware; software faults are systematic, not random." } ] },
        { q:"What is Leveson's central principle of system safety?", o:[
          { t:"Safety is a property of the whole system, not of reliable parts alone.", v:"expert", fb:"A reliable component doing the wrong thing is still deadly." },
          { t:"Making every single component reliable enough guarantees a safe system.", v:"danger", fb:"Leveson rejects this; safety emerges from interactions, not part reliability." },
          { t:"Safety comes from training operators to never make a mistake at all.", v:"wrong", fb:"She locates safety in system design, not in flawless operators." },
          { t:"Safety is achieved once the software passes its full test suite cleanly.", v:"partial", fb:"Passing tests is not safety; safety is a designed system property." } ] },
        { q:"What did the Therac-25 overdoses actually come from?", o:[
          { t:"Software race conditions plus hardware interlocks that had been removed.", v:"expert", fb:"A concealed defect with the physical safeguard stripped away — not sabotage." },
          { t:"A malicious intrusion into the hospital's radiation-therapy machine.", v:"danger", fb:"Leveson found no attacker; the cause was defective software and lost interlocks." },
          { t:"Operators who repeatedly ignored clear warnings the machine displayed.", v:"danger", fb:"The operators were not the cause; a hidden race and removed interlocks were." },
          { t:"A single miscalibrated sensor that reported the wrong dose to the console.", v:"partial", fb:"It was software timing and removed interlocks, not one stray sensor." } ] }
      ] },
    // cell: Technician Ama @ The Manufacturer's Software Office
    criticalsoftware:{ sci:"David Parnas (b. 1941)", topic:"Safety-critical software & its limits", lede:"The computer scientist who invented modular design, then publicly quit a weapons program rather than pretend its software could be trusted.", no:14,
      profile:"David Parnas is a computer scientist whose 1972 paper 'On the Criteria To Be Used in Decomposing Systems into Modules' gave the field the principle of information hiding: each module should conceal a design decision behind a stable interface, so that when that decision changes, the damage stays inside the module. This idea underlies modularity, encapsulation, and much of how large software is structured today. Parnas also did rigorous work on precise software documentation and tabular specifications for critical systems.\n\nHe is equally remembered for an act of conscience. In 1985 he resigned from an advisory panel on the software for the Strategic Defense Initiative — the 'Star Wars' missile-defense program — and published his reasons. His argument was technical, not political: software of that complexity could never be adequately tested under the conditions it would actually face, and therefore could not be trusted to work correctly the first time it truly mattered. You cannot, he insisted, gain justified confidence in software that has never met its real-world triggering conditions.\n\nThat warning is the core of safety-critical engineering. Complex software routinely contains states that are never exercised until some rare, real combination of events arrives — and by then it is too late to discover the flaw gently. Modularity helps organize such software, but it can also hide a defect inside a module that everyone trusts and no one has opened.\n\nFor this inquiry, Parnas cautions against the very confidence the maker will offer. A radiotherapy machine's software may have run flawlessly for years and still harbor a lethal state waiting for one rare timing. That is neither an attacker's doing nor an operator's error — it is untested-in-reality software finally meeting its trigger. Parnas teaches the investigator to distrust 'it always worked before.'",
      frame:"Ama keeps her voice flat. \"They'll tell you this software ran for years without trouble. There was a man who quit a whole program over that kind of confidence. Show me you understand its limits.\"",
      q:[
        { q:"What is Parnas's principle of information hiding?", o:[
          { t:"Each module conceals a design decision behind a stable interface.", v:"expert", fb:"When that decision changes, the damage stays inside the module." },
          { t:"Sensitive data should be encrypted so intruders cannot ever read it.", v:"wrong", fb:"Information hiding is about design decisions, not data encryption." },
          { t:"Source code should be kept secret from the customers who buy it.", v:"wrong", fb:"It concerns internal module boundaries, not commercial secrecy." },
          { t:"Every module should expose all of its internals so others can reuse them.", v:"partial", fb:"It does the reverse: modules hide internals behind a narrow interface." } ] },
        { q:"Why did Parnas resign from the SDI software panel?", o:[
          { t:"He argued such software could never be adequately tested for its real conditions.", v:"expert", fb:"It could not be trusted to work correctly the first time it truly mattered." },
          { t:"He believed that no computer was ever fast enough to run the missile-defense code.", v:"wrong", fb:"His objection was untestability and trust, not raw processing speed." },
          { t:"He was ordered to insert a backdoor and refused on ethical grounds.", v:"wrong", fb:"His published reason was the impossibility of adequate testing, not a backdoor." },
          { t:"He thought the project simply needed more programmers to succeed.", v:"partial", fb:"He argued the trust problem was fundamental, not a staffing shortfall." } ] },
        { q:"How does Parnas's warning apply to this machine?", o:[
          { t:"Software may run for years and still hide a lethal state awaiting a rare trigger.", v:"expert", fb:"That is untested-in-reality code meeting its trigger, not sabotage or a slip." },
          { t:"Software that ran for years is surely proven safe, so the operator is at fault.", v:"danger", fb:"Years of use is not proof; a rare untriggered state can still be lethal." },
          { t:"A long record of safe use means only a hacker could have changed things.", v:"danger", fb:"A latent defect can surface on its own; no intruder need be involved." },
          { t:"If it worked before, any new fault must come from worn-out hardware.", v:"partial", fb:"Software does not wear; a dormant defect can strike with hardware intact." } ] }
      ] },
    // cell: The Medical Physicist @ The Manufacturer's Software Office
    robusterror:{ sci:"Margaret Hamilton (b. 1936)", topic:"Robust error handling & Apollo", lede:"The programmer whose software refused to crash while a lunar lander screamed alarms three minutes from touchdown.", no:15,
      profile:"Margaret Hamilton is an American computer scientist who led the team that wrote the onboard flight software for NASA's Apollo missions at the MIT Instrumentation Laboratory. She is often credited with popularizing the very term 'software engineering,' insisting that writing reliable code deserved the same rigor as any other engineering discipline. Her work faced the ultimate stakes: software that had to keep a spacecraft and its crew alive with no chance to patch it midflight.\n\nHamilton's guiding obsession was robust error handling — designing software that behaves sensibly when something unexpected happens, rather than simply failing. This was vindicated dramatically during the Apollo 11 landing in 1969. Minutes from the Moon, the guidance computer was overwhelmed by data from a radar switch left in the wrong position, and it began flashing 1201 and 1202 alarms. Because Hamilton's team had built in priority scheduling, the computer shed its lower-priority tasks and kept doing the essential job of landing, instead of freezing. The mission continued; the design absorbed the fault.\n\nHer principle is that a safe system anticipates errors and asynchronous events and has a planned, safe response to each — it degrades gracefully. The opposite is software that meets an unexpected condition and either halts or, far worse, proceeds blindly in an invalid state.\n\nFor this inquiry, Hamilton sets the standard the machine failed to meet. When a radiotherapy console meets a rare timing fault, robust software would detect the inconsistency and refuse to fire — fail safe. Instead, a poorly handled error can let the machine deliver a lethal beam while showing a cryptic code. That is a defect in the software's design, not a hacker's payload and not an operator's error. Hamilton teaches the investigator to ask what the software did when it hit the unexpected — and whether it was ever built to fail safe.",
      frame:"The physicist studies an alarm printout. \"Good software catches the unexpected and refuses to do harm. This one flashed a code and fired anyway. Show me you understand error handling before I walk you through it.\"",
      q:[
        { q:"What is robust error handling, in Hamilton's sense?", o:[
          { t:"Software that meets the unexpected and responds safely instead of failing.", v:"expert", fb:"It anticipates errors and degrades gracefully rather than acting blindly." },
          { t:"Software that runs faster by skipping checks it decides are unnecessary.", v:"danger", fb:"Skipping checks is the opposite; robustness means handling errors, not skipping them." },
          { t:"Hardware built so sturdily that the software inside can never crash at all.", v:"wrong", fb:"It is a software design discipline, not a matter of rugged hardware." },
          { t:"Code that stops the whole machine the instant any small anomaly appears.", v:"partial", fb:"Halting is one response; Hamilton aimed for a planned, safe continuation." } ] },
        { q:"What happened during the Apollo 11 landing?", o:[
          { t:"Priority scheduling shed low-value tasks so the computer kept landing.", v:"expert", fb:"The design absorbed an overload and continued the essential job." },
          { t:"The computer crashed and the crew landed the module entirely by hand.", v:"wrong", fb:"It did not crash; it shed tasks and kept running the landing." },
          { t:"A hacker's signal triggered the 1202 alarms during the final descent.", v:"danger", fb:"The alarms came from a misconfigured radar switch, not any intrusion." },
          { t:"The alarms forced an abort and the landing was scrubbed until later.", v:"partial", fb:"There was no abort; the robust software let the landing proceed." } ] },
        { q:"How does Hamilton's standard bear on this fault?", o:[
          { t:"Robust software would detect the inconsistency and refuse to fire the beam.", v:"expert", fb:"Firing anyway on a rare fault is a design defect, not sabotage or a slip." },
          { t:"A machine that fires on an error must have been commanded by an intruder.", v:"danger", fb:"Poor error handling fires unsafely on its own; no intruder is needed." },
          { t:"A cryptic error code proves the operator typed something they should not.", v:"danger", fb:"The code signals a software fault, not proof of an operator's mistake." },
          { t:"If the machine kept running, the error was minor and can be set aside.", v:"partial", fb:"Continuing through an unhandled error is precisely the dangerous failure." } ] }
      ] },
    // cell: The Medical Physicist @ The Manufacturer's Software Office
    hci:{ sci:"Donald Norman (b. 1935)", topic:"Human error & design", lede:"The scientist who looked at a door people always push the wrong way and blamed the door, not the person.", no:16,
      profile:"Donald Norman is an American cognitive scientist and designer whose 1988 book 'The Design of Everyday Things' reshaped how the world thinks about human error. A former engineer and psychologist who later worked at Apple, Norman argued that when people repeatedly misuse a device, the fault usually lies not in the people but in the design. His 'Norman doors' — doors whose handles invite the wrong action — became a byword for design that sets its users up to fail.\n\nNorman's central concepts are affordances (what a design suggests you can do), signifiers and feedback (how it tells you what is happening), and the crucial idea that good design makes the right action easy and the wrong action hard. He distinguished slips (doing the wrong thing while intending the right one) from mistakes (intending the wrong thing), and insisted that blaming the operator ends the inquiry too soon. Behind most 'human error,' he wrote, is a system that made the error likely and gave the person no way to catch or recover from it.\n\nCrucially, Norman warned that calling something 'human error' is a comforting stopping point that hides the real, fixable cause and leaves the next person to make the same mistake.\n\nFor this inquiry, Norman confronts the dismissal head-on. When a console gives terse, ambiguous feedback, lets a fast edit put the machine into a hidden dangerous state, and offers no clear signal of danger, an operator who triggers a fault has been trapped by the design, not merely careless. 'Operator error' is exactly the label Norman spent his career dismantling. He teaches the investigator to ask what the machine told the operator, what it let them do, and whether it was built so the human could ever have known.",
      frame:"The physicist taps the console screen. \"They want to call this operator error and go home. There's a scientist who'd say the design trapped her. Show me you understand human error before I tell you what she faced.\"",
      q:[
        { q:"What is Norman's core claim about human error?", o:[
          { t:"Repeated misuse usually signals bad design, not a careless user.", v:"expert", fb:"Good design makes the right action easy and the wrong one hard." },
          { t:"Most errors come from users who fail to read the manual carefully.", v:"danger", fb:"Norman rejects this; he locates the fault in the design, not the reader." },
          { t:"Errors are unavoidable, so studying their causes is a waste of effort.", v:"wrong", fb:"He held that design can prevent most errors, so studying them matters." },
          { t:"Errors happen only to untrained people who lack real experience.", v:"partial", fb:"Even experts are trapped by poor design; training is not the whole answer." } ] },
        { q:"What are affordances and feedback in Norman's design?", o:[
          { t:"What a design suggests you can do, and how it tells you what happened.", v:"expert", fb:"They let a user form a correct picture of the device and its state." },
          { t:"The colors and fonts a designer picks to make a product look modern.", v:"wrong", fb:"They concern possible actions and information, not surface styling." },
          { t:"The legal warnings printed on a device to shield the maker from blame.", v:"wrong", fb:"They are design cues about use, not liability disclaimers." },
          { t:"The speed at which a machine responds once a button has been pressed.", v:"partial", fb:"Feedback is broader than speed; it is how the device reveals its state." } ] },
        { q:"How does Norman challenge the 'operator error' verdict?", o:[
          { t:"A design that hides danger and invites the slip has trapped the operator.", v:"expert", fb:"'Operator error' is the label Norman spent his career dismantling." },
          { t:"Since only a person can press the keys, the operator is nearly always to blame.", v:"danger", fb:"Norman shows the design, not the last hand on the keys, is often the cause." },
          { t:"A confusing console proves an intruder altered its display to mislead.", v:"danger", fb:"Poor feedback is a design failure, not evidence of tampering." },
          { t:"If the operator was trained, then the fault has to be theirs alone.", v:"partial", fb:"Training cannot rescue a design that hides the machine's dangerous state." } ] }
      ] },
    // cell: The QA Engineer @ The Manufacturer's Software Office
    complexity:{ sci:"Donald Knuth (b. 1938)", topic:"The analysis of algorithms", lede:"The perfectionist who mails a small reward for every error found in his books, and built a science out of counting an algorithm's every step.", no:17,
      profile:"Donald Knuth is an American computer scientist at Stanford, often called the father of the analysis of algorithms. His multi-volume work 'The Art of Computer Programming,' begun in the 1960s and still unfinished, sets a standard of rigor for the field, and he won the Turing Award in 1974. Frustrated by poor typesetting of his own mathematics, he also created the TeX system, and he championed 'literate programming,' the idea that programs should be written to be read by humans as much as executed by machines.\n\nKnuth's signature contribution is the rigorous analysis of algorithms: determining precisely how much time and memory a procedure needs, and how those costs grow as the problem gets larger. This is the world of Big-O notation, which describes the growth rate of an algorithm's cost while ignoring incidental constants, letting engineers compare methods and predict behavior at scale. Crucially, good analysis considers every case — not just the typical run, but the worst case and the rare one.\n\nHis perfectionism is legendary: he famously offers a small monetary reward for each genuine error found in his books, and once quipped, 'Beware of bugs in the above code; I have only proved it correct, not tried it.' Behind the joke is a serious point about the limits of confidence.\n\nFor this inquiry, Knuth stands for the discipline of accounting for every case, including the rare one. A defect that appears only under an unusual timing or an uncommon input is invisible to casual use and typical testing, yet it is exactly the case rigorous analysis is meant to catch. Complexity is where such faults hide. Knuth teaches the QA engineer that a machine is not understood until its rare and worst cases are understood — and that is where this truth was buried.",
      frame:"The QA engineer taps a thick manual. \"There's a man who counts every step an algorithm can take, including the rare ones nobody runs. That rare case is where this hid. Show me you can think that way.\"",
      q:[
        { q:"What is the analysis of algorithms, Knuth's field?", o:[
          { t:"The rigorous study of the time and memory a procedure needs, in every case.", v:"expert", fb:"It predicts behavior at scale and across worst and rare cases alike." },
          { t:"The art of writing code as quickly as possible to meet a deadline.", v:"wrong", fb:"It is rigorous mathematical study, not a race to write code fast." },
          { t:"The practice of guessing which program will feel fastest to a user.", v:"wrong", fb:"It measures cost precisely rather than relying on subjective feel." },
          { t:"The study of how to lay out one's code neatly so that others can easily read it.", v:"partial", fb:"Readability matters to Knuth, but analysis is about time and space costs." } ] },
        { q:"What does Big-O notation describe?", o:[
          { t:"How an algorithm's cost grows with input size, ignoring constants.", v:"expert", fb:"It captures the growth rate so methods can be compared at scale." },
          { t:"The exact number of seconds a program will take on a given machine.", v:"wrong", fb:"It gives growth rate, not an exact wall-clock time on one machine." },
          { t:"The count of lines of code a programmer wrote to solve a problem.", v:"wrong", fb:"It measures resource growth, not the length of the source code." },
          { t:"The largest input a computer can hold in its memory at any one time.", v:"partial", fb:"It concerns how cost scales with input, not a memory capacity limit." } ] },
        { q:"How does Knuth's rigor bear on this hidden fault?", o:[
          { t:"A defect in a rare case is invisible to casual use but caught by analysis.", v:"expert", fb:"Rigorous accounting of every case is what rare-timing faults require." },
          { t:"A fault seen only rarely must have been slipped in by an attacker.", v:"danger", fb:"Rare defects hide in ordinary complexity; no intruder is implied." },
          { t:"If the common case works, the rare case can safely be ignored entirely.", v:"danger", fb:"The rare case is exactly where this lethal fault lived; it cannot be ignored." },
          { t:"Only very large programs can hide such faults, so small code is always safe.", v:"partial", fb:"Even small code hides rare-case defects; size is no guarantee of safety." } ] }
      ] },
    // cell: The QA Engineer @ The Manufacturer's Software Office
    mythicalmonth:{ sci:"Fred Brooks (1931-2022)", topic:"Schedule pressure & the mythical man-month", lede:"The manager of a legendary software fiasco who turned his hardest lessons into the book every project ignores at its peril.", no:18,
      profile:"Frederick P. Brooks Jr. was an American computer architect and software engineer who managed the development of IBM's System/360 mainframe and its enormous, troubled operating system, OS/360. From that ordeal he distilled 'The Mythical Man-Month' (1975), still one of the most quoted books in software engineering. He later won the Turing Award in 1999 for his contributions to computer architecture and software.\n\nHis most famous lesson, now called Brooks's Law, is counterintuitive: adding manpower to a late software project makes it later. New people must be trained and coordinated, and the communication overhead grows faster than the extra hands can help. A project is 'mythical' in treating people and months as interchangeable — you cannot simply throw bodies at a deadline. In his 1986 essay 'No Silver Bullet,' Brooks argued there is no single technique that yields an order-of-magnitude improvement, because much of software's difficulty is essential complexity inherent in the problem, not incidental. He also prized 'conceptual integrity' — a coherent design vision — as the key to good systems.\n\nBeneath these ideas runs a warning about schedule and cost pressure. When a project falls behind or over budget, the temptation is to cut corners: trim testing, reuse code without re-checking it, or strip out a safeguard to save money and time.\n\nFor this inquiry, Brooks names the motive. A maker under pressure to ship cheaply and fast may quietly remove a costly hardware interlock, skimp on the testing that would expose a rare defect, and reuse code beyond its safe limits — then present a machine that looks finished. That is how a concealed defect gets built and shipped. It is a failing of the maker and its schedule, not an attacker's plot and not an operator's slip. Brooks teaches the investigator to follow the pressure.",
      frame:"The QA engineer's voice goes cold. \"Everything on this project bent to the schedule and the budget. Corners got cut where you can't see them. Show me you understand schedule pressure, and I'll tell you which corner.\"",
      q:[
        { q:"What is Brooks's Law?", o:[
          { t:"Adding manpower to a late software project only makes it later.", v:"expert", fb:"Training and coordination overhead outpaces the help new hands provide." },
          { t:"Doubling the programmers on a project always halves the time it takes.", v:"danger", fb:"Brooks's Law is exactly the opposite; people and months are not interchangeable." },
          { t:"A project's cost is fixed once the first line of code has been written.", v:"wrong", fb:"His law concerns adding people to a late project, not fixed early costs." },
          { t:"The best programmers are worth about ten of the merely average ones.", v:"partial", fb:"Talent varies, but Brooks's Law is specifically about adding late manpower." } ] },
        { q:"What did Brooks argue in 'No Silver Bullet'?", o:[
          { t:"No single technique gives an order-of-magnitude gain against essential complexity.", v:"expert", fb:"Much of software's difficulty is inherent and cannot be conjured away." },
          { t:"A brand-new programming language would very soon make all software effortless to write.", v:"danger", fb:"He argued the reverse; no single advance slays the essential complexity." },
          { t:"Better hardware would shortly remove the need for careful software at all.", v:"wrong", fb:"His point was about inherent software difficulty, not hardware speed." },
          { t:"Only larger teams could ever tackle the hardest software problems.", v:"partial", fb:"He warned larger teams add overhead; the essential complexity remains." } ] },
        { q:"How does schedule pressure bear on this defect?", o:[
          { t:"Pressure tempts a maker to cut testing and strip a costly safeguard to ship.", v:"expert", fb:"That is how a concealed defect is built in — a maker's failing, not a slip." },
          { t:"A rushed project is safe, since deadlines force programmers to focus harder.", v:"danger", fb:"Rushing invites cut corners and hidden defects, not extra safety." },
          { t:"Budget cuts can only hurt a project if an attacker exploits the gaps later.", v:"danger", fb:"Cost-cutting plants defects directly; no attacker is needed to cause harm." },
          { t:"Schedule slips are the operator's problem and never reach the software.", v:"partial", fb:"Schedule pressure shapes the software itself, planting the very defect here." } ] }
      ] }
  },
  STORIES:{
    tech:{
      treatment:"Ama stands at her own console, arms crossed, as if the room might accuse her. \"This is where I typed the edit they hung me with. I did my job the way I always do — and the machine did something I've never seen.\"",
      biomed:"She looks lost among the physicist's meters and phantoms. \"I don't speak this language of dose curves, but I know what I saw on that screen. Tell me your numbers agree that it wasn't me.\"",
      vendor:"In the maker's glass office Ama keeps her back straight and her voice low. \"They built this thing and now they watch me take the blame for it. Somebody in this building knows more than they're saying.\""
    },
    phys:{
      treatment:"The physicist runs a hand along the console housing, unimpressed. \"The operators keep telling me what they typed. I care what the machine delivered — and the beam that day was nothing like what the screen promised.\"",
      biomed:"Surrounded by dosimeters and film, the physicist is finally at home. \"I reconstructed every dose. The patient was not the variable here. The machine handed out a fault, and I can show you the shape of it.\"",
      vendor:"In the maker's office the physicist lays the reconstruction on the table like a verdict. \"Your machine, not my patient, was wrong. I have the numbers. Now I want to know what you knew when you shipped it.\""
    },
    qa:{
      treatment:"The QA engineer lingers at the console, uneasy at the scene of the harm. \"I tested machines like this for a living. Standing here, I keep thinking about the report nobody wanted filed.\"",
      biomed:"Beside the physicist's reconstruction the QA engineer nods slowly. \"Your numbers match what I feared. This wasn't a wild dose — it was a specific fault, the kind that only shows up when the timing lines up wrong.\"",
      vendor:"On home ground the QA engineer is quietest of all. \"The memo is in this building. I know because I helped write it. Follow the engineering and the schedule, and you'll find what they buried.\""
    }
  },
  story:[
    "The <b>Calder radiotherapy machine</b> was supposed to save lives with a precisely measured beam. Instead, on a handful of ordinary treatment days, it delivered radiation doses a hundred times what the screen displayed, and patients who came in for healing went home dying. You are <b>Auditor Lena Foss</b>, and the inquiry has handed you the machine, the logs, and a room full of people who would each rather the blame landed anywhere but on them.",
    "<b>Three people inside will help you</b>, each holding a piece and none the whole. <b>Technician Ama</b>, who typed the fast edit they blame her for and swears she saw a cryptic 'MALFUNCTION 54' on the screen. <b>The Medical Physicist</b>, who reconstructed the doses and can prove the machine, not the patient, was wrong. And <b>the QA Engineer</b> from the manufacturer, who knows which reports were filed and which were quietly shelved. Earn their trust and they will talk.",
    "<b>Someone here is behind it.</b> Three names sit in your notepad: the <b>radiotherapy technicians</b>, who ran the console; <b>Renwick</b>, the manufacturer's software lead, who owned the code; and the <b>hospital physicist</b>, who signed off on the equipment. Every column of the case — <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> truly happened — hides a tempting wrong answer. The headlines want <b>a malicious hack, the machine seized by an attacker</b>. The quick file wants <b>simple operator error, nothing systemic</b>. The truth is narrower than the first and graver than the second — and it is quieter than either.",
    "You have <b>8 days</b> and a single accusation to make. Name it well and a buried engineering finding becomes proof; name it wrong and a real, provable failure is lost to a headline or a scapegoat, waiting for the next patient on the table."
  ],
  endings:{ overclaimWhat:"hack", dismissalWhat:"usererror",
    win:{
      expertTitle:"What the Code Proves, and No More",
      expert:["Foss names it exactly: Renwick, the manufacturer's software lead, who owned the code and buried the finding; the truth culminating in the Manufacturer's Software Office, where the flawed program and the shelved report live; and a concealed software defect — a race condition that fires under a rare timing — made lethal because a hardware interlock had been removed to save cost. Not a hack. Not a careless technician.",
        "Every card accounted for. Foss worked the console, the biomedical lab, and the vendor's office, turned a wary QA engineer into a witness, and claimed precisely what the logs and the memo could defend. The inquiry issues findings that recall the machine and restore the interlock — which is the entire point of doing it right."],
      soundTitle:"Right — but Lightly Proven",
      sound:["Foss names the right three — Renwick, the Software Office, and the concealed defect with its stripped-out interlock. The shape of the case is correct, and the refusal to cry sabotage or blame the technician is exactly right.",
        "But too many threads were left loose, and the maker's lawyers will pull at them. A few more days tracing the race condition and the shelved report would have made the finding unassailable. Close and honest, if not yet airtight."],
      namedTitle:"The Right Answer, Unearned",
      named:["Foss names the truth — Renwick, the Software Office, the concealed defect and removed interlock — but gathered too little to back it. It reads like a hunch that happened to land.",
        "The inquiry cannot recall a machine on an accusation this thin, however correct. Being right is not the same as being able to prove it to the people who will fight the finding in court."]
    },
    overclaim:{ title:"The Inquiry That Cried Hacker",
      body:["Foss reports a malicious hack — the machine seized by an outside attacker — the answer the headlines were already broadcasting. It is vivid, and it is not what the evidence shows.",
        "There was no intrusion, no attacker, no breach in the logs — only software delivering a lethal fault under a rare timing, with the one physical safeguard that would have stopped it deliberately removed. When the overclaim collapses, it takes credibility with it, and the real, provable defect is dismissed as just another conspiracy theory. The only intruder was a race condition the maker already knew about."] },
    dismissal:{ title:"Case Closed on the Technician",
      body:["Foss files it as simple operator error — a technician typed too fast, nothing systemic, close the file. It is half true and misses the graver half.",
        "The technician triggered a fault the software should never have allowed, on a machine whose hardware interlock had been quietly removed and whose defect the maker had already seen. Blaming the last hand on the keys leaves the flaw in every other machine still treating patients, waiting for the next fast edit. The inquiry saw the keystroke and never the corner cut into the design."] },
    wrongNames:{ title:"So Close",
      body:["Foss has the nature of it cold — a concealed software defect, a race condition made lethal by a removed interlock, neither a hack nor a careless technician. But the finger lands on the wrong name or the wrong room."] } },
}};