// STARTER — fill every "" and [] with authored prose per SPEC.md. Structure is fixed; do not change ids.
module.exports = { PACK: {
  id:"chemplant", title:"The Ardsley Works", discipline:"Chemical & Process Engineering",
  teaser:"A gas cloud rolled out of a chemical plant at midnight. A saboteur, bad luck — or safety systems switched off to save money?", overclaimTag:"sabotage", truthTag:"disabled safety systems, to cut costs",
  venue:"the Ardsley Works inquiry", agent:{name:"Inspector Grace Mbeki", role:"Investigator's Notepad"},
  standingLabel:"Safety credibility", readingShort:"Pioneers", readingLabel:"Chemical Pioneers",
  dossierName:"CHEMICAL PIONEERS", enterLabel:"Open the inquiry", subt:"A deduction game inside the Ardsley Works disaster inquiry", DAYS_TOTAL:8,
  boardNarr:"You have ${days} before your inquiry ends. A hop costs a day or two; each stop is one appointment. All three informants move throughout — travel to a location and choose whom to meet.",
  placeNarr:"You have arrived. Choose one informant to keep an appointment with. A dossier from the Bureau will reach you on the way in.",
  overclaimTease:"And beware the answer the front pages crave: the trail leads not to an intruder in the night, but to something quieter — and far harder to forgive.",
  CATS:{
    who:{ title:"Who is behind it", truth:"manager", items:[
      {id:"manager", label:"Voss — plant manager"},
      {id:"operator", label:"The night-shift operator"},
      {id:"contractor", label:"The maintenance contractor"} ]},
    where:{ title:"Where it culminates", truth:"office", items:[
      {id:"tank", label:"The Storage Tank & Reactor"},
      {id:"controlroom", label:"The Plant Control Room"},
      {id:"office", label:"The Plant Manager's Office"} ]},
    what:{ title:"What is happening", truth:"disabled", items:[
      {id:"sabotage", label:"Deliberate sabotage by an intruder"},
      {id:"freak", label:"An unforeseeable freak accident"},
      {id:"disabled", label:"Safety systems disabled to cut costs"} ]}
  },
  PLACES:{
    tank:{name:"The Storage Tank & Reactor", xy:[140,90]},
    controlroom:{name:"The Plant Control Room", xy:[330,240]},
    office:{name:"The Plant Manager's Office", xy:[520,90]}
  },
  EDGES:[["tank","controlroom"],["controlroom","office"]],
  CHARACTERS:{
    operator:{ name:"Operator Sahni", role:"Night-shift operator", face:"🎛", badge:"O", legend:"the control room", hint:"Watched the pressure climb with the scrubber offline and the flare cold." },
    safety:{ name:"The Safety Officer", role:"Process-safety officer", face:"🧯", badge:"S", legend:"the plant", hint:"Filed reports warning the interlocks were bypassed; they were shelved." },
    driver:{ name:"Tanker Driver Vale", role:"Chemical tanker driver", face:"🛢", badge:"D", legend:"the yard", hint:"Knows what was stored, how much, and that the refrigeration was off." }
  },
  TOPICMAP:{
    tank:{ operator:["stoichiometry","thermo"], safety:["kinetics","equilibrium"], driver:["catalysis","runaway"] },
    controlroom:{ operator:["highpressure","unitops"], safety:["distillation","heattransfer"], driver:["dispersion","doseresponse"] },
    office:{ operator:["inherentsafety","riskdrift"], safety:["nearmiss","corrosion"], driver:["ammonia","processcontrol"] }
  },
  TOPICS:{
    // cell: Operator Sahni @ The Storage Tank & Reactor
    stoichiometry:{ sci:"Antoine Lavoisier (1743-1794)", topic:"Conservation of mass & stoichiometry", lede:"The tax-farmer chemist who weighed the world before and after every reaction and proved that matter is never truly lost.", no:1,
      profile:"Antoine Lavoisier is called the father of modern chemistry, and his central tool was the balance. Working in Paris in the 1770s and 1780s, often with his wife and collaborator Marie-Anne Paulze, he weighed reactants and products with obsessive care in sealed vessels, and showed that the total mass never changed. When a metal rusted and gained weight, the surrounding air lost exactly that much; nothing was created or destroyed. From this he demolished the reigning 'phlogiston' theory, identified and named oxygen and hydrogen, and explained combustion as a combination with oxygen rather than the loss of a mysterious fire-substance.\n\nHis 1789 Elementary Treatise on Chemistry laid out a new quantitative language: reactions could be written as balanced accounts in which every atom is tracked. This is the root of stoichiometry — the arithmetic of how much reacts with how much, and how much must result. A chemical engineer lives inside that arithmetic, because a plant is a giant ledger of mass in and mass out. Lavoisier's own life ended under the guillotine in 1794, a victim of the Terror, but his bookkeeping outlived the politics that killed him.\n\nFor this board, conservation of mass is the first discipline. A known mass of a reactive chemical sat in that tank, and a known contaminant reached it; the gas that rolled over the town did not appear from nowhere, and it can be weighed backward to its source. Mass balance turns a 'freak' cloud into an accountable event and denies the saboteur his mystery. If the inputs were on the inventory sheet all along, then what happened was foreseeable arithmetic, not sorcery — and the real question becomes who let those inputs meet.",
      frame:"Sahni's hands are steady on the log. \"I recorded every gauge that night, to the minute. The mass doesn't lie, even when people do. Balance a reaction for me before I show you my sheet.\"",
      q:[
        { q:"What did Lavoisier's law of conservation of mass establish?", o:[
          { t:"In a closed reaction the total mass stays the same, whatever new substances form.", v:"expert", fb:"Mass is conserved; atoms only rearrange, they are never lost or gained." },
          { t:"A little mass is quietly consumed each time a reaction runs to completion.", v:"wrong", fb:"No mass vanishes; Lavoisier proved the totals always match exactly." },
          { t:"Mass turns freely into heat in ordinary chemistry, so the books never balance.", v:"wrong", fb:"Ordinary reactions conserve mass; the heat carries no measurable weight." },
          { t:"The count of molecules is fixed, though their combined mass may drift over time.", v:"partial", fb:"Molecule counts can change; it is the total mass that stays constant." } ] },
        { q:"What is stoichiometry, in Lavoisier's tradition?", o:[
          { t:"The arithmetic of what reacts with what, and how much product results.", v:"expert", fb:"Stoichiometry is the quantitative bookkeeping of a balanced reaction." },
          { t:"The study of how fast a reaction goes once its ingredients are combined.", v:"wrong", fb:"That is kinetics; stoichiometry is about amounts, not rates." },
          { t:"A rule that reactions always yield equal masses of every product formed.", v:"wrong", fb:"Products differ in mass; only the grand total is conserved." },
          { t:"The measure of how much heat a given reaction will release when it runs.", v:"partial", fb:"That is thermochemistry; stoichiometry counts the matter, not the heat." } ] },
        { q:"Why does mass balance matter to reading this disaster?", o:[
          { t:"A known chemical met a known contaminant, so the cloud traces back.", v:"expert", fb:"Accountable inputs make the release traceable, not a mystery." },
          { t:"It proves the gas was smuggled in, since clouds this large cannot form on site.", v:"danger", fb:"The mass was already on the inventory; no intruder was needed to supply it." },
          { t:"It shows the event was pure chance, since mass can appear without any source.", v:"danger", fb:"Mass never appears from nowhere; the source was on the books." },
          { t:"It lets the board weigh the wreckage and stop there, ignoring what was stored.", v:"partial", fb:"Weighing helps, but the stored inventory is the point of the balance." } ] }
      ] },
    // cell: Operator Sahni @ The Storage Tank & Reactor
    thermo:{ sci:"J. Willard Gibbs (1839-1903)", topic:"Chemical thermodynamics", lede:"The quiet Yale professor who wrote the rulebook of energy and equilibrium that industry took decades to even read.", no:2,
      profile:"Josiah Willard Gibbs was an American mathematical physicist who spent almost his entire life at Yale, publishing in an obscure Connecticut journal work that would reshape physical chemistry. Between 1876 and 1878 his monograph 'On the Equilibrium of Heterogeneous Substances' introduced the concepts of free energy, chemical potential, and the phase rule, giving chemists a rigorous way to predict whether a reaction will proceed and in which direction. Where others measured, Gibbs derived: from the laws of thermodynamics he built a framework that said which changes are possible at all.\n\nThe heart of it is what we now call the Gibbs free energy. A reaction runs spontaneously when it lowers the system's free energy, combining its tendency to release heat with its tendency toward disorder. If the free-energy change is negative, the reaction is thermodynamically favorable and will proceed once given the chance; many such reactions are strongly exothermic, dumping heat into their surroundings. Gibbs's chemical potential explained why substances move, mix, and react, and his phase rule governs how liquids, vapors, and solids coexist — the daily bread of any plant handling volatile chemicals.\n\nFor this board, thermodynamics separates the possible from the impossible. The reaction that filled that tank was not a bizarre one-off; it was thermodynamically downhill and heavily exothermic, meaning that once a contaminant reached the stored chemical, heat release was not bad luck but chemistry doing exactly what Gibbs's equations predict. The 'freak accident' story imagines an event no one could foresee. Gibbs answers that the energy release was written into the substances themselves — knowable in advance — so the surprise was never the chemistry, but that the safeguards meant to absorb it were gone.",
      frame:"Sahni watches the cold tank. \"People act like the heat came out of nowhere. It was always in there, waiting. Tell me what makes a reaction want to run, and I'll believe you read the gauges right.\"",
      q:[
        { q:"When does a reaction proceed spontaneously, in Gibbs's terms?", o:[
          { t:"When it lowers free energy, balancing heat release against disorder.", v:"expert", fb:"A negative free-energy change is Gibbs's criterion for a spontaneous reaction." },
          { t:"Whenever the reactants are simply placed together in the very same vessel.", v:"wrong", fb:"Contact is not enough; the free-energy change must be favorable." },
          { t:"Only when the mixture is actively heated from outside past its boiling point.", v:"wrong", fb:"Many spontaneous reactions release heat rather than requiring it." },
          { t:"When the products weigh less than the reactants that first went into it.", v:"partial", fb:"Mass is conserved; it is free energy, not weight, that must fall." } ] },
        { q:"What is an exothermic reaction?", o:[
          { t:"One that releases heat to its surroundings as it forms products.", v:"expert", fb:"Exothermic reactions dump energy outward, warming everything nearby." },
          { t:"One that quietly absorbs heat, cooling the vessel as it slowly proceeds.", v:"wrong", fb:"That is endothermic; exothermic reactions give heat out." },
          { t:"One that neither takes in nor gives out any energy at all as it runs.", v:"wrong", fb:"That describes no real reaction; energy always changes hands." },
          { t:"One that only releases heat once an outside spark is applied to start it.", v:"partial", fb:"A trigger may start it, but the heat comes from the reaction itself." } ] },
        { q:"How does thermodynamics undercut the 'freak accident' story?", o:[
          { t:"The heat release was thermodynamically downhill, and so foreseeable.", v:"expert", fb:"Gibbs's math made the energy release predictable in advance." },
          { t:"It shows the reaction was impossible, so an intruder must have forced it by hand.", v:"danger", fb:"The reaction was favorable and needed no intruder to occur." },
          { t:"It confirms the event was unrepeatable and could never have been anticipated.", v:"danger", fb:"Thermodynamics made it entirely anticipatable, the opposite of a freak." },
          { t:"It proves the tank was safe, since favorable reactions are always gentle ones.", v:"partial", fb:"Favorable does not mean gentle; strongly exothermic reactions are violent." } ] }
      ] },
    // cell: The Safety Officer @ The Storage Tank & Reactor
    kinetics:{ sci:"Svante Arrhenius (1859-1927)", topic:"Reaction rate & activation energy", lede:"The Swede whose thesis nearly failed him, then won a Nobel — and whose equation explains why a warm tank is a fast tank.", no:3,
      profile:"Svante Arrhenius was a Swedish physical chemist whose doctoral thesis on the dissociation of electrolytes earned a barely-passing grade in 1884 and, twenty years later, the 1903 Nobel Prize in Chemistry. Among his lasting gifts is the Arrhenius equation of 1889, which describes how reaction rate depends on temperature. It captures a simple, ferocious idea: molecules must clear an energy barrier — the activation energy — before they can react, and the fraction with enough energy to do so climbs steeply as temperature rises. As a rule of thumb, many reactions roughly double in rate for every ten-degree rise.\n\nActivation energy is the hill reactants must climb to reach products, and temperature is what gives molecules the speed to climb it. This is why a reaction that crawls in the cold can race when warmed, and why the two feed on each other in a heated vessel: a faster reaction releases heat faster, which raises the temperature, which speeds the reaction further. Arrhenius, remarkably, also first estimated how carbon dioxide warms the planet — another case of a small change in conditions producing an outsized effect.\n\nFor this board, kinetics is the reason refrigeration is a safety system, not a convenience. A reactive chemical kept cold reacts slowly enough to be controlled; let its temperature climb, and Arrhenius's exponential takes over, driving the rate up and up until control is lost. The refrigeration that was switched off at Ardsley was the brake on that exponential. Understanding activation energy tells the board that the disaster's speed was not an unforeseeable surprise but the predictable consequence of removing the one control that kept the reaction cold and slow.",
      frame:"The Safety Officer taps a temperature chart, cold and level. \"I warned them what happens when this line climbs. It is not linear. Show me you understand why heat feeds a reaction, and you will understand my reports.\"",
      q:[
        { q:"What is activation energy?", o:[
          { t:"The energy barrier reactants must clear before they can turn into products.", v:"expert", fb:"Activation energy is the hill molecules climb for a reaction to occur." },
          { t:"The total heat a reaction gives off once it has finally gone to completion.", v:"wrong", fb:"That is the heat of reaction; activation energy is the barrier to start." },
          { t:"The energy stored permanently in the products after the reaction is over.", v:"wrong", fb:"Activation energy is spent reaching the transition, not stored after." },
          { t:"The minimum amount of reactant needed before any reaction can begin at all.", v:"partial", fb:"That is a quantity of matter, not the energy barrier Arrhenius described." } ] },
        { q:"How does temperature affect reaction rate?", o:[
          { t:"Rate climbs steeply with temperature, often roughly doubling per ten degrees.", v:"expert", fb:"More molecules clear the barrier as it warms, so the rate soars." },
          { t:"Rate falls as things heat up, because hot molecules collide too gently to react.", v:"wrong", fb:"Hotter molecules collide harder and more often, speeding the reaction." },
          { t:"Rate is fixed by the chemicals alone and does not respond to temperature.", v:"wrong", fb:"The Arrhenius equation makes rate strongly temperature-dependent." },
          { t:"Rate rises in a gentle straight line, adding a little for each degree of heat.", v:"partial", fb:"The rise is exponential, not linear, which makes runaway so sudden." } ] },
        { q:"Why does kinetics make refrigeration a safety system?", o:[
          { t:"Cold keeps a reactive chemical slow; losing cooling lets the rate run away.", v:"expert", fb:"Refrigeration is the brake on the Arrhenius exponential." },
          { t:"Cooling only saves money on power, so switching it off changed nothing chemical.", v:"danger", fb:"Cooling holds the rate down; losing it is a direct safety failure." },
          { t:"The temperature could never have climbed on its own without an intruder's help.", v:"danger", fb:"An exothermic reaction heats itself; no saboteur is required." },
          { t:"Refrigeration matters only for storage life, never for the speed of a reaction.", v:"partial", fb:"It also throttles reaction rate, which is the safety-critical role here." } ] }
      ] },
    // cell: The Safety Officer @ The Storage Tank & Reactor
    equilibrium:{ sci:"Henry Le Chatelier (1850-1936)", topic:"Chemical equilibrium", lede:"The French engineer who found the single principle that tells you which way a squeezed, heated, crowded reaction will jump.", no:4,
      profile:"Henri Louis Le Chatelier was a French chemist and engineer whose name is attached to one of the most useful principles in all of chemistry. Trained at the École Polytechnique and drawn to the practical problems of mines, cements, metals, and flames, he framed in 1884 the principle that bears his name: when a system at equilibrium is disturbed — by a change in temperature, pressure, or concentration — it shifts in the direction that partly counteracts the disturbance. Squeeze a gas equilibrium and it moves to reduce the number of gas molecules; heat it and it moves to absorb the heat.\n\nEquilibrium is the balance point where forward and reverse reactions run at equal rates, so the mixture appears steady. Le Chatelier's insight let engineers steer that balance deliberately: raise the pressure to favor a product, lower the temperature to shift a yield. It was exactly this reasoning that later guided industrial synthesis of ammonia and countless other processes. He also worked on thermocouples and high-temperature measurement, and studied the oxy-acetylene flame — always an engineer, chasing chemistry that had to work in a real furnace.\n\nFor this board, equilibrium explains the pressure the operators watched climb. A volatile chemical sits in equilibrium with its own vapor; warm it, and Le Chatelier's principle drives more of it into the gas phase, and the pressure in the tank rises. Refrigeration holds that equilibrium down, keeping the vapor pressure low and the tank quiet. Once the reaction heated the contents, the equilibrium shifted hard toward vapor, and the pressure that burst the relief was the system obeying a law known for a century — not an unforeseeable freak, but a shift the safeguards existed precisely to prevent.",
      frame:"The Safety Officer folds their arms. \"Everything in that tank was a balance, and balances can be pushed. Tell me which way heat and pressure push them, and I will trust you with what I filed.\"",
      q:[
        { q:"What does Le Chatelier's principle state?", o:[
          { t:"A disturbed equilibrium shifts to partly oppose the change imposed.", v:"expert", fb:"The system moves to counteract added heat, pressure, or concentration." },
          { t:"An equilibrium, once reached, can never be shifted by any outside change at all.", v:"wrong", fb:"Equilibria shift readily; that shifting is the whole principle." },
          { t:"Reactions always run fully forward and never settle at a balance point.", v:"wrong", fb:"Equilibrium is precisely a settled balance of forward and reverse." },
          { t:"Adding a reactant always speeds a reaction up without moving its balance.", v:"partial", fb:"Adding reactant shifts the equilibrium toward products, not just speed." } ] },
        { q:"How does warming a volatile liquid affect its vapor pressure?", o:[
          { t:"Vapor pressure rises as heat drives more of the liquid into the gas phase.", v:"expert", fb:"Higher temperature shifts the balance toward vapor, raising pressure." },
          { t:"Vapor pressure falls, because warm liquid holds its molecules more tightly.", v:"wrong", fb:"Warming loosens molecules into vapor, so pressure rises, not falls." },
          { t:"Vapor pressure stays fixed, set only by the liquid's chemical identity.", v:"wrong", fb:"Vapor pressure depends strongly on temperature, not identity alone." },
          { t:"Vapor pressure changes only if the container's volume is changed as well.", v:"partial", fb:"Temperature alone raises vapor pressure, regardless of the volume." } ] },
        { q:"How does equilibrium explain the rising tank pressure?", o:[
          { t:"Heat shifted the balance toward vapor, so the pressure climbed by a known law.", v:"expert", fb:"The pressure rise was Le Chatelier's principle in plain action." },
          { t:"The pressure could only have been raised by someone pumping gas in deliberately.", v:"danger", fb:"Warming alone raises the pressure; no intruder had to pump anything." },
          { t:"Such a pressure rise is unpredictable, a one-in-a-million fluke of the vapor.", v:"danger", fb:"It follows a century-old law and is entirely predictable." },
          { t:"Pressure rose purely because the tank was overfilled, not because of any heat.", v:"partial", fb:"Fill level matters, but the heat-driven vapor shift is the key mechanism." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Storage Tank & Reactor
    catalysis:{ sci:"Paul Sabatier (1854-1941)", topic:"Catalysis", lede:"The chemist who turned cheap nickel into a magic wand for hydrogen, and showed the best catalyst holds on just tightly enough.", no:5,
      profile:"Paul Sabatier was a French chemist who shared the 1912 Nobel Prize for discovering that finely divided metals, especially nickel, could catalyze the addition of hydrogen to organic compounds. Working at Toulouse, he found that passing an unsaturated vapor over hot nickel would hydrogenate it cleanly — a method that transformed the food, fuel, and chemical industries and still underlies the hardening of oils and much of modern synthesis. A catalyst, he showed, speeds a reaction by offering an easier path, lowering the activation energy, while emerging unchanged itself.\n\nSabatier also articulated a principle that still guides catalyst design: the best catalyst binds the reacting species neither too weakly nor too strongly. Bind too weakly and nothing sticks to react; bind too strongly and the products never let go. This 'just right' optimum — later drawn as a volcano-shaped curve — captures why a particular metal, at a particular condition, can dramatically accelerate a reaction that would otherwise barely proceed. A pinch of the right material changes everything, though it never appears in the final tally of products.\n\nFor this board, catalysis is the hidden accelerant. The very metals a plant is built from — iron and its rust, traces shed by corroding pipes and walls — can catalyze the reactions of the chemicals they contain, speeding a slow decomposition into a fast one. This is not exotic sabotage; it is ordinary industrial chemistry, and it is exactly why contamination and corrosion products are treated as hazards, not curiosities. When a reaction ran far faster than the clean chemistry alone predicts, Sabatier's lesson tells the board to look for a catalyst that should never have been allowed into the tank.",
      frame:"Vale leans on the tanker. \"A speck of the wrong metal and the whole load turns on you. I've hauled enough to know. Show me you understand a catalyst, and I'll tell you what was in that tank.\"",
      q:[
        { q:"What does a catalyst do to a reaction?", o:[
          { t:"It speeds the reaction by lowering activation energy, and is not used up.", v:"expert", fb:"A catalyst offers an easier path and emerges unchanged." },
          { t:"It is used up steadily as it drives the reaction toward its products.", v:"wrong", fb:"A true catalyst is regenerated, not consumed, as it works." },
          { t:"It raises how much product forms by shifting the final equilibrium point.", v:"wrong", fb:"A catalyst speeds arrival at equilibrium but does not move it." },
          { t:"It slows a runaway reaction down by soaking up the heat that it releases.", v:"partial", fb:"Catalysts change rate, not heat capacity, and typically speed things up." } ] },
        { q:"What is Sabatier's principle of 'just right' binding?", o:[
          { t:"The best catalyst binds the reactants neither too weakly nor too strongly.", v:"expert", fb:"An intermediate binding strength gives the fastest catalytic turnover." },
          { t:"The strongest possible binding always yields the most effective catalyst.", v:"wrong", fb:"Bind too strongly and the products never release; strength is not all." },
          { t:"The catalyst should never touch the reactants, only warm them from nearby.", v:"wrong", fb:"Catalysis requires the reactants to bind to the catalyst surface." },
          { t:"Any metal works equally, so the choice of catalyst hardly matters at all.", v:"partial", fb:"The right metal at the right condition matters enormously." } ] },
        { q:"How might catalysis have driven this reaction faster?", o:[
          { t:"Metal shed by corroding pipes can catalyze the load, speeding a slow decay.", v:"expert", fb:"Corrosion products are a known, ordinary catalytic hazard." },
          { t:"Only a planted catalyst smuggled in could make the reaction move this fast.", v:"danger", fb:"The plant's own corroded metal supplies the catalyst; no smuggling needed." },
          { t:"Such acceleration is a total fluke that no chemist could ever have foreseen.", v:"danger", fb:"Catalysis by contaminants is well known and entirely foreseeable." },
          { t:"The reaction sped up only because the tank was simply filled too full.", v:"partial", fb:"Overfilling matters, but a catalyst changes the rate itself." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Storage Tank & Reactor
    runaway:{ sci:"Nikolay Semyonov (1896-1986)", topic:"Chain reactions & thermal runaway", lede:"The Soviet physicist who explained why a reaction can suddenly turn into an explosion, and won his country its first science Nobel.", no:6,
      profile:"Nikolay Semyonov was a Soviet physical chemist who shared the 1956 Nobel Prize in Chemistry with Cyril Hinshelwood for the theory of chemical chain reactions — the first Nobel awarded to a Soviet scientist. Studying combustion and oxidation in the 1920s and 1930s, Semyonov explained how some reactions proceed through chains in which each step produces reactive species that trigger further steps. In branched chains, one active particle can spawn several, and the reaction multiplies explosively — the basis of a chemical explosion.\n\nSemyonov also developed the theory of thermal explosion, which is the heart of what process engineers call thermal runaway. The idea is a race between two rates: the rate at which a reaction generates heat and the rate at which that heat can be carried away. Heat generation rises exponentially with temperature, following Arrhenius; heat removal by cooling rises only gently. If generation ever outpaces removal, the temperature climbs, which speeds the reaction, which generates still more heat — a self-accelerating spiral that ends in a violent release. Below a critical point the system is stable; cross it, and runaway is nearly unstoppable.\n\nFor this board, thermal runaway is the mechanism of the whole disaster, and Semyonov drew its map. A reactive chemical, a source of heat from an unwanted reaction, and cooling that could not keep pace: that is the runaway triangle. The refrigeration and cooling systems exist precisely to keep heat removal ahead of heat generation. Disable them, and an ordinary upset that should have been absorbed instead tips across the critical point into runaway. The 'freak accident' story ignores that this outcome is textbook and predictable once the heat-removal side of Semyonov's balance is deliberately taken away.",
      frame:"Vale's voice is flat. \"I've seen a load cook itself. Once it starts you don't stop it. Explain to me how a reaction runs away, and I'll tell you why this one had nothing to stop it.\"",
      q:[
        { q:"What is thermal runaway?", o:[
          { t:"A self-accelerating spiral where heat generation outpaces heat removal.", v:"expert", fb:"When generation beats removal, temperature and rate feed each other." },
          { t:"A reaction that suddenly stops cold once the vessel reaches a high temperature.", v:"wrong", fb:"Runaway accelerates with heat; it does not stop itself." },
          { t:"A steady, gentle warming that always levels off on its own before any danger.", v:"wrong", fb:"Past the critical point it does not level off; it spirals upward." },
          { t:"A reaction that runs fast only while an external heater is left switched on.", v:"partial", fb:"Runaway is self-heating; it needs no external heater to continue." } ] },
        { q:"What did Semyonov's branched chain reactions explain?", o:[
          { t:"How one active particle spawns several, multiplying the reaction fast.", v:"expert", fb:"Branching multiplies active species, driving a chemical explosion." },
          { t:"How catalysts are slowly consumed as a long reaction chain proceeds.", v:"wrong", fb:"That concerns catalysts; branching is about multiplying active species." },
          { t:"How reactions reach a calm equilibrium and then hold perfectly steady.", v:"wrong", fb:"Branched chains do the opposite, accelerating away from balance." },
          { t:"How a reaction needs a fresh spark applied for each and every step.", v:"partial", fb:"In a chain, each step generates the trigger for the next itself." } ] },
        { q:"Why does disabling cooling invite runaway?", o:[
          { t:"Cooling is the heat-removal side; remove it and generation wins.", v:"expert", fb:"Without heat removal, Semyonov's race tips straight into runaway." },
          { t:"Cooling is decorative, so switching it off could not have mattered chemically.", v:"danger", fb:"Cooling is the very safeguard against runaway; losing it is decisive." },
          { t:"Runaway needs an intruder to inject heat, since reactions never self-heat.", v:"danger", fb:"Exothermic reactions self-heat; an intruder is not required." },
          { t:"Cooling only protects the pumps, not the reaction inside the vessel itself.", v:"partial", fb:"Cooling directly limits the reaction's temperature, which is the point." } ] }
      ] },
    // cell: Operator Sahni @ The Plant Control Room
    highpressure:{ sci:"Carl Bosch (1874-1940)", topic:"High-pressure vessels & relief", lede:"The engineer who tamed reactions at hundreds of atmospheres and learned, the hard way, how to keep a vessel from bursting.", no:7,
      profile:"Carl Bosch was a German chemist and engineer who took Fritz Haber's laboratory synthesis of ammonia and turned it into an industry, work that won him the 1931 Nobel Prize in Chemistry. The challenge was pressure: the reaction demanded hundreds of atmospheres and high temperature, conditions that destroyed ordinary steel vessels through hydrogen attack, which weakened the metal from within. Bosch and his team at BASF invented reactors with a soft inner liner and a perforated outer shell that let hydrogen escape safely, and pioneered the metallurgy and mechanical design of vessels that could contain enormous pressures for years without failing.\n\nBosch's world taught the discipline of the pressure envelope. A vessel has a maximum it can safely hold, and every high-pressure system must therefore include a way to relieve pressure before it reaches that limit — a relief valve or rupture disk that opens to vent the contents to a safe place rather than let the vessel explode. The vented material is then routed to be neutralized or burned, never simply dumped. Bosch's plants ran because their designers respected that the container is only as safe as its weakest relief path.\n\nFor this board, the relief train is the safeguard that failed. A tank whose pressure climbs will reach its relief device, which is meant to open and send the escaping gas onward to a scrubber and a flare that render it harmless. If those downstream systems were offline, the relief valve did its job and simply delivered raw toxic gas straight to the atmosphere. Bosch's engineering shows the board that a relief valve lifting is not itself the disaster; the disaster is that what it vented had nowhere safe to go, because the systems meant to catch it were shut down.",
      frame:"Sahni gestures at the panel. \"When the pressure hit the relief, it lifted, exactly as designed. The horror is what it lifted into. Show me you know how relief is supposed to work.\"",
      q:[
        { q:"Why does a high-pressure vessel need a relief device?", o:[
          { t:"To vent contents before pressure exceeds what the vessel can hold.", v:"expert", fb:"Relief opens below the limit so the vessel never bursts." },
          { t:"To let the operator top the vessel up with more product during a run.", v:"wrong", fb:"Relief is for venting excess pressure, not for adding material." },
          { t:"To keep the vessel warm by trapping the heat that the reaction gives off.", v:"wrong", fb:"Relief releases pressure; it does not manage the vessel's heat." },
          { t:"To hold the pressure as high as possible for the best reaction yield.", v:"partial", fb:"Yield aside, the relief's job is safety, capping pressure, not raising it." } ] },
        { q:"What problem did Bosch solve in high-pressure reactors?", o:[
          { t:"Hydrogen weakening steel, which he beat with a lined, vented shell.", v:"expert", fb:"His liner-and-vent design let vessels survive years at high pressure." },
          { t:"Reactors freezing solid, which he fixed by wrapping them in heavy insulation.", v:"wrong", fb:"His challenge was hydrogen embrittlement, not freezing." },
          { t:"Catalysts wearing out, which he cured by switching to a cheaper metal.", v:"wrong", fb:"His breakthrough was vessel metallurgy, not catalyst replacement." },
          { t:"Reactions running too slowly, which he solved by simply raising the heat.", v:"partial", fb:"Heat helped the reaction, but his fame is containing the pressure safely." } ] },
        { q:"What does it mean if a relief valve vented straight to the air?", o:[
          { t:"The valve worked, but its scrubber and flare weren't there to catch it.", v:"expert", fb:"Relief lifting is normal; venting raw gas means the catch systems failed." },
          { t:"The valve must have been sabotaged to open, since relief valves never lift.", v:"danger", fb:"Relief valves are designed to lift; the failure was downstream, not sabotage." },
          { t:"A freak overpressure no design could handle simply overwhelmed everything.", v:"danger", fb:"The relief path was designed for exactly this; the catch systems were absent." },
          { t:"The vessel itself had ruptured, which is the only way gas ever reaches the air.", v:"partial", fb:"An intact vessel can vent through relief; rupture is not required." } ] }
      ] },
    // cell: Operator Sahni @ The Plant Control Room
    unitops:{ sci:"Warren K. Lewis (1882-1975)", topic:"Unit operations & mass balance", lede:"The MIT professor who cut chemical manufacturing into a handful of repeatable steps and made engineers of chemists.", no:8,
      profile:"Warren K. Lewis is often called the father of chemical engineering as a distinct discipline. Teaching at MIT for decades, he helped establish, with Arthur D. Little, the concept of 'unit operations': the idea that any chemical process, however complex, can be broken into a limited set of basic physical steps — distillation, absorption, heat exchange, filtration, mixing, and the like — each governed by principles that transfer from one industry to another. This reframing turned chemical manufacturing from a collection of trade secrets into an engineering science that could be taught, calculated, and designed.\n\nLewis co-wrote the foundational textbook 'Principles of Chemical Engineering' in 1923, advanced the theory of distillation and absorption, and later contributed to fluid catalytic cracking, which reshaped petroleum refining. Central to his method is the mass balance: track every stream of matter into and out of each unit, and account for all of it, because by Lavoisier's law it must add up. A discrepancy in the balance is a signal — a leak, an unexpected reaction, or an input that should not be there. The mass balance is the engineer's audit of a running plant.\n\nFor this board, unit operations and mass balance give the investigator a map and a ledger. The plant is a chain of units — storage, reaction, scrubbing, flaring — each with streams that should sum. Following the mass through those units reveals where a contaminant entered a tank it should never have reached, and which safeguarding unit was bypassed. When the balance does not close, something is unaccounted for, and Lewis's discipline says to find it rather than shrug. The plant was designed to be auditable; the disaster becomes legible the moment the board treats it as one.",
      frame:"Sahni points along the flow diagram. \"Every stream on this board should add up, in and out. When it doesn't, that's your clue. Prove you can balance a plant, and I'll walk you through the night.\"",
      q:[
        { q:"What is a 'unit operation'?", o:[
          { t:"A basic physical step, like distillation, common to many processes.", v:"expert", fb:"Unit operations are the shared building blocks of chemical plants." },
          { t:"A single chemical reaction that turns one specific reactant into one product.", v:"wrong", fb:"Unit operations are physical steps, not one particular reaction." },
          { t:"The whole factory taken as one indivisible operation that cannot be split.", v:"wrong", fb:"The idea is precisely to split a process into repeatable steps." },
          { t:"A safety procedure the operators follow when a single unit is shut down.", v:"partial", fb:"That is an operating step, not the design concept Lewis defined." } ] },
        { q:"What is a mass balance on a process unit?", o:[
          { t:"All matter entering a unit must equal what leaves or builds up inside.", v:"expert", fb:"Every stream must sum, because mass is conserved." },
          { t:"A measure of how much a unit weighs when it is fully loaded with product.", v:"wrong", fb:"A mass balance tracks flowing streams, not the unit's own weight." },
          { t:"A check that the reaction inside a unit is releasing the right amount of heat.", v:"wrong", fb:"That is an energy balance; a mass balance tracks matter." },
          { t:"A rule that every unit must output exactly the mass of product it was sold.", v:"partial", fb:"Outputs include waste and byproducts too, not just saleable product." } ] },
        { q:"How does a mass balance help this investigation?", o:[
          { t:"A balance that fails to close flags a contaminant or a bypassed safeguard unit.", v:"expert", fb:"An unclosed balance points to where matter went astray." },
          { t:"It proves an intruder added material, since only sabotage unbalances a plant.", v:"danger", fb:"Leaks and stray inputs unbalance a plant far more often than intruders." },
          { t:"It shows the release was unaccountable, a fluke the ledger simply cannot explain.", v:"danger", fb:"The ledger is meant to account for everything; a gap is a clue, not a fluke." },
          { t:"It lets the board weigh the tanks and stop, without tracing the streams between.", v:"partial", fb:"The value is in tracing streams unit to unit, not weighing tanks alone." } ] }
      ] },
    // cell: The Safety Officer @ The Plant Control Room
    distillation:{ sci:"George E. Davis (1850-1907)", topic:"Separation & distillation", lede:"The British factory inspector who saw the same operations in every works he visited, and named a whole profession.", no:9,
      profile:"George E. Davis was a British chemical engineer and, before that, a government inspector under the Alkali Acts, charged with policing the emissions of chemical works. Traveling from factory to factory, he noticed that the same basic operations — distilling, evaporating, absorbing, filtering — recurred everywhere, regardless of the product, and he was among the first to teach chemistry as engineering. His 1887 lectures at the Manchester Technical School and his 1901 'A Handbook of Chemical Engineering' laid out the field, and many credit him, alongside American figures, as a founder of the discipline.\n\nDavis's world centered on separation, and the archetype is distillation: exploiting differences in volatility to split a mixture, boiling off the lighter components and condensing them apart from the heavier ones. The same physics of preferential transfer between phases governs absorption, in which a gas is scrubbed by contacting it with a liquid that selectively dissolves or reacts with the unwanted component. A scrubber is, in essence, a separation unit whose product is a clean gas stream and a captured contaminant — the very safeguard meant to catch a toxic release.\n\nFor this board, Davis matters twice. As an inspector, he embodies the idea that a chemical works owes the public around it a duty, enforced by someone whose job is to check the emissions — the ancestor of the very inquiry now underway. As a separations engineer, he explains what the plant's scrubber was for: to absorb escaping gas into a reactive liquid and render it harmless before it left the site. If that scrubber was drained, cold, or bypassed, the one unit designed to separate poison from air was simply not doing the job Davis's science says it should. The board should ask why the separation never happened.",
      frame:"The Safety Officer's tone sharpens. \"I came up watching inspectors check what a plant let out. The scrubber is a separator, nothing mystical. Tell me how it should work, and I'll tell you what it wasn't doing.\"",
      q:[
        { q:"What principle underlies distillation?", o:[
          { t:"Separating a mixture by volatility, boiling and condensing apart.", v:"expert", fb:"Distillation exploits how readily each component vaporizes." },
          { t:"Filtering a mixture through a fine mesh that traps the heavier molecules.", v:"wrong", fb:"That is filtration; distillation works by volatility, not sieving." },
          { t:"Freezing a mixture so the parts separate cleanly into distinct solid layers.", v:"wrong", fb:"That is crystallization; distillation relies on boiling differences." },
          { t:"Spinning a mixture so its denser components are flung to the outer wall.", v:"partial", fb:"That is centrifugation; distillation separates by volatility instead." } ] },
        { q:"How does a gas scrubber work?", o:[
          { t:"It contacts the gas with a liquid that selectively absorbs the unwanted part.", v:"expert", fb:"A scrubber dissolves or reacts away the hazard, cleaning the stream." },
          { t:"It burns the gas completely, leaving only water vapor behind to vent away.", v:"wrong", fb:"That describes a flare; a scrubber absorbs into a liquid instead." },
          { t:"It cools the gas until every component condenses back into a liquid at once.", v:"wrong", fb:"A scrubber selectively absorbs; it does not condense the whole stream." },
          { t:"It filters solid particles out of the gas but leaves the vapors untouched.", v:"partial", fb:"Scrubbers target vapors chemically, not just particulate matter." } ] },
        { q:"What if the scrubber was drained or bypassed during the release?", o:[
          { t:"The one unit meant to absorb the poison was not separating it from the air.", v:"expert", fb:"A dead scrubber lets the hazard pass straight through untreated." },
          { t:"It means an intruder must have poisoned the scrubbing liquid on purpose.", v:"danger", fb:"A drained or bypassed scrubber needs no intruder; it was simply offline." },
          { t:"Nothing changes, since scrubbers are optional polish, not real safety gear.", v:"danger", fb:"The scrubber is a primary safeguard; without it, poison reaches the public." },
          { t:"The gas was cleaned anyway, because scrubbing happens naturally in the pipe.", v:"partial", fb:"Absorption needs the scrubber's liquid contact; it does not just happen." } ] }
      ] },
    // cell: The Safety Officer @ The Plant Control Room
    heattransfer:{ sci:"Wilhelm Nusselt (1882-1957)", topic:"Heat transfer & cooling", lede:"The German engineer who turned the messy art of cooling into numbers, so an engineer could know if a chiller could keep up.", no:10,
      profile:"Wilhelm Nusselt was a German engineer who helped make heat transfer a quantitative science. In 1915 he set out the fundamental laws of convective heat transfer using dimensional analysis, showing how the many variables of a cooling or heating problem collapse into a few dimensionless groups. The most important of these now bears his name: the Nusselt number, which measures how much a flowing fluid enhances heat transfer over still conduction alone. His 1916 theory of film condensation likewise predicted, from first principles, how fast a condensing vapor gives up its heat.\n\nNusselt's work let engineers design heat exchangers, chillers, and cooling jackets with confidence, calculating whether a given surface, flow, and temperature difference could carry away a required amount of heat. This is the quantitative backbone of every cooling system in a plant. The rate of heat removal depends on the area available, the temperature difference driving it, and the vigor of the fluid flow — all captured in Nusselt's framework. Knowing these, an engineer can state plainly how much heat a cooling system can shed per second, and therefore whether it can keep a reactive vessel under control.\n\nFor this board, heat transfer is the other half of Semyonov's runaway balance made concrete. A cooling or refrigeration system removes heat at a calculable rate; a reaction generates heat at a rate that soars with temperature. Safety depends on removal staying ahead of generation. If the refrigeration was switched off, the removal rate dropped toward zero while generation kept climbing, and Nusselt's numbers would have told any engineer in advance that the cooling could no longer win. The board can compute what the cooling should have carried away — and show that its absence, not fate, let the heat build.",
      frame:"The Safety Officer sets down a heat-exchanger drawing. \"Cooling is not a hope, it is a number you can compute. Show me you understand how heat leaves a vessel, and I'll show you the number they ignored.\"",
      q:[
        { q:"What does the Nusselt number describe?", o:[
          { t:"How much a flowing fluid boosts heat transfer beyond conduction.", v:"expert", fb:"It captures convection's enhancement of heat transfer." },
          { t:"How much total heat a reaction will release once it finishes running.", v:"wrong", fb:"That is a heat of reaction; Nusselt concerns transfer, not release." },
          { t:"How fast a reaction's rate doubles for each ten degrees of warming.", v:"wrong", fb:"That is the Arrhenius rule; Nusselt is about heat transfer." },
          { t:"How much pressure a fluid exerts on the walls of the vessel it fills.", v:"partial", fb:"That is a pressure concern; the Nusselt number is about heat flow." } ] },
        { q:"What sets how fast a cooling system removes heat?", o:[
          { t:"The surface area, the temperature difference, and the flow's vigor.", v:"expert", fb:"Area, driving temperature, and flow together set the removal rate." },
          { t:"Only the total volume of coolant stored in the plant's holding tanks.", v:"wrong", fb:"Stored volume is not the rate; area, flow, and temperature govern it." },
          { t:"Only the chemical identity of the reacting substance inside the vessel.", v:"wrong", fb:"Heat removal depends on the exchanger, not the reactant's identity." },
          { t:"Only how new the cooling equipment is, since old units cannot transfer heat.", v:"partial", fb:"Condition matters, but the rate is set by area, temperature, and flow." } ] },
        { q:"Why does losing refrigeration decide a runaway?", o:[
          { t:"Heat removal drops toward zero while generation climbs, so removal can't win.", v:"expert", fb:"With cooling off, the runaway balance tips irreversibly." },
          { t:"It changes nothing, because a reaction can always shed its own heat unaided.", v:"danger", fb:"A vessel cannot shed runaway heat without a working cooling system." },
          { t:"Only a saboteur pumping in heat could ever overwhelm a plant's cooling.", v:"danger", fb:"An exothermic reaction overwhelms cooling on its own once it is off." },
          { t:"Refrigeration only affects storage quality, never the reaction's temperature.", v:"partial", fb:"Refrigeration directly limits vessel temperature, which is safety-critical." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Plant Control Room
    dispersion:{ sci:"Frank Pasquill (1914-1994)", topic:"Gas dispersion & the plume", lede:"The British meteorologist who sorted the sky into six moods and predicted how far a poison cloud would carry on each.", no:11,
      profile:"Frank Pasquill was a British meteorologist who developed the practical framework for predicting how gases and pollutants disperse in the atmosphere. In 1961 he introduced a classification of atmospheric stability — the Pasquill stability classes, labeled A through F, running from very unstable, turbulent daytime conditions to very stable, calm nighttime ones. Combined with the Gaussian plume model, these classes let engineers estimate how a release spreads: how wide the plume grows, how much it dilutes, and what concentration reaches a given distance downwind.\n\nThe crucial insight is that the same quantity of gas can be harmless or lethal depending on the weather. On a sunny, gusty afternoon (an unstable class), turbulence stirs a release upward and dilutes it fast. On a still, clear night with a temperature inversion (a stable class), the cloud stays low, narrow, and concentrated, hugging the ground and traveling far before it thins. Wind speed, time of day, and the vertical temperature profile decide the difference between a scare and a catastrophe. Pasquill turned that into numbers a planner could use.\n\nFor this board, dispersion explains why a midnight release was so deadly, and why that is not an excuse. A cloud let loose at night, under a stable inversion and light wind, behaved exactly as Pasquill's classes predict: it clung to the ground and rolled over the sleeping town at high concentration. This is not an unforeseeable freak of weather; nighttime stable conditions are ordinary and well understood, and any plant handling toxic gas must assume a release could occur under the worst dispersion, not the best. The severity was set by physics anyone could have modeled — which is precisely why the missing safeguards, not the weather, are on trial.",
      frame:"Vale looks toward the town. \"That cloud didn't rise and blow off. It laid down and crawled, on a still night, right where the people were. Tell me how a plume behaves, and you'll see it wasn't the weather's fault.\"",
      q:[
        { q:"What do Pasquill's stability classes describe?", o:[
          { t:"How turbulent or calm the air is, which sets how a release disperses.", v:"expert", fb:"The classes rank conditions from turbulent to stable for dispersion." },
          { t:"How toxic a given gas is to a person exposed for a fixed length of time.", v:"wrong", fb:"That is toxicity; the classes describe the atmosphere, not the gas." },
          { t:"How much gas a plant is legally permitted to release in a single day.", v:"wrong", fb:"They are meteorological categories, not emission permits." },
          { t:"How quickly a chemical reacts once it has been carried into open air.", v:"partial", fb:"They govern physical spreading, not the gas's chemical reactivity." } ] },
        { q:"Why is a still, clear night the worst case for a release?", o:[
          { t:"A stable inversion keeps the cloud low and concentrated as it drifts.", v:"expert", fb:"Stable air traps the plume near the ground at high concentration." },
          { t:"Warm turbulent night air lifts the cloud and dilutes it almost immediately.", v:"wrong", fb:"Nights are typically stable, not turbulent; the cloud stays low." },
          { t:"Rain at night always scrubs the cloud from the sky before it can travel.", v:"wrong", fb:"A clear stable night has no rain to scrub it; the plume persists." },
          { t:"Strong night winds tear the cloud apart faster than any daytime breeze.", v:"partial", fb:"Stable nights usually bring light winds, which concentrate the plume." } ] },
        { q:"What does dispersion imply about calling this a freak of weather?", o:[
          { t:"Nighttime stable air is ordinary, so the severe spread was foreseeable.", v:"expert", fb:"The worst-case dispersion is routine and should have been planned for." },
          { t:"The weather was so freakish that no plant could have prepared for the cloud.", v:"danger", fb:"Stable night air is common; assuming it is basic safety planning." },
          { t:"The concentration proves the gas was released by an intruder to maximize harm.", v:"danger", fb:"The physics of a night plume needs no intruder to explain its severity." },
          { t:"Dispersion is unpredictable, so the harm downwind could never be estimated.", v:"partial", fb:"Pasquill's models estimate it well; the outcome was quite predictable." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Plant Control Room
    doseresponse:{ sci:"Paracelsus (1493-1541)", topic:"Dose-response: the dose makes the poison", lede:"The wandering Renaissance physician who burned the old textbooks and declared that everything is poison in the wrong amount.", no:12,
      profile:"Paracelsus — born Theophrastus von Hohenheim in Switzerland — was a physician, alchemist, and relentless iconoclast of the early sixteenth century, often called the father of toxicology. Contemptuous of the ancient authorities, he reputedly burned their books and insisted that medicine be grounded in observation and chemistry. His most enduring line, paraphrased, is that 'the dose makes the poison': all substances are toxic at some dose and harmless below it, and it is the quantity, not merely the identity, that determines harm. A remedy in a small dose can be a poison in a large one.\n\nThat principle is the seed of the modern dose-response relationship, the backbone of toxicology and occupational health. For a given substance, the probability and severity of harm rise with the dose received, which for an inhaled gas depends on both its concentration and the duration of exposure. Toxicologists define thresholds — levels below which effects are not seen, and levels above which they become dangerous or lethal. Some substances are so potent that concentrations of only a few parts per million, breathed briefly, can injure or kill, which is exactly what makes certain industrial gases so hazardous.\n\nFor this board, dose-response translates the cloud into human terms and refuses two evasions. It refutes the dismissal that a little leaked gas is no great matter: for a highly toxic substance, even low concentrations over a short exposure can be deadly, so 'only a small release' is no comfort. And it refutes the overclaim that such lethality requires a deliberate poisoner: the substance is intrinsically potent at low doses, so an accidental release of the ordinary inventory, undiluted by the failed safeguards, is fully enough to explain the toll. The math of dose is grim, and entirely mundane.",
      frame:"Vale taps the placard on the tanker. \"People think a whiff of anything is harmless. Not this. A few parts per million and you're down. Tell me what makes a dose deadly, and you'll understand the count.\"",
      q:[
        { q:"What does 'the dose makes the poison' mean?", o:[
          { t:"Any substance can harm at a high enough dose and be harmless below a threshold.", v:"expert", fb:"Harm tracks the quantity received, not merely the substance's name." },
          { t:"Only substances labeled as poisons can ever cause harm, at any amount at all.", v:"wrong", fb:"Even benign substances harm at high dose; the amount is what matters." },
          { t:"Every substance is equally dangerous, so the specific dose makes no difference.", v:"wrong", fb:"The principle is exactly that dose, not identity alone, sets the danger." },
          { t:"A poison is only harmful if swallowed, never if it is breathed or touched.", v:"partial", fb:"Route matters, but the core idea is that dose governs the harm." } ] },
        { q:"For an inhaled gas, what determines the dose received?", o:[
          { t:"Both its concentration in the air and how long the person breathes it in.", v:"expert", fb:"Inhaled dose combines concentration with duration of exposure." },
          { t:"Only the total mass of gas released, regardless of where anyone was standing.", v:"wrong", fb:"Local concentration and exposure time, not the bulk released, set the dose." },
          { t:"Only the color or smell of the gas, which reveals how poisonous it truly is.", v:"wrong", fb:"Odor is an unreliable guide; dose depends on concentration and time." },
          { t:"Only the outdoor temperature, since heat alone decides how much harm results.", v:"partial", fb:"Temperature affects dispersion, but dose is concentration times duration." } ] },
        { q:"How does dose-response rebut the two easy stories?", o:[
          { t:"A potent gas kills at low doses, so no small leak or poisoner is needed.", v:"expert", fb:"Intrinsic potency explains the toll without minimizing or sabotage." },
          { t:"Only a deliberate poisoner could achieve a dose high enough to kill anyone.", v:"danger", fb:"The gas is lethal at low doses; an accidental release suffices." },
          { t:"A leak this small was surely harmless, so the deaths must have another cause.", v:"danger", fb:"For a potent gas, even a small release delivers a deadly dose." },
          { t:"Toxicity is unknowable, so the number of casualties can never be explained.", v:"partial", fb:"Dose-response makes the toll quite explainable from concentration and time." } ] }
      ] },
    // cell: Operator Sahni @ The Plant Manager's Office
    inherentsafety:{ sci:"Trevor Kletz (1922-2013)", topic:"Inherently safer design", lede:"The plant chemist who, after a fatal blast, spent his life arguing that what you don't have can't leak.", no:13,
      profile:"Trevor Kletz was a British chemical engineer at ICI who, after a fatal explosion at a plant in 1974, became the conscience of process safety. He is credited with founding the philosophy of inherently safer design and with helping develop and popularize HAZOP, the systematic hazard-and-operability study that walks a design team through every way a process can deviate and go wrong. Prolific and quotable, he distilled hard lessons into memorable slogans, the most famous being 'What you don't have can't leak.'\n\nKletz drew a sharp distinction between adding safety and building it in. Bolt-on safety — alarms, scrubbers, interlocks, relief systems — reduces risk but can fail, be bypassed, or be switched off. Inherently safer design instead removes the hazard at the source: store less of a dangerous material (minimize inventory), use a less hazardous substance where possible (substitution), run at gentler conditions (moderation), and simplify to cut the ways things can fail. A plant that keeps only a small quantity of a toxic intermediate cannot release a large one, no matter how many add-on systems fail. He wrote extensively on Bhopal, arguing it exemplified everything he warned against.\n\nFor this board, Kletz is the measure of what went wrong. A plant that stored a huge inventory of a lethal chemical, and leaned entirely on a stack of add-on safeguards to contain it, was fragile by design — and those very add-ons were the systems found disabled. Kletz would note first that the enormous stored quantity should never have existed, and second that relying on switch-off-able safeguards is exactly the trap he spent decades warning against. His lens turns 'freak accident' into 'foreseeable and foreseen,' and points the board straight at the decisions that chose cost over inherent safety.",
      frame:"Sahni lowers his voice near the office door. \"The safest tank is the one that's nearly empty. He filled ours to the brim and trusted the gadgets. Show me you understand inherent safety, and you'll see the choice that was made.\"",
      q:[
        { q:"What is the core idea of inherently safer design?", o:[
          { t:"Remove the hazard at its source rather than relying on add-on safeguards.", v:"expert", fb:"Inherent safety eliminates the danger instead of merely containing it." },
          { t:"Add as many alarms and interlocks as possible around a dangerous process.", v:"wrong", fb:"That is bolt-on safety, the very thing Kletz contrasted it against." },
          { t:"Train operators so thoroughly that no hazard can ever catch them off guard.", v:"wrong", fb:"Training helps, but inherent safety changes the design, not the people." },
          { t:"Insure the plant heavily so any loss from a hazard is fully covered.", v:"partial", fb:"Insurance handles cost after the fact; inherent safety removes the hazard." } ] },
        { q:"What did Kletz mean by 'what you don't have can't leak'?", o:[
          { t:"Storing less hazardous material means less can ever be released.", v:"expert", fb:"Minimizing inventory caps the worst possible release at the source." },
          { t:"Sealing a tank perfectly ensures its full contents can never escape at all.", v:"wrong", fb:"His point was about not storing the hazard, not about better seals." },
          { t:"Hidden materials are safe, so hazards should be kept out of public view.", v:"wrong", fb:"He meant reducing inventory, not concealing what is stored." },
          { t:"A chemical is harmless as long as it stays sealed inside its own vessel.", v:"partial", fb:"Vessels fail; his point was to store little, so failure matters less." } ] },
        { q:"How does Kletz's lens read this plant's design?", o:[
          { t:"A huge toxic inventory behind switch-off-able safeguards was fragile.", v:"expert", fb:"Large inventory plus bolt-on safety is exactly the trap he warned of." },
          { t:"The plant was inherently safe, so the release must have been forced by sabotage.", v:"danger", fb:"Storing a large hazard behind add-ons is the opposite of inherently safe." },
          { t:"The disaster was unforeseeable, since no one could predict a safeguard failing.", v:"danger", fb:"Kletz spent decades foreseeing exactly this; it was predictable." },
          { t:"The add-on safeguards made large inventory perfectly acceptable to store.", v:"partial", fb:"Add-ons can fail or be bypassed, which is why inventory should be small." } ] }
      ] },
    // cell: Operator Sahni @ The Plant Manager's Office
    riskdrift:{ sci:"Jens Rasmussen (1926-2018)", topic:"Why safeguards get bypassed", lede:"The Danish engineer who showed that organizations don't leap into disaster — they drift, one economy at a time.", no:14,
      profile:"Jens Rasmussen was a Danish systems-safety researcher whose work reshaped how engineers think about human error and organizational risk. Beginning in the nuclear industry, he developed the skill-rule-knowledge framework describing how people perform tasks at different cognitive levels, and later a broad risk-management model of how complex socio-technical systems behave. His most influential idea is often called 'drift to the boundary' or migration to danger: under relentless pressure toward efficiency and lower cost, and toward less individual effort, a system's actual operating point gradually moves away from the safe design margin toward the edge of catastrophe.\n\nRasmussen's insight is that this drift is not the work of villains or fools but the emergent result of many small, locally rational decisions: skip a redundant check that never seemed to matter, defer a costly maintenance, run a safeguard offline 'just for now.' Each step saves money or effort and seems harmless, and because nothing bad happens immediately, the new position feels normal. The margin of safety silently erodes until an ordinary disturbance, which the original design would have absorbed, now tips the system over the edge. He argued that safety management must actively push back against this economic and workload pressure, making the drift visible before it reaches the boundary.\n\nFor this board, Rasmussen names the mechanism behind the disabled safeguards. No single dramatic decision switched everything off at once; a series of cost-driven choices — deferred maintenance, safeguards left offline to save money, warnings not acted upon — moved the plant, step by step, to the boundary, where a routine upset became a catastrophe. This is neither an unforeseeable freak nor an outsider's sabotage; it is the predictable end of a drift that a plant manager under budget pressure allowed and directed. Rasmussen tells the board to trace the drift, and to ask who kept pushing the operating point toward the edge.",
      frame:"Sahni stares at the manager's shut door. \"It was never one big order. It was a hundred little 'just for now's until nothing was left. Show me you understand how a plant drifts, and you'll understand how we got here.\"",
      q:[
        { q:"What is Rasmussen's 'drift to the boundary'?", o:[
          { t:"A system edging toward danger as cost and effort pressures erode its margins.", v:"expert", fb:"Small economies gradually move operations toward the safety boundary." },
          { t:"A sudden decision by one person to abandon every safety rule at once.", v:"wrong", fb:"Drift is gradual and collective, not a single dramatic act." },
          { t:"A gradual improvement in safety as an organization learns from its mistakes.", v:"wrong", fb:"Drift moves toward danger, not away from it, absent active pushback." },
          { t:"A random wandering of risk that no management action could ever influence.", v:"partial", fb:"Drift is driven by real pressures and can be pushed back against." } ] },
        { q:"Why do individually rational choices produce drift?", o:[
          { t:"Each small economy seems harmless because nothing bad happens right away.", v:"expert", fb:"Local savings with no immediate harm normalize each step toward the edge." },
          { t:"Workers deliberately sabotage the margins to make their own jobs easier.", v:"wrong", fb:"Drift is not sabotage; the choices are locally rational, not malicious." },
          { t:"Managers are simply incompetent and cannot understand basic safety rules.", v:"wrong", fb:"Drift arises from ordinary pressures, not from stupidity." },
          { t:"Regulations force plants to cut corners against their operators' wishes.", v:"partial", fb:"Cost and workload pressure drive drift more than regulation does." } ] },
        { q:"How does drift explain the disabled safeguards here?", o:[
          { t:"A chain of cost-driven choices moved the plant to the edge, step by step.", v:"expert", fb:"Deferred upkeep and offline safeguards are the classic drift signature." },
          { t:"Only an intruder could disable that many systems, so drift is beside the point.", v:"danger", fb:"Drift, not an intruder, disables systems one economy at a time." },
          { t:"The failure was a sudden freak, so no gradual pattern could have led to it.", v:"danger", fb:"A gradual drift toward the boundary is exactly what preceded it." },
          { t:"The safeguards failed all at once by chance, unrelated to any decisions.", v:"partial", fb:"They were let go deliberately over time, which is the drift Rasmussen named." } ] }
      ] },
    // cell: The Safety Officer @ The Plant Manager's Office
    nearmiss:{ sci:"Herbert Heinrich (1886-1962)", topic:"The accident triangle & near-misses", lede:"The insurance man who counted thousands of mishaps and drew the pyramid that says every death has a crowd of warnings beneath it.", no:15,
      profile:"Herbert William Heinrich was an American safety engineer working for an insurance company when, in his 1931 book 'Industrial Accident Prevention,' he proposed a model that has shaped workplace safety ever since. Studying large numbers of incident reports, he suggested a rough ratio — often drawn as a triangle — in which for every serious injury there were many more minor injuries and a far larger base of no-injury near-misses. The famous figures, one major to twenty-nine minor to three hundred with no injury, are his; later researchers have questioned the exact numbers, but the underlying shape endures.\n\nHeinrich's real contribution was the idea that serious accidents are not isolated bolts from the blue but the visible tip of a pyramid of lesser events sharing common causes. If the broad base of near-misses and minor incidents is watched and acted upon, the rare catastrophe at the apex can often be prevented, because it springs from the same unsafe conditions. He also advanced a 'domino' model of accident causation, in which removing one contributing factor can stop the sequence. His work made near-miss reporting a cornerstone of process safety, even where his precise ratios are debated.\n\nFor this board, Heinrich's triangle asks a pointed question: what was happening at the base of the pyramid before the catastrophe at the apex? A major toxic release does not usually arrive without a history of smaller leaks, alarms, and near-misses beneath it, each a warning that shared the same root causes. If those warnings were logged and ignored, then the disaster was foreseeable in the most literal sense — it was foreseen, in the near-miss record, and not acted upon. That record is evidence, and it turns 'freak accident' into a story of ignored warnings.",
      frame:"The Safety Officer slides a folder across. \"Every big one sits on top of small ones nobody wanted to see. I logged the small ones. Show me you understand the triangle, and read what's in here.\"",
      q:[
        { q:"What does Heinrich's accident triangle claim?", o:[
          { t:"Each serious injury sits atop many minor ones and far more near-misses.", v:"expert", fb:"The triangle links rare disasters to a broad base of lesser events." },
          { t:"Serious accidents strike at random, with no smaller events beneath them.", v:"wrong", fb:"The triangle's whole point is a base of warnings under each disaster." },
          { t:"Minor injuries and major ones occur in exactly equal numbers over time.", v:"wrong", fb:"Heinrich's ratios are steeply weighted toward minor and near-miss events." },
          { t:"Only injuries that require hospital care are worth counting or recording.", v:"partial", fb:"The near-miss base, with no injury at all, is the most important to track." } ] },
        { q:"Why do near-misses matter for preventing disasters?", o:[
          { t:"They share the catastrophe's root causes, so acting on them prevents it.", v:"expert", fb:"Near-misses reveal the same hazards before the big event arrives." },
          { t:"They are harmless flukes, so recording them wastes an operator's time.", v:"wrong", fb:"Near-misses are the early warnings that could stop the disaster." },
          { t:"They matter only to the insurer's paperwork, not to actual plant safety.", v:"wrong", fb:"They are frontline safety intelligence, not mere paperwork." },
          { t:"They predict only the timing of a disaster, never its underlying cause.", v:"partial", fb:"They expose the shared causes, which is what lets prevention work." } ] },
        { q:"How does the triangle reframe this 'freak' disaster?", o:[
          { t:"A history of ignored leaks and alarms means the catastrophe was foreseen.", v:"expert", fb:"A logged near-miss record turns a freak into a warning unheeded." },
          { t:"The apex event came without warning, so no near-misses could have preceded it.", v:"danger", fb:"Major releases almost always sit on a base of ignored near-misses." },
          { t:"Such a disaster can only mean an intruder bypassed a spotless safety record.", v:"danger", fb:"A near-miss trail points to internal warnings, not an outside intruder." },
          { t:"Near-misses cannot be linked to the final event, so the record proves nothing.", v:"partial", fb:"Shared root causes link them directly; the record is strong evidence." } ] }
      ] },
    // cell: The Safety Officer @ The Plant Manager's Office
    corrosion:{ sci:"Ulick R. Evans (1889-1980)", topic:"Corrosion", lede:"The Cambridge chemist who proved that rust is not decay but a battery, quietly eating a plant from the inside out.", no:16,
      profile:"Ulick Richardson Evans was a British scientist at Cambridge who is widely regarded as the father of the modern science of corrosion. Across a long career, culminating in his 1960 masterwork 'The Corrosion and Oxidation of Metals,' he established that the rusting of metals is fundamentally an electrochemical process, not a vague chemical decay. Where a metal surface has regions of differing potential, tiny galvanic cells form; metal dissolves at anodic sites while a complementary reaction proceeds at cathodic sites, with moisture and dissolved oxygen or salts completing the circuit. Corrosion, Evans showed, obeys the laws of electrochemistry and can be measured, predicted, and controlled.\n\nThis understanding turned corrosion from an inevitable nuisance into an engineering variable. Evans mapped how protective oxide films form and break down, why certain spots pit and others stay sound, and how coatings, inhibitors, and material choices slow the process. Crucially, corrosion is cumulative and often hidden: a pipe or vessel wall can thin steadily from the inside, sound to the eye, until it leaks or fails, or until its shed products contaminate the very fluid it carries. Regular inspection and maintenance exist precisely because corrosion works out of sight and on its own schedule.\n\nFor this board, corrosion is where deferred maintenance turns physical. Pipes and vessels left uninspected and unmaintained corrode; a corroded line can admit a contaminant into a tank that must stay pure, and the iron it sheds can catalyze the very reaction that runs away. None of this is exotic or unforeseeable — it is the slow, lawful electrochemistry Evans described, and its remedy is maintenance that costs money. When that maintenance is cut, corrosion advances on schedule. The board should read a corroded, contaminating pipe not as bad luck but as the visible cost of a budget decision.",
      frame:"The Safety Officer runs a thumb over a pitted pipe sample. \"This didn't happen overnight, and it wasn't bad luck. Maintenance was cut. Tell me what corrosion really is, and you'll see what neglect looks like.\"",
      q:[
        { q:"What did Evans show corrosion fundamentally is?", o:[
          { t:"An electrochemical process, with tiny galvanic cells dissolving metal.", v:"expert", fb:"Corrosion obeys electrochemistry, not vague chemical decay." },
          { t:"A purely mechanical wearing-away of metal by the friction of moving fluids.", v:"wrong", fb:"That is erosion; corrosion is electrochemical dissolution." },
          { t:"A sudden chemical burning of metal that only occurs at very high heat.", v:"wrong", fb:"Corrosion proceeds at ordinary temperatures via electrochemical cells." },
          { t:"An unavoidable decay that follows no rules and cannot be predicted at all.", v:"partial", fb:"Evans showed it follows electrochemical laws and can be predicted." } ] },
        { q:"Why is corrosion especially dangerous when hidden?", o:[
          { t:"A wall can thin from within, looking sound, until it leaks or fails.", v:"expert", fb:"Internal corrosion progresses unseen until a sudden failure or leak." },
          { t:"It always announces itself loudly, so a hidden case simply cannot exist.", v:"wrong", fb:"Corrosion often works out of sight, which is precisely the danger." },
          { t:"It only ever affects a metal's outer paint, never the structure beneath.", v:"wrong", fb:"Corrosion attacks the metal itself, thinning load-bearing walls." },
          { t:"It stops on its own once a thin protective film has formed on the surface.", v:"partial", fb:"Films can break down locally, letting pitting and thinning continue." } ] },
        { q:"How does corrosion connect to this disaster?", o:[
          { t:"Deferred upkeep let pipes corrode, admitting contaminant and a catalyst.", v:"expert", fb:"Corrosion from cut maintenance is a direct, lawful route to the upset." },
          { t:"Corrosion is random bad luck, so the contaminated tank was simple misfortune.", v:"danger", fb:"Corrosion follows predictable electrochemistry driven by cut maintenance." },
          { t:"Only an intruder drilling the pipe could have let a contaminant into the tank.", v:"danger", fb:"A corroded, neglected line admits contaminants with no intruder at all." },
          { t:"Corrosion weakens metal but could never affect the chemistry inside a tank.", v:"partial", fb:"Shed corrosion products can catalyze the reaction, affecting the chemistry." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Plant Manager's Office
    ammonia:{ sci:"Fritz Haber (1868-1934)", topic:"The Haber process & dual-use", lede:"The chemist who pulled bread from the air and poison gas from the same genius, and never escaped either legacy.", no:17,
      profile:"Fritz Haber was a German chemist whose 1918 Nobel Prize recognized his synthesis of ammonia from atmospheric nitrogen and hydrogen — the reaction, industrialized by Carl Bosch, that made synthetic fertilizer possible and now helps feed billions. It was one of the most consequential discoveries in history, breaking the natural limit on how much food the land could yield. Yet the same Haber personally led Germany's chemical-weapons program in the First World War, directing the first large-scale use of chlorine gas at Ypres in 1915. His wife Clara Immerwahr, herself a chemist, died by suicide days after that attack.\n\nHaber embodies the principle of dual use: that the same chemistry, the same knowledge, and often the same substances can nourish or kill depending on how they are handled. Ammonia feeds crops and also underlies explosives; the industrial gases that make pesticides can themselves be lethal. Chemistry is not moral or immoral in itself; the danger lies in scale, intent, and control. Haber's fertilizers saved untold lives even as his gases took them, and history has never quite settled the ledger of a man who was both benefactor and war criminal.\n\nFor this board, Haber's dual-use lesson cuts against the sensational story. A plant like Ardsley handles intrinsically dangerous chemistry for an ordinary industrial purpose, making something useful from substances that are lethal if released. The presence of a deadly gas is not evidence of a weapon or a plot; it is the everyday nature of the materials, the same duality Haber lived. The question is never whether the chemistry could kill — of course it could — but whether it was contained. When the containment was stripped away to save money, ordinary industrial poison did what such poison does, no saboteur required.",
      frame:"Vale caps the tanker valve. \"Same stuff that grows the crops will drop a town if you let it loose. That's just the trade. Show me you get how a useful chemical is also a deadly one.\"",
      q:[
        { q:"What did the Haber process achieve?", o:[
          { t:"Synthesizing ammonia from air, for fertilizer that now feeds billions.", v:"expert", fb:"Fixing atmospheric nitrogen broke the natural limit on food production." },
          { t:"Extracting pure oxygen from the air to enrich industrial furnaces.", v:"wrong", fb:"The process fixes nitrogen into ammonia, not oxygen." },
          { t:"Turning coal directly into liquid fuel for wartime engines and vehicles.", v:"wrong", fb:"That is a different process; Haber's fixed nitrogen into ammonia." },
          { t:"Distilling ammonia out of animal waste at a far larger industrial scale.", v:"partial", fb:"He synthesized it from air and hydrogen, not by distilling waste." } ] },
        { q:"What does 'dual use' mean in chemistry?", o:[
          { t:"The same chemistry can nourish or kill, by scale, intent, and control.", v:"expert", fb:"Dual use means one science serves both benefit and harm." },
          { t:"A chemical can be used only once before it must be completely discarded.", v:"wrong", fb:"Dual use is about two purposes, not a single use before disposal." },
          { t:"Two different chemicals are always required to produce any useful product.", v:"wrong", fb:"Dual use refers to one substance's benign and harmful roles." },
          { t:"A substance is safe in industry but dangerous only in a laboratory setting.", v:"partial", fb:"The duality is benefit versus harm, not lab versus industry." } ] },
        { q:"How does dual use undercut the sabotage theory?", o:[
          { t:"A deadly gas on site is the ordinary nature of the work, not a plot.", v:"expert", fb:"Lethal chemistry is routine here; its presence implies no weapon." },
          { t:"Only a saboteur would keep such a lethal substance at an industrial plant.", v:"danger", fb:"Lethal intermediates are normal industrial stock, not a saboteur's mark." },
          { t:"The gas proves a secret weapons program was hidden inside the plant.", v:"danger", fb:"Dangerous chemistry is standard here; it signals no clandestine weapon." },
          { t:"Such a gas is harmless in industry and only dangerous if weaponized first.", v:"partial", fb:"It is lethal either way; the issue is containment, not weaponization." } ] }
      ] },
    // cell: Tanker Driver Vale @ The Plant Manager's Office
    processcontrol:{ sci:"Nicolas Minorsky (1885-1970)", topic:"Process control & feedback", lede:"The Russian-American engineer who taught a ship to steer itself, and gave industry the feedback loop that holds a plant steady.", no:18,
      profile:"Nicolas Minorsky was a Russian-born American engineer and control theorist who, in a landmark 1922 paper on the automatic steering of ships, laid out the mathematics of what became proportional-integral-derivative (PID) control. Watching how a skilled helmsman corrected a ship's course — responding not just to the present error but to its accumulation over time and to how fast it was changing — he formalized the three-term feedback controller that still regulates temperature, pressure, flow, and level in plants worldwide. Feedback control is the art of measuring a variable, comparing it to a target, and automatically adjusting to close the gap.\n\nThe power of feedback is stability: a well-tuned loop holds a process at its setpoint against disturbances, and a layered system of alarms and interlocks extends the same logic into safety. An alarm alerts an operator when a variable strays into a dangerous range; an interlock goes further, automatically taking a protective action — shutting a valve, tripping a pump, dumping a reaction to a safe state — without waiting for a human. These automatic safeguards are the plant's reflexes, designed to catch an upset faster than any person can, and to act even when no one is watching the board.\n\nFor this board, process control explains what the disabled interlocks and silenced alarms were supposed to do. A rising temperature or pressure should have tripped an interlock that cooled, vented safely, or shut the process down, and should have sounded alarms that summoned a response. If those loops were bypassed or their alarms muted, the plant lost its reflexes: the automatic corrections that would have caught the upset never fired, and the operators were flying blind. Minorsky's feedback is the difference between a self-correcting plant and a runaway one — and someone chose to cut the loops that would have corrected this one.",
      frame:"Vale nods at the dark alarm panel. \"A plant's supposed to catch itself before a man even reaches the button. This one had its reflexes cut out. Tell me how feedback control works, and you'll see what was missing.\"",
      q:[
        { q:"What is feedback control, in Minorsky's sense?", o:[
          { t:"Measuring a variable against a target and adjusting to close the gap.", v:"expert", fb:"Feedback continuously corrects toward the setpoint." },
          { t:"Setting a process once at startup and never adjusting it again afterward.", v:"wrong", fb:"That is open-loop; feedback keeps correcting against disturbances." },
          { t:"Letting the operator make every adjustment by hand with no automation at all.", v:"wrong", fb:"Feedback control automates the correction Minorsky formalized." },
          { t:"Recording a variable for later review without acting on it during the run.", v:"partial", fb:"Feedback acts in real time; mere recording does not correct anything." } ] },
        { q:"What does a safety interlock do?", o:[
          { t:"It automatically takes a protective action when a variable strays into danger.", v:"expert", fb:"Interlocks act on their own to bring a process to a safe state." },
          { t:"It merely logs a dangerous condition for the operators to review the next day.", v:"wrong", fb:"An interlock acts immediately; it does not just log for later." },
          { t:"It locks the control room door so no unauthorized person can reach the panel.", v:"wrong", fb:"An interlock is a process safeguard, not a physical door lock." },
          { t:"It sounds an alarm and then waits for a human to decide what to do next.", v:"partial", fb:"That is an alarm; an interlock takes the protective action itself." } ] },
        { q:"What did bypassing the interlocks and alarms cost this plant?", o:[
          { t:"Its automatic reflexes, so the upset was never caught and operators flew blind.", v:"expert", fb:"Cutting the loops removed the corrections that would have caught it." },
          { t:"Nothing, since interlocks are backups that a good operator never actually needs.", v:"danger", fb:"Interlocks act faster than any operator; losing them is decisive." },
          { t:"Only its record-keeping, as alarms and interlocks merely document events.", v:"danger", fb:"They actively intervene; without them, no automatic correction fires." },
          { t:"Its efficiency alone, because interlocks affect output but never safety.", v:"partial", fb:"Interlocks are primarily safety reflexes, not production tuning." } ] }
      ] }
  },
  STORIES:{
    operator:{
      tank:"Sahni stands at the foot of the cold tank, arms wrapped tight. \"I watched this gauge climb for an hour and had nothing left to stop it. Everything I'd have reached for was already dead.\"",
      controlroom:"Sahni sits at his darkened console, pointing at a muted alarm tile. \"This should have been screaming. It wasn't. I was flying the plant blind and they'd taken my instruments away.\"",
      office:"Sahni lingers uneasily outside the manager's door. \"The orders came from in here — run lean, defer this, shut that down 'for now.' I only worked the board they handed me.\""
    },
    safety:{
      tank:"The Safety Officer gestures at the reactor's dead cooling jacket. \"I put the runaway risk in writing months ago. Cold storage was the whole defense, and look — the refrigeration's been off.\"",
      controlroom:"The Safety Officer taps a shelved report on the console. \"Every warning I filed ended up in a drawer, not a work order. The scrubber and flare were on that list, both offline.\"",
      office:"The Safety Officer stands rigid before the filing cabinet. \"My reports are in here somewhere, stamped received and ignored. Someone read them and chose the budget instead.\""
    },
    driver:{
      tank:"Vale thumps the tank's shell. \"I filled this to the brim and signed for it. Full of the nasty stuff, and the chiller wasn't even humming when I pulled out.\"",
      controlroom:"Vale leans in the doorway, unimpressed. \"Your fancy panel's half dark. I don't need it to tell you what was in that tank or how much — I hauled every drop.\"",
      office:"Vale jerks a thumb at the manager's desk. \"He signed my manifests and knew exactly what was sitting out there. Don't let him act surprised about his own inventory.\""
    }
  },
  story:[
    "At a few minutes past midnight, a low cloud slid over the wall of the <b>Ardsley Works</b> and settled into the streets of the town asleep downwind. By dawn the wards were full and the plant was silent, and you, <b>Inspector Grace Mbeki</b>, have been handed the file the whole country is now watching. The chemistry that made this town's living has turned on it, and everyone wants to know how.",
    "<b>Three people inside will help you</b>, each holding a piece and none the whole. <b>Operator Sahni</b>, who worked the night board and watched the pressure climb with nothing left to stop it. <b>The Safety Officer</b>, who filed warning after warning and saw each one shelved. And <b>Tanker Driver Vale</b>, blunt and unimpressed, who knows exactly what was stored, how much, and what wasn't running. Prove you understand the science and they will talk.",
    "<b>Someone here is behind it.</b> Three names sit in your notepad: <b>Voss</b>, the plant manager, who ran the budget; the <b>night-shift operator</b>, who had the controls; and the <b>maintenance contractor</b>, who kept the iron sound — or didn't. Every column of the case — <b>who</b> is behind it, <b>where</b> it culminates, and <b>what</b> truly happened — hides a tempting wrong answer. The front pages want <b>deliberate sabotage, an intruder in the dark</b>. The quick verdict wants <b>an unforeseeable freak accident, no one to blame</b>. The truth is narrower than the first and graver than the second.",
    "You have <b>8 days</b> and a single accusation to make. Name it well and a shelved stack of warnings becomes proof; name it wrong and a real, provable failure is lost to a headline or written off as fate."
  ],
  endings:{ overclaimWhat:"sabotage", dismissalWhat:"freak",
    win:{
      expertTitle:"What the Records Prove, and No More",
      expert:["Mbeki names it exactly: Voss, the plant manager, who ran the plant lean and ordered the safeguards left broken to cut costs; the truth culminating in the Plant Manager's Office, where the budget orders and the shelved warning reports live; and safety systems deliberately disabled — the scrubber drained, the flare cold, the refrigeration off, the interlocks bypassed — so a routine upset became a catastrophe. Not a saboteur. Not an act of fate.",
        "Every column accounted for. Mbeki worked the tank, the control room, and the office, turned a vindicated safety officer and a haunted operator into witnesses, and claimed precisely what the records and the near-miss log could defend. The inquiry issues findings that fix the design and name the decision that killed a town — which is the entire point of doing it right."],
      soundTitle:"Right — but Lightly Proven",
      sound:["Mbeki names the right three — Voss, the Plant Manager's Office, and safety systems disabled to cut costs. The shape of the case is correct, and the refusal to cry sabotage or shrug at fate is exactly right.",
        "But too many threads were left loose, and the company's lawyers will pull at them. A few more days tracing the shelved reports and the disabled-alarm records would have made the finding unassailable. Close and honest, if not yet airtight."],
      namedTitle:"The Right Answer, Unearned",
      named:["Mbeki names the truth — Voss, the office, the safeguards switched off to save money — but gathered too little to back it. It reads like a hunch that happened to land.",
        "The inquiry cannot indict a manager and fault a design on an accusation this thin, however correct. Being right is not the same as being able to prove it to the people who will fight the finding."]
    },
    overclaim:{ title:"The Inquiry That Cried Sabotage",
      body:["Mbeki reports deliberate sabotage — an intruder who forced the release — the answer the front pages were already printing. It is vivid, and it is not what the evidence shows.",
        "There was no intruder and no forced entry; there was a drained scrubber, a cold flare, dead refrigeration, and bypassed interlocks, every one of them switched off or left broken to save money. When the sabotage story collapses, it takes the inquiry's credibility with it, and the real, provable failure is dismissed as just another conspiracy theory. The only saboteur was a budget, and the manager who signed it."] },
    dismissal:{ title:"Case Closed on Bad Luck",
      body:["Mbeki files it as an unforeseeable freak accident — a one-in-a-million upset no one could have prevented, close the file. It is the comfortable answer and it is false.",
        "The reaction was thermodynamically downhill and its runaway textbook; the safeguards existed precisely to absorb such an upset, and they were disabled to cut costs. The near-miss log warned of it, the safety officer's shelved reports named it, and the physics made it foreseeable. Blaming fate leaves every disabled system disabled, waiting for the next town downwind. The inquiry saw an accident and never the decision cut into the plant."] },
    wrongNames:{ title:"So Close",
      body:["Mbeki has the nature of it cold — safety systems disabled to cut costs, the scrubber and flare and refrigeration and interlocks all switched off or left broken, neither a saboteur nor a freak of fate. But the finger lands on the wrong name or the wrong room."] } },
}};
