// groups.js — the areas of study
// GENERATED by tools/import-book.mjs from boomtown.yml
// Hand edits are lost on the next import. Change the book.

export const GROUPS = [
  {
    "id": "T",
    "code": "T",
    "name": "Civic Advice Office",
    "color": "#315c78",
    "difficulty": 5,
    "type": "ballpark",
    "desc": "",
    "defaultLeader": "velez",
    "budget": 72,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "CM",
    "code": "CM",
    "name": "Business Workshop",
    "color": "#8a6921",
    "difficulty": 4,
    "type": "protocol",
    "desc": "",
    "defaultLeader": "bell",
    "budget": 80,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "E",
    "code": "E",
    "name": "Freight Contract Office",
    "color": "#865044",
    "difficulty": 3,
    "type": "sequence",
    "desc": "",
    "defaultLeader": "sen",
    "budget": 88,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "P",
    "code": "P",
    "name": "Housing and Work Office",
    "color": "#4b775f",
    "difficulty": 4,
    "type": "diagnosis",
    "desc": "",
    "defaultLeader": "moss",
    "budget": 72,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  },
  {
    "id": "X",
    "code": "X",
    "name": "Water and Land Office",
    "color": "#704f88",
    "difficulty": 5,
    "type": "sciencetank",
    "desc": "",
    "defaultLeader": "price",
    "budget": 96,
    "milestones": [
      {
        "name": "Open the room",
        "cost": 12,
        "work": 9,
        "brief": "Open the room"
      },
      {
        "name": "Read what it holds",
        "cost": 16,
        "work": 12,
        "brief": "Read what it holds"
      },
      {
        "name": "Settle the question",
        "cost": 20,
        "work": 15,
        "brief": "Settle the question"
      },
      {
        "name": "Hand it on",
        "cost": 24,
        "work": 18,
        "brief": "Hand it on"
      }
    ],
    "issuePool": [
      "A result and a record disagree.",
      "A step was skipped."
    ]
  }
];
