// interiors.js — what is inside each room
// GENERATED by tools/import-book.mjs from qd-dna.yml
// Hand edits are lost on the next import. Change the book.

export const INTERIORS = {
  "CHEM": {
    "caption": "A composition is a measurement; a structure is an argument.",
    "standLine": "Two runs of the base analysis, agreeing, and two columns still blank.",
    "station": {
      "kind": "panel",
      "title": "Base analysis",
      "rows": [
        {
          "label": "Adenine",
          "value": "30.1 %",
          "status": "normal"
        },
        {
          "label": "Guanine",
          "value": "19.8 %",
          "status": "normal"
        },
        {
          "label": "Thymine",
          "value": "not reported",
          "status": "low"
        },
        {
          "label": "Cytosine",
          "value": "not reported",
          "status": "low"
        }
      ]
    }
  },
  "XRAY": {
    "caption": "A plate records where the scattered rays went, not what the molecule looks like.",
    "standLine": "One exposure, eleven hours, measured twice against the scale.",
    "station": {
      "kind": "film",
      "title": "Plate 51",
      "note": "strong X, layer lines to the fourth order"
    }
  },
  "MODEL": {
    "caption": "Brass will not let a rung close that does not close.",
    "standLine": "Two backbones clamped at a fixed separation, one rung to fill.",
    "station": {
      "kind": "panel",
      "title": "Rung gauge",
      "rows": [
        {
          "label": "Backbone separation",
          "value": "11.1 Å",
          "status": "normal"
        },
        {
          "label": "Rungs closed",
          "value": "0 of 10",
          "status": "low"
        },
        {
          "label": "Widths agreeing",
          "value": "awaiting a pair",
          "status": "low"
        }
      ]
    }
  },
  "BOARD": {
    "caption": "A candidate is crossed off by naming the clue it breaks.",
    "standLine": "Four candidates standing, seven clues pinned above them.",
    "station": {
      "kind": "plot",
      "title": "Mass per unit length",
      "note": "one number, two unknowns",
      "axes": {
        "x": "chains wound together",
        "y": "rise per base"
      },
      "curves": [
        {
          "points": [
            [
              0.08,
              0.06
            ],
            [
              0.25,
              0.28
            ],
            [
              0.42,
              0.5
            ],
            [
              0.58,
              0.72
            ],
            [
              0.75,
              0.94
            ]
          ],
          "label": "fits the weighing"
        }
      ]
    }
  }
};
