// fixtures.js — the objects the questions are about, for The Trial.
//
// GENERATED from the campaign bible by tools/build-fixtures.mjs. Every id, place,
// kind and caption is the bible's; `wall` and `along` are this file's, because
// they are about the room rather than the object. Look at them with
// `npm run shots` before believing the arrangement — see gamekit/INTERIORS.md.
//
//   build:  'vessel' | 'rack' | 'bench' | 'board'
//   wall:   'left' | 'right' | 'back'
//   along:  -1 … 1 along that wall. 0 is the middle.
export const FIXTURES = {
  REG: [
    { id: 'commitment-terminal', name: 'The preregistered endpoints', build: 'vessel', wall: 'back', along: 0,
      caption: "The preregistered endpoints, analysis dates, and amendment controls glow behind Lena's keyed approval screen." },
    { id: 'records-wall', name: 'Protocol pages', build: 'board', wall: 'left', along: 0,
      caption: "Protocol pages, registry timestamps, and signed change notices run in one dated line across the wall." },
    { id: 'claim-ledger', name: 'Every proposed claim has a numbered row', build: 'board', wall: 'right', along: 0,
      caption: "Every proposed claim has a numbered row, a promised test, and a blank seal where evidence is still missing." },
    { id: 'evidence-desk', name: 'Variable cards', build: 'bench', wall: 'back', along: -0.45,
      caption: "Variable cards, summary sheets, and the day's flagged values lie beneath a lamp marked DESCRIBE FIRST." },
  ],
  MONITOR: [
    { id: 'monitor-desk', name: 'Hospital rosters', build: 'bench', wall: 'back', along: 0,
      caption: "Hospital rosters, sampling instructions, and source-query slips arrive here before they cross upstairs." },
    { id: 'enrollment-wall', name: 'enrollment wall', build: 'board', wall: 'left', along: 0,
      caption: "Enrollment counts by hospital and region face a row of empty spaces for patients who never entered the frame." },
    { id: 'query-map', name: 'Distance', build: 'board', wall: 'right', along: 0,
      caption: "Distance, follow-up delay, and open queries connect each site to Fenwick with colored cord." },
    { id: 'site-comparison-board', name: 'Site rates', build: 'board', wall: 'back', along: -0.45,
      caption: "Site rates, residuals, deletion checks, and pause status share one board beside Eli's phone." },
  ],
  RAND: [
    { id: 'allocation-reader', name: 'allocation reader', build: 'vessel', wall: 'back', along: 0,
      caption: "The concealed sequence appears one assignment at a time, with block and match settings locked behind Priya's key." },
    { id: 'sealed-box-scanner', name: 'sealed box scanner', build: 'vessel', wall: 'left', along: 0,
      caption: "Numbered treatment boxes pass under a scanner that records seals, weights, and handling times without revealing the arm." },
    { id: 'blind-ledger', name: 'Kit numbers', build: 'board', wall: 'right', along: 0,
      caption: "Kit numbers, guess surveys, and custody signatures meet here without treatment labels." },
    { id: 'randomisation-board', name: 'Candidate designs', build: 'board', wall: 'back', along: -0.45,
      caption: "Candidate designs, precision estimates, and expected waiting times remain pinned beside the approved allocation rule." },
  ],
  DATAMANA: [
    { id: 'roster-wall', name: 'Screened', build: 'board', wall: 'back', along: 0,
      caption: "Screened, enrolled, randomized, treated, and analyzed patients occupy separate columns, including the missing rows." },
    { id: 'extraction-console', name: 'The frozen extract', build: 'vessel', wall: 'left', along: 0,
      caption: "The frozen extract, sampling controls, and holdout hash sit behind a two-person release switch." },
    { id: 'deletion-diagnostic', name: 'deletion diagnostic', build: 'board', wall: 'right', along: 0,
      caption: "Complete-case and restored-data fits appear together, with the fast site circled only after the comparison runs." },
    { id: 'holdout-safe', name: 'Sealed validation files carry hashes', build: 'rack', wall: 'back', along: -0.45,
      caption: "Sealed validation files carry hashes, owners, and release times on tamper-evident sleeves." },
    { id: 'sampling-board', name: 'Sample size', build: 'board', wall: 'left', along: -0.45,
      caption: "Sample size, standard error, and repeated-sample spreads are written beside the roster they describe." },
  ],
  ENDP: [
    { id: 'outcome-viewer', name: 'Patient records can be viewed by center', build: 'vessel', wall: 'back', along: 0,
      caption: "Patient records can be viewed by center, outcome definition, and adjudication status without exposing treatment." },
    { id: 'adjudication-desk', name: 'Amina\'s rubric', build: 'bench', wall: 'left', along: 0,
      caption: "Amina's rubric, paired charts, and disputed endpoint packets wait under the same reading lamp." },
    { id: 'matched-record-table', name: 'matched record table', build: 'bench', wall: 'right', along: 0,
      caption: "Matched pairs and independent groups occupy separate trays so no patient can silently count twice." },
    { id: 'table-wall', name: 'Means', build: 'board', wall: 'back', along: -0.45,
      caption: "Means, counts, fitted distributions, and the population each table can reach are posted with their assumptions." },
  ],
  STAT: [
    { id: 'analysis-board', name: 'Parameters', build: 'board', wall: 'back', along: 0,
      caption: "Parameters, estimators, probability rules, and the current model are written where the whole team can challenge them." },
    { id: 'simulation-console', name: 'simulation console', build: 'vessel', wall: 'left', along: 0,
      caption: "Repeated trials accumulate into sampling distributions, event counts, and power curves on the central console." },
    { id: 'residual-wall', name: 'Residual plots', build: 'board', wall: 'right', along: 0,
      caption: "Residual plots, leverage marks, and model checks remain visible after the headline fit is printed." },
    { id: 'uncertainty-console', name: 'Intervals', build: 'vessel', wall: 'back', along: -0.45,
      caption: "Intervals, error rates, and sensitivity bounds move together as Tomas changes one assumption at a time." },
    { id: 'extraction-map', name: 'Roster fields', build: 'board', wall: 'left', along: -0.45,
      caption: "Roster fields, adjudicated outcomes, model inputs, and final tables connect through a signed data lineage." },
    { id: 'evidence-budget-desk', name: 'Follow-up options carry costs', build: 'bench', wall: 'right', along: -0.45,
      caption: "Follow-up options carry costs, expected information, and the decision each result could still change." },
  ],
  SAFE: [
    { id: 'event-console', name: 'Arm-by-event counts', build: 'vessel', wall: 'back', along: 0,
      caption: "Arm-by-event counts, exposure time, and interim boundaries appear without patient names." },
    { id: 'board-console', name: 'Jonas\'s console holds site pauses', build: 'vessel', wall: 'left', along: 0,
      caption: "Jonas's console holds site pauses, benefit-harm summaries, and the controls that authorize the next action." },
    { id: 'trigger-rail', name: 'Precommitted stop', build: 'board', wall: 'right', along: 0,
      caption: "Precommitted stop, continue, and follow-up rules slide along a rail but cannot be rewritten after results arrive." },
    { id: 'board-simulator', name: 'Power', build: 'vessel', wall: 'back', along: -0.45,
      caption: "Power, effect size, variance, and enrollment assumptions feed a projected decision path across the screen." },
    { id: 'board-table', name: 'The final statistical argument', build: 'bench', wall: 'left', along: -0.45,
      caption: "The final statistical argument, safeguard sheet, and seven signature spaces lie in front of the voting seats." },
  ],
  TRIAMAST: [
    { id: 'archive-seal', name: 'A steel seal records the file hash', build: 'vessel', wall: 'back', along: 0,
      caption: "A steel seal records the file hash, lock time, and every authorized opening of the master record." },
    { id: 'evidence-locker', name: 'Protocol versions', build: 'rack', wall: 'left', along: 0,
      caption: "Protocol versions, signed attestations, and frozen extracts occupy numbered archival boxes." },
    { id: 'provenance-desk', name: 'provenance desk', build: 'bench', wall: 'right', along: 0,
      caption: "A read-only terminal traces each final number back to its source record and approving signature." },
  ],
  KITWAREC: [
    { id: 'exposure-logger', name: 'Temperature traces', build: 'vessel', wall: 'back', along: 0,
      caption: "Temperature traces, door openings, and kit identifiers scroll beneath the cold-room alarm lamps." },
    { id: 'cold-room-workbench', name: 'Interval worksheets', build: 'bench', wall: 'left', along: 0,
      caption: "Interval worksheets, benchmark limits, and quarantined-kit lists sit beside insulated gloves." },
    { id: 'temperature-rack', name: 'temperature rack', build: 'rack', wall: 'right', along: 0,
      caption: "Reference probes and sealed control kits stand at three shelf heights inside the monitored room." },
    { id: 'kit-sequence-rack', name: 'kit sequence rack', build: 'rack', wall: 'back', along: -0.45,
      caption: "Numbered boxes preserve the actual packing order, with one sealed sequence reserved for audit." },
    { id: 'blind-audit-table', name: 'Guess surveys', build: 'bench', wall: 'left', along: -0.45,
      caption: "Guess surveys, concealment checks, and arm-free summaries are spread across a table with no treatment key." },
    { id: 'label-scanner', name: 'label scanner', build: 'vessel', wall: 'right', along: -0.45,
      caption: "A handheld reader checks label order and custody history while keeping assignment codes masked." },
  ],
};
