// theme.js — Deep Watch, at grade 6.
//
// edition-of: deepwatch
//
// GENERATED by tools/derive-edition.mjs. This is an *edition*: the place, the
// props, the interiors and the outfits are themes/deepwatch's and are imported
// across, so this directory owns a manifest and its generated content and
// nothing else. engine/dev/editionParity.mjs fails the game for any other file
// in here, and for a cast or a set of areas that has drifted from the base.
//
// The marker line above is read by engine/dev/registry.mjs (placeDir) and by
// vite.config.js, which take the site kind and the world module from the base
// theme — this directory's site.js is a re-export and no regex can read it.
import { site } from '../deepwatch/site.js';
import { GROUPS } from './content/groups.js';
import { MISSIONS, WARMUPS } from './content/missions.js';
import { CURRICULUM, BALLPARK_CALCS, JARGON } from './content/curriculum.js';
import { ROSTER, LEADERS, AVATARS } from './content/roster.js';
import { COPY } from './content/copy.js';
import { OUTFITS, roleToOutfit } from '../deepwatch/outfits.js';
import { INTERIORS } from '../deepwatch/interiors.js';

export default {
  // Who this edition is for. `engine/core/typography.js` reads it and scales the
  // root font size, so the same game can ship at several reading levels with
  // type sized for each. Undergraduate: no scaling.
  audience: { grade: 6 },

  // What one mission is called here. The engine's model is a working day;
  // this campaign is not one, so the label is not either.
  dayNoun: 'Watch',


  id: 'deepwatch_ms',
  title: 'Deep Watch',
  subtitle: 'Reasoning Under Pressure Beneath the Surface',

  site,
  start: site.spawn,

  content: { GROUPS, MISSIONS, CURRICULUM, BALLPARK_CALCS, JARGON, ROSTER, LEADERS, AVATARS, COPY, WARMUPS },

  people: {
    OUTFITS,
    roleToOutfit,
    spawn: ROSTER.length,
    // A boat is crowded, and the passage is 4.5 m wide: more than a handful of
    // extras and the player cannot get past them.
    extras: 8,
  },

  interiors: INTERIORS,
  // Painted steel and deck matting, not laboratory vinyl.
  interiorStyle: 'steel',

  opening: [
    'You have the watch on a submarine, ninety metres down. Nobody aboard can see '
    + 'out, and neither can you. What you know about the water comes from listening. '
    + 'What you know about the boat comes from people reading gauges to you over a '
    + 'telephone. Tonight something is out there that nobody has named, water is '
    + 'rising inside the hull, and the pencil line on the chart drifts further from '
    + 'the truth every minute. Commander Iris Vance can order the boat up, where all '
    + 'of it stops being deadly. Somebody has to be willing to say so.',
  ],

  // How it ends. Shown when the campaign closes and printed as the book's last page.
  ending: [
    'The boat surfaced at dawn on the twenty-third day, into weather nobody had seen for three '
    + 'weeks. The fractured wrist is in a cast and signed fit for the transit. The contact was '
    + 'resolved, the plot was fixed, and the machine that had been left since Tuesday was opened '
    + 'up and found in time.',
    'Nothing was lost on this patrol that could not be repaired. The whole crew went up the ladder '
    + 'into daylight, which is the only measure of a watch that matters.',
  ],
  look: {
    fov: 68,
    near: 0.05,
    far: 200,
    // Exponential, not linear: inside a hull the far end of the passage should
    // fade rather than end.
    fog: { colour: 0x04080a, density: 0.012 },
    exposure: 1.0,
    // A hatch is a 1.1 m opening. At the engine's default 0.45 the player is
    // 0.9 m across and the gap that is left is twelve centimetres, which reads
    // in play as "sometimes I cannot get through the door".
    playerRadius: 0.3,
    lighting: { ambient: 0.55, hemi: 0.6 },
  },
};
