// curriculum.js — lessons per area, the estimate specs and the glossary
// GENERATED by tools/import-book.mjs from bring-them-home-ms.yml
// Hand edits are lost on the next import. Change the book.

export const CURRICULUM = {
  "NAV": [
    {
      "day": 1,
      "title": "Which measurement gives what",
      "scene": "The onboard computer has restarted and the tracking comes and goes. The room has to rebuild where the spacecraft is from whatever can still be measured, and say what each measurement buys.",
      "takeaway": "No single measurement gives a position. Each one gives a piece, and the pieces are different shapes.",
      "place": "Deep-Space Tracking Station",
      "story": "The onboard computer has restarted and the tracking comes and goes. The room has to rebuild where the spacecraft is from whatever can still be measured, and say what each measurement buys.",
      "game": {
        "type": "PROTOCOL",
        "title": "Which measurement gives what",
        "setup": "Deep-Space Tracking Station",
        "play": "Match each thing you need to know to the measurement that gives it.",
        "task": "Match each thing you need to know to the measurement that gives it.",
        "question": "Match each thing you need to know to the measurement that gives it.",
        "answer": "",
        "why": "Each measurement answers a different question and none of them answers all of it. Photographing the spacecraft against known stars gives a direction and no distance. Timing a radio pulse out and back gives a distance and no direction. The pitch of the returning signal says how fast it is coming or going, and nothing about sideways motion. And rates come from repeating: two positions give a speed, two speeds give a change in speed.",
        "rebuttals": [
          "Direction is an angle, and the star camera is the only instrument here that measures one.",
          "Motion toward us or away shows up in the pitch of what comes back, and nowhere else.",
          "A distance is a speed multiplied by a time, which is what the round trip gives you.",
          "Rates come from repeating. Two positions give a speed, and two speeds give a change."
        ],
        "scenarios": [
          "Which direction it lies in.",
          "How fast it is coming toward us.",
          "How far away it is.",
          "Whether its speed is changing."
        ],
        "choices": [
          "Photograph it against stars whose places are already known.",
          "Compare the pitch coming back with the pitch sent out.",
          "Time a radio pulse out to it and back again.",
          "Measure the same thing twice, and subtract."
        ],
        "mapping": [
          0,
          1,
          2,
          3
        ],
        "columns": [
          "What we want to know",
          "How we measure it"
        ]
      },
      "assumes": [
        "saying where something is and how it is moving takes more than one number"
      ]
    },
    {
      "day": 2,
      "title": "Rebuild where it is",
      "scene": "The computer restarted and lost its bearings. A distance, two angles and a pitch trace remain, recorded on different clocks. The next tracking pass will test whatever the room reconstructs.",
      "takeaway": "A useful answer predicts the next measurement, and says how sure it is.",
      "place": "Guidance Room",
      "story": "The computer restarted and lost its bearings. A distance, two angles and a pitch trace remain, recorded on different clocks. The next tracking pass will test whatever the room reconstructs.",
      "game": {
        "type": "SEQUENCE",
        "title": "Rebuild where it is",
        "setup": "Guidance Room",
        "play": "Put the four steps in order.",
        "task": "Put the four steps in order.",
        "question": "Put the four steps in order.",
        "answer": "",
        "why": "Everything goes onto one map and one clock first, or a tidy answer comes out wrong in a way nobody can see. The distance, the angles and the pitch then get fitted together. Each pins down something different, and fitted apart they give three answers. What the fit misses is read for pattern rather than size. A pattern is a force nobody allowed for. Then it is carried forward to the burn.",
        "rebuttals": [
          "One map and one clock first. Two clocks in one fit is the mistake that never shows up afterwards.",
          "Fit all three together second. Fitted separately they give three answers and no way to choose.",
          "Read the misses third, for pattern rather than size. A pattern is a force nobody modelled.",
          "Carry it forward last. The burn happens later than the measurements, and the doubt grows on the way."
        ],
        "cards": [
          "Put every measurement on one map and one clock.",
          "Fit one path to the distance, the angles and the pitch.",
          "Look at what the fit misses, and why.",
          "Carry the answer, and its range, to the burn."
        ],
        "order": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "measurements only combine when they are on the same map and the same clock"
      ]
    },
    {
      "day": 3,
      "title": "What holds it in the curve",
      "scene": "The return path swings the spacecraft round the Moon at two and a half thousand kilometres up. Somebody on the loop has asked why it does not simply fall onto the surface.",
      "takeaway": "An orbit is falling, with enough sideways speed that the ground keeps curving away.",
      "place": "Guidance Computer Room",
      "story": "The return path swings the spacecraft round the Moon at two and a half thousand kilometres up. Somebody on the loop has asked why it does not simply fall onto the surface.",
      "game": {
        "type": "CHOICE",
        "title": "What holds it in the curve",
        "setup": "Guidance Computer Room",
        "play": "Say why the spacecraft needs speed to stay in that path.",
        "task": "Say why the spacecraft needs speed to stay in that path.",
        "question": "Why does the spacecraft need any speed at all to stay in that path?",
        "answer": "It is falling the whole way round. Its sideways speed means the surface curves away as fast as it drops.",
        "why": "It is falling. It has been falling the whole way round. What stops it arriving is sideways speed: while gravity pulls it down, it moves along, and the Moon's surface curves away underneath at about the same rate. Too slow and the path meets the ground. Too fast and it swings out and away. Nothing is holding it up, which is exactly why the crew float. Falling and floating are the same thing here.",
        "rebuttals": [
          "There is no outward force. The spacecraft is being pulled inward the whole time, which is what bends the path.",
          "Speed does not weaken gravity. It changes the shape of the path that gravity produces.",
          "There is no air out there to push against, and the engine is off for nearly all of it."
        ],
        "choices": [
          "Its sideways speed turns constant falling into a curve around the Moon.",
          "An outward force balances gravity, so nothing is pulling it anywhere.",
          "Its speed weakens the Moon's pull on it.",
          "Its forward motion holds it up, like a wing."
        ],
        "correctChoice": "Its sideways speed turns constant falling into a curve around the Moon."
      },
      "assumes": [
        "something moving in a circle is being pulled toward the middle, even at a steady speed"
      ]
    },
    {
      "day": 4,
      "title": "Turning effect from a thruster",
      "scene": "A thruster pushes with two hundred newtons, three metres out from the middle of the spacecraft. The crew needs the turning effect before it can predict how fast the turn starts.",
      "takeaway": "Where a push is applied matters as much as how hard it pushes.",
      "place": "Guidance Console",
      "story": "A thruster pushes with two hundred newtons, three metres out from the middle of the spacecraft. The crew needs the turning effect before it can predict how fast the turn starts.",
      "game": {
        "type": "BALLPARK",
        "title": "Turning effect from a thruster",
        "setup": "Guidance Console",
        "play": "Work out the turning effect of the thruster.",
        "task": "Work out the turning effect of the thruster.",
        "question": "How much turning effect does the thruster give?",
        "answer": "Six hundred. Two hundred newtons pushing three metres out from the middle.",
        "why": "Turning effect is the push multiplied by how far out it acts. Two hundred newtons, three metres from the middle, is six hundred. Move the same thruster in to half the distance and the turning effect halves, with the same fuel burnt. That is why the crew care which pair fires. They cannot make the thruster stronger, and they can choose one that acts further out, and it is exactly the same amount of fuel either way.",
        "givens": [],
        "relationship": "Turning effect = the push × how far out it acts.",
        "calcKey": "NAV-4"
      },
      "assumes": [
        "the same push further from the middle turns something harder"
      ]
    },
    {
      "day": 5,
      "title": "Really off course, or one bad clock?",
      "scene": "Several ground measurements suddenly put the spacecraft ahead of where it should be. They agree with each other. A star camera and the clock records are both available.",
      "takeaway": "When measurements agree, ask whether they agree separately or share a part.",
      "place": "Global Tracking Network",
      "story": "Several ground measurements suddenly put the spacecraft ahead of where it should be. They agree with each other. A star camera and the clock records are both available.",
      "game": {
        "type": "TRACE",
        "title": "Really off course, or one bad clock?",
        "setup": "Global Tracking Network",
        "play": "Say which explanation fits all four checks.",
        "task": "Say which explanation fits all four checks.",
        "question": "Which measurements moved on their own, and which moved together?",
        "answer": "One shared clock. The measurements that moved all use it, and the star camera, which does not, still agrees with the prediction.",
        "why": "Agreement counts only when the things agreeing could have failed apart. These measurements all use the same ground clock, so one clock error moves them together. The star camera does not use that clock, and it still matches the prediction. Nothing pushed the spacecraft, and the onboard readings show no push either. Redo the sums with the corrected clock and nearly all the error disappears. Several agreeing numbers turned out to be one fault.",
        "rebuttals": [
          "Moving off course needs a push, and the onboard readings show no push at all.",
          "Separate failures do not drift the same way at the same moment. These share a clock.",
          "A failed star camera would put its answer in the wrong place. It is the one that agrees with the prediction."
        ],
        "trace": {
          "channels": [
            {
              "id": "range",
              "label": "Range measurement",
              "reading": "puts it ahead",
              "depends": [
                "path",
                "ground_clock"
              ]
            },
            {
              "id": "doppler",
              "label": "Doppler measurement",
              "reading": "puts it ahead",
              "depends": [
                "path",
                "ground_clock"
              ]
            },
            {
              "id": "reprocessed",
              "label": "The same data, re-timed",
              "reading": "puts it ahead",
              "depends": [
                "path",
                "ground_clock"
              ]
            },
            {
              "id": "star",
              "label": "Star camera",
              "reading": "matches the prediction",
              "depends": [
                "path",
                "star_field"
              ]
            },
            {
              "id": "onboard",
              "label": "Onboard motion sensors",
              "reading": "no push at all",
              "depends": [
                "onboard"
              ]
            }
          ],
          "resources": [
            {
              "id": "path",
              "label": "Where the spacecraft actually is"
            },
            {
              "id": "ground_clock",
              "label": "The ground clock"
            },
            {
              "id": "star_field",
              "label": "The stars"
            },
            {
              "id": "onboard",
              "label": "The spacecraft's own sensors"
            }
          ],
          "independent": [
            "star",
            "onboard"
          ],
          "target": "ground_clock",
          "hint": "Open each measurement to see what it is built from. Keep the ones that do not pass through the suspect clock.",
          "commit": "Correct it"
        }
      },
      "assumes": [
        "several instruments can be wrong together if they share a part"
      ]
    },
    {
      "day": 6,
      "title": "How much room is left",
      "scene": "The entry corridor is forty kilometres wide. The circle of doubt around the spacecraft's position is ten kilometres across. Sandoval needs a margin before the burn is called.",
      "takeaway": "A route is planned against the doubt, not against the line drawn through the middle of it.",
      "place": "Navigation Covariance Room",
      "story": "The entry corridor is forty kilometres wide. The circle of doubt around the spacecraft's position is ten kilometres across. Sandoval needs a margin before the burn is called.",
      "game": {
        "type": "BALLPARK",
        "title": "How much room is left",
        "setup": "Navigation Covariance Room",
        "play": "Work out how much clear space is left either side.",
        "task": "Work out how much clear space is left either side.",
        "question": "How much clear space is left on each side, if it flies down the middle?",
        "answer": "Fifteen kilometres each side. Twenty from the middle of the corridor, less five for how far off the spacecraft might be.",
        "why": "The corridor is forty kilometres wide, so aiming down the middle puts twenty either side. The spacecraft could be five kilometres off in any direction, so five of those twenty are already spent before anybody makes a mistake. Fifteen is what is left. That is the number the burn is judged against, and it is why the doubt has to be drawn at the same scale as the corridor rather than mentioned in a footnote.",
        "givens": [],
        "relationship": "Margin = (corridor − doubt) ÷ 2.",
        "calcKey": "NAV-6"
      },
      "assumes": [
        "a position is the middle of a circle of doubt, not a fact"
      ]
    },
    {
      "day": 7,
      "title": "What the review should fix",
      "scene": "The crew is aboard the recovery ship and the review board meets Monday. Four proposals compete for three funded places.",
      "takeaway": "Fixing what caused it outlasts getting better at coping with it.",
      "place": "Entry Tracking Network",
      "story": "The crew is aboard the recovery ship and the review board meets Monday. Four proposals compete for three funded places.",
      "game": {
        "type": "CHOICE",
        "title": "What the review should fix",
        "setup": "Entry Tracking Network",
        "play": "Say which proposal removes the cause rather than improving the response.",
        "task": "Say which proposal removes the cause rather than improving the response.",
        "question": "Which proposal deserves first place, because it removes the cause?",
        "answer": "Remove the shared parts. Everything else on the list helps people cope with the same failure rather than preventing it.",
        "why": "The same weakness appeared twice on this flight. Three pressure readings shared one circuit, and later several tracking numbers shared one clock. Both times, agreement looked far stronger than it was, and both times somebody nearly acted on it. Removing those shared parts is the only proposal that stops it happening again. Keeping better records and rehearsing more both help people cope with it, which is a different and smaller thing.",
        "rebuttals": [
          "Keeping the records is how anybody reconstructs it afterwards, and it leaves the shared parts exactly where they are.",
          "Rehearsing improves how people handle the same failure. It does not stop the shared clock failing again.",
          "More people can diagnose it faster, and the shared part is still there to fail."
        ],
        "choices": [
          "Redesign the shared circuits and shared clocks, so agreement means something.",
          "Keep the full records of telemetry, settings and decisions.",
          "Improve the simulator, and rehearse failures more.",
          "Put more people on the anomaly desk for future flights."
        ],
        "correctChoice": "Redesign the shared circuits and shared clocks, so agreement means something."
      },
      "assumes": [
        "a fix that removes a cause outlasts a fix that improves the response"
      ]
    }
  ],
  "ELEC": [
    {
      "day": 1,
      "title": "How long can the battery last?",
      "scene": "The fuel cells are gone, and the crew is on the entry batteries days earlier than any plan allowed. The flight doctor, who watches the crew's health from the ground, wants a number of hours before the next decision about switching things off.",
      "takeaway": "An amount divided by a rate is a time, and that time is what every other decision gets argued against.",
      "place": "Electrical Systems Room",
      "story": "The fuel cells are gone, and the crew is on the entry batteries days earlier than any plan allowed. The flight doctor, who watches the crew's health from the ground, wants a number of hours before the next decision about switching things off.",
      "game": {
        "type": "BALLPARK",
        "title": "How long can the battery last?",
        "setup": "Electrical Systems Room",
        "play": "Turn the store and the draw into hours.",
        "task": "Turn the store and the draw into hours.",
        "question": "How long will the batteries last?",
        "answer": "About six hours, if the draw stays flat. It is a rough number, and everything today gets argued against it.",
        "why": "There is a store and there is a draw, and dividing one by the other gives hours. Eighteen kilowatt hours at three kilowatts is six hours. It is an ideal figure. It assumes the draw stays flat and that every last bit of the store is usable, and neither is quite true. A cold battery gives less than its label. It is still the number every argument this shift is measured against, so it is worth having early and worth calling rough.",
        "givens": [],
        "relationship": "Hours = what is in the store ÷ how fast it is being used.",
        "calcKey": "ELEC-1"
      },
      "assumes": [
        "a store is an amount, and a draw is how fast it is being used"
      ],
      "equations": [
        {
          "e": "how long = amount ÷ rate",
          "c": "how long a store lasts",
          "v": [
            [
              "how long",
              "in hours"
            ],
            [
              "amount",
              "what is in the store"
            ],
            [
              "rate",
              "how fast it is being used"
            ]
          ],
          "s": "A store divided by the rate it is being drawn at gives the hours before it is empty.",
          "computed": true
        }
      ]
    }
  ],
  "THERM": [
    {
      "day": 1,
      "title": "How much does the cabin cool?",
      "scene": "With most things switched off, the cabin is losing about a kilowatt more heat than it makes. The flight doctor wants to know how long the crew has before the cold becomes a medical problem.",
      "takeaway": "Big things change temperature slowly, and that slowness is time to think.",
      "place": "Thermal Control Lab",
      "story": "With most things switched off, the cabin is losing about a kilowatt more heat than it makes. The flight doctor wants to know how long the crew has before the cold becomes a medical problem.",
      "game": {
        "type": "BALLPARK",
        "title": "How much does the cabin cool?",
        "setup": "Thermal Control Lab",
        "play": "Work out how far the temperature falls in three hours.",
        "task": "Work out how far the temperature falls in three hours.",
        "question": "How far does the cabin cool over three hours?",
        "answer": "Under one degree. The cabin is heavy, so a kilowatt leaking for three hours barely moves it.",
        "why": "A kilowatt is a thousand joules leaking away every second. Three hours is about eleven thousand seconds, so the cabin loses roughly 11 million joules. That sounds enormous. It is not, because the cabin and everything in it is heavy, and heavy things take about 12 million joules to shift by a single degree. That is the useful part. The cold is real and it is slow, so the crew has hours rather than minutes. The same fact is why warming it back up later costs so much.",
        "givens": [],
        "relationship": "Degrees lost = energy lost ÷ energy needed for one degree.",
        "calcKey": "THERM-1"
      },
      "assumes": [
        "it takes energy to warm something up, and the same energy leaves as it cools"
      ],
      "equations": [
        {
          "e": "degrees lost = energy lost ÷ energy for one degree",
          "c": "how far something cools",
          "v": [
            [
              "degrees lost",
              "in °C"
            ],
            [
              "energy lost",
              "in joules"
            ],
            [
              "energy for one degree",
              "in joules"
            ]
          ],
          "s": "Heavy things need a lot of energy per degree, which is why they cool slowly.",
          "computed": true
        }
      ]
    },
    {
      "day": 2,
      "title": "How the heat is getting out",
      "scene": "The cabin is cooling and the crew wants to do something about it. What they can do depends on how the heat is actually leaving, so the room names the route first.",
      "takeaway": "Naming the route is what tells you which fix would work at all.",
      "place": "Cabin Environment Console",
      "story": "The cabin is cooling and the crew wants to do something about it. What they can do depends on how the heat is actually leaving, so the room names the route first.",
      "game": {
        "type": "PROTOCOL",
        "title": "How the heat is getting out",
        "setup": "Cabin Environment Console",
        "play": "Match each thing happening in the cabin to how the heat is moving.",
        "task": "Match each thing happening in the cabin to how the heat is moving.",
        "question": "Match each thing happening in the cabin to how the heat is moving.",
        "answer": "",
        "why": "Heat leaves three ways, and each has a different fix. By touching, which needs contact and is short range. By riding on moving air, which is why circulation spreads warmth about. And by beaming straight across a gap, which needs nothing in between and works fine in vacuum. A metal strut running out to the cold structure is the worst kind, because it touches all the way and never stops. Insulation, circulation and shiny surfaces each work on a different one.",
        "rebuttals": [
          "People in contact pass heat by touching. It is short range and it needs contact.",
          "Air carrying warmth about the cabin is heat riding on something moving, rather than passing through it.",
          "A cold wall soaking up warmth from across the cabin is heat beaming across a gap. It needs nothing in between.",
          "A metal strut to the outside conducts all the way out, and it never stops. That is the leak that runs all night."
        ],
        "scenarios": [
          "The crew huddle together.",
          "Moving air carries warmth round the cabin.",
          "A cold wall soaks up warmth from everything facing it.",
          "A metal strut runs out to the structure outside."
        ],
        "choices": [
          "Heat moving by touching.",
          "Heat riding on moving air.",
          "Heat beaming across a gap.",
          "Heat conducted straight out along metal."
        ],
        "mapping": [
          0,
          1,
          2,
          3
        ],
        "columns": [
          "What is happening in the cabin",
          "How the heat is moving"
        ]
      },
      "assumes": [
        "heat moves by touching, by riding on moving air, or by beaming across a gap"
      ],
      "equations": [
        {
          "e": "how long = amount ÷ rate",
          "c": "how long a store lasts",
          "v": [
            [
              "how long",
              "in hours"
            ],
            [
              "amount",
              "what is in the store"
            ],
            [
              "rate",
              "how fast it is being used"
            ]
          ],
          "s": "A store divided by the rate it is being drawn at gives the hours before it is empty."
        }
      ]
    },
    {
      "day": 3,
      "title": "How much they breathe out",
      "scene": "Three crew, each breathing out about twenty litres of carbon dioxide an hour. The workshop needs to know what a home-made scrubber has to keep up with over the next six hours.",
      "takeaway": "The rate something arrives at sets the smallest rate that can remove it.",
      "place": "Cabin Air Console",
      "story": "Three crew, each breathing out about twenty litres of carbon dioxide an hour. The workshop needs to know what a home-made scrubber has to keep up with over the next six hours.",
      "game": {
        "type": "BALLPARK",
        "title": "How much they breathe out",
        "setup": "Cabin Air Console",
        "play": "Work out how much carbon dioxide the crew makes in six hours.",
        "task": "Work out how much carbon dioxide the crew makes in six hours.",
        "question": "How much carbon dioxide do they make in six hours?",
        "answer": "About 360 litres. Sixty litres an hour between the three of them, for six hours.",
        "why": "Three people at twenty litres an hour make sixty litres an hour between them. Six hours of that is three hundred and sixty. That number is the bar. Anything that removes carbon dioxide more slowly than the crew makes it does not hold the level steady. It only makes the rise slower. The workshop does not need this precise. It needs to know whether what they can build is big enough to matter at all.",
        "givens": [],
        "relationship": "Total = what one person makes an hour × how many people × how many hours.",
        "calcKey": "THERM-3"
      },
      "assumes": [
        "a rate multiplied by a time gives a total"
      ]
    }
  ],
  "COMMS": [
    {
      "day": 1,
      "title": "Why did the signal fade?",
      "scene": "Voice and data have gone weak at two ground stations at once. A ground station is a dish antenna on Earth, and these two are on opposite sides of the world. The spacecraft's transmitter is putting out what it should. Three things can be swapped without risking anything.",
      "takeaway": "A cause is proved when the effect follows the change both ways.",
      "place": "Deep-Space Antenna",
      "story": "Voice and data have gone weak at two ground stations at once. A ground station is a dish antenna on Earth, and these two are on opposite sides of the world. The spacecraft's transmitter is putting out what it should. Three things can be swapped without risking anything.",
      "game": {
        "type": "CONTROL",
        "title": "Why did the signal fade?",
        "setup": "Deep-Space Antenna",
        "play": "Change one thing at a time, and put it back, until the fade follows something.",
        "task": "Change one thing at a time, and put it back, until the fade follows something.",
        "question": "Which change makes the fade appear and disappear?",
        "answer": "Where the antenna is pointing. Correcting it brings the signal back, and putting the error back makes it fade again. Neither swap changes anything.",
        "why": "Several things can weaken a radio link, and only one test settles which. Swap to a different ground receiver and nothing changes, so it is not one receiver. Swap the transmitter chain and nothing changes, so it is not the transmitter. Correct where the antenna is pointing and almost all the missing signal comes back. Point it wrong again and the fade returns. Following the change in both directions is what makes it a cause rather than a coincidence.",
        "control": {
          "observable": {
            "label": "received power db relative",
            "unit": ""
          },
          "variables": [
            {
              "id": "receiver_path",
              "label": "Ground receiver path"
            },
            {
              "id": "tx_chain",
              "label": "Spacecraft transmitter chain"
            },
            {
              "id": "pointing",
              "label": "Antenna pointing correction"
            }
          ],
          "held": [],
          "truth": "pointing",
          "baseline": -12,
          "response": 11,
          "noise": 0.2,
          "hint": "Run one reversible test at a time. A cause has to produce a response larger than the noise and reproduce that response when the change is reversed.",
          "run": "Run the measurement",
          "commit": "Name it"
        }
      },
      "assumes": [
        "a fair test changes one thing and leaves the rest alone"
      ]
    },
    {
      "day": 2,
      "title": "How long is one wave",
      "scene": "The link is fading, and the antenna team needs the length of one wave for its pointing model. The spacecraft transmits two billion waves a second.",
      "takeaway": "How long a wave is decides how fussy the aiming has to be.",
      "place": "Communications Analysis Room",
      "story": "The link is fading, and the antenna team needs the length of one wave for its pointing model. The spacecraft transmits two billion waves a second.",
      "game": {
        "type": "BALLPARK",
        "title": "How long is one wave",
        "setup": "Communications Analysis Room",
        "play": "Work out how long one wave of the radio signal is.",
        "task": "Work out how long one wave of the radio signal is.",
        "question": "How long is one wave?",
        "answer": "About fifteen centimetres. That short a wave makes a narrow beam, which is why the aiming has to be so exact.",
        "why": "Radio covers three hundred million metres in a second. In that same second, two billion waves go past. So one wave is that distance shared between them, which is about fifteen centimetres. The number matters because the dish sends its signal in a beam. Short waves make a narrow beam. A narrow beam reaches further, and it has to be aimed far more carefully.",
        "givens": [],
        "relationship": "Length of one wave = how far it travels in a second ÷ how many waves fit in that second.",
        "calcKey": "COMMS-2"
      },
      "assumes": [
        "radio travels at a fixed speed, three hundred million metres every second"
      ],
      "equations": [
        {
          "e": "length of one wave = how far it goes in a second ÷ waves in a second",
          "c": "how long one radio wave is",
          "v": [
            [
              "length of one wave",
              "in metres"
            ],
            [
              "how far it goes in a second",
              "in metres"
            ],
            [
              "waves in a second",
              "how many"
            ]
          ],
          "s": "Short waves make a narrow beam, which is why the aiming has to be exact.",
          "computed": true
        }
      ]
    }
  ],
  "STRUCT": [
    {
      "day": 1,
      "title": "How a spacecraft turns",
      "scene": "The guidance computer is out and the crew is about to fly by hand. Before anybody touches a thruster, the room says plainly what each change does.",
      "takeaway": "Turning follows the same rules as moving. It is just harder to see them.",
      "place": "Attitude Dynamics Lab",
      "story": "The guidance computer is out and the crew is about to fly by hand. Before anybody touches a thruster, the room says plainly what each change does.",
      "game": {
        "type": "PROTOCOL",
        "title": "How a spacecraft turns",
        "setup": "Attitude Dynamics Lab",
        "play": "Match each change to what it does to the turning.",
        "task": "Match each change to what it does to the turning.",
        "question": "Match each change to what it does to the turning.",
        "answer": "",
        "why": "Four rules cover every hand-flown turn. The same push further from the middle turns harder, which is the one the crew can actually choose. The same push on a heavier, more spread-out craft turns it more slowly, and stops it more slowly too. A push one way and an equal push back cancels out, which is what starting and stopping a turn actually is. And moving things about inside changes nothing overall, because nothing inside can push on the outside.",
        "rebuttals": [
          "The same push further out has more leverage, and it is the term the crew can actually choose.",
          "The same push on something harder to turn gives less turning. Harder to start, and just as hard to stop.",
          "Equal pushes for equal times cancel out. That is exactly what a start pulse and a stop pulse are.",
          "Moving mass inside shifts the turning about between parts, and it cannot change the total."
        ],
        "scenarios": [
          "The same push, further from the middle.",
          "The same push, on a craft that is harder to turn.",
          "An equal push one way, then the other, for equal times.",
          "Moving things about inside, with nothing pushing from outside."
        ],
        "choices": [
          "It turns harder.",
          "It turns more slowly.",
          "The turning cancels out, and it ends up as it started.",
          "The total turning cannot change, however things move inside."
        ],
        "mapping": [
          0,
          1,
          2,
          3
        ],
        "columns": [
          "What you change",
          "What happens to the turning"
        ]
      },
      "assumes": [
        "a push off to one side is what makes something start or stop turning"
      ]
    },
    {
      "day": 2,
      "title": "Get the link back",
      "scene": "The signal is weak and drifting. The crew is answering calls it can barely hear. The next navigation update depends on getting the link back.",
      "takeaway": "Do the biggest and cheapest thing first, and let each move buy the next.",
      "place": "Spacecraft Attitude Console",
      "story": "The signal is weak and drifting. The crew is answering calls it can barely hear. The next navigation update depends on getting the link back.",
      "game": {
        "type": "SEQUENCE",
        "title": "Get the link back",
        "setup": "Spacecraft Attitude Console",
        "play": "Put the four moves in order.",
        "task": "Put the four moves in order.",
        "question": "Put the four moves in order.",
        "answer": "",
        "why": "Pointing is the biggest thing on the list and the cheapest to fix, so it goes first. Slowing the message down comes next. Less is being sent, so less signal is needed to read it, and nothing aboard has to change. Then the big ground dishes get told where to listen, because the signal has drifted. What comes back feeds the navigation the burn needs.",
        "rebuttals": [
          "Pointing first. It is the biggest term in the sum, and the cheapest one to fix.",
          "Slowing the message down second. A slower message needs less signal, and it costs nothing aboard.",
          "The big dishes third, told where to listen, because the signal has drifted in frequency.",
          "Navigation last. Getting the link back also produces the measurements the burn needs."
        ],
        "cards": [
          "Check where the spacecraft is pointing.",
          "Slow the message down, and listen over a narrower range.",
          "Point the big ground dishes, and tell them where to listen.",
          "Feed the tracking that comes back into the navigation."
        ],
        "order": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "a slower message needs less signal to be read"
      ]
    },
    {
      "day": 3,
      "title": "How far to stay clear",
      "scene": "The bad band runs from three thousand one hundred to three thousand three hundred turns a minute. The rule is to stay two hundred clear of it, and the pump still has to run.",
      "takeaway": "Avoiding a resonance is arithmetic on the band, not a matter of running gently.",
      "place": "Spacecraft Vibration Console",
      "story": "The bad band runs from three thousand one hundred to three thousand three hundred turns a minute. The rule is to stay two hundred clear of it, and the pump still has to run.",
      "game": {
        "type": "BALLPARK",
        "title": "How far to stay clear",
        "setup": "Spacecraft Vibration Console",
        "play": "Work out the highest speed that is safely below the bad band.",
        "task": "Work out the highest speed that is safely below the bad band.",
        "question": "What is the highest speed that is safely below the band?",
        "answer": "Two thousand nine hundred turns a minute. The band starts at 3,100, and the rule is 200 clear of it.",
        "why": "A resonance is a band rather than a point, and a margin either side of it is what stops the pump wandering back in. The band starts at three thousand one hundred. Two hundred clear of that is two thousand nine hundred, and that is the fastest the pump can safely run below it. Running slower is fine. Running anywhere between three thousand one hundred and three thousand three hundred is not, and neither is sitting just outside and drifting.",
        "givens": [],
        "relationship": "Highest safe speed = the bottom of the band − the clearance.",
        "calcKey": "STRUCT-3"
      },
      "assumes": [
        "a shaking problem has a band of speeds, with room either side"
      ]
    }
  ],
  "INTEG": [
    {
      "day": 1,
      "title": "The spacecraft, or the sensors?",
      "scene": "Nine minutes after the bang, three cabin pressure readings fall in the same second. Cabin pressure is how hard the air inside is pushing on the walls, and it drops when air leaks out. The dial gauge beside them, which is a needle on a spring rather than anything electrical, has not moved.",
      "takeaway": "Three readings that fall together are one event. What they share is where to look first.",
      "place": "Mission Control",
      "story": "Nine minutes after the bang, three cabin pressure readings fall in the same second. Cabin pressure is how hard the air inside is pushing on the walls, and it drops when air leaks out. The dial gauge beside them, which is a needle on a spring rather than anything electrical, has not moved.",
      "game": {
        "type": "CHOICE",
        "title": "The spacecraft, or the sensors?",
        "setup": "Mission Control",
        "play": "Say what could make three readings fall in the same second.",
        "task": "Say what could make three readings fall in the same second.",
        "question": "What could make all three readings fall in the same second?",
        "answer": "One thing all three share — the circuit that powers them. A real leak would move the dial gauge too.",
        "why": "Three holes appearing in the same second is not a thing that happens. One fault behind all three is. So the question becomes what those three have in common, and the answer is the circuit they all run off. There is a check available, and it is the dial gauge. It measures the same cabin a completely different way, through a spring rather than through wires, and it has not moved. The leak listener hears nothing either. Together they say the cabin is fine and the wiring is not.",
        "rebuttals": [
          "Three holes in the same second is not a thing that happens.",
          "A valve would move the dial gauge as well, and it has not moved.",
          "The dial gauge is the one that disagrees, and it is the one working."
        ],
        "choices": [
          "The circuit that all three run off",
          "Three separate holes in the cabin wall",
          "The crew opening a valve somewhere",
          "The dial gauge being read wrongly"
        ],
        "correctChoice": "The circuit that all three run off"
      },
      "assumes": [
        "several instruments can run off one shared circuit"
      ]
    },
    {
      "day": 2,
      "title": "Build the first picture",
      "scene": "Three consoles hold numbers that disagree. One of the two main power lines reads zero. The guidance computer, which keeps track of where the spacecraft is and which way it points, has restarted with no memory of what it saw. Nothing has been written down yet.",
      "takeaway": "An answer built to survive being wrong has to be built in a particular order.",
      "place": "Telemetry Analysis Room",
      "story": "Three consoles hold numbers that disagree. One of the two main power lines reads zero. The guidance computer, which keeps track of where the spacecraft is and which way it points, has restarted with no memory of what it saw. Nothing has been written down yet.",
      "game": {
        "type": "SEQUENCE",
        "title": "Build the first picture",
        "setup": "Telemetry Analysis Room",
        "play": "Put the four steps in the order they have to happen.",
        "task": "Put the four steps in the order they have to happen.",
        "question": "Put the four steps in the order they have to happen.",
        "answer": "",
        "why": "The recordings from across the failure get wiped within minutes, so they are saved before anything is worked out. Units and clocks come next. A tidy answer built from mixed clocks is confidently wrong. Then the estimates, each with a range rather than one number. A number with no range cannot be argued with. And the only commands worth sending are the ones that help whatever turns out to be true.",
        "rebuttals": [
          "Save the recordings first. It is the only step with a deadline set by a machine rather than by people.",
          "Units and clocks second. This is where one shared fault shows up, instead of being fitted into the answer.",
          "Estimates third, each with a range. A single number cannot be argued with or tested.",
          "Commands last, and only the ones that survive every answer the data still allows."
        ],
        "cards": [
          "Save the recordings from before and after the failure.",
          "Check the units, the clocks, and what everything depends on.",
          "Work out where it is and how fast, with a range.",
          "Send only the commands that help either way."
        ],
        "order": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "a number without its units and its time is not a measurement"
      ]
    },
    {
      "day": 3,
      "title": "The reading that cannot wait",
      "scene": "Four screens are showing four problems at once. Camila Reyes wants to know which one the room should watch while the tracking pass — the few minutes when a dish on Earth can measure the spacecraft — comes round.",
      "takeaway": "Air runs out in minutes. Warmth and power run out in hours, so the air is watched first.",
      "place": "Spacecraft Systems Console",
      "story": "Four screens are showing four problems at once. Camila Reyes wants to know which one the room should watch while the tracking pass — the few minutes when a dish on Earth can measure the spacecraft — comes round.",
      "game": {
        "type": "CHOICE",
        "title": "The reading that cannot wait",
        "setup": "Spacecraft Systems Console",
        "play": "Say which reading the room watches first.",
        "task": "Say which reading the room watches first.",
        "question": "Which reading tells you soonest whether the crew is in danger?",
        "answer": "Cabin pressure. A leak empties the cabin in minutes, and nothing else on the board moves that fast.",
        "why": "All four readings matter. What separates them is how fast each one runs out. Air is the quick one. A hole in the wall of a spacecraft empties the cabin in minutes, and there is no warning after that. The batteries have hours left in them. The cabin cools slowly, because heat leaks out through the walls rather than pouring out of a hole. So the flight director watches the pressure while the other three are still being counted. The order is set by the clock on each one, not by which number looks worst.",
        "rebuttals": [
          "Voltage matters, but the batteries have hours in them. Air does not.",
          "The cabin cools over hours. A leak empties it in minutes.",
          "A lost radio is frightening and not fatal. The crew can still fly."
        ],
        "choices": [
          "Cabin pressure",
          "Battery voltage",
          "Cabin temperature",
          "Radio signal strength"
        ],
        "correctChoice": "Cabin pressure"
      },
      "assumes": [
        "people need air, warmth and power, and they need them on different clocks"
      ]
    },
    {
      "day": 4,
      "title": "Turning it by hand",
      "scene": "The guidance computer is off. The crew has to turn the spacecraft ninety degrees using two thruster pairs and a mark on the window. Every extra correction spends fuel meant for the return.",
      "takeaway": "Stopping the push does not stop the motion, so the braking has to start early.",
      "place": "Crew Procedures Room",
      "story": "The guidance computer is off. The crew has to turn the spacecraft ninety degrees using two thruster pairs and a mark on the window. Every extra correction spends fuel meant for the return.",
      "game": {
        "type": "FLY",
        "title": "Turning it by hand",
        "setup": "Crew Procedures Room",
        "play": "Choose the opening pulse and where to start braking, then run the turn.",
        "task": "Choose the opening pulse and where to start braking, then run the turn.",
        "question": "How hard do you start the turn, and where do you start braking so it arrives still?",
        "answer": "Brake before the target. A six-second pulse gets it turning at twelve degrees a second, which takes about thirty-six degrees to stop, so braking starts near fifty-four.",
        "why": "A thruster pulse does not make a turn that stops itself. It changes how fast the spacecraft is turning, and when the pulse ends it keeps going at that rate. Stopping needs the opposite thruster, and that takes just as long as starting did. So the braking has to begin before the target, by about the angle the starting pulse used up. Brake at the target and it sails past. The turn only works if the angle and the turning both reach zero together.",
        "fly": {
          "state": {
            "label": "Attitude",
            "unit": "",
            "init": 0
          },
          "rate": {
            "label": "Rate",
            "unit": ""
          },
          "accel": 2,
          "pulse": {
            "min": 4,
            "max": 8,
            "step": 2,
            "unit": "s"
          },
          "brake": {
            "min": 35,
            "max": 90,
            "step": 1,
            "unit": ""
          },
          "pulseLabel": "Pulse each way",
          "brakeLabel": "Begin braking at",
          "target": 90,
          "tolerance": 3,
          "rateTolerance": 1,
          "budget": 16,
          "hint": "Pick a start-pulse duration, then set the angle where the opposite thruster begins firing. The run ends only when the vehicle has stopped rotating.",
          "run": "Run it",
          "commit": "Report the attitude"
        }
      },
      "assumes": [
        "a push changes how fast something turns",
        "it keeps turning after the thruster stops"
      ],
      "equations": [
        {
          "e": "speed = distance ÷ time",
          "c": "how fast something is travelling",
          "v": [
            [
              "speed",
              "in kilometres per second"
            ],
            [
              "distance",
              "in kilometres"
            ],
            [
              "time",
              "in seconds"
            ]
          ],
          "s": "Speed is how much ground is covered divided by how long it took."
        }
      ]
    },
    {
      "day": 5,
      "title": "Why is the voltage sagging?",
      "scene": "A main power line is sagging at twenty-four volts instead of twenty-eight, while the current drawn from it sits where it was planned to be. Engineers want to start pulling equipment off.",
      "takeaway": "Voltage, current and heat are three views of one fault, and one view is not enough.",
      "place": "Spacecraft Load Panel",
      "story": "A main power line is sagging at twenty-four volts instead of twenty-eight, while the current drawn from it sits where it was planned to be. Engineers want to start pulling equipment off.",
      "game": {
        "type": "CHOICE",
        "title": "Why is the voltage sagging?",
        "setup": "Spacecraft Load Panel",
        "play": "Say which fault fits the voltage, the current and the heat together.",
        "task": "Say which fault fits the voltage, the current and the heat together.",
        "question": "Which fault fits the voltage, the current and the heat?",
        "answer": "A bad connection in the path. It eats voltage on the way through and turns it into heat, which is why the joint is warm.",
        "why": "Three readings, one fault, and each says something different. Something extra drawing power would show up as more current than planned. The current is where it should be. A failed supply would show as less coming in, and what comes in is normal. What is left is something in the path resisting. It eats voltage going past and turns it into heat.",
        "rebuttals": [
          "Something extra drawing power would show as more current than planned, and the current is where it should be.",
          "A failed supply would show as less coming in. What is coming in is normal, so the fault is further along.",
          "A bad voltmeter explains the reading and not the hot joint or the extra battery current. Two instruments agree."
        ],
        "choices": [
          {
            "label": "A bad connection somewhere in the path.",
            "mechanism": "A resisting joint drops the voltage past it, and turns what it drops into heat."
          },
          {
            "label": "Something extra drawing power that nobody knows about.",
            "mechanism": "An unexpected device pulls extra current and drags the bus down."
          },
          {
            "label": "The supply itself has failed.",
            "mechanism": "Less is coming in, so the battery has to make up the difference."
          },
          {
            "label": "Only the voltmeter is wrong.",
            "mechanism": "The bus is fine, and only one instrument is telling a story."
          }
        ],
        "correctChoice": "A bad connection somewhere in the path."
      },
      "assumes": [
        "current pushing through something that resists it drops the voltage and makes heat"
      ]
    },
    {
      "day": 6,
      "title": "Switch things off without losing the mission",
      "scene": "Forty-one amp-hours left, and sixty-two hours to fly. An amp-hour is one hour of giving one amp, so forty-one of them is not much. Guidance, radio, heating and life support all want power. Something has to be turned down within minutes.",
      "takeaway": "A power budget is not a ranking of what matters. It is hours multiplied by draw, and the total is fixed.",
      "place": "Mission Planning Desk",
      "story": "Forty-one amp-hours left, and sixty-two hours to fly. An amp-hour is one hour of giving one amp, so forty-one of them is not much. Guidance, radio, heating and life support all want power. Something has to be turned down within minutes.",
      "game": {
        "type": "ALLOCATE",
        "title": "Switch things off without losing the mission",
        "setup": "Mission Planning Desk",
        "play": "Share out the amp-hours, and keep every needed condition met.",
        "task": "Share out the amp-hours, and keep every needed condition met.",
        "question": "How many hours of each can the spacecraft afford?",
        "answer": "Buy life support for the whole return. Book the guidance windows. Keep enough heating to protect the batteries. What is left pays for short radio windows.",
        "why": "This is not a list of what matters most. It is a sum. Every load costs its draw multiplied by the hours it runs, and the total cannot pass forty-one. Life support runs the whole way, so it is bought first. Guidance is needed in fixed windows, so those get booked. Heating can be switched on and off, and not removed, because a cold battery gives less back.",
        "allocate": {
          "pool": {
            "amount": 41,
            "unit": "Ah",
            "mode": "scalar"
          },
          "items": [
            {
              "id": "life",
              "label": "Life support and circulation",
              "cost": 24.8
            },
            {
              "id": "thermal",
              "label": "Thermal survival loads",
              "cost": 6.6
            },
            {
              "id": "guidance",
              "label": "Guidance and navigation windows",
              "cost": 7.2
            },
            {
              "id": "comms",
              "label": "High-bandwidth communications",
              "cost": 55.8
            }
          ],
          "answers": [
            {
              "question": "Keep crew and critical batteries within survival limits",
              "requires": [
                "life",
                "thermal"
              ],
              "required": true
            },
            {
              "question": "Power the planned navigation and burn windows",
              "requires": [
                "guidance"
              ],
              "required": true
            },
            {
              "question": "Maintain continuous high-bandwidth communications",
              "requires": [
                "comms"
              ]
            }
          ],
          "hint": "Set runtime for each load. The amp-hour total updates as current times hours, and the mission-condition panel shows what your allocation can still accomplish.",
          "commit": "Commit the plan"
        }
      },
      "assumes": [
        "an amp-hour is a current drawn for an hour",
        "some things can be switched on and off, and some cannot"
      ],
      "equations": [
        {
          "e": "how long = amount ÷ rate",
          "c": "how long a store lasts",
          "v": [
            [
              "how long",
              "in hours"
            ],
            [
              "amount",
              "what is in the store"
            ],
            [
              "rate",
              "how fast it is being used"
            ]
          ],
          "s": "A store divided by the rate it is being drawn at gives the hours before it is empty."
        }
      ]
    },
    {
      "day": 7,
      "title": "Keep the cabin survivable",
      "scene": "The cabin is at four degrees and falling. Water is beading on the walls and the crew is sleeping in their suits. Heating all of it is not affordable on what is left.",
      "takeaway": "Slowing a loss keeps paying. Replacing it has to be paid again every time.",
      "place": "Materials and Insulation Shop",
      "story": "The cabin is at four degrees and falling. Water is beading on the walls and the crew is sleeping in their suits. Heating all of it is not affordable on what is left.",
      "game": {
        "type": "CHOICE",
        "title": "Keep the cabin survivable",
        "setup": "Materials and Insulation Shop",
        "play": "Say what the last of the energy should be spent on.",
        "task": "Say what the last of the energy should be spent on.",
        "question": "Four degrees and falling, on a fixed amount of energy. What do you spend it on?",
        "answer": "Wrap the crew area and the batteries. Slowing the loss keeps paying after the energy is gone; reheating has to be paid for again every time.",
        "why": "There are two ways to fight cold and they cost differently. Replacing heat means paying again the moment you stop. Slowing the loss keeps working after the spending stops, which is what matters when the energy is fixed. So it goes round the crew and round the batteries, where cold does the most damage. Cold batteries also give back less than warm ones, so a heat problem quietly becomes a power problem if nobody attends to it.",
        "rebuttals": [
          "Reheating the whole cabin replaces what has gone and does nothing about the next hour. The same energy gets spent again.",
          "Running the fans evens the temperature out and costs power the whole time, and it does not slow anything leaving.",
          "Protecting the electronics keeps the hardware and lets the crew and the batteries go on cooling."
        ],
        "choices": [
          "Wrap the crew area and the batteries, to slow the loss.",
          "Spend the rest on short bursts of heating the whole cabin.",
          "Run the fans all the time, so everywhere is the same temperature.",
          "Heat the electronics bay, and let the crew rely on their suits."
        ],
        "correctChoice": "Wrap the crew area and the batteries, to slow the loss."
      },
      "assumes": [
        "slowing a loss and replacing it are different things"
      ]
    },
    {
      "day": 8,
      "title": "Follow the air",
      "scene": "Carbon dioxide keeps climbing. The scrubber, which is the machine that takes that gas back out of the air, has a fan that sounds normal and draws its usual current. The airflow through it is low. There are pressure readings on both sides of the filter.",
      "takeaway": "A chain moves at the rate of its most restricted link, not the rate of its noisiest one.",
      "place": "Life-Support Laboratory",
      "story": "Carbon dioxide keeps climbing. The scrubber, which is the machine that takes that gas back out of the air, has a fan that sounds normal and draws its usual current. The airflow through it is low. There are pressure readings on both sides of the filter.",
      "game": {
        "type": "CHAIN",
        "title": "Follow the air",
        "setup": "Life-Support Laboratory",
        "play": "Build the air path in order, then name the link that is holding it up.",
        "task": "Build the air path in order, then name the link that is holding it up.",
        "question": "Where does the air path become the problem?",
        "answer": "The filter. The fan is fine, and almost nothing is getting past that filter, so nothing reaches the scrubber.",
        "why": "The fan makes a push. How much air moves depends on everything downstream of it. Normal current only proves the fan has power. The pressure difference across the filter is large and the flow is small, which is what a blockage looks like. Every breath has to get through that filter before it reaches anything that cleans it. So the loop runs at whatever the filter allows.",
        "chain": {
          "links": [
            {
              "id": "intake",
              "label": "Cabin intake",
              "transfers": "cabin air into the loop"
            },
            {
              "id": "fan",
              "label": "Scrubber fan",
              "transfers": "pressure rise to the moving air"
            },
            {
              "id": "filter",
              "label": "Filter section",
              "transfers": "air through the particulate barrier"
            },
            {
              "id": "sorbent",
              "label": "CO2 sorbent bed",
              "transfers": "carbon dioxide from air into sorbent"
            },
            {
              "id": "return",
              "label": "Return duct",
              "transfers": "treated air back to the cabin"
            }
          ],
          "order": [
            "intake",
            "fan",
            "filter",
            "sorbent",
            "return"
          ],
          "governing": "filter",
          "distractor": "fan",
          "hint": "Put the air-transfer links in physical order. Then use the observed flow and pressure pattern to name the one required link that governs the entire loop.",
          "commit": "Name the governing transfer"
        }
      },
      "assumes": [
        "a motor running does not prove any air is moving",
        "air has to pass through every part of a loop"
      ],
      "equations": [
        {
          "e": "amount = rate × time",
          "c": "how much of a store gets used",
          "v": [
            [
              "amount",
              "amp hours, or litres"
            ],
            [
              "rate",
              "per hour"
            ],
            [
              "time",
              "in hours"
            ]
          ],
          "s": "Anything drawn at a steady rate adds up in proportion to how long it is drawn for."
        }
      ]
    },
    {
      "day": 9,
      "title": "Make the air breathable",
      "scene": "Carbon dioxide is close to the limit and still climbing. The spare canisters are square, the socket is round, and there is tape, a suit hose, a sock and a plastic cover.",
      "takeaway": "Nothing gets cleaned unless it goes through the thing that cleans it.",
      "place": "Crew Hardware Workshop",
      "story": "Carbon dioxide is close to the limit and still climbing. The spare canisters are square, the socket is round, and there is tape, a suit hose, a sock and a plastic cover.",
      "game": {
        "type": "CHOICE",
        "title": "Make the air breathable",
        "setup": "Crew Hardware Workshop",
        "play": "Say what the improvised fix has to get right.",
        "task": "Say what the improvised fix has to get right.",
        "question": "Tape, a hose, a sock and a plastic cover. What does the fix have to get right?",
        "answer": "A sealed path, so the air has nowhere to go but through. A gap round the canister undoes everything else.",
        "why": "Two things have to be true, and only one of them is obvious. There has to be something that takes the carbon dioxide out, and every bit of air has to be made to go through it. Air is lazy. Leave a gap round the canister and most of it goes round instead of through, and comes back into the cabin exactly as it left. A big canister with a gap round it cleans less than a small one taped tight.",
        "rebuttals": [
          "Exposing more of it only helps the air that reaches it. A big canister with a gap round it cleans less than a small one taped tight.",
          "Measuring in several places is how they find out whether it worked. That is necessary and it is not the fix.",
          "A fan they can hear proves a motor is turning. It says nothing about how much air is moving, or where it goes."
        ],
        "choices": [
          "A sealed path, so the air has to go through the canister.",
          "As much of the canister exposed to the cabin as possible.",
          "Readings taken in several places round the cabin.",
          "A fan loud enough that the crew can hear it running."
        ],
        "correctChoice": "A sealed path, so the air has to go through the canister."
      },
      "assumes": [
        "air, like water, goes the easiest way it is offered"
      ]
    },
    {
      "day": 10,
      "title": "What is shaking it?",
      "scene": "A bad vibration only appears when the wheel runs near one speed. Above and below that it dies away. Two sensors on different parts of the structure see the same narrow band.",
      "takeaway": "What matters is not how hard it shakes, but what is shaking it, and how fast.",
      "place": "Structural Dynamics Lab",
      "story": "A bad vibration only appears when the wheel runs near one speed. Above and below that it dies away. Two sensors on different parts of the structure see the same narrow band.",
      "game": {
        "type": "CHOICE",
        "title": "What is shaking it?",
        "setup": "Structural Dynamics Lab",
        "play": "Say which explanation fits how the shaking depends on speed.",
        "task": "Say which explanation fits how the shaking depends on speed.",
        "question": "Which explanation fits the readings?",
        "answer": "The wheel is pushing in time with the structure's own rhythm. That is why it only happens in a narrow band of speed.",
        "why": "Everything has a rhythm it likes to shake at, the way a swing does. Push a swing at any old moment and little happens. Push it in time with itself and it goes higher every push. Here the wheel is the push, and one speed lands in time with the structure's own rhythm. Move off that speed either way and the pushes fall out of step. That is why the vibration has a narrow band rather than growing with speed.",
        "rebuttals": [
          "A loose sensor rattles on its own mount. A second sensor somewhere else sees exactly the same thing.",
          "A single knock does not care what speed the wheel is running at, and nothing recorded an impact.",
          "Breaking up shakes at every speed. This is narrow, repeatable, and it stops when the speed changes."
        ],
        "choices": [
          {
            "label": "The wheel is pushing in time with the structure's own rhythm.",
            "mechanism": "A repeated push lands in time with the structure's rhythm, and the shaking builds."
          },
          {
            "label": "One sensor has come loose and is rattling.",
            "mechanism": "One sensor rattles on its own mount while the structure is quiet."
          },
          {
            "label": "Something hit it once, and this is the after-effect.",
            "mechanism": "A single knock rings the structure, whatever the wheel is doing."
          },
          {
            "label": "The structure is breaking up.",
            "mechanism": "Damage shakes everything, at all speeds and all frequencies."
          }
        ],
        "correctChoice": "The wheel is pushing in time with the structure's own rhythm."
      },
      "assumes": [
        "everything has speeds at which it prefers to shake"
      ]
    },
    {
      "day": 11,
      "title": "Stop the shaking",
      "scene": "A panel shakes whenever the pump runs near one speed, and it has grown worse over three cycles. The pump is needed, and its speed can still be changed from the panel.",
      "takeaway": "Change what is pushing, when you cannot change what is being pushed.",
      "place": "Operations Planning Room",
      "story": "A panel shakes whenever the pump runs near one speed, and it has grown worse over three cycles. The pump is needed, and its speed can still be changed from the panel.",
      "game": {
        "type": "CHOICE",
        "title": "Stop the shaking",
        "setup": "Operations Planning Room",
        "play": "Say which change stops the pushes landing in time.",
        "task": "Say which change stops the pushes landing in time.",
        "question": "Which change stops the pushes landing in time with the panel?",
        "answer": "Move the pump speed off the band. It stops the pushes landing in time, and it can be undone at once.",
        "why": "This kind of shaking needs two things: a structure with a rhythm, and something pushing in time with it. In flight, changing what is pushing is far easier than changing the structure. Moving the pump speed off the band stops the pushes landing in time, and it can be undone in a second. Deadening the panel is the proper permanent fix, and it needs hardware and somebody's hands on it. Running faster through the band assumes it survives the crossing.",
        "rebuttals": [
          "Deadening it bleeds the energy away and is the right permanent fix. It needs hardware, access and somebody's hands on the structure.",
          "Measuring in more places is how you check the fix worked. It is the check rather than the fix.",
          "Getting through quickly assumes the structure survives the crossing, which is exactly what three growing cycles have called into question."
        ],
        "choices": [
          "Move the pump's speed away from the band.",
          "Deaden the panel, so the shaking dies away.",
          "Measure it in a few more places first.",
          "Run the pump harder, to get through the band quickly."
        ],
        "correctChoice": "Move the pump's speed away from the band."
      },
      "assumes": [
        "shaking like this needs a structure and something pushing it in time"
      ]
    },
    {
      "day": 12,
      "title": "Say it before you do it",
      "scene": "The correction burn is ready. It adds 3 metres a second, 12 hours before the spacecraft reaches the air. Carter wants the prediction written down first.",
      "takeaway": "A burn that happened is not a burn that worked. Only the measurement afterwards says so.",
      "place": "Flight Director Console",
      "story": "The correction burn is ready. It adds 3 metres a second, 12 hours before the spacecraft reaches the air. Carter wants the prediction written down first.",
      "game": {
        "type": "VERIFY",
        "title": "Say it before you do it",
        "setup": "Flight Director Console",
        "play": "Predict what the burn will do, fire it, then measure it.",
        "task": "Predict what the burn will do, fire it, then measure it.",
        "question": "Predict how far the burn moves the landing point, fire it, and then measure.",
        "answer": "About 130 kilometres — and only the tracking pass afterwards shows whether it really moved that far.",
        "why": "Three metres every second sounds like nothing. Keep it up for 12 hours and it is a long way. Three metres a second is about 11 kilometres an hour. Eleven, for 12 hours, is roughly 130 kilometres. Say that number out loud first. It is the only thing the tracking pass can be compared against. An engine can run short, point a little wrong, or stop early. None of that shows on the console that told it to fire. The pass afterwards is what turns a burn that happened into a burn that worked.",
        "verify": {
          "prediction": {
            "label": "How far the landing point moves",
            "unit": "km",
            "min": 0,
            "max": 200,
            "step": 5
          },
          "truth": 130,
          "passRatio": [
            0.7,
            1.4
          ],
          "intervention": {
            "label": "The correction burn",
            "note": "3 metres per second, 12 hours before entry.",
            "outcome": "Burn complete. The engine ran for the full nine seconds."
          },
          "measurement": {
            "label": "A tracking pass after the burn",
            "note": "One station, comparing where it is now against where it was going.",
            "cost": 1,
            "costUnit": "passes"
          },
          "hint": "Write the prediction first. It cannot be changed afterwards, which is the whole point of writing it first.",
          "unmeasuredMoral": "The engine fired and nobody looked. A burn that happened is not the same as a burn that worked.",
          "lock": "Lock the prediction",
          "run": "Commit it",
          "measure": "Take the measurement",
          "commit": "Report the correction"
        }
      },
      "assumes": [
        "a speed and a time give a distance",
        "a prediction is only a test if it is made before the result is known"
      ],
      "equations": [
        {
          "e": "change in position = change in speed × time",
          "c": "why an early correction is worth more",
          "v": [
            [
              "change in position",
              "in kilometres"
            ],
            [
              "change in speed",
              "in metres per second"
            ],
            [
              "time",
              "how long it has to act"
            ]
          ],
          "s": "A tiny change in speed moves a spacecraft hardly at all in an hour and a long way in a day."
        }
      ]
    },
    {
      "day": 13,
      "title": "Four minutes of silence",
      "scene": "For four minutes in the middle of entry there is no radio at all. The room knows it is coming, and Carter still wants somebody to say why it happens.",
      "takeaway": "Some silences are physics rather than faults, and nothing on the ground can shorten one.",
      "place": "Integrated Flight Room",
      "story": "For four minutes in the middle of entry there is no radio at all. The room knows it is coming, and Carter still wants somebody to say why it happens.",
      "game": {
        "type": "CHOICE",
        "title": "Four minutes of silence",
        "setup": "Integrated Flight Room",
        "play": "Say why the radio goes quiet.",
        "task": "Say why the radio goes quiet.",
        "question": "Why does the radio go quiet for four minutes?",
        "answer": "The air around the capsule is squeezed until it glows, and glowing air will not let radio through.",
        "why": "The capsule hits the air at enormous speed, and the air in front of it has nowhere to go. Being squeezed that hard makes it hot, hot enough to glow, and that glowing layer wraps the whole capsule. Radio waves cannot get through it. The silence is not a fault and nobody can fix it from the ground. It ends by itself when the capsule has slowed enough for the air to stop glowing, and everything that might need a decision has to be settled before it starts.",
        "rebuttals": [
          "Nothing is switched off. The radio is transmitting the whole time and nothing gets out.",
          "The Moon is far behind them by entry. They are at the Earth.",
          "Nothing breaks. The radio works again by itself once the capsule slows down."
        ],
        "choices": [
          "Glowing hot air wraps the capsule and blocks radio.",
          "The antenna is switched off to save battery.",
          "The capsule is behind the Moon at that point.",
          "The radio is broken by the shaking of entry."
        ],
        "correctChoice": "Glowing hot air wraps the capsule and blocks radio."
      },
      "assumes": [
        "rubbing something hard makes it hot",
        "radio waves travel through air but not through everything"
      ]
    },
    {
      "day": 14,
      "title": "The order the silence forces",
      "scene": "Everything now depends on eleven minutes, and four of them have no radio at all. Anything that needs the ground has to happen before the silence starts.",
      "takeaway": "When part of a plan cannot be changed, everything that might need changing goes before it.",
      "place": "Crew Capsule",
      "story": "Everything now depends on eleven minutes, and four of them have no radio at all. Anything that needs the ground has to happen before the silence starts.",
      "game": {
        "type": "SEQUENCE",
        "title": "The order the silence forces",
        "setup": "Crew Capsule",
        "play": "Put the entry steps in order around the four minutes of silence.",
        "task": "Put the entry steps in order around the four minutes of silence.",
        "question": "Put the entry steps in order around the four minutes of silence.",
        "answer": "",
        "why": "Four minutes of silence sets the whole order. Anything that needs a decision from the ground has to be settled first, because during the silence there is nobody to ask. Who is flying gets agreed before the silence, not during it. Watching the slowing and the heating can only start once entry has begun, so it comes after. And the recording runs throughout, because this flight is the only test the predictions will ever get.",
        "rebuttals": [
          "Attitude and settings first, before entry. Nothing here can be changed through four minutes of silence.",
          "Agree who is flying before committing. That is not something to work out while nobody can talk.",
          "Watching the slowing comes third. It cannot start before entry, because there is nothing to compare yet.",
          "Descent last, with the record kept. This is the only flight that will ever produce this data."
        ],
        "cards": [
          "Set the approved attitude and settings before the silence.",
          "Agree who is flying, before the radio goes quiet.",
          "Watch the slowing and the heating against what was predicted.",
          "Come down, keeping the record of what happened."
        ],
        "order": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "nothing can be fixed from the ground while the radio is quiet"
      ]
    }
  ]
};

export const BALLPARK_CALCS = {
  "NAV-4": {
    "prompt": "The thruster pushes with 200 newtons, at right angles, three metres out from the middle of the spacecraft.",
    "question": "How much turning effect does the thruster give?",
    "labels": [
      "3 m (how far out the thruster is)",
      "200 N (how hard it pushes)",
      "1.5 m (distance to the docking ring)",
      "30,000 kg (what the spacecraft weighs)",
      "0.5 (a half)"
    ],
    "values": [
      3,
      200,
      1.5,
      30000,
      0.5
    ],
    "slots": 2,
    "template": "{0} × {1}",
    "formula": "a*b",
    "correct": [
      0,
      1
    ],
    "target": 600,
    "tolerance": 40,
    "units": "N m",
    "solution": "200 × 3 is 600.",
    "explanation": "The distance has to be measured to the middle of the spacecraft, not to whatever piece of structure is nearest. The mass of the craft decides how fast it then turns, and it is not part of this sum."
  },
  "ELEC-1": {
    "prompt": "The entry batteries hold about 18 kilowatt hours that can actually be used. The things that must stay on draw about 3 kilowatts.",
    "question": "How long will the batteries last?",
    "labels": [
      "18 kWh (what is usable in the batteries)",
      "3 kW (what must stay on)",
      "28 V (the bus voltage)",
      "3.5 kW (the peak draw, briefly)",
      "6 h (time to the next burn)"
    ],
    "values": [
      18,
      3,
      28,
      3.5,
      6
    ],
    "slots": 2,
    "template": "{0} ÷ {1}",
    "formula": "a/b",
    "correct": [
      0,
      1
    ],
    "target": 6,
    "tolerance": 0.4,
    "units": "h",
    "solution": "18 ÷ 3 is 6 hours.",
    "explanation": "The bus voltage says how the energy is delivered, and nothing about how much there is. The time to the next burn is a deadline rather than an ingredient."
  },
  "THERM-1": {
    "prompt": "Over three hours the cabin loses about 11 million joules more than it makes. Warming this cabin by one degree takes about 12 million joules.",
    "question": "How far does the cabin cool over three hours?",
    "labels": [
      "11 million joules (lost in three hours)",
      "12 million joules (to warm it one degree)",
      "4 °C (the cabin now)",
      "3 h (how long)"
    ],
    "values": [
      11,
      12,
      4,
      3
    ],
    "slots": 2,
    "template": "{0} ÷ {1}",
    "formula": "a/b",
    "correct": [
      0,
      1
    ],
    "target": 0.9,
    "tolerance": 0.15,
    "units": "°C",
    "solution": "Eleven million shared out at twelve million for each degree is a bit under one degree.",
    "explanation": "Both numbers are energies, so they divide straight into a number of degrees. The 4 °C is where the cabin is now, not how far it moves, and the three hours are already inside the eleven million."
  },
  "THERM-3": {
    "prompt": "Three crew each breathe out about twenty litres of carbon dioxide an hour, and the scrubber has to keep up for six hours.",
    "question": "How much carbon dioxide do they make in six hours?",
    "labels": [
      "3 (people)",
      "20 L each hour, each person",
      "6 (hours)",
      "24 (hours in a day)",
      "1.0 kg each person each day"
    ],
    "values": [
      3,
      20,
      6,
      24,
      1
    ],
    "slots": 3,
    "template": "{0} × {1} × {2}",
    "formula": "a*b*c",
    "correct": [
      0,
      1,
      2
    ],
    "target": 360,
    "tolerance": 25,
    "units": "L",
    "solution": "3 × 20 × 6 is 360 litres.",
    "explanation": "A rate for one person needs a head count and a stretch of time, and both have to match the question. The daily figure describes the same crew and cannot be used here without more work."
  },
  "COMMS-2": {
    "prompt": "Counted in millions: radio travels 300 million metres each second, and this signal sends 2,000 million waves in that second.",
    "question": "How long is one wave?",
    "labels": [
      "300 (millions of metres travelled each second)",
      "2,000 (millions of waves sent each second)",
      "2 (millions of waves, if it were megahertz)",
      "343 (metres a second, the speed of sound)"
    ],
    "values": [
      300,
      2000,
      2,
      343
    ],
    "slots": 2,
    "template": "{0} ÷ {1}",
    "formula": "a/b",
    "correct": [
      0,
      1
    ],
    "target": 0.15,
    "tolerance": 0.02,
    "units": "m",
    "solution": "300 shared between 2,000 is 0.15, so each wave is fifteen centimetres.",
    "explanation": "Both numbers are counted in millions, so the millions cancel and the answer is in plain metres. Use 2 instead of 2,000 and each wave comes out 150 metres long, which would need an aerial nobody could fly."
  },
  "STRUCT-3": {
    "prompt": "The bad band runs from 3,100 to 3,300 turns a minute. The rule is to stay 200 clear of it.",
    "question": "What is the highest speed that is safely below the band?",
    "labels": [
      "3,100 (bottom of the bad band)",
      "200 (clearance needed)",
      "3,300 (top of the band)",
      "3,200 (the worst point)"
    ],
    "values": [
      3100,
      200,
      3300,
      3200
    ],
    "slots": 2,
    "template": "{0} − {1}",
    "formula": "a-b",
    "correct": [
      0,
      1
    ],
    "target": 2900,
    "tolerance": 50,
    "units": "rpm",
    "solution": "3,100 − 200 is 2,900 turns a minute.",
    "explanation": "Work off the bottom of the band, not the worst point in the middle of it. Using 3,200 puts the pump inside the band it is meant to avoid."
  },
  "NAV-6": {
    "prompt": "The corridor is 40 kilometres wide. The circle of doubt around the position is 10 kilometres across.",
    "question": "How much clear space is left on each side, if it flies down the middle?",
    "labels": [
      "40 km (width of the corridor)",
      "10 km (width of the doubt)",
      "6 km (one of the two errors)"
    ],
    "values": [
      40,
      10,
      6
    ],
    "slots": 2,
    "template": "({0} − {1}) ÷ 2",
    "formula": "(a-b)/2",
    "correct": [
      0,
      1
    ],
    "target": 15,
    "tolerance": 2,
    "units": "km",
    "solution": "Forty take away ten is thirty. Down the middle, that is 15 kilometres on each side.",
    "explanation": "Take the doubt off the corridor first, then split what is left between the two sides. Both are widths, so both belong to the whole corridor rather than to one edge of it."
  }
};

export const JARGON = [
  {
    "name": "Cabin pressure",
    "aliases": [
      "cabin pressure"
    ],
    "def": "How hard the air inside the crew cabin pushes on the walls. It drops when air leaks out, and the crew cannot breathe without it.",
    "core": true
  },
  {
    "name": "Carbon dioxide",
    "aliases": [
      "carbon dioxide"
    ],
    "def": "The gas people breathe out. Outdoors it blows away. In a sealed cabin it builds up, and too much of it makes people muddled and then very ill."
  },
  {
    "name": "Scrubber",
    "aliases": [
      "scrubber",
      "scrubbers"
    ],
    "def": "The machine that takes the carbon dioxide back out of the cabin air. It can only clean air that actually reaches it.",
    "core": true
  },
  {
    "name": "Amp-hour",
    "aliases": [
      "amp-hour",
      "amp-hours"
    ],
    "def": "A way of saying how much a battery holds. One amp-hour is one hour of giving one amp, so a battery of forty can give one amp for forty hours, or two amps for twenty.",
    "core": true
  },
  {
    "name": "Guidance computer",
    "aliases": [
      "guidance computer"
    ],
    "def": "The computer that keeps track of where the spacecraft is, how fast it is going, and which way it is pointing."
  },
  {
    "name": "Tracking pass",
    "aliases": [
      "tracking pass",
      "tracking passes"
    ],
    "def": "The few minutes when the spacecraft passes over a dish on Earth and can be measured. That short window is what a pass is. Between passes nobody on the ground can measure anything."
  },
  {
    "name": "Ground station",
    "aliases": [
      "ground station",
      "ground stations"
    ],
    "def": "A big dish antenna on Earth that talks to the spacecraft and times how long the answer takes."
  },
  {
    "name": "Dial gauge",
    "aliases": [
      "dial gauge"
    ],
    "def": "A gauge with a needle, moved by a spring rather than by wires. It keeps working when the electrics do not, which is why it is worth having."
  },
  {
    "name": "Star camera",
    "aliases": [
      "star camera"
    ],
    "def": "A camera that photographs stars to work out which way the spacecraft is pointing. It uses no clock and no radio, so it can disagree with both."
  },
  {
    "name": "Correction burn",
    "aliases": [
      "correction burn"
    ],
    "def": "A short firing of the engine to nudge the path back where it should be.",
    "core": true
  },
  {
    "name": "Entry corridor",
    "aliases": [
      "entry corridor"
    ],
    "def": "The narrow band of angles the capsule has to come in at. Too steep and it burns up, too shallow and it skips back out."
  },
  {
    "name": "Flight doctor",
    "aliases": [
      "flight doctor"
    ],
    "def": "The doctor who watches the crew's health from the ground, using numbers rather than a stethoscope."
  },
  {
    "name": "Calibration",
    "aliases": [
      "calibration",
      "calibrated",
      "calibrate"
    ],
    "def": "Checking an instrument against something you already know, and writing down how far off it is. Two instruments checked against the same thing can be wrong the same way."
  },
  {
    "name": "Common-mode error",
    "aliases": [
      "common-mode error"
    ],
    "def": "One fault that makes several instruments wrong in the same direction. They agree with each other, and all of them are wrong."
  },
  {
    "name": "Doppler shift",
    "aliases": [
      "doppler shift"
    ],
    "def": "The change in pitch of something moving toward you or away from you. A siren sounds higher coming and lower going, and radio does the same."
  },
  {
    "name": "Parallax",
    "aliases": [
      "parallax"
    ],
    "def": "The way a near thing seems to jump against far things when you move. Hold a finger up and close one eye, then the other."
  },
  {
    "name": "Power",
    "aliases": [
      "power"
    ],
    "def": "How fast energy is being used. A bright lamp uses more power than a dim one."
  },
  {
    "name": "Resonance",
    "aliases": [
      "resonance"
    ],
    "def": "What happens when a push keeps arriving in time with a swing, so the swing gets bigger and bigger. Push at the wrong moment and it dies away instead."
  },
  {
    "name": "Torque",
    "aliases": [
      "torque"
    ],
    "def": "Turning effect. The same push turns something more when it acts further from the middle, which is why a door opens easily at the handle and hardly at all near the hinge."
  },
  {
    "name": "Transponder",
    "aliases": [
      "transponder"
    ],
    "def": "A box on the spacecraft that answers a radio call from Earth. How long the answer takes tells you how far away it is."
  },
  {
    "name": "State vector",
    "aliases": [
      "state vector"
    ],
    "def": "Where something is and how fast it is going, written down together for one moment in time."
  }
];
