// roster.js — the cast, their passages and their questions
// GENERATED by tools/import-book.mjs from planetary_defense_v2.yml
// Hand edits are lost on the next import. Change the book.

export const ROSTER = [
  {
    "id": "chen",
    "name": "Mira Chen",
    "role": "International NEO Response Director",
    "division": "OPS",
    "color": "#3d6f52",
    "bio": "<p>Local officials will act on her statements, while public pressure rewards a definite answer before the evidence warrants one. Protecting uncertainty can make her sound detached from the people who must act.</p>"
  },
  {
    "id": "ortiz",
    "name": "Lena Ortiz",
    "role": "Survey and discovery lead",
    "division": "DISC",
    "color": "#315c78",
    "bio": "<p>Years of work went into her pipeline, and a timing fault could undermine confidence in a discovery that still needs urgent follow-up. A well-tuned pipeline can feel more trustworthy than an inconvenient external timing check.</p>"
  },
  {
    "id": "rowan",
    "name": "Malik Rowan",
    "role": "Orbit-determination lead",
    "division": "ORBIT",
    "color": "#704f88",
    "bio": "<p>His orbit solution determines whom the response team warns; revising it after public planning has begun carries real consequences. A precise modeled covariance can look complete before unmodeled systematics are tested.</p>"
  },
  {
    "id": "vale",
    "name": "Sanaa Vale",
    "role": "Physical-characterization lead",
    "division": "CHAR",
    "color": "#4b775f",
    "bio": "<p>She wants to prevent an action based on the wrong physical body, but every extra observation uses time the response team needs. Waiting for complete characterization can delay a useful bounded answer.</p>"
  },
  {
    "id": "ibarra",
    "name": "Tomás Ibarra",
    "role": "Planetary-radar director",
    "division": "RADAR",
    "color": "#9a741d",
    "bio": "<p>He must use limited radar time well and initially gives the clean main return priority over ambiguous structure. A strong main echo can draw attention away from a weak but repeatable feature.</p>"
  },
  {
    "id": "park",
    "name": "Evelyn Park",
    "role": "Entry-and-consequences lead",
    "division": "IMPACT",
    "color": "#9a3f36",
    "bio": "<p>She must tell emergency managers what harm they may have to prevent before an impact becomes certain. The worst credible outcome can dominate even when actions should scale with changing evidence.</p>"
  },
  {
    "id": "hale",
    "name": "Jordan Hale",
    "role": "division emergency manager for Valle Seco",
    "division": "TOWN",
    "color": "#6b7f8a",
    "bio": "<p>County teams will have to explain changing instructions at roadblocks and transport desks. Changing guidance can feel like breaking trust, even when the evidence changes.</p>"
  },
  {
    "id": "sen",
    "name": "Arjun Sen",
    "role": "Space-intervention and operations lead",
    "division": "IMPACT",
    "color": "#9a3f36",
    "bio": "<p>He has kept the dormant Aegis demonstrator ready for a chance like this and wants that preparation to matter. Available hardware makes intervention feel more valuable than observation before feasibility is tested.</p>"
  }
];

export const LEADERS = [
  {
    "id": "chen",
    "name": "Mira Chen",
    "role": "International NEO Response Director",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "ortiz",
    "name": "Lena Ortiz",
    "role": "Survey and discovery lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "rowan",
    "name": "Malik Rowan",
    "role": "Orbit-determination lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "vale",
    "name": "Sanaa Vale",
    "role": "Physical-characterization lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "ibarra",
    "name": "Tomás Ibarra",
    "role": "Planetary-radar director",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "park",
    "name": "Evelyn Park",
    "role": "Entry-and-consequences lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "chen",
    "name": "Mira Chen",
    "role": "International NEO Response Director",
    "science": 4,
    "management": 4,
    "trait": ""
  }
];

export const AVATARS = {};
