// curriculum.js — lessons per area, the estimate specs and the glossary
// GENERATED by tools/import-book.mjs from midway.yml
// Hand edits are lost on the next import. Change the book.

export const CURRICULUM = {
  "TOWER": [
    {
      "day": 1,
      "title": "What forty-two metres of fall is worth",
      "scene": "The tower drops its carriage forty-two metres before the brake fins begin. Brennan's notebook gives the speed at the bottom as \"about twenty-nine\" and nothing else. Vey wants the line of working under it.",
      "takeaway": "A derivation is a chain of licensed steps, and naming the licence is half of it.",
      "place": "The Drop Tower",
      "story": "The tower drops its carriage forty-two metres before the brake fins begin. Brennan's notebook gives the speed at the bottom as \"about twenty-nine\" and nothing else. Vey wants the line of working under it.",
      "game": {
        "type": "DERIVE",
        "title": "What forty-two metres of fall is worth",
        "setup": "The Drop Tower",
        "play": "Derive the speed at the bottom of the drop",
        "task": "Derive the speed at the bottom of the drop",
        "question": "Get the speed at the end of a forty-two metre free fall, from the constant-acceleration relations rather than from the notebook.",
        "answer": "v = √(2 × 9.8 × 42) ≈ 28.7 m/s, and it is the speed at the moment the fins engage.",
        "why": "Brennan's \"about twenty-nine\" was right, and now it is defensible. The relation v² = v₀² + 2aΔx is the one to reach for when a problem gives a distance and asks for a speed, since it is the only constant-acceleration relation with no time in it. Two things carry the physics: the factor of two, which is where the average speed of an accelerating body lives, and the square, which is why a fall twice as long gives a speed only forty per cent higher.",
        "derive": {
          "start": "v² = v₀² + 2aΔx",
          "goal": "the speed at the bottom of the fall, in metres per second",
          "startNote": "the carriage is released from rest and falls 42 m before the fins engage",
          "rules": [
            "substitution",
            "rearrangement",
            "evaluation",
            "definition"
          ],
          "steps": [
            {
              "ask": "Put the conditions of this drop into the relation.",
              "answer": 0,
              "candidates": [
                {
                  "text": "v² = 0 + 2(9.8)(42)",
                  "rule": "substitution"
                },
                {
                  "text": "v² = 0 + 2(9.8)(42)(2.9)",
                  "rule": "substitution",
                  "why": "The time is already inside the relation; that is what makes it the useful one here. Multiplying by it as well counts the fall twice and leaves units of metres squared per second."
                },
                {
                  "text": "v² = 0 + (9.8)(42)",
                  "rule": "substitution",
                  "why": "The factor of two is what carries the average speed of an accelerating body. Drop it and every step below is clean algebra with a speed twenty-nine per cent low — twenty metres a second, which reads perfectly plausible for a fall of this size.",
                  "survives": true
                },
                {
                  "text": "v = 0 + 2(9.8)(42)",
                  "rule": "substitution",
                  "why": "The relation gives the square of the speed. Reading the left side as v and not v² turns a speed into something eight hundred and twenty-three units large."
                }
              ]
            },
            {
              "ask": "Rearrange for the speed itself.",
              "answer": 1,
              "candidates": [
                {
                  "text": "v = 823 ÷ 2",
                  "rule": "rearrangement",
                  "why": "Halving is not the inverse of squaring. It happens to be the operation that appears in the relation, applied to the wrong side of it."
                },
                {
                  "text": "v = √823",
                  "rule": "rearrangement"
                },
                {
                  "text": "v = 823²",
                  "rule": "rearrangement",
                  "why": "Squaring again moves in the wrong direction. The left-hand side is already a square and has to be undone rather than repeated."
                },
                {
                  "text": "v = √(823) with the sign left open, since the root has two values",
                  "rule": "definition",
                  "why": "Algebraically correct and physically empty: the negative root is the same speed travelling upward, which this carriage is not doing. Carrying it down the page leaves an answer that cannot be reported as a number.",
                  "survives": true
                }
              ]
            },
            {
              "ask": "Evaluate it, and say what the answer is a statement about.",
              "answer": 2,
              "candidates": [
                {
                  "text": "v ≈ 28.7 m/s, the speed of anybody in the carriage",
                  "rule": "evaluation",
                  "why": "The arithmetic is right and the claim is too wide. It is the speed of the carriage and of everything falling with it, which happens to include the riders, and the derivation says nothing about what any of them feel.",
                  "survives": true
                },
                {
                  "text": "v ≈ 41.2 m/s by the time the carriage reaches the bottom of the tower",
                  "rule": "evaluation",
                  "why": "That is the root of 1,700, which is what 2aΔx gives if the drop is taken as the whole tower rather than the free part of it. The fins take the last nine metres."
                },
                {
                  "text": "v ≈ 28.7 m/s, the speed of the carriage where the fins begin",
                  "rule": "evaluation"
                },
                {
                  "text": "v ≈ 28.7 m/s, the average speed over the fall",
                  "rule": "definition",
                  "why": "The average speed of a fall from rest is half the final one, about fourteen. This number is the speed at one instant, which is the instant the brake has to work at."
                }
              ]
            }
          ],
          "hint": "Each line has to follow from the one above it, and the rule you name is part of the answer.",
          "commit": "Commit the derivation"
        }
      },
      "assumes": [
        "an object in free fall accelerates at about 9.8 metres per second every second",
        "the constant-acceleration relations connect speed, acceleration and distance"
      ]
    },
    {
      "day": 2,
      "title": "Nine metres to take back twenty-nine",
      "scene": "The carriage arrives at the fins at 28.7 metres a second and is stationary nine metres later. Santos wants that expressed as an acceleration before anybody argues about whether it is comfortable.",
      "takeaway": "A stopping distance and a speed are enough to fix the acceleration, with no time measured at all.",
      "place": "The Drop Tower",
      "story": "The carriage arrives at the fins at 28.7 metres a second and is stationary nine metres later. Santos wants that expressed as an acceleration before anybody argues about whether it is comfortable.",
      "game": {
        "type": "BALLPARK",
        "title": "Nine metres to take back twenty-nine",
        "setup": "The Drop Tower",
        "play": "Get the deceleration the fins have to produce",
        "task": "Get the deceleration the fins have to produce",
        "question": "Estimate the average deceleration in the braked section.",
        "answer": "",
        "why": "The same relation that gave the speed gives the deceleration when it is run the other way, and neither use needs a stopwatch. Forty-six metres a second every second is four point seven times gravity, which is what the seat has to push through the rider for a fifth of a second. The square is the part worth keeping: a brake run half as long would double the deceleration, and one metre shorter than designed costs more than most people expect.",
        "givens": [],
        "relationship": "a = v² ÷ 2Δx: the deceleration is the entry speed squared divided by twice the distance it is removed over.",
        "calcKey": "TOWER-2"
      },
      "assumes": [
        "the same constant-acceleration relation runs backwards for slowing down",
        "an acceleration can be quoted as a multiple of g"
      ]
    },
    {
      "day": 3,
      "title": "The order a drop test runs in",
      "scene": "Vey wants the tower's annual drop test witnessed rather than described. Santos has four operations written on the whiteboard in the order he happens to have thought of them.",
      "takeaway": "A test is designed backwards from the number it has to produce.",
      "place": "The Drop Tower",
      "story": "Vey wants the tower's annual drop test witnessed rather than described. Santos has four operations written on the whiteboard in the order he happens to have thought of them.",
      "game": {
        "type": "SEQUENCE",
        "title": "The order a drop test runs in",
        "setup": "The Drop Tower",
        "play": "Order the operations for a witnessed drop test.",
        "task": "Order the operations for a witnessed drop test.",
        "question": "Order the operations for a witnessed drop test.",
        "answer": "",
        "why": "Each operation exists because the one after it would mean nothing without it. A logged deceleration is a number about a mass, so the mass is established before anything moves. An instrument that was fitted after the drop has recorded a different drop. The release is at full height because a partial drop tests a brake at a speed it will not meet in service. And the comparison is last because it is the only step that produces the thing the certificate needs, which is a measurement set against a claim.",
        "cards": [
          "Weigh the ballast and record what the carriage will mass on the drop.",
          "Fit the recording accelerometer to the carriage floor and confirm it is logging.",
          "Release from the full height with the ballast aboard and no passengers on site.",
          "Compare the logged deceleration against the figure the certificate will carry."
        ],
        "order": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "a test is only evidence if the conditions are known before it runs",
        "ballast can stand in for passengers"
      ]
    }
  ],
  "COASTER": [
    {
      "day": 1,
      "title": "Reading a circuit as energy",
      "scene": "Marta Kovač walks the track every morning and has the circuit chalked on the workshop wall: lift hill, first drop, loop, brake run. Four points on it, and one statement each.",
      "takeaway": "A ride is one quantity of energy being moved between two forms and quietly spent.",
      "place": "The Coaster",
      "story": "Marta Kovač walks the track every morning and has the circuit chalked on the workshop wall: lift hill, first drop, loop, brake run. Four points on it, and one statement each.",
      "game": {
        "type": "PROTOCOL",
        "title": "Reading a circuit as energy",
        "setup": "The Coaster",
        "play": "Match each point on the circuit to what is true of the train's energy there.",
        "task": "Match each point on the circuit to what is true of the train's energy there.",
        "question": "Match each point on the circuit to what is true of the train's energy there.",
        "answer": "",
        "why": "A circuit like this is one lot of energy handed back and forth. The motor does work once, at the beginning; from the crest onward nothing adds any, and every metre of descent converts store into motion. The foot of the first drop is the fastest point on the whole ride for that reason, and every hill after it has to be lower than the one before. The brake run is the only other place energy crosses the boundary, and it goes out as heat.",
        "scenarios": [
          "The chain is dragging the train up the lift hill.",
          "The train is at the crest, moving slowly.",
          "The train is at the foot of the first drop.",
          "The train is in the brake run at the end."
        ],
        "choices": [
          "A motor is putting energy in, and it is the only place on the circuit where that happens.",
          "Almost all of it is stored in the height, and very little is in the motion.",
          "Almost all of it is in the motion, and this is the fastest the train will be all circuit.",
          "It is being taken out and turned into heat in the fins, and none of it comes back."
        ],
        "mapping": [
          0,
          1,
          2,
          3
        ]
      },
      "assumes": [
        "lifting something stores energy that can be given back",
        "a moving body carries energy that depends on the square of its speed"
      ]
    },
    {
      "day": 2,
      "title": "The lap that does not come back",
      "scene": "The train leaves the crest at 26 metres and reaches the bottom of the first drop two metres above the station. Kovač's wheel says 21.4 metres a second at the bottom, and an ideal circuit says more.",
      "takeaway": "The gap between the ideal speed and the measured one is a measurement of the friction.",
      "place": "The Coaster",
      "story": "The train leaves the crest at 26 metres and reaches the bottom of the first drop two metres above the station. Kovač's wheel says 21.4 metres a second at the bottom, and an ideal circuit says more.",
      "game": {
        "type": "DERIVE",
        "title": "The lap that does not come back",
        "setup": "The Coaster",
        "play": "Derive the speed at the bottom with the losses in it",
        "task": "Derive the speed at the bottom with the losses in it",
        "question": "Work the energy statement down to the speed at the foot of the drop, and say what the measured speed then tells you.",
        "answer": "v₁ = √(2.0² + 2 × 9.8 × 24) ≈ 21.8 m/s ideal against 21.4 measured — about four per cent of the energy gone by the foot of the first drop.",
        "why": "Dividing by the mass is the step worth remembering: it is why the loaded train and the empty one arrive together, and why the answer is a statement about the track rather than about the load. What the comparison buys is a measurement of the friction that no gauge in the park reports. Four per cent by the foot of the drop is ordinary; the number that matters is what has gone by the crown of the loop, because that is where the circuit has the least in hand.",
        "derive": {
          "start": "mgh₀ + ½mv₀² = mgh₁ + ½mv₁² + W_friction",
          "goal": "the speed at the foot of the drop with no losses, and what the measured 21.4 m/s implies",
          "startNote": "h₀ = 26 m, h₁ = 2 m, v₀ = 2.0 m/s at the crest, mass of the loaded train 4,800 kg",
          "rules": [
            "conservation",
            "cancellation",
            "substitution",
            "evaluation"
          ],
          "steps": [
            {
              "ask": "Set the friction term to zero for the ideal case and divide through by the mass.",
              "answer": 1,
              "candidates": [
                {
                  "text": "gh₀ + ½v₀² = gh₁ + ½v₁², so the result depends on the mass of the train",
                  "rule": "cancellation",
                  "why": "The line is right and the conclusion contradicts it. Every term had an m and every m has just been divided out, which is the whole reason a heavy train and a light one reach the bottom together."
                },
                {
                  "text": "gh₀ + ½v₀² = gh₁ + ½v₁²",
                  "rule": "cancellation"
                },
                {
                  "text": "gh₀ + ½v₀² = gh₁ + ½v₁² + W_friction ÷ m",
                  "rule": "cancellation",
                  "why": "Correct algebra for the real circuit, and it is not the ideal case the step asked for. Carried down the page it gives an answer with an unknown in it, and the unknown is the thing this stop is trying to measure.",
                  "survives": true
                },
                {
                  "text": "mgh₀ + ½mv₀² = mgh₁ + ½mv₁², so v₁ = √(2g(h₀ − h₁))",
                  "rule": "conservation",
                  "why": "The final expression drops the starting speed, which is small here and not zero. It is the answer to a train released from rest, and this one is already moving."
                }
              ]
            },
            {
              "ask": "Solve for the ideal speed at the foot.",
              "answer": 0,
              "candidates": [
                {
                  "text": "v₁ = √(v₀² + 2g(h₀ − h₁))",
                  "rule": "substitution"
                },
                {
                  "text": "v₁ = √(2g(h₀ − h₁))",
                  "rule": "substitution",
                  "why": "Valid for a start from rest, and this train enters the drop at two metres a second. It understates the ideal speed by a tenth of a metre a second — small here, and the same omission on a launched circuit is a large error.",
                  "survives": true
                },
                {
                  "text": "v₁ = v₀ + 2g(h₀ − h₁)",
                  "rule": "substitution",
                  "why": "Speeds and squares of speeds cannot be added. The left side is metres a second and the right is metres squared per second squared."
                },
                {
                  "text": "v₁ = √(v₀² + g(h₀ − h₁))",
                  "rule": "conservation",
                  "why": "The half in the kinetic term is what puts a two in front of g when the equation is rearranged. Dropping it loses thirty per cent of the speed."
                }
              ]
            },
            {
              "ask": "Evaluate it and compare with the wheel's 21.4 metres a second.",
              "answer": 2,
              "candidates": [
                {
                  "text": "v₁ ≈ 21.7 m/s, so the measured speed shows the circuit is very nearly ideal",
                  "rule": "evaluation",
                  "why": "The arithmetic drops the starting speed and the difference looks like nothing. Compare energies rather than speeds and the same gap is 130 kilojoules a lap — the square is what makes a small speed difference a large energy one.",
                  "survives": true
                },
                {
                  "text": "v₁ ≈ 23.6 m/s, and the wheel is reading two metres a second low",
                  "rule": "evaluation",
                  "why": "That is the ideal speed for a drop from 26 metres to the ground rather than to the station two metres above it."
                },
                {
                  "text": "v₁ ≈ 21.8 m/s, so friction has taken about 4 per cent of the energy",
                  "rule": "evaluation"
                },
                {
                  "text": "v₁ ≈ 21.8 m/s, so friction has taken about 2 per cent of the energy",
                  "rule": "evaluation",
                  "why": "Two per cent is the shortfall in the speed. Energy goes as the square, so the fraction lost is close to twice the fraction of speed lost, and reporting the smaller one halves the loss the ride actually has."
                }
              ]
            }
          ],
          "hint": "Write the energy statement first, then divide out what cancels. Name the move as well as the line.",
          "commit": "Commit the derivation"
        }
      },
      "assumes": [
        "stored energy is weight times height, and kinetic energy is half the mass times the speed squared",
        "friction does negative work along the whole path"
      ]
    }
  ],
  "CAROUSEL": [
    {
      "day": 1,
      "title": "Going round at a steady speed",
      "scene": "The carousel turns at eight revolutions a minute and has done since Brennan set it. Bisi Adeyemi is wiring a new controller and wants to know what the outer horses are actually being subjected to.",
      "takeaway": "Steady speed on a curve is still acceleration, and it points at the middle.",
      "place": "The Carousel and Swings",
      "story": "The carousel turns at eight revolutions a minute and has done since Brennan set it. Bisi Adeyemi is wiring a new controller and wants to know what the outer horses are actually being subjected to.",
      "game": {
        "type": "CHOICE",
        "title": "Going round at a steady speed",
        "setup": "The Carousel and Swings",
        "play": "Separate the speed from the acceleration",
        "task": "Separate the speed from the acceleration",
        "question": "An outer horse goes round at a constant eight revolutions a minute. What is its acceleration?",
        "answer": "About 4.4 metres per second squared, directed at the centre of the carousel.",
        "why": "Velocity is a direction as well as a size, and on a circle the direction changes every instant even when the size does not. That change is an acceleration, it points at the centre, and its size is the speed squared over the radius: 5.2 metres a second on a 6.2 metre radius gives 4.4, which is about 0.44 g sideways. The force that produces it comes from the platform and the pole, and the rider feels it as being leant outward.",
        "rebuttals": [
          "Constant speed and constant velocity are different claims, and only the first one is true here.",
          "Along the motion is where an acceleration points when a body is speeding up, which this one is not.",
          "Mass sets the force needed and not the acceleration, which comes from the speed and the radius alone."
        ],
        "choices": [
          "About 4.4 metres per second squared, directed at the centre of the carousel.",
          "Zero, since the speed is not changing.",
          "About 4.4 metres per second squared, directed along the way the horse is travelling.",
          "It cannot be found without knowing the mass of the horse and its rider."
        ],
        "correctChoice": "About 4.4 metres per second squared, directed at the centre of the carousel."
      },
      "assumes": [
        "velocity has a direction as well as a size",
        "acceleration is the rate at which velocity changes"
      ]
    },
    {
      "day": 2,
      "title": "Why the chains come out",
      "scene": "The swing carousel turns at ten revolutions a minute. The chains are 4.5 metres long, hung from a hub of radius 3.0 metres, and Brennan's chalk mark on the pole says where the seats reach at full speed.",
      "takeaway": "The angle a hanging chain settles at is set by the turning, and the mass falls out of it entirely.",
      "place": "The Carousel and Swings",
      "story": "The swing carousel turns at ten revolutions a minute. The chains are 4.5 metres long, hung from a hub of radius 3.0 metres, and Brennan's chalk mark on the pole says where the seats reach at full speed.",
      "game": {
        "type": "DERIVE",
        "title": "Why the chains come out",
        "setup": "The Carousel and Swings",
        "play": "Derive the angle the chains hang at",
        "task": "Derive the angle the chains hang at",
        "question": "Work the two force equations down to a relation for the angle, and say what the angle depends on.",
        "answer": "tanθ = v²/(rg), giving about 31° from the vertical at ten turns a minute — and it depends on the speed and the radius, not on who is sitting in the seat.",
        "why": "Dividing the two equations is the move: the tension is unknown, it appears in both, and one division removes it along with the mass. What is left says the angle is fixed by the speed and the radius alone, which is why a ride full of adults and a ride full of children hang their chains identically. The radius has to be solved with the angle, since a seat that swings out travels a wider circle. Brennan's chalk mark reads thirty degrees.",
        "derive": {
          "start": "T sinθ = mv²/r  and  T cosθ = mg",
          "goal": "a relation for θ, and the quantities it turns out to depend on",
          "startNote": "θ is measured from the vertical; r is the radius of the circle the seat travels in",
          "rules": [
            "resolution",
            "division",
            "substitution",
            "evaluation"
          ],
          "steps": [
            {
              "ask": "Divide the horizontal equation by the vertical one.",
              "answer": 2,
              "candidates": [
                {
                  "text": "tanθ = v²/(rg) × m",
                  "rule": "division",
                  "why": "Both sides carried an m and the division removes it. Leaving one in makes the angle depend on the load, which would mean a full seat and an empty one hanging differently on the same ride, and they do not."
                },
                {
                  "text": "sinθ/cosθ = mv²/r ÷ mg, so cotθ = v²/(rg)",
                  "rule": "division",
                  "why": "Sine over cosine is the tangent. Naming it the cotangent inverts the relation and gives an angle of about sixty degrees where the chains hang at thirty."
                },
                {
                  "text": "tanθ = v²/(rg)",
                  "rule": "division"
                },
                {
                  "text": "T tanθ = v²/(rg)",
                  "rule": "division",
                  "why": "The tension divides out along with the mass; keeping it leaves an unknown on the left. The line is algebraically consistent and every step below it produces an angle in terms of a force nobody has measured.",
                  "survives": true
                }
              ]
            },
            {
              "ask": "Say what this angle can depend on, given the relation.",
              "answer": 1,
              "candidates": [
                {
                  "text": "The speed, the radius and the mass of the loaded seat.",
                  "rule": "substitution",
                  "why": "Mass appeared on both sides of the original pair and has gone. This is the same result as a pendulum's period ignoring its bob, and for the same reason."
                },
                {
                  "text": "The speed of the seat and the radius of the circle it travels in.",
                  "rule": "substitution"
                },
                {
                  "text": "The length of the chain and nothing else, since that is what is hanging.",
                  "rule": "resolution",
                  "why": "The chain's length is genuinely in the problem — it sets the radius once the angle is known — but it is not what fixes the angle, and treating it as the only input gives a ride whose chains hang at one angle at every speed.",
                  "survives": true
                },
                {
                  "text": "The tension in the chain, which is what holds the seat out.",
                  "rule": "resolution",
                  "why": "The tension is what does the holding and it is not a free quantity: it adjusts itself to whatever the load and the angle require, which is why it divides out."
                }
              ]
            },
            {
              "ask": "Evaluate the angle at ten turns a minute.",
              "answer": 0,
              "candidates": [
                {
                  "text": "About 31° from the vertical, with the seats out at a radius of 5.3 m",
                  "rule": "evaluation"
                },
                {
                  "text": "About 31° from the horizontal, with the seats well above the hub",
                  "rule": "evaluation",
                  "why": "The angle in these equations is measured from the vertical, since that is the direction the weight acts in. Reading it from the horizontal puts the chains at fifty-nine degrees and the seats far outside anything this ride does."
                },
                {
                  "text": "About 21°, taking the radius as the 3.0 m hub",
                  "rule": "substitution",
                  "why": "Consistent arithmetic on the wrong radius. The seat travels in a circle wider than the hub by however far the chain has swung out, so the radius and the angle have to be solved together — and the answer is ten degrees shy.",
                  "survives": true
                },
                {
                  "text": "About 45°, since the speed and the radius are nearly equal in size",
                  "rule": "evaluation",
                  "why": "Comparing a speed with a length compares two different quantities. The tangent here is v² over rg, which is a pure number, and it is not close to one."
                }
              ]
            }
          ],
          "hint": "Resolve the tension into two directions, write one equation each way, and divide one by the other.",
          "commit": "Commit the derivation"
        }
      },
      "assumes": [
        "a body moving in a circle needs a net force toward the centre",
        "the tension in a chain acts along the chain"
      ]
    },
    {
      "day": 3,
      "title": "What a pole holds sideways",
      "scene": "An outer horse carries a rider of 78 kilograms at 6.2 metres from the middle, going round at eight turns a minute. Adeyemi wants the sideways force the pole is asked for.",
      "takeaway": "The force holding somebody in a circle is a real force from a real part, and it grows with the square of the speed.",
      "place": "The Carousel and Swings",
      "story": "An outer horse carries a rider of 78 kilograms at 6.2 metres from the middle, going round at eight turns a minute. Adeyemi wants the sideways force the pole is asked for.",
      "game": {
        "type": "BALLPARK",
        "title": "What a pole holds sideways",
        "setup": "The Carousel and Swings",
        "play": "Get the sideways force on an outer pole",
        "task": "Get the sideways force on an outer pole",
        "question": "Estimate the sideways force the pole puts on a 78 kg rider.",
        "answer": "",
        "why": "Three hundred and forty newtons is about forty-four per cent of this rider's weight, pushing sideways, and it has to come from somewhere real — the pole, through the saddle, into the rider. Nine turns a minute instead of eight would make it 430 newtons, since the force goes as the square of the speed while the speed goes as the rate of turning. That is the whole of why Brennan's difference between eight and nine was something he could feel.",
        "givens": [],
        "relationship": "F = mv²/r: the force needed to hold a mass on a circle is the mass times the speed squared, divided by the radius.",
        "calcKey": "CAROUSEL-3"
      },
      "assumes": [
        "a body in a circle needs a net force toward the centre",
        "that force is the mass times the centripetal acceleration"
      ]
    }
  ],
  "WHEEL": [
    {
      "day": 1,
      "title": "The number people get wrong",
      "scene": "Jan Novák has a jib out over the wheel's hub with a load on the end of it, and a disagreement with the lifting plan about how big the moment on the pin is.",
      "takeaway": "A turning effect is fixed by where the line of the force passes, not by the shape of the thing carrying it.",
      "place": "The Ferris Wheel",
      "story": "Jan Novák has a jib out over the wheel's hub with a load on the end of it, and a disagreement with the lifting plan about how big the moment on the pin is.",
      "game": {
        "type": "CHOICE",
        "title": "The number people get wrong",
        "setup": "The Ferris Wheel",
        "play": "Identify the distance a torque is actually measured over",
        "task": "Identify the distance a torque is actually measured over",
        "question": "The jib is six metres long and angled up at 30°. Which distance sets the moment about the pin?",
        "answer": "The horizontal distance from the pin to the load's line of action, which is 5.2 metres.",
        "why": "A torque is the force times the perpendicular distance from the pivot to the line the force acts along. The load hangs straight down, so that line is vertical and the perpendicular distance to it is horizontal — six metres times the cosine of thirty, which is 5.2. Raising the jib does not shorten the steel and it does shorten the arm, which is exactly why a crane can lift more with the boom up. Using the length of the member instead overstates this moment by fifteen per cent.",
        "rebuttals": [
          "The steel is six metres of it, and the arm is measured across the force rather than along the member.",
          "The height fixes where the load hangs and has no bearing on a vertical force's arm.",
          "The tracks are not the pivot; the moment being argued about is the one at the pin."
        ],
        "choices": [
          "The horizontal distance from the pin to the load's line of action, which is 5.2 metres.",
          "The length of the jib itself, six metres, since that is the steel carrying the load.",
          "The vertical height the load hangs above the pin, three metres.",
          "The distance along the ground from the crane's tracks to the load."
        ],
        "correctChoice": "The horizontal distance from the pin to the load's line of action, which is 5.2 metres."
      },
      "assumes": [
        "a force applied further from a pivot has a greater turning effect",
        "a force can be drawn as a line extending in both directions"
      ]
    },
    {
      "day": 2,
      "title": "Loading one side of a wheel",
      "scene": "Loading puts passengers into the gondolas at the bottom, six at a time, so for part of every cycle one side of the wheel carries more than the other. Priya Raman wants the worst case on paper.",
      "takeaway": "A wheel is balanced by its own symmetry, and loading is what breaks the symmetry.",
      "place": "The Ferris Wheel",
      "story": "Loading puts passengers into the gondolas at the bottom, six at a time, so for part of every cycle one side of the wheel carries more than the other. Priya Raman wants the worst case on paper.",
      "game": {
        "type": "BALLPARK",
        "title": "Loading one side of a wheel",
        "setup": "The Ferris Wheel",
        "play": "Balance the wheel before it is asked to turn",
        "task": "Balance the wheel before it is asked to turn",
        "question": "Estimate the out-of-balance torque about the axle with four gondolas loaded on one side.",
        "answer": "",
        "why": "A wheel with everything symmetrical needs no torque to hold it, which is why an empty Ferris wheel turns on very little power. Loading four gondolas on one side puts a hundred and seventy-seven kilonewton-metres on the drive and the brake, and the number the drawing gives is for the ride running full, which is the balanced case. The awkward load is not the heaviest one; it is the most lopsided one, and it happens during loading rather than during the ride.",
        "givens": [],
        "relationship": "τ = Fd: the out-of-balance moment is the unbalanced weight times its perpendicular distance from the axle.",
        "calcKey": "WHEEL-2"
      },
      "assumes": [
        "torque is a force times the perpendicular distance from the axle",
        "a torque can be balanced by another torque acting the other way"
      ]
    }
  ],
  "BUMPER": [
    {
      "day": 1,
      "title": "A hundred collisions an hour",
      "scene": "Wei Chen has accelerometers in three cars and four hundred collisions logged from last season. Two cars, one moving and one stopped, and they leave the impact together.",
      "takeaway": "One quantity survives every collision and the other one does not, and knowing which is the whole of the subject.",
      "place": "The Bumper Cars",
      "story": "Wei Chen has accelerometers in three cars and four hundred collisions logged from last season. Two cars, one moving and one stopped, and they leave the impact together.",
      "game": {
        "type": "CHOICE",
        "title": "A hundred collisions an hour",
        "setup": "The Bumper Cars",
        "play": "Count what survives a collision and what does not",
        "task": "Count what survives a collision and what does not",
        "question": "A 320 kg car at 3.1 m/s strikes a stationary 290 kg car and they move off together. What is conserved?",
        "answer": "The momentum, which is the same before and after; the kinetic energy is not.",
        "why": "Momentum is conserved in any collision where nothing outside pushes on the pair, which on a slippery floor over a tenth of a second is a good description. Kinetic energy is a different quantity and it is not protected: this pair leaves at 1.6 metres a second carrying about 810 joules where 1,540 went in, so nearly half of it has gone into deforming rubber, making noise and warming the bumper. That is what an inelastic collision is, and it is what makes the ride bearable.",
        "rebuttals": [
          "A collision that returned all its energy would send the cars apart again, which these do not do.",
          "Kinetic energy is the quantity that goes missing here; nearly half of it does.",
          "The motor pushes through the pickup all the time and does nothing measurable in the tenth of a second the impact lasts."
        ],
        "choices": [
          "The momentum, which is the same before and after; the kinetic energy is not.",
          "Both the momentum and the kinetic energy, since nothing leaves the floor.",
          "The kinetic energy, which is the same before and after; the momentum is not.",
          "Neither, since the floor's motor is putting energy in throughout."
        ],
        "correctChoice": "The momentum, which is the same before and after; the kinetic energy is not."
      },
      "assumes": [
        "momentum is mass times velocity, counted with direction",
        "kinetic energy depends on the square of the speed"
      ]
    }
  ],
  "SHIP": [
    {
      "day": 1,
      "title": "Sixty people and the same five seconds",
      "scene": "Sam Idowu has run the ship for twenty years. He says a full boat and an empty one swing at the same rate, and the console log agrees with him: five point nine seconds either way, all season.",
      "takeaway": "More mass brings more restoring force with it, and the two changes cancel exactly.",
      "place": "The Pirate Ship",
      "story": "Sam Idowu has run the ship for twenty years. He says a full boat and an empty one swing at the same rate, and the console log agrees with him: five point nine seconds either way, all season.",
      "game": {
        "type": "CHOICE",
        "title": "Sixty people and the same five seconds",
        "setup": "The Pirate Ship",
        "play": "Say what the swing's period depends on",
        "task": "Say what the swing's period depends on",
        "question": "Why does the loaded boat swing at the same rate as the empty one?",
        "answer": "Extra mass is pulled back harder in the same proportion, so the acceleration is unchanged.",
        "why": "The force pulling the boat back to the middle is a share of its own weight, so doubling the mass doubles the restoring force. Acceleration is force divided by mass, and both have doubled, so the acceleration at every point of the swing is exactly what it was. The mass cancels out of the problem entirely, which is why a pendulum's period depends on its length and on gravity and on nothing else — and why sixty people change the loads in the bearings without changing the timing by a hundredth of a second.",
        "rebuttals": [
          "Riders sit along the whole boat, and where they sit would matter to the period if mass mattered at all.",
          "The drive gives a push at the end of each swing and does not set the rate the boat returns at.",
          "The log shows five point nine seconds on empty cycles and on full ones separately, not as a mean."
        ],
        "choices": [
          "Extra mass is pulled back harder in the same proportion, so the acceleration is unchanged.",
          "The extra riders sit near the pivot, where they have little effect on the swing.",
          "The drive motor holds the rate constant whatever the boat weighs.",
          "Extra mass does slow it, and five point nine seconds is the average of full and empty."
        ],
        "correctChoice": "Extra mass is pulled back harder in the same proportion, so the acceleration is unchanged."
      },
      "assumes": [
        "a pendulum swings back and forth in a repeating time",
        "a heavier body needs a bigger force to give it the same acceleration"
      ]
    },
    {
      "day": 2,
      "title": "What the swing is worth at the bottom",
      "scene": "The ship swings to 48 degrees on a full cycle. Idowu wants the speed through the bottom before the bearing work is quoted, and the pivot is 8.6 metres above the centre of the loaded boat.",
      "takeaway": "A swing is a fall along a curve, and the height it falls through is the only part that matters.",
      "place": "The Pirate Ship",
      "story": "The ship swings to 48 degrees on a full cycle. Idowu wants the speed through the bottom before the bearing work is quoted, and the pivot is 8.6 metres above the centre of the loaded boat.",
      "game": {
        "type": "BALLPARK",
        "title": "What the swing is worth at the bottom",
        "setup": "The Pirate Ship",
        "play": "Get the speed at the bottom of the swing",
        "task": "Get the speed at the bottom of the swing",
        "question": "Estimate the speed of the boat through the bottom of its swing.",
        "answer": "",
        "why": "A pendulum is a fall down a curved track, and energy does not care about the shape of the path — only about the height. That is the same expression the tower's carriage obeys and the same one the flume's water obeys, which is worth noticing: three rides, three mechanisms, one relation. The height here is not the swing radius but the rise, 8.6 metres times one minus the cosine of forty-eight degrees, which is 2.85.",
        "givens": [],
        "relationship": "v = √(2gh): the speed at the bottom of a swing comes from the height fallen through, whatever path the body took to fall.",
        "calcKey": "SHIP-2"
      },
      "assumes": [
        "stored energy is weight times the height risen",
        "the height risen by a pendulum comes from the geometry of the swing"
      ]
    }
  ],
  "FLUME": [
    {
      "day": 1,
      "title": "What nine metres of water pushes with",
      "scene": "The header tank stands nine point four metres above the splash pool and feeds the top of the flume. Kelechi Abara has a gauge on the outlet pipe and a figure in Brennan's notebook that does not match it.",
      "takeaway": "Depth sets pressure, and the width of the tank has nothing to do with it.",
      "place": "The Log Flume",
      "story": "The header tank stands nine point four metres above the splash pool and feeds the top of the flume. Kelechi Abara has a gauge on the outlet pipe and a figure in Brennan's notebook that does not match it.",
      "game": {
        "type": "BALLPARK",
        "title": "What nine metres of water pushes with",
        "setup": "The Log Flume",
        "play": "Turn the header tank's depth into a pressure",
        "task": "Turn the header tank's depth into a pressure",
        "question": "Estimate the gauge pressure at the bottom of the header tank.",
        "answer": "",
        "why": "Pressure at a depth is the weight of the column standing above one square metre, so it depends on how tall the column is and not how wide. That is why the tank's diameter is absent from the arithmetic and why a hose left up a ladder can burst a fitting. Ninety-two kilopascals is a little under one atmosphere, which means the outlet fitting is holding about nine tonnes over its face — a number worth having before anybody opens it.",
        "givens": [],
        "relationship": "P = ρgh: gauge pressure is the density of the liquid times g times the depth below its surface.",
        "calcKey": "FLUME-1"
      },
      "assumes": [
        "pressure in a liquid grows with depth below the surface",
        "water has a density of about a thousand kilograms per cubic metre"
      ]
    },
    {
      "day": 2,
      "title": "Two centimetres driving nine",
      "scene": "The flume's sluice gate is held by a hydraulic ram. A two-centimetre piston at the hand pump drives a nine-centimetre one at the gate, and Brennan's note against it reads \"plenty\".",
      "takeaway": "A hydraulic multiplies force and gives back exactly nothing, because the big piston moves less.",
      "place": "The Log Flume",
      "story": "The flume's sluice gate is held by a hydraulic ram. A two-centimetre piston at the hand pump drives a nine-centimetre one at the gate, and Brennan's note against it reads \"plenty\".",
      "game": {
        "type": "DERIVE",
        "title": "Two centimetres driving nine",
        "setup": "The Log Flume",
        "play": "Derive what the hydraulic gate multiplies",
        "task": "Derive what the hydraulic gate multiplies",
        "question": "Work Pascal's principle down to the force at the gate, and say what the multiplication costs.",
        "answer": "F₂ = 250 × (9.0/2.0)² ≈ 5,060 N at the gate — and the gate piston travels about a twentieth of the distance the hand piston does.",
        "why": "The step that decides this is the area, not the diameter: doubling a piston's width quadruples its face, so a factor of four and a half in diameter is twenty in force. What the hydraulic gives is force, and what it takes is distance — the two multiply to the same work at both ends, which is why nobody has ever built a hydraulic that produces energy. Brennan's \"plenty\" turns out to be five kilonewtons against a gate that needs about eleven hundred.",
        "derive": {
          "start": "P₁ = P₂",
          "goal": "the force at the gate, and what has been given up to get it",
          "startNote": "hand piston 2.0 cm across, gate piston 9.0 cm across, 250 N applied by hand",
          "rules": [
            "definition",
            "substitution",
            "geometry",
            "evaluation"
          ],
          "steps": [
            {
              "ask": "Write each pressure as a force over its own area.",
              "answer": 0,
              "candidates": [
                {
                  "text": "F₁/A₁ = F₂/A₂, so F₂ = F₁ × (A₂/A₁)",
                  "rule": "definition"
                },
                {
                  "text": "F₁A₁ = F₂A₂, so F₂ = F₁ × (A₁/A₂)",
                  "rule": "definition",
                  "why": "Consistent algebra on an inverted definition. Pressure is force divided by area, not multiplied by it, and this version makes the wide piston the weak one — a ram that would give five newtons at the gate for two hundred and fifty at the hand.",
                  "survives": true
                },
                {
                  "text": "F₁ = F₂, since pressure is passed on undiminished",
                  "rule": "substitution",
                  "why": "What is passed on undiminished is the pressure. The force is the pressure times an area, and the two areas here differ by a factor of twenty."
                },
                {
                  "text": "F₂ = F₁ × (d₂/d₁)",
                  "rule": "geometry",
                  "why": "This uses the diameters where the areas belong. It gives a multiplication of four and a half instead of twenty, which is the same mistake as pricing a pizza by its width."
                }
              ]
            },
            {
              "ask": "Put the areas in, from the diameters given.",
              "answer": 3,
              "candidates": [
                {
                  "text": "A₂/A₁ = 9.0/2.0 = 4.5",
                  "rule": "geometry",
                  "why": "That is the ratio of the diameters. Area grows with the square of the diameter, so the ratio of areas is the square of this."
                },
                {
                  "text": "A₂/A₁ = (9.0² − 2.0²)/2.0² = 19.25",
                  "rule": "geometry",
                  "why": "Subtracting the small area from the large one is the arithmetic for an annulus. These are two separate cylinders and each has its own full circle."
                },
                {
                  "text": "A₂/A₁ = π(9.0)²/π(2.0)², and the π has to be evaluated before dividing",
                  "rule": "evaluation",
                  "why": "Perfectly valid and needlessly so: the π appears above and below and cancels exactly. Evaluating it changes nothing except the number of chances to make an arithmetic slip.",
                  "survives": true
                },
                {
                  "text": "A₂/A₁ = (9.0/2.0)² = 20.25",
                  "rule": "geometry"
                }
              ]
            },
            {
              "ask": "Give the force at the gate and say what it cost.",
              "answer": 1,
              "candidates": [
                {
                  "text": "F₂ ≈ 5,060 N, and the ram delivers that over the same distance the hand moved",
                  "rule": "evaluation",
                  "why": "The force is right and the second half is not. Work cannot be created by plumbing: the gate piston moves about a twentieth as far as the hand piston, which is exactly what keeps the energy books straight.",
                  "survives": true
                },
                {
                  "text": "F₂ ≈ 5,060 N, and the gate piston moves about a twentieth as far",
                  "rule": "evaluation"
                },
                {
                  "text": "F₂ ≈ 1,125 N, from the ratio of the diameters",
                  "rule": "substitution",
                  "why": "This is the diameter ratio again, four and a half times the hand force. It understates the gate force by a factor of four and a half."
                },
                {
                  "text": "F₂ ≈ 5,060 N, so the hand pump does twenty times the work",
                  "rule": "evaluation",
                  "why": "The work at each end is the same, less what the seals take. Twenty times the force over a twentieth of the distance is the same product."
                }
              ]
            }
          ],
          "hint": "Start from the pressures being equal, write each as a force over an area, and remember what an area does when a diameter changes.",
          "commit": "Commit the derivation"
        }
      },
      "assumes": [
        "pressure applied to an enclosed fluid is passed on undiminished",
        "pressure is force divided by the area it acts over"
      ]
    }
  ]
};

export const BALLPARK_CALCS = {
  "TOWER-2": {
    "prompt": "The carriage enters the fins at 28.7 m/s and stops in 9.0 m of travel.",
    "question": "Estimate the average deceleration in the braked section.",
    "labels": [
      "28.7 m/s  (speed entering the fins)",
      "2  (the factor in v² = 2aΔx)",
      "9.0 m  (length of the braked section)",
      "42 m  (the free fall above it)",
      "9.8 m/s²  (g)"
    ],
    "values": [
      28.7,
      2,
      9,
      42,
      9.8
    ],
    "slots": 3,
    "template": "{0} × {0} ÷ ({1} × {2})",
    "formula": "a*a/(b*c)",
    "correct": [
      0,
      1,
      2
    ],
    "target": 45.8,
    "tolerance": 3,
    "units": "m/s²",
    "solution": "a = v² ÷ 2Δx = 28.7² ÷ (2 × 9.0) ≈ 45.8 m/s², which is 4.7 g.",
    "explanation": "The free fall above the fins and the value of g are already inside the entry speed. Using them again counts the same drop twice."
  },
  "FLUME-1": {
    "prompt": "The water in the header tank stands 9.4 m above the outlet. Water is 1,000 kg per cubic metre.",
    "question": "Estimate the gauge pressure at the bottom of the header tank.",
    "labels": [
      "1000 kg/m³  (density of water)",
      "9.8 m/s²  (g)",
      "9.4 m  (depth of water above the outlet)",
      "3.2 m  (diameter of the tank)",
      "0.42 m³/s  (flow through the outlet)"
    ],
    "values": [
      1000,
      9.8,
      9.4,
      3.2,
      0.42
    ],
    "slots": 3,
    "template": "{0} × {1} × {2}",
    "formula": "a*b*c",
    "correct": [
      0,
      1,
      2
    ],
    "target": 92120,
    "tolerance": 4000,
    "units": "Pa",
    "solution": "P = ρgh = 1000 × 9.8 × 9.4 ≈ 92 kPa above atmospheric.",
    "explanation": "The tank's diameter does not appear. A narrow standpipe of the same height pushes just as hard, which is the part people refuse to believe."
  },
  "SHIP-2": {
    "prompt": "The boat rises 2.85 m above its lowest point at 48°. Energy is conserved through the swing.",
    "question": "Estimate the speed of the boat through the bottom of its swing.",
    "labels": [
      "2  (the factor in v = √(2gh))",
      "9.8 m/s²  (g)",
      "2.85 m  (height risen at the top of the swing)",
      "8.6 m  (length from pivot to the boat's centre)",
      "5.9 s  (the period of the swing)"
    ],
    "values": [
      2,
      9.8,
      2.85,
      8.6,
      5.9
    ],
    "slots": 3,
    "template": "√({0} × {1} × {2})",
    "formula": "Math.sqrt(a*b*c)",
    "correct": [
      0,
      1,
      2
    ],
    "target": 7.5,
    "tolerance": 0.6,
    "units": "m/s",
    "solution": "v = √(2 × 9.8 × 2.85) ≈ 7.5 m/s at the bottom.",
    "explanation": "The length and the period fix how long the swing takes and not how fast it goes; the height risen is what becomes speed."
  },
  "WHEEL-2": {
    "prompt": "Four gondolas on one side each carry 470 kg of passengers, at an average perpendicular distance of 9.6 m from the axle.",
    "question": "Estimate the out-of-balance torque about the axle with four gondolas loaded on one side.",
    "labels": [
      "4  (loaded gondolas on one side)",
      "470 kg  (passenger load in each)",
      "9.8 m/s²  (g)",
      "9.6 m  (average perpendicular distance from the axle)",
      "14 m  (radius of the wheel)"
    ],
    "values": [
      4,
      470,
      9.8,
      9.6,
      14
    ],
    "slots": 4,
    "template": "{0} × {1} × {2} × {3}",
    "formula": "a*b*c*d",
    "correct": [
      0,
      1,
      2,
      3
    ],
    "target": 176870,
    "tolerance": 9000,
    "units": "N·m",
    "solution": "τ = 4 × 470 × 9.8 × 9.6 ≈ 177 kN·m about the axle.",
    "explanation": "The wheel's radius is not the arm. A gondola part-way up the wheel hangs on a shorter perpendicular distance, which is why the average is 9.6 and not 14."
  },
  "CAROUSEL-3": {
    "prompt": "The rider sits 6.2 m from the axis and travels at 5.2 m/s. Their mass is 78 kg.",
    "question": "Estimate the sideways force the pole puts on a 78 kg rider.",
    "labels": [
      "78 kg  (mass of the rider)",
      "5.2 m/s  (speed at that radius)",
      "6.2 m  (radius of the circle)",
      "9.8 m/s²  (g)",
      "8  (turns a minute)"
    ],
    "values": [
      78,
      5.2,
      6.2,
      9.8,
      8
    ],
    "slots": 3,
    "template": "{0} × {1} × {1} ÷ {2}",
    "formula": "a*b*b/c",
    "correct": [
      0,
      1,
      2
    ],
    "target": 340,
    "tolerance": 30,
    "units": "N",
    "solution": "F = mv²/r = 78 × 5.2² ÷ 6.2 ≈ 340 N toward the middle.",
    "explanation": "g does not appear: this force is horizontal and the weight is vertical. The turns a minute are already inside the speed."
  }
};

export const JARGON = [
  {
    "name": "Acceleration",
    "aliases": [
      "accelerating",
      "accelerates",
      "decelerate",
      "deceleration"
    ],
    "def": "How fast a velocity is changing, in metres per second every second. Speeding up, slowing down and turning are all acceleration."
  },
  {
    "name": "Free fall",
    "aliases": [
      "falls freely",
      "in free fall"
    ],
    "def": "Motion with gravity as the only force acting. Everything in free fall gains speed at the same rate, whatever it weighs."
  },
  {
    "name": "g",
    "aliases": [
      "gravitational field strength",
      "acceleration due to gravity"
    ],
    "def": "The acceleration of anything in free fall near the ground, about 9.8 metres per second every second."
  },
  {
    "name": "Net force",
    "aliases": [
      "resultant force",
      "unbalanced force",
      "sum of the forces"
    ],
    "def": "What is left when every force on a body is added together with its direction. It is what the mass responds to."
  },
  {
    "name": "Free-body diagram",
    "aliases": [
      "free body diagram"
    ],
    "def": "A sketch of one object with every force acting on it drawn as an arrow, and nothing else on the page."
  },
  {
    "name": "Normal force",
    "aliases": [
      "normal",
      "support force",
      "seat force"
    ],
    "def": "The push a surface gives an object at right angles to itself. It is what a rider actually feels."
  },
  {
    "name": "Apparent weight",
    "aliases": [
      "felt weight",
      "g-force"
    ],
    "def": "The support force a rider feels, divided by their ordinary weight. In free fall it is zero, and nothing about their mass has changed."
  },
  {
    "name": "Friction",
    "aliases": [
      "frictional",
      "kinetic friction",
      "static friction"
    ],
    "def": "The force a surface makes along itself, opposing sliding. Static friction holds until it is exceeded; kinetic friction acts while sliding."
  },
  {
    "name": "Coefficient of friction",
    "aliases": [
      "coefficient",
      "mu"
    ],
    "def": "The ratio of the friction available to the normal force pressing the surfaces together."
  },
  {
    "name": "Centripetal acceleration",
    "aliases": [
      "centripetal",
      "towards the centre"
    ],
    "def": "The acceleration of anything moving in a circle, directed at the centre, equal to the speed squared over the radius."
  },
  {
    "name": "Centripetal force",
    "aliases": [
      "the force towards the centre"
    ],
    "def": "The net force that produces circular motion. It is not a new force; it is whatever is doing the job — a rail, a chain, a seat."
  },
  {
    "name": "Conical pendulum",
    "aliases": [
      "swing chair",
      "hanging chain"
    ],
    "def": "A mass on a chain swung in a horizontal circle, so the chain traces a cone. Its angle depends on speed and radius, not on mass."
  },
  {
    "name": "Work",
    "aliases": [
      "work done"
    ],
    "def": "Force times the distance moved along the force. It is the way energy gets from one place to another."
  },
  {
    "name": "Kinetic energy",
    "aliases": [
      "kinetic"
    ],
    "def": "The energy a moving body has, one half its mass times its speed squared. It goes up with the square, so twice the speed is four times the energy."
  },
  {
    "name": "Potential energy",
    "aliases": [
      "gravitational potential energy",
      "stored energy",
      "height energy"
    ],
    "def": "The energy stored by lifting something, its weight times the height it was lifted."
  },
  {
    "name": "Mechanical energy",
    "aliases": [
      "total energy",
      "energy of the train"
    ],
    "def": "Kinetic and potential added together. Without friction it stays the same all the way round."
  },
  {
    "name": "Work–energy theorem",
    "aliases": [
      "work energy theorem",
      "net work"
    ],
    "def": "The net work done on a body equals the change in its kinetic energy. It is how a force becomes a speed."
  },
  {
    "name": "Power",
    "aliases": [
      "rate of working"
    ],
    "def": "How quickly work is done, in joules a second. A pump's rating is a power, not an energy."
  },
  {
    "name": "Momentum",
    "aliases": [
      "momenta"
    ],
    "def": "Mass times velocity. In a collision the total, counted with direction, is the same before and after."
  },
  {
    "name": "Impulse",
    "aliases": [
      "impulse–momentum",
      "change in momentum"
    ],
    "def": "Force times the time it acts for. It equals the change in momentum, which is why a slower stop is a gentler one."
  },
  {
    "name": "Elastic collision",
    "aliases": [
      "elastic"
    ],
    "def": "A collision that gives back all its kinetic energy. Bumper cars do not."
  },
  {
    "name": "Inelastic collision",
    "aliases": [
      "inelastic",
      "perfectly inelastic"
    ],
    "def": "A collision that keeps some of the kinetic energy as deformation, sound and heat. Momentum is still conserved."
  },
  {
    "name": "Centre of mass",
    "aliases": [
      "center of mass",
      "balance point"
    ],
    "def": "The point a body's weight can be treated as acting through."
  },
  {
    "name": "Torque",
    "aliases": [
      "moment",
      "turning effect"
    ],
    "def": "The turning effect of a force about a point: the force times the perpendicular distance to the line it acts along."
  },
  {
    "name": "Moment arm",
    "aliases": [
      "lever arm",
      "perpendicular distance"
    ],
    "def": "The distance from the pivot to the line of the force, measured at right angles to that line."
  },
  {
    "name": "Static equilibrium",
    "aliases": [
      "balanced",
      "in equilibrium"
    ],
    "def": "Forces adding to zero and torques adding to zero, so nothing moves and nothing turns."
  },
  {
    "name": "Rotational inertia",
    "aliases": [
      "moment of inertia",
      "inertia of a wheel"
    ],
    "def": "How hard it is to change something's spin. It depends on where the mass is, not only how much there is."
  },
  {
    "name": "Angular velocity",
    "aliases": [
      "angular speed",
      "revolutions a minute",
      "rpm"
    ],
    "def": "How fast something turns, in radians a second. Multiply by the radius and you have the speed of a point on it."
  },
  {
    "name": "Angular momentum",
    "aliases": [
      "spin momentum"
    ],
    "def": "Rotational inertia times angular velocity. With no outside torque it stays the same."
  },
  {
    "name": "Simple harmonic motion",
    "aliases": [
      "harmonic",
      "oscillation",
      "oscillates",
      "oscillating"
    ],
    "def": "Motion where the restoring force is proportional to the displacement. It gives a period that does not depend on the size of the swing."
  },
  {
    "name": "Restoring force",
    "aliases": [
      "restoring"
    ],
    "def": "The force that pulls an oscillator back toward the middle, and grows as it gets further away."
  },
  {
    "name": "Period",
    "aliases": [
      "time for one swing",
      "cycle time"
    ],
    "def": "The time for one complete oscillation. For a pendulum it depends on the length and on g, and not on the mass."
  },
  {
    "name": "Frequency",
    "aliases": [
      "frequencies",
      "cycles a second"
    ],
    "def": "How many oscillations happen each second. It is one divided by the period."
  },
  {
    "name": "Resonance",
    "aliases": [
      "resonant",
      "in step with"
    ],
    "def": "Driving an oscillator at its own frequency, so every push arrives in step and the swing keeps growing."
  },
  {
    "name": "Damping",
    "aliases": [
      "damped",
      "damper"
    ],
    "def": "Taking energy out of an oscillation, so the swing dies away instead of building."
  },
  {
    "name": "Amplitude",
    "aliases": [
      "swing angle",
      "size of the swing"
    ],
    "def": "How far an oscillator goes from the middle at the extreme of its motion."
  },
  {
    "name": "Pressure",
    "aliases": [
      "pressures"
    ],
    "def": "Force spread over an area, in pascals. In a liquid it grows with depth and acts in every direction."
  },
  {
    "name": "Density",
    "aliases": [
      "densities"
    ],
    "def": "Mass in each cubic metre. Water is about a thousand kilograms in every cubic metre."
  },
  {
    "name": "Buoyancy",
    "aliases": [
      "buoyant force",
      "upthrust",
      "floats",
      "floating"
    ],
    "def": "The upward force on anything in a fluid, equal to the weight of the fluid it pushes out of the way."
  },
  {
    "name": "Pascal's principle",
    "aliases": [
      "pascals principle",
      "hydraulic"
    ],
    "def": "Pressure applied to an enclosed fluid is passed on undiminished, so a small force on a small piston becomes a large force on a large one."
  },
  {
    "name": "Continuity",
    "aliases": [
      "continuity equation",
      "flow rate"
    ],
    "def": "What goes in has to come out, so a channel that narrows makes the water in it move faster."
  },
  {
    "name": "Safety factor",
    "aliases": [
      "margin",
      "factor of safety"
    ],
    "def": "What a part can take, divided by what it is asked to take. A margin of one is a part that fails at its working load."
  }
];
