// roster.js — the cast, their passages and their questions
// GENERATED by tools/import-book.mjs from groundtruth_v2.yml
// Hand edits are lost on the next import. Change the book.

export const ROSTER = [
  {
    "id": "ortiz",
    "name": "Lena Ortiz",
    "role": "division director; stops a launch while crew-clear lights disagree",
    "division": "SHOT",
    "color": "#3f8f7a",
    "bio": "<p>Her station has already authorized a shot that damaged an outstation; she must defend the next authorization to the crew who will carry it out. An established procedure can feel like independent proof that the station is safe.</p>"
  },
  {
    "id": "ravi",
    "name": "Ravi Sen",
    "role": "division scientist; opens the reference mill while rain reaches the flat",
    "division": "FIELD",
    "color": "#5f7fb8",
    "bio": "<p>He has maintained the mill array and argued that its agreement makes the storm record usable. Agreement among several instruments can hide a shared reference error.</p>"
  },
  {
    "id": "strand",
    "name": "Elise Strand",
    "role": "division impulse engineer; keeps the earthing stick on the Marx bank",
    "division": "BANK",
    "color": "#c2703f",
    "bio": "<p>She is responsible for scarce bank hardware and wants each test to earn enough evidence to justify its cost. Stored energy can dominate her attention while the route that energy takes receives too little weight.</p>"
  },
  {
    "id": "tate",
    "name": "Marcus Tate",
    "role": "division engineer; checks a hot bond rather than defending his drawings",
    "division": "MAST",
    "color": "#8a8f4a",
    "bio": "<p>His drawings guide maintenance of the mast and bonds; an overlooked path would require him to revise work other people trusted. A low-resistance bond can appear harmless when only steady behavior is considered.</p>"
  },
  {
    "id": "noor",
    "name": "Noor Haddad",
    "role": "division data and safety analyst; compares raw timestamps before summaries",
    "division": "SCREEN",
    "color": "#6b7f8a",
    "bio": "<p>They must decide which evidence is sufficient while the storm window and recorder budget are running out. Seeking perfect certainty can delay a useful test after its decision standard could have been fixed.</p>"
  },
  {
    "id": "saira",
    "name": "Saira Malik",
    "role": "division earthing specialist; verifies each bond at the trench",
    "division": "EARTH",
    "color": "#7a6a52",
    "bio": "<p>Crews use the earthing certificate to decide whether they can work; she wants its limits to be as clear as its passing result. A good direct-current resistance result can be mistaken for a complete surge certificate.</p>"
  },
  {
    "id": "owen",
    "name": "Owen Park",
    "role": "division remote-systems engineer; opens the outstation cable bay",
    "division": "COUPLE",
    "color": "#6f5b9a",
    "bio": "<p>He must return the damaged outstation to service and is under pressure to replace its visibly failed cards. A damaged card looks like the source of the failure before the incoming path is traced.</p>"
  }
];

export const LEADERS = [
  {
    "id": "ortiz",
    "name": "Lena Ortiz",
    "role": "division director; stops a launch while crew-clear lights disagree",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "ravi",
    "name": "Ravi Sen",
    "role": "division scientist; opens the reference mill while rain reaches the flat",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "strand",
    "name": "Elise Strand",
    "role": "division impulse engineer; keeps the earthing stick on the Marx bank",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "tate",
    "name": "Marcus Tate",
    "role": "division engineer; checks a hot bond rather than defending his drawings",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "saira",
    "name": "Saira Malik",
    "role": "division earthing specialist; verifies each bond at the trench",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "owen",
    "name": "Owen Park",
    "role": "division remote-systems engineer; opens the outstation cable bay",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "ortiz",
    "name": "Lena Ortiz",
    "role": "division director; stops a launch while crew-clear lights disagree",
    "science": 4,
    "management": 4,
    "trait": ""
  }
];

export const AVATARS = {};
