// roster.js — the cast, their passages and their questions
// GENERATED by tools/import-book.mjs from blackout-ms.yml
// Hand edits are lost on the next import. Change the book.

export const ROSTER = [
  {
    "id": "reyes",
    "name": "Dolores Reyes",
    "role": "Shift Supervisor, System Operations",
    "division": "OPS",
    "color": "#c0392b",
    "bio": "<p>22 years on the desk, 11 of them on nights. She runs the room the way a bridge is run: nobody touches a control without saying out loud what they expect to happen, and then whether it did.</p><p>Her rule is that frequency is the only number on the wall that belongs to everybody. Voltage is local and can be argued about; frequency is the whole interconnection agreeing or failing to agree, and it moves before anything else does.</p><p>Her limit is that she is paid to act before the picture is complete. The operator who waits for certainty is the operator who watches the cascade.</p>",
    "quiz": [
      {
        "q": "Why does Reyes treat frequency differently from voltage?",
        "a": "Frequency is one number for the whole interconnection",
        "wrong": [
          "Voltage instruments are more accurate than frequency instruments during a disturbance",
          "Voltage cannot be measured while the system is swinging",
          "Frequency matters at the generators and nowhere else"
        ]
      }
    ]
  },
  {
    "id": "haddad",
    "name": "Nadia Haddad",
    "role": "Generation Lead",
    "division": "GEN",
    "color": "#d35400",
    "bio": "<p>Came up through turbine commissioning and still walks a machine hall listening rather than reading. She can tell a governor hunting from the sound of it before the trend on the screen has moved.</p><p>What she wants understood is that a generator is a flywheel first and a power source second. The stored rotational energy is what buys the seconds in which anybody gets to make a decision.</p><p>Her limit is ramp rate. A machine that can supply 400 megawatts cannot supply them in the 90 seconds after a trip, and no amount of wanting changes the thermal gradient in a steam drum.</p>",
    "quiz": [
      {
        "q": "Why does Haddad describe a generator as a flywheel first?",
        "a": "Its stored rotational energy slows the frequency change",
        "wrong": [
          "Because a flywheel stores more energy per tonne than a boiler and its steam plant do",
          "Because the turbine and the flywheel are the same component",
          "Because rotational energy costs less per megawatt than fuel"
        ]
      }
    ]
  },
  {
    "id": "novak",
    "name": "Piotr Novak",
    "role": "Protection Engineer",
    "division": "TRANS",
    "color": "#2980b9",
    "bio": "<p>Sets the relays, which means he designs the conditions under which the network is allowed to give up on part of itself. He describes the job as writing the rules for an argument that will happen in 80 milliseconds with nobody present.</p><p>A relay that never trips is not a cautious relay, it is a relay that lets a fault burn. A relay that trips early takes out a healthy line and moves the overload somewhere less convenient. Coordination is the whole discipline.</p><p>His limit is that he is protecting against faults he has to imagine in advance, and the cascade always finds the sequence nobody drew.</p>",
    "quiz": [
      {
        "q": "Why does Novak call a relay setting the rules for an argument nobody attends?",
        "a": "The relay has to decide alone, in milliseconds, from settings written months earlier",
        "wrong": [
          "Relay settings are agreed by a standing committee that never meets in the same room",
          "The argument is between the two ends of a line that cannot talk to each other in time",
          "Nobody is allowed in the yard while protection is live"
        ]
      }
    ]
  },
  {
    "id": "obi",
    "name": "Chinelo Obi",
    "role": "Distribution Lead",
    "division": "DIST",
    "color": "#27ae60",
    "bio": "<p>Runs the feeders, which is where the network acquires customers, trees and opinions. She points out that every elegant thing decided in the control room arrives here as a van, a pole and somebody's evening.</p><p>Her measure of a restoration is not megawatts, it is households and how long they waited, and she will say so in a meeting about megawatts.</p><p>Her limit is that the low-voltage network is only sparsely instrumented. Past the substation she is often reasoning from the shape of the load rather than from a reading.</p>",
    "quiz": [
      {
        "q": "Why does Obi resist reporting restoration purely in megawatts?",
        "a": "A few large customers can dominate the megawatts restored",
        "wrong": [
          "Megawatts restored is a settlement quantity and is not available until afterwards",
          "Household supply is not counted in the system total",
          "Distribution work is measured in amperes rather than in watts"
        ]
      }
    ]
  },
  {
    "id": "lindgren",
    "name": "Sten Lindgren",
    "role": "Load Forecasting Analyst",
    "division": "LOAD",
    "color": "#8e44ad",
    "bio": "<p>Forecasts demand, which he insists is a branch of anthropology conducted with a thermometer. Weather, the television schedule, the school holidays and whether it gets dark before people get home.</p><p>He is precise about what a forecast is: a distribution, not a number. The useful output is the width, because the width is what the reserve has to cover.</p><p>His limit is that the events worth forecasting are rare by construction, so the model is always best calibrated for the days that matter least.</p>",
    "quiz": [
      {
        "q": "What does Lindgren mean by calling forecasting anthropology with a thermometer?",
        "a": "Demand is what people do, and weather is only one of the things that decides it",
        "wrong": [
          "Forecasters interview a panel of households about their heating every winter",
          "The model is built from historical temperature alone",
          "Demand can be predicted from population size and nothing else"
        ]
      }
    ]
  },
  {
    "id": "farrow",
    "name": "June Farrow",
    "role": "Metering and Standards Engineer",
    "division": "METER",
    "color": "#b0762a",
    "bio": "<p>Owns the question nobody wants to open during an incident: is that number the number. Instrument transformers, telemetry lag, clock skew, and the cheerful confidence of a meter reading the wrong side of a saturated core.</p><p>She keeps the traceability chain because after the event there will be an inquiry, and the inquiry will run on the records rather than on anybody's memory of the night.</p><p>Her limit is that she is usually reconstructing rather than observing, and the highest-value seconds are the ones with the worst data.</p>",
    "quiz": [
      {
        "q": "Why does Farrow distrust telemetry during a fast disturbance?",
        "a": "Scan rates and clock skew can put readings in the wrong order",
        "wrong": [
          "Instrument transformers saturate during a fault and stop reporting altogether",
          "Telemetry stops being sent once frequency leaves its band",
          "Digital meters are less accurate than the analogue ones they replaced"
        ]
      }
    ]
  },
  {
    "id": "whitlock",
    "name": "Aaron Whitlock",
    "role": "Assistant Operator",
    "division": "OPS",
    "color": "#c0392b",
    "bio": "<p>Second seat on nights, three years in, and the person who actually keeps the log. Has read every sequence-of-events report the company owns and can quote which ones contradict the official account.</p>",
    "quiz": [
      {
        "q": "Why is the log Whitlock keeps worth more than the reports written afterwards?",
        "a": "It records what the room knew at the time, before anybody knew how it ended",
        "wrong": [
          "It is the only document the regulator is entitled to ask the company for",
          "Reports are written afterwards by people who were not on shift that night",
          "The log records exact times and the reports do not"
        ]
      }
    ]
  },
  {
    "id": "sarraf",
    "name": "Mina Sarraf",
    "role": "Wind Fleet Controller",
    "division": "GEN",
    "color": "#d35400",
    "bio": "<p>Dispatches the ridge fleet from a desk with more forecast on it than telemetry. Explains patiently and often that curtailing a turbine is not waste when the alternative is a line at its thermal limit.</p>",
    "quiz": [
      {
        "q": "Why does Sarraf say curtailing a turbine is not waste?",
        "a": "Energy that cannot reach a customer was never available, whatever the wind was doing",
        "wrong": [
          "Curtailed output is held in storage and released later the same night",
          "The fleet is paid the same under contract whether it runs or not",
          "Turbines last longer when they are not run at full output"
        ]
      }
    ]
  },
  {
    "id": "dube",
    "name": "Thabo Dube",
    "role": "Substation Technician",
    "division": "TRANS",
    "color": "#2980b9",
    "bio": "<p>Does the switching in the yard when the control room asks for it, in the order it is written, reading it back before he touches anything. Has opinions about people who improvise switching sequences.</p>",
    "quiz": [
      {
        "q": "Why does Dube read a switching order back before he touches anything?",
        "a": "Saying it aloud is the one chance to catch a wrong item before it is irreversible",
        "wrong": [
          "The control room records the readback afterwards as proof of who is liable",
          "Reading aloud is required by the radio protocol in the yard",
          "It gives the control room time to cancel the instruction"
        ]
      }
    ]
  },
  {
    "id": "kowalczyk",
    "name": "Ewa Kowalczyk",
    "role": "Field Crew Lead",
    "division": "DIST",
    "color": "#27ae60",
    "bio": "<p>Runs the crew that finds the fault, which is usually a tree, and puts the feeder back. Knows which streets have the hospital, the dialysis clinic and the two houses on home oxygen.</p>",
    "quiz": [
      {
        "q": "Why does Kowalczyk know which streets have the dialysis clinic on them?",
        "a": "Restoration order is decided by what waiting costs, not by how many houses are on the feeder",
        "wrong": [
          "Those streets are required by law to be restored first in every outage",
          "Medical addresses are the only ones the fault-finding system records",
          "Crews are paid a premium for restoring critical premises"
        ]
      }
    ]
  },
  {
    "id": "alvarez",
    "name": "Rafael Alvarez",
    "role": "Demand Analyst",
    "division": "LOAD",
    "color": "#8e44ad",
    "bio": "<p>Builds the load curves and the counterfactuals. Spends the day after an event working out what demand would have been if the event had not happened, which is the number every settlement argument turns on.</p>",
    "quiz": [
      {
        "q": "What is Alvarez's counterfactual demand curve for?",
        "a": "It says what demand would have been without the event, which is what the loss is measured against",
        "wrong": [
          "It predicts what demand will be over the course of the following week",
          "It shows which feeders were restored in which order",
          "It converts megawatts into megawatt-hours for the report"
        ]
      }
    ]
  },
  {
    "id": "bergström",
    "name": "Klara Bergström",
    "role": "Calibration Technician",
    "division": "METER",
    "color": "#b0762a",
    "bio": "<p>Keeps the standards traceable and the calibration records current. The cheerful arbiter of whether a disputed reading is admissible, and immune to being hurried.</p>",
    "quiz": [
      {
        "q": "Why will Bergström not be hurried over a disputed reading?",
        "a": "A reading is only admissible if the instrument's traceability can be shown, and that takes as long as it takes",
        "wrong": [
          "Calibration records can only be updated at the end of an accounting month",
          "She is the only person permitted to touch the standards",
          "A rushed calibration would damage the reference instrument"
        ]
      }
    ]
  }
];

export const LEADERS = [
  {
    "id": "reyes",
    "name": "Dolores Reyes",
    "role": "Shift Supervisor, System Operations",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "haddad",
    "name": "Nadia Haddad",
    "role": "Generation Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "novak",
    "name": "Piotr Novak",
    "role": "Protection Engineer",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "obi",
    "name": "Chinelo Obi",
    "role": "Distribution Lead",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "lindgren",
    "name": "Sten Lindgren",
    "role": "Load Forecasting Analyst",
    "science": 4,
    "management": 4,
    "trait": ""
  },
  {
    "id": "farrow",
    "name": "June Farrow",
    "role": "Metering and Standards Engineer",
    "science": 4,
    "management": 4,
    "trait": ""
  }
];

export const AVATARS = {};
