// syllabus.js — the thirty concepts each game's senior-high course has to cover.
//
// This file is AUTHORED, and it is the only authored thing in the book generator.
// Everything else `tools/make-book.mjs` prints is read out of the game's own
// content; a syllabus cannot be, because it is the claim the content is measured
// against. It says what a senior-high course in the subject must teach, in the
// order such a course usually teaches it, and the book then reports which of its
// own questions teach each item — including the ones nothing teaches.
//
// That last part is the point. A game is not a course, and the gaps are the useful
// output: twenty-five of thirty covered is a syllabus map, thirty of thirty would be
// a suspiciously flattering one.
//
// ## The mapping
//
// `k` is a list of phrases matched against each question's own words — its title,
// scene, the ask, the cards or options, the verdict and the takeaway. Phrases, not
// single words, wherever a single word would be ambiguous: "half-life" is safe,
// "mass" is not, and a concept matched by "rate" alone would collect half the book.
// A phrase matches on word boundaries, so "arc" does not fire inside "arcsecond".
//
// `groups` is optional and narrows a concept to particular areas of study, which is
// the cheapest false-positive control there is: energy in a chemistry game means
// enthalpy, and in an astronomy game it means impact energy.
export const SYLLABUS = {
  // ---------------------------------------------------------------- chemistry
  contamcity: {
    course: 'AP Chemistry, with the analytical half of a first-year college course',
    concepts: [
      { c: 'Atomic structure, ions and electron configuration',
        k: ['electron', 'cation', 'anion', 'oxidation state', 'ionic', 'atomic number'] },
      { c: 'Periodic trends and what an element can do',
        k: ['periodic', 'electronegativity', 'group of the periodic table', 'transition metal'] },
      { c: 'Chemical formulas, naming and composition',
        k: ['chemical formula', 'formula tells', 'nomenclature', 'stoichiometric formula', 'composition'] },
      { c: 'Molecular geometry, polarity and intermolecular forces',
        k: ['polarity', 'polar', 'nonpolar', 'hydrogen bond', 'intermolecular'] },
      { c: 'The mole, molar mass and stoichiometry',
        k: ['mole', 'molar mass', 'stoichiometry', 'balanced equation', 'moles of',
            'mass balance', 'follows the mass', 'conservation of mass'] },
      { c: 'Limiting reactant and percent yield',
        k: ['limiting', 'excess reagent', 'percent yield', 'theoretical yield'] },
      { c: 'Gas laws and the ideal gas equation',
        k: ['ideal gas', 'partial pressure', 'gas law', 'nrt', 'vapour pressure', 'vapor pressure'] },
      { c: 'Kinetic molecular theory, diffusion and volatility',
        k: ['kinetic molecular', 'volatile', 'volatility', 'diffusion', 'headspace'] },
      { c: 'Solutions, molarity and dilution',
        k: ['molarity', 'dilution', 'dilute', 'concentration of the solution', 'aliquot', 'stock solution'] },
      { c: 'Solubility, precipitation and complexation',
        k: ['solubility', 'precipitat', 'complexation', 'complex ion', 'ligand', 'dissolution'] },
      { c: 'Acids, bases and pH',
        k: ['ph!', 'acid', 'alkaline', 'hydroxide', 'protonat'] },
      { c: 'Buffers and titration',
        k: ['buffer', 'titration', 'titrate', 'equivalence point'] },
      { c: 'Equilibrium and Le Chatelier',
        k: ['equilibrium', 'le chatelier', 'equilibrium constant', 'shifts the equilibrium'] },
      { c: 'Reaction kinetics, rate laws and activation energy',
        k: ['rate law', 'reaction rate', 'activation energy', 'arrhenius', 'half-life of the reaction',
            'photochemi', 'formed in sunlight', 'secondary pollutant', 'transformed in the air',
            'secondary product', 'oxidant', 'sunlight'] },
      { c: 'Catalysis',
        k: ['catalys', 'catalyst', 'catalytic'] },
      { c: 'Thermochemistry: enthalpy, calorimetry, energy balance',
        k: ['enthalpy', 'calorimet', 'exotherm', 'endotherm', 'heat of reaction', 'energy balance',
            'heat capacity', 'specific heat', 'absorbed heat', 'temperature rise'] },
      { c: 'Entropy, free energy and spontaneity',
        k: ['entropy', 'free energy', 'spontaneous', 'thermodynamically favour'] },
      { c: 'Redox and electrochemistry',
        k: ['redox', 'oxidis', 'oxidiz', 'reduction', 'electrode', 'corrosion', 'half-cell'] },
      { c: 'Spectroscopy, Beer–Lambert and calibration curves',
        k: ['beer-lambert', 'beer–lambert', 'absorbance', 'spectrum', 'spectroscop', 'calibration curve',
            'chromatograph', 'retention time'] },
      { m: true, c: 'Measurement: significant figures, blanks, detection limits, uncertainty',
        k: ['detection limit', 'blank!', 'blanks', 'uncertainty', 'significant figure', 'replicate',
            'precision', 'systematic error'] },
      { c: 'Separation science: chromatography and extraction',
        k: ['chromatograph', 'extraction', 'separat', 'eluti', 'sorbent'] },
      { c: 'Phase changes, vapour pressure and phase diagrams',
        k: ['phase change', 'boiling point', 'evaporat', 'condens', 'vapour pressure', 'vapor pressure',
            'phase diagram'] },
      { c: 'Colligative properties',
        k: ['colligative', 'freezing point depression', 'boiling point elevation', 'osmotic pressure'] },
      { c: 'Reaction mechanisms and the rate-determining step',
        k: ['mechanism of the reaction', 'rate-determining', 'elementary step', 'intermediate'] },
      { c: 'Solubility product and the common-ion effect',
        k: ['solubility product', 'ksp', 'common-ion', 'saturated solution'] },
      { c: 'Electrolysis and quantitative electrochemistry',
        k: ['electrolysis', 'faraday', 'coulomb', 'current passed', 'plating'] },
      { c: 'Mass spectrometry and molecular mass',
        k: ['mass spectrom', 'mass-to-charge', 'molecular mass', 'fragment ion'] },
      { m: true, c: 'Sampling: representative samples and sample handling',
        k: ['representative sample', 'grab sample', 'composite sample', 'sample handling',
            'hold time', 'preserv', 'sampling design', 'sampling plan', 'survey sample',
            'where to sample', 'what does the survey'] },
      { m: true, c: 'Quality control: standards, spikes and recovery',
        k: ['standard solution', 'spike', 'recovery', 'reference standard', 'duplicate', 'quality control'] },
      { m: true, c: 'Concentration units and conversions: ppm, mg/L, molarity',
        k: ['ppm', 'mg/l', 'parts per million', 'milligrams per litre', 'milligrams per liter',
            'unit conversion'] },
    ],
  },

  // ------------------------------------------------------------ nuclear physics
  projecty: {
    course: 'AP Physics 2 nuclear unit, with the nuclear chemistry of AP Chemistry',
    concepts: [
      { c: 'Nuclear structure: protons, neutrons, isotopes, nuclide notation',
        k: ['nuclide', 'isotope', 'proton', 'neutron number', 'atomic number', 'mass number', 'nucleus', 'nucleon'] },
      { c: 'Mass defect, binding energy and E = mc²',
        k: ['mass defect', 'binding energy', 'rest-mass energy', 'mass-energy'] },
      { c: 'Binding energy per nucleon and the stability curve',
        k: ['binding energy per nucleon', 'curve of binding', 'most stable nuclide'] },
      { c: 'Radioactive decay modes: alpha, beta, gamma',
        k: ['alpha', 'beta decay', 'gamma ray', 'decay mode', 'positron'] },
      { c: 'Decay constant, half-life and activity',
        k: ['half-life', 'decay constant', 'activity of the sample', 'becquerel', 'curie'] },
      { c: 'Exponential decay and logarithms',
        k: ['exponential decay', 'logarithm', 'e-folding', 'exponential in'] },
      { c: 'Fission, neutron multiplication and chain reactions',
        k: ['fission', 'chain reaction', 'multiplication factor', 'neutron balance', 'fissile'] },
      { c: 'Criticality: mass, geometry, reflectors, moderation',
        k: ['critical', 'criticality', 'reflector', 'moderat', 'subcritical', 'supercritical'] },
      { c: 'Fusion',
        k: ['fusion', 'thermonuclear', 'deuterium', 'tritium'] },
      { c: 'Cross sections and mean free path',
        k: ['cross section', 'mean free path', 'barn', 'macroscopic cross'] },
      { c: 'Attenuation of radiation through matter',
        k: ['attenuation', 'attenuate', 'transmitted intensity', 'shielding thickness'] },
      { c: 'Detectors: ionisation, count rate, efficiency, dead time',
        k: ['detector', 'count rate', 'ionisation chamber', 'ionization chamber', 'dead time',
            'detector efficiency', 'pulse height'] },
      { c: 'Counting statistics and uncertainty',
        k: ['counting statistic', 'poisson', 'square root of the count', 'statistical uncertainty'] },
      { c: 'Shielding, dose and radiation protection',
        k: ['dose', 'shield', 'roentgen', 'exposure limit', 'radiation protection'] },
      { c: 'Conservation of energy and momentum in reactions',
        k: ['conservation of energy', 'conservation of momentum', 'momentum is conserved', 'q value'] },
      { c: 'Units and conversions: MeV, u, barns, scientific notation',
        k: ['mev', 'atomic mass unit', 'scientific notation', 'unit conversion', 'order of magnitude'] },
      { m: true, c: 'Order-of-magnitude estimation from givens',
        k: ['estimate', 'approximately', 'ballpark', 'rounded result'] },
      { c: 'Materials: phases, allotropes, alloys, density',
        k: ['allotrop', 'phase transformation', 'alloy', 'density of the metal', 'metallurg', 'polymorph',
            'strength', 'stiffness', 'hardness', 'toughness', 'ductil'] },
      { c: 'Shock waves, compression and hydrodynamics',
        k: ['shock wave', 'compression', 'implosion', 'detonation', 'hydrodynamic'] },
      { m: true, c: 'Experimental method: controls, calibration, systematic vs random error',
        k: ['control experiment', 'calibrat', 'systematic error', 'random error', 'independent measurement',
            'reproducib', 'evidence chain', 'traceab', 'independent benchmark',
            'independent inspection'] },
      { c: 'Isotope separation and enrichment',
        k: ['enrich', 'isotope separation', 'gaseous diffusion', 'electromagnetic separation', 'calutron'] },
      { c: 'Penetrating power and range of alpha, beta, gamma',
        k: ['penetrat', 'range in air', 'stopping power', 'absorbed in a sheet', 'ionising track'] },
      { c: 'Inverse-square law for radiation intensity',
        k: ['inverse square', 'inverse-square', 'distance from the source', 'intensity falls with distance'] },
      { m: true, c: 'Descriptive statistics: mean, spread, standard deviation',
        k: ['standard deviation', 'mean of the', 'scatter in the data', 'average of the measurements',
            'spread', 'percentage of the mean', 'dispersion', 'distribution rather than'] },
      { m: true, c: 'Graphical analysis: semi-log plots and slopes',
        k: ['semi-log', 'log plot', 'slope of the line', 'straight line on a', 'plot the'] },
      { c: 'Pressure, temperature and equations of state',
        k: ['equation of state', 'pressure and temperature', 'compressibility', 'adiabatic'] },
      { c: 'Chemical explosives: energy release and detonation velocity',
        k: ['detonation velocity', 'explosive charge', 'energy release', 'high explosive', 'brisance'] },
      { m: true, c: 'Timing, synchronisation and simultaneity of events',
        k: ['simultane', 'microsecond', 'timing of the', 'synchronis', 'synchroniz', 'jitter'] },
      { m: true, c: 'Dimensional analysis and scaling laws',
        k: ['dimensional analysis', 'scaling law', 'scales as', 'proportional to the cube',
            'scaled experiment'] },
      { m: true, c: 'Criticality safety: administrative limits and controls',
        k: ['administrative limit', 'safety margin', 'criticality safety', 'two-person', 'procedural control'] },
    ],
  },

  // ---------------------------------------------------------------- astronomy
  planetary_defense: {
    course: 'Astronomy elective, with the mechanics of AP Physics 1',
    concepts: [
      { c: 'Celestial coordinates and angular measure',
        k: ['arcsec', 'coordinate system', 'right ascension', 'declination', 'angular'] },
      { c: 'Apparent and absolute magnitude; inverse-square brightness',
        k: ['magnitude', 'brightness', 'inverse square', 'flux!'] },
      { c: 'Albedo and the size–brightness degeneracy',
        k: ['albedo', 'reflectiv', 'diameter', 'size of the object'] },
      { c: 'Light curves and rotation',
        k: ['light curve', 'rotation period', 'rotational', 'periodic brightness'] },
      { c: 'Telescopes: aperture, resolution, signal-to-noise',
        k: ['aperture', 'signal-to-noise', 'exposure', 'point-spread', 'resolution'] },
      { c: 'Detectors and image artifacts',
        k: ['hot pixel', 'cosmic ray', 'artifact', 'detector defect', 'satellite trail', 'flat frame'] },
      { c: "Kepler's laws",
        k: ['kepler', 'orbital period', 'semi-major axis', 'eccentric'] },
      { c: 'Orbital elements and orbit determination',
        k: ['orbital element', 'orbit determination', 'orbit fit', 'observation arc', 'ephemeris'] },
      { c: 'Gravitation, orbital speed and energy',
        k: ['gravitational', 'orbital speed', 'escape velocity', 'perturbation'] },
      { c: 'Radar ranging, light travel time and Doppler',
        k: ['radar', 'round-trip delay', 'light travel', 'doppler'] },
      { m: true, c: 'Uncertainty, error bars and covariance',
        k: ['uncertainty', 'covariance', 'error bar', 'residual', 'confidence'] },
      { m: true, c: 'Time and coordinate standards',
        k: ['time standard', 'utc', 'timestamp', 'clock'] },
      { c: 'Kinetic energy and impact energy scaling',
        k: ['kinetic energy', 'impact energy', 'megaton', 'joule', 'energy scales'] },
      { c: 'Atmospheric entry: drag, ablation, airburst',
        k: ['entry', 'airburst', 'ablat', 'atmospher', 'burst altitude', 'drag'] },
      { c: 'Momentum transfer and deflection',
        k: ['momentum transfer', 'deflect', 'delta-v', 'velocity change', 'beta factor'] },
      { c: 'Probability, risk and expected value',
        k: ['impact probability', 'probability', 'risk', 'expected value', 'expected number'] },
      { m: true, c: 'Scientific notation and unit conversion',
        k: ['scientific notation', 'unit conversion', 'order of magnitude', 'kilometre per second',
            'megaton', 'exponent', 'powers of ten', 'in the units the'] },
      { m: true, c: 'Independent confirmation and data validation',
        k: ['independent follow-up', 'independent confirmation', 'somebody else can test',
            'cross-match', 'validate'] },
      { c: 'Solar system architecture and near-Earth objects',
        k: ['near-earth', 'asteroid', 'solar system', 'ecliptic', 'main belt'] },
      { m: true, c: 'Observing constraints: elongation, visibility windows, scheduling',
        k: ['elongation', 'observing window', 'visibility', 'discretionary time', 'schedule'] },
      { c: 'Angular size and the small-angle formula',
        k: ['angular size', 'small-angle', 'subtend', 'apparent size'] },
      { c: 'Parallax, baselines and distance',
        k: ['parallax', 'baseline', 'two stations', 'triangulat'] },
      { c: 'Thermal emission and infrared temperature',
        k: ['thermal emission', 'infrared', 'blackbody', 'thermal data', 'temperature of the surface'] },
      { c: 'Phase angle, scattering and observing geometry',
        k: ['phase angle', 'scattering', 'scattered light', 'illuminat', 'observing geometry',
            'sun-object-earth'] },
      { c: 'Impact velocity and gravitational focusing',
        k: ['impact velocity', 'encounter speed', 'gravitational focus', 'entry velocity',
            'entry speed', 'approach speed', 'escape speed'] },
      { c: 'Momentum conservation in collisions',
        k: ['momentum', 'conservation of momentum', 'ejecta', 'recoil'] },
      { c: 'Planetary perturbations and resonances',
        k: ['perturb', 'resonance', 'close approach to', 'keyhole'] },
      { m: true, c: 'Monte Carlo methods and ensembles',
        k: ['monte carlo', 'ensemble', 'virtual impactor', 'sample of orbits', 'many trial'] },
      { m: true, c: 'Detection thresholds, false alarms and completeness',
        k: ['threshold', 'false alarm', 'false positive', 'completeness', 'survey completeness',
            'searchable volume', 'volume grows', 'deeper sensitivity', 'limiting magnitude'] },
      { c: 'Crater and blast scaling; ground effects',
        k: ['crater', 'blast', 'overpressure', 'ground damage', 'shock wave'] },
    ],
  },

  // ------------------------------------------------------------------- biology
  outbreak_riverton: {
    course: 'AP Biology, with a public-health unit',
    concepts: [
      { c: 'Cell structure and function',
        k: ['cell wall', 'organelle', 'cytoplasm', 'nucleus of the cell', 'cell structure'] },
      { c: 'Membranes and transport',
        k: ['membrane', 'osmosis', 'diffusion', 'active transport', 'permeab', 'gradient'] },
      { c: 'Enzymes and metabolism',
        k: ['enzyme', 'substrate', 'metabolis', 'catalys'] },
      { c: 'Energy: respiration and ATP',
        k: ['respiration', 'atp', 'aerobic', 'anaerobic', 'glucose'] },
      { c: 'DNA structure and replication',
        k: ['dna', 'replicat', 'nucleotide', 'genome', 'rna'] },
      { c: 'Transcription, translation and gene expression',
        k: ['transcription', 'translation', 'protein synthesis', 'expression'] },
      { c: 'Molecular diagnostics: PCR and amplification',
        k: ['pcr', 'amplif', 'primer', 'cycle threshold', 'assay'] },
      { c: 'Mutation and genetic variation',
        k: ['mutation', 'variant', 'genetic variation', 'sequence change'] },
      { c: 'Natural selection and evolution',
        k: ['selection', 'evolv', 'evolution', 'fitness', 'resistan'] },
      { c: 'Populations, transmission chains and exponential growth',
        k: ['exponential', 'doubling time', 'transmission chain', 'growth rate', 'incidence'] },
      { c: 'Homeostasis and feedback',
        k: ['homeostasis', 'feedback', 'set point', 'regulat'] },
      { c: 'Circulatory and respiratory physiology',
        k: ['oxygen saturation', 'blood pressure', 'perfusion', 'respiratory rate', 'cardiac'] },
      { c: 'Innate and adaptive immunity',
        k: ['immune', 'innate', 'adaptive', 'antibod', 'antigen', 'inflammat'] },
      { c: 'Vaccination and treatment',
        k: ['vaccin', 'antivir', 'antibiotic', 'treatment', 'prophylax'] },
      { c: 'Pathogens: viruses and bacteria',
        k: ['virus', 'viral', 'bacteri', 'pathogen', 'infectious agent'] },
      { c: 'Epidemiology: case definitions, curves, R and reservoirs',
        k: ['case definition', 'epidemic curve', 'reproduction number', 'reservoir', 'outbreak',
            'contact tracing', 'next generation', 'threshold near one', 'surveillance',
            'upstream of the'] },
      { c: 'Test performance: sensitivity, specificity, predictive value',
        k: ['sensitivity', 'specificity', 'false positive', 'false negative', 'predictive value'] },
      { m: true, c: 'Experimental design: controls, sampling and bias',
        k: ['control group', 'negative control', 'sample size', 'bias', 'randomis', 'randomiz',
            'trial', 'participant protection', 'interpretable evidence'] },
      { c: 'Ecology, vectors and zoonoses',
        k: ['vector', 'zoono', 'animal reservoir', 'ecolog', 'spillover', 'one health'] },
      { m: true, c: 'Rates, ratios and reading data',
        k: ['rate per', 'per hundred thousand', 'ratio', 'trend in the data', 'denominator',
            'upper bound', 'bound on', 'simple bounds'] },
      { c: 'Cell division and growth',
        k: ['mitosis', 'cell division', 'divides', 'proliferat'] },
      { c: 'Inheritance and Mendelian genetics',
        k: ['inherit', 'allele', 'genotype', 'phenotype', 'mendel', 'dominant'] },
      { c: 'Gene regulation and expression control',
        k: ['gene regulation', 'upregulat', 'downregulat', 'promoter', 'switched on'] },
      { c: 'Protein structure and function',
        k: ['protein structure', 'receptor', 'binding site', 'conformation', 'denatur'] },
      { c: 'pH and buffering in biological systems',
        k: ['ph!', 'acidosis', 'buffer', 'bicarbonate'] },
      { c: 'Signalling: nervous and endocrine control',
        k: ['hormone', 'neurotransmit', 'signal', 'endocrine', 'insulin'] },
      { c: 'Antimicrobial resistance',
        k: ['resistan', 'antimicrobial', 'antibiotic resistance', 'selective pressure'] },
      { m: true, c: 'Biosafety, aseptic technique and contamination',
        k: ['biosafety', 'aseptic', 'sterile', 'contaminat', 'personal protective', 'decontaminat'] },
      { m: true, c: 'Statistics: confidence, significance and sample size',
        k: ['confidence interval', 'statistically significant', 'p-value', 'sample size', 'power of the study',
            'effect size', 'number needed to treat', 'relative risk', 'absolute risk'] },
      { c: 'Epidemic modelling and projection',
        k: ['model of the epidemic', 'projection', 'compartment model', 'susceptible', 'forecast'] },
    ],
  },

  // ------------------------------------------------------------------ mechanics
  bring_them_home: {
    course: 'AP Physics 1, with the mechanics half of AP Physics C',
    concepts: [
      { c: 'Vectors and components',
        k: ['vector', 'component', 'resolve into', 'state vector'] },
      { c: 'Kinematics',
        k: ['velocity', 'acceleration', 'displacement', 'trajector'] },
      { c: "Newton's laws and free-body reasoning",
        k: ['newton', 'net force', 'free-body', 'thrust', 'reaction force'] },
      { c: 'Work, energy and conservation of energy',
        k: ['work done', 'kinetic energy', 'potential energy', 'conservation of energy', 'energy budget'] },
      { c: 'Momentum, impulse and conservation',
        k: ['momentum', 'impulse', 'conservation of momentum'] },
      { c: 'Circular motion and centripetal force',
        k: ['circular motion', 'centripetal', 'orbital radius'] },
      { c: 'Rotational kinematics',
        k: ['angular velocity', 'angular rate', 'rotation rate', 'degrees per second'] },
      { c: 'Torque and moment of inertia',
        k: ['torque', 'moment of inertia', 'lever arm', 'couple'] },
      { c: 'Angular momentum',
        k: ['angular momentum', 'spin-up', 'gyroscop'] },
      { c: 'Gravitation and orbits',
        k: ['gravitation', 'orbit', 'free return', 'perigee', 'apogee', 'burn'] },
      { c: 'Simple harmonic motion and resonance',
        k: ['resonance', 'harmonic', 'natural frequency', 'oscillat', 'damping'] },
      { c: 'Waves: frequency, wavelength, speed',
        k: ['wavelength', 'frequency', 'wave speed', 'antenna', 'carrier'] },
      { c: 'Doppler shift',
        k: ['doppler'] },
      { c: "Circuits: current, voltage, resistance, Ohm's law",
        k: ['voltage', 'electric current', 'current draw', 'amps', 'resistance', 'ohm', 'circuit', 'bus voltage'] },
      { c: 'Electrical power and energy budgets',
        k: ['watt', 'amp-hour', 'power draw', 'load shed', 'energy remaining', 'battery'] },
      { c: 'Series, parallel and load management',
        k: ['in series', 'in parallel', 'load!', 'loads', 'breaker', 'isolat'] },
      { c: 'Heat transfer: conduction, convection, radiation',
        k: ['conduction', 'convection', 'radiat', 'thermal', 'insulat', 'heat rejection'] },
      { c: 'Gas behaviour and life support',
        k: ['partial pressure', 'carbon dioxide', 'scrub', 'oxygen', 'lithium hydroxide'] },
      { m: true, c: 'Measurement uncertainty and error propagation',
        k: ['uncertainty', 'residual', 'error propagat', 'tolerance', 'common-mode',
            'angular error', 'position error', 'precision becomes', 'transverse offset'] },
      { m: true, c: 'Systems thinking: dependency, redundancy, failure modes',
        k: ['dependency', 'redundan', 'failure mode', 'single point of failure', 'interlock',
            'blackout', 'ordered so that', 'settled before'] },
      { c: 'Projectile motion and free fall',
        k: ['projectile', 'free fall', 'ballistic', 'parabolic'] },
      { c: 'Friction and drag',
        k: ['friction', 'drag', 'resistive force'] },
      { c: "Springs and Hooke's law",
        k: ['spring', 'hooke', 'stiffness', 'deflection under load'] },
      { c: 'Collisions: elastic and inelastic',
        k: ['collision', 'elastic', 'inelastic', 'docking impact'] },
      { c: 'Centre of mass and balance',
        k: ['centre of mass', 'center of mass', 'centre of gravity', 'center of gravity', 'balance point'] },
      { c: 'Static equilibrium and structural loads',
        k: ['equilibrium of forces', 'static load', 'structural load', 'stress', 'strain', 'buckl'] },
      { c: 'Fluid pressure and flow',
        k: ['pressure of the', 'psi', 'flow rate', 'leak rate', 'tank pressure'] },
      { c: 'Capacitance, RC time constants and transients',
        k: ['capacit', 'time constant', 'transient', 'surge', 'inrush'] },
      { c: 'Magnetism, motors and actuators',
        k: ['magnet', 'motor', 'solenoid', 'actuator', 'gimbal'] },
      { m: true, c: 'Graphical analysis of motion data',
        k: ['plot the', 'plotted', 'graph', 'slope of the', 'against time', 'read the curve'] },
    ],
  },

  // ------------------------------------------------------------ waves & systems
  deepwatch: {
    course: 'Physics of waves and sound, with an engineering-systems unit',
    concepts: [
      { c: 'Sound as a wave: frequency, wavelength, speed',
        k: ['wavelength', 'frequency', 'sound speed', 'hertz', 'acoustic'] },
      { c: 'Sound in water: refraction, layers, propagation paths',
        k: ['the layer', 'refract', 'sound channel', 'propagation path', 'thermocline'] },
      { c: 'Reflection, absorption and transmission loss',
        k: ['reflect', 'absorb', 'transmission loss', 'echo', 'return'] },
      { c: 'Doppler shift',
        k: ['doppler'] },
      { c: 'Resonance and harmonics',
        k: ['resonance', 'harmonic', 'natural frequency', 'blade rate'] },
      { c: 'Spectra: broadband and narrowband',
        k: ['broadband', 'narrowband', 'spectrum', 'tonal'] },
      { c: 'Signal-to-noise and detection thresholds',
        k: ['signal-to-noise', 'noise floor', 'detection threshold', 'quieter than'] },
      { c: 'Bearings, triangulation and geometry',
        k: ['bearing', 'triangulat', 'fix!', 'a fix', 'cross-bearing', 'range estimate'] },
      { c: 'Relative motion, vectors and dead reckoning',
        k: ['dead reckoning', 'set and drift', 'relative motion', 'course and speed', 'vector',
            'clear water', 'margin', 'off track', 'plotted line'] },
      { c: 'Buoyancy and Archimedes',
        k: ['buoyan', 'archimedes', 'displacement of water', 'ballast'] },
      { c: 'Pressure, depth and hydrostatics',
        k: ['pressure at depth', 'hydrostatic', 'sea pressure', 'flooding rate'] },
      { c: 'Trim, stability and centre of gravity',
        k: ['trim', 'stability', 'centre of gravity', 'center of gravity', 'listing to'] },
      { c: 'Fluid flow and cavitation',
        k: ['cavitat', 'flow rate', 'turbulen', 'pump'] },
      { c: 'Thermodynamics and heat engines',
        k: ['thermodynam', 'steam', 'heat exchanger', 'condens', 'efficiency of the plant'] },
      { c: 'Circuits, grounding and electrical faults',
        k: ['ground fault', 'breaker', 'bus', 'volt!', 'volts', 'insulation resistance', 'energis', 'energiz'] },
      { c: 'Gas laws and life support',
        k: ['partial pressure', 'carbon dioxide', 'scrubber', 'oxygen', 'atmosphere monitor'] },
      { c: 'Combustion, the fire triangle and reflash',
        k: ['fire', 'combust', 'reflash', 'fuel source', 'smother'] },
      { m: true, c: 'Dependency order and interlocks',
        k: ['dependency', 'interlock', 'in order', 'prerequisite', 'restore in'] },
      { m: true, c: 'Instruments versus indicators: validating a reading',
        k: ['indicator', 'meter the', 'gauge', 'confirm it is', 'proved dead', 'independent check'] },
      { m: true, c: 'Risk, redundancy and failure propagation',
        k: ['redundan', 'cascad', 'propagat', 'single failure', 'worst case'] },
      { c: 'Interference, beats and phase',
        k: ['interfer', 'beat frequency', 'in phase', 'out of phase', 'cancel'] },
      { c: 'Standing waves and cavity resonance',
        k: ['standing wave', 'node', 'cavity', 'hull resonance', 'ringing'] },
      { c: 'Diffraction, beamwidth and array directivity',
        k: ['diffract', 'beamwidth', 'array', 'directivity', 'aperture'] },
      { c: 'Decibels and logarithmic scales',
        k: ['decibel', ' db', 'logarithm', 'source level'] },
      { c: "Snell's law, ray paths and shadow zones",
        k: ['snell', 'ray path', 'shadow zone', 'bends toward', 'gradient of sound speed'] },
      { c: 'The sonar equation: source level, transmission loss, noise',
        k: ['sonar equation', 'source level', 'transmission loss', 'noise level', 'figure of merit'] },
      { c: 'Speed, time, distance and closest point of approach',
        k: ['closest point of approach', 'time to intercept', 'speed and distance', 'range rate',
            'knot', 'time budget', 'how much time does', 'slowing'] },
      { c: 'Materials under pressure: stress, strength, the pressure hull',
        k: ['pressure hull', 'hull integrity', 'stress', 'strength of the', 'yield', 'fatigue',
            'crush depth'] },
      { c: 'Batteries, DC distribution and grounding',
        k: ['batter', 'direct current', 'distribution panel', 'ground', 'shore power'] },
      { m: true, c: 'Human factors: checklists, handover and communication',
        k: ['checklist', 'handover', 'report to the officer', 'read back', 'watch team'] },
    ],
  },

  // ------------------------------------------------------- anatomy & physiology
  hospital: {
    course: 'Anatomy & Physiology — note this game is written for grade 2, not senior high',
    concepts: [
      { c: 'Levels of organisation: cells, tissues, organs, systems',
        k: ['cell!', 'cells', 'tissue', 'organ!', 'organs', 'body system'] },
      { c: 'Homeostasis and feedback',
        k: ['homeostasis', 'in balance', 'keeps the body', 'feedback'] },
      { c: 'Skeletal system',
        k: ['bone', 'skeleton', 'joint', 'fracture', 'ankle'] },
      { c: 'Muscles and movement',
        k: ['muscle', 'movement', 'tendon', 'strength'] },
      { c: 'Skin: barrier, healing, temperature',
        k: ['skin', 'wound', 'heal', 'rash', 'burn'] },
      { c: 'Nervous system and reflexes',
        k: ['nerve', 'brain', 'reflex', 'spinal'] },
      { c: 'The senses',
        k: ['you can see', 'looks at', 'hearing', 'ear', 'eye', 'touch', 'sense'] },
      { c: 'Heart and circulation',
        k: ['heart', 'blood vessel', 'circulat', 'artery'] },
      { c: 'Blood and its components',
        k: ['blood', 'red cell', 'platelet', 'bleeding'] },
      { c: 'Pulse and blood pressure',
        k: ['pulse', 'blood pressure', 'beats per minute', 'heart rate'] },
      { c: 'Breathing and gas exchange',
        k: ['breath', 'lung', 'oxygen', 'airway', 'wheez'] },
      { c: 'Digestion and absorption',
        k: ['stomach', 'digest', 'intestin', 'food goes'] },
      { c: 'Nutrition and energy',
        k: ['nutrition', 'energy from food', 'food is fuel', 'sugar', 'calorie',
            'eats', 'eating', 'eaten', 'fuel'] },
      { c: 'Fluids, hydration and dehydration',
        k: ['water', 'hydrat', 'dehydrat', 'fluid', 'drink'] },
      { c: 'Kidneys and waste',
        k: ['kidney', 'urine', 'waste'] },
      { c: 'Hormones and growth',
        k: ['hormone', 'insulin', 'growth', 'gland'] },
      { c: 'Immune defence and inflammation',
        k: ['immune', 'fight the germ', 'swell', 'fever', 'inflam'] },
      { c: 'Germs, transmission and hand hygiene',
        k: ['germ', 'wash your hands', 'spread', 'clean your hands', 'infection'] },
      { m: true, c: 'Vital signs, measurement and normal ranges',
        k: ['measure', 'normal range', 'thermometer', 'number from a tool', 'vital sign'] },
      { c: 'Emergency assessment and triage',
        k: ['triage', 'who to see first', 'urgen', 'sickest', 'emergency'] },
      { c: 'Anatomical terms and body regions',
        k: ['left side', 'right side', 'front of the body', 'upper body', 'lower body', 'body part'] },
      { c: 'How things move in and out of cells',
        k: ['soaks in', 'passes through', 'absorb', 'diffus', 'through the wall'] },
      { c: 'Joints and how far they move',
        k: ['joint', 'bend it', 'range of motion', 'swollen ankle', 'sprain'] },
      { c: 'The heartbeat: rhythm and rate',
        k: ['rhythm', 'beats', 'fast heart', 'slow heart', 'steady beat'] },
      { c: 'Breathing effort and how much air',
        k: ['breathing hard', 'breaths per minute', 'deep breath', 'short of breath', 'chest moves'] },
      { c: 'Swelling, lymph and healing',
        k: ['swell', 'swollen', 'bruise', 'lymph', 'ice on it'] },
      { c: 'Body temperature and fever',
        k: ['temperature', 'fever', 'hot forehead', 'degrees'] },
      { c: 'Medicines and dose',
        k: ['medicine', 'dose', 'how much to give', 'milligram', 'drops'] },
      { c: 'First aid: airway, breathing, circulation',
        k: ['airway', 'first aid', 'chest compression', 'choking', 'stop the bleeding'] },
      { c: 'Imaging: X-rays and pictures of the inside',
        k: ['x-ray', 'picture of the bone', 'scan', 'ultrasound', 'image of the'] },
    ],
  },

  // ------------------------------------------------------------ power systems
  // Written before the book, which is the order NEW_GAME.md §1 asks for: the
  // gaps report is what says which questions still need writing.
  blackout: {
    course: 'AP Physics 2 circuits and induction, with a first-year electrical-engineering unit',
    concepts: [
      { c: 'Charge, current, voltage and resistance',
        k: ['current', 'voltage', 'resistance', 'potential difference', 'ampere'] },
      { c: "Ohm's law and resistive networks",
        k: ['ohm', 'resistive', 'v = ir', 'volt drop across'] },
      { c: "Kirchhoff's laws and nodal analysis",
        k: ['kirchhoff', 'node', 'loop rule', 'sum of the currents'] },
      { c: 'Series, parallel and equivalent circuits',
        k: ['in series', 'in parallel', 'equivalent resistance'] },
      { c: 'Electrical power and energy over time',
        k: ['electrical power', 'kilowatt', 'megawatt', 'kilowatt-hour', 'energy delivered'] },
      { c: 'AC waveforms: frequency, period and phase',
        k: ['alternating', 'waveform', 'hertz', 'phase angle', 'cycle'] },
      { c: 'RMS against peak and average',
        k: ['rms', 'root mean square', 'peak voltage'] },
      { c: 'Capacitance, inductance and stored energy',
        k: ['capacitor', 'capacitance', 'inductor', 'inductance'] },
      { c: 'Reactance, impedance and phasors',
        k: ['reactance', 'impedance', 'phasor', 'inductive', 'capacitive'] },
      { c: 'Real, reactive and apparent power',
        k: ['reactive power', 'apparent power', 'volt-ampere', 'kvar', 'mvar'] },
      { c: 'Power factor and its correction',
        k: ['power factor', 'leading', 'lagging', 'correction capacitor'] },
      { c: 'Three-phase systems and balance',
        k: ['three-phase', 'three phase', 'balanced load', 'phase imbalance', 'neutral current'] },
      { c: 'Transformers, turns ratio and losses',
        k: ['transformer', 'turns ratio', 'step-up', 'step-down', 'no-load loss'] },
      { m: true, c: 'Voltage levels and the per-unit system',
        k: ['per-unit', 'per unit', 'base voltage', 'nominal voltage', 'kv'] },
      { c: 'Transmission losses and conductor sizing',
        k: ['transmission loss', 'conductor', 'line loss', 'thermal rating', 'ampacity'] },
      { c: 'Voltage drop, regulation and reactive support',
        k: ['voltage drop', 'volt drop', 'voltage regulation', 'voltage collapse', 'tap changer',
            'reactive support'] },
      { c: "Faraday's law and electromagnetic induction",
        k: ['faraday', 'induction', 'flux', 'induced emf'] },
      { c: 'Synchronous machines and synchronisation',
        k: ['synchronous', 'synchronis', 'synchroniz', 'alternator', 'excitation', 'in step'] },
      { c: 'Frequency as the balance of supply and demand',
        k: ['frequency deviation', 'under-frequency', 'over-frequency', '50 hz', '60 hz',
            'supply and demand'] },
      { c: 'Inertia, governor response and droop control',
        k: ['inertia', 'governor', 'droop', 'rate of change of frequency', 'primary response'] },
      { c: 'Load curves and demand forecasting',
        k: ['load curve', 'peak demand', 'demand forecast', 'diversity factor'] },
      { c: 'Economic dispatch and merit order',
        k: ['dispatch', 'merit order', 'marginal cost', 'spinning reserve'] },
      { c: 'Protection: relays, breakers and coordination',
        k: ['relay', 'circuit breaker', 'protection', 'coordination', 'trip'] },
      { c: 'Fault current and short-circuit analysis',
        k: ['fault current', 'short circuit', 'short-circuit', 'arc flash'] },
      { c: 'Earthing, step-and-touch potential and safety',
        k: ['earthing', 'grounding', 'touch potential', 'step potential', 'lockout'] },
      { c: 'Islanding, black start and restoration order',
        k: ['island', 'black start', 'restoration', 'energise', 'energize', 'cranking path'] },
      { m: true, c: 'Contingency analysis and the N-1 criterion',
        k: ['contingency', 'n-1', 'redundan', 'single point of failure'] },
      { c: 'Cascading failure and the sequence of events',
        k: ['cascad', 'sequence of events', 'overload trip', 'ripple through'] },
      { c: 'Storage, round-trip efficiency and ramp rate',
        k: ['storage', 'round-trip', 'battery', 'ramp rate', 'pumped'] },
      { c: 'Renewables: variability, curtailment and inverters',
        k: ['curtail', 'inverter', 'variability', 'grid-forming', 'intermitten'] },
      { m: true, c: 'Metering, instrument transformers and measurement error',
        k: ['metering', 'instrument transformer', 'current transformer', 'measurement error',
            'telemetry'] },
      { m: true, c: 'Load shedding as a decision under uncertainty',
        k: ['load shed', 'shed load', 'rolling blackout', 'brownout'] },
    ],
  },
  aftershock: {
    course: 'Earth science, statics and materials — a senior-school engineering unit',
    concepts: [
      { c: 'P and S waves, and what the gap between them measures',
        k: ['p-wave', 's-wave', 'primary wave', 'shear wave', 's-minus-p', 'travel time'] },
      { c: 'Locating an earthquake from three or more stations',
        k: ['epicentre', 'epicenter', 'hypocentre', 'triangulat', 'locate the source'] },
      { c: 'Magnitude as a logarithmic scale',
        k: ['magnitude', 'log scale', 'logarithmic', 'orders of magnitude'] },
      { c: 'Moment magnitude, and what it is made of',
        k: ['moment magnitude', 'seismic moment', 'rupture area', 'slip', 'rigidity'] },
      { c: 'Intensity against magnitude — one event, many shakings',
        k: ['intensity', 'mercalli', 'felt report', 'shaking map'] },
      { c: 'Peak ground acceleration and what a building feels',
        k: ['peak ground acceleration', 'pga', 'ground motion', 'acceleration record'] },
      { c: 'Site effect: soft ground amplifies',
        k: ['site effect', 'amplif', 'soft soil', 'fill', 'basin effect', 'soil class'] },
      { c: 'Natural period, and resonance between building and ground',
        k: ['natural period', 'fundamental period', 'resonance', 'period of the ground'] },
      { c: 'Base shear — the horizontal force a building is designed for',
        k: ['base shear', 'seismic coefficient', 'design force', 'lateral force'] },
      { c: 'Load path, and what happens where it stops',
        k: ['load path', 'soft storey', 'soft story', 'discontinuity', 'transfer'] },
      { c: 'Ductility: bending without breaking',
        k: ['ductil', 'brittle', 'plastic hinge', 'energy dissipat'] },
      { c: 'Stress, strain and the yield point',
        k: ['stress', 'strain', 'yield', 'elastic modulus', 'stress-strain'] },
      { c: 'Factor of safety, and what it is protecting against',
        k: ['factor of safety', 'safety factor', 'capacity to demand', 'demand-capacity'] },
      { c: 'Unreinforced masonry, and why it fails outward',
        k: ['unreinforced masonry', 'urm', 'parapet', 'out-of-plane', 'gable end'] },
      { c: 'Liquefaction: when saturated fill stops behaving as a solid',
        k: ['liquefaction', 'liquefied', 'pore pressure', 'sand boil', 'ejecta'] },
      { c: 'Bearing capacity and settlement',
        k: ['bearing capacity', 'settlement', 'differential settlement', 'raft', 'foundation'] },
      { c: 'Lateral spreading toward a free face',
        k: ['lateral spread', 'free face', 'quay', 'toward the water'] },
      { c: 'Effective stress, and why water pressure matters',
        k: ['effective stress', 'pore water', 'water table', 'drainage'] },
      { c: 'Aftershock decay as a power law',
        k: ['aftershock', 'omori', 'decay', 'rate of aftershocks'] },
      { c: 'Probability of a larger event after a mainshock',
        k: ['foreshock', 'probability of a larger', 'sequence', 'conditional probability'] },
      { c: 'Placarding as a decision under uncertainty',
        k: ['placard', 'red tag', 'yellow tag', 'green tag', 'reoccupancy', 'cordon'] },
      { c: 'Rapid assessment against detailed evaluation',
        k: ['rapid assessment', 'detailed evaluation', 'triage of buildings', 'walk-through'] },
      { c: 'Non-structural hazards — what falls before the frame does',
        k: ['non-structural', 'nonstructural', 'ceiling', 'cladding', 'anchorage', 'shelving'] },
      { c: 'Instruments: what an accelerograph actually records',
        k: ['accelerograph', 'seismometer', 'strong motion', 'trigger', 'clipped'] },
      { c: 'Sampling and testing damaged material',
        k: ['core sample', 'coupon', 'rebound hammer', 'compressive strength', 'test to failure'] },
      { c: 'Retrofit: what is worth doing before the next one',
        k: ['retrofit', 'strengthen', 'bracing', 'tie the parapet', 'anchor the wall'] },
      { c: 'Recurrence intervals and what "the big one" means',
        k: ['recurrence', 'return period', 'paleoseismic', 'trench', 'slip rate'] },
      { c: 'Communicating risk to people who have to act on it',
        k: ['advisory', 'press', 'public meeting', 'tell people', 'explain the risk'] },
      { c: 'Cordons, lifelines and the cost of keeping people out',
        k: ['lifeline', 'water main', 'cordon cost', 'business', 'displaced'] },
      { c: 'Documentation: the record somebody inherits',
        k: ['record', 'photograph', 'log the damage', 'inspection form'] },
    ],
  },
  quantum: {
    course: 'Modern quantum, taught through the hardware — second-year physics or electrical engineering',
    concepts: [
      { c: 'Energy quantisation, and why a level spacing sets everything else',
        k: ['energy level', 'level spacing', 'quantised', 'quantized', 'transition frequency'] },
      { c: 'Thermal energy against level spacing — why a qubit needs millikelvin',
        k: ['thermal energy', 'kt', 'millikelvin', 'boltzmann', 'thermal population'] },
      { c: 'The two-level approximation, and when it fails',
        k: ['two-level', 'qubit', 'leakage', 'higher level', 'anharmonic'] },
      { c: 'Superposition as an amplitude, not a mixture',
        k: ['superposition', 'amplitude', 'coherent state of', 'bloch'] },
      { c: 'Measurement collapses the state and returns one outcome',
        k: ['measurement', 'collapse', 'projective', 'single shot', 'outcome'] },
      { c: 'Probability from amplitude, and why one shot tells you nothing',
        k: ['probability', 'repeated shots', 'statistics of', 'sampling the state'] },
      { c: 'Rabi oscillation: driving a transition',
        k: ['rabi', 'drive amplitude', 'pi pulse', 'pulse length'] },
      { c: 'Resonance, detuning, and finding a qubit frequency',
        k: ['resonance', 'detuning', 'spectroscopy', 'frequency sweep'] },
      { c: 'Relaxation time T1 — energy leaving the system',
        k: ['t1', 'relaxation', 'energy decay', 'lifetime of the excited'] },
      { c: 'Dephasing time T2 — the phase going before the energy does',
        k: ['t2', 'dephasing', 'phase noise', 'coherence time', 'ramsey'] },
      { c: 'Where decoherence comes from: two-level defects, photons, flux noise',
        k: ['decoherence', 'two-level system', 'tls', 'flux noise', 'quasiparticle'] },
      { c: 'Gate fidelity, and how error compounds with depth',
        k: ['fidelity', 'gate error', 'circuit depth', 'compound'] },
      { c: 'Randomised benchmarking: what it measures and what it does not',
        k: ['randomised benchmarking', 'randomized benchmarking', 'benchmark', 'average error'] },
      { c: 'Readout, discriminators, and how a classifier can cheat',
        k: ['readout', 'discriminator', 'classifier', 'assignment error', 'single-shot readout'] },
      { c: 'Calibration drift, and the tuning that has to happen daily',
        k: ['calibration', 'recalibrate', 'drift', 'tune-up', 'tuning'] },
      { c: 'The microwave chain: attenuation, amplification and noise temperature',
        k: ['attenuator', 'amplifier', 'noise temperature', 'microwave chain', 'circulator'] },
      { c: 'Cryogenics: stages, cooling power and heat load',
        k: ['dilution refrigerator', 'mixing chamber', 'cooling power', 'heat load', 'cryostat'] },
      { c: 'Materials and fabrication: junctions, oxide and yield',
        k: ['josephson', 'junction', 'oxide', 'fabrication', 'wafer', 'yield'] },
      { c: 'Entanglement as a correlation stronger than any shared instruction',
        k: ['entangle', 'correlation', 'bell state', 'epr'] },
      { c: 'The Bell inequality as a number you measure',
        k: ['bell inequality', 'chsh', 'local hidden variable', 'violation'] },
      { c: 'Quantum error correction and the threshold idea',
        k: ['error correction', 'logical qubit', 'surface code', 'threshold', 'syndrome'] },
      { c: 'What a quantum advantage claim actually claims',
        k: ['advantage', 'supremacy', 'classical simulation', 'runtime comparison'] },
      { c: 'The standard quantum limit, and beating it with squeezing',
        k: ['shot noise', 'standard quantum limit', 'squeez', 'sensitivity scaling'] },
      { c: 'Interferometry as a phase measurement',
        k: ['interferometer', 'interference', 'phase difference', 'fringe'] },
      { c: 'Atomic clocks and what frequency accuracy buys',
        k: ['atomic clock', 'frequency standard', 'stability of the clock', 'timekeeping'] },
      { c: 'Magnetometry: NV centres and SQUIDs',
        k: ['magnetometer', 'magnetometry', 'nv centre', 'nv center', 'squid'] },
      { c: 'Quantum key distribution, and where its security comes from',
        k: ['key distribution', 'qkd', 'bb84', 'eavesdrop', 'secret key'] },
      { c: 'Loss in fibre, and why a repeater is hard',
        k: ['fibre loss', 'fiber loss', 'repeater', 'attenuation length', 'no-cloning'] },
      { c: 'Reproducibility: a result on one device is not a result',
        k: ['reproduc', 'second device', 'independent replication', 'cross-check'] },
      { c: 'Provenance of data, and what a shared calibration hides',
        k: ['provenance', 'shared calibration', 'common mode', 'training data', 'leakage of information'] },
    ],
  },
};

// --------------------------------------------------------------- equations
//
// The equations a course cannot be said to have taught without. Same idea as the
// concepts above and the same matching, but a narrower claim and a stricter test.
//
// **Deliberately a separate export, not a field on the entry above.**
// `claimedWords` walks every string in a `SYLLABUS[theme]` entry and turns it
// into the allowlist that `jargonSweep` prioritises by and that `import-book`
// stamps `core` from. Adding equations there would quietly claim "constant",
// "logarithm", "specificity" and forty more, restamp `core` across the glossary,
// and reorder every plan card in the game — a syllabus page is not worth that.
//
// `e` is the equation as a reader should meet it. `c` is what it is for. `k` are
// the phrases that say a question is about it, matched exactly as a concept's
// are. `strong` is the extra test: a question *computes* the equation when its
// estimate's own `relationship` or worked solution matches, and merely *mentions*
// it when only the prose does. Both are printed, because they are not the same
// claim — an estimate that gets a number out of PV = nRT has taught it, and a
// verdict that says the words has not.
//
// The lists are short on purpose. "Absolutely has to be taught" is a much higher
// bar than "appears in the course", so a topic that a course could reasonably
// cover qualitatively is not here: the test applied was whether a student could
// pass the unit without being able to write the thing down.
export const EQUATIONS = {
  contamcity: [
    { e: 'n = m / M', c: 'moles from a mass and a molar mass',
      v: [['n', 'number of moles, in mol'], ['m', 'mass of the sample, in grams'], ['M', 'molar mass of the substance, in grams per mole']],
      s: 'Divide a weighed mass by the mass of one mole to get how many moles you are holding.',
      k: ['molar mass', 'moles of', 'mole!', 'number of moles'] },
    { e: 'PV = nRT', c: 'the ideal gas law',
      v: [['P', 'pressure, in pascals'], ['V', 'volume, in cubic metres'], ['n', 'moles of gas'], ['R', 'the gas constant, 8.314 J per mole per kelvin'], ['T', 'absolute temperature, in kelvin']],
      s: 'For a gas, pressure times volume is fixed by how much gas there is and how hot it is.',
      k: ['nrt', 'ideal gas', 'gas law'] },
    { e: 'c = n / V', c: 'molarity as moles per unit volume',
      v: [['c', 'concentration, in moles per litre'], ['n', 'moles of solute'], ['V', 'volume of solution, in litres']],
      s: 'Concentration is how many moles are dissolved in each litre of solution.',
      k: ['molarity', 'moles per litre', 'moles per liter', 'concentration of the solution'] },
    { e: 'C₁V₁ = C₂V₂', c: 'dilution, and carrying a dilution factor back',
      v: [['C₁', 'concentration before dilution'], ['V₁', 'volume taken of the stronger solution'], ['C₂', 'concentration after dilution'], ['V₂', 'final volume, in the same units as V₁']],
      s: 'Diluting adds solvent and not solute, so moles before equal moles after and the product of concentration and volume is unchanged.',
      k: ['dilution', 'dilute', 'stock solution', 'aliquot'] },
    { e: 'q = mcΔT', c: 'calorimetry — heat from a temperature change',
      v: [['q', 'heat gained or lost, in joules'], ['m', 'mass being heated, in grams'], ['c', 'specific heat capacity, in joules per gram per kelvin'], ['ΔT', 'temperature change, in kelvin']],
      s: 'The heat that went in is the mass times how hard that substance is to warm times how far its temperature moved.',
      k: ['specific heat', 'heat capacity', 'calorimet', 'temperature rise'] },
    { e: 'pH = −log[H⁺]', c: 'acidity on a logarithmic scale',
      v: [['pH', 'the acidity scale, no units'], ['[H⁺]', 'hydrogen ion concentration, in moles per litre']],
      s: 'pH is the negative logarithm of hydrogen ion concentration, so one pH unit is a tenfold change in acid.',
      k: ['ph!', 'hydrogen ion', 'protonat', 'hydroxide'] },
    { e: 'A = εlc', c: 'Beer–Lambert, and the calibration curve it justifies',
      v: [['A', 'absorbance, no units'], ['ε', 'molar absorptivity, how strongly the compound absorbs'], ['l', 'path length through the sample, in centimetres'], ['c', 'concentration, in moles per litre']],
      s: 'How much light a sample absorbs rises in step with concentration, which is what lets a calibration curve turn a reading into a number.',
      k: ['beer-lambert', 'beer–lambert', 'absorbance', 'calibration curve'] },
    { e: 'Kₛₚ = [Aᵃ][Bᵇ]', c: 'the solubility product and the common-ion effect',
      v: [['Kₛₚ', 'solubility product, a constant for that salt at that temperature'], ['[Aᵃ]', 'concentration of one ion raised to its coefficient'], ['[Bᵇ]', 'concentration of the other ion raised to its coefficient']],
      s: 'A salt keeps dissolving until the product of its ion concentrations reaches a fixed value, which is why adding one of those ions pushes the rest back out.',
      k: ['solubility product', 'common-ion', 'common ion', 'ksp'] },
    { e: 'percent yield = actual ÷ theoretical × 100', c: 'yield against a stoichiometric prediction',
      v: [['actual', 'mass or moles you really recovered'], ['theoretical', 'what the stoichiometry says you should have got'], ['100', 'the factor that turns the fraction into a percentage']],
      s: 'Yield measures what you actually collected against what the reaction could have produced at best.',
      k: ['percent yield', 'theoretical yield', 'chemical yield', 'recovery fraction'] },
    { e: 'rate = k[A]ⁿ', c: 'a rate law, and the order it asserts',
      v: [['rate', 'how fast the reaction goes, in moles per litre per second'], ['k', 'the rate constant for that reaction at that temperature'], ['[A]', 'concentration of the reactant, in moles per litre'], ['n', 'the order, how strongly rate answers to concentration']],
      s: 'Reaction rate depends on concentration raised to a power that has to be measured rather than assumed.',
      k: ['rate law', 'reaction rate', 'arrhenius', 'activation energy'] },
  ],

  projecty: [
    { e: 'E = mc²', c: 'mass defect converted to binding energy',
      v: [['E', 'energy released, in joules'], ['m', 'the mass that went missing, in kilograms'], ['c', 'the speed of light, 3.0 × 10⁸ metres per second']],
      s: 'Mass that disappears in a nuclear reaction reappears as energy, and the conversion factor is enormous.',
      k: ['mass defect', 'binding energy', 'mass-energy', 'rest-mass', 'energy equivalent'] },
    { e: 'B / A', c: 'binding energy per nucleon, and the stability curve it plots',
      v: [['B', 'total binding energy of the nucleus, in MeV'], ['A', 'the number of nucleons in it']],
      s: 'Binding energy per nucleon says how tightly an average particle is held, and nuclei move toward the peak of that curve by splitting or by fusing.',
      k: ['per nucleon', 'stability curve', 'binding energy per'] },
    { e: 'N(t) = N₀e^(−λt)', c: 'exponential decay of a population',
      v: [['N(t)', 'how many nuclei are left at time t'], ['N₀', 'how many there were at the start'], ['λ', 'decay constant, in per second'], ['t', 'elapsed time, in seconds']],
      s: 'A fixed fraction decays each second, so the population falls by the same proportion in every equal interval.',
      k: ['exponential decay', 'decay law', 'half-lives', 'what is left'] },
    { e: 'λ = ln2 / t½', c: 'decay constant from half-life',
      v: [['λ', 'decay constant, in per second'], ['ln2', '0.693'], ['t½', 'half-life, the time for half of it to go']],
      s: 'The decay constant and the half-life are the same fact written two ways.',
      k: ['decay constant', 'half-life', 'half life'] },
    { e: 'A = λN', c: 'activity from a decay constant and a population',
      v: [['A', 'activity, in decays per second'], ['λ', 'decay constant, in per second'], ['N', 'how many nuclei are present']],
      s: 'How radioactive something is depends on both how unstable it is and how much of it there is.',
      k: ['activity', 'decays per', 'disintegrations', 'becquerel'] },
    { e: 'Σ = nσ', c: 'macroscopic cross section from number density',
      v: [['Σ', 'macroscopic cross section, in per centimetre'], ['n', 'nuclei per cubic centimetre'], ['σ', 'microscopic cross section, the target area of one nucleus']],
      s: 'One nucleus offers a small target, and packing many of them into a centimetre of material is what makes an interaction likely.',
      k: ['macroscopic cross section', 'number density', 'cross section'] },
    { e: 'mfp = 1 / Σ', c: 'mean free path as the inverse of interaction per length',
      v: [['mfp', 'mean free path, in centimetres'], ['Σ', 'macroscopic cross section, in per centimetre']],
      s: 'The average distance a neutron travels before interacting is the inverse of how much interaction each centimetre offers.',
      k: ['mean free path'] },
    { e: 'I = I₀e^(−Σx)', c: 'exponential attenuation through matter',
      v: [['I', 'intensity after the material'], ['I₀', 'intensity before it'], ['Σ', 'macroscopic cross section, in per centimetre'], ['x', 'thickness, in centimetres']],
      s: 'Shielding removes a fixed fraction per centimetre, so intensity falls exponentially rather than linearly with thickness.',
      k: ['attenuation', 'shielding', 'half-thickness', 'uncollided'] },
    { e: 'σ = √N', c: 'Poisson counting uncertainty, and why precision costs time',
      v: [['σ', 'the standard deviation of the count'], ['N', 'the number of counts recorded']],
      s: 'Counting is random, so the uncertainty is the square root of the count and four times the counting time buys only twice the precision.',
      k: ['counting statistics', 'poisson', 'fractional uncertainty', 'square root of the number'] },
    { e: 'I ∝ 1 / r²', c: 'inverse-square fall-off of radiation intensity',
      v: [['I', 'intensity at the detector'], ['r', 'distance from the source, in metres']],
      s: 'The same energy spreads over a sphere that grows as the square of distance, so doubling the distance quarters the intensity.',
      k: ['inverse-square', 'inverse square'] },
  ],

  planetary_defense: [
    { e: 'θ = s / d', c: 'the small-angle formula — angular size to physical size',
      v: [['θ', 'angular size, in radians'], ['s', 'true size across, in kilometres'], ['d', 'distance to it, in kilometres']],
      s: 'For small angles the angle an object subtends is simply its size divided by its distance.',
      k: ['small-angle', 'small angle', 'angular width', 'arcsecond', 'angular size'] },
    { e: 'd = baseline / parallax angle', c: 'distance from a parallax shift',
      v: [['baseline', 'separation between the two observing points, in kilometres'], ['parallax angle', 'the shift in apparent position, in radians']],
      s: 'Watching an object from two places shifts it against the background, and the size of that shift gives the distance.',
      k: ['parallax', 'baseline'] },
    { e: 'F = L / 4πd²', c: 'inverse-square brightness, and the size–albedo degeneracy',
      v: [['F', 'flux received here, in watts per square metre'], ['L', 'how much light the object sends out, in watts'], ['d', 'distance, in metres']],
      s: 'Brightness at the telescope is the emitted light spread over a sphere, which is why a small bright object and a large dark one can look identical.',
      k: ['inverse-square', 'inverse square', 'absolute magnitude', 'apparent magnitude', 'albedo'] },
    { e: 'KE = ½mv²', c: 'impact energy, and why speed dominates it',
      v: [['KE', 'kinetic energy, in joules'], ['m', 'mass, in kilograms'], ['v', 'speed, in metres per second']],
      s: 'Impact energy rises with the square of speed, so a body arriving twice as fast carries four times the energy.',
      k: ['kinetic energy', 'impact energy', 'megaton'] },
    { e: 'p = mv', c: 'momentum, and momentum transfer in a deflection',
      v: [['p', 'momentum, in kilogram metres per second'], ['m', 'mass, in kilograms'], ['v', 'speed, in metres per second']],
      s: 'Momentum is conserved, so whatever a deflection pushes away pushes back on the object by the same amount.',
      k: ['momentum', 'velocity change', 'deflect'] },
    { e: 'v² = v∞² + v_esc²', c: 'gravitational focusing of impact speed',
      v: [['v', 'impact speed, in kilometres per second'], ['v∞', 'speed far from Earth, before it is pulled in'], ['v_esc', 'Earth\'s escape speed, 11.2 kilometres per second']],
      s: 'Earth\'s gravity accelerates anything falling toward it, so nothing can arrive slower than escape speed.',
      k: ['gravitational focusing', 'impact velocity', 'escape velocity'] },
    { e: 'v = √(GM / r)', c: 'orbital speed, and the energy that goes with it',
      v: [['v', 'orbital speed, in metres per second'], ['G', 'the gravitational constant'], ['M', 'mass of the body being orbited, in kilograms'], ['r', 'orbital radius, in metres']],
      s: 'An orbit is a balance between speed and distance, so a closer orbit has to be a faster one.',
      k: ['orbital speed', 'vis-viva', 'orbital energy', 'semi-major'] },
    { e: 'Δλ / λ = v / c', c: 'Doppler shift as a line-of-sight speed',
      v: [['Δλ', 'shift in wavelength'], ['λ', 'the unshifted wavelength'], ['v', 'speed along the line of sight'], ['c', 'the speed of light']],
      s: 'Motion toward or away stretches or squeezes the light by a fraction equal to the speed as a fraction of light speed.',
      k: ['doppler', 'radial velocity', 'line-of-sight speed'] },
    { e: 'E[X] = Σ p·x', c: 'expected value — a consequence weighted by its probability',
      v: [['E[X]', 'expected value, in the same units as the consequence'], ['p', 'probability of an outcome'], ['x', 'what that outcome costs or gains']],
      s: 'Weight each outcome by how likely it is and add them up, which is how a small chance of something enormous is compared with a certainty of something small.',
      k: ['expected value', 'expectation', 'probability of impact', 'expected consequence'] },
    { e: 'λ_max T = b', c: "Wien's law — a temperature read off a thermal spectrum",
      v: [['λ_max', 'wavelength where the emission peaks, in metres'], ['T', 'temperature, in kelvin'], ['b', 'Wien\'s constant, 2.898 × 10⁻³ metre kelvin']],
      s: 'Hotter things peak at shorter wavelengths, so the colour of thermal emission is a thermometer.',
      k: ['thermal emission', 'infrared temperature', 'blackbody', 'wien'] },
  ],

  outbreak_riverton: [
    { e: 'Rₑ = R₀ × S', c: 'effective reproduction number against a susceptible fraction',
      v: [['Rₑ', 'effective reproduction number, cases caused per case now'], ['R₀', 'basic reproduction number, in a wholly susceptible population'], ['S', 'the fraction still susceptible']],
      s: 'The number that matters is not how infectious the pathogen could be but how many people are left for it to infect.',
      k: ['reproduction number', 'r0', 'effective reproduction', 'secondary cases'] },
    { e: 'N(t) = N₀ · 2^(t/T_d)', c: 'exponential growth from a doubling time',
      v: [['N(t)', 'how many cases at time t'], ['N₀', 'cases at the start'], ['t', 'elapsed time'], ['T_d', 'doubling time, in the same units as t']],
      s: 'Exponential growth adds a constant proportion rather than a constant number, so the count doubles in every doubling time.',
      k: ['doubling time', 'exponential growth', 'doubling'] },
    { e: 'sensitivity = TP / (TP+FN)', c: 'and specificity = TN / (TN+FP) — what a test misses',
      v: [['TP', 'true positives, sick and testing positive'], ['FN', 'false negatives, sick and testing negative'], ['TN', 'true negatives'], ['FP', 'false positives']],
      s: 'Sensitivity is the share of sick people a test catches, and specificity the share of well people it clears; a test can be excellent at one and poor at the other.',
      k: ['sensitivity', 'specificity', 'false negative', 'false positive'] },
    { e: 'PPV = (prev·sens) / (prev·sens + (1−prev)(1−spec))', c: 'why a good test fails at low prevalence',
      v: [['PPV', 'positive predictive value, the chance a positive is real'], ['prev', 'prevalence, how common the disease is'], ['sens', 'sensitivity'], ['spec', 'specificity']],
      s: 'When almost nobody has the disease, most positives come from the many well people tested, however good the test is.',
      k: ['predictive value', 'prevalence', 'positive predictive'] },
    { e: 'risk = events / people at risk', c: 'and NNT = 1 / (control risk − treated risk)',
      v: [['events', 'how many people had the outcome'], ['people at risk', 'how many could have'], ['NNT', 'number needed to treat'], ['control risk', 'risk without the treatment'], ['treated risk', 'risk with it']],
      s: 'Risk is a proportion rather than a count, and the number needed to treat says how many patients you must treat to prevent one event.',
      k: ['number needed to treat', 'absolute risk', 'relative risk', 'attack rate', 'people at risk'] },
    { e: 'CFR = deaths / cases', c: 'case fatality, and what its denominator hides',
      v: [['CFR', 'case fatality ratio'], ['deaths', 'deaths among known cases'], ['cases', 'cases that were actually diagnosed']],
      s: 'The denominator is the diagnosed rather than the infected, so a ratio falls as testing widens without anything changing in the disease.',
      k: ['case fatality', 'fatality rate'] },
    { e: 'pH = pKa + log([A⁻]/[HA])', c: 'Henderson–Hasselbalch — buffering in a body',
      v: [['pH', 'acidity of the blood'], ['pKa', 'the acid constant for that buffer pair, 6.1 for bicarbonate'], ['[A⁻]', 'concentration of the base form, bicarbonate'], ['[HA]', 'concentration of the acid form, dissolved carbon dioxide']],
      s: 'Blood pH is set by the ratio of base to acid rather than by either alone, which is why the lungs and the kidneys can compensate for each other.',
      k: ['henderson', 'buffer', 'pka', 'buffering'] },
  ],

  bring_them_home: [
    { e: 'v = v₀ + at, x = x₀ + v₀t + ½at²', c: 'kinematics at constant acceleration',
      v: [['v', 'speed at time t, in metres per second'], ['v₀', 'speed at the start'], ['a', 'acceleration, in metres per second squared'], ['t', 'elapsed time, in seconds'], ['x', 'position'], ['x₀', 'starting position']],
      s: 'Under constant acceleration, speed grows in step with time and distance grows with the square of it.',
      k: ['kinematic', 'constant acceleration', 'free fall', 'displacement'] },
    { e: 'F = ma', c: "Newton's second law",
      v: [['F', 'net force, in newtons'], ['m', 'mass, in kilograms'], ['a', 'acceleration, in metres per second squared']],
      s: 'Acceleration is what a net force produces, and the same force moves a heavier object less.',
      k: ['net force', 'newton', 'force on the'] },
    { e: 'W = Fd, KE = ½mv²', c: 'work, kinetic energy and conservation of energy',
      v: [['W', 'work done, in joules'], ['F', 'force along the motion, in newtons'], ['d', 'distance moved, in metres'], ['KE', 'kinetic energy, in joules'], ['m', 'mass'], ['v', 'speed']],
      s: 'Work done on something becomes its energy, and the total energy is bookkeeping that has to balance.',
      k: ['work done', 'kinetic energy', 'conservation of energy', 'potential energy', 'energy stored'] },
    { e: 'J = FΔt = Δp', c: 'impulse as the change in momentum',
      v: [['J', 'impulse, in newton seconds'], ['F', 'force applied'], ['Δt', 'how long it acts for'], ['Δp', 'the resulting change in momentum']],
      s: 'A small force applied for a long time changes momentum as much as a large one applied briefly.',
      k: ['impulse', 'momentum'] },
    { e: 'τ = rF', c: 'torque about an axis, and rotational equilibrium',
      v: [['τ', 'torque, in newton metres'], ['r', 'distance from the axis, in metres'], ['F', 'force applied at that distance']],
      s: 'Turning effect depends on where the force is applied as much as on how hard, and equilibrium needs the torques to cancel.',
      k: ['torque', 'lever arm', 'moment of inertia'] },
    { e: 'a_c = v² / r', c: 'centripetal acceleration in circular motion',
      v: [['a_c', 'centripetal acceleration, in metres per second squared'], ['v', 'speed along the circle'], ['r', 'radius of the circle, in metres']],
      s: 'Going round a curve is an acceleration even at constant speed, because the direction keeps changing.',
      k: ['centripetal', 'circular motion'] },
    { e: 'T = 2π√(m/k)', c: 'the period of a simple harmonic oscillator, and resonance',
      v: [['T', 'period, in seconds'], ['m', 'the oscillating mass, in kilograms'], ['k', 'stiffness of the spring, in newtons per metre']],
      s: 'An oscillator has a natural period set by its mass and stiffness, and driving it at that rate is what makes a resonance.',
      k: ['harmonic', 'resonance', 'stiffness'] },
    { e: 'P = IV = I²R', c: 'electrical power, and an energy budget over time',
      v: [['P', 'power, in watts'], ['I', 'current, in amperes'], ['V', 'voltage, in volts'], ['R', 'resistance, in ohms']],
      s: 'Power is the rate energy is used, and over a mission it is the energy budget that decides what can stay switched on.',
      k: ['power dissipated', 'power drawn', 'resistance', 'current'] },
    { e: 'Q = mcΔT', c: 'heat against a temperature change and a heat capacity',
      v: [['Q', 'heat, in joules'], ['m', 'mass, in kilograms'], ['c', 'specific heat capacity'], ['ΔT', 'temperature change, in kelvin']],
      s: 'How far a temperature moves depends on the heat added, the mass and how hard that material is to warm.',
      k: ['heat capacity', 'temperature drop', 'specific heat'] },
    { e: 'v = fλ', c: 'wave speed, frequency and wavelength',
      v: [['v', 'wave speed, in metres per second'], ['f', 'frequency, in hertz'], ['λ', 'wavelength, in metres']],
      s: 'For a given medium the speed is fixed, so raising the frequency shortens the wavelength in proportion.',
      k: ['wavelength', 'frequency'] },
  ],

  deepwatch: [
    { e: 'v = fλ', c: 'wave speed, frequency and wavelength',
      v: [['v', 'speed of sound in water, about 1500 metres per second'], ['f', 'frequency, in hertz'], ['λ', 'wavelength, in metres']],
      s: 'Sound speed in water is roughly fixed, so frequency and wavelength trade off against each other.',
      k: ['wavelength', 'frequency', 'speed of sound'] },
    { e: 'Δf / f = v / c', c: 'Doppler shift as a closing speed',
      v: [['Δf', 'the shift in frequency, in hertz'], ['f', 'the frequency being transmitted'], ['v', 'closing speed along the line of sight'], ['c', 'speed of sound in water']],
      s: 'A contact closing on you raises the frequency you hear, by a fraction equal to the closing speed over the speed of sound.',
      k: ['doppler', 'closing speed', 'frequency shift'] },
    { e: 'dB = 10·log₁₀(P/P₀)', c: 'the decibel, and why 3 dB is a doubling',
      v: [['dB', 'the level, in decibels'], ['P', 'the power being measured'], ['P₀', 'the reference power it is quoted against']],
      s: 'Decibels are a logarithm, so adding 3 dB is doubling the power and adding 10 dB is ten times it.',
      k: ['decibel', 'db!', 'logarithmic scale'] },
    { e: 'SL − 2TL + TS − NL ≥ DT', c: 'the sonar equation as a detection budget',
      v: [['SL', 'source level of the noise'], ['TL', 'transmission loss, once each way'], ['TS', 'target strength of the contact'], ['NL', 'noise level at the array'], ['DT', 'detection threshold the operator needs']],
      s: 'Detection is a budget: the echo has to survive two trips through the water and still stand above the noise.',
      k: ['sonar equation', 'source level', 'transmission loss', 'noise level', 'detection threshold'] },
    { e: 'sinθ₁ / v₁ = sinθ₂ / v₂', c: "Snell's law — why sound bends at a layer",
      v: [['θ₁', 'angle in the first layer'], ['v₁', 'sound speed in that layer'], ['θ₂', 'angle in the second layer'], ['v₂', 'sound speed there']],
      s: 'Sound bends toward the slower water when it crosses a layer, which is what makes a shadow zone.',
      k: ['refract', 'snell', 'sound speed profile', 'the layer'] },
    { e: 'd = ½vt', c: 'echo ranging on a two-way travel time',
      v: [['d', 'range to the contact, in metres'], ['v', 'speed of sound in water'], ['t', 'the round-trip travel time, in seconds']],
      s: 'The ping goes out and comes back, so the range is half of what the travel time would otherwise give.',
      k: ['round trip', 'echo', 'two-way', 'ranging'] },
    { e: 'p = ρgh', c: 'hydrostatic pressure with depth',
      v: [['p', 'pressure, in pascals'], ['ρ', 'density of seawater, about 1025 kilograms per cubic metre'], ['g', '9.81 metres per second squared'], ['h', 'depth, in metres']],
      s: 'Pressure rises steadily with depth, which is why the same hole floods faster the deeper you go.',
      k: ['hydrostatic', 'pressure at depth', 'pressure increases with'] },
    { e: 'F_b = ρVg', c: 'Archimedes — buoyancy from displaced volume',
      v: [['F_b', 'buoyant force, in newtons'], ['ρ', 'density of the water'], ['V', 'volume of water displaced, in cubic metres'], ['g', '9.81 metres per second squared']],
      s: 'The upward force equals the weight of the water pushed aside, so flooding a compartment removes buoyancy the boat was relying on.',
      k: ['buoyan', 'archimedes', 'displaced'] },
    { e: 'f_beat = |f₁ − f₂|', c: 'beats between two close frequencies',
      v: [['f_beat', 'the beat frequency you hear, in hertz'], ['f₁', 'one source frequency'], ['f₂', 'the other']],
      s: 'Two close tones rise and fall together at the difference of their frequencies, which is how two machines are told from one.',
      k: ['beat frequency', 'beats', 'interference'] },
    { e: 'PV = nRT', c: 'the gas law behind a life-support margin',
      v: [['P', 'pressure'], ['V', 'volume'], ['n', 'moles of gas'], ['R', 'the gas constant'], ['T', 'absolute temperature, in kelvin']],
      s: 'The air aboard is a fixed quantity of gas, so pressure, volume and temperature cannot be changed independently.',
      k: ['gas law', 'partial pressure', 'nrt'] },
  ],

  blackout: [
    { e: 'V = IR', c: "Ohm's law, on a conductor and on a whole network",
      v: [['V', 'voltage across it, in volts'], ['I', 'current through it, in amperes'], ['R', 'resistance, in ohms']],
      s: 'Current through a resistance produces a voltage across it, in proportion.',
      k: ['ohm', 'resistance', 'voltage drop'] },
    { e: 'P = IV, and P = I²R', c: 'power delivered, and the loss that never arrives',
      v: [['P', 'power, in watts'], ['I', 'current, in amperes'], ['V', 'voltage, in volts'], ['R', 'resistance, in ohms']],
      s: 'Power delivered is current times voltage, and the power wasted as heat in a conductor rises with the square of the current.',
      k: ['electrical power', 'line loss', 'transmission loss', 'megawatt'] },
    { e: 'V_rms = V_peak / √2', c: 'why an AC quantity needs saying which one you mean',
      v: [['V_rms', 'the root-mean-square value a meter reports'], ['V_peak', 'the highest instantaneous value a scope shows']],
      s: 'An alternating voltage has no single value, so a reading is meaningless until it says which one is meant.',
      k: ['rms', 'root mean square', 'peak voltage'] },
    { e: 'S = √(P² + Q²), pf = P/S', c: 'apparent power and power factor',
      v: [['S', 'apparent power, in volt-amperes'], ['P', 'real power, in watts'], ['Q', 'reactive power, in volt-amperes reactive'], ['pf', 'power factor, between 0 and 1']],
      s: 'Equipment is sized for the current it carries, which includes reactive power that does no work.',
      k: ['power factor', 'reactive power', 'apparent power', 'kvar'] },
    { e: 'N₁/N₂ = V₁/V₂', c: 'the transformer ratio, and why transmission is at high voltage',
      v: [['N₁', 'turns on the primary winding'], ['N₂', 'turns on the secondary'], ['V₁', 'primary voltage'], ['V₂', 'secondary voltage']],
      s: 'A transformer trades voltage for current in the ratio of its turns, which is what makes long-distance transmission affordable.',
      k: ['transformer', 'turns ratio', 'step-up', 'step-down'] },
    { e: 'P = √3 · V_L · I_L · cos φ', c: 'three-phase power from line quantities',
      v: [['P', 'three-phase power, in watts'], ['V_L', 'line-to-line voltage, in volts'], ['I_L', 'line current, in amperes'], ['cos φ', 'power factor']],
      s: 'Three-phase power from line quantities carries a √3 because line and phase values differ.',
      k: ['three-phase', 'three phase', 'line current'] },
    { e: 'df/dt = (P_gen − P_load) / 2H', c: 'frequency as the running balance of supply and demand',
      v: [['df/dt', 'how fast frequency is moving, in hertz per second'], ['P_gen', 'total generation, in megawatts'], ['P_load', 'total demand, in megawatts'], ['H', 'stored kinetic energy of the machines online, in megawatt-seconds']],
      s: 'Frequency falls at a rate set by how far generation is short, divided by the spinning inertia there to absorb it.',
      k: ['inertia', 'rate of change of frequency', 'rate of frequency change', 'stored kinetic energy',
          'frequency deviation', 'droop'] },
    { e: 'ΔV ≈ I(R cos φ + X sin φ)', c: 'voltage drop along a line, and why reactive power moves it',
      v: [['ΔV', 'voltage drop along the line, in volts'], ['I', 'current, in amperes'], ['R', 'line resistance, in ohms'], ['X', 'line reactance, in ohms'], ['cos φ / sin φ', 'the power factor terms']],
      s: 'Voltage falls along a loaded line, and on a transmission line the reactance term dominates, which is why reactive power moves voltage.',
      k: ['voltage drop', 'volt drop', 'voltage regulation', 'reactive support'] },
    { e: 'E = Pt', c: 'energy from power over time — the kilowatt-hour',
      v: [['E', 'energy, in kilowatt-hours'], ['P', 'power, in kilowatts'], ['t', 'time it was sustained, in hours']],
      s: 'Power is a rate and energy is the amount, and every settlement and compensation claim is in energy.',
      k: ['kilowatt-hour', 'megawatt-hour', 'energy delivered', 'energy not delivered',
          'energy stored', 'endurance'] },
    { e: 'η = E_out / E_in', c: 'round-trip efficiency of storage',
      v: [['η', 'round-trip efficiency, between 0 and 1'], ['E_out', 'energy you get back out'], ['E_in', 'energy you put in']],
      s: 'Storage returns less than it takes, so the reserve it is counted as is smaller than its nameplate.',
      k: ['round-trip', 'efficiency', 'storage'] },
  ],

  // Written for grade 2, so this list is not the senior-high kind. There is no
  // equation an eight-year-old has to be able to write down; there are four
  // arithmetic relationships the questions genuinely turn on, and claiming more
  // would be inventing a syllabus this game never promised.
  hospital: [
    { e: 'beats in a minute = beats in 15 seconds × 4', c: 'scaling a short count up to a rate',
      v: [['beats in 15 seconds', 'how many beats you counted'], ['× 4', 'because there are four fifteen-second blocks in a minute']],
      s: 'Counting for a quarter of a minute and multiplying by four gives the rate for a whole minute.',
      k: ['fifteen seconds', 'beats in', 'pulse'] },
    { e: 'breaths in a minute = breaths in 15 seconds × 4', c: 'the same scaling for breathing',
      v: [['breaths in 15 seconds', 'how many breaths you counted'], ['× 4', 'four fifteen-second blocks make a minute']],
      s: 'The same trick works for breathing, as long as the child does not know you are counting.',
      k: ['breaths in', 'breathing rate', 'breaths a minute'] },
    { e: 'how far behind = what is needed − what was taken', c: 'a running deficit',
      v: [['what is needed', 'the amount the body should have had'], ['what was taken', 'the amount that actually went in']],
      s: 'The gap between what was needed and what was given is how far behind the patient is.',
      k: ['how much more', 'needs', 'drank', 'behind'] },
    { e: 'change each hour = total change ÷ hours taken', c: 'a rate from a change and a time',
      v: [['total change', 'how much the number moved altogether'], ['hours taken', 'how long it took to move']],
      s: 'Dividing the change by the time gives how fast it is moving, which is what says whether to act now or watch.',
      k: ['each hour', 'per hour', 'how fast it changed'] },
  ],
  aftershock: [
    { e: 'd ≈ 8 km/s · (t_S − t_P)', c: 'distance from the S-minus-P interval',
      v: [['d', 'distance from the station to the source, in kilometres'], ['t_S − t_P', 'the gap between the S and P arrivals, in seconds'], ['8 km/s', 'the usual constant for shallow crust']],
      s: 'The S wave travels slower than the P wave, so the gap between them grows with distance and one station can say how far away the source was.',
      k: ['s-minus-p', 's minus p', 'travel time', 'arrival', 'p-wave', 's-wave'] },
    { e: 'M₀ = μ · A · D', c: 'seismic moment, and what makes a big earthquake big',
      v: [['M₀', 'seismic moment, in newton metres'], ['μ', 'rigidity of the rock, about 30 GPa'], ['A', 'area of fault that slipped, in square metres'], ['D', 'average slip on it, in metres']],
      s: 'The size of an earthquake is the area that moved times how far it moved times how stiff the rock is, which is why a long rupture matters more than a violent one.',
      k: ['seismic moment', 'rupture area', 'slip', 'rigidity', 'moment magnitude'] },
    { e: 'M_w = ⅔ log₁₀ M₀ − 6.06', c: 'moment magnitude, and why the scale is logarithmic',
      v: [['M_w', 'moment magnitude, no units'], ['M₀', 'seismic moment, in newton metres'], ['⅔ and 6.06', 'constants that make the scale line up with the older ones']],
      s: 'One unit of magnitude is about thirty-two times the energy, so a 7 is not a bit worse than a 6.',
      k: ['moment magnitude', 'magnitude scale', 'log scale', 'logarithmic', 'thirty-two'] },
    { e: 'T ≈ 0.1 N', c: 'a building\'s natural period from its storeys',
      v: [['T', 'natural period, in seconds'], ['N', 'number of storeys']],
      s: 'A rule of thumb: about a tenth of a second per floor, which is how you know whether a building and the ground it stands on want to swing at the same rate.',
      k: ['natural period', 'fundamental period', 'storeys', 'stories', 'period of the building'] },
    { e: 'V = C_s · W', c: 'base shear — the sideways force it is designed for',
      v: [['V', 'base shear, in kilonewtons'], ['C_s', 'seismic coefficient, a fraction of weight'], ['W', 'the weight of the building above the base, in kilonewtons']],
      s: 'Design treats the earthquake as a fraction of the building\'s own weight pushed sideways at its base.',
      k: ['base shear', 'seismic coefficient', 'design force', 'lateral force', 'weight of the building'] },
    { e: 'σ = F / A, ε = ΔL / L', c: 'stress and strain, and the yield point between them',
      v: [['σ', 'stress, in megapascals'], ['F', 'force carried, in newtons'], ['A', 'cross-sectional area, in square metres'], ['ε', 'strain, a ratio with no units'], ['ΔL / L', 'how much it stretched over how long it was']],
      s: 'Stress is force spread over area and strain is the stretch it causes; up to the yield point the material comes back, and past it the deformation stays.',
      k: ['stress', 'strain', 'yield', 'elastic modulus', 'coupon', 'test to failure'] },
    { e: 'FoS = capacity / demand', c: 'factor of safety as a ratio, not a feeling',
      v: [['FoS', 'factor of safety, no units'], ['capacity', 'what the element can carry'], ['demand', 'what the earthquake asked of it, in the same units']],
      s: 'A factor of safety below one does not mean collapse and above one does not mean safe: it says how much of the margin the event used up.',
      k: ['factor of safety', 'safety factor', 'capacity', 'demand', 'margin'] },
    { e: "σ' = σ − u", c: 'effective stress, and how liquefaction happens',
      v: [["σ'", 'effective stress holding the grains together, in kilopascals'], ['σ', 'total stress from the weight above, in kilopascals'], ['u', 'pore water pressure between the grains, in kilopascals']],
      s: 'Soil carries load through grain contact; when shaking drives the water pressure up to the total stress, the grains stop touching and the ground behaves as a liquid.',
      k: ['effective stress', 'pore water', 'pore pressure', 'liquefaction', 'liquefied'] },
    { e: 'n(t) = K / (c + t)^p', c: 'aftershock rate, falling as a power law',
      v: [['n(t)', 'aftershocks per day at time t'], ['t', 'days since the mainshock'], ['K, c, p', 'constants fitted to this sequence, with p usually near 1']],
      s: 'Aftershocks fall off roughly as one over time, so the rate halves as the days double rather than dropping to nothing on any particular day.',
      k: ['aftershock', 'omori', 'decay', 'rate of aftershocks', 'power law'] },
    { e: 'A_soft / A_rock', c: 'site amplification — the same wave on two grounds',
      v: [['A_soft', 'shaking measured on the soft site'], ['A_rock', 'shaking measured on rock nearby, in the same units']],
      s: 'Soft ground can multiply the shaking several times over, which is how one earthquake produces two different disasters in one town.',
      k: ['site effect', 'amplif', 'soft soil', 'fill', 'on rock', 'soil class'] },
  ],

  quantum: [
    { e: 'E = hf,  compare with  kT', c: 'why a superconducting qubit needs millikelvin',
      v: [['E', 'energy of one quantum, in joules'], ['h', "Planck's constant, 6.63 × 10⁻³⁴ J s"], ['f', 'transition frequency, in hertz'], ['k', "Boltzmann's constant, 1.38 × 10⁻²³ J per kelvin"], ['T', 'temperature, in kelvin']],
      s: 'A qubit only stays in its ground state if the thermal energy around it is well below the energy of one quantum, which for a 5 GHz qubit means tens of millikelvin.',
      k: ['thermal energy', 'kt', 'millikelvin', 'planck', 'level spacing', 'transition frequency'] },
    { e: 't_π = 1 / (2 f_Rabi)', c: 'drive strength to pulse length',
      v: [['t_π', 'length of a pulse that flips the qubit, in seconds'], ['f_Rabi', 'Rabi frequency, set by how hard you drive, in hertz']],
      s: 'Driving harder makes the qubit turn over faster, so the pulse that flips it gets shorter in proportion.',
      k: ['rabi', 'pi pulse', 'pulse length', 'drive amplitude'] },
    { e: 'P(t) = e^(−t/T₁)', c: 'relaxation, as a decay you fit',
      v: [['P(t)', 'chance the qubit is still excited after time t'], ['t', 'time since the pulse, in microseconds'], ['T₁', 'relaxation time, in microseconds']],
      s: 'An excited qubit loses its energy at random, so the population falls by the same fraction in every equal interval and T₁ is the time it takes to fall to about a third.',
      k: ['t1', 'relaxation', 'energy decay', 'lifetime'] },
    { e: '1/T₂ = 1/(2T₁) + 1/T_φ', c: 'why dephasing is usually the harder number',
      v: [['T₂', 'coherence time, in microseconds'], ['T₁', 'relaxation time, in microseconds'], ['T_φ', 'pure dephasing time, from noise that scrambles phase without taking energy']],
      s: 'Coherence is limited both by energy leaving and by phase being scrambled, and T₂ can never be more than twice T₁ however quiet the phase noise is.',
      k: ['t2', 'dephasing', 'coherence time', 'phase noise'] },
    { e: 'F_total ≈ F^n', c: 'gate fidelity compounding over circuit depth',
      v: [['F_total', 'chance the whole circuit is right'], ['F', 'fidelity of one gate, between 0 and 1'], ['n', 'number of gates in the circuit']],
      s: 'Errors multiply rather than add, so a gate that is right 99.9 per cent of the time is useless a few thousand gates deep.',
      k: ['fidelity', 'gate error', 'circuit depth', 'compound'] },
    { e: 'Δf = 1 / (2T)', c: 'Ramsey fringes, and measurement time as resolution',
      v: [['Δf', 'frequency resolution you can reach, in hertz'], ['T', 'free evolution time between the two pulses, in seconds']],
      s: 'Letting the state evolve for longer before reading it out resolves smaller frequency differences, which is why coherence time is what limits a sensor.',
      k: ['ramsey', 'fringe', 'frequency resolution', 'free evolution'] },
    { e: 'δB ∝ 1 / √N', c: 'the standard quantum limit, and what squeezing buys',
      v: [['δB', 'smallest field change you can resolve'], ['N', 'number of independent measurements or atoms']],
      s: 'Averaging independent measurements improves a sensor only as the square root of their number, which is the wall entanglement is used to get past.',
      k: ['shot noise', 'standard quantum limit', 'squeez', 'sensitivity', 'averaging'] },
    { e: 'S = E(a,b) − E(a,b′) + E(a′,b) + E(a′,b′),  |S| ≤ 2', c: 'the Bell test, as a measured number',
      v: [['S', 'the CHSH quantity, computed from four correlation measurements'], ['E(a,b)', 'correlation between the two detectors at settings a and b'], ['2', 'the largest value any shared instruction agreed in advance can produce']],
      s: 'No pre-agreed instruction set can push S above 2, so measuring more than that rules out the whole class of explanations rather than supporting one.',
      k: ['bell inequality', 'chsh', 'local hidden variable', 'violation', 'correlation'] },
    { e: 'n_phys ≈ d²  per logical qubit', c: 'what error correction costs',
      v: [['n_phys', 'physical qubits used for one logical qubit'], ['d', 'code distance, how many errors the code can survive'], ['p_threshold', 'the physical error rate below which adding qubits helps rather than hurts']],
      s: 'Error correction only works below a threshold error rate, and above it every qubit you add makes the logical qubit worse rather than better.',
      k: ['error correction', 'logical qubit', 'surface code', 'threshold', 'code distance'] },
    { e: 'R = 1 − 2h(e)', c: 'the key rate left after error correction and privacy amplification',
      v: [['R', 'secret key bits per sifted bit'], ['e', 'quantum bit error rate, the fraction of test bits that disagree'], ['h(e)', 'the binary entropy of that error rate']],
      s: 'Every error might be an eavesdropper, so the protocol throws away enough key to cover it, and above about eleven per cent errors nothing is left.',
      k: ['key distribution', 'qkd', 'bb84', 'secret key', 'error rate', 'privacy amplification'] },
  ],

};

/**
 * Which questions address each equation the course has to teach.
 *
 * `pages` is one entry per question: `{ text, formula, group }`, where `text` is
 * everything the question says and `formula` is only the estimate's own
 * `relationship`, template and worked solution. The split is the whole point —
 * `computes` means a question got a number out of it, `mentions` means the words
 * appeared. A gap is neither.
 */
export function equationCoverage(theme, pages = [], hit = defaultHit){
  const list = EQUATIONS[theme] ?? EQUATIONS[String(theme).replace(/_/g, '-')] ?? [];
  return list.map((eq, i) => {
    const computes = [], mentions = [];
    pages.forEach((p, n) => {
      const strong = p.formula && eq.k.some(k => hit(p.formula, k));
      if(strong) computes.push(n + 1);
      else if(eq.k.some(k => hit(p.text, k))) mentions.push(n + 1);
    });
    return { n: i + 1, e: eq.e, c: eq.c, v: eq.v ?? [], s: eq.s ?? '', computes, mentions };
  });
}

/** The same two-kinds-of-phrase rule the concepts use, so both agree. */
function defaultHit(hay, phrase){
  const exact = phrase.endsWith('!') || phrase.replace(/!$/, '').trim().length <= 3;
  const w = phrase.replace(/!$/, '').toLowerCase().trim();
  const e = w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`(^|[^a-z0-9])${e}${exact ? '([^a-z0-9]|$)' : ''}`, 'i').test(hay);
}

// ---------------------------------------------------------------- matching
//
// Whether the syllabus claims a word is asked in two places — `jargonSweep`
// sorts its queue by it, and `import-book` stamps `core` on the glossary terms
// it claims — so the rule lives here, next to the claim it is testing.
import { COMMON, PREFIXES, stems, ordinary, norm } from './common-words.mjs';

const wordsOf = (s) => String(s ?? '').match(/[A-Za-z][A-Za-z0-9'’\/]*/g) ?? [];

/**
 * The syllabus, flattened: every string in a game's entry becomes an allowlist
 * word. Word by word over-claims — "activation energy" would hand "energy" a
 * licence it did not earn — so a single word counts only when it is technical on
 * its own.
 */
export function claimedWords(theme){
  const entry = SYLLABUS[theme] ?? SYLLABUS[String(theme).replace(/_/g, '-')] ?? null;
  const out = new Set();
  // A short key is not a weak one. "ph!", "mole", "flux!", "fix!" carry the bang
  // this file already uses for "match this word exactly", and a length rule
  // written for the long words dropped every one of them — so pH, the concept
  // thirteen of Riverton's fifteen days reason with, counted as claimed by
  // nothing at all. They go in a set of their own, matched whole.
  out.exact = new Set();
  const walk = (v) => {
    if(typeof v === 'string'){
      if(v.endsWith('!') || v.trim().length <= 4){
        const k = norm(v.replace(/!$/, '').trim());
        if(k) out.exact.add(k);
      }
      for(const w of wordsOf(v)){
        const k = norm(w);
        if(k.length >= 5 && !COMMON.has(k)) out.add(k);
      }
      return;
    }
    if(Array.isArray(v)){ v.forEach(walk); return; }
    if(v && typeof v === 'object'){ Object.values(v).forEach(walk); }
  };
  walk(entry);
  return out;
}

/**
 * The syllabus writes stems on purpose — "precipitat", "oxidis", "mass spectrom" —
 * so an exact match claims almost nothing. Two words share a root when one starts
 * the other, or when they agree for seven characters: long enough that
 * "electrochemical" finds "electrochemistry" and "detonators" finds "detonation
 * velocity", short enough that "electrically" still does not find "electrolysis".
 */
export function sharesRoot(a, b){
  if(a === b) return true;
  const [s, l] = a.length <= b.length ? [a, b] : [b, a];
  if(s.length >= 5 && l.startsWith(s)) return true;
  let i = 0;
  while(i < s.length && s[i] === l[i]) i++;
  return i >= 7;
}

// The candidate side needs stemming as much as the syllabus side does:
// "detonates" and "detonators" are the syllabus's "detonation velocity" with an
// ending on them, and an unstemmed comparison claims neither.
export const rootsOf = (key) => [key, key.replace(PREFIXES, ''), ...stems(key)].filter(w => w.length >= 5);

/** Does this game's syllabus claim this single word? */
export function claimsWord(theme, word, claimed = claimedWords(theme)){
  const key = norm(word);
  if(claimed.exact?.has(key)) return true;
  return rootsOf(key).some(w => [...claimed].some(c => sharesRoot(w, c)));
}

/**
 * And a phrase — a glossary term's name or one of its aliases. Ordinary words in
 * it prove nothing: "surrogate material" is claimed only if "surrogate" is.
 */
export function claimsPhrase(theme, phrase, claimed = claimedWords(theme)){
  return wordsOf(phrase).some(w => {
    const k = norm(w);
    if(claimed.exact?.has(k)) return true;
    return k.length >= 5 && !ordinary(k) && claimsWord(theme, k, claimed);
  });
}

export default SYLLABUS;
