// missions.js — the campaign
// GENERATED by tools/import-book.mjs from contamcity.yml
// Hand edits are lost on the next import. Change the book.

export const MISSIONS = [
  {
    "title": "The Unknown Containers",
    "objective": "Create a provisional identity list and choose the next discriminating measurements.",
    "briefing": "A freight-yard fire damages several unlabeled containers beside Riverton's river. The response team must establish chemical identity and hazard classes before firefighters, residents, and the water utility act on rumors. A wrong identity can cause an incompatible firefighting or treatment decision.",
    "stake": "Day one, and the freight yard fire has been out for six hours. A row of containers eighty metres from the river is damaged and nobody can tell you what was in them. Three names are going around: one from a driver, one from a half-burnt manifest, one from a label nobody can read. Adaeze Okonjo, who leads the analytical chemistry, wants two methods on the same sample before anybody writes a name down; the fire chief wants a name now. Today you turn that into a short list you would defend, and decide how to spend the one round of lab work you get. Sampling has an order too, because some steps destroy what the next one needed.",
    "takeaway": "Create a provisional identity list and choose the next discriminating measurements.",
    "stops": [
      {
        "group": "IDENT",
        "lesson": 0,
        "task": "Read the formula, not the rumor"
      },
      {
        "group": "IDENT",
        "lesson": 1,
        "task": "From damaged container to provisional identity"
      },
      {
        "group": "IDENT",
        "lesson": 2,
        "task": "Spend the first analytical reserve"
      }
    ]
  },
  {
    "title": "The Vapor Cloud",
    "objective": "Provide a bounded plume assessment and decision triggers for evacuation zones.",
    "briefing": "A colorless plume moves toward two neighborhoods as the weather changes. The team must estimate expansion, density, and direction without treating an ideal-gas model as a complete atmospheric forecast. A delayed evacuation risks exposure; an overbroad evacuation can block emergency access and overwhelm shelters.",
    "stake": "Day two, first light, and the wind has backed forty degrees. A colourless plume is drifting off the yard toward two neighbourhoods, and the forecast from the atmospheric chemistry lead, Miklos Varga, disagrees with the incident commander's map about where it goes by eleven. Sipho Mbeki, who briefs the public, has to tell residents something by eight. Today you work out how much air that release can fill, what the warming morning will do to it, and which measurement to buy next. Both mistakes cost people. Evacuate too small an area and somebody is standing downwind of it. Evacuate the whole district and you block the roads the fire crews need.",
    "takeaway": "Provide a bounded plume assessment and decision triggers for evacuation zones.",
    "stops": [
      {
        "group": "GASES",
        "lesson": 0,
        "task": "How much volume can the gas occupy?"
      },
      {
        "group": "GASES",
        "lesson": 1,
        "task": "Interpret plume behavior"
      },
      {
        "group": "GASES",
        "lesson": 2,
        "task": "Choose the next plume evidence"
      }
    ]
  },
  {
    "title": "What Dissolved in the River?",
    "objective": "Predict where each chemical class will be found and design a mass-balance sampling plan.",
    "briefing": "Runoff from the accident enters the river. Some compounds remain in surface films, some dissolve, and others bind to sediment. The player must predict partitioning from molecular interactions and verify it with sampling. If the team samples only water, a persistent sediment reservoir may be missed until it re-enters the water supply.",
    "stake": "Day three. Runoff reached the river overnight and Riverton's drinking-water intake is nine hundred metres downstream. Inês Ferreira, who owns water and sediment, has been out since four and wants it sampled; the state's auditor wants a water survey, because that is what a water survey means. Today you design it: where to sample, in what order, and which parts of the river to sample at all. That last one decides everything else. Test only the water and the result comes back clean, and it is honestly clean — today. The next flood stirs the mud.",
    "takeaway": "Predict where each chemical class will be found and design a mass-balance sampling plan.",
    "stops": [
      {
        "group": "WATER",
        "lesson": 0,
        "task": "Where will the chemical go?"
      },
      {
        "group": "WATER",
        "lesson": 1,
        "task": "Build a river mass-balance survey"
      },
      {
        "group": "WATER",
        "lesson": 2,
        "task": "Spend the river survey budget"
      }
    ]
  },
  {
    "title": "Identify the Unknowns",
    "objective": "Assign confidence-ranked identities to mixture components using orthogonal evidence.",
    "briefing": "Chromatography reveals several peaks, while spectroscopy suggests overlapping functional groups. The player must combine separation and structural evidence rather than forcing one peak to equal one compound. A false identification could lead the treatment plant to use chemistry that creates a more hazardous byproduct.",
    "stake": "Day four. The lab has a chromatogram — a chart with one peak for each thing it managed to separate out — and there are more peaks than the team has names. Two methods run on the same sample disagree. Kwabena Osei, the treatment engineer, wants a list this morning so the plant can start ordering chemistry; Okonjo will not give him one she cannot defend. Today you decide what is actually in the mixture and how sure you are willing to be about each name. Name something that is not there and the plant treats the water for it.",
    "takeaway": "Assign confidence-ranked identities to mixture components using orthogonal evidence.",
    "stops": [
      {
        "group": "IDENT",
        "lesson": 3,
        "task": "From mixture to supported identity"
      },
      {
        "group": "IDENT",
        "lesson": 4,
        "task": "Read analytical disagreement"
      },
      {
        "group": "IDENT",
        "lesson": 5,
        "task": "Resolve the ambiguous peak"
      }
    ]
  },
  {
    "title": "The Concentration Problem",
    "objective": "Produce concentration maps whose units, detection limits, and quality controls are explicit.",
    "briefing": "City leaders ask whether the contaminant is \"high,\" but samples differ in dilution, path length, and matrix interference. The team must turn signals into defensible concentrations. An incorrect concentration map can either close a safe water system or expose residents through a false reassurance.",
    "stake": "Day six, and this is where the utility director, Marisol Reyes, and her quality assurance lead, Rie Nakamura, stop agreeing. The results are back as numbers and the city is holding each one against a legal limit, one water system at a time. Nakamura wants every result re-run before anything reopens. Reyes points out that four systems are shut on numbers nobody has questioned, hospitals are on tankers, and a week of caution has a cost too — and today she is right. Today you turn readings into what was really in the river, decide whether one result can be trusted, and choose where to sample. Outside the calibrated range nobody has checked what the instrument does at all.",
    "takeaway": "Produce concentration maps whose units, detection limits, and quality controls are explicit.",
    "stops": [
      {
        "group": "QUANT",
        "lesson": 0,
        "task": "Undo the dilution"
      },
      {
        "group": "QUANT",
        "lesson": 1,
        "task": "Protect the calibration"
      },
      {
        "group": "QUANT",
        "lesson": 2,
        "task": "Map concentration with limited samples"
      }
    ]
  },
  {
    "title": "A Reaction Underground",
    "objective": "Estimate the maximum reaction scale and define measurements that verify whether the assumed chemistry is occurring.",
    "briefing": "Two drainage streams may mix in a confined tunnel. The player must determine limiting reactants, plausible products, and gas or heat generation before crews enter. Entering before bounding the chemistry could expose crews to heat, pressure, or oxygen displacement.",
    "stake": "Day eight. Two drains may be meeting in a closed tunnel under the yard and the confined-space safety officer, Femi Oyelaran, has a crew suited up at the hatch waiting on your word. He will not send them in on a story. Oyelaran has monitors at the hatch and two hours of bottled air per man. Today you work out the largest reaction that could be happening down there, and whether the reaction you assumed is the one really going on. What hurts people in a closed space is ordinary: heat, pressure, and oxygen pushed out.",
    "takeaway": "Estimate the maximum reaction scale and define measurements that verify whether the assumed chemistry is occurring.",
    "stops": [
      {
        "group": "ENERGY",
        "lesson": 0,
        "task": "From identity to reaction estimate"
      },
      {
        "group": "ENERGY",
        "lesson": 1,
        "task": "Which reactant limits?"
      },
      {
        "group": "ENERGY",
        "lesson": 2,
        "task": "Is the assumed reaction happening?"
      }
    ]
  },
  {
    "title": "The Heat Is Rising",
    "objective": "Create an energy balance and choose a monitoring plan that detects self-heating early.",
    "briefing": "A storage zone continues warming after the visible fire is out. The team must distinguish stored heat from ongoing exothermic reaction and estimate whether cooling can keep up. If self-heating is mistaken for leftover warmth, responders may leave before runaway conditions develop.",
    "stake": "Day nine, two o'clock in the morning. The fire has been out for eight days and one storage bay is still getting warmer. Tomas Brandt, who owns reactions and energy, has been reading it hourly since midnight and has eleven readings. Fire Command wants the site released tonight and the crews have been on shift for fourteen hours. Today you work out how much energy it takes to warm that much material, decide whether you are watching leftover heat or a reaction still running, and set up the monitoring either way. Fire Command wants your answer after the next reading, not after the trend.",
    "takeaway": "Create an energy balance and choose a monitoring plan that detects self-heating early.",
    "stops": [
      {
        "group": "ENERGY",
        "lesson": 3,
        "task": "How much energy raises the temperature?"
      },
      {
        "group": "ENERGY",
        "lesson": 4,
        "task": "Stored heat or continuing reaction?"
      },
      {
        "group": "ENERGY",
        "lesson": 5,
        "task": "Control the self-heating risk"
      }
    ]
  },
  {
    "title": "Will the Reaction Run Away?",
    "objective": "Identify the controlling rate factors and define a safe operating envelope with automatic shutdown triggers.",
    "briefing": "A treatment chemical reacts slowly at room temperature but rapidly as the vessel warms. The team must connect rate laws and activation energy to thermal feedback. A treatment intended to remove contamination could become the largest hazard on the site.",
    "stake": "Day eleven. The treatment chemical sat quietly in a drum all week; in Brandt's warm pilot vessel it is lively. His own trace shows an hour of very little and then a step. Osei plans to run it at full scale on Monday — the pilot vessel holds forty litres and the plant tank holds nine thousand. Today you decide what temperature range this process may run in, and what shuts it down without asking anybody. Treatment also gathers a spill spread thin across a yard into a single tank, and if that tank runs away, the whole of it leaves at once, hot.",
    "takeaway": "Identify the controlling rate factors and define a safe operating envelope with automatic shutdown triggers.",
    "stops": [
      {
        "group": "ENERGY",
        "lesson": 6,
        "task": "What changes the rate?"
      },
      {
        "group": "ENERGY",
        "lesson": 7,
        "task": "Build a runaway feedback loop"
      },
      {
        "group": "ENERGY",
        "lesson": 8,
        "task": "Define the safe operating envelope"
      }
    ]
  },
  {
    "title": "The Water Changes pH",
    "objective": "Select a controlled neutralization strategy and determine when buffer capacity will be exhausted.",
    "briefing": "The river intake becomes acidic, while one proposed treatment could overshoot into strongly basic conditions. The player must use acid-base equilibria and buffering to control pH without masking chemical risk. A pH correction can mobilize metals, damage infrastructure, or injure workers if the chemical context is ignored.",
    "stake": "Day fourteen. The intake has turned acidic and Reyes wants a neutralising dose this morning; Novák, who maintains the pipeline, wants to know what it will do to her mains before anybody doses anything. The titration Ferreira ran overnight is nearly flat for four millilitres and then turns over hard. Today you work out how much acid is really there, read what that curve says about this water, and pick a dose that will not overshoot. There is one dosing pump and no way to take a dose back out. Overshoot and metals come off the pipe walls. Novák's question is the right one.",
    "takeaway": "Select a controlled neutralization strategy and determine when buffer capacity will be exhausted.",
    "stops": [
      {
        "group": "WATER",
        "lesson": 3,
        "task": "How many moles of acid are present?"
      },
      {
        "group": "WATER",
        "lesson": 4,
        "task": "Read the titration curve"
      },
      {
        "group": "WATER",
        "lesson": 5,
        "task": "Control pH without overshoot"
      }
    ]
  },
  {
    "title": "Equilibrium in the Reservoir",
    "objective": "Predict how pH and ligands shift dissolved concentration and design monitoring for remobilization.",
    "briefing": "After pH adjustment, dissolved contaminant decreases but sediment concentrations rise. The team must determine whether precipitation and complexation have transferred rather than destroyed the hazard. An apparently clean reservoir can become contaminated again when chemistry or flow changes.",
    "stake": "Day twenty-three, and nine days have been clean. The dissolved amount is down, the amount in the sediment is up by about as much, and Elena Stavros, who will have to monitor it for a decade, is the only person in the room still asking about it — everybody else has moved on to the treatment plant. Today you predict where the contaminant goes the next time conditions move, and design monitoring that would catch it coming back. Nothing was destroyed by the correction. It was moved into a form that is not in the water today, and it is still in the reservoir. What tests that claim is a storm, a warm month, or the autumn week when the lake turns over.",
    "takeaway": "Predict how pH and ligands shift dissolved concentration and design monitoring for remobilization.",
    "stops": [
      {
        "group": "WATER",
        "lesson": 6,
        "task": "From condition change to new equilibrium"
      },
      {
        "group": "WATER",
        "lesson": 7,
        "task": "Interpret the shift"
      },
      {
        "group": "WATER",
        "lesson": 8,
        "task": "Manage the new contaminant reservoir"
      }
    ]
  },
  {
    "title": "The Corrosion Failure",
    "objective": "Identify the corrosion cell and choose controls that address both chemistry and electrical coupling.",
    "briefing": "Acidic water and dissimilar metals threaten the intake pipeline. The player must identify redox couples and stop a small leak from becoming a system-wide failure. A hidden localized failure could interrupt drinking water during the emergency.",
    "stake": "Day twenty-six. A section of the intake pipeline has failed and Novák is standing in the hole in Third Street. It is also the main your own team clamped an earth cable to a fortnight ago. That pipe carries the water a hundred and forty thousand people drink, and the city is already on its reserves. Today you find where the metal is being lost and why, work out how fast, and choose the protection. Speed decides your response: the same loss over ten years is maintenance, and over a fortnight it is a burst main.",
    "takeaway": "Identify the corrosion cell and choose controls that address both chemistry and electrical coupling.",
    "stops": [
      {
        "group": "TREAT",
        "lesson": 0,
        "task": "Find the anode and cathode"
      },
      {
        "group": "TREAT",
        "lesson": 1,
        "task": "How fast can material disappear?"
      },
      {
        "group": "TREAT",
        "lesson": 2,
        "task": "Protect the pipeline"
      }
    ]
  },
  {
    "title": "Remove It Without Making It Worse",
    "objective": "Choose a treatment train using contaminant removal, byproduct formation, waste fate, and operational reliability.",
    "briefing": "Three treatment methods can lower the target contaminant, but one creates a toxic byproduct and another shifts the contaminant into sludge. The player must compare complete chemical consequences. A rapid treatment can create a less visible but more persistent hazard.",
    "stake": "Day thirty-one. Osei's pilot treatment works — ninety-eight per cent of the compound you identified is gone by the outlet — and he wants to scale it this week. Nakamura points out that the panel it was tested against was written for that compound and nothing else. Today you work out what the treatment actually did: what it removed, what it made, and where the rest went. A test panel written for the original reports success either way, because it is not looking for what you made. The most stubborn hazard here could be one nobody has a test for.",
    "takeaway": "Choose a treatment train using contaminant removal, byproduct formation, waste fate, and operational reliability.",
    "stops": [
      {
        "group": "TREAT",
        "lesson": 3,
        "task": "What did the treatment actually do?"
      },
      {
        "group": "TREAT",
        "lesson": 4,
        "task": "Select a treatment train"
      },
      {
        "group": "TREAT",
        "lesson": 5,
        "task": "Choose the safest pilot program"
      }
    ]
  },
  {
    "title": "The Air Is Not Clear Yet",
    "objective": "Identify likely secondary products and update monitoring locations and times.",
    "briefing": "Sunlight and atmospheric oxidants transform remaining vapors into secondary products. The player must reason about radicals, reaction pathways, and changing exposure after the source is controlled. Residents may return after the primary plume clears while secondary pollutants are still forming.",
    "stake": "Day thirty-eight. The main plume cleared on Thursday and residents came home on Friday. Since then Varga's monitors climb every afternoon and drop overnight, and he has been ignored twice because the release is over. He has three fixed monitors, all of them on the yard fence, and one van. Today you work out what is forming out there and move the monitoring to where and when it could see it. Monitoring built for the release will keep reporting that the release is over, and it will be right. People are back in their houses with the windows open.",
    "takeaway": "Identify likely secondary products and update monitoring locations and times.",
    "stops": [
      {
        "group": "GASES",
        "lesson": 3,
        "task": "Build a secondary-pollutant pathway"
      },
      {
        "group": "GASES",
        "lesson": 4,
        "task": "Read the day-night pattern"
      },
      {
        "group": "GASES",
        "lesson": 5,
        "task": "Monitor the transformed plume"
      }
    ]
  },
  {
    "title": "Can the Water Be Released?",
    "objective": "Make a transparent release decision with conditional monitoring and explicit treatment of borderline results.",
    "briefing": "Treatment results cluster near the decision threshold. The player must account for uncertainty, detection limits, and sampling representativeness before reopening the water system. A premature release exposes the city; an unnecessary hold can deprive hospitals and homes of essential water.",
    "stake": "Day forty-five, and Nakamura gets her day. The verification results are in and one sits just under the limit — and it is the re-run of a sample whose first quality check failed. She has the instrument's own repeatability from forty duplicate runs and would like somebody to look at it. Reyes has schools and two hospitals on tankers and wants the release signed this morning. Today you decide: release, release with conditions, or hold. Nakamura's name is on that form under Reyes's. Both mistakes are real, and they are not the same size.",
    "takeaway": "Make a transparent release decision with conditional monitoring and explicit treatment of borderline results.",
    "stops": [
      {
        "group": "QUANT",
        "lesson": 3,
        "task": "A borderline result"
      },
      {
        "group": "QUANT",
        "lesson": 4,
        "task": "Close the verification gaps"
      },
      {
        "group": "QUANT",
        "lesson": 5,
        "task": "Approve, condition, or hold"
      }
    ]
  },
  {
    "title": "Reopen the City",
    "objective": "Deliver a claim-by-claim chemical evidence package and a long-term monitoring plan.",
    "briefing": "The final board must explain what was released, how chemicals moved and changed, which treatments worked, and what contamination remains in solids, infrastructure, and ecosystems. Without a complete fate and uncertainty record, the city cannot know whether the emergency is over or merely hidden.",
    "stake": "Day fifty-two. The mayor wants one word tonight and Mbeki has to put it on a screen behind him. Behind that word sits everything your teams have concluded in seven weeks, and those conclusions are not equally strong. Stavros wants the monitoring programme funded before the emergency budget closes on Friday; nobody else in the room has mentioned it. Today you take the claims one at a time — what was measured, what was worked out from it, what is still open — and decide what the city keeps paying for after everyone goes home. The sentence people quote back to you for years is usually the one you were least sure of.",
    "takeaway": "Deliver a claim-by-claim chemical evidence package and a long-term monitoring plan.",
    "stops": [
      {
        "group": "TREAT",
        "lesson": 6,
        "task": "Disposition the final chemical claims"
      },
      {
        "group": "TREAT",
        "lesson": 7,
        "task": "Build the public chemistry narrative"
      },
      {
        "group": "TREAT",
        "lesson": 8,
        "task": "Fund the chemical legacy"
      }
    ]
  }
];
