// copy.js — what each place says
// GENERATED by tools/import-book.mjs from qd-ligo.yml
// Hand edits are lost on the next import. Change the book.

export const COPY = {
  "OPTICS": "<p>The optics lab, first door on the west side. The beam splitter, the recycling cavities, and the two windows through which the arms leave the building at right angles to each other.</p>",
  "ISOL": "<p>The isolation bay, across the corridor. Suspension stacks on the floor, the noise budget drawn along the wall as one long curve, and several hundred auxiliary channels on a rack of screens.</p>",
  "CTRL": "<p>The control room, further down the east side. The strain channel across the top of the wall, the template bank beside it, and a telephone with the other site's number written on it.</p>",
  "PARAM": "<p>The parameter room at the far end of the west side. The waveform fitted through all three stages, a mass ledger on the whiteboard, and no instrument in the room at all.</p>",
  "PORCH": "<p>The entrance desk. A signing-in book, a rack of hard hats nobody wears indoors, and a screen showing how long both arms have been locked.</p>",
  "TEA": "<p>The coffee area halfway down the west side. A machine, six chairs, and the seismic trace from the ground outside printed out every hour.</p>",
  "DARK": "<p>The calibration bay, next to the isolation bay. The drive that shakes a mirror by a known amount, and the tables that turn a brightness into a length.</p>",
  "RACK": "<p>The store at the end of the west side. Spare suspension wires, optics in sealed cases, and the crate the last mirror came in.</p>",
  "LIB": "<p>The reading room at the far end. Preprints, the waveform catalogue, and the only quiet on a site whose whole purpose is quiet.</p>"
};
