// missions.js — the campaign, and why it takes each warm-up
// GENERATED by tools/import-book.mjs from deepwatch-hs.yml
// Hand edits are lost on the next import. Change the book.

export const MISSIONS = [
  {
    "title": "Boat Walkdown",
    "objective": "Learn the boat as a system of spaces, not a list of names.",
    "briefing": "You have the watch for the first time. Before anything else happens, you have to be able to find your way around this hull in the dark, and know what is in each space and how you would get out of it.",
    "stake": "Two hours to sailing, still alongside. The fire main shut-off valve in the forward compartment is chained shut. Nobody will say who chained it. Chief Ferro wants to walk you through the boat before your first watch tonight. This watch you learn the forward spaces by heart. You learn what the fittings on a bulkhead are for. You learn how to get from one end of the boat to the other without looking at anything. Ferro has a rule about that. A route learned as a set of steps survives being cut short. Tonight you may have to find that valve in the dark, in smoke, by feel.",
    "takeaway": "A compartment is defined by its boundaries, what it holds, and how you leave it.",
    "stops": [
      {
        "group": "DC",
        "lesson": 0,
        "task": "Learn a compartment in the order the facts depend on each other"
      },
      {
        "group": "ENG",
        "lesson": 0,
        "task": "Match each fitting to what it is there to do."
      },
      {
        "group": "NAV",
        "lesson": 0,
        "task": "Learn the compartment route, rebuild it without labels, then recover after one door is blocked."
      }
    ]
  },
  {
    "title": "Contact in the Noise",
    "objective": "Work out what is out there before the boat commits to anything.",
    "briefing": "Sonar has four sources on the display at once. Two of them have been there since before the boat slowed, one came with the turn, and one comes and goes. The captain wants to know which of them she has to care about.",
    "stake": "Second day out, forenoon watch. There are 4 traces on the broadband display. Petty Officer Nils Rask, the sonar supervisor, has been arguing with his own operator about the fourth one for 11 minutes. It holds almost the same bearing. It is getting louder. The captain, Commander Iris Vance, wants that trace named before the boat commits to the track she was ordered onto. This watch you sort out what is out there. You say what a steady bearing means. Sound is all you have. A bearing that does not change is not a quiet situation. It is the mark of two ships closing on each other.",
    "takeaway": "A bearing is a measurement; a track is an argument built from several of them.",
    "stops": [
      {
        "group": "SONAR",
        "lesson": 0,
        "task": "Match each trace to what is making it."
      },
      {
        "group": "SONAR",
        "lesson": 1,
        "task": "Which explanation fits every reading, not just the loudest one?"
      },
      {
        "group": "NAV",
        "lesson": 1,
        "task": "Turn the tonal into a wavelength"
      }
    ]
  },
  {
    "title": "Position Without a Trusted Fix",
    "objective": "Work out not where the boat is, but how well that is known.",
    "briefing": "The boat has been submerged for hours on dead reckoning. The plot is a confident-looking line drawn from course and speed, and it knows nothing about the water that has been setting the boat sideways the whole time. Ahead is a bank.",
    "stake": "Third day, middle watch. The last fix anybody trusts is three and a half hours old. Lieutenant Imani Sowande, the navigator, has built the plot from course, speed and time. Her assistant, Quartermaster Anya Petrov, has been reading the depth sounder. The two of them do not agree. There is a current here of about half a knot. Nobody has measured it today. This watch you work out how far the water has carried the boat. You pick which instrument to believe. You get a position that does not lean on the plot at all. Two displays fed by the same gyro will agree beautifully. That is Sowande's whole worry. 60 fathoms here, and a bank half a mile off the track.",
    "takeaway": "Precision is not accuracy, and two displays sharing a source are one measurement.",
    "stops": [
      {
        "group": "NAV",
        "lesson": 2,
        "task": "Age the position"
      },
      {
        "group": "NAV",
        "lesson": 3,
        "task": "Decide what the agreement between the two navigation displays is actually worth."
      },
      {
        "group": "SONAR",
        "lesson": 2,
        "task": "Derive the angle the sound cannot cross"
      }
    ]
  },
  {
    "title": "Silent Passage",
    "objective": "Cross a constrained area without losing contact awareness or making unnecessary noise.",
    "briefing": "The route ahead narrows between the bank and a shipping lane. Command wants the boat through it with contact held throughout and as little acoustic exposure as the plant allows.",
    "stake": "Fifth day, first watch. The narrows are 4 miles across. The passage takes 11 hours. The plot could be off by 2 miles in any direction. Lieutenant Commander Theo Whitfield, the executive officer, wants to wait for a better fix. Vance says waiting puts the boat in the middle of the strait at first light. That is worse than any argument about the plot, and this time she is right. This watch you decide what has to be true before the boat commits. You work out how much margin the passage really has. You also decide what Haruki can afford to shut down for Rask. What matters is how much water stays under the keel.",
    "takeaway": "Quiet costs capability, and the trade has to be made deliberately rather than by default.",
    "stops": [
      {
        "group": "SONAR",
        "lesson": 3,
        "task": "Order the passage"
      },
      {
        "group": "NAV",
        "lesson": 4,
        "task": "Work out how much sky the periscope can see"
      },
      {
        "group": "ENG",
        "lesson": 1,
        "task": "The hull rings at one shaft speed and nowhere else. Why that one?"
      }
    ]
  },
  {
    "title": "Forward Flooding",
    "objective": "Find the water, decide whether pumping can win, and stop the source.",
    "briefing": "The forward space is taking water. The drain pump is running and the level is still rising. Somewhere under those deck plates is a hole, and the boat is at 90 metres, which is what makes it a hole worth respecting.",
    "stake": "Sixth day, morning watch. Water is over the bilge in the forward space. The drain pump is running. Machinist's Mate Ruth Hallam, on the pumps, has the level and reports it steady. Ferro does not believe steady means anything. He is looking for the hole. This watch you find where the water is coming in. You work out whether pumping can win. You also work out what shutting that supply costs elsewhere. The two valves that stop it sit on a header that feeds other things. Pumping buys minutes. Those minutes are worth nothing unless somebody spends them finding the source.",
    "takeaway": "Flooding is stopped at the hull fitting; everything else is delay.",
    "stops": [
      {
        "group": "DC",
        "lesson": 1,
        "task": "Read the flows, decide which terms belong in the ledger, and close the water balance."
      },
      {
        "group": "DC",
        "lesson": 2,
        "task": "Estimate the pressure driving the seawater leak"
      },
      {
        "group": "ENG",
        "lesson": 2,
        "task": "Match each action to what it actually achieves."
      }
    ]
  },
  {
    "title": "Electrical Fire",
    "objective": "Put out a fire whose ignition source is electrical, in the order that makes it stay out.",
    "briefing": "Smoke in the electrical distribution space. The switchboard indicator says the affected bus is open, and the fire is behind a panel where nobody can see the seat of it.",
    "stake": "Same day, afternoon watch. Eight hours after the flooding, and nobody has slept. There is smoke from a switchboard in the electrical space. The indicator lamp shows the bus open. A meter on the cable inside reads 440 volts, and one of his own electrician's mates put it there. The chief electrician, Bede Okonkwo, will not send anybody in on the strength of a lamp. This watch you take the fire apart into the things keeping it alive. You decide what that meter is telling you. You work out how to fight a space nobody can see into. Here the order of your actions matters more than the speed of any one of them.",
    "takeaway": "An electrical fire is put out by de-energizing it; the agent only finishes the job.",
    "stops": [
      {
        "group": "FIRE",
        "lesson": 0,
        "task": "Match each leg of the fire to the action that removes it."
      },
      {
        "group": "FIRE",
        "lesson": 1,
        "task": "Predict the volt drop, then put a meter on it"
      },
      {
        "group": "ATMO",
        "lesson": 0,
        "task": "Set the insulation line before the next round of readings"
      }
    ]
  },
  {
    "title": "Atmosphere Degradation",
    "objective": "Tell a failing sensor from failing air, and find where the air stopped moving.",
    "briefing": "Two of the crew in berthing have headaches. The atmosphere plant says everything is normal. Both of those statements can be true at once, and working out how is the whole of this watch.",
    "stake": "Eighth day, middle watch. The scrubber plant is running and its outlet reads clean. Hospital Corpsman Elena Navarro has been round berthing with a handheld meter. Her reading is far higher than the sensor on that bulkhead. Nine people are asleep in there. Lieutenant Junior Grade Ana Lindqvist, the atmosphere control officer, has to decide whether to wake them. This watch you decide whether it is the air or the instrument that is wrong. You work out how long that space stays safe. You get the air moving again. This is the one system where the crew notice before the instruments do. Headaches. Short tempers. People asleep on watch. The crew have already noticed all three.",
    "takeaway": "A plant reading is a report about the plant, not about the compartment you are standing in.",
    "stops": [
      {
        "group": "ATMO",
        "lesson": 1,
        "task": "Which explanation accounts for every reading?"
      },
      {
        "group": "ATMO",
        "lesson": 2,
        "task": "Work out how much oxygen the space is actually holding"
      },
      {
        "group": "ENG",
        "lesson": 3,
        "task": "Work out where the mass spectrometer puts the ion"
      }
    ]
  },
  {
    "title": "Compound Casualty",
    "objective": "Prioritise and delegate when there are more casualties than there are people.",
    "briefing": "Flooding forward, a partial power loss, a degraded plot and one injured crewman, all inside four minutes. There are not enough people to do everything, so the first decision is which things do not get done yet.",
    "stake": "Ninth day, forenoon watch. Four things at once. Water forward. A bus lost aft. The plot gone bad from that power loss. And Machinist's Mate Tunde Adeyemi, the propulsion plant operator, with a broken wrist in the passage. Vance wants to hold the ordered speed. Whitfield says a boat with four casualties at eight knots, nine miles off a bank, is about to have five. This time he is the one who is right. This watch you decide what you keep and what you hand to somebody else. You also decide whether the boat slows down. Anything you hold yourself is a job nobody else is doing. Whitfield will not build the watch team for you.",
    "takeaway": "Command is deciding what you do, and who does the rest.",
    "stops": [
      {
        "group": "DC",
        "lesson": 3,
        "task": "Decide what is first"
      },
      {
        "group": "FIRE",
        "lesson": 2,
        "task": "Keep the one condition that cannot wait. Delegate every other problem with an owner, first action and return condition."
      },
      {
        "group": "NAV",
        "lesson": 5,
        "task": "Buy the time to think"
      }
    ]
  },
  {
    "title": "Sonar Blinded by the Boat",
    "objective": "Find the noise the boat is making about itself, and prove which machine it is.",
    "briefing": "Sonar has lost the picture. There is a broadband rise across every bearing and a new narrowband line, and the ocean has not changed. The problem is aboard, which makes it the engineers' problem and sonar's evidence.",
    "stake": "Eleventh day. The broadband noise floor is up on every bearing, not in 1 sector. Sonarman Kes Dunne, the broadband operator, has found a new narrowband line at 113 hertz. It grows with turns. Rask says the boat is shouting into its own array. Haruki says his plant is running just as it ran yesterday. This watch you decide whether the noise comes from outside the boat or from inside it. You narrow it down to one machine. You say what kind of fault makes a line like that. While the array is this bad, other boats can still hear this one. It cannot hear them.",
    "takeaway": "Own-ship noise is diagnosed by correlating what sonar hears with what the plant is doing.",
    "stops": [
      {
        "group": "SONAR",
        "lesson": 4,
        "task": "Close the energy ledger on the transducer bank"
      },
      {
        "group": "ENG",
        "lesson": 4,
        "task": "Change one machine at a time, listen to the line, then reverse the suspected change to confirm the cause."
      },
      {
        "group": "SONAR",
        "lesson": 5,
        "task": "Use the supplied values to estimate the contact’s line-of-sight speed."
      },
      {
        "group": "SONAR",
        "lesson": 6,
        "task": "Sort the night's contacts before the log goes up."
      }
    ]
  },
  {
    "title": "Uncontrolled Depth Change",
    "objective": "Tell a symptom from a cause when the boat is going somewhere you did not order.",
    "briefing": "The boat is heavier than it was an hour ago and it is going down. The depth gauge, the trim state and the planes all have something to say and only one of them is the cause.",
    "stake": "Twelfth day, middle watch. The boat is going deeper with the planes already at rise. The trim shows heavy forward. Speed has not changed. The depth gauge is the calmest instrument in the control room. Ferro is on his way forward without being asked, which tells you what he thinks it is. This watch you decide what is really causing it. You work out how much weight is aboard. You choose which control to use, knowing that two of the four are hard to undo at this depth. Treat the symptom and the boat keeps going down. Everybody will be watching the right gauge for the wrong reason.",
    "takeaway": "Depth is the outcome of weight, angle and speed, and each of those has its own cause.",
    "stops": [
      {
        "group": "NAV",
        "lesson": 6,
        "task": "Which cause accounts for every reading?"
      },
      {
        "group": "DC",
        "lesson": 4,
        "task": "Work out the work the air has to do"
      },
      {
        "group": "ENG",
        "lesson": 5,
        "task": "Predict the induced voltage, then measure it"
      },
      {
        "group": "ENG",
        "lesson": 6,
        "task": "Hold the trim while the boat works."
      }
    ]
  },
  {
    "title": "The Cooling Path",
    "objective": "Trace one cooling path end to end and find where it stopped.",
    "briefing": "Lube oil temperature is rising on the main bearing and nothing has changed on the throttle. Somewhere between the sea and that bearing there is a chain of things that carry heat away, and one of them is not.",
    "stake": "Thirteenth day. This one was bought two watches ago. A main bearing is running hot. The oil is hot. The fresh water loop is hot. The seawater leaving the heat exchanger is barely warmer than the seawater going in. The second cooling pump is still shut down from the quiet lineup Rask asked for. Its breaker is open at the switchboard, with nothing written in the log. This watch you write the cooling path down in order. Then you decide which link stopped handing the heat on. A bearing run hot for an hour is a bearing replaced in a shipyard.",
    "takeaway": "A cooling system is a chain, and a chain is diagnosed link by link.",
    "stops": [
      {
        "group": "ENG",
        "lesson": 7,
        "task": "Build the heat path in order, then name the link that governs how fast heat can leave the boat."
      },
      {
        "group": "ENG",
        "lesson": 8,
        "task": "Choose the fix that survives the fouling nobody measured"
      },
      {
        "group": "FIRE",
        "lesson": 3,
        "task": "Work out the heat the run is putting into the space"
      }
    ]
  },
  {
    "title": "Silent-Running Configuration",
    "objective": "Decide what may be secured, reduced or rescheduled while keeping the boat alive.",
    "briefing": "The boat has to be quiet for four hours. Everything aboard that makes noise also does something, and the ones that keep people breathing and bearings cool are not on the table.",
    "stake": "Fifteenth day. The argument that has run all patrol comes due. The boat needs four hours of quiet running. Haruki means to shut down everything on Rask's list to get it. That includes the second seawater pump and half the carbon dioxide scrubbing. Lindqvist has done the arithmetic on that second item and she is not happy. This watch you decide what may be shut down and what may only be slowed. You also say what the whole lineup costs the boat. Quiet is bought with capability. The bill arrives late, and in another department. None of it shows up on the same gauge as the choice.",
    "takeaway": "A silent lineup is a set of deadlines, not a set of switches.",
    "stops": [
      {
        "group": "ENG",
        "lesson": 9,
        "task": "Stress the plan by shrinking the time margin left before the six-hour passage ceiling, then choose the lineup that still works."
      },
      {
        "group": "ATMO",
        "lesson": 3,
        "task": "Put a deadline on the quiet"
      },
      {
        "group": "SONAR",
        "lesson": 7,
        "task": "Work out where the periscope forms its image"
      },
      {
        "group": "NAV",
        "lesson": 7,
        "task": "Work the contact board while the standing order changes."
      }
    ]
  },
  {
    "title": "Rig for Dive",
    "objective": "Prove the boat is ready before the last patrol, rather than assuming it.",
    "briefing": "The boat sails in an hour. Every check on the rig-for-dive list exists because somebody once did not do it, and each one proves a different thing.",
    "stake": "Nineteenth day. The boat has been open to the surface since Tuesday for work on the mast. She dives at dawn. The switchboard shows two breakers open from that work. The log says one of them was put back. Every valve on the rig sheet has a signature against it. One of those signatures belongs to a man who was ashore that morning. This watch you work out what each line of the checklist is really asking. You close the boat up in the right order. You decide what to do about a record that does not match. This is the cheapest hour of the patrol. It is also the last one before the sea decides.",
    "takeaway": "A check is a measurement that proves a specific claim, not a box beside a word.",
    "stops": [
      {
        "group": "DC",
        "lesson": 5,
        "task": "Choose which two signed claims to verify physically before the boat dives."
      },
      {
        "group": "ATMO",
        "lesson": 4,
        "task": "Line up the air before you need it"
      },
      {
        "group": "FIRE",
        "lesson": 4,
        "task": "Predict how long the bank stays dangerous, then time it"
      }
    ]
  },
  {
    "title": "Refit Decision",
    "objective": "Choose what to improve before the last patrol, on evidence rather than preference.",
    "briefing": "There is money and yard time for some of what the boat wants and not all of it. Every proposal has a cost, an uncertain benefit, and an effect on the patrol that follows.",
    "stake": "Twenty-first day. The refit list goes off the boat in tomorrow's message window. The yard will pay for one item. Haruki wants the cooling pump that has cost him two watches this patrol. Rask wants the mounts that would have kept the noise line out of his array. Lindqvist wants a second scrubber train. Whitfield wants to know which of the three the next patrol is most likely to need. This watch you decide. The evidence is dull. Which failures cost real time. Which ones are happening more often. What each fix would actually take away. Everyone in the room is arguing from memory, and nobody has opened the log.",
    "takeaway": "An upgrade is worth what it changes about the decisions you will actually face.",
    "stops": [
      {
        "group": "ENG",
        "lesson": 10,
        "task": "Spend two yard slots across four refits and make sure the plan answers the patrol’s required capability questions."
      },
      {
        "group": "SONAR",
        "lesson": 8,
        "task": "Use the supplied values, show the governing relationship, and give a sensible rounded result with units and interpretation."
      },
      {
        "group": "NAV",
        "lesson": 8,
        "task": "Work out whether the photocathode can see the wavelength at all"
      }
    ]
  },
  {
    "title": "Deep Watch",
    "objective": "Run the whole boat at once, with everything degraded a little and nothing decided for you.",
    "briefing": "An uncertain contact, a plot four hours old, water in the forward bilge, a scrubber train down and a bearing running warm. None of them is an emergency. Together they are the patrol.",
    "stake": "Twenty-second day, the last full watch of the patrol. Everything is a little degraded. There is a contact Rask has not sorted out. There is a plot Sowande has not been able to fix since the forenoon. There is a machine Haruki has not looked at since Tuesday. Whitfield is in the wardroom with the corpsman and a broken wrist of his own. So the officer you would have handed half of this to is not there. This watch you decide the order everything gets worked in. You do it while it is all still happening. Nobody will tell you which problem is the big one. Getting that order right is the job, and it is the only part you cannot hand away.",
    "takeaway": "Command is choosing which uncertainty you can live with, and saying so out loud.",
    "stops": [
      {
        "group": "NAV",
        "lesson": 9,
        "task": "Work out how much light the escape markers have left"
      },
      {
        "group": "DC",
        "lesson": 6,
        "task": "Match each item to the assignment that fits it."
      },
      {
        "group": "SONAR",
        "lesson": 9,
        "task": "Calculate the beat frequency from the two spectral lines."
      }
    ]
  }
];

export const WARMUPS = {
  "greet": {
    "title": "Nobody sails with people they have not met",
    "why": "You joined at the last port and the boat sailed the same night. Rask, the sonar supervisor, wants you known to every watch before the first drill, because in a compartment with the lights out a voice you recognise is worth more than a nameplate you cannot read. Get through the boat and put a name to most of the crew before the watch changes."
  },
  "trial-near": {
    "title": "Learn the boat before you need to move through it in the dark",
    "why": "One passage, nine compartments, and every bulkhead door a hatch you have to fold yourself through. Walk the whole length now, while the lights are on and nothing is wrong, because the next time you do this at speed it will be to a compartment that is filling and you will not be able to see the deck."
  },
  "follow": {
    "title": "The rounds, walked once by the man who has done them for eleven years",
    "why": "Petrov, the assistant navigator, does engineering rounds twice a watch and has never written them down. Stay with him. He stops at each machine long enough to listen to it, which is the part that cannot be written down, and he does not slow up for anybody. Get too close and you are standing between him and the thing he is listening to."
  },
  "hunt": {
    "title": "Six breathing sets, and the locker list says four",
    "item": {
      "name": "breathing set",
      "plural": "breathing sets"
    },
    "why": "Before the next drill every emergency breathing set has to be accounted for. Four are in the lockers where the list says. Two are not, because somebody moved them during the last maintenance period and told nobody. Find them, because a set nobody can locate is a set that does not exist when the compartment fills with smoke."
  },
  "canvass": {
    "title": "Who actually heard the pipe",
    "why": "The order was piped through the boat twenty minutes ago and the coxswain does not believe it reached everybody. Ask along the compartments until enough answers have come back to say whether the pipe failed or whether the people in the after compartments were simply too busy to acknowledge it."
  },
  "evade": {
    "title": "The chief wants a decision you are not ready to make",
    "why": "The chief has been looking for you since the watch turned over, wanting a verbal answer on the port motor that you have not got the readings for yet. Stay out of his way until the readings are in. An answer given in a passageway is an answer nobody can produce afterwards, and this boat runs on what is written in the log."
  },
  "tag": {
    "title": "Catch Rask before she goes into the control room",
    "why": "Rask, the sonar supervisor, has the sound survey from the last patrol, which is the only record of what this hull sounded like when it was quiet. Once she is in the control room and the brief has started she is unavailable for two hours, and the whole afternoon's work is a comparison against a survey you do not yet have a copy of."
  }
};
